### PR TITLE
Fix up .NET method invocation with Optional arg

### LINKED ISSUE #21372: F#-based library (Deedle) fails in PS
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm trying to use [Deedle](https://fslab.org/Deedle/) to work with various data

```powershell
install-package -Name deedle -scope CurrentUser

$fsharp = add-type -LiteralPath 'C:\Users\<someUser>\AppData\Local\PackageManagement\NuGet\Packages\FSharp.Core.8.0.200\lib\netstandard2.0\FSharp.Core.dll' -PassThru
$deedle = add-type -LiteralPath 'C:\Users\<someUser>\AppData\Local\PackageManagement\NuGet\Packages\Deedle.3.0.0\lib\netstandard2.0\Deedle.dll' -PassThru

[Deedle.Frame]::ReadCsv("C:\temp\charts\locations.csv")
```

### Expected behavior

```console
should not crash
```

### Actual behavior

```console
crashes as follows


OperationStopped: Expression of type 'System.Reflection.Missing' cannot be used for parameter of type 'System.Nullable`1[System.Boolean]' of method 'Deedle.Frame`2[System.Int32,System.String] ReadCsv(System.String, System.Nullable`1[System.Boolean], System.Nullable`1[System.Boolean], System.Nullable`1[System.Int32], System.String, System.String, System.String, System.Nullable`1[System.Int32], System.String[], Boolean)' (Parameter 'arguments[1]')
```

### Error details

```console
PS C:\temp> get-error

Exception             :
    Type       : System.ArgumentException
    Message    : Expression of type 'System.Reflection.Missing' cannot be used for parameter of type 'System.Nullable`1[System.Boolean]' of method 'Deedle.Frame`2[System.Int32,System.String] ReadCsv(System.String,
System.Nullable`1[System.Boolean], System.Nullable`1[System.Boolean], System.Nullable`1[System.Int32], System.String, System.String, System.String, System.Nullable`1[System.Int32], System.String[], Boolean)' (Parameter
'arguments[1]')
    ParamName  : arguments[1]
    TargetSite :
        Name          : ValidateOneArgument
        DeclaringType : System.Dynamic.Utils.ExpressionUtils, System.Linq.Expressions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
        MemberType    : Method
        Module        : System.Linq.Expressions.dll
    Data       : System.Collections.ListDictionaryInternal
    Source     : System.Linq.Expressions
    HResult    : -2147024809
    StackTrace :
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Dynamic.Utils.ExpressionUtils.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments, String methodParamName)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at System.Management.Automation.Language.PSInvokeMemberBinder.InvokeMethod(MethodBase mi, DynamicMetaObject target, DynamicMetaObject[] args, Boolean expandParameters, MethodInvocationType invocationType)
   at System.Management.Automation.Language.PSInvokeMemberBinder.InvokeDotNetMethod(CallInfo callInfo, String name, PSMethodInvocationConstraints psMethodInvocationConstraints, MethodInvocationType methodInvocationType,
DynamicMetaObject target, DynamicMetaObject[] args, BindingRestrictions restrictions, MethodInformation[] mi, Type errorExceptionType)
   at System.Management.Automation.Language.PSInvokeMemberBinder.FallbackInvokeMember(DynamicMetaObject target, DynamicMetaObject[] args, DynamicMetaObject errorSuggestion)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : OperationStopped: (:) [], ArgumentException
FullyQualifiedErrorId : System.ArgumentException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 4
    Line             : [Deedle.Frame]::ReadCsv("C:\temp\charts\locations.csv")
    Statement        : [Deedle.Frame]::ReadCsv("C:\temp\charts\locations.csv")
    PositionMessage  : At line:1 char:1
                       + [Deedle.Frame]::ReadCsv("C:\temp\charts\locations.csv")
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PS C:\temp> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

image

### PR DESCRIPTION
**Pull request by jborean93**
# PR Summary
Fix .NET method invocation with an argument that has an [Optional] attribute but no default value.

Fixes: https://github.com/PowerShell/PowerShell/issues/21372

## PR Context
While not common .NET has the ability to set an optional argument but no explicit value https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments#optional-arguments

> You can also declare optional parameters by using the .NET [OptionalAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.optionalattribute) class. OptionalAttribute parameters do not require a default value. However, if a default value is desired, take a look at [DefaultParameterValueAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.defaultparametervalueattribute) class.

The docs for F# even recommend this attribute when it comes to F# assemblies that could be used in C# and other .NET languages https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/parameters-and-arguments#optional-parameters

> For the purposes of C# and Visual Basic interop you can use the attributes [<Optional; DefaultParameterValue<(...)>] in F#, so that callers will see an argument as optional. This is equivalent to defining the argument as optional in C# as in MyMethod(int i = 3).

When it comes to the compiled assembly the `ParameterInfo.DefaultValue` for an argument with only `[Optional]` is [System.Reflection.Missing](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.missing?view=net-8.0) but this value cannot be passed as an argument unless the type is `object` because it cannot be casted to the argument type. Instead using `null` or the `default` value for that type should be used.

This is a good candidate to backport.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/engine/runtime/Binding/Binders.cs [hunk 1]
```diff
@@ -7167,6 +7167,13 @@ internal static Expression InvokeMethod(MethodBase mi, DynamicMetaObject target,
                     {
                         argExprs[i] = Expression.Default(parameterType);
                     }
+                    else if (!parameters[i].HasDefaultValue && parameterType != typeof(object) && argValue == Type.Missing)
+                    {
+                        // If the method contains just [Optional] without a default value set then we cannot use
+                        // Type.Missing as a placeholder. Instead we use the default value for that type. Only
+                        // exception to this rule is when the parameter type is object.
+                        argExprs[i] = Expression.Default(parameterType);
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/runtime/Binding/Binders.cs:7175]: Please reword the comment.
It seems your comment in the PR description is more clear about behavior with `object`
> When it comes to the compiled assembly the ParameterInfo.DefaultValue for an argument with only [Optional] is [System.Reflection.Missing](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.missing?view=net-8.0) but this value cannot be passed as an argument unless the type is object because it cannot be casted to the argument type. Instead using null or the default value for that type should be used.

Comment (jborean93) [reply src/System.Management.Automation/engine/runtime/Binding/Binders.cs:7229]: I've updated the comment, please let me know if there's any further improvements or clarifications it should have.

Comment (jborean93) [reply src/System.Management.Automation/engine/runtime/Binding/Binders.cs:7229]: Ah sorry, that last host I made this change on was set to format on save, will undo those.

Comment (jborean93) [reply src/System.Management.Automation/engine/runtime/Binding/Binders.cs:7175]: Done

**Review by iSazonov — APPROVED** [review]

**Comment by jborean93** [comment]
Thanks for the review @iSazonov

**Comment by SeeminglyScience** [comment]
The Engine WG discussed this and agree with the change and it is ready to be reviewed

**Comment by adityapatwardhan** [comment]
This is a new feature and hence does not meet the bar for backport. It is also in a fairly risky area.

**Review by daxian-dbw — APPROVED** [review]
