### PR TITLE
Separate DSC Configuration parser check for ARM processor

### LINKED ISSUE #18781: Misleading error message when parsing `Configuration` keyword on ARM processor
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When I work on PowerShell DSC files on an ARM-based Mac, the PowerShell extension for VS Code claims that I'm in constrained language mode and warns that I can't use the `Configuration` keyword.

To reproduce:
1. Use an ARM-based Mac.
2. Ensure Constrained Language Mode is disabled.
```powershell
PS> $ExecutionContext.SessionState.LanguageMode
FullLanguage
```
3. Parse a script containing the `Configuration` keyword.
```powershell
$errors = $null
[System.Management.Automation.PSParser]::Tokenize("Configuration MyConfig {}",[ref]$errors)
```
4. View the resulting errors.
```
PS> $errors

Token                                Message
-----                                -------
System.Management.Automation.PSToken Configuration keyword is not allowed in constrainedLanguage mode.
```

### Expected behavior

The `Configuration` keyword should be supported, or the error message should accurately state why it's not supported.

### Actual behavior

The error message claims constrainedLanguage mode is enabled, which isn't true.

I believe this is caused by this block of code, which checks that either:
1. ConstrainedLanguage mode is enabled, or
2. The processor type is ARM.

https://github.com/PowerShell/PowerShell/blob/c3a080caf9c46c2a742b032e4a85d05c21129fe4/src/System.Management.Automation/engine/parser/Parser.cs#L2987-L2995

It uses the same error message ("Configuration keyword is not allowed in constrainedLanguage mode.") even if the real issue is that I'm using an ARM processor.

### Error details

_No response_

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

From the Visual Studio Code PowerShell extension:
image

### PR DESCRIPTION
**Pull request by dkontyko**
# PR Summary

This PR fixes #18781 by creating a separate check for an ARM processor and corresponding error message when parsing a DSC Configuration node. 

## PR Context

As noted in the issue, writing a DSC configuration on an ARM-based Mac causes the VS Code PowerShell extension to display an error that Configuration is not supported in Constrained Language mode. This causes confusion when PowerShell is not actually in Constrained Language mode.  Separating the ARM check into its own block and adding an ARM-specific error message will improve user understanding of the actual error.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [X] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Review by SteveL-MSFT — APPROVED** [review]

File: src/System.Management.Automation/engine/parser/Parser.cs [hunk 1]
```diff
@@ -3004,6 +3004,16 @@ private StatementAst ConfigurationStatementRule(IEnumerable<AttributeAst> custom
                         dropIntoDebugger: true);
                 }
 
+                // Configuration is not supported on ARM64
+                if (PsUtils.IsRunningOnProcessorArchitectureARM())
+                {
+                    ReportError(configurationToken.Extent,
```
Comment (SteveL-MSFT) [inline src/System.Management.Automation/engine/parser/Parser.cs:3010]: Can you fix the formatting here to comply with CodeFactor?

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]

File: src/System.Management.Automation/engine/parser/Parser.cs (hunk 1 above)
Comment (dkontyko) [reply src/System.Management.Automation/engine/parser/Parser.cs]: Fixed.

**Review by SteveL-MSFT — APPROVED** [review]

**Review by anmenaga — APPROVED** [review]
