### PR TITLE
Fix PSMethodInvocationConstraints.GetHashCode method

### LINKED ISSUE #24964: Bad hash code calculation in `PSMethodInvocationConstraints` results in explosion of static cache
The hash code calculation in `PSMethodInvocationConstraints` only counts in the array members but not their elements, so the returned hash code would be different for two `PSMethodInvocationConstraints` instances that hold exactly the same elements in their array members.

The hash code of `PSMethodInvocationConstraints` is used by the static cache `PSInvokeMemberBinder.s_binderCache` because `PSMethodInvocationConstraints` is a member of the key for that cache, so you end up with every request being a cache miss in `PSInvokeMemberBinder.s_binderCache`.

https://github.com/PowerShell/PowerShell/blob/8f1d1115f28f652248ca23295041938e6ed3d2a1/src/System.Management.Automation/engine/MshMemberInfo.cs#L2012

### PR DESCRIPTION
**Pull request by crazyjncsu**
# PR Summary

Fix #24964

## PR Context

The issue comes from #12412. The bottom line is that we need to calculate the hash for _all array members_, not for the _array object itself_.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
  - [x] None
  - **OR**
  - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
    - [ ] Experimental feature name(s): 
- **User-facing changes**
  - [x] Not Applicable
  - **OR**
  - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
  - [x] N/A or can only be tested interactively
  - **OR**
  - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
  - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
  - **OR**
  - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
    - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
      - [ ] Issue filed: 
    - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
      - [ ] Issue filed: 
    - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
      - [ ] Issue filed: 
    - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
      - [ ] Issue filed:

### CODE REVIEW

**Comment by crazyjncsu** [comment]
fixes #24965

File: src/System.Management.Automation/engine/MshMemberInfo.cs [hunk 1]
```diff
@@ -2009,7 +2009,7 @@ public override bool Equals(object obj)
         }
 
         public override int GetHashCode()
-            => HashCode.Combine(MethodTargetType, ParameterTypes, GenericTypeParameters);
+            => HashCode.Combine(MethodTargetType, ParameterTypes.SequenceGetHashCode(), GenericTypeParameters.SequenceGetHashCode());
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/MshMemberInfo.cs:2012]: The change add nothing - HashCode.Combine() internally evaluate hashes for every parameter and for array it is array.GetHashCode(). So we have no need to use custom SequenceGetHashCode() method.

Comment (crazyjncsu) [reply src/System.Management.Automation/engine/MshMemberInfo.cs:2012]: But the implementation of “array.GetHashCode()” will return a different value for two different arrays with identical elements, no?  Don’t we want to hash on the basis of the elements?

`[“boo”].GetHashCode() != [“boo”]GetHashCode()`

https://dotnetfiddle.net/8cJ2w9

Comment (crazyjncsu) [reply src/System.Management.Automation/engine/MshMemberInfo.cs:2012]: Btw I'm not at all beholden to the implementation in the submitted fix. Because it generates a hash code itself to pass into a method that expects an object to be hashed.

I've implemented a HashCode class myself similar to yours but included methods for AddElements(ICollection<T>) to make it easier to deal with collection elements.

Also have recently realized that Array is IStructuralEquatable, so when using array as a tuple element for a dictionary key, I'd wrap in a class like this:

```
    class StructuralEquatableWrapper(IStructuralEquatable target)
    {
      public IStructuralEquatable Target => target;
      public override int GetHashCode() => target.GetHashCode(EqualityComparer<object>.Default);
      public override bool Equals(object? obj) => obj is StructuralEquatableWrapper wrapper && target.Equals(wrapper.Target, EqualityComparer<object>.Default);
    }
```

But I do maintain the issue is in urgent need of a fix.

Comment (iSazonov) [reply src/System.Management.Automation/engine/MshMemberInfo.cs:2012]: @crazyjncsu Thanks for clarify! I see it is a tricky bug coming from #12412 - hash for array vs hash for array members.

I agree that it is easily fix reverting to `SequenceGetHashCode()`.

**Comment by daxian-dbw** [comment]
@crazyjncsu Thank you for reporting this issue!
I think we should either revert the change back to the [original hash code calculation](https://github.com/PowerShell/PowerShell/pull/12412/files#diff-0ddb35aa9c54dfe72659129d2153e6d838772a153c9c12aced85a33e7d6d9b1bL1997-R2014) with the addition of `ParameterTypes.SequenceGetHashCode()`, or use `HashCode.Add` to include all elements of `ParameterTypes` and `GenericTypeParameters` to the hash code calculation.

**Comment by crazyjncsu** [comment]
Looks great for my purposes ;)

**Comment by iSazonov** [comment]
@daxian-dbw Could you please explain why we cannot use HashCode.Combine() as @crazyjncsu proposed? I think old custom algorithm is not best choice. Or you are thinking about performance?

File: src/System.Management.Automation/engine/MshMemberInfo.cs [hunk 2]
```diff
@@ -2009,7 +2009,19 @@ public override bool Equals(object obj)
...
+            unchecked
+            {
+                int result = 61;
+
+                result = result * 397 + (MethodTargetType != null ? MethodTargetType.GetHashCode() : 0);
+                result = result * 397 + ParameterTypes.SequenceGetHashCode();
+                result = result * 397 + GenericTypeParameters.SequenceGetHashCode();
+
+                return result;
+            }
```
Comment (SeeminglyScience) [inline src/System.Management.Automation/engine/MshMemberInfo.cs:2023]: I would go with this since it seems to be the preferred API now. But I also don't know enough about the specifics of hashcodes to know why one is or isn't better (partially why I'd personally stick to the API that does it "properly" for you)

```suggestion
            HashCode hashCode = new();
            hashCode.Add(MethodTargetType);
            if (ParameterTypes is not null)
            {
                foreach (Type parameterType in ParameterTypes)
                {
                    hashCode.Add(parameterType);
                }
            }
            else
            {
                hashCode.Add(0);
            }
            
            if (GenericTypeParameters is null)
            {
                hashCode.Add(0);
                return hashCode.ToHashCode();
            }
            
            foreach (Type genericParameter in GenericTypeParameters)
            {
                hashCode.Add(genericParameter);
            }
            
            return hashCode.ToHashCode();
```

**Comment by daxian-dbw** [comment]
My bad. I missed the fact that `GetHashCode()` on an integer will simply return the integer value itself.
So `HashCode.Combine(MethodTargetType, ParameterTypes.SequenceGetHashCode(), GenericTypeParameters.SequenceGetHashCode())` should work as expected.

File: src/System.Management.Automation/engine/MshMemberInfo.cs (hunk 2 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/MshMemberInfo.cs]: > but Int32.GetHashCode() simply returns the integer itself

Also given this, I guess we now can replace the utility method `Utils.CombineHashCodes` in PowerShell with `HashCode.Combine`.

**Review by daxian-dbw — APPROVED** [review]

File: src/System.Management.Automation/engine/MshMemberInfo.cs (hunk 2 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/MshMemberInfo.cs]: > But I also don't know enough about the specifics of hashcodes to know why one is or isn't better (partially why I'd personally stick to the API that does it "properly" for you)

1. Less collisions.
2. Random seed per process (protects against cache attacks).

**Comment by iSazonov** [comment]
@crazyjncsu Thanks for you contribution!

----

@ArmaanMcleod Have you an interest to migrate the method to new HashCode.Add() API?

**Comment by TravisEz13** [comment]
@PowerShell/powershell-maintainers  triage decision - wait until more data from a 7.5 release
