### PR TITLE
Break action preference

### LINKED ISSUE #9474: PS should reset $? to the value it had when it entered the debugger
While a debugger is meant to allow you to modify variables, and otherwise debug and tinker with a program, the `$?` variable is a special case and its value should be preserved unless it is explicitly modified with an assignment command because PowerShell itself modifies that variable with any successful command that is invoked.

# Steps to reproduce

```powershell
Push-Location -LiteralPath $env:USERPROFILE
[Environment]::CurrentDirectory = $env:USERPROFILE
${FileSystem::.\test.ps1} = @'
Get-Process -id 12345678
if (-not $?) {
    'The value of $? was preserved during debugging.'
} else {
    'The value of $? was changed to $true during debugging.'
}
'@
$bp = Set-PSBreakPoint -Script .\test.ps1 -Line 2
& .\test.ps1
Remove-PSBreakpoint -Breakpoint $bp
Remove-Item .\test.ps1
Pop-Location
```

At this point you will be in the debugger on the breakpoint. Invoke the following command:

```PowerShell
$?
```

You'll see that `$?` has a value of `$false`; however, since you invoked a command that was successful (i.e. that returned an exit code of 0), `$?` is now set to true. Invoke `c` to continue the script to allow it to run to completion.

# Expected behavior

The script outputs the following statement:

```none
The value of $? was preserved during debugging.
```

# Actual behavior

The script outputs the following statement:

```none
The value of $? was changed to $true during debugging.
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by KirkMunro**
## PR Summary

Added `ActionPreference.Break`. This new ActionPreference value allows for scripters to break into the debugger anytime a message is to be sent to a stream. It can be used for specific commands via the `-ErrorAction` or `-WarningAction` common parameters, or across scripts using one of the preference variables (`$DebugPreference`, `$ErrorActionPreference`, `$InformationPreference`, `$ProgressPreference`, `$VerbosePreference`, or `$WarningPreference`).

When a record for one of these message types is raised, if the corresponding preference variable is set to `ActionPreference.Break`, PowerShell will immediately enter the debugger and add the appropriate message record to the $PSDebugContext variable in the new Trigger property.

These changes also include the following:

1. Updated Wait-Debugger so that it now enters the debugger on the Wait-Debugger command, rather than on the command following Wait-Debugger (which confuses users, especially if the next command is not in the same scope). This was necessary so that all commands to enter the debugger without a breakpoint use the same code. As a side benefit, the new UX is much more intuitive, and you can now enter the debugger using Wait-Debugger even if it is the last/only command in your script.
1. Fix #9474.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [X] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [X] Issue filed - Issue link: [#4283](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/4283)
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by rkeithhill** [comment]
Interesting idea but I would have expected this functionality to be part of `Set-PSBreakpoint`.  Perhaps a new parameter with a `-StreamWrite` parameter that takes an enum that identifies each stream.  Not sure how useful the Output stream would be to break on as it would probably hit that breakpoint a lot.  :-)

**Comment by KirkMunro** [comment]
@rkeithhill That approach would be more complicated to implement. We already have a framework for message processing with ActionPreference variables and the common -ErrorAction and -WarningAction parameters. This is just additional message processing that extends that framework. It fits quite naturally into what is already there, and is intended to supercede ActionPreference.Inquire. Plus for the most common use case, entering the debugger on error, possibly for a specific command that is deep in a call stack, you can either use -ErrorAction Break at the top level or set -ErrorAction on the specific command where you want to break using $PSDefaultParameterValues. No new breakpoint types were required, and based on personal experience evangelizing the debugger to the community and gathering feedback from the community, I think this approach will get much more use than a new Set-PSBreakpoint parameter set would. It's much more visual and easier to digest for scripters.

**Comment by KirkMunro** [comment]
Tracing isn't really an advantage in the case of stream messages though, is it? Messages provide that naturally (they are messages sent through a stream, after all). Also, with so many scripters who don't use the debugger, the simple UX that this provides feels like a win to me. But you're right, you don't get conditional breakpointing with this approach.

I was looking at this again this morning, and could add a new type of breakpoint so that either `Set-PSBreakpoint` or the new `ActionPreference.Break` value could be used to trigger breakpoints, with the former creating an explicit breakpoint which could be conditional, and the latter creating a non-conditional, implicit breakpoint that only exists during the invocation, if that approach is preferred.

**Comment by KirkMunro** [comment]
@PaulHigin Even though this is only marked WIP for now (mostly because I want to make sure I have adequate test coverage once this is all hashed out), I'd really like your thoughts on what I've done here so far.

File: src/System.Management.Automation/engine/debugger/debugger.cs [hunk 1]
```diff
@@ -644,6 +652,27 @@ public virtual void SetDebuggerStepMode(bool enabled)
 
         #region Internal Methods
 
+        /// <summary>
+        /// Breaks into the debugger.
+        /// </summary>
+        /// <param name="triggerObject">The object that triggered the breakpoint, if there is one.</param>
+        internal virtual void Break(object triggerObject = null)
+        {
+            if (!IsDebugHandlerSubscribed &&
```
Comment (PaulHigin) [inline src/System.Management.Automation/engine/debugger/debugger.cs]: This implementation code should go into the ScriptDebugger class below, since it applies only there.  This should throw "not implemented" exception.

File: src/System.Management.Automation/engine/debugger/debugger.cs [hunk 2]
```diff
@@ -2415,6 +2444,24 @@ public override void SetDebuggerStepMode(bool enabled)
...
 
+        /// <summary>
+        /// Breaks into the debugger.
+        /// </summary>
+        /// <param name="triggerObject">The object that triggered the breakpoint, if there is one.</param>
+        internal override void Break(object triggerObject = null)
+        {
+            base.Break(triggerObject);
+
+            // If the debugger is running and we are not in a breakpoint, trigger an immediate break in the current location
```
Comment (PaulHigin) [inline src/System.Management.Automation/engine/debugger/debugger.cs]: // If the debugger is **enabled** and we are not...

File: src/System.Management.Automation/engine/debugger/debugger.cs [hunk 3]
```diff
@@ -2415,6 +2444,24 @@ public override void SetDebuggerStepMode(bool enabled)
...
+            using (IEnumerator<CallStackFrame> enumerator = GetCallStack().GetEnumerator())
+            {
+                if (enumerator.MoveNext() && _context._debuggingMode > 0)
+                {
+                    OnSequencePointHit(enumerator.Current.FunctionContext);
```
Comment (PaulHigin) [inline src/System.Management.Automation/engine/debugger/debugger.cs]: This is interesting, but seems like it should work.  Much better than waiting until next sequence point!

**Review by PaulHigin — CHANGES_REQUESTED** [review]
Overall I like this a lot.  Please be sure to test with remote debugging, debugging runspaces (nested), job debugging, etc. We have tests for this, but they haven't been ported yet because they are c# tests requiring "friend" test assemblies. But we should add test hooks at some point.  For the short term, manual testing is probably Ok.

**Comment by PaulHigin** [comment]
Regarding ActionPreference versus new breakpoint type, I think I prefer the current ActionPreference.  This is different than breakpoints, more like Wait-Debugger, and I feel adding a new breakpoint type that really isn't a breakpoint could be confusing. OTOH it would be nice to also include a "break on exception (terminating error)", and I am not sure how that would be set ... breakpoint type or new built-in variable. It is worth thinking about and discussing.

**Comment by iSazonov** [comment]
At first look users can understand that `ActionPreference.Break`  breaks/exits the script. What about `ActionPreference.BreakToDebugger`, `ActionPreference.JumpToDebugger`, or `ActionPreference.Debug`?

If I remember right there is a problem with propagating the preference variables ($DebugPreference, $ErrorActionPreference, $InformationPreference, $ProgressPreference, $VerbosePreference,  $WarningPreference) to local and module scopes. This may somehow affect this enhancement.

**Comment by KirkMunro** [comment]
@iSazonov Regarding the suggestion for `ActionPreference.Debug`, I was originally debating between that and Break, but decided Debug wasn't appropriate because it could easily be confused with `-Debug` or `$DebugPreference`, which are entirely different.

I also thought about the possible confusion between `Break` and the `break` statement, but felt that wasn't an issue because we also have `ActionPreference.Continue`, which could be confused with the `continue` statement, but they are entirely different from one another. Users need to understand that these `ActionPreference` values are about actions taken by the engine during the execution of a script, controlling how messages are handled, and not the same thing as keywords used for flow control within a loop in a script.

**Comment by vexx32** [comment]
@KirkMunro My understanding of it is that pref variables (`$ErrorActionPreference` etc) are not correctly passed between modules.

For example:

  * You write module A which calls `Remove-Item` (which is part of one of the default modules).
  * You load both modules and set `$ErrorActionPreference = 'Continue'`
  * You then try to call a command from module A with preference variable set

**Result:** module A sees the value you set, but `Remove-Item` will *not* see the variable.

However, it is my understanding that it manages to work correctly when (in the above example) calling a command from module A with `-ErrorActionPreference` *parameter*.

**Comment by iSazonov** [comment]
@vexx32 Thanks! You are right.
@KirkMunro Thanks for clarify. It'll be useful for PowerShell Committee considerations. 
The issue about preference variables is #4568 .

File: src/System.Management.Automation/engine/debugger/debugger.cs (hunk 1 above)
Comment (KirkMunro) [reply src/System.Management.Automation/engine/debugger/debugger.cs]: Fixed, thanks.

File: src/System.Management.Automation/engine/debugger/debugger.cs (hunk 2 above)
Comment (KirkMunro) [reply src/System.Management.Automation/engine/debugger/debugger.cs]: Fixed, thanks.

File: src/System.Management.Automation/engine/debugger/debugger.cs (hunk 3 above)
Comment (KirkMunro) [reply src/System.Management.Automation/engine/debugger/debugger.cs]: Thanks! It works great in my tests so far!

**Comment by joeyaiello** [comment]
@PowerShell/powershell-committee summary:

@KirkMunro could you elaborate more on your reasoning for not adding this functionality to `ActionPreference.Inquire`? (Overall, we agree that this is useful behavior, and some kind of method on `ActionPreference` is the right approach.)

Given a concern about the proliferation of trivial type accelerators, instead of adding a new accelerator, we should just fix our tab completion to complete the same way that parameters like `-ErrorAction` complete. (Unless there's another reason for that change that we're missing?)

As for the `Wait-Debugger` change, everyone is in favor. 😊

**Comment by KirkMunro** [comment]
Great questions @joeyaiello. Answers below.

1. `ActionPreference.Break` is explicit. It allows scripts to tell PowerShell they want to enter the debugger under certain conditions, just like they can by setting up breakpoints. `ActionPreference.Inquire` is a prompt for the end user, to which they would have to provide a reply, and then debug, when they could simply choose to continue execution when they enter the debugger if they don't want to debug at that point. If they're unsure, they need to be in the debugger anyway to look around, view where they are in the script, etc., so it made much more sense to me to simply bring users into the debugger by providing them with an explicit choice they make at execution time rather than asking them during the running of a script. Also, since PowerShell had a debugger added to it in v2, I can't think of one person who uses or promotes the use of `ActionPreference.Inquire`. If someone else gave me break functionality behind the question generated by `ActionPreference.Inquire`, I would be inclined to add `ActionPreference.Break` anyway. Last, there is PR #8195, which removes the only built-in use of `ActionPreference.Inquire` that I know of in PowerShell, so that option feels pretty legacy at this point. All of that said, if the PowerShell team would like `ActionPreference.Inquire` to have a Break option in place of the option to Enter a nested prompt, I wouldn't be opposed to adding it to at least make it an option for folks who might want such functionality.

1. So you're suggesting have tab completion work for variable assignment like it does for parameter values, such that a user could type in `$ErrorActionPreference = '<tab>`, and be presented with the values they can use? Yeah, ok, that could work. I still think it's useful to learn/understand the type behind the `*Preference` variables though, and as far as script readability/scanning goes, `$ErrorActionPreference = [ActionPreference]::Break` is a better way to write scripts IMHO than `$ErrorActionPreference = 'Break'`. Just give me a using command to identify the namespaces I want to use in place of additional type accelerators, that would make me happier. :) That said, if you folks don't want the accelerator, I can take it out. I really think it is much easier to identify in scripts though, and helps users learn what is really happening much more than assigning those values to a string.

1. I know, right? I was really happy to work that one out.

**Comment by KirkMunro** [comment]
One more thought regarding the "proliferation of trivial type accelerators": what if PowerShell automatically worked as if you had invoked the equivalent of this at the top of every script/script module:

```PowerShell
using namespace System.Management.Automation
using namespace System.Management.Automation.Language
using namespace System.Management.Automation.Runspaces
```

I think that, plus type acceleration for aliases/shorthand type names and outliers that are in namespaces from which you only care about a few types, would make working with the .NET side of PowerShell much easier. Is there a downside to automatically using some core namespaces that are among the most frequently used in PowerShell?

**Comment by vexx32** [comment]
That should probably be discussed in a new issue, @KirkMunro... but I don't think that would be overly terrible to have work. As you say, many of those types would be extremely helpful to have readily available. 😄

**Comment by SteveL-MSFT** [comment]
@KirkMunro `using namespace` is a good option to make scripts a bit more readable, but can affect runtime performance during discovery of types so we wouldn't want to include the SMA namespaces by default.  One of the things we discussed that could help in the future is allowing `using system.management.automation.actionpreference as actionpreference` to get custom type accelerators within your script.

**Comment by KirkMunro** [comment]
This is not abandoned. It's just a busy time of year for everyone involved.

@joeyaiello: I'm waiting on feedback/comments from you in response to my reply to your questions.

**Comment by joeyaiello** [comment]
Hey @KirkMunro, sorry, I was just the messenger for the @PowerShell/powershell-committee. Unfortunately, we've been light on meetings as folks have been out for the holidays. Might have to pick this one back up after the new year (in particular, I think @JamesWTruher and @BrucePay cared deeply about the behavior).

**Comment by KirkMunro** [comment]
Ok, thanks @joeyaiello. I wasn't trying to be impatient, just saw GitHub marked the PR as stale and wanted to make sure it was still moving forward.

**Comment by iSazonov** [comment]
Do we want to lost the PR?

**Review by PaulHigin — APPROVED** [review]
LGTM

**Comment by daxian-dbw** [comment]
@KirkMunro Is this PR still WIP? If it's ready, I would like @JamesWTruher to review this.

**Comment by KirkMunro** [comment]
@daxian-dbw Sorry for delay, I'm coming out of being sick (had pneumonia), and tidying up some old PRs to drive them to closure. This is the current one I'm reviewing to ensure it is ready for review.

**Comment by daxian-dbw** [comment]
@KirkMunro I'm sorry to hear that and hope you are feeling much better now. No rush, please take your time. Thanks!

**Comment by KirkMunro** [comment]
@daxian-dbw This is good to go. All of my tests (which are manual) pass with the code as is just fine.

While testing, I uncovered a few bugs that are not the result of this PR (they exist in PowerShell Core 6.2) that I'll mention here (tracking them for now, issues to be opened later):

1. When you detach the debugger from a job, you are returned to a prompt that renders with an extra ">". This is presumably because the prompt function runs before the detach has fully completed, and at that time the system thinks it's still in a nested prompt.
1. When you detach the debugger from a job, you return to your original session; however, the running job does not enter an AtBreakpoint state when it encounters the Wait-Debugger command (or now -ErrorAction Break). Instead, it just continues to run. I believe this is a bug, and the job should still stop at any breakpoints it encounters and wait for the debugger. @PaulHigin: Thoughts on this one?

Also, I considered putting together some automated testing via a hook into the debugger, but felt I might be reinventing some of what you have internally already in the classes that @PaulHigin talked about above, so I just stuck with manual testing to make sure that everything worked as expected.

**Comment by daxian-dbw** [comment]
Thanks @KirkMunro!
@PaulHigin Can you please comment on the two issues @KirkMunro mentioned above? Also, could you please review this PR again as it has been quite a while and there are new changes pushed? Thanks!
@JamesWTruher Can you please also review this PR to make sure the UX behavior is what you expect?

**Comment by daxian-dbw** [comment]
@KirkMunro By the way, can you please include a few sample scripts in the PR description (with annotations maybe) as examples to show the UX behavior? That would be very helpful too. Thanks!

**Comment by PaulHigin** [comment]
I agree about the >> prompt, but am not too concerned since hitting 'Enter' redraws the prompt correctly.
I agree the Debug-Job, 'detach' command should allow another debugger attach wait, and that it is a bug. 

Thanks.

**Comment by KirkMunro** [comment]
For sample scripts used when debugging jobs, have a look at scripts 2, 3, and 7, [here](https://github.com/KirkMunro/debugging-powershell-session). They need a little modification (pay attention to the paths they expect or modify them to use their own paths). I added `Get-ChildItem .\doesnotexist -ErrorAction break` to script 2 to make sure that worked as expected.

**Comment by KirkMunro** [comment]
@daxian-dbw @PaulHigin @JamesWTruher Related to this PR, I have an important question. It was really bugging me during testing this that `-ErrorAction Break` wouldn't cause PowerShell to enter the debugger immediately when an exception was raised. It's one of those things that felt like I would have to explain around as a shortcoming when talking about this feature.

To avoid having to dance around a functionality gap if I'm demoing this to someone, this afternoon/evening, I decided I wanted to see if I could resolve that as well, such that `-ErrorAction Break` would enter the debugger if any of the following occurred:

1. Invocation of the `throw` statement.
1. Invocation of Write-Error.
1. Invocation of $PSCmdlet.ThrowTerminatingError
1. An exception from the parser (e.g. gps -foo bar).
1. A runtime exception (e.g. 1/0).

I've managed to get this working by making a very small addition to `MshCommandRuntime.ThrowTerminatingError` as well as to `ExceptionHandlingOps.CheckActionPreference`. The code added simply checks the error action preference, and if it is set to break, it enters the debugger, setting `PSDebugContext.TriggerObject` to the exception that was raised.

I really feel this should be part of this PR. Since we're early in the 7.0 cycle, it feels like a good time to make this addition. Do any of y'all object to me committing these additional changes and increasing the scope of this PR to what I really wanted it to be in the first place?

**Comment by KirkMunro** [comment]
You know what, rather than wait for a response I just committed those changes. Using them locally, it is just the right thing to do and makes this PR so much better.

**Review by PaulHigin — APPROVED** [review]
This looks good to me.  The only question I have is whether MshCommandRuntime and MiscOps are the right places to handle terminating errors.  @lzybkr can you comment?

The other question I have is how well this works over remote debugging.  The TargetObject is part of the DebugContext object and I don't know if it will appear since serialization is limited to two levels by default.  But it is something we can experiment with.

**Comment by lzybkr** [comment]
Just today I reviewed a fix where a script expected `-ErrorAction` to do something with terminating errors. Today it consistently does not. `-ErrorAction Break` would change that for a specific preference and this seems like it will lead to even more confusion.

**Comment by KirkMunro** [comment]
@lzybkr: To restate what I think you just said, you are concerned that having `-ErrorAction Break` enter a breakpoint for both terminating and non-terminating errors may lead to confusion because of cases where `-ErrorAction` does not behave the same between terminating and non-terminating errors with other values such as `SilentlyContinue`. Is this what you meant? Can you identify the specific script or scenario that you're referring to?

**Comment by lzybkr** [comment]
You understand correctly.

The script I'm referring to is internal, but used `-ErrorAction SilentlyContinue -ErrorVariable blah` when it should have used `try/catch`.

**Comment by KirkMunro** [comment]
I'm OK with the difference between `SilentlyContinue` and `Break`. Since PowerShell v1, both terminating and non-terminating errors have been stored in the `$Error` variable. From that perspective, `-ErrorAction Break` entering the debugger for both terminating and non-terminating errors seems like the expected behavior.

Similarly, when you use `-ErrorAction Inquire`, whether you encounter a terminating error or a non-terminating error, you get prompted for the action you would like to take. This makes both `Inquire` and `Break` consistent with one another. Other `ActionPreference` values of `Continue`, `SilentlyContinue`, and `Ignore` apply to the handling of non-terminating errors, `Stop` makes a non-terminating error become terminating, and try/catch applies to the handling of terminating errors (exceptions).

I think all of this is easily explainable in documentation.

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs [hunk 4]
```diff
@@ -1610,6 +1610,13 @@ internal static void CheckActionPreference(FunctionContext funcContext, Exceptio
                 preference = ExceptionHandlingOps.QueryForAction(rte, rte.Message, context);
             }
 
+            // if the error action preference is set to break, then break
+            // immediately into the debugger
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: Could you please explain what tool you use for 80 column auto word wrapping and why? It seems that for modern displays 120-140 width is very good. (We could adjust config files in our repo)

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs [hunk 5]
```diff
@@ -1610,6 +1619,13 @@ internal static void CheckActionPreference(FunctionContext funcContext, Exceptio
...
+            if (preference == ActionPreference.Break)
+            {
+                funcContext._executionContext?.Debugger?.Break(rte);
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]:
```suggestion
                context.Debugger?.Break(rte);
```

File: src/System.Management.Automation/engine/MshCommandRuntime.cs [hunk 6]
```diff
@@ -2051,6 +2086,14 @@ public void ThrowTerminatingError(ErrorRecord errorRecord)
 
             CmdletInvocationException e =
                 new CmdletInvocationException(errorRecord);
+
+            // If the error action preference is set to break, break immediately
+            // into the debugger
+            if (ErrorAction == ActionPreference.Break)
+            {
+                Context?.Debugger?.Break(e.InnerException ?? e);
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/MshCommandRuntime.cs]:
```suggestion
                Context.Debugger?.Break(e.InnerException ?? e);
```

**Comment by lzybkr** [comment]
I'd always assumed break on error would be implemented via `Set-PSBreakPoint` which would handle any exception thrown - from methods, cmdlets, or ordinary functions.

`-ErrorAction Break` won't support methods or non-cmdlet binding functions, so you'd have to set `$ErrorActionPreference`?

I don't see approval from the committee on this, and honestly it feels like there should be an RFC or a tracking issue - I think many people don't look at PRs for feature level discussions.

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs (hunk 4 above)
Comment (KirkMunro) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: I don't use a tool for auto-word wrapping of comments. I just inspected the wrapping that I already saw in the files/projects I was working in, and eyeballed it, making my comments wrap the same way. Working with so many different projects over the years, I've become accustomed to following whatever style is already in place, so that the file/project is consistent. If we want comment wrapping to be at a certain column width instead, I'm happy to switch to whatever we want to use.

**Comment by KirkMunro** [comment]
@lzybkr: [Committee approval](https://github.com/PowerShell/PowerShell/pull/8205#issuecomment-454982713)

**Comment by KirkMunro** [comment]
Also @lzybkr, one more thought behind where I was coming from with this approach. The vast majority of the PowerShell community does not use the debugger. I believe `-ErrorAction Break` and `$ErrorActionPreference = [actionpreference]::Break` offer a lower barrier to entry and are easier concepts to grasp for users who traditionally would avoid anything to do with a debugger.

A workflow such as:

1. Run script or function.
1. Encounter an error.
1. Run script or function again with `-ea Break`, or set `$ErrorActionPreference = 'Break'` and then re-run your script or function.

is conceptually easier than:

1. Run script or function.
1. Encounter an error.
1. Use `Set-PSBreakpoint` to configure a breakpoint so that when you run your script again you stop on the error.
1. Run script or function again.

**Comment by lzybkr** [comment]
I'm not convinced that people don't use the debugger (VSCode? ISE?) or that ErrorActionPreference.Break is conceptually simpler, but that doesn't matter for my concerns.

Documentation won't easily solve the issue around ErrorActionPreference for non-terminating errors. There is a ton of experience out there today and this will just muddy the waters. People will get the wrong idea and expect `-ErrorAction <anything>` to apply to terminating errors.

Possibly just as bad - I don't see how this would work in scripts that set `$ErrorActionPreference`, or how it would work across modules. And when it doesn't work, people will learn to distrust the debugger.

I feel like the @PowerShell/powershell-committee spent too little time thinking about this - I'd expect to see some more rationale behind their thinking and why `Set-PSBreakpoint` was rejected.

**Comment by KirkMunro** [comment]
> I'm not convinced that people don't use the debugger (VSCode? ISE?)

Just to give some context, that comes after presenting sessions on PowerShell debugging over several years to people who are intermediate to advanced in PowerShell, and learning through questions and discussion with the attendees how few of them actually use the debugger. People use the editors, and either don't debug, or inject statements to see how far they get in a script, etc. -- debugging is a scary concept for non-developers to consider.

> People will get the wrong idea and expect -ErrorAction <anything> to apply to terminating errors.

Has `ErrorAction.Inquire` caused people to get the wrong idea? Because it applies to terminating errors, and has been around since v1.

> I don't see how this would work in scripts that set $ErrorActionPreference, or how it would work across modules

You're right, there is a challenge with the current approach for this PR when used with one module that invokes an advanced function in another because of #4568. I just added a note to that issue because it really needs some attention/thought, rather than dragging on for years.

> I feel like the @PowerShell/powershell-committee spent too little time thinking about this - I'd expect to see some more rationale behind their thinking and why Set-PSBreakpoint was rejected.

Fair enough. As noted above, I took this approach because `Set-PSBreakpoint` didn't seem like the right approach to me at the time (thinking of the breakpoint as more virtual -- who knows when/where an error will occur, terminating or not). I've tried thinking about how `Set-PSBreakpoint` could make sense with command breakpoints conditional on the command raising an error, but that still feels really weird because it doesn't break on the command, but instead on the error that occurs. Plus the current approach supports breaking on more than just errors -- it works for warnings, verbose messages, debug messages, progress messages, etc. (minus when it doesn't because of #4568).

**Comment by PaulHigin** [comment]
FWIW I am leaning toward Kirk in that this is an overall good use of action preference.  It is opt-in and deliberate so I feel there is no real chance that live script will unaccountably break into the debugger and appear hung.  But instead will help developers track down difficult error paths.  I think it is a good start and something we can experiment with and refine as needed.

**Comment by lzybkr** [comment]
> Has ErrorAction.Inquire caused people to get the wrong idea? Because it applies to terminating errors, and has been around since v1.

We don't have telemetry, but I'm guessing `Inquire` is used infrequently because it is not automation friendly. And it's kinda weird and not too useful IMO.

> You're right, there is a challenge with the current approach for this PR when used with one module that invokes an advanced function in another because of #4568. I just added a note to that issue because it really needs some attention/thought, rather than dragging on for years.

It's not just across modules. Scripts/functions set `$errorActionPreference` locally.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this again.  We believe that `Break` is similar to `Inquire` and thus acceptable for handling terminating and non-terminating errors.  If there was a formal proposal for how this would be in `Set-PSBreakPoint`, we would review it, but we also don't believe there is an issue with `Break` action co-existing with `Set-PSBreakPoint`.  We discussed relationship with [`-OnError {}`](https://github.com/PowerShell/PowerShell/issues/6010) and the two makes sense to co-exist as `Break` is mostly for interactive use while `-OnError` would be for automation.

**Comment by KirkMunro** [comment]
Thanks @SteveL-MSFT.

Also FYI for anyone testing this manually, I recently ran into one minor issue that I'm still trying to work out. When I use a terminating error in a function inside of try/catch(throw) block and invoke that function with `-ErrorAction Break`, the debugger shows the current line as the throw statement inside of the catch instead of as the line where the error actually occurs. I think I know how to resolve that one properly, but I'm still working on it.

**Comment by KirkMunro** [comment]
The bug I ran into (breaking on error thrown from within a try/catch statement) is fixed, and I resolved a similar bug with traps that is also fixed. I feel this is solid now, but since it needs to be manually tested I'm really happy to have other eyes on it to make sure their experience is the same.

Here are some of the more recent functions I've been running (plus additional permutations and combinations of them):

```PowerShell
# Testing without try/catches or trap
function test-1 {
    [cmdletbinding()]
    param()
    gps -id 12345678
    1/0
    'Hello' # This will run
}

# Testing with nested try/catches and rethrow
function test-2 {
    [cmdletbinding()]
    param()
    try {
        try {
            gps -id 12345678
            1/0
            'Hello' # This should never run
        } catch {
            throw
        }
    } catch {
        throw $_
    }
}

# Testing with trap
function test-3 {
    [cmdletbinding()]
    param()
    trap {
        throw $_
    }
    gps -id 12345678
    1/0
    'Hello' # This should never run
}

# Testing with trap and try/catch
function test-4 {
    [cmdletbinding()]
    param()
    trap {
        throw $_
    }
    try {
        gps -id 12345678
        1/0
        'Hello' # This should never run
    } catch {
        throw
    }
}
```

If you run any of those with `-ea break`, with the latest update they work exactly as I expect them to.

**Comment by KirkMunro** [comment]
FYI, working on fixes for the Pester tests that fail.

**Comment by KirkMunro** [comment]
To fix the broken Pester tests and maintain performance in the `ExceptionHandlingOps.CheckActionPreference` static method, I needed to refactor some of the logic used to check if an `ActionPreference` variable value is `Ignore`, and as a result of that refactoring I fixed one of the issues identified in #4348.

Prior to this change, if you had any `ActionPreference` variable (e.g. ErrorActionPreference, DebugPreference, etc.) that was not of type `ActionPreference`, you could use a string value of `'Ignore'` and avoid the check that tries unsuccessfully to prevent that. With this change, because I broke some logic up into new methods, the check now picks up on `ActionPreference` variable values of `'Ignore'` (e.g. string values) as well.

*NOTE:* This could be seen as a breaking change for any users who are setting `$ErrorActionPreference` (or any of the other preference variables) with a string value of `'Ignore'` (see that linked bug for details). IMHO, the right solution here is to just resolve #4348 by removing the `Ignore` checks entirely and leave that to a linter, logging a bug for the PSSA team to add a rule for that. If you don't want that as a solution, I'll have to undo a small part of what I just did (but the code will be messier as a result).

**Comment by KirkMunro** [comment]
And...case in point: the new Pester test failures fail because the `./test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1` file assigns a value of `'Ignore'` to the `$InformationPreference` variable. 😆

That's more argument for what was proposed in #4348, I guess.

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs [hunk 7]
```diff
@@ -1603,33 +1603,38 @@ internal static void CheckActionPreference(FunctionContext funcContext, Exceptio
...
+            ActionPreference preference = ExceptionHandlingOps.QueryForAction(rte, rte.Message, context);
 
-            if (!anyTrapHandlers && !ExceptionHandlingOps.NeedToQueryForActionPreference(rte, context))
+            // if the exception is new (i.e. it was not rethrown from a naked throw
+            // statement inside of a catch block, and it is not currently being
+            // handled by the system), and if ErrorActionPreference is set to break,
+            // then break immediately into the debugger.
+            if (!rte.WasRethrown &&
+                context.CurrentExceptionBeingHandled == null &&
+                preference == ActionPreference.Break)
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: It seems the comment above adds nothing useful - we see directly the same in the code.
I'd remove the dummy comment.

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs [hunk 8]
```diff
@@ -1603,33 +1603,38 @@ internal static void CheckActionPreference(FunctionContext funcContext, Exceptio
...
             {
-                throw rte;
+                context.Debugger?.Break(rte);
+
+                // set the value of $? here in case it was reset in the debugger.
+                context.QuestionMarkVariableValue = false;
             }
 
-            ActionPreference preference;
+            bool anyTrapHandlers = funcContext._traps.Any() && funcContext._traps.Last().Item2 != null;
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: Can we avoid LINQ?
What is "Item2" here?

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs (hunk 7 above)
Comment (KirkMunro) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: I think there is value in clearly identifying what makes an exception "new" to this block of code; however, I can remove it and create an `IsExceptionNew` method to keep that detail in the code itself.

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs (hunk 8 above)
Comment (KirkMunro) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: No idea what Item2 is. That was existing code that I just moved. I'll have to take a closer look, and see if LINQ can be removed as well.

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs (hunk 7 above)
Comment (KirkMunro) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: Fixed.

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs (hunk 8 above)
Comment (KirkMunro) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: Removed this use of LINQ and added comment describing what Item2 is.

**Comment by KirkMunro** [comment]
Here's an additional test I thought to check earlier today that works:

```PowerShell
function Test-DBHidden {
    [System.Diagnostics.DebuggerHidden()]
    [CmdletBinding()]
    param()
    1/0 # We shouldn't be able to break here with -ErrorAction Break
}
Test-DBHidden -ErrorAction Break
```

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs [hunk 9]
```diff
@@ -1595,25 +1604,40 @@ internal static void CheckActionPreference(FunctionContext funcContext, Exceptio
             // set $? to false indicating an error
             context.QuestionMarkVariableValue = false;
 
-            bool anyTrapHandlers = funcContext._traps.Any() && funcContext._traps.Last().Item2 != null;
+            ActionPreference preference = GetErrorActionPreference(context);
 
-            if (!anyTrapHandlers && !ExceptionHandlingOps.NeedToQueryForActionPreference(rte, context))
+            if (IsExceptionNew(rte, context) &&
```
Comment (PaulHigin) [inline src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: `IsExceptionNew` helper method is not needed since it is a simple comparison and only used once.

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs [hunk 10]
```diff
@@ -1595,25 +1604,40 @@ internal static void CheckActionPreference(FunctionContext funcContext, Exceptio
...
             }
-            else
+            else if (ExceptionCannotBeStoppedContinuedOrIgnored(rte, context))
             {
-                preference = ExceptionHandlingOps.QueryForAction(rte, rte.Message, context);
+                throw rte;
+            }
+            else if (preference == ActionPreference.Inquire && !rte.SuppressPromptInInterpreter)
+            {
+                preference = InquireForActionPreference(rte.Message, context);
```
Comment (PaulHigin) [inline src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: It looks like `QuestionMarkVariableValue` is not being set here.  Should it be?

**Review by PaulHigin — CHANGES_REQUESTED** [review]

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs (hunk 10 above)
Comment (KirkMunro) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: Yes, it should be. Good catch.

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs (hunk 9 above)
Comment (KirkMunro) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: Funny, I added IsExceptionNew because @iSazonov felt the comment I had was unnecessary in a previous code review, and I wanted other devs reading the code to understand that the comparison was used to check if the exception was new. I prefer the inline comparison with the comment though, so I'm putting that back (although I've worded the comment differently).

File: src/System.Management.Automation/engine/debugger/debugger.cs [hunk 11]
```diff
@@ -2436,6 +2450,36 @@ public override void SetDebuggerStepMode(bool enabled)
...
+            }
+
+            // Store the triggerObject so that we can add it to PSDebugContext
+            TriggerObject = triggerObject;
+
+            // Set debugger to step mode so that a break can occur.
+            SetDebuggerStepMode(true);
+
+            // If the debugger is enabled and we are not in a breakpoint, trigger an immediate break in the current location
+            using (IEnumerator<CallStackFrame> enumerator = GetCallStack().GetEnumerator())
```
[the remark this answers is not in the document]
Comment (KirkMunro) [reply src/System.Management.Automation/engine/debugger/debugger.cs]: Good idea. Done.

File: src/System.Management.Automation/engine/ExecutionContext.cs [hunk 12]
```diff
@@ -568,29 +568,51 @@ internal void SetVariable(VariablePath path, object newValue)
...
+        internal bool IsBreakOnErrorEnabled()
         {
+            // Unlike the GetEnumPreference method, which can throw an exception, this
+            // method  is used to specifically check if ErrorActionPreference is set to
+            // ActionPreference.Break so that it can 
             CmdletProviderContext context = null;
             SessionStateScope scope = null;
-            object val = EngineSessionState.GetVariableValue(preferenceVariablePath, out context, out scope);
-            if (val is T)
+            object val = EngineSessionState.GetVariableValue(SpecialVariables.ErrorActionPreferenceVarPath, out context, out scope);
```
[the remark this answers is not in the document]
Comment (KirkMunro) [reply src/System.Management.Automation/engine/ExecutionContext.cs]: No longer applicable since the method is being removed for the very reason you identify why it is no longer needed. It's not used, and I just forgot to remove it. Thanks again. :)

**Comment by daxian-dbw** [comment]
Reassign this PR to@TravisEz13 as I will be OOF for a few days.

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs (hunk 10 above)
Comment (KirkMunro) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: FYI, this is fixed @PaulHigin.

**Comment by PoshChan** [comment]
@KirkMunro, your last commit had 3 failures in `PowerShell-CI-windows`
Tests for (error, warning, etc) action preference.ErrorAction = Suspend does not work on functions
```powershell
Expected an exception, with FullyQualifiedErrorId 'ParameterBindingFailed,MyHelperFunction' to be thrown, but the FullyQualifiedErrorId was 'CannotConvertArgumentNoMessage,MyHelperFunction'. from D:\a\1\s\test\powershell\Language\Scripting\ActionPreference.Tests.ps1:86 char:45
    +             { MyHelperFunction -ErrorAction Suspend } | Should -Throw ...
    +                                             ~~~~~~~
at <ScriptBlock>, D:\a\1\s\test\powershell\Language\Scripting\ActionPreference.Tests.ps1: line 86
86:             { MyHelperFunction -ErrorAction Suspend } | Should -Throw -ErrorId "ParameterBindingFailed,MyHelperFunction"
```
Tests for (error, warning, etc) action preference.ErrorAction = Suspend does not work on cmdlets
```powershell
Expected an exception, with FullyQualifiedErrorId 'ParameterBindingFailed,Microsoft.PowerShell.Commands.GetProcessCommand' to be thrown, but the FullyQualifiedErrorId was 'CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.GetProcessCommand'. from D:\a\1\s\test\powershell\Language\Scripting\ActionPreference.Tests.ps1:90 char:40
    +             { Get-Process -ErrorAction Suspend } | Should -Throw -Err ...
    +                                        ~~~~~~~
at <ScriptBlock>, D:\a\1\s\test\powershell\Language\Scripting\ActionPreference.Tests.ps1: line 90
90:             { Get-Process -ErrorAction Suspend } | Should -Throw -ErrorId "ParameterBindingFailed,Microsoft.PowerShell.Commands.GetProcessCommand"
```
Tests for (error, warning, etc) action preference.WarningAction = Suspend does not work
```powershell
Expected an exception, with FullyQualifiedErrorId 'ParameterBindingFailed,Microsoft.PowerShell.Commands.GetProcessCommand' to be thrown, but the FullyQualifiedErrorId was 'CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.GetProcessCommand'. from D:\a\1\s\test\powershell\Language\Scripting\ActionPreference.Tests.ps1:94 char:42
    +             { Get-Process -WarningAction Suspend } | Should -Throw -E ...
    +                                          ~~~~~~~
at <ScriptBlock>, D:\a\1\s\test\powershell\Language\Scripting\ActionPreference.Tests.ps1: line 94
94:             { Get-Process -WarningAction Suspend } | Should -Throw -ErrorId "ParameterBindingFailed,Microsoft.PowerShell.Commands.GetProcessCommand"
```

**Comment by PoshChan** [comment]
@KirkMunro, your last commit had 3 failures in `PowerShell-CI-macos`
Tests for (error, warning, etc) action preference.ErrorAction = Suspend does not work on functions
```powershell
Expected an exception, with FullyQualifiedErrorId 'ParameterBindingFailed,MyHelperFunction' to be thrown, but the FullyQualifiedErrorId was 'CannotConvertArgumentNoMessage,MyHelperFunction'. from /Users/vsts/agent/2.150.3/work/1/s/test/powershell/Language/Scripting/ActionPreference.Tests.ps1:86 char:45
    +             { MyHelperFunction -ErrorAction Suspend } | Should -Throw ...
    +                                             ~~~~~~~
at <ScriptBlock>, /Users/vsts/agent/2.150.3/work/1/s/test/powershell/Language/Scripting/ActionPreference.Tests.ps1: line 86
86:             { MyHelperFunction -ErrorAction Suspend } | Should -Throw -ErrorId "ParameterBindingFailed,MyHelperFunction"
```
Tests for (error, warning, etc) action preference.ErrorAction = Suspend does not work on cmdlets
```powershell
Expected an exception, with FullyQualifiedErrorId 'ParameterBindingFailed,Microsoft.PowerShell.Commands.GetProcessCommand' to be thrown, but the FullyQualifiedErrorId was 'CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.GetProcessCommand'. from /Users/vsts/agent/2.150.3/work/1/s/test/powershell/Language/Scripting/ActionPreference.Tests.ps1:90 char:40
    +             { Get-Process -ErrorAction Suspend } | Should -Throw -Err ...
    +                                        ~~~~~~~
at <ScriptBlock>, /Users/vsts/agent/2.150.3/work/1/s/test/powershell/Language/Scripting/ActionPreference.Tests.ps1: line 90
90:             { Get-Process -ErrorAction Suspend } | Should -Throw -ErrorId "ParameterBindingFailed,Microsoft.PowerShell.Commands.GetProcessCommand"
```
Tests for (error, warning, etc) action preference.WarningAction = Suspend does not work
```powershell
Expected an exception, with FullyQualifiedErrorId 'ParameterBindingFailed,Microsoft.PowerShell.Commands.GetProcessCommand' to be thrown, but the FullyQualifiedErrorId was 'CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.GetProcessCommand'. from /Users/vsts/agent/2.150.3/work/1/s/test/powershell/Language/Scripting/ActionPreference.Tests.ps1:94 char:42
    +             { Get-Process -WarningAction Suspend } | Should -Throw -E ...
    +                                          ~~~~~~~
at <ScriptBlock>, /Users/vsts/agent/2.150.3/work/1/s/test/powershell/Language/Scripting/ActionPreference.Tests.ps1: line 94
94:             { Get-Process -WarningAction Suspend } | Should -Throw -ErrorId "ParameterBindingFailed,Microsoft.PowerShell.Commands.GetProcessCommand"
```

**Comment by PoshChan** [comment]
@KirkMunro, your last commit had 3 failures in `PowerShell-CI-linux`
Tests for (error, warning, etc) action preference.ErrorAction = Suspend does not work on functions
```powershell
Expected an exception, with FullyQualifiedErrorId 'ParameterBindingFailed,MyHelperFunction' to be thrown, but the FullyQualifiedErrorId was 'CannotConvertArgumentNoMessage,MyHelperFunction'. from /home/vsts/work/1/s/test/powershell/Language/Scripting/ActionPreference.Tests.ps1:86 char:45
    +             { MyHelperFunction -ErrorAction Suspend } | Should -Throw ...
    +                                             ~~~~~~~
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Language/Scripting/ActionPreference.Tests.ps1: line 86
86:             { MyHelperFunction -ErrorAction Suspend } | Should -Throw -ErrorId "ParameterBindingFailed,MyHelperFunction"
```
Tests for (error, warning, etc) action preference.ErrorAction = Suspend does not work on cmdlets
```powershell
Expected an exception, with FullyQualifiedErrorId 'ParameterBindingFailed,Microsoft.PowerShell.Commands.GetProcessCommand' to be thrown, but the FullyQualifiedErrorId was 'CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.GetProcessCommand'. from /home/vsts/work/1/s/test/powershell/Language/Scripting/ActionPreference.Tests.ps1:90 char:40
    +             { Get-Process -ErrorAction Suspend } | Should -Throw -Err ...
    +                                        ~~~~~~~
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Language/Scripting/ActionPreference.Tests.ps1: line 90
90:             { Get-Process -ErrorAction Suspend } | Should -Throw -ErrorId "ParameterBindingFailed,Microsoft.PowerShell.Commands.GetProcessCommand"
```
Tests for (error, warning, etc) action preference.WarningAction = Suspend does not work
```powershell
Expected an exception, with FullyQualifiedErrorId 'ParameterBindingFailed,Microsoft.PowerShell.Commands.GetProcessCommand' to be thrown, but the FullyQualifiedErrorId was 'CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.GetProcessCommand'. from /home/vsts/work/1/s/test/powershell/Language/Scripting/ActionPreference.Tests.ps1:94 char:42
    +             { Get-Process -WarningAction Suspend } | Should -Throw -E ...
    +                                          ~~~~~~~
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Language/Scripting/ActionPreference.Tests.ps1: line 94
94:             { Get-Process -WarningAction Suspend } | Should -Throw -ErrorId "ParameterBindingFailed,Microsoft.PowerShell.Commands.GetProcessCommand"
```

**Review by PaulHigin — APPROVED** [review]

**Comment by KirkMunro** [comment]
@daxian-dbw How is the manual testing going on this PR? Are there additional reviews outstanding? I'd love to see the review process finalized and this merged so that I could work on related changes/fixes in other separate PRs. I keep periodically merging the latest from master into this PR (just did this again) so that it remains ready for merge.

**Comment by TravisEz13** [comment]
I think we are waiting on this testing:  https://github.com/PowerShell/PowerShell/pull/8205#pullrequestreview-173223481

I don't think we have anyone signed up to do this testing.

**Comment by KirkMunro** [comment]
Thanks @TravisEz13. I know @daxian-dbw requested @JamesWTruher do a review of this PR [a while back](https://github.com/PowerShell/PowerShell/pull/8205#issuecomment-481809344), and was curious if he made any progress on that.

File: src/System.Management.Automation/engine/parser/Position.cs [hunk 13]
```diff
@@ -145,9 +145,9 @@ internal static string VerboseMessage(IScriptExtent position)
             if (!string.IsNullOrEmpty(sourceLine))
             {
                 int spacesBeforeError = position.StartColumnNumber - 1;
-                int errorLength = (position.StartLineNumber == position.EndLineNumber)
+                int errorLength = (position.StartLineNumber == position.EndLineNumber && position.EndColumnNumber <= sourceLine.Length + 1)
                                       ? position.EndColumnNumber - position.StartColumnNumber
-                                      : sourceLine.TrimEnd().Length - position.StartColumnNumber + 1;
+                                      : sourceLine.Length - position.StartColumnNumber + 1;
```
Comment (JamesWTruher) [inline src/System.Management.Automation/engine/parser/Position.cs]: Do you know what was the original thought behind the addition of `TrimEnd`?

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs [hunk 14]
```diff
@@ -1595,25 +1604,47 @@ internal static void CheckActionPreference(FunctionContext funcContext, Exceptio
...
                 preference = ProcessTraps(funcContext, rte);
+
+                // set the value of $? here in case it was reset in trap handling.
+                context.QuestionMarkVariableValue = false;
             }
-            else
+            else if (ExceptionCannotBeStoppedContinuedOrIgnored(rte, context))
             {
-                preference = ExceptionHandlingOps.QueryForAction(rte, rte.Message, context);
+                throw rte;
```
Comment (JamesWTruher) [inline src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: will `$?` get set as a result of this throw, or does that need to be done explicitly.

File: test/powershell/Language/Scripting/ActionPreference.Tests.ps1 [hunk 15]
```diff
@@ -33,22 +33,23 @@ Describe "Tests for (error, warning, etc) action preference" -Tags "CI" {
...
 
-        It 'action preference of Ignore cannot be set as a preference variable' {
-            $e = {
-                $GLOBAL:errorActionPreference = "Ignore"
-                Get-Process -Name asdfasdfasdf
-            } | Should -Throw -ErrorId 'System.NotSupportedException,Microsoft.PowerShell.Commands.GetProcessCommand' -PassThru
-            $e.CategoryInfo.Reason | Should -BeExactly 'NotSupportedException'
+        It 'action preference of Ignore can be set as a preference variable using a string value' {
+            Remove-Variable -Name ErrorActionPreference -Scope Global -Force
+            $GLOBAL:errorActionPreference = "Ignore"
```
Comment (JamesWTruher) [inline test/powershell/Language/Scripting/ActionPreference.Tests.ps1]: while unlikely, it's possible that the setting could leak, I'd be happier if this was in a `try { } finally { }`

File: test/powershell/Language/Scripting/ActionPreference.Tests.ps1 [hunk 16]
```diff
@@ -60,42 +61,7 @@ Describe "Tests for (error, warning, etc) action preference" -Tags "CI" {
             $error.Count | Should -BeExactly $errorCount
         }
```
Comment (JamesWTruher) [inline test/powershell/Language/Scripting/ActionPreference.Tests.ps1]: is there a way to add a break into the debugger test?

**Review by JamesWTruher — COMMENTED** [review]
my only real concern is the lack of tests which cover the break into debugger behavior.

File: src/System.Management.Automation/engine/ExecutionContext.cs [hunk 17]
```diff
@@ -1048,7 +1033,7 @@ internal ActionPreference DebugPreferenceVariable
             get
             {
                 bool defaultUsed = false;
-                return this.GetEnumPreference<ActionPreference>(
+                return this.GetEnumPreference(
```
[the remark this answers is not in the document]
Comment (KirkMunro) [reply src/System.Management.Automation/engine/ExecutionContext.cs]: It was a compiler recommendation, to simplify the name. The `ActionPreference` type isn't needed here. It still calls the same method.

File: src/System.Management.Automation/engine/MshCommandRuntime.cs [hunk 18]
```diff
@@ -2898,7 +2957,7 @@ internal ConfirmImpact ConfirmPreference
                 if (!_isConfirmPreferenceCached)
                 {
                     bool defaultUsed = false;
-                    _confirmPreference = Context.GetEnumPreference<ConfirmImpact>(SpecialVariables.ConfirmPreferenceVarPath, _confirmPreference, out defaultUsed);
+                    _confirmPreference = Context.GetEnumPreference(SpecialVariables.ConfirmPreferenceVarPath, _confirmPreference, out defaultUsed);
```
[the remark this answers is not in the document]
Comment (KirkMunro) [reply src/System.Management.Automation/engine/MshCommandRuntime.cs]: Same answer as above.

File: src/System.Management.Automation/engine/parser/Position.cs (hunk 13 above)
Comment (KirkMunro) [reply src/System.Management.Automation/engine/parser/Position.cs]: Look above that, on line 142. TrimEnd() is called as sourceLine is set, and sourceLine isn't changed, so the additional call to TrimEnd() was redundant/unnecessary.

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs (hunk 14 above)
Comment (KirkMunro) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: It's explicitly set on line 1605, just a little above this.

File: test/powershell/Language/Scripting/ActionPreference.Tests.ps1 (hunk 15 above)
Comment (KirkMunro) [reply test/powershell/Language/Scripting/ActionPreference.Tests.ps1]: Agreed, done local, will commit soon.

File: test/powershell/Language/Scripting/ActionPreference.Tests.ps1 (hunk 16 above)
Comment (KirkMunro) [reply test/powershell/Language/Scripting/ActionPreference.Tests.ps1]: Not as an automated test that I'm aware of. I've been looking at that code quite a bit and trying to determine the best way to set up debugger testing, because it would be incredibly useful for all of us. Maybe another event handler on the debugger that can be used to execute debugger commands once we're actually in the debugger. I've tried a bunch of things with what's already there, but so far I haven't had any luck. @PaulHigin mentioned an internal tool/class for testing that was not open source.

Comment (KirkMunro) [reply test/powershell/Language/Scripting/ActionPreference.Tests.ps1]: After sleeping on the problem, I came up with a solution that allows me to programmatically test the debugger without requiring any code changes or refactoring. 😄 

Now to write up some Pester tests to automate the testing of this functionality.

Comment (KirkMunro) [reply test/powershell/Language/Scripting/ActionPreference.Tests.ps1]: Just a quick update. I submitted a separate PR for debugger command test automation, and once that is approved/merged I'll use the module that PR includes to do automated testing in this PR.

**Comment by KirkMunro** [comment]
Status update: I'm trying to get another PR done related to some debugger work that Tyler did, and I'll be switching back to this PR as soon as I get that other work out of the way. I thought that would happen today until I ran into a bug in breakpoint management that got in my way.

**Review by PaulHigin — CHANGES_REQUESTED** [review]
It looks like enough has changed where a complete new review will be needed.  It may make sense to combine into a single PR.

**Comment by KirkMunro** [comment]
Update: I'm in the process of breaking this PR up into more manageable chunks, so that this is focused on the specific issue it was built to address. This will be WIP until I can pull it apart properly and get different parts of it filed in other PRs.

File: src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs [hunk 19]
```diff
@@ -351,7 +351,7 @@ public SwitchParameter BreakAll
         }
```
Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 3 failures in `PowerShell-CI-static-analysis`
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/powershell-beginners-guide.md.http://powershell.com/cs/blogs/ebookv2/default.aspx should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/README.md.http://powershell.com/cs/blogs/ebookv2/default.aspx should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/README.md.http://powershell.com/cs/media/14/default.aspx should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 3 failures in `PowerShell-CI-static-analysis`
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/powershell-beginners-guide.md.http://powershell.com/cs/blogs/ebookv2/default.aspx should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/README.md.http://powershell.com/cs/blogs/ebookv2/default.aspx should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/README.md.http://powershell.com/cs/media/14/default.aspx should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 3 failures in `PowerShell-CI-static-analysis`
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/powershell-beginners-guide.md.http://powershell.com/cs/blogs/ebookv2/default.aspx should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/README.md.http://powershell.com/cs/blogs/ebookv2/default.aspx should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/README.md.http://powershell.com/cs/media/14/default.aspx should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 1 failures in `PowerShell-CI-macos`
Tests for (error, warning, etc) action preference.action preference of Ignore can be set as a preference variable using an enumerated value
```powershell
The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/s/test/powershell/Language/Scripting/ActionPreference.Tests.ps1: line 53
53:                 Get-Process -Name asdfasdfasdf

```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 1 failures in `PowerShell-CI-linux`
Tests for (error, warning, etc) action preference.action preference of Ignore can be set as a preference variable using an enumerated value
```powershell
The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Language/Scripting/ActionPreference.Tests.ps1: line 53
53:                 Get-Process -Name asdfasdfasdf

```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 1 failures in `PowerShell-CI-windows`
Tests for (error, warning, etc) action preference.action preference of Ignore can be set as a preference variable using an enumerated value
```powershell
The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."
at <ScriptBlock>, D:\a\1\s\test\powershell\Language\Scripting\ActionPreference.Tests.ps1: line 53
53:                 Get-Process -Name asdfasdfasdf

```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 3 failures in `PowerShell-CI-static-analysis`
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/powershell-beginners-guide.md.http://powershell.com/cs/blogs/ebookv2/default.aspx should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/README.md.http://powershell.com/cs/blogs/ebookv2/default.aspx should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/README.md.http://powershell.com/cs/media/14/default.aspx should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 3 failures in `PowerShell-CI-static-analysis`
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/powershell-beginners-guide.md.http://powershell.com/cs/blogs/ebookv2/default.aspx should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/README.md.http://powershell.com/cs/blogs/ebookv2/default.aspx should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/README.md.http://powershell.com/cs/media/14/default.aspx should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 7 failures in `PowerShell-CI-macos`
(These are 5 of the failures)

Tests for (error, warning, etc) action preference.action preference of Ignore cannot be set as a preference variable
```powershell
The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/a/bins/publish/Modules/Pester/4.8.0/Functions/It.ps1: line 281
281:                     $null = & $ScriptBlock @Parameters

```
Tests for (error, warning, etc) action preference.action preference of Suspend cannot be set as a preference variable
```powershell
The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/a/bins/publish/Modules/Pester/4.8.0/Functions/It.ps1: line 281
281:                     $null = & $ScriptBlock @Parameters

```
Tests for (error, warning, etc) action preference.ErrorAction = Suspend does not work on functions
```powershell
The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/a/bins/publish/Modules/Pester/4.8.0/Functions/It.ps1: line 281
281:                     $null = & $ScriptBlock @Parameters

```
Tests for (error, warning, etc) action preference.ErrorAction = Suspend does not work on cmdlets
```powershell
The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/a/bins/publish/Modules/Pester/4.8.0/Functions/It.ps1: line 281
281:                     $null = & $ScriptBlock @Parameters

```
Tests for (error, warning, etc) action preference.WarningAction = Suspend does not work
```powershell
The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/a/bins/publish/Modules/Pester/4.8.0/Functions/It.ps1: line 281
281:                     $null = & $ScriptBlock @Parameters

```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 7 failures in `PowerShell-CI-linux`
(These are 5 of the failures)

Tests for (error, warning, etc) action preference.action preference of Ignore cannot be set as a preference variable
```powershell
The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."
at <ScriptBlock>, /home/vsts/work/1/a/bins/publish/Modules/Pester/4.8.0/Functions/It.ps1: line 281
281:                     $null = & $ScriptBlock @Parameters

```
Tests for (error, warning, etc) action preference.action preference of Suspend cannot be set as a preference variable
```powershell
The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."
at <ScriptBlock>, /home/vsts/work/1/a/bins/publish/Modules/Pester/4.8.0/Functions/It.ps1: line 281
281:                     $null = & $ScriptBlock @Parameters

```
Tests for (error, warning, etc) action preference.ErrorAction = Suspend does not work on functions
```powershell
The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."
at <ScriptBlock>, /home/vsts/work/1/a/bins/publish/Modules/Pester/4.8.0/Functions/It.ps1: line 281
281:                     $null = & $ScriptBlock @Parameters

```
Tests for (error, warning, etc) action preference.ErrorAction = Suspend does not work on cmdlets
```powershell
The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."
at <ScriptBlock>, /home/vsts/work/1/a/bins/publish/Modules/Pester/4.8.0/Functions/It.ps1: line 281
281:                     $null = & $ScriptBlock @Parameters

```
Tests for (error, warning, etc) action preference.WarningAction = Suspend does not work
```powershell
The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."
at <ScriptBlock>, /home/vsts/work/1/a/bins/publish/Modules/Pester/4.8.0/Functions/It.ps1: line 281
281:                     $null = & $ScriptBlock @Parameters

```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 7 failures in `PowerShell-CI-windows`
(These are 5 of the failures)

Tests for (error, warning, etc) action preference.action preference of Ignore cannot be set as a preference variable
```powershell
The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."
at <ScriptBlock>, D:\a\1\s\src\powershell-win-core\bin\Release\netcoreapp3.0\win7-x64\publish\Modules\Pester\4.8.0\Functions\It.ps1: line 281
281:                     $null = & $ScriptBlock @Parameters

```
Tests for (error, warning, etc) action preference.action preference of Suspend cannot be set as a preference variable
```powershell
The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."
at <ScriptBlock>, D:\a\1\s\src\powershell-win-core\bin\Release\netcoreapp3.0\win7-x64\publish\Modules\Pester\4.8.0\Functions\It.ps1: line 281
281:                     $null = & $ScriptBlock @Parameters

```
Tests for (error, warning, etc) action preference.ErrorAction = Suspend does not work on functions
```powershell
The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."
at <ScriptBlock>, D:\a\1\s\src\powershell-win-core\bin\Release\netcoreapp3.0\win7-x64\publish\Modules\Pester\4.8.0\Functions\It.ps1: line 281
281:                     $null = & $ScriptBlock @Parameters

```
Tests for (error, warning, etc) action preference.ErrorAction = Suspend does not work on cmdlets
```powershell
The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."
at <ScriptBlock>, D:\a\1\s\src\powershell-win-core\bin\Release\netcoreapp3.0\win7-x64\publish\Modules\Pester\4.8.0\Functions\It.ps1: line 281
281:                     $null = & $ScriptBlock @Parameters

```
Tests for (error, warning, etc) action preference.WarningAction = Suspend does not work
```powershell
The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help topic, "about_Preference_Variables."
at <ScriptBlock>, D:\a\1\s\src\powershell-win-core\bin\Release\netcoreapp3.0\win7-x64\publish\Modules\Pester\4.8.0\Functions\It.ps1: line 281
281:                     $null = & $ScriptBlock @Parameters

```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 3 failures in `PowerShell-CI-static-analysis`
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/powershell-beginners-guide.md.http://powershell.com/cs/blogs/ebookv2/default.aspx should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/README.md.http://powershell.com/cs/blogs/ebookv2/default.aspx should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/README.md.http://powershell.com/cs/media/14/default.aspx should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 2 failures in `PowerShell-CI-macos`
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The second statement should be the statement after that which generated the non-terminating error
```powershell
Expected 9, but got 7.
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/s/test/tools/Modules/HelpersDebugger/HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The third statement should be the statement in the finally block
```powershell
Expected 13, but got 11.
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/s/test/tools/Modules/HelpersDebugger/HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 2 failures in `PowerShell-CI-windows`
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The second statement should be the statement after that which generated the non-terminating error
```powershell
Expected 9, but got 7.
at <ScriptBlock>, D:\a\1\s\test\tools\Modules\HelpersDebugger\HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The third statement should be the statement in the finally block
```powershell
Expected 13, but got 11.
at <ScriptBlock>, D:\a\1\s\test\tools\Modules\HelpersDebugger\HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 2 failures in `PowerShell-CI-linux`
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The second statement should be the statement after that which generated the non-terminating error
```powershell
Expected 9, but got 7.
at <ScriptBlock>, /home/vsts/work/1/s/test/tools/Modules/HelpersDebugger/HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The third statement should be the statement in the finally block
```powershell
Expected 13, but got 11.
at <ScriptBlock>, /home/vsts/work/1/s/test/tools/Modules/HelpersDebugger/HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 2 failures in `PowerShell-CI-macos`
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The second statement should be the statement after that which generated the non-terminating error
```powershell
Expected 9, but got 7.
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/s/test/tools/Modules/HelpersDebugger/HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The third statement should be the statement in the finally block
```powershell
Expected 13, but got 11.
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/s/test/tools/Modules/HelpersDebugger/HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 2 failures in `PowerShell-CI-windows`
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The second statement should be the statement after that which generated the non-terminating error
```powershell
Expected 9, but got 7.
at <ScriptBlock>, D:\a\1\s\test\tools\Modules\HelpersDebugger\HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The third statement should be the statement in the finally block
```powershell
Expected 13, but got 11.
at <ScriptBlock>, D:\a\1\s\test\tools\Modules\HelpersDebugger\HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 2 failures in `PowerShell-CI-linux`
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The second statement should be the statement after that which generated the non-terminating error
```powershell
Expected 9, but got 7.
at <ScriptBlock>, /home/vsts/work/1/s/test/tools/Modules/HelpersDebugger/HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The third statement should be the statement in the finally block
```powershell
Expected 13, but got 11.
at <ScriptBlock>, /home/vsts/work/1/s/test/tools/Modules/HelpersDebugger/HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```

**Review by PaulHigin — APPROVED** [review]
These changes look good to me but since this is new debugging behavior should it not be behind the 'experimental' flag?  I'll tag committee review to get their opinion.

**Comment by KirkMunro** [comment]
Thanks @PaulHigin. It can obviously be made experimental if necessary. Some clarification on what should/should not be experimental would be helpful.

Also FYI, the only outstanding item I have on this at the moment is the Pester test failure. I added some new Pester tests today that check the extent when PowerShell enters the debugger in response to an `ActionPreference.Break` for an error or other stream message. Locally, the tests all run without issue. In our ADO CI build, all of the new tests except for the one where I use `-ErrorAction Break` to enter the debugger on a non-terminating error fails because the statement extent I expect is different. I'm thinking there may be something going on when these tests are run in a background, non-interactive process, so that's what I'm going to check next.

File: src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs (hunk 19 above)
Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 2 failures in `PowerShell-CI-macos`
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The second statement should be the statement after that which generated the non-terminating error
```powershell
Expected 9, but got 7.
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/s/test/tools/Modules/HelpersDebugger/HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The third statement should be the statement in the finally block
```powershell
Expected 13, but got 11.
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/s/test/tools/Modules/HelpersDebugger/HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 2 failures in `PowerShell-CI-windows`
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The second statement should be the statement after that which generated the non-terminating error
```powershell
Expected 9, but got 7.
at <ScriptBlock>, D:\a\1\s\test\tools\Modules\HelpersDebugger\HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The third statement should be the statement in the finally block
```powershell
Expected 13, but got 11.
at <ScriptBlock>, D:\a\1\s\test\tools\Modules\HelpersDebugger\HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 2 failures in `PowerShell-CI-linux`
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The second statement should be the statement after that which generated the non-terminating error
```powershell
Expected 9, but got 7.
at <ScriptBlock>, /home/vsts/work/1/s/test/tools/Modules/HelpersDebugger/HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The third statement should be the statement in the finally block
```powershell
Expected 13, but got 11.
at <ScriptBlock>, /home/vsts/work/1/s/test/tools/Modules/HelpersDebugger/HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```

**Comment by KirkMunro** [comment]
I'm still facing the same errors in all ADO CI builds that I cannot reproduce locally. Can someone please share details on how the Pester tests are run? I believe you use `Start-PSPester` in the `build.psm1` module, but that information isn't enough, because that works fine for me. What relevant details about the environment can you share? I need to be able to run the tests locally the same way that they are run through ADO CI so that I can reproduce the issue with one test that's showing up and fix it.

**Comment by iSazonov** [comment]
> I'm still facing the same errors in all ADO CI builds that I cannot reproduce locally.

Perhaps previous tests do not clean environment.

**Comment by KirkMunro** [comment]
@iSazonov Maybe, but I don't think that's it. I'm still investigating though. What seems to be happening is a non-terminating error is being picked up and thrown as a terminating error. I can't be sure of that without reproducing it/debugging it though. I wonder if the version of Pester that is being used plays a factor here.

File: src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs (hunk 19 above)
Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 2 failures in `PowerShell-CI-macos`
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The second statement should be the statement after that which generated the non-terminating error
```powershell
Expected 9, but got 7.
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/s/test/tools/Modules/HelpersDebugger/HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The third statement should be the statement in the finally block
```powershell
Expected 13, but got 11.
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/s/test/tools/Modules/HelpersDebugger/HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 2 failures in `PowerShell-CI-windows`
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The second statement should be the statement after that which generated the non-terminating error
```powershell
Expected 9, but got 7.
at <ScriptBlock>, D:\a\1\s\test\tools\Modules\HelpersDebugger\HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The third statement should be the statement in the finally block
```powershell
Expected 13, but got 11.
at <ScriptBlock>, D:\a\1\s\test\tools\Modules\HelpersDebugger\HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 2 failures in `PowerShell-CI-linux`
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The second statement should be the statement after that which generated the non-terminating error
```powershell
Expected 9, but got 7.
at <ScriptBlock>, /home/vsts/work/1/s/test/tools/Modules/HelpersDebugger/HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```
ActionPreference.Break tests.-ErrorAction Break should break on a non-terminating error.The third statement should be the statement in the finally block
```powershell
Expected 13, but got 11.
at <ScriptBlock>, /home/vsts/work/1/s/test/tools/Modules/HelpersDebugger/HelpersDebugger.psm1: line 189
189:         $extent.StartLineNumber | Should -Be $(if ($PSCmdlet.ParameterSetName -eq 'SingleLineExtent') {$Line} else {$FromLine})
```

**Comment by KirkMunro** [comment]
The Pester test issue is resolved. Turns out that using `$Host.Runspace` in a call to `$ps = [powershell]::Create($Host.Runspace)` as a way to prove a script cannot be invoked async in a runspace that is busy causes some state to change in that runspace, which later invalidates one of my new tests.

FYI @daxian-dbw: The test I had to change to get this working was one you reviewed for me a while back when we exposed `PowerShell.InvokeAsync`, where you requested I simplify that test and use `$Host.Runspace` instead of a newly created runspace. That appears to be a bad idea for the test harness because it changes state on something in the Runspace such that the flow when you step through the debugger using `-ErrorAction Break` is different, so I've changed it back to using a newly created runspace instead.

I now think using `$Host.Runspace` with runspace-based tests in our test harness is a bad idea, and should be avoided.

**Comment by KirkMunro** [comment]
Unless required to do so, I don't plan to address the Codacy issues. They identify things I would care about in a production PowerShell script, but fixing them in Pester tests would just add bloat.

**Comment by daxian-dbw** [comment]
Hmm, that's not expected. Invoking on a busy Runspace shouldn't affect the Runspace in any way ... 

> the flow when you step through the debugger using -ErrorAction Break is different

I'm curious about how the flow would be different. Can you please provide simpler repro of the issue?

**Comment by KirkMunro** [comment]
@daxian-dbw I had intended to do that later, because I didn't like just changing that test to make this PR pass, but I didn't want an unrelated issue to get in the way of this being reviewed/merged either. At any rate, I dug through it this morning, and it turns out the unexpected issue that was coming up is that an error cannot be written to an internal buffer because the buffer is closed. That is unexpected behavior, and a bug.

Here's a simplified script that reproduces the issue on PowerShell 6.2.1+:

```powershell
$ps = [powershell]::Create($host.Runspace)
try {
    $ps.AddScript('Get-Date').Invoke() > $null
} finally {
    $ps.Dispose()
}

[ScriptBlock]::Create({Write-Error 'An error'}).Invoke() > $null
```

That script produces the following output:

```none
Exception calling "Invoke" with "0" argument(s): "The pipeline was not run because a pipeline is already running. Pipelines cannot be run concurrently."
At C:\Users\kirka\source\repos\Test-RunspaceIssue.ps1:3 char:5
+     $ps.AddScript('Get-Date').Invoke() > $null
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : PSInvalidOperationException

Exception calling "Invoke" with "0" argument(s): "Objects cannot be added to a closed buffer. Make sure the buffer is open for Add and Insert operations to succeed."
At C:\Users\kirka\source\repos\Test-RunspaceIssue.ps1:8 char:1
+ [ScriptBlock]::Create({Write-Error 'An error'}).Invoke() > $null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : CmdletInvocationException
```

The first error is expected. The second is not.

**Comment by PaulHigin** [comment]
@KirkMunro 
I am unable to repro this on 6.20, 6.22, or Windows PowerShell 5.1, so it appears to be only in your current changes.  Buffers are only closed when a pipeline object is disposed so I am guessing your changes are writing to a stale pipeline.  But you should be able to debug this and determine the cause.  This should definitely be fixed before check in.

**Comment by KirkMunro** [comment]
@PaulHigin That repro works on PowerShell Core 6.2.1 and Windows PowerShell 5.1 (slightly modified since `[powershell]::Create()` does not accept a runspace in that version) on my local system. I specifically created that repro external to the current changes I have been working on to validate that it is not related to this PR. Since it repros in both cases using released versions of PowerShell, this issue cannot be related to my current changes. I agree it should be fixed, but I disagree that it is my responsibility to do so as part of this PR.

Evidence for Windows PowerShell 5.1:

image

Evidence for PowerShell 6.2.1:

image

**Comment by PaulHigin** [comment]
@KirkMunro 
That's weird as I still don't repro it, and I tried on two separate machines.

```powershell
$ps = [powershell]::Create()
$ps.Runspace = $host.Runspace
try { $ps.AddScript('Get-Date').Invoke() > $null } finally { $ps.Dispose() }
[scriptblock]::Create({Write-Error 'An error'}).Invoke() > $null
```
It might be a timing thing.

**Comment by iSazonov** [comment]
@PaulHigin  It is tricky :-)
If insert the test code without CR after last $null and then press Enter manually - no second error.
But if the test code already has CR after last $null and all commands is executed at once - we will see second error.

**Comment by KirkMunro** [comment]
Thanks @iSazonov. I'll update the repro to use the call operator so that the commands can't be separated.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this.  By default, our expectation is that new features are put behind an Experimental Flag which includes this one.

File: src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs (hunk 19 above)
Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 2 failures in `PowerShell-CI-macos`
Basic debugger tests.The value of $? should be preserved when exiting the debugger.Should show 2 debugger commands were invoked
```powershell
Expected 2, but got 3.
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/s/test/powershell/Language/Scripting/Debugging/Debugging.Tests.ps1: line 41
41:             $results.Count | Should -Be 2
```
Basic debugger tests.The value of $? should be preserved when exiting the debugger.Should have $false output from the first $? command
```powershell
Expected $false, but got $true.
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/s/test/powershell/Language/Scripting/Debugging/Debugging.Tests.ps1: line 46
46:             $results[0].Output | Should -Not -BeTrue
```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 2 failures in `PowerShell-CI-linux`
Basic debugger tests.The value of $? should be preserved when exiting the debugger.Should show 2 debugger commands were invoked
```powershell
Expected 2, but got 3.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Language/Scripting/Debugging/Debugging.Tests.ps1: line 41
41:             $results.Count | Should -Be 2
```
Basic debugger tests.The value of $? should be preserved when exiting the debugger.Should have $false output from the first $? command
```powershell
Expected $false, but got $true.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Language/Scripting/Debugging/Debugging.Tests.ps1: line 46
46:             $results[0].Output | Should -Not -BeTrue
```

**Comment by KirkMunro** [comment]
@SteveL-MSFT I took your recommendation to make the functionality in this PR experimental very seriously, and did a bunch of research to see how I could do that. Based on the results of my research, I have come to the conclusion that it is unreasonable to suggest that PRs that make changes inside of the engine, with no new cmdlets and no new parameters, should use an experimental flag. If you or one of the PS Team developers reviews this code, I'm confident that you'll agree with me.

This PR:
- adds a value to an existing enumeration
- updates plumbing within the engine to support that enumerated value
- fixes `Wait-Debugger` so that it properly stops on itself
- fixes the debugger so that the value of `$?` is preserved through a debugging session
- adds appropriate tests to make sure this all works properly

_I don't see how I can wrap the changes in this PR in an experimental flag without taking existing functionality that is in the PowerShell runtime and moving it into an experimental state._

Further, I can't hide the enumerated value behind an experimental flag, because that's not supported, and this PR includes changes to plumbing to make this work, so even if I could hide the enumeration, there are other changes that would remain in place in many locations, making it a lot less experimental.

In my opinion, experimental can only realistically be used for net new functionality, such as when you add a new cmdlet, add a parameter to a cmdlet, etc. It cannot be used for updates to existing code that are internal to the engine, the parser, the compiler, the debugger, etc.

Without any new public interfaces that support the experimental feature to work with in this PR, I just don't see how that can be reasonably made experimental without a ton of extra work that would include:
- breaking out logic into multiple code paths all over the place
- creating a maintenance nightmare because any bugs that are fixed in code that is broken out into multiple paths would have to be debugged, fixed, and tested in all paths
- increasing risk from fragmented code and additional error prone work that would be required to later remove code paths that are old when experimental features come out of their experimental state

Given this, my current recommendation is to review the PR that is feature complete as it is, and merge it in once you are comfortable with that review.

File: src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs (hunk 19 above)
Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 2 failures in `PowerShell-CI-windows`
Basic debugger tests.The value of $? should be preserved when exiting the debugger.Should show 2 debugger commands were invoked
```powershell
Expected 2, but got 3.
at <ScriptBlock>, D:\a\1\s\test\powershell\Language\Scripting\Debugging\Debugging.Tests.ps1: line 41
41:             $results.Count | Should -Be 2
```
Basic debugger tests.The value of $? should be preserved when exiting the debugger.Should have $false output from the first $? command
```powershell
Expected $false, but got $true.
at <ScriptBlock>, D:\a\1\s\test\powershell\Language\Scripting\Debugging\Debugging.Tests.ps1: line 46
46:             $results[0].Output | Should -Not -BeTrue
```

**Comment by KirkMunro** [comment]
FYI, I logged the separate issue I ran into as #10335.

**Comment by KirkMunro** [comment]
The CodeFactor and Codacy issues that are reported are out of scope for this PR.

**Comment by KirkMunro** [comment]
Any chance this PR can get reviewed and merged in time for the upcoming preview?

[As indicated above](https://github.com/PowerShell/PowerShell/pull/8205#issuecomment-519744453), it can't be placed behind an experimental flag, but:
- the feature has been demonstrated to users and received positive feedback;
- it comes with automated tests to verify that the debugger hits the exact locations it should in the scenarios that are tested;
- anything that was unrelated to the original issue has been moved into separate PRs, to keep this focused on `ActionPreference.Break`, the minor fix to `Wait-Debugger` behavior (that is part of these changes, and can't be separated), and the minor fix for issue #9474.

**Comment by PaulHigin** [comment]
+ @daxian-dbw

File: src/System.Management.Automation/engine/debugger/debugger.cs [hunk 20]
```diff
@@ -2500,6 +2518,39 @@ public override void SetDebuggerStepMode(bool enabled)
...
+                // No debugger attached and runspace debugging is not enabled.  Enable runspace debugging here
+                // so that this command is effective.
+                UnhandledBreakpointMode = UnhandledBreakpointProcessingMode.Wait;
+            }
+
+            // Store the triggerObject so that we can add it to PSDebugContext
+            TriggerObject = triggerObject;
+
+            // Set debugger to step mode so that a break can occur.
+            SetDebuggerStepMode(true);
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/debugger/debugger.cs]: `-ErrorAction break` will set the debugger mode to be `Enabled`, and after that the debugger mode will stay `Enabled`. That means once a `ActionPreference.Break` is hit, the session will never be able to run script in optimized mode anymore.
This feels like a concern to me. I can imagine one scenario where people uses `-ErrorAction Break` -- I don't expect an error will be thrown but want to debug in case the unexpected happens, but after debugging (quit the debugger prompt), I would like the rest of my scripts continue to run as efficient as it can (in optimized mode). That scenario will be compromised as the debugger mode will always be `Enabled` after the `-ErrorAction Break` is hit, and thus the `Compiler` will generated unoptimized code for the rest time of the session.

`Set-PSBreakpoint` turns the debugger mode to `Enabled`, and `Remove-PSBreakpoint` turns it back to `Disabled` after removing the last breakpoint. Maybe what we need is to reset the debugger mode after quitting the debugger prompt if we broke in the debugger because of `ActionPreference.Break`. Just an idea, totally thinking aloud here.

**Review by daxian-dbw — COMMENTED** [review]
The release process for preview.3 has already started. But this will definitely in the preview.4 :)

File: src/System.Management.Automation/engine/debugger/debugger.cs [hunk 21]
```diff
@@ -5169,11 +5229,12 @@ public DebuggerCommand(string command, DebuggerResumeAction? action, bool repeat
...
-        /// Constructor.
+        /// Initializes a new instance of the <see cref="PSDebugContext"/> class.
         /// </summary>
-        /// <param name="invocationInfo">InvocationInfo.</param>
-        /// <param name="breakpoints">Breakpoints.</param>
-        public PSDebugContext(InvocationInfo invocationInfo, List<Breakpoint> breakpoints)
+        /// <param name="invocationInfo">The invocation information for the current command.</param>
+        /// <param name="breakpoints">The breakpoint(s) that caused the script to break in the debugger.</param>
+        /// <param name="triggerObject">The object that caused the script to break in the debugger.</param>
+        public PSDebugContext(InvocationInfo invocationInfo, List<Breakpoint> breakpoints, object triggerObject = null)
```
[the remark this answers is not in the document]
Comment (KirkMunro) [reply src/System.Management.Automation/engine/debugger/debugger.cs]: I didn't think reflection APIs were considered for these types of changes. Regardless, that's an easy change, will be in my next commit.

File: src/System.Management.Automation/engine/parser/TypeResolver.cs [hunk 22]
```diff
@@ -885,6 +885,7 @@ static TypeAccelerators()
             builtinTypeAccelerators.Add("psnoteproperty", typeof(PSNoteProperty));
             builtinTypeAccelerators.Add("psaliasproperty", typeof(PSAliasProperty));
             builtinTypeAccelerators.Add("psvariableproperty", typeof(PSVariableProperty));
+            builtinTypeAccelerators.Add("actionpreference", typeof(ActionPreference));
```
[the remark this answers is not in the document]
Comment (KirkMunro) [reply src/System.Management.Automation/engine/parser/TypeResolver.cs]: It was discussed [around here](https://github.com/PowerShell/PowerShell/pull/8205#issuecomment-438895740). There was some resistance, a rebuttal, and then no official judgement.

Personally, having used this a lot in scripts written with this PR build, and having tried to use this a lot in scripts where it was not present, I really think it should be there by default -- it's very, very useful for error handling, which should be easy to write and easy to see in scripts. You only get both of those with the type accelerator. That said, I'll do whatever is deemed appropriate by the committee.

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs [hunk 23]
```diff
@@ -1901,10 +1949,13 @@ internal static bool ReportErrorRecord(IScriptExtent extent, RuntimeException rt
 
             context.ShellFunctionErrorOutputPipe.Add(errorWrap);
 
+            // set the value of $? here in case it is reset in error reporting.
+            context.QuestionMarkVariableValue = false;
```
[the remark this answers is not in the document]
Comment (KirkMunro) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: I have no idea. That logic pre-dates these changes. I just carried it forward.

File: src/System.Management.Automation/engine/debugger/debugger.cs (hunk 20 above)
Comment (KirkMunro) [reply src/System.Management.Automation/engine/debugger/debugger.cs]: Interesting idea.

A few relevant thoughts:

1. `Remove-PSBreakpoint` only turns the debugger mode back to disabled if it is invoked while you are not debugging (this was identified in #9824 and fixed as part of #9825) -- as a command-line debugger, I routinely add breakpoints, debug things, remove breakpoints while in the debugger, and then step through things. This is the right thing to do, because otherwise I can remove a breakpoint, then step, but the debugger doesn't step, it continues instead. Based on what you mention here, it sounds like this would also leave my debugger mode as `Enabled`.

1. A PR that I plan to submit once this is merged in is to add `-Condition <ScriptBlock>` as a parameter to `Wait-Debugger` (while also updating it to support pipeline input), so that you can enter the debugger conditionally with that command. I would expect the condition to be evaluated and that event to trigger even if the debug mode is `Disabled`.

1. With `ActionPreference.Break`, you can have dynamic breakpointing for all messages, so if I detach from the debugger after I processed one dynamic message trigger, I would want other messages to trigger breakpoints as well.

1. Issue #9336 highlights how detaching from a job prevents dynamic breakpoints like `Wait-Debugger` from triggering. Those should always trigger, so we need to be careful about what we do when we detach a debugger. I'm curious what the cause of #9336 is: what are we doing when we detach that prevents `Wait-Debugger` from triggering in the first place -- does the compiler enable debugger mode before a script with `Wait-Debugger` is even run? Or are we doing more than detach when we detach from a job? I just haven't dug into it yet to figure that out, but I think that's an important detail to know to make sure that we persist debug mode when appropriate.

That said, we should run optimized when possible, but rather than relying on `Remove-PSBreakpoint`, where would be an appropriate place to safely disable debugger mode? Can we do it when we're back at the top-level prompt if there are no explicit breakpoints, since nothing is running at that point?

File: src/System.Management.Automation/engine/parser/TypeResolver.cs (hunk 22 above)
[the remark this answers is not in the document]
Comment (KirkMunro) [reply src/System.Management.Automation/engine/parser/TypeResolver.cs]: FWIW, static `ActionPreference` types as strings can be typoed in any scope other than global because the variable will not automatically be strongly typed in a child scope (easy to miss bugs). Plus, they are not as visible in scripts as `[actionpreference]::ignore` is.

e.g.

```powershell
# This is possible
function Test-Something {
    [CmdletBinding()]
    param()
    $ErrorActionPreference = 'SilenltyContinue' # Whoops, typo, but PS allows it
    # ... do stuff here
}
Test-Something

# This is not with the type accelerator
function Test-Something {
    [CmdletBinding()]
    param()
    $ErrorActionPreference = [actionpreference]::SilentlyContinue
    # ... do stuff here
}
Test-Something
```

File: src/System.Management.Automation/engine/debugger/debugger.cs (hunk 20 above)
Comment (PaulHigin) [reply src/System.Management.Automation/engine/debugger/debugger.cs]: We can experiment with this, but it seems like the right place to do this is when processing a debugger 'continue' or 'detach' command.  If no breakpoints are set then the debugger can be disabled until Wait-Debugger or ErrorAction break occurs.

Comment (KirkMunro) [reply src/System.Management.Automation/engine/debugger/debugger.cs]: @PaulHigin As a follow-up PR though once this one is merged, right? Or would you want some investigation done as part of this PR?

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs (hunk 23 above)
[the remark this answers is not in the document]
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: This line was newly added to this method, and that means you think this method could change `context.QuestionMarkVariableValue`, right? I would like to understand the necessity of this change.

File: src/System.Management.Automation/engine/debugger/debugger.cs (hunk 20 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/debugger/debugger.cs]: I'm fine with addressing this in a follow-up PR. Opened issue https://github.com/PowerShell/PowerShell/issues/10380 to track this.

File: src/System.Management.Automation/engine/parser/TypeResolver.cs (hunk 22 above)
[the remark this answers is not in the document]
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/parser/TypeResolver.cs]: Hmm, this probably should be addressed by making `ErrorActionPreference` an `AllScope` variable. But `AllScope` variable seems not working as expected ... need to look into that.
Anyways, I will get this addition reviewed by the committee.

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs (hunk 23 above)
[the remark this answers is not in the document]
Comment (KirkMunro) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: Ok, I see the source of confusion now. That line (and the comment that precedes it) was moved into that method from the `CheckActionPreference` method that invokes it. [Here is the same line before my changes](https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs#L1642-L1643). With the other places where `QuestionMarkVariableValue` needs to be set now properly setting it, and given the comment before it, it made much more sense for that line to be inside of `ReportErrorRecord` (assuming it is actually necessary). I didn't want to discard the line, just tidy how it is used up a little, and make sure that `$?` gets set whenever `ReportErrorRecord` is invoked in case there is risk of it being reset in error reporting.

File: src/System.Management.Automation/engine/parser/TypeResolver.cs (hunk 22 above)
[the remark this answers is not in the document]
Comment (KirkMunro) [reply src/System.Management.Automation/engine/parser/TypeResolver.cs]: Not `AllScope`. Variables with `AllScope` are referenced in every scope, so they're singletons. Preference variables need to be modifiable in child scopes without changing the value in a parent scope, so they can't be singletons. PowerShell doesn't have a way to tell it that a global automatic variable should always be of a certain type whenever it is used in another scope, which is what would be needed to prevent the possibility of typos as shown above, but to apply logic like that to preference variables would definitely be breaking at this point.

[the remark this answers is not in the document]
Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/parser/TypeResolver.cs]: If I recall correctly, the original concern about adding an accelerator is perf impact of looking to see if the type matched an accelerator.  However, since accelerators are stored in a Dictionary, adding another entry in the Dictionary has a negligible impact on the perf.  So the question then is if it's valuable enough to add since if we add it, we can't remove it without it being a breaking change.  It does seem useful to aid in tab-completion and avoiding typos.  So I'm ok with adding the accelerator.

**Review by daxian-dbw — APPROVED** [review]
I'm fine not making the `ActionPreference.Break` support an experimental feature.
It's doable if we really want, by making the `-ErrorAction`, `-WarningAction` and preference variables not accept the `Break` value when the feature is disabled, but I don't think that will really provides a useful experience.

Now we just need the committee's decision on the new accelerator.

File: src/System.Management.Automation/engine/parser/TypeResolver.cs (hunk 22 above)
[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/engine/parser/TypeResolver.cs]: > It does seem useful to aid in tab-completion

I agree that this is very valuable scenario.

**Comment by KirkMunro** [comment]
@daxian-dbw Not directly related to this PR being merged, I have a question about experimental features. Is the experimental part of a feature strictly defined by interface changes? For example, with this PR, it adds a new `ActionPreference` enumerated value. As you point out, we can't hide the new enumerated value today, but we could show a message indicating it is experimental if it is used in any `-*Action` common parameter, or if it is assigned to any `*Preference` variable that accepts an `ActionPreference`, being sure to check for string assignments as well as enumerated value assignments. The question I keep coming back to with such an approach is: what's the value in having that be experimental, because all that does it put some limitations on the surface, while the plumbing underneath would have been changed regardless. If 90% of a PR is simply applied in a merge and integrated into the runtime, and 10% of the PR (the user-facing interface) is marked as experimental:

1. Is there value in that?
2. Isn't that misleading for end users, because if the runtime changes regardless of whether they have an experimental feature enabled or not, then I don't know that's very apparent.

Contrast that with a new cmdlet that experimental or a new parameter/parameter set on a cmdlet that is experimental, where it is much easier to isolate the experimental code such that it doesn't do anything at all when the experimental feature is disabled.

This may be a better side-bar discussion, but it's something I find very confusing and it's the key point that makes me question the value of experimental features, when the bulk of the change is applied regardless...

**Comment by daxian-dbw** [comment]
> Is the experimental part of a feature strictly defined by interface changes?

No, it's not. It's about the functionality/behavior before and after introducing a new feature.
Technically, putting a feature behind an experimental feature should mean that when the feature is disabled, PowerShell behaves exactly as before the feature was introduced.
Take this PR as an example, yes the runtime code has been changed to support the `Break` action, but when `Break` is not used, PowerShell should behavior exactly as before this PR -- namely, the runtime code changes shouldn't caused any behavior change to the existing behaviors (no breaking changes).

> 1. Is there value in that?
> 2. Isn't that misleading for end users, because if the runtime changes regardless of whether they have an experimental feature enabled or not, then I don't know that's very apparent.

For changes like this PR -- mostly updating engine code that are hard to co-exist with the old engine code, I personally think it shouldn't be targeted as an experimental feature. (_if the engine code changes caused any change in existing behavior, it will be noticed too even with the feature enabled_).
Changes like this should be heavily reviewed at design/implementation phase (dogfooded by reviewers), and if decide to accept, then accept directly as an official feature.
I'm not saying other experimental features with less engine code changes would have a lower bar for acceptance. We always have a high bar for feature changes, but the changes like this PR should have an even higher bar.

**Comment by KirkMunro** [comment]
Thanks for that reply, @daxian-dbw, that was helpful.

> Now we just need the committee's decision on the new accelerator.

Does [@SteveL-MSFT's reply here](https://github.com/PowerShell/PowerShell/pull/8205#discussion_r315471089) satisfy that need? Or does this still require being put in front of the committee again?

**Comment by daxian-dbw** [comment]
> Does @SteveL-MSFT's reply here satisfy that need? Or does this still require being put in front of the committee again?

Steve's opinion is very important for driving the committee's conclusion, but we still need the committee's approval on this. We're having a meeting this afternoon, so it should be done today :)

**Comment by SteveL-MSFT** [comment]
@KirkMunro to help make the @PowerShell/powershell-committee meetings more efficient, we're trying to add individual opinions on items for review rather than having the discussion entirely within the meeting.  So don't be surprised if you start seeing more of this.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and do not support adding the type accelerator as `[actionp<tab>` is a similar experience to the accelerator to resolve the tab-complete concern.  In general, expectation is that type accelerators should exist for types that are highly used which isn't the case for this pref variable.

**Comment by joeyaiello** [comment]
Just to add a little more context: we don't want to open the doors for more low-use type accelerators in the future. And in my opinion, "[actionpreference]" is just as difficult to get right sans tab as "SilentlyContinue". I'm sure there's more out there that I'm not aware of, but I'm also not at all a fan of an all-lowercase, two-word accelerator like that. Accelerators like "[string]" and "[int]" fit a lot better with what folks are used to seeing from a non-C# type perspective.

**Comment by KirkMunro** [comment]
> Just to add a little more context: we don't want to open the doors for more low-use type accelerators in the future. And in my opinion, "[actionpreference]" is just as difficult to get right sans tab as "SilentlyContinue". I'm sure there's more out there that I'm not aware of, but...

@joeyaiello I removed the accelerator, but I disagree with the community decision on this and will point a few things out highlighting why I disagree:

1. For string enumerated values you only get tab complete when you use them within the `-*Action` parameters. You don't get tab complete when you assign a string value to one of the `$*Preference` variables, which is commonly done in scripts, and that's where typos can occur. Those typos only get caught in the global scope where those variables are strongly typed, but you never use those variables in the global scope. Those are the scenarios where I think having an accelerator adds value for the community, when you use the preference variables in scripts or functions or modules.
1. I disagree that action preference variables are low use -- I've seen it used a lot, and I believe that an accelerator would get quite a bit of use in scripts if it was available.

>  I'm also not at all a fan of an all-lowercase, two-word accelerator like that.

I only made it all lowercase to follow the format of other accelerators. My preference would have been for an `[ActionPreference]` accelerator, but none of the other existing accelerators that have multiple "words" use uppercase in their names.

File: src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs (hunk 19 above)
Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 2 failures in `PowerShell-CI-macos`
ActionPreference.Break tests.Other message types should break on their corresponding messages when requested.Should show 7 debugger commands were invoked
```powershell
Expected 7, but got 0.
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/s/test/powershell/Language/Scripting/ActionPreference.Tests.ps1: line 306
306:             $results.Count | Should -Be 7
```
ActionPreference.Break tests.ActionPreference.Break in jobs.ActionPreference.Break should break in a running job
```powershell
Expected $true, but got $false.
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/s/test/powershell/Language/Scripting/ActionPreference.Tests.ps1: line 352
352:             Wait-UntilTrue -sb { $job.State -eq 'AtBreakpoint' } -TimeoutInMilliseconds (10 * 1000) -IntervalInMilliseconds 100 | Should -BeTrue
```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 2 failures in `PowerShell-CI-windows`
ActionPreference.Break tests.Other message types should break on their corresponding messages when requested.Should show 7 debugger commands were invoked
```powershell
Expected 7, but got 0.
at <ScriptBlock>, D:\a\1\s\test\powershell\Language\Scripting\ActionPreference.Tests.ps1: line 306
306:             $results.Count | Should -Be 7
```
ActionPreference.Break tests.ActionPreference.Break in jobs.ActionPreference.Break should break in a running job
```powershell
Expected $true, but got $false.
at <ScriptBlock>, D:\a\1\s\test\powershell\Language\Scripting\ActionPreference.Tests.ps1: line 352
352:             Wait-UntilTrue -sb { $job.State -eq 'AtBreakpoint' } -TimeoutInMilliseconds (10 * 1000) -IntervalInMilliseconds 100 | Should -BeTrue
```

Comment (PoshChan) [inline src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs]: @KirkMunro, your last commit had 2 failures in `PowerShell-CI-linux`
ActionPreference.Break tests.Other message types should break on their corresponding messages when requested.Should show 7 debugger commands were invoked
```powershell
Expected 7, but got 0.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Language/Scripting/ActionPreference.Tests.ps1: line 306
306:             $results.Count | Should -Be 7
```
ActionPreference.Break tests.ActionPreference.Break in jobs.ActionPreference.Break should break in a running job
```powershell
Expected $true, but got $false.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Language/Scripting/ActionPreference.Tests.ps1: line 352
352:             Wait-UntilTrue -sb { $job.State -eq 'AtBreakpoint' } -TimeoutInMilliseconds (10 * 1000) -IntervalInMilliseconds 100 | Should -BeTrue
```

**Review by daxian-dbw — APPROVED** [review]
The updates about reverting `actionpreference` accelerator look good to me.

**Comment by iSazonov** [comment]
@KirkMunro Please update the PR description.

**Comment by KirkMunro** [comment]
@iSazonov Done.
