### PR TITLE
Make sure we always return an object in command searcher

### LINKED ISSUE #9396: NullReferenceException in Get-Command
# Steps to reproduce

```powershell
# This throws:
PS> get-command "less `"-PsPage %db?B of %D:`"" -ErrorAction Ignore
get-command : Object reference not set to an instance of an object.
# This doesn't:
PS> get-command "less `"-PsPage %db?B of %D`"" -ErrorAction Ignore
```
It looks like the `D:` in the string looks like a path??

# Expected behavior
This command shouldn't throw a terminating error given this input.

# Actual behavior
It throws this exception:
```none
PSMessageDetails      :
Exception             : System.NullReferenceException: Object reference not set to an instance of an object.
                           at System.Management.Automation.CommandSearcher.GetNextFromPath() in C:\Users\Keith\GitHub\r
                        keithhill\PowerShell\src\System.Management.Automation\engine\CommandSearcher.cs:line 477
                           at System.Management.Automation.CommandSearcher.ProcessBuiltinScriptState() in C:\Users\Keit
                        h\GitHub\rkeithhill\PowerShell\src\System.Management.Automation\engine\CommandSearcher.cs:line
                        292
                           at System.Management.Automation.CommandSearcher.MoveNext() in C:\Users\Keith\GitHub\rkeithhi
                        ll\PowerShell\src\System.Management.Automation\engine\CommandSearcher.cs:line 191
                           at
                        Microsoft.PowerShell.Commands.GetCommandCommand.FindCommandForName(SearchResolutionOptions
                        options, String commandName, Boolean isPattern, Boolean emitErrors, Int32& currentCount,
                        Boolean& isDuplicate) in C:\Users\Keith\GitHub\rkeithhill\PowerShell\src\System.Management.Auto
                        mation\engine\GetCommandCommand.cs:line 887
                           at Microsoft.PowerShell.Commands.GetCommandCommand.AccumulateMatchingCommands(IEnumerable`1
                        commandNames) in C:\Users\Keith\GitHub\rkeithhill\PowerShell\src\System.Management.Automation\e
                        ngine\GetCommandCommand.cs:line 759
                           at Microsoft.PowerShell.Commands.GetCommandCommand.AccumulateMatchingCommands() in C:\Users\
                        Keith\GitHub\rkeithhill\PowerShell\src\System.Management.Automation\engine\GetCommandCommand.cs
                        :line 700
                           at Microsoft.PowerShell.Commands.GetCommandCommand.ProcessRecord() in C:\Users\Keith\GitHub\
                        rkeithhill\PowerShell\src\System.Management.Automation\engine\GetCommandCommand.cs:line 421
                           at System.Management.Automation.Cmdlet.DoProcessRecord() in C:\Users\Keith\GitHub\rkeithhill
                        \PowerShell\src\System.Management.Automation\engine\cmdlet.cs:line 173
                           at System.Management.Automation.CommandProcessor.ProcessRecord() in C:\Users\Keith\GitHub\rk
                        eithhill\PowerShell\src\System.Management.Automation\engine\CommandProcessor.cs:line 386
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Get-Command], NullReferenceException
FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetCommandCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0-rc.1
PSEdition                      Core
GitCommitId                    6.2.0-rc.1-167-ge9ffbe5cf27ad6461607fcf4bc69258652a88d33
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Interesting this shows 6.2.0-rc.1 since I'm building off of the latest on `master`.  BTW this is a regression from 6.1.0 where this did not throw an NRE.

### PR DESCRIPTION
**Pull request by TravisEz13**
# PR Summary

Make sure we always return an object in command searcher

## PR Context

Fixes #9396 

Reviewing the code returning an empty object should not cause an issue.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Review by PaulHigin — APPROVED** [review]

File: src/System.Management.Automation/engine/CommandSearcher.cs [hunk 1]
```diff
@@ -565,7 +565,7 @@ private Collection<string> GetNextFromPathUsingWildcards(string command, out Pro
             }
 
             provider = null;
-            return null;
+            return new Collection<string>();
```
Comment (adityapatwardhan) [inline src/System.Management.Automation/engine/CommandSearcher.cs]: Maybe you should use this if read only is ok.

https://github.com/PowerShell/PowerShell/blob/0dc216ee7c682a6c64b7cf6a70b4ccde85cec23d/src/System.Management.Automation/engine/Utils.cs#L1455

Comment (TravisEz13) [reply src/System.Management.Automation/engine/CommandSearcher.cs]: This breaks functionality in the searcher.

File: test/powershell/engine/Basic/CommandDiscovery.Tests.ps1 [hunk 2]
```diff
@@ -205,4 +205,10 @@ Describe "Command Discovery tests" -Tags "CI" {
             }
         }
     }
+
+    Context "error cases" {
+        It 'Get-Command "less `"-PsPage %db?B of %DoesNotExist:`"" should throw Drive not found' {
+            {Get-Command -Name "less `"-PsPage %db?B of %DoesNotExist:`""} | Should -Throw -ErrorId 'DriveNotFound' -because "The drive 'DoesNotExist:' should not exist"
```
Comment (iSazonov) [inline test/powershell/engine/Basic/CommandDiscovery.Tests.ps1]:
```suggestion
            {Get-Command -Name "less `"-PsPage %db?B of %DoesNotExist:`""} | Should -Throw -ErrorId 'DriveNotFound' -Because "The drive 'DoesNotExist:' should not exist"
```

**Comment by TravisEz13** [comment]
@PoshChan Please remind me in 1 hour

**Comment by PoshChan** [comment]
@TravisEz13, this is the reminder you requested 1 hour ago
