### PR TITLE
Fix a regression in formatting caused by the 'FirstOrDefault' primitive added in 7.0.0-Preview1

### LINKED ISSUE #10554: Write-Output of class with hidden params regression in PS 7
# Steps to reproduce
In PS 6 and below if a class has only hidden params it will show the ToString() output like it do when there are no parameters. If there are non hiden params it shows them instead.
In PS 7  if a class has only hidden params it shows blank lines.
```powershell
class Empty {
    MyClass() { }
    [String]ToString() { return 'MyString' }
}
[Empty]::new()
# Will Show "MyString"

class Hidden {
    hidden $Param = 'Foo'
    MyClass() { }
    [String]ToString() { return 'MyString' }
}
[Hidden]::new()
# On PS < 7 Will Show "MyString"
# On PS 7 Will Show "2 blank lines"

class Params {
    $Param = 'Foo'
    MyClass() { }
    [String]ToString() { return 'MyString' }
}
[Params]::new()
<# Will Show:
Param
-----
Foo
#>
```

# Expected behavior
If there are only hidden params show the ToString() like in PS6

# Actual behavior
If there are only hidden params it shows blank lines like it tries to show the params but have noting to show.

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #10554

Hidden members should not be returned by any fuzzy searches, such as searching by 'match' or enumerating the collection. They are returned only if the member names are explicitly looked for. `FirstOrDefault` is a fuzzy search, so it should ignore the hidden members.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Review by iSazonov — APPROVED** [review]
LGTM with one minor comment.

File: src/System.Management.Automation/engine/CoreAdapter.cs [hunk 1]
```diff
@@ -2012,17 +2038,30 @@ internal void Add(string name, object member)
                     return null;
                 }
 
-                return this.memberCollection[indexObj];
+                return memberCollection[indexObj];
             }
         }
 
+        /// <summary>
+        /// Get the first no-hidden member that satisfies the predicate.
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/CoreAdapter.cs]:
```suggestion
        /// Get the first non-hidden member that satisfies the predicate.
```

File: src/System.Management.Automation/engine/CoreAdapter.cs [hunk 2]
```diff
@@ -2585,9 +2624,33 @@ internal MethodCacheEntry(MethodBase[] methods)
                     return methodInformationStructures[i];
                 }
             }
+
+            private bool? _isHidden;
+            internal override bool IsHidden
+            {
+                get
+                {
+                    if (_isHidden == null)
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/CoreAdapter.cs]: If multiple threads access this property, we'll do the work to discover the hidden attribute multiple times. But, I don't believe that would cause a bug, just does needless work. OTOH, the easiest way to make this threadsafe (`Lazy<bool>(IsMemberHidden)`) probably adds some overhead on both generation and access (or we could just add a lock per instance I suppose). So I'm guessing the solution here sells out an uncommon bad case with race conditions (which aren't really race conditions, since the result is always the same) for the usual case?

File: test/powershell/engine/Formatting/BugFix.Tests.ps1 [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+        }
+
+        $outstring = [Hidden]::new() | Out-String
+        $outstring.Trim() | Should -BeExactly "MyString"
+    }
+
+    It 'Formatting for an object with no-hidden property should use the default view' {
+        class Params {
+            $Param = 'Foo'
+            [String]ToString() { return 'MyString' }
```
Comment (rjmholt) [inline test/powershell/engine/Formatting/BugFix.Tests.ps1]: What's the behaviour supposed to be when `ToString()` isn't overridden?

File: src/System.Management.Automation/engine/CoreAdapter.cs (hunk 2 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/CoreAdapter.cs]: I see we lock cache tables but not cache elements in the whole file.

File: test/powershell/engine/Formatting/BugFix.Tests.ps1 (hunk 3 above)
Comment (daxian-dbw) [reply test/powershell/engine/Formatting/BugFix.Tests.ps1]: Whether the `ToString()` method is present or not shouldn't affect how `Params` object is formatted by PowerShell in this case.

File: src/System.Management.Automation/engine/CoreAdapter.cs (hunk 2 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/CoreAdapter.cs]: To me, this is more of a small optimization so that we don't have to calculate the value every time this property gets accessed. Adding a lock is expensive and not needed in this case given that the operation is so simple that it's OK for multiple threads run in the `if (_isHidden == null)` block occasionally.
Previously, the `ishidden` check happens in higher level like `GetDotNetPropertyImpl` and `GetDotNetMethodImpl`, and it happens every time when those methods called. So having this small optimization is worthwhile.

File: test/powershell/engine/Formatting/BugFix.Tests.ps1 [hunk 4]
```diff
@@ -0,0 +1,34 @@
+# Copyright (c) Microsoft Corporation. All rights reserved.
+# Licensed under the MIT License.
+
+Describe 'Bug fixes related to formatting' -Tag CI {
```
[the remark this answers is not in the document]
Comment (daxian-dbw) [reply test/powershell/engine/Formatting/BugFix.Tests.ps1]: Updated the test name, but kept the file name unchanged. I would like this file to be used for future bug fixes related to formatting.

File: test/powershell/engine/Formatting/BugFix.Tests.ps1 (hunk 3 above)
Comment (rjmholt) [reply test/powershell/engine/Formatting/BugFix.Tests.ps1]: Does it make sense in that case to have some test where `ToString()` isn't overridden as a control?

File: src/System.Management.Automation/engine/CoreAdapter.cs (hunk 2 above)
Comment (rjmholt) [reply src/System.Management.Automation/engine/CoreAdapter.cs]: I agree, just wanted to make sure we discussed it

**Review by rjmholt — APPROVED** [review]

File: src/System.Management.Automation/engine/CoreAdapter.cs (hunk 2 above)
Comment (zaconeal5) [reply src/System.Management.Automation/engine/CoreAdapter.cs]: -        /// Get the first no-hidden member that satisfies the predicate.

+        /// Get the first non-hidden member that satisfies the predicate.

File: test/powershell/engine/Formatting/BugFix.Tests.ps1 (hunk 3 above)
Comment (daxian-dbw) [reply test/powershell/engine/Formatting/BugFix.Tests.ps1]: Sure, I can add 3 more tests without the `ToString` override.

**Review by adityapatwardhan — APPROVED** [review]
