### PR TITLE
Fix `Format-Table` where header label is empty

### LINKED ISSUE #21147: Bug - Format-Default - Cannot process argument because the value of argument "name" is not valid
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The issue is specific to `TableControl` with that pulls from a localized resource.

### Expected behavior

```console
This starts failing from PS 7.4.


<View>
      <Name>PSRule.Rules.RuleRecord</Name>
      <ViewSelectedBy>
        <TypeName>PSRule.Rules.RuleRecord</TypeName>
      </ViewSelectedBy>
      <GroupBy>
        <PropertyName>TargetName</PropertyName>
      </GroupBy>
      <TableControl>
        <TableHeaders>
          <TableColumnHeader>
            <Label AssemblyName="Microsoft.PSRule.Core" BaseName="PSRule.Resources.ViewStrings" ResourceId="RuleName"/>
            <Width>35</Width>
          </TableColumnHeader>
          <TableColumnHeader>
            <Label AssemblyName="Microsoft.PSRule.Core" BaseName="PSRule.Resources.ViewStrings" ResourceId="Outcome"/>
            <Width>10</Width>
          </TableColumnHeader>
          <TableColumnHeader>
            <Label AssemblyName="Microsoft.PSRule.Core" BaseName="PSRule.Resources.ViewStrings" ResourceId="Recommendation"/>
          </TableColumnHeader>
        </TableHeaders>
        <TableRowEntries>
          <TableRowEntry>
            <TableColumnItems>
              <TableColumnItem>
                <PropertyName>RuleName</PropertyName>
              </TableColumnItem>
              <TableColumnItem>
                <PropertyName>Outcome</PropertyName>
              </TableColumnItem>
              <TableColumnItem>
                <PropertyName>Recommendation</PropertyName>
              </TableColumnItem>
            </TableColumnItems>
          </TableRowEntry>
        </TableRowEntries>
      </TableControl>
    </View>
```

### Actual behavior

```console
Generates exception.
```

### Error details

```console
Type           : System.Management.Automation.CmdletInvocationException
ErrorRecord    :
    Exception             :
        Type        : System.Management.Automation.PSArgumentException
        ErrorRecord :
            Exception             :
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
                HResult : -2146233087
            CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : Argument
        Message     : Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
        ParamName   : name
        TargetSite  :
            Name          : get_Item
            DeclaringType : System.Management.Automation.PSMemberInfoIntegratingCollection`1[T]
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Source      : System.Management.Automation
        HResult     : -2147024809
        StackTrace  :
   at System.Management.Automation.PSMemberInfoIntegratingCollection`1.get_Item(String name)
   at Microsoft.PowerShell.Commands.Internal.Format.TableViewGenerator.GenerateTableHeaderInfoFromDataBaseInfo(PSObject so)
   at Microsoft.PowerShell.Commands.Internal.Format.TableViewGenerator.GenerateStartData(PSObject so)
   at Microsoft.PowerShell.Commands.Internal.Format.InnerFormatShapeCommand.WriteFormatStartData(PSObject so)
   at Microsoft.PowerShell.Commands.Internal.Format.InnerFormatShapeCommand.ProcessObject(PSObject so)
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    CategoryInfo          : InvalidArgument: (:) [format-default], PSArgumentException
    FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.FormatDefaultCommand
    InvocationInfo        :
        MyCommand       : format-default
        HistoryId       : 3
        CommandOrigin   : Internal
    ScriptStackTrace      : at Invoke-PSRule<Process>, D:\Dev\Workspace\PSRule\out\modules\PSRule\PSRule.psm1: line 181
                            at <ScriptBlock>, <No file>: line 1
    PipelineIterationInfo :



TargetSite     :
    Name          : Invoke
    DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation, Version=7.4.1.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    MemberType    : Method
    Module        : System.Management.Automation.dll
Message        : Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
InnerException :
    Type        : System.Management.Automation.PSArgumentException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : Argument
    Message     : Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
    ParamName   : name
    TargetSite  :
        Name          : get_Item
        DeclaringType : System.Management.Automation.PSMemberInfoIntegratingCollection`1[T]
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Source      : System.Management.Automation
    HResult     : -2147024809
    StackTrace  :
   at System.Management.Automation.PSMemberInfoIntegratingCollection`1.get_Item(String name)
   at Microsoft.PowerShell.Commands.Internal.Format.TableViewGenerator.GenerateTableHeaderInfoFromDataBaseInfo(PSObject so)
   at Microsoft.PowerShell.Commands.Internal.Format.TableViewGenerator.GenerateStartData(PSObject so)
   at Microsoft.PowerShell.Commands.Internal.Format.InnerFormatShapeCommand.WriteFormatStartData(PSObject so)
   at Microsoft.PowerShell.Commands.Internal.Format.InnerFormatShapeCommand.ProcessObject(PSObject so)
   at System.Management.Automation.CommandProcessor.ProcessRecord()
Source         : System.Management.Automation
HResult        : -2146233087
StackTrace     :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

With the addition of the feature to add italics to table headers that are synthetic, the code that checks this was simply passing the header label to PSObject to see if the property exists.  However, PSObject doesn't allow for an empty string as the property name so throws an exception rather than returning null. 

This is a regression introduced in 7.4

Fix is to check if the label text is empty before attempting to retrieve the property to see if it exists.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/21147

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator_Table.cs [hunk 1]
```diff
@@ -173,7 +173,10 @@ private TableHeaderInfo GenerateTableHeaderInfoFromDataBaseInfo(PSObject so)
                     ci.alignment = colHeader.alignment;
                     if (colHeader.label != null)
                     {
-                        ci.HeaderMatchesProperty = so.Properties[colHeader.label.text] is not null;
+                        if (colHeader.label.text != string.Empty)
+                        {
+                            ci.HeaderMatchesProperty = so.Properties[colHeader.label.text] is not null;
+                        }
```
Comment (daxian-dbw) [inline src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator_Table.cs:179]: After the change, `ci.HeaderMatchesProperty` is unset in this code path when `label.text == string.empty`, is that expected?

Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator_Table.cs:179]: There shouldn't be any problem with it being unset as it defaults to `true`

**Review by daxian-dbw — APPROVED** [review]
LGTM.
