### PR TITLE
Fix use of `Start-Process http://bing.com`

### LINKED ISSUE #9791: v7.0.0-preview.1: can't open a URL with Start-Process
# Steps to reproduce

Invoke the following:

```
Start-Process "http://www.microsoft.com"
```

# Expected behavior

The specified URL is opened in the default browser

# Actual behavior

```
Start-Process : Cannot find drive. A drive with the name 'http' does not exist.
At line:1 char:1
+ Start-Process "http://www.microsoft.com"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (http:String) [Start-Process], DriveNotFoundException
+ FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.StartProcessCommand
```

# Environment data

```
PS C:/Users/steph> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.1
PSEdition                      Core
GitCommitId                    7.0.0-preview.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

The change in #9202 introduced this regression by searching for a literal path.  In the case of `http://bing.com`, this results in an exception because the `http:` drive doesn't exist.  The fix is to catch this exception and let the search continue which will end up using ShellExecute to find a handler.

Since this specific case brings up the browser, I didn't add a test but validated it manually.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/9791

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 1 failures in `PowerShell-CI-macos`
Command Discovery tests.error cases.Get-Command "less `"-PsPage %db?B of %DoesNotExist:`"" should throw Drive not found
```powershell
Expected an exception, with FullyQualifiedErrorId 'DriveNotFound' to be thrown, because The drive 'DoesNotExist:' should not exist, but no exception was thrown.
at <ScriptBlock>, /Users/vsts/agent/2.150.3/work/1/s/test/powershell/engine/Basic/CommandDiscovery.Tests.ps1: line 211
211:             {Get-Command -Name "less `"-PsPage %db?B of %DoesNotExist:`""} | Should -Throw -ErrorId 'DriveNotFound' -Because "The drive 'DoesNotExist:' should not exist"
```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 1 failures in `PowerShell-CI-windows`
Command Discovery tests.error cases.Get-Command "less `"-PsPage %db?B of %DoesNotExist:`"" should throw Drive not found
```powershell
Expected an exception, with FullyQualifiedErrorId 'DriveNotFound' to be thrown, because The drive 'DoesNotExist:' should not exist, but no exception was thrown.
at <ScriptBlock>, D:\a\1\s\test\powershell\engine\Basic\CommandDiscovery.Tests.ps1: line 211
211:             {Get-Command -Name "less `"-PsPage %db?B of %DoesNotExist:`""} | Should -Throw -ErrorId 'DriveNotFound' -Because "The drive 'DoesNotExist:' should not exist"
```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 1 failures in `PowerShell-CI-linux`
Command Discovery tests.error cases.Get-Command "less `"-PsPage %db?B of %DoesNotExist:`"" should throw Drive not found
```powershell
Expected an exception, with FullyQualifiedErrorId 'DriveNotFound' to be thrown, because The drive 'DoesNotExist:' should not exist, but no exception was thrown.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/engine/Basic/CommandDiscovery.Tests.ps1: line 211
211:             {Get-Command -Name "less `"-PsPage %db?B of %DoesNotExist:`""} | Should -Throw -ErrorId 'DriveNotFound' -Because "The drive 'DoesNotExist:' should not exist"
```

**Comment by vexx32** [comment]
In the case where there is no further path that works, does it still not make sense to throw the DriveNotFound exception?

**Comment by SteveL-MSFT** [comment]
@vexx32 currently, we fall through to using ShellExecute if the command is not found.  This is consistent with Windows PowerShell (and prior versions of PSCore6).  At that time, we leave it to the shell to find an associated app to run so there isn't an opportunity to rethrow.

**Comment by bergmeister** [comment]
It seems this PR also fixes my recently opened issue #9814 as well, it might be useful to add a test for this as well.

**Comment by TravisEz13** [comment]
@bergmeister Can you file an issue to add a test for the the issue?   I don't think we should block this PR on that.

**Comment by TravisEz13** [comment]
@PoshChan Please remind me in 1 hour.

**Comment by bergmeister** [comment]
@TravisEz13 I suggest to just edit the issue after the merge to add a test scenario for it.

**Comment by PoshChan** [comment]
@TravisEz13, this is the reminder you requested 1 hour. ago

**Comment by TravisEz13** [comment]
@SteveL-MSFT I reviewed where this was regressed and I think we missed a few exceptions that should be handled.  I refactored your code to add the exception handlers back.  I remember discussing this but I think our conclusion was wrong.  

Adding the exception handlers in the other two locations causes different regressions, so I have a wrapper for the helper that handles exceptions and use it where we need to handle exception and use the inner helper where we don't need to handle exceptions.

**Comment by TravisEz13** [comment]
Verified the `gcm global:help` is consistent with 5.1

File: src/System.Management.Automation/engine/CommandSearcher.cs [hunk 1]
```diff
@@ -1222,6 +1222,64 @@ private string ResolvePSPath(string path)
...
+            }
+            catch (ItemNotFoundException)
+            {
+                CommandDiscovery.discoveryTracer.TraceError(
+                    "The path could not be found: {0}",
+                        _commandName);
+            }
+            catch (DriveNotFoundException)
+            {
+                CommandDiscovery.discoveryTracer.TraceError(
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/CommandSearcher.cs]: Add a comment about when this catch is useful, since we know it now :)

File: src/System.Management.Automation/engine/CommandSearcher.cs [hunk 2]
```diff
@@ -1222,6 +1222,64 @@ private string ResolvePSPath(string path)
...
+        /// <param name="command">
+        /// The command to search for.
+        /// </param>
+        /// <param name="provider">The provider that the command was found in.</param>
+        /// <returns>
+        /// Full path to the command.
+        /// </returns>
+        private string GetNextLiteralPathThatExistsAndHandleExceptions(string command, out ProviderInfo provider)
+        {
+            try {
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/CommandSearcher.cs]: `{` should be on the next line

File: src/System.Management.Automation/engine/CommandSearcher.cs [hunk 3]
```diff
@@ -1222,6 +1222,64 @@ private string ResolvePSPath(string path)
...
+                CommandDiscovery.discoveryTracer.TraceError(
+                    "The provider associated with the path '{0}' encountered an error: {1}",
+                    _commandName,
+                    providerException.Message);
+            }
+            catch (PSNotSupportedException)
+            {
+                CommandDiscovery.discoveryTracer.TraceError(
+                    "The provider associated with the path '{0}' does not implement ContainerCmdletProvider",
+                        _commandName);
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/CommandSearcher.cs]: indentation needs to be fixed.

**Review by daxian-dbw — APPROVED** [review]

**Comment by TravisEz13** [comment]
@PoshChan Please remind me in 1 hour

**Comment by PoshChan** [comment]
@TravisEz13, this is the reminder you requested 1 hour ago
