### PR TITLE
Fix how processor arch is validated in `Import-Module`

### LINKED ISSUE #24225: `ProcessorArchitecture` module requirement regression or intended change in `7.5.0-preview.4`?
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Very simple demo module for demonstration purposes and (hopefully) straightforward reproduction:

###### `DummyModule.psd1`

```ps1
@{
	RootModule            = 'DummyModule.psm1'
	ModuleVersion         = '0.0.1'
	GUID                  = 'c06a9044-ddbb-466b-9ef5-a2a76e9160a3'
	Author                = 'Foo'
	CompanyName           = 'Bar'
	Copyright             = '(c) 2024 Baz'
	Description           = 'Demo Module Only for Testing Purposes'
	PowerShellVersion     = '7.2'
	ProcessorArchitecture = 'Amd64'
	FunctionsToExport     = @('Show-Dummy')
	VariablesToExport     = @()
	CmdletsToExport       = @()
	AliasesToExport       = @('shd')
	PrivateData           = @{
		PSData = @{
				Tags       = @('Demo', 'Example', 'Testing', 'Debug')
				ProjectUri = 'https://github.com/PowerShell/PowerShell/issues'
		}
	}
}

```

###### `DummyModule.psm1`

```ps1
function Show-Dummy {
	[Alias('shd')]
	param(
		[string] $val = 'Test'
	)
	[Console]::WriteLine("`e[38;05;$(Get-Random -Maximum 256)m ${val}`e[0m")
}

```

I've put these into a zip, ready to extract  anywhere and to import immediately, for convenience:
[DummyModuleGitHub.zip](https://github.com/user-attachments/files/16796615/DummyModuleGitHub.zip)

### Expected behavior

```console
PS C:\Test> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Test> Import-Module .\DummyModule\
PS C:\Test> shd
 Test
PS C:\Test> shd
 Test
PS C:\Test> shd
 Test
PS C:\Test> shd
 Test
PS C:\Test> shd 'was working before'
 was working before
PS C:\Test>
```

### Actual behavior

```console
PS C:\Test> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.5.0-preview.4
PSEdition                      Core
GitCommitId                    7.5.0-preview.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Test> Import-Module .\DummyModule\
Import-Module: The current processor architecture is: MSIL. The module 'C:\Test\DummyModule\0.0.1\DummyModule.psd1' requires the following architecture: Amd64.
PS C:\Test>
```

### Error details

_No response_

### Environment data

```powershell
See above...

Import-Module is *working* with `7.4.5` and was also *working* with `7.5.0-preview.3`.
New (unexpected?) behavior in `7.5.0-preview.4`

Full build version: Windows 10 22H2, 10.0.19045.4780
Terminal (Unpackaged) Version: 1.22.240823002-preview
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

In .NET 9, the deprecated call to `AssemblyName.ProcessorArchitecture` returns `MSIL` so this causes the module manifest `ProcessorArchitecture` keyword to fail (unless it specifies `MSIL`.  Change is to use the current process architecture, however, this is a different enum, so we have to do direct comparisons.  The module manifest limits what `ProcessorArchitecture` values are allowed, so we only need to check those.

This is a regression from 7.4

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/24225

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
  - [x] None
  - **OR**
  - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
    - [ ] Experimental feature name(s): 
- **User-facing changes**
  - [x] Not Applicable
  - **OR**
  - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
  - [ ] N/A or can only be tested interactively
  - **OR**
  - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
  - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
  - **OR**
  - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
    - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
      - [ ] Issue filed: 
    - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
      - [ ] Issue filed: 
    - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
      - [ ] Issue filed: 
    - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
      - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs [hunk 1]
```diff
@@ -1920,11 +1921,12 @@ internal PSModuleInfo LoadModuleManifest(
...
             {
-                #pragma warning disable SYSLIB0037
-                ProcessorArchitecture currentArchitecture = typeof(object).Assembly.GetName().ProcessorArchitecture;
-                #pragma warning restore SYSLIB0037
+                Architecture currentArchitecture = RuntimeInformation.ProcessArchitecture;
 
-                if (currentArchitecture != requiredProcessorArchitecture)
+                if ((requiredProcessorArchitecture == ProcessorArchitecture.X86 && currentArchitecture != Architecture.X86) ||
+                    (requiredProcessorArchitecture == ProcessorArchitecture.Amd64 && currentArchitecture != Architecture.X64) ||
+                    (requiredProcessorArchitecture == ProcessorArchitecture.Arm && currentArchitecture != Architecture.Arm64) ||
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs:1928]: What if `currentArchitecture` is `Arm` or `Armv6` (no idea what this is :))

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs:1928]: Module manifest only allows `Arm`, no `Arm64`, and since .NET only supports `Arm64`, `arm == arm64`

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs:1928]: Hmm, it seems .NET 9 supports ARM32: https://github.com/dotnet/runtime/discussions/71042#discussioncomment-6745103

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs:1928]: `ProcessorArchitecture` only has `arm`.  So module manifests can't specify arm32 vs arm64.  We could allow for either arm32 or arm64, but while arm64 can run arm32, the opposite isn't true and will fail at runtime.

**Comment by iSazonov** [comment]
Can you please explain the purpose of this parameter in the manifest?
In my understanding of how this code works, this parameter is intended _only_ to tell the user that the module will not work on his system.
The fact is that the parameter is formal and subjective. In other words, the author must specify the value, although the _actual_ value is in the _assembly metadata_. Then the question arises why should we check a dummy value from the manifest (which may even contradict the actual one) when we could check the actual value from metadata? There is a universal rule "check the features at run time". I think we should rely on this rule. Over time, the number of supported architectures may increase (in addition, there may be dependencies on the type and version of the OS). 
So my suggestion is:
1. ignore this parameter in the manifest 
2. GetManifest should show the value from assembly metadata
3. Test-Manifest should compare the current architecture and the value from assembly metadata

**Review by daxian-dbw — APPROVED** [review]
