### PR TITLE
Make SemanticVersion compatible with SemVer 2.0

### LINKED ISSUE #5004: SMA SemanticVersion not SemVer 2 compliant
First: System.Management.Automation.SemanticVersion is not SemVer v2 compliant

Second: PowerShell releases are using SemVer v2 syntax

Therefore: `$PSVersionTable.PSVersion` is truncated and thus *broken*, as pre-release versions cannot be compared to each other (the only useful assertion possible is that the PSVersion is `-lt "6.0.0"`)

You should be using (an implementation like) Nuget.Core's Nuget.SemanticVersion which handles `-prerelease` and `+patch` as well as dotted versions like your `6.0.0-beta.7`

Note that both the tests below return TRUE if $SemVer is Nuget.SemanticVersion:

Steps to reproduce
------------------

```powershell
$SemVer = [System.Management.Automation.SemanticVersion]
("6.0.0-beta.10" -as $SemVer) -gt ("6.0.0-beta.7" -as $SemVer)
("6.0.0+fixes" -as $SemVer) -gt ("6.0.0-beta" -as $SemVer)
```

Expected behavior
-----------------

```none
True
True
```

Actual behavior
---------------

```none
False
False
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.7
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by iSazonov**
Fix #5004 

### Fix description

Made compatible with SymVer 2.0 http://semver.org/ (p.10)
Fixed comparisons
Refactored tests 
Added new tests

### Additional information
Useful sample https://github.com/maxhauser/semver/blob/master/src/Semver/SemVersion.cs
Related #2983

### CODE REVIEW

**Comment by daxian-dbw** [comment]
@JamesWTruher @PaulHigin Can you please review this PR?

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 1]
```diff
@@ -571,77 +659,127 @@ public static bool TryParse(string version, out SemanticVersion result)
...
+
+            string versionSansLabel = null;
+            var major=0;
+            var minor=0;
+            var patch=0;
+            string preLabel = null;
+            string buildLabel = null;
+
             var dashIndex = version.IndexOf('-');
+            var plusIndex = version.IndexOf('+');
```
Comment (PaulHigin) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: This parse code would be easier to read if it included comments with examples of expected version string.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 2]
```diff
@@ -571,77 +659,127 @@ public static bool TryParse(string version, out SemanticVersion result)
...
-                return false;
+                if (plusIndex == -1)
+                {
+                    // No buildLabel - buildLabel == null;
+                    preLabel = version.Substring(dashIndex+1);
+                    versionSansLabel = version.Substring(0, dashIndex);
+                }
+                else
+                {
+                    // No preLabel - preLabel == null;
```
Comment (PaulHigin) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: Can you add a comment that a hyphen character ('-') is allowed as part of the buildLabel (metadata) per the spec?  BTW why do you use "buildLabel" instead of "metadata" or "metadataLable" as referred to by the spec?

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 3]
```diff
@@ -571,77 +659,127 @@ public static bool TryParse(string version, out SemanticVersion result)
...
-            if (!Int32.TryParse(component, NumberStyles.Integer, CultureInfo.InvariantCulture, out parsedComponent))
+            if (match.Groups["patch"].Success && !int.TryParse(match.Groups["patch"].Value, out patch))
             {
-                result.SetFailure(ParseFailureKind.FormatException, component);
+                result.SetFailure(ParseFailureKind.FormatException);
                 return false;
             }
 
-            if (parsedComponent < 0)
+            if (preLabel != null && !Regex.IsMatch(preLabel, s_LabelUnitRegEx) ||
```
Comment (PaulHigin) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: I wonder if we should do this preLabel, buildLabel regex validation in the SemanticVersion constructor.  That way we can prevent malformed SemanticVersion objects from being created.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 4]
```diff
@@ -748,7 +882,6 @@ public override int GetHashCode()
         /// </summary>
         public static bool operator <(SemanticVersion v1, SemanticVersion v2)
         {
-            if ((object)v1 == null) throw PSTraceSource.NewArgumentException(nameof(v1));
```
Comment (PaulHigin) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: I feel we still need this check, otherwise v1.CompareTo will throw null reference exception.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 5]
```diff
@@ -757,7 +890,6 @@ public override int GetHashCode()
         /// </summary>
         public static bool operator <=(SemanticVersion v1, SemanticVersion v2)
         {
-            if ((object)v1 == null) throw PSTraceSource.NewArgumentException(nameof(v1));
```
Comment (PaulHigin) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: I feel we still need this check, otherwise v1.CompareTo will throw null reference exception.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 6]
```diff
@@ -766,15 +898,50 @@ public override int GetHashCode()
         /// </summary>
         public static bool operator >(SemanticVersion v1, SemanticVersion v2)
         {
-            return (v2 < v1);
+            return (v1.CompareTo(v2) > 0);
```
Comment (PaulHigin) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: We should check v1 for null value.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 7]
```diff
@@ -766,15 +898,50 @@ public override int GetHashCode()
...
         }
 
         /// <summary>
         /// Overloaded &gt;= operator
         /// </summary>
         public static bool operator >=(SemanticVersion v1, SemanticVersion v2)
         {
-            return (v2 <= v1);
+            return (v1.CompareTo(v2) >= 0);
```
Comment (PaulHigin) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: We should check v1 for null value.

**Review by PaulHigin — CHANGES_REQUESTED** [review]
I am not quite finished with the review.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 8]
```diff
@@ -384,12 +386,18 @@ IEnumerator IEnumerable.GetEnumerator()
     /// </summary>
     public sealed class SemanticVersion : IComparable, IComparable<SemanticVersion>, IEquatable<SemanticVersion>
     {
+        private static readonly string s_VersionSansRegEx = @"^(?<major>\d+)(\.(?<minor>\d+))?(\.(?<patch>\d+))?$";
```
[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Fixed.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 9]
```diff
@@ -398,8 +406,47 @@ public SemanticVersion(string version)
...
+            PreLabel = v.PreLabel;
+            BuildLabel = v.BuildLabel;
+        }
+
+        /// <summary>
+        /// Construct a SemanticVersion.
+        /// </summary>
+        /// <param name="major">The major version</param>
+        /// <param name="minor">The minor version</param>
+        /// <param name="patch">The minor version</param>
```
[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Fixed.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 10]
```diff
@@ -398,8 +406,47 @@ public SemanticVersion(string version)
...
+        {
+            if (!string.IsNullOrEmpty(preLabel))
+            {
+                if (preLabel.StartsWith('-') || preLabel.Contains("+")) throw new FormatException(nameof(preLabel));
+
+                PreLabel = preLabel;
+            }
+            else
+            {
+                PreLabel = null;
```
[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: I only thought about symmetry and better readability.

Removed.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 11]
```diff
@@ -410,17 +457,27 @@ public SemanticVersion(string version)
         /// <param name="patch">The minor version</param>
         /// <param name="label">The label for the version</param>
         /// <exception cref="PSArgumentException">
-        /// If <paramref name="major"/>, <paramref name="minor"/>, or <paramref name="patch"/> is less than 0.
-        /// </exception>
-        /// <exception cref="PSArgumentNullException">
-        /// If <paramref name="label"/> is null or an empty string.
+        /// <exception cref="FormatException">
+        /// If <paramref name="label"/> starts with '-'.
```
[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Complex RegEx is a puzzle for me too. I found some sample RegEx strings for SymVer but after testing I concluded that they all have bugs. 
So I split the SymVer regex string on some string (s_VersionSansRegEx, s_LabelRegEx, s_LabelUnitRegEx). This slightly increased the code but helped to avoid bugs.

Comment added.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 12]
```diff
@@ -521,22 +602,29 @@ public SemanticVersion(Version version)
         public int Patch { get; }
 
         /// <summary>
-        /// The last component in a SemanticVersion - may be null if not specified.
+        ///
         /// </summary>
-        public string Label { get; }
+        //public string Label { get; }
```
[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Removed.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 13]
```diff
@@ -521,22 +602,29 @@ public SemanticVersion(Version version)
...
+
+        public string PreLabel { get; }
```
[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Comments added.

File: src/System.Management.Automation/engine/PSVersionInfo.cs (hunk 1 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Comment added.

File: src/System.Management.Automation/engine/PSVersionInfo.cs (hunk 2 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Comments added and edited.

File: src/System.Management.Automation/engine/PSVersionInfo.cs (hunk 3 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: I wonder too why I checked only first char in constructors :-) I wonted to be fast. We should use RegEx.

Fixed.

File: src/System.Management.Automation/engine/PSVersionInfo.cs (hunk 4 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Fixed by new method Compare()

File: src/System.Management.Automation/engine/PSVersionInfo.cs (hunk 5 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Fixed.

File: src/System.Management.Automation/engine/PSVersionInfo.cs (hunk 6 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Fixed.

File: src/System.Management.Automation/engine/PSVersionInfo.cs (hunk 7 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Fixed.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 14]
```diff
@@ -680,16 +822,14 @@ public int CompareTo(SemanticVersion value)
             if (Patch != value.Patch)
                 return Patch > value.Patch ? 1 : -1;
 
-            if (Label == null)
```
[the remark this answers is not in the document]
Comment (PaulHigin) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Actually this PreLabel null check here can be removed since it is duplicated in ComparePreLabel().

[the remark this answers is not in the document]
Comment (PaulHigin) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: But please add the comment in ComparePreLabel() method.

**Review by PaulHigin — CHANGES_REQUESTED** [review]

File: src/System.Management.Automation/engine/PSVersionInfo.cs (hunk 14 above)
[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Duplicate checks was removed.
Comment was added.

**Comment by iSazonov** [comment]
I've rebased to resolve a merge conflict.

**Comment by daxian-dbw** [comment]
@anmenaga Can you please also review this PR? Thanks!

**Review by PaulHigin — APPROVED** [review]

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 15]
```diff
@@ -571,77 +647,142 @@ public static bool TryParse(string version, out SemanticVersion result)
...
-                : StringUtil.Format("{0}.{1}.{2}-{3}", Major, Minor, Patch, Label);
+            return versionString;
+        }
+
+        /// <summary>
+        /// Implement Compare.
+        /// </summary>
+        public static int Compare(SemanticVersion versionA, SemanticVersion versionB)
+        {
+            if (versionA == null) return -1;
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: what about versionA and versionB are both null?

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 16]
```diff
@@ -705,21 +839,18 @@ public override bool Equals(object obj)
...
         /// Override <see cref="object.GetHashCode()"/>
         /// </summary>
         public override int GetHashCode()
         {
-            return Utils.CombineHashCodes(
-                Major.GetHashCode(),
-                Minor.GetHashCode(),
-                Patch.GetHashCode(),
-                Label == null ? 0 : Label.GetHashCode());
+            return versionString.GetHashCode();
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: `versionString` could be null when running this method.
Besides, if we use the hashcode of  `versionString` for the SemanticVersion, we would have a hashcode collision, would that be a problem? Why not continue to use `Utils.CombineHashCodes`?

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 17]
```diff
@@ -748,33 +879,67 @@ public override int GetHashCode()
...
+                var isNumber1 = Int32.TryParse(ac, out number1);
+                var isNumber2 = Int32.TryParse(bc, out number2);
+
+                if (isNumber1 && isNumber2)
+                {
+                    if (number1 != number2) { return number1 < number2 ? -1 : 1; }
+                }
+                else
+                {
+                    if (isNumber1) { return -1; }
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: It would be great if you can add comment here saying that "Numeric identifiers always have lower precedence than non-numeric identifiers. "

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 18]
```diff
@@ -384,12 +386,18 @@ IEnumerator IEnumerable.GetEnumerator()
     /// </summary>
     public sealed class SemanticVersion : IComparable, IComparable<SemanticVersion>, IEquatable<SemanticVersion>
     {
+        private const string s_VersionSansRegEx = @"^(?<major>\d+)(\.(?<minor>\d+))?(\.(?<patch>\d+))?$";
+        private const string s_LabelRegEx = @"^((?<preLabel>[0-9A-Za-z][0-9A-Za-z\-\.]*))?(\+(?<buildLabel>[0-9A-Za-z][0-9A-Za-z\-\.]*))?$";
+        private const string s_LabelUnitRegEx = @"^[0-9A-Za-z][0-9A-Za-z\-\.]*?$";
```
[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: `s_` was removed.
`?` was removed - I think it is bug in any case.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 19]
```diff
@@ -398,8 +406,39 @@ public SemanticVersion(string version)
...
+        /// <summary>
+        /// Construct a SemanticVersion.
+        /// </summary>
+        /// <param name="major">The major version</param>
+        /// <param name="minor">The minor version</param>
+        /// <param name="patch">The patch version</param>
+        /// <param name="preLabel">The preLabel for the version</param>
+        /// <param name="buildLabel">The buildLabel for the version</param>
+        /// <exception cref="FormatException">
+        /// If <paramref name="preLabel"/> starts with '-' ot contains '+'.
```
[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: I changed the comments because the code was changed previously.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 20]
```diff
@@ -521,22 +591,28 @@ public SemanticVersion(Version version)
         public int Patch { get; }
 
         /// <summary>
-        /// The last component in a SemanticVersion - may be null if not specified.
+        /// PreLabel position in the SymVer string 'major.minor.patch-PreLabel+BuildLabel'.
+        /// </summary>
+
```
[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Done.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 21]
```diff
@@ -521,22 +591,28 @@ public SemanticVersion(Version version)
...
+        public string PreLabel { get; }
```
[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Replaced with `PreReleaseLabel` - it looks more readable.

File: src/System.Management.Automation/engine/PSVersionInfo.cs (hunk 15 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Good catch!

Fixed.

File: src/System.Management.Automation/engine/PSVersionInfo.cs (hunk 16 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: null - fixed.

versionString is relatively short string - why you believe that CoreFX implementation of `String.GetHashCode()` so bad that we should make more complex hashcode?

File: src/System.Management.Automation/engine/PSVersionInfo.cs (hunk 17 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: I copy-paste all text from the standard.

File: src/System.Management.Automation/engine/PSVersionInfo.cs (hunk 16 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: What I mean is the hashcode of a SemanticsVersion instance would be the same of the hashcode of a string (the versionString), so there is a collision in terms that 2 different objects have the same hashcode.

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/DotNetTypes_format_ps1xml.cs [hunk 22]
```diff
@@ -478,6 +486,46 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_System_Version()
...
+                    .AddHeader(width: 6)
+                    .AddHeader(width: 6)
+                    .AddHeader(width: 6)
+                    .AddHeader(width: 9)
+                    .AddHeader(width: 11)
+                    .StartRowDefinition()
+                        .AddPropertyColumn("Major")
+                        .AddPropertyColumn("Minor")
+                        .AddPropertyColumn("Patch")
+                        .AddPropertyColumn("PreLabel")
```
Comment (daxian-dbw) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/DotNetTypes_format_ps1xml.cs]: The property name has changed to 'PrereleaseLabel'.

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/DotNetTypes_format_ps1xml.cs [hunk 23]
```diff
@@ -478,6 +486,46 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_System_Version()
...
+                    .AddHeader(width: 6)
+                    .AddHeader(width: 8)
+                    .AddHeader(width: 26)
+                    .AddHeader(width: 27)
+                    .StartRowDefinition()
+                        .AddPropertyColumn("Major")
+                        .AddPropertyColumn("Minor")
+                        .AddPropertyColumn("Build")
+                        .AddPropertyColumn("Revision")
+                        .AddPropertyColumn("PSSemanticVersionPreLabel")
```
Comment (daxian-dbw) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/DotNetTypes_format_ps1xml.cs]: Would it make sense to change this property name to `PSSemanticVersionPrereleaseLabel`?

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 24]
```diff
@@ -398,8 +406,39 @@ public SemanticVersion(string version)
...
+        /// <param name="major">The major version</param>
+        /// <param name="minor">The minor version</param>
+        /// <param name="patch">The patch version</param>
+        /// <param name="preLabel">The preLabel for the version</param>
+        /// <param name="buildLabel">The buildLabel for the version</param>
+        /// <exception cref="FormatException">
+        /// If <paramref name="preLabel"/> don't match 'LabelUnitRegEx'.
+        /// If <paramref name="buildLabel"/> don't match 'LabelUnitRegEx'.
+        /// </exception>
+        public SemanticVersion(int major, int minor, int patch, string preLabel, string buildLabel)
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: Shall we rename `preLabel` to `prereleaseLabel` too? It's the parameter of a public method.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 25]
```diff
@@ -384,12 +386,18 @@ IEnumerator IEnumerable.GetEnumerator()
     /// </summary>
     public sealed class SemanticVersion : IComparable, IComparable<SemanticVersion>, IEquatable<SemanticVersion>
     {
+        private const string VersionSansRegEx = @"^(?<major>\d+)(\.(?<minor>\d+))?(\.(?<patch>\d+))?$";
+        private const string LabelRegEx = @"^((?<preLabel>[0-9A-Za-z][0-9A-Za-z\-\.]*))?(\+(?<buildLabel>[0-9A-Za-z][0-9A-Za-z\-\.]*))?$";
+        private const string LabelUnitRegEx = @"^[0-9A-Za-z][0-9A-Za-z\-\.]*$";
+        private const string PreLabelPropertyName = "PSSemanticVersionPreLabel";
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: Same here. We probably should use `PSSemanticVersionPrereleaseLabel`, since it's for a public property.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 26]
```diff
@@ -571,77 +646,154 @@ public static bool TryParse(string version, out SemanticVersion result)
...
+
+            return versionString;
+        }
+
+        /// <summary>
+        /// Implement Compare.
+        /// </summary>
+        public static int Compare(SemanticVersion versionA, SemanticVersion versionB)
+        {
+            if (versionA != null) {
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: Minor comment: it's better to follow the same open curly brace style in this file.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 27]
```diff
@@ -571,77 +646,154 @@ public static bool TryParse(string version, out SemanticVersion result)
...
+                if (versionB != null)
+                {
+                    return versionA.CompareTo(versionB);
+                }
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: The instance method `CompareTo` handles null value in it, so this `versionB != null` check is not needed. It can just be:
```
if (versionA != null)
{
    return versionA.CompareTo(versionB);
}

if (versionB != null)
{
    return -1;
}

return 0;
```

**Comment by daxian-dbw** [comment]
I still have a concern about the `GetHashCode()` method. See my new comment at https://github.com/PowerShell/PowerShell/pull/5037#discussion_r149441925

**Comment by daxian-dbw** [comment]
@SteveL-MSFT This PR changes the public APIs, including:
- Add a public constructions `public SemanticVersion(int major, int minor, int patch, string preLabel, string buildLabel)`
- Remove public property `Label` and add two public properties `PreReleaseLabel` and `BuildLabel`.
- Add a public method `public static int Compare(SemanticVersion versionA, SemanticVersion versionB)`

Do you think it needs the committee review?

File: src/System.Management.Automation/engine/Types_Ps1Xml.cs [hunk 28]
```diff
@@ -1982,6 +1982,22 @@ public static IEnumerable<TypeData> Get()
             var td251 = new TypeData(@"Deserialized.System.Management.Automation.DebuggerCommandResults", true);
             td251.TargetTypeForDeserialization = typeof(Microsoft.PowerShell.DeserializingTypeConverter);
             yield return td251;
+
+            var td252 = new TypeData(@"System.Version#IncludeLabel", true);
+            td252.Members.Add("ToString",
+                new ScriptMethodData(@"ToString", GetScriptBlock(@"
+          $suffix = """"
+          if (![String]::IsNullOrEmpty($this.PSSemanticVersionPreLabel))
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/Types_Ps1Xml.cs]: This needs to be changed if the property name is changed.

**Comment by SteveL-MSFT** [comment]
@daxian-dbw the general guidance is that for small api changes, the code review process is sufficient.  However, any maintainer can request Committee review if needed or if the contributors for the code review can't come to an agreement.

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/DotNetTypes_format_ps1xml.cs (hunk 23 above)
Comment (iSazonov) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/DotNetTypes_format_ps1xml.cs]: Looks very long 😕

**Comment by iSazonov** [comment]
SemanticVersion API is new in PowerShell Core so until RTM we can change it free if we need.

**Comment by daxian-dbw** [comment]
I'm fine with the API changes in this PR.

File: src/System.Management.Automation/engine/PSVersionInfo.cs (hunk 16 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: In the [docs](https://msdn.microsoft.com/en-us/library/system.object.gethashcode%28v=vs.110%29.aspx) I don't found that the hash must be different for different objects of different types. It seems we follow the docs - it will be work well with Dictionary and Hashtable types.

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/DotNetTypes_format_ps1xml.cs (hunk 23 above)
Comment (iSazonov) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/DotNetTypes_format_ps1xml.cs]: Maybe ` PSSemVerPreReleaseLabel `?

Comment (daxian-dbw) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/DotNetTypes_format_ps1xml.cs]: That looks good to me, especially `semver` is the type accelerator for `SemanticVersion`.

Comment (iSazonov) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/DotNetTypes_format_ps1xml.cs]: Fixed.

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/DotNetTypes_format_ps1xml.cs (hunk 22 above)
Comment (iSazonov) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/DotNetTypes_format_ps1xml.cs]: Fixed.

File: src/System.Management.Automation/engine/PSVersionInfo.cs (hunk 25 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Fixed.

File: src/System.Management.Automation/engine/PSVersionInfo.cs (hunk 24 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Renamed.

File: src/System.Management.Automation/engine/PSVersionInfo.cs (hunk 26 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Fixed.

File: src/System.Management.Automation/engine/PSVersionInfo.cs (hunk 27 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Fixed.

File: src/System.Management.Automation/engine/PSVersionInfo.cs (hunk 16 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/PSVersionInfo.cs]: Maybe I'm just overthinking it. Let's keep it as is.

File: .vscode/tasks.json [hunk 29]
```diff
@@ -1,6 +1,6 @@
 {
     "version": "0.1.0",
-    "command": "pwsh",
+    "command": "powershell",
```
Comment (daxian-dbw) [inline .vscode/tasks.json]: Please revert this change.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 30]
```diff
@@ -530,10 +530,10 @@ public SemanticVersion(Version version)
             Minor = version.Minor;
             Patch = version.Build == -1 ? 0 : version.Build;
             var psobj = new PSObject(version);
-            var preLabelNote = psobj.Properties[PreLabelPropertyName];
-            if (preLabelNote != null)
+            var PreReleaseLabelNote = psobj.Properties[PreLabelPropertyName];
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: A local variable name should start with a lower-case letter.
In fact, I think you can continue to use `preLabel` for any non-public members.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 31]
```diff
@@ -387,10 +387,10 @@ IEnumerator IEnumerable.GetEnumerator()
     public sealed class SemanticVersion : IComparable, IComparable<SemanticVersion>, IEquatable<SemanticVersion>
     {
         private const string VersionSansRegEx = @"^(?<major>\d+)(\.(?<minor>\d+))?(\.(?<patch>\d+))?$";
-        private const string LabelRegEx = @"^((?<preLabel>[0-9A-Za-z][0-9A-Za-z\-\.]*))?(\+(?<buildLabel>[0-9A-Za-z][0-9A-Za-z\-\.]*))?$";
+        private const string LabelRegEx = @"^((?<PreReleaseLabel>[0-9A-Za-z][0-9A-Za-z\-\.]*))?(\+(?<buildLabel>[0-9A-Za-z][0-9A-Za-z\-\.]*))?$";
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: Same here, I think it's OK to use `preLabel` here.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 32]
```diff
@@ -656,7 +656,7 @@ private static bool TryParseVersion(string version, ref VersionResult result)
             var major=0;
             var minor=0;
             var patch=0;
-            string preLabel = null;
+            string PreReleaseLabel = null;
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: Same here. Local variable should start with lower case letter.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 33]
```diff
@@ -917,7 +914,7 @@ public override int GetHashCode()
             return (Compare(v1, v2) >= 0);
         }
 
-        private static int ComparePreLabel(string preLabel1, string preLabel2)
+        private static int ComparePreLabel(string PreReleaseLabel1, string PreReleaseLabel2)
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: Same here. parameter names.

**Review by daxian-dbw — COMMENTED** [review]
It looks to me you just simply replaced `preLabel` with `PreReleaseLabel` and didn't care about the local variables and parameter names. Local variable names and parameter names should start with a lower case letter. I will fix it for you.

**Review by daxian-dbw — APPROVED** [review]

**Comment by daxian-dbw** [comment]
The test failure in AppVeyor is a known issue and will be fixed by #5379 
Travis CI passed, but it's not updated here.

**Comment by iSazonov** [comment]
😕  Sorry, I forgot to set VS Code case-sensitive flag to search and replace.

**Comment by daxian-dbw** [comment]
The macOS CI was shown as passed yesterday after clicking the Travis CI "Details" link. I have no idea why it's shown as canceled today. Now we seem to have a problem with macOS CI -- it takes forever to start.

Given that I know the Travis CI previously passed, I will merge this PR.
