### PR TITLE
Fix up buffer management getting network roots

### LINKED ISSUE #21064: Get-PSDrive returns incorrect DisplayRoot property for mounted drive letters in 7.4.1
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When running this for a network-mounted drive letter

```powershell
Get-PSDrive -Name V | Select-Object DisplayRoot
```

The output is incorrect, because the value of the property is incorrect (padded with NULs up to some length):

image

The output from Windows PowerShell 5.1 is correct:

image

Here's the culprit:

image

This is linked to (the fix for) #19903 

### Expected behavior

```console
Get-PSDrive -Name V | Select-Object DisplayRoot

DisplayRoot
-----------
\\pnjnas\V
```

### Actual behavior

```console
Get-PSDrive -Name V | Select-Object DisplayRoot

DisplayRoot
-----------
\\pnjnas\V…
```

### Error details

_No response_

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by jborean93**
# PR Summary
Fixes the logic used when getting the PSDrive DisplayRoot for network PSDrive paths to exclude null terminators.

## PR Context
2nd attempt at fixes: https://github.com/PowerShell/PowerShell/issues/21064. Original was https://github.com/PowerShell/PowerShell/pull/21068.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
  - [x] None
  - **OR**
  - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
    - [ ] Experimental feature name(s): 
- **User-facing changes**
  - [x] Not Applicable
  - **OR**
  - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
  - [ ] N/A or can only be tested interactively
  - **OR**
  - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
  - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
  - **OR**
  - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
    - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
      - [ ] Issue filed: 
    - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
      - [ ] Issue filed: 
    - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
      - [ ] Issue filed: 
    - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
      - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/engine/Interop/Windows/WNetGetConnection.cs [hunk 1]
```diff
@@ -24,46 +24,44 @@ internal static int GetUNCForNetworkDrive(char drive, out string? uncPath)
...
-
 #if DEBUG
-            // In Debug mode buffer size is initially set to 3 and if additional buffer is required, the
-            // required buffer size is allocated and the WNetGetConnection API is executed with the newly
-            // allocated buffer size.
-            bufferSize = 3;
+            int testBufferSize = System.Management.Automation.Internal.InternalTestHooks.WNetGetConnectionBufferSize;
+            int bufferSize = testBufferSize == 0 ? MAX_PATH : testBufferSize;
+#else
+            int bufferSize = MAX_PATH;
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/Interop/Windows/WNetGetConnection.cs:31]: Since CI run tests only in Release config we should remove the `#if DEBUG`.
Also best practice is to allocate stackalloc with const and then slice if needed.

```c#
internal static int WNetGetConnectionBufferSize = -1; // Including terminate '\0'

...

int bufferSize = MAX_PATH;
Span<char> uncBuffer = stackalloc char[bufferSize];
if (InternalTestHooks.WNetGetConnectionBufferSize > 0)
{
    bufferSize = InternalTestHooks.WNetGetConnectionBufferSize;
    uncBuffer = uncBuffer.Slice(0, bufferSize);
}
```

File: test/powershell/Modules/Microsoft.PowerShell.Management/Get-PSDrive.Tests.ps1 [hunk 2]
```diff
@@ -78,4 +78,39 @@ Describe "Get-PSDrive for network path" -Tags "Feature","RequireAdminOnWindows"
         $drive.DisplayRoot | Should -BeExactly '\\localhost\c$\Windows'
         subst "$($PSDriveName):" /D
     }
+
+    It 'Check P/Invoke for WNetGetConnection with small buffer <SmallBuffer>' -Skip:(-not $IsWindows) -TestCases @(
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/Get-PSDrive.Tests.ps1:82]:
```suggestion
    It 'Check P/Invoke for WNetGetConnection with small buffer: <SmallBuffer>' -Skip:(-not $IsWindows) -TestCases @(
```

**Review by iSazonov — APPROVED** [review]
LGTM with one minor comment.

File: src/System.Management.Automation/engine/Interop/Windows/WNetGetConnection.cs [hunk 3]
```diff
@@ -24,46 +25,43 @@ internal static int GetUNCForNetworkDrive(char drive, out string? uncPath)
...
-#endif
-
             ReadOnlySpan<char> driveName = stackalloc char[] { drive, ':', '\0' };
-            Span<char> uncBuffer = stackalloc char[(int)bufferSize];
-            int errorCode = ERROR_NO_NETWORK;
-
-            try
+            int bufferSize = MAX_PATH;
+            Span<char> uncBuffer = stackalloc char[bufferSize];
+            if (InternalTestHooks.WNetGetConnectionBufferSize > 0)
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/Interop/Windows/WNetGetConnection.cs:31]: If `WNetGetConnectionBufferSize > MAX_PATH` there will be an exception in line 34.
```suggestion
            if (InternalTestHooks.WNetGetConnectionBufferSize > 0 && InternalTestHooks.WNetGetConnectionBufferSize <= MAX_PATH)
```

**Review by iSazonov — CHANGES_REQUESTED** [review]
@jborean93 Please address two comments - we are near to merge.

**Review by iSazonov — APPROVED** [review]

**Comment by jborean93** [comment]
Thanks for the review and merge @iSazonov. Any chance to mark this as a backport candidate?
