### PR TITLE
Expose file attributes of OneDrive placeholders

### LINKED ISSUE #8315: Some bits in the file attributes are masked out
Files in the OneDrive sync folder with the "Files on Demand" feature make use of a number of specific attribute bits, such as:

0x00000200 | SparseFile
0x00000400 | ReparsePoint
0x00001000 | Offline
0x00080000 | Pinned
0x00100000 | Unpinned

(non-exhaustive list)

In PowerShell 6.1, some of the bits are masked out, so code that runs in Windows PowerShell 5.1 will not run correctly under PowerShell 6.1.

(this might be related to underlying .NET Core behavior, but the PS6 user… doesn't care ;-) )

# Steps to reproduce

Run the following commands under PowerShell 6.1:

```
"'{0:x}' -f (gi 'C:\Users\steph\OneDrive\Always keep on this device.txt').Attributes
"'{0:x}' -f (gi 'C:\Users\steph\OneDrive\Free up space.txt').Attributes
```

# Expected behavior

The output should be:
```
00080420
00401620
```
like in Windows PowerShell 5.1.

# Actual behavior
Instead, PowerShell 6.1 outputs:

```
00080020
00400020
```

# Environment data

```
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by sba923**
## PR Summary

Fix #8315.

PowerShell Core must "expose" the OneDrive placeholders so as to make all their attributes visible

This is done by changing the "placeholder compatibility mode" to PHCM_EXPOSE_PLACEHOLDERS

## PR Context  

Without this change, PowerShell Core isn't backwards-compatible with Windows PowerShell: the attributes returned for OneDrive placeholders are not the same as in PS5.1

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.  
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**  
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [X] can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 1]
```diff
@@ -341,6 +341,22 @@ public string GetHelpMaml(string helpItemName, string path)
...
+        static extern sbyte RtlQueryProcessPlaceholderCompatibilityMode();
+        [DllImport("ntdll.dll")]
+        static extern sbyte RtlSetProcessPlaceholderCompatibilityMode(sbyte pcm);
+
+        const sbyte PHCM_APPLICATION_DEFAULT = 0;
+        const sbyte PHCM_DISGUISE_PLACEHOLDER = 1;
+        const sbyte PHCM_EXPOSE_PLACEHOLDERS = 2;
+        const sbyte PHCM_MAX = 2;
+        const sbyte PHCM_ERROR_INVALID_PARAMETER = -1;
+        const sbyte PHCM_ERROR_NO_TEB = -2;
```
Comment (vexx32) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Seems like you could define an enum type for this purpose? The PHCM_MAX constant would either be implicit or a duplicate/Alias definition to the EXPOSE_PLACEHOLDERS value.

**Review by vexx32 — COMMENTED** [review]
Nice work!

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 2]
```diff
@@ -341,6 +341,22 @@ public string GetHelpMaml(string helpItemName, string path)
         #endregion
 
         #region CmdletProvider members
+        // OneDrive placeholder support (issue #8315)
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]:
```suggestion
        // OneDrive placeholder support
```

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 3]
```diff
@@ -341,6 +341,22 @@ public string GetHelpMaml(string helpItemName, string path)
...
+#if !UNIX
+        [DllImport("ntdll.dll")]
+        static extern sbyte RtlQueryProcessPlaceholderCompatibilityMode();
+        [DllImport("ntdll.dll")]
+        static extern sbyte RtlSetProcessPlaceholderCompatibilityMode(sbyte pcm);
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Should the type be char?
https://docs.microsoft.com/en-us/cpp/dotnet/calling-native-functions-from-managed-code?view=vs-2017
```suggestion
        internal static extern char RtlSetProcessPlaceholderCompatibilityMode(char pcm);
```

Also please use `internal static`.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 1 above)
Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs]: I do not see the need.

Please use `internal const`.

**Review by iSazonov — COMMENTED** [review]
I'm not sure that we can add tests.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 1 above)
Comment (sba923) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs]: An enum indeed seems like overkill given that I need only two of the values I got from `ntifs.h`

Added `internal`

**Comment by sba923** [comment]
Strange: I've updated the code, and CodeFactor (still) reports issues that refer to the previous version of the code... What am I missing?

**Comment by vexx32** [comment]
Hmm... Looks like it's complaining mainly about the constants not being marked as internal/private/public. I think Ilya recommended they should all be `internal`?

You can probably ignore the complaints about names with underscores, though; I think that's a common style in this repo and they'll probably adjust the style rules for it sooner or later. 😄

**Comment by sba923** [comment]
I was actually fighting... my git ignorance.

Now that my changes have been pushed again, CodeFactor has run again and reports only 8 issues.

Checking them out.

**Comment by vexx32** [comment]
@sba923 most of the time, yeah, but this isn't the first time I've seen it come up with issues that the PS team and maintainers don't necessarily agree with.

If you're more or less done (check that failing test on the Windows CI and see if you can figure that one out and resolve if it's something your changes might have affected), just remove the WIP flag and ping the codeowners for further review.

If those issues are a problem they'll let you know. 🙂

**Comment by sba923** [comment]
I think I'm gonna need some help...

```
Current placeholder compatibility mode: 1 (PHCM_DISGUISE_PLACEHOLDER)
Attributes for 'C:\Users\steph\OneDrive\test\alwaysavailable.xml': 0x00080020
Creation of symbolic link 'c:\temp\link1' to 'd:\tmp' with flags 1 FAILED
Creation of symbolic link 'c:\temp\link2' to 'd:\tmp' with flags 3 SUCCEEDED
Setting placeholder compatibility mode to: 2 (PHCM_EXPOSE_PLACEHOLDERS)
Attributes for 'C:\Users\steph\OneDrive\test\alwaysavailable.xml': 0x00080420
Creation of symbolic link 'c:\temp\link3' to 'd:\tmp' with flags 1 FAILED
Creation of symbolic link 'c:\temp\link4' to 'd:\tmp' with flags 3 SUCCEEDED
```
Everything's expected (my machine has developer mode enabled).

The behavior of CreateSymlink() is unaffected by the placeholder mode.

How could I debug that failing test in CI?

**Comment by sba923** [comment]
??? reverted to the initial code, Windows CI now succeeds...

**Comment by iSazonov** [comment]
@sba923 
CodeFactor is not mandatory.
Please use our code guidelines https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/coding-guidelines.md#naming-conventions
Maintainers will ask you to fix style issues if needed.

**Comment by sba923** [comment]
I've changed the code to get rid of the last two issues with underscores, but I could revert to the names from the SDK #define's to make the code more understandable. What do you think?

**Comment by iSazonov** [comment]
@sba923  Yes, our guidelines say:
> The only exception is for interop code where the constant should exactly match the name and value of the code you are calling via interop (e.g. const int ERROR_SUCCESS = 0).

**Comment by sba923** [comment]
OK, will change that back (which will bring two CodeFactor issues back).

BTW you asked me earlier to change `sbyte` to `char` because [https://docs.microsoft.com/en-us/cpp/dotnet/calling-native-functions-from-managed-code?view=vs-2017](url) says the managed type for `CHAR` is `char`. But for these particular APIs, some return values (that I don't use in the code for now) are negative, something `char` doesn't allow--that's why my prototype C# code was using `sbyte` (I was also following [https://manski.net/2012/06/pinvoke-tutorial-passing-parameters-part-3/#marshalling-primitive-data-types](url)). Should I stick to `char `or revert to `sbyte` to be "more compatible with the underlying native APIs" and more "future proof"?

**Comment by iSazonov** [comment]
@sba923 My understanding is that C++ CHAR is C# char and has 2 byte length so we can not use sbyte. I am ok with using char - we can always use cast to int to check result code.

**Comment by vexx32** [comment]
@iSazonov if the C++ CHAR has 2-byte length and as @sba923 says is returning some negative values in this instance, wouldn't a `short` type be preferable here?

**Comment by sba923** [comment]
IIRC CHAR is a typedef for C/C++ char which is a signed 8-bit type, so *not* the same as C# char which is a UTF-16 2-byte character. TBC once I'm in front of my PC 😜

**Comment by iSazonov** [comment]
I expected that there is auto marshalling for char but it is not blittable. So you are right and it should be sbyte.

**Comment by sba923** [comment]
OK. I'll revert to the initial code then ;-)

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 4]
```diff
@@ -372,6 +386,20 @@ protected override ProviderInfo Start(ProviderInfo providerInfo)
                         s_tracer.WriteLine("Not setting home directory {0} - does not exist", homeDirectory);
                 }
             }
+           
+            // OneDrive placeholder support (issue #8315)
+            // make it so OneDrive placeholders are perceived as such with *all* their attributes accessible
+#if !UNIX
+            Version minBuildForPlaceHolderAPIs = new Version(10, 0, 17134, 0);
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: This could be static to exclude allocations.

**Comment by sba923** [comment]
IMVHO this is executed only once at provider initialization, so can't that remain as is?

**Comment by sba923** [comment]
I think you've lost me with "the class is created for every operation."

I've checked (with tracing) that this code (the `Start()` method of the filesystem provider) is called only once at PowerShell initialization.

So there's no performance impact of calling this `new()` to create the non-static `Version` object.

If by "previous code with if" you mean:

```
            if (((Environment.OSVersion.Version.Major == 10) && (Environment.OSVersion.Version.Build >= 17134)) ||
                (Environment.OSVersion.Version.Major >= 11))
```

Yes, this is probably slightly cheaper because this doesn't create a `Version` object and doesn't invoke `Version`'s overloaded `>=` operator.

I made the change because someone made a similar change elsewhere in the very same file, and I found this more readable / elegant.

**Comment by iSazonov** [comment]
@sba923 FileSystemProvider is created for every file operation. ProviderInfo is create once per session. You put the fix in ProviderInfo so the fix is LGTM.

**Review by iSazonov — APPROVED** [review]

**Comment by sba923** [comment]
Everything's green, except for CodeFactor.

What's still blocking the PR from merging?

**Comment by iSazonov** [comment]
@sba923 CodeFactor is not mandatory. @anmenaga was assigned so wait for his conclusion - merge or ask additional review.

**Comment by sba923** [comment]
OK, fine.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 5]
```diff
@@ -341,6 +341,20 @@ public string GetHelpMaml(string helpItemName, string path)
         #endregion
 
         #region CmdletProvider members
+        // OneDrive placeholder support
+#if !UNIX
```
Comment (anmenaga) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: In this case it is very easy to fix the Code Factor violation "Field names must not contain underscores."
Same file `FileSystemProvider.cs` already has `private static class NativeMethods`, so please move this new P/Invoke things there. Thank you.

Here is the guidance from Code Factor:

> If the field or variable name is intended to match the name of an item associated with Win32 or COM, and thus needs to include underscores, place the field or variable within a special NativeMethods class. A NativeMethods class is any class which contains a name ending in NativeMethods, and is intended as a placeholder for Win32 or COM wrappers. StyleCop will ignore this violation if the item is placed within a NativeMethods class.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 4 above)
Comment (anmenaga) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: It would be good to have an explicit comment on top of this line like `// The ProcessPlaceholderCompatibilityMode APIs are only available on Win10 build 17134 or newer`.

**Review by anmenaga — CHANGES_REQUESTED** [review]

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 5 above)
Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs]: We already have some NativeMethods classes and could consider reusing one.

**Comment by sba923** [comment]
Code changes made.

`.\test\common\markdown\markdown-link.tests.ps1` fails in CI but succeeds locally. What's going on?

**Comment by iSazonov** [comment]
I can not open https://blogs.msdn.microsoft.com/kebab/2013/06/09/an-introduction-to-error-handling-in-powershell/ - seems the site temporary broken in the time.

**Comment by sba923** [comment]
How's that related to the failing test?

**Comment by sba923** [comment]
How's that related to the failing test?

**Comment by sba923** [comment]
Oops... Hadn't checked what those links were...

**Comment by sba923** [comment]
Codacy has been pending for 7 hours... anything wrong there?

What about my test script question?

**Comment by sba923** [comment]
Codacy doesn't look disabled to me, it says "Pending  — Hang in there, Codacy is reviewing your Pull request."

I will look into the testing approach you're suggesting. The code I shared earlier assumes the test file is created under the OneDrive sync folder, which causes the OneDrive plumbing to set some of the attributes that get maskes by the "placeholder compatibility" mechanism. I could indeed try to create a file "anywhere" with those bits set, and see what PSCore and WinPS return for that same file.

**Comment by vexx32** [comment]
Yeah, I'm sure if you push another commit it probably will go away. It's just an issue of Github only updating those when a commit is made, or the tool itself updates the status (which it won't if it's been disabled).

**Comment by anmenaga** [comment]
Restarted 'PowerShell-CI-static-analysis' as the error is unrelated and was fixed by another PR.

**Review by anmenaga — APPROVED** [review]

**Comment by anmenaga** [comment]
@sba923 Thank you for your contribution!

**Comment by iSazonov** [comment]
@adityapatwardhan Could you please help with the test? Make sense to add it?

**Comment by sba923** [comment]
Note that I haven't been able to find a way to create test files with the appropriate attributes, outside of the OneDrive client's sync folder, from the test script (yet). Without this, it's not possible to run the test in an automated way.

FWIW, here's the current version of the script:

```
# test fix for PowerShell Core issue #8315
# https://github.com/PowerShell/PowerShell/issues/8315
#
# fix implemented by PR #8745
# https://github.com/PowerShell/PowerShell/pull/8745
#
# Can't be tested by Windows CI since it lacks the proper environment
# (OneDrive desktop client sync directory)

$iswinps = ($null, 'Desktop') -contains $PSVersionTable.PSEdition
if ($iswinps)
{
    Write-Host -ForegroundColor Yellow ("This script requires PowerShell Core")
    Exit(1)
}


if ($null -eq (Get-Process -Name 'OneDrive' -ErrorAction SilentlyContinue))
{
    Write-Host -ForegroundColor Yellow ("OneDrive not running")
    Exit(1)
}

if ( `
    ($null -ne $env:OneDrive) `
        -and ($env:OneDrive -ne '') `
        -and (Test-Path -LiteralPath $env:OneDrive -PathType Container) `
)
{
    # create a test file under the OneDrive sync folder
    $testfile = Join-Path -Path $env:OneDrive -ChildPath ("pwsh-8315-test-file-{0:yyyyMMddHHmmss}.txt" -f [datetime]::Now)
    if (!(Test-Path -LiteralPath $testfile))
    {
        "some data" | Out-File -LiteralPath $testfile -Encoding utf8
    }

    # make the testfile "Always available on this device"
    & attrib +P -U $testfile

    # wait until end of sync so that attributes don't change between the two times they're retrieved below
    Start-Sleep  -Seconds 15

    # get the attributes using the current (PowerShell Core) host
    $pscoreattributes = "0x{0:x8}" -f ([int](Get-Item -LiteralPath $testfile).Attributes)

    # get the attributes using Windows PowerShell
    $winpsattributes = & powershell -noprofile -command ('"{0x{0:x8}}" -f ([int] (Get-Item -LiteralPath "' + $testfile + '").Attributes)')

    # check that the attributes contain at least one of the bits that are masked off if the placeholder mode is set to PHCM_DISGUISE_PLACEHOLDER
    if (($winpsattributes -band ([System.IO.FileAttributes]::SparseFile -bor [System.IO.FileAttributes]::ReparsePoint)) -eq 0)
    {
        Write-Host -ForegroundColor Red ("FAILURE: Cannot create suitable test file: attributes for '{0}' = {1}", $testfile, $winpsattributes)
    }
    else
    {
        # check they're identical
        if ($pscoreattributes -ne $winpsattributes)
        {
            Write-Host -ForegroundColor Red ("FAILURE: PowerShell Core attributes for '{0}' = {1}, Windows PowerShell attributes = {2}" -f $testfile, $pscoreattributes, $winpsattributes)
        }
        else
        {
            Write-Host -ForegroundColor Green ("SUCCESS: PowerShell Core attributes for '{0}' = {1}, Windows PowerShell attributes = {2}" -f $testfile, $pscoreattributes, $winpsattributes)
        }

    }


    Remove-Item -Force -LiteralPath $testfile
}

```

**Comment by jantari** [comment]
The placeholder compatibility mode and the masked file attributes do *NOT* just affect OneDrive.

I realize this is an old, long-merged PR but it still turns up on Google when researching this topic so I wanted to clarify. For example, I encountered this behavior with Windows' built-in [Workfolders](https://learn.microsoft.com/en-us/windows-server/storage/work-folders/work-folders-overview) sync directory. It is my understanding that this attribute-masking is enacted on *all* directories and files under *any* Cloud-Sync-Engines' root sync directory. See: https://learn.microsoft.com/en-us/windows/win32/cfapi/cloud-files-api-portal

I believe the Nextcloud desktop client is another example that implements the "Cloud Files API" thus making it a "Cloud Sync Engine" that should evoke this behavior.

If someone really wants to add a test for this PR, I believe a Cloud-Sync-Engine program would have to be installed and configured in the PowerShell test environment, even if it is just some kind of [minimal dummy implementation](https://learn.microsoft.com/en-us/windows/win32/cfapi/build-a-cloud-file-sync-engine). Or if PowerShell builds are tested in an environment where a Windows Server is available, the aforementioned Workfolders Feature could be enabled and used which should be a lot simpler.
