### PR TITLE
Fix VtSubstring helper method to correctly check chars copied

### LINKED ISSUE #19231: Some rows are invisible in output of long string of «Select-String»
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
Host

Name             : ConsoleHost
Version          : 7.3.3
InstanceId       : b895a510-c2ac-4215-92f1-de9fcfe0c309
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : ru-RU
CurrentUICulture : ru-RU
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace


"12" + "1"*((((Host).UI.RawUI.WindowSize.Width - 1) * 3) - 2) | Select-String -Pattern "2"

12111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111

"12" + "1"*((((Host).UI.RawUI.WindowSize.Width - 1) * 3) - 1) | Select-String -Pattern "2"

12111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111

1
```

### Expected behavior

```console
All rows are visible.
```

### Actual behavior

```console
All rows are invisible except the first, second, and last rows.
```

### Error details

```console
Exception             :
    Type    : System.InvalidOperationException
    Message : You must specify an object for the Get-Member cmdlet.
    HResult : -2146233079
CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
InvocationInfo        :
    MyCommand        : Get-Member
    ScriptLineNumber : 1
    OffsetInLine     : 18
    HistoryId        : 31
    Line             : (Host).UI.Name | Get-Member
    PositionMessage  : At line:1 char:18
                       + (Host).UI.Name | Get-Member
                       +                  ~~~~~~~~~~
    InvocationName   : Get-Member
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

Couldn't figure out why `ru-ru` is affected as the code seems to should have been broken and nothing in the area was related to culture.  The problem was with a check to exit after copying the expected number of characters to a new buffer.  However, it was only looking at the offset which restarted at zero and would stop at the length, but it should only count when copying has started.

Manually validated that I could repro with `ru-ru` culture, but not with `en-us` culture and the fix does fix it in `ru-ru` culture as well as `en-us`.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/19231

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/utils/StringUtil.cs [hunk 1]
```diff
@@ -202,7 +202,7 @@ internal static string VtSubstring(this string str, int startOffset, int length,
                     }
 
                     // If the number of copied non-escape-sequence characters has reached the specified length, done copying.
-                    if (offset == length)
+                    if (copyStarted && offset == length)
```
Comment (daxian-dbw) [inline src/System.Management.Automation/utils/StringUtil.cs:205]: Thank you for fixing this! It's a hard one to track 😄

**Review by daxian-dbw — APPROVED** [review]
> Couldn't figure out why ru-ru is affected as the code seems to should have been broken and nothing in the area was related to culture.

It turns out the formatting code does branch based on culture:

https://github.com/PowerShell/PowerShell/blob/d554d06f57829bdd5ab09072788e967c68bee3d1/src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs#L437-L444

[Six pre-selected cultures](https://github.com/PowerShell/PowerShell/blob/d554d06f57829bdd5ab09072788e967c68bee3d1/src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs#L336) will go with the `if` block, including `en-US`. For `ru-RU` and other cultures, it will go with the `else` block. So, this `VtSubstring` method is not hit for this repro in the `en-US` culture.

**Comment by iSazonov** [comment]
> [Six pre-selected cultures](https://github.com/PowerShell/PowerShell/blob/d554d06f57829bdd5ab09072788e967c68bee3d1/src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs#L336) will go with the `if` block, including `en-US`. For `ru-RU` and other cultures, it will go with the `else` block. So, this `VtSubstring` method is not hit for this repro in the `en-US` culture.

I don't see reasons why `ru-RU` is not in the list. Since we don't split words itself the rules for splitting by words is the same - delimiters are space and tab.
