### PR TITLE
Remove duplicate modules from completion results

### LINKED ISSUE #5184: using module duplicate completions
### Prerequisites

- [x] I have written a descriptive issue title.
- [x] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [x] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [x] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [x] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [x] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

`using module` returns duplicates.

### PowerShell Version

```console
7.6-preview4
```

### Visual Studio Code Version

```console
1.100.0
19e0f9e681ecb8e5c09d8784acaa601316ca4571
x64
```

### Extension Version

```console
ms-vscode.powershell@2025.3.0
```

### Steps to Reproduce

Install a module with multiple versions and then create a ps1/psm1 script.

Type `using module` and the completions will be duplicated (most likely due to multiple versions being installed)

### Visuals

Image

### Logs

_No response_

### PR DESCRIPTION
**Pull request by MartinGC94**
# PR Summary
This PR adds a check to avoid adding the same module names again and again if multiple modules with the same name is found (multiple versions or multiple install locations) similar to this previous PR for command names: https://github.com/PowerShell/PowerShell/pull/21113

## PR Context
Fixes https://github.com/PowerShell/vscode-powershell/issues/5184

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge. If this PR is a work in progress, please open this as a [Draft Pull Request and mark it as Ready to Review when it is ready to merge](https://docs.github.com/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests).
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
  - [X] None
  - **OR**
  - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
    - [ ] Experimental feature name(s): 
- **User-facing changes**
  - [X] Not Applicable
  - **OR**
  - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [ ] Issue filed: 
- **Testing - New and feature**
  - [ ] N/A or can only be tested interactively
  - **OR**
  - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs [hunk 1]
```diff
@@ -524,6 +529,7 @@ internal static List<CompletionResult> CompleteModuleName(CompletionContext cont
                                   + moduleInfo.ModuleType.ToString() + "\r\nPath: "
                                   + moduleInfo.Path;
 
+                    string listItemText = completionText;
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:532]: We could remove at all, and use named argument below.

**Comment by iSazonov** [comment]
It seems there have already been PRs with duplicate removal in other places? Could you please add links to them in the PR description?

**Review by iSazonov — APPROVED** [review]
