### PR TITLE
Close pipe client handles after creating the child ssh process

### LINKED ISSUE #25203: Invoke-Command and New-PSSession hang indefinitely when ssh.exe unexpectedly terminates
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [x] Search the existing issues.
- [x] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [x] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This is trivially easy to reproduce by just trying to connect to a system that does not exist (e.g. `test@test`). However, it can also randomly happen when trying to connect to system that is rebooting, which is how I discovered it.

To prove that it's ssh process termination that triggers this bug, try running `Invoke-Command -HostName ...` with this running in the background:
```PowerShell
while ($true) {
    Start-Sleep -Milliseconds 500
    Stop-Process -Name "ssh" -ErrorAction SilentlyContinue -PassThru
}
```

The only workaround seems to be to use the `-ConnectingTimeout` parameter, but it just forces pwsh to wait the entire timeout duration, even though ssh.exe isn't even running.

### Expected behavior

```console
# It should behave exactly like ssh.exe:
PS C:\> ssh.exe test@test "echo 1"
ssh: Could not resolve hostname test: No such host is known.
PS C:\>
```

### Actual behavior

```console
PS C:\> Invoke-Command -HostName "test" -UserName "test" -ScriptBlock { echo 1 }
ssh: Could not resolve hostname test: No such host is known.

<Indefinite hang, need to press Ctrl+C to regain prompt, breaking non-interactive sessions>

# New-PSSession is also impacted:
PS C:\> New-PSSession -HostName "test" -UserName "test"
ssh: Could not resolve hostname test: No such host is known.

<hang>
# Also, -ErrorAction doesn't help:
PS C:\> Invoke-Command -HostName "test" -UserName "test" -ScriptBlock { echo 1 } -ErrorAction Stop
ssh: Could not resolve hostname test: No such host is known.

<hang>
```

### Error details

```console

```

### Environment data

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.5.0
PSEdition                      Core
GitCommitId                    7.5.0
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by daxian-dbw**
## PR Summary

Fix #25203
Fix https://github.com/PowerShell/PowerShell/issues/26228

**Symptom**

Running the following commands on Windows will hang indefinitely today.

- `Invoke-Command -HostName "test" -UserName "test" -ScriptBlock { 1 }`
- `New-PSSession -HostName "test" -UserName "test"`

The reported hang happens on Windows only. On Linux and macOS, both commands return to the prompt with an error written out.

**Root Cause**

What happens on Windows is -- the `ssh.exe` process already exited, but the `stdin` writer and `stdout/stderr` readers were not closed as expected. That led to the hang, as both the output and error reader threads were still blocked on the `reader.ReadLine` call.

This is because when creating the `ssh.exe` using the Win32 function `CreateProcess`, we don't close the client handles of the pipes (_`stdInPipeClient`, `stdOutPipeClient`, and `stdErrPipeClient`_) after they get inherited by the child process ([see code](https://github.com/PowerShell/PowerShell/blob/6928efb4c5224805c9d6f9fef5a20e26a20fd89c/src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs#L2776-L2843)).

When inherited by a child process, the parent side of those handles remain valid and unchanged. Windows duplicates that handle into the child process's handle table.

- The parent keeps its original handle.
- The child gets a new handle value (_different numeric value_) that refers to the same underlying kernel object.
- Both processes now have separate references to that object, each with its own handle entry.

So, when the child process `ssh.exe` exits, the pipe client handles in the child process are automatically closed. However, the pipe client handles in the parent process `powershell` are still open, so the pipes will remain functional and thus the pipe server handles (_i.e. the readers used in the stdout/stderr reading threads_) are still open. Therefore, the hang happens.

**Fix Changes**

To fix the issue, we need to close the parent side pipe client handles right after creating the `ssh.exe` process, so, only the `ssh.exe` process holds the handles of client side of the pipes. Then later, when `ssh.exe` exits, the client side of the pipe will be closed, which will, as expected, lead the server side of the pipes to be closed too.

The main changes of the fix are:

- Close the client pipe handles after creating the child process (by adding `lpStartupInfo.Dispose()` in the finally block).
- A bit cleanup of the redundant namespace-qualified usages of types (e.g., `System.Diagnostics.Process`, `System.IO.Path`, etc.)
- Added new tests to verify that PowerShell does not hang when attempting SSH connections to non-existent hosts.

### PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge. If this PR is a work in progress, please open this as a [Draft Pull Request and mark it as Ready to Review when it is ready to merge](https://docs.github.com/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests).
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
  - [x] None
  - **OR**
  - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
    - [ ] Experimental feature name(s): 
- **User-facing changes**
  - [x] Not Applicable
  - **OR**
  - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [ ] Issue filed: 
- **Testing - New and feature**
  - [ ] N/A or can only be tested interactively
  - **OR**
  - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

File: src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs [hunk 1]
```diff
@@ -2693,19 +2693,40 @@ private static int StartSSHProcessImpl(
...
+            {
+                try
+                {
+                    Utils.SafeDispose(stdInWriterVar);
+                    Utils.SafeDispose(stdOutReaderVar);
+                    Utils.SafeDispose(stdErrReaderVar);
+                }
+                catch
+                {
+                    // Ignore all exceptions in the event handler.
```
[the remark this answers is not in the document]
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: Addressed.

File: src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs [hunk 2]
```diff
@@ -1781,14 +1781,17 @@ private void CloseConnection()
             var connectionTimer = Interlocked.Exchange(ref _connectionTimer, null);
             connectionTimer?.Dispose();
 
+            // On Windows, the stdIn, stdOut, stdErr writer/readers are also disposed in the 'Exited' event of the ssh process.
+            // In that case, the 'Dispose' method could be called in parallel on them, which might result in a race condition.
+            // So, we handle their disposal here in a thread-safe manner.
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: From my understanding correctly implemented Dispose() is thread-safe.
StreamRead and StreamWrite come from standard library and have correctly implemented Dispose() method.

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: `Dispose()` should be idempotent but not necessarily thread safe.
However, after looking more into how `CloseConnection` is called, I think the chance of a race condition is low -- the `ssh.exe` is terminated at the same time when the connection is explicitly closed from PowerShell.

We have the output/error reader threads reading from the stdout/stdin `StreamReader` objects, on 2 separate threads, so technically, there is also possibility of race condition between the output/error reader threads and `CloseConnection`.

I've removed `SafeDispose` method, and am inclined to simply call `Dispose()` on the writer/readers in the `Exited` event.

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: I found the root cause of the issue. The parent's pipe client handles are not closed, which caused the pipe server handles to remain open after `ssh.exe` exits. See the updated PR descriptions for details.

**Review by iSazonov — APPROVED** [review]
Great!

One notice.
`PlatformInvokes.STARTUPINFO lpStartupInfo` is disposable too. It dispose the same handles but formally we should dispose it too.

**Comment by daxian-dbw** [comment]
Good point. Actually, disposing `lpStartupInfo` will dispose the parent side pipe client handles. So, I changed to just call `lpStartupInfo.Dispose()`.

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
I believe we need to backport the commit.

**Review by TravisEz13 — APPROVED** [review]

File: test/powershell/engine/Remoting/SSHRemotingCmdlets.Tests.ps1 [hunk 3]
```diff
@@ -70,3 +70,24 @@ Describe "SSHConnection parameter hashtable type conversions" -Tags 'Feature', '
         $err.FullyQualifiedErrorId | Should -Match 'PSSessionOpenFailed'
     }
 }
+
+Describe "No hangs when host doesn't exist" -Tag "CI" {
```
[the remark this answers is not in the document]
Comment (daxian-dbw) [reply test/powershell/engine/Remoting/SSHRemotingCmdlets.Tests.ps1]: Addressed.

**Review by TravisEz13 — APPROVED** [review]
