### PR TITLE
Fix `Minimal` ProgressView to handle Activity that is longer than console width

### LINKED ISSUE #15251: ProgressView Minimal - Copy-Item error when copying to/from pssession
I've had some errors when copying a file from my local machine to another machine using the ToSession argument. I haven't had time to troubleshoot it, but I was able to force the same error when going the other direction, copying from the remote session to my local machine using the FromSession argument.  

In the example below, if I shorten the directory name by one character, then the command succeeds.

## Steps to reproduce

```powershell
Copy-Item c:\temp\xxxxxxxxxx\web.config C:\tmp\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\web.config -FromSession $session
```

## Expected behavior

```none
successful copy
```

## Actual behavior

```none
Exception             :
    Type       : System.ArgumentOutOfRangeException
    Message    : Length cannot be less than zero. (Parameter 'length')
    ParamName  : length
    TargetSite :
        Name          : Substring
        DeclaringType : string
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    StackTrace :
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.PowerShell.ProgressNode.RenderAnsi(ArrayList strCollection, Int32 indentation, Int32 maxWidth)
   at Microsoft.PowerShell.ProgressNode.Render(ArrayList strCollection, Int32 indentation, Int32 maxWidth, PSHostRawUserInterface rawUI)
   at Microsoft.PowerShell.PendingProgress.RenderHelper(ArrayList strings, ArrayList nodes, Int32 indentation, Int32 maxWidth, PSHostRawUserInterface rawUI)
   at Microsoft.PowerShell.PendingProgress.Render(Int32 maxWidth, Int32 maxHeight, PSHostRawUserInterface rawUI)
   at Microsoft.PowerShell.ProgressPane.Show(PendingProgress pendingProgress)
   at Microsoft.PowerShell.ConsoleHostUserInterface.HandleIncomingProgressRecord(Int64 sourceId, ProgressRecord record)
   at Microsoft.PowerShell.ConsoleHostUserInterface.WriteProgress(Int64 sourceId, ProgressRecord record)
   at System.Management.Automation.Internal.Host.InternalHostUserInterface.WriteProgress(Int64 sourceId, ProgressRecord record)
   at System.Management.Automation.MshCommandRuntime.WriteProgress(Int64 sourceId, ProgressRecord progressRecord, Boolean overrideInquire)
   at System.Management.Automation.MshCommandRuntime.WriteProgress(ProgressRecord progressRecord, Boolean overrideInquire)
   at System.Management.Automation.MshCommandRuntime.WriteProgress(ProgressRecord progressRecord)
   at System.Management.Automation.Cmdlet.WriteProgress(ProgressRecord progressRecord)
   at System.Management.Automation.Provider.CmdletProvider.WriteProgress(ProgressRecord progressRecord)
   at Microsoft.PowerShell.Commands.FileSystemProvider.PerformCopyFileFromRemoteSession(String sourceFileFullName, FileInfo destinationFile, String destinationPath, Boolean force, PowerShell ps, Int64
fileSize, Boolean isAlternateDataStream, String streamName)
   at Microsoft.PowerShell.Commands.FileSystemProvider.CopyFileFromRemoteSession(String sourceFileName, String sourceFileFullName, String destinationPath, Boolean force, PowerShell ps, Int64 fileSize)
   at Microsoft.PowerShell.Commands.FileSystemProvider.CopyItemFromRemoteSession(String path, String destinationPath, Boolean recurse, Boolean force, PSSession fromSession)
   at Microsoft.PowerShell.Commands.FileSystemProvider.CopyItem(String path, String destinationPath, Boolean recurse)
   at System.Management.Automation.SessionStateInternal.CopyItem(CmdletProvider providerInstance, String path, String copyPath, Boolean recurse, CmdletProviderContext context)
    Source     : System.Private.CoreLib
    HResult    : -2146233086
CategoryInfo          : NotSpecified: (:) [Copy-Item], ArgumentOutOfRangeException
FullyQualifiedErrorId : System.ArgumentOutOfRangeException,Microsoft.PowerShell.Commands.CopyItemCommand
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.5
PSEdition                      Core
GitCommitId                    7.2.0-preview.5
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

The current code handles the case where `Status` is too long, but doesn't handle the case where `Activity` is longer than console width so that when calculating the space for status, it becomes a negative value.  Fix is to check if `Activity` is longer than the console width and truncate it so that it doesn't take up more than half the console width allowing space for the `Status`.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/15251

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs [hunk 1]
```diff
@@ -387,6 +387,12 @@ internal static bool IsMinimalProgressRenderingEnabled()
...
             }
 
+            // if the activity is really long, only use up to half the width
+            if (Activity.Length > maxWidth / 2)
+            {
+                Activity = Activity.Substring(0, maxWidth / 2) + PSObjectHelper.Ellipsis;
+            }
+
             // 4 is for the extra space and square brackets below and one extra space
             int barWidth = maxWidth - Activity.Length - indentation - 4;
```
Comment (iSazonov) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs:397]: 1. It doesn't cover all edge cases again.
2. We change Activity - what if user will expand Window width?
3. What about adding "..." on Activity end?

Comment (SteveL-MSFT) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs:397]: The `maxWidth` comes from [_bufsize](https://github.com/PowerShell/PowerShell/blob/658837323599ab1c7a81fe66fcd43f7420e4402b/src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressPane.cs#L218) which gets [retrieved](https://github.com/PowerShell/PowerShell/blob/658837323599ab1c7a81fe66fcd43f7420e4402b/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostRawUserInterface.cs#L348) from the console.  So if the Window width changes, this value will change and is read every time progress is rendered.

Adding `...` to end of Activity is not an issue as the max length of Activity is now half the window width + 1 character which in most cases will be fine.  There is an edge case where the window width is extremely narrow which I can fix.

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs [hunk 2]
```diff
@@ -387,14 +387,21 @@ internal static bool IsMinimalProgressRenderingEnabled()
                 maxWidth = PSStyle.Instance.Progress.MaxWidth;
             }
 
+            // if the activity is really long, only use up to half the width
+            if (Activity.Length > maxWidth / 2)
+            {
+                Activity = Activity.Substring(0, maxWidth / 2) + PSObjectHelper.Ellipsis;
```
Comment (iSazonov) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs:393]: My concern is that Activity is in ProgressRecord which could be reused over iterations. So we shouldn't change it.

**Review by iSazonov — COMMENTED** [review]
Another concern is the code very complex and we can catch issues with it again and again. Why not use old approach? (I mean RenderFullDescription)

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs [hunk 3]
```diff
@@ -387,14 +387,26 @@ internal static bool IsMinimalProgressRenderingEnabled()
                 maxWidth = PSStyle.Instance.Progress.MaxWidth;
             }
 
+            // if the activity is really long, only use up to half the width
+            string activity;
+            if (Activity.Length > maxWidth / 2)
+            {
+                activity = Activity.Substring(0, maxWidth / 2) + PSObjectHelper.Ellipsis;
```
Comment (iSazonov) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs:394]: Looking on Archive expand example in #14414 I think we break the scenario.

Comment (SteveL-MSFT) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs:394]: I just tried expand-archive with this branch and works fine with a narrow console window.  As expected, activity and status are truncated.

Comment (iSazonov) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs:394]: I guess they are truncated too early while there is still a lot of free space on the right.

Comment (SteveL-MSFT) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs:394]: The bar area is also used for Status text which can change as progress is being written.  So it's possible to fill up as much of Activity and Status as possible so whitespace is limited, it would also mean that the Status area would resize if the text changes which would make it hard to read.

Comment (iSazonov) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs:394]: I tried the build and I see the resizing scenario doesn't work at all. But this doesn't depend on the PR.
Run follow and use mouse to change windows width:
```powershell
1..100 | % { Write-Progress -Activity "123456789012345678901234567890123456789012345678901234567890" -Status "S" -PercentComplete $_ -SecondsRemaining $_ ; Sleep 1}
```
Results:
- after size changed (both left and right directions) the progress bar doesn't work
- screen destroyed 
- after the command finished (or Ctrl-C pressed) screen buffer destroyed 
- instead of final Ellipsis I see single dot (direct output Ellipsis works on the console

(only last related to the PR)

**Review by anmenaga — APPROVED** [review]
LGTM

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs (hunk 3 above)
Comment (daxian-dbw) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs:394]: @iSazonov Can you please take another look and see if you have any outstanding concerns for the changes in this particular PR? For the points you brought up above in https://github.com/PowerShell/PowerShell/pull/15264#discussion_r618048122, they look like out of the scope of this PR (correct me if I'm wrong), and maybe track them in a separate issue?

Comment (iSazonov) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs:394]: @daxian-dbw This removes the exception but I personally do not like the result of the display, although it is not fundamental. The fundamental thing is that the resizing scenario works horribly.  But I don't see the point of opening a new issue since MSFT team doesn't have the resources to fix 3000 issues anyway.

Comment (daxian-dbw) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs:394]: I opened #15407 to track the resizing issue.

> instead of final Ellipsis I see single dot (direct output Ellipsis works on the console

image

@SteveL-MSFT It does look weird to have a single dot instead of Ellipsis when truncation happens. Should that be addressed in this PR or you think it should be a separate one?

Comment (SteveL-MSFT) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs:394]: I'll take a look at the other issues in a separate PR since this specific issue is affecting users with real world scenarios

**Comment by SteveL-MSFT** [comment]
Codefactor issue is "won't fix"

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs (hunk 3 above)
Comment (daxian-dbw) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs:394]: Sounds good. #15412 is opened to track the review comment.
