### PR TITLE
Handle global tool specially when prepending PSHome to PATH

### LINKED ISSUE #24090: Cannot run pwsh script but bash can.
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Try to start a script with a `#!` for powershell.
Might have to do it on Linux ARM machine from Azure.

### Expected behavior

```console
debian@DebianARM:~$ pwsh
PS /home/debian> head -1 ~/agent/az-agents
#!/usr/bin/env pwsh
PS /home/debian> ~/agent/az-agents
Find agents in the pool 'Default' on 'https://dev.azure.com/TVisionDev/'
98      online  True    None    32      None    None    DebianARM
128     online  True    None    500     None    10.0.19045      Blade01
130     online  True    None    500     None    10.0.19045      Blade02
131     online  True    None    250     None    10.0.19045      Blade03
```

### Actual behavior

```console
debian@DebianARM:~$ pwsh
PS /home/debian> head -1 ~/agent/az-agents
#!/usr/bin/env pwsh
PS /home/debian> ~/agent/az-agents
x86_64-binfmt-P: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
PS /home/debian> debian@DebianARM:~$
debian@DebianARM:~$ ~/agent/az-agents
Find agents in the pool 'Default' on 'https://dev.azure.com/TVisionDev/'
98      online  True    None    32      None    None    DebianARM
128     online  True    None    500     None    10.0.19045      Blade01
130     online  True    None    500     None    10.0.19045      Blade02
131     online  True    None    250     None    10.0.19045      Blade03
```

### Error details

```console
PS /home/debian> get-error
PS /home/debian>
```

### Environment data

```powershell
PS /home/debian> $PSVersiontable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Debian GNU/Linux 12 (bookworm)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /home/debian>
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by daxian-dbw**
## PR Summary

Fix #24090

Handle global tool specially when prepending PSHome to the `PATH` environment variable.
When running PowerShell global tool, the real entry executable should be the `pwsh` or `pwsh.exe` within the '../.dotnet/tools' folder, not what `PSHome` is pointing to.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
  - [x] None
  - **OR**
  - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
    - [ ] Experimental feature name(s): 
- **User-facing changes**
  - [x] Not Applicable
  - **OR**
  - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
  - [x] N/A or can only be tested interactively
  - **OR**
  - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
  - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

**Comment by daxian-dbw** [comment]
@adityapatwardhan I think we should not include the `pwsh` executable file in the `any\unix` and `any\win` folders, because there are only those 2 folders in the global tool, and you just cannot cover all the architecture flavors.

I guess the `pwsh/pwsh.exe` executable was added because there was complaint about `$pshome\pwsh` doesn't work? I think it's by design with the global tool installation. And with this change, the workaround would be to run `pwsh` directly which is guaranteed to be the same global tool executable (under `.../.dotnet/tools`)

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs [hunk 1]
```diff
@@ -123,11 +123,23 @@ internal static int Start(
...
+            string pshome = Utils.DefaultPowerShellAppBase;
 
-            // to not impact startup perf, we don't remove duplicates, but we avoid adding a duplicate to the front
+            int index = pshome.IndexOf(dotnetToolsPathSegment, StringComparison.Ordinal);
+            if (index > 0)
+            {
+                // We're running PowerShell global tool. In this case the real entry executable should be the 'pwsh'
+                // or 'pwsh.exe' within the '../.dotnet/tools' folder, not what PSHome is pointing to.
+                // BTW, 13 is the length of '.dotnet/tools'
+                pshome = pshome[0..(index + 13)];
```
Comment (adityapatwardhan) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs:137]: this is true for global tools that are installed globally with `dotnet tool install -g`. It can be installed to any path, but I agree that most people will install it globally. Maybe add this to comments.

**Review by adityapatwardhan — APPROVED** [review]

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs (hunk 1 above)
Comment (daxian-dbw) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs]: Good point, thanks! I've updated the code to cover the scenario where the PowerShell global tool is installed to an arbitrary location.

**Review by adityapatwardhan — APPROVED** [review]
