### PR TITLE
Fix blocking wait when starting file associated with a Windows application

### LINKED ISSUE #13744: When PowerShell runs elevated on Windows, starting *.msc files locks the console
When PowerShell `v7.1.0-preview.7` or `v7.1.0-rc.1` is started as Administrator on Windows, and I start some mmc snap-in: `compmgmt`, `diskmgmt`, etc., it locks the console until I close the snapin.

It doesn't lock on `v7.1.0-preview.6` and earlier versions.
It doesn't lock when PowerShell started as standard user (no elevation).
Also, it doesn't lock, when I start the snapin as `mmc compmgmt.msc`

I haven't found (yet?) other file types, that behave like this, maybe there are some.

## Steps to reproduce

```powershell
compmgmt
```

## Expected behavior

```none
Computer management snapin starts, console doesn't lock.
```

## Actual behavior

```none
Computer management snapin starts, console locks until snapin closes.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-rc.1
PSEdition                      Core
GitCommitId                    7.1.0-rc.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

Change https://github.com/PowerShell/PowerShell/pull/13481 modified some logic on how console apps are detected.  The problem in this situation is:

1. user starts `diskmgmt.msc`
2. check if exe, this is not an exe so set `_isWindowsApplication = false`
3. check if associated with an exe
4. finds `mmc.exe`
5. check if exe, this is an exe, so launch this with previous "command" as the argument
6. check `_isWindowsApplication` to determine if we block waiting for exe to finish, since this value was cached and not updated on step 5, it treats as console exe and waits

Fix is to change `CheckIfConsoleApplication()` to be non-static so that the second time it's called it updates `_isWindowsApplication` to point to the new exe and not the previous file.

Tested manually.  Since CI won't have a Windows app associated with a file, can't create a test case.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/13744

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by iSazonov** [comment]
@SteveL-MSFT I think we should simply revert a change in line 557
from
`_isRunningInBackground = IsWindowsApplication;`
to
`_isRunningInBackground = IsWindowsApplication(_nativeProcess.StartInfo.FileName);`

As for test, you could see last test in Invoke-Item.Tests,ps1 file:
`Describe "Invoke-Item tests on Windows" -Tags "CI","RequireAdminOnWindows" {`

**Comment by SteveL-MSFT** [comment]
@iSazonov the problem is if anyone updates the code and uses `CheckIfConsoleApplication()` it will have a similar problem as `IsWindowsApplication` doesn't get updated if we just do the change you are suggesting.

As for the test, it appears the hang only occurs if the associated process explicitly supports elevation like mmc.exe.  I can add a test that runs if `diskmgmt.msc` and `mmc.exe` are on the system, otherwise it'll be skipped.  At least it can work locally.

**Comment by iSazonov** [comment]
>  the problem is if anyone updates the code and uses CheckIfConsoleApplication() it will have a similar problem as IsWindowsApplication doesn't get updated if we just do the change you are suggesting.

My thoughts is that switching to mmc.exe is temporary and we should follow diskmgmt.msc. Otherwise it will very tricky code - input is diskmgmt.msc but result is for mmc.exe.
And I'd remove IsWindowsApplication and IsConsoleApplication because they is used once.

**Comment by SteveL-MSFT** [comment]
@iSazonov but `diskmgmt.msc` is not the process so following it doesn't make sense unless I'm misunderstanding.  Removing `IsWindowsApplication` and `IsConsoleApplication` makes sense.

**Comment by iSazonov** [comment]
If we remove IsWindowsApplication we remove _isWindowsApplication and this resolves our discussion (til we will want to make IsWindowsApplication public :-) )

File: src/System.Management.Automation/engine/NativeCommandProcessor.cs [hunk 1]
```diff
@@ -423,7 +400,8 @@ private void InitNativeProcess()
 
             _startPosition = new Host.Coordinates();
 
-            CalculateIORedirection(out redirectOutput, out redirectError, out redirectInput);
+            bool isWindowsApplication = IsWindowsApplication(this.Path);
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/NativeCommandProcessor.cs:403]: These names are so similar that it can be confused. Can we keep the old name for the method?

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/NativeCommandProcessor.cs:403]: The old name with the `Check` makes it slightly harder to understand reading the code as it's not as clear what true/false means with `Check` vs `Is`.  The alternative is to have the local variable be `isConsoleApplication` to differentiate I guess.

Comment (iSazonov) [reply src/System.Management.Automation/engine/NativeCommandProcessor.cs:403]: We could use `bool windowsApplication` without Bulgarian prefix.
If no I agreed  with `isWindowsApplication`.

**Comment by iSazonov** [comment]
As unrelated notice. The code fallback to default shell (cmd.exe/bash) to invoke an item. But what if we assign PowerShell as default shell? Infinite cycle? 
It seems we need to review all places where we fallback to default shell to understand the consequences.

**Comment by SteveL-MSFT** [comment]
@iSazonov can you point me to what code you are referring to?

**Comment by iSazonov** [comment]
In the context - line 488. If UseShellExecute is true we call PowerShell again?

File: src/System.Management.Automation/engine/NativeCommandProcessor.cs (hunk 1 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/NativeCommandProcessor.cs:403]: Since this code currently is only used in one place, I think the casing diff is ok and prefer the `is` making it a bit more readable

**Comment by iSazonov** [comment]
I mean the code
https://github.com/PowerShell/PowerShell/blob/f2a37164bfb321f5218cea25ed1d1cf8b284961c/src/System.Management.Automation/engine/NativeCommandProcessor.cs#L478-L490

**Comment by SteveL-MSFT** [comment]
@iSazonov ok, now I see what you mean.  However, on my macBook I can see that Process.Start() doesn't start a new shell to run the exe.

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
I'd expect the cycle with:
1. Set PowerShell as default shell
2. Run PowerShell unelevated
3. Run diskmgmt.msc

In line 534 we will have UseShellExecute = true and run PowerShell again.

**Comment by SteveL-MSFT** [comment]
@iSazonov perhaps you can open a new issue to discuss that specific concern, I don't see additional pwsh processes, however

**Comment by iSazonov** [comment]
@SteveL-MSFT I looked at the UseShellExecute implementation. It does not use a call to default shell. On Windows it uses ShellExecuteEx P/Invoke, on Unix it uses x-bit. So the cycle would be only if PowerShell associated with the extension or file.
On Windows this is an incredible scenario. On Unix the code path is blocked in line 494.
On Unix I still had a concern because in line 488 UseShellExecute is false and Process.Start will just fork and execute - if the file has `#!pwsh` in header the pwsh would run again but I tried on WSL without problems. So the question is closed.

**Comment by ImportTaste** [comment]
Is this in 7.1 stable? I don't see a revert to this commit in the diff log between 7.1 and 7.1-rc2, but it's re-incorporated in 7.2 preview 1.

**Comment by iSazonov** [comment]
It was included in v7.2.0-preview.1. You can check that 7.1 works well in the scenario.

**Comment by ImportTaste** [comment]
> It was included in v7.2.0-preview.1. You can check that 7.1 works well in the scenario.

So... both versions have it?

**Comment by iSazonov** [comment]
Yes, both.
