### PR TITLE
Fix regression in `Move-Item` to only fallback to CopyAndDelete in specific cases

### LINKED ISSUE #16000: Recent Move-Item changes causing Windows platform regressions
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The recent change to Move-Item (PR https://github.com/PowerShell/PowerShell/pull/15077) is causing regressions on Windows platforms as reported by WSD.

The recent change of catching all IOException and retry is causing infinite recursion in some move cases.

I suggest we consider moving back to the original code that tries to detect (Windows platform code path) when MoveTo or CopyAndDelete should be used, and add additional error handling to that, if needed.

### Expected behavior

```console
cd c:\
mkdir 0
Move-Item  0 0
Move-Item : The process cannot access the file because it is being used by another process.
# Expected error is returned.
```

### Actual behavior

```console
cd c:\
mkdir 0
Move-Item 0 0
Ctrl+C
# Move-Item runs recursion indefinitely, continually creating '0' subdirectories.

Move-Item 0 0\1
Ctrl+C
# Move-Item runs recursion indefinitely, continually creating '1' subdirectories.
```

### Error details

```console
Unexpected error
```

### Environment data

```powershell
PSVersion                      7.2.0-preview.9
PSEdition                      Core
GitCommitId                    7.2.0-preview.9-14-g403767d7f7b910a6f315505287fe9a72c3960c52
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

If Move fails, check if known case before attempting CopyAndDelete:

- if an item is attempted to be renamed across filesystem mount boundaries.
- if the source and destination do not have the same root path

## PR Context

#15077 introduced a regression where it would fall through to CopyAndDelete on any IOException including where the destination doesn't exist (and probably other cases as well).

Fix https://github.com/PowerShell/PowerShell/issues/16000

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Review by PaulHigin — APPROVED** [review]
LGTM.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 1]
```diff
@@ -6112,24 +6121,44 @@ protected override bool IsItemContainer(string path)
...
-            try
+            if (!IsSameWindowsVolume(directory.FullName, destinationPath))
             {
-                if (InternalTestHooks.ThrowExdevErrorOnMoveDirectory)
-                {
-                    throw new IOException("Invalid cross-device link");
-                }
-
-                directory.MoveTo(destinationPath);
+                CopyAndDelete(directory, destinationPath, force);
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:6126]: It makes no sense to do the check here since it doesn't cover all scenarios - paths with different root directory can point to the same volume and vise verse.
We should trust OS behavior and do directory.MoveTo() first. Then handle exception in right way. See my comment https://github.com/PowerShell/PowerShell/issues/16000#issuecomment-906926525

Comment (SteveL-MSFT) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:6126]: .NET runtime has the same check, the alternative is to check another HResult on Windows to catch that case

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 2]
```diff
@@ -6116,12 +6126,12 @@ private void MoveDirectoryInfoUnchecked(DirectoryInfo directory, string destinat
...
                 if (InternalTestHooks.ThrowExdevErrorOnMoveDirectory)
                 {
-                    throw new IOException("Invalid cross-device link");
+                    throw new IOException("Invalid cross-device link", hresult: MOVE_FAILED_ERRORS[0]);
                 }
 
                 directory.MoveTo(destinationPath);
             }
-            catch (IOException)
+            catch (IOException e) when (MOVE_FAILED_ERRORS.Contains(e.HResult))
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:6134]: We could simplify the code and exclude allocations:
```suggestion
#if UNIX
            // This is the errno returned by the rename() syscall
            // when an item is attempted to be renamed across filesystem mount boundaries.
            catch (IOException e) when (e.HResult == 18)
#else
            // 0x80070005 ACCESS_DENIED is returned when trying to move files across volumes like DFS
            // 0x80131620 is returned if the source and destination do not have the same root path
            catch (IOException e) when (e.HResult == -2147024891)
            catch (IOException e) when (e.HResult == -2146232800)
#endif
```

Comment (SteveL-MSFT) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:6134]: Good suggestion, will update

**Comment by SteveL-MSFT** [comment]
@iSazonov are you good with the changes?

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
I hope to discuss the issues with .Net team. Perhaps they will approve to enhance MoveTo() with copy-and-delete.
