### PR TITLE
On Windows, reset cursor visibility back to previous state when rendering progress

### LINKED ISSUE #16412: `Write-Progress` since 7.2.0 sets `CursorVisible` to `$true`
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run the script:
```PowerShell
[Console]::CursorVisible = $false
Write-Host "Before wp - " -NoNewLine
[Console]::CursorVisible
0..10 | % {
    Write-Progress -Activity test -Status test -PercentComplete $_
    Start-Sleep -s 0.1
}
Write-Host "After wp - " -NoNewLine
[Console]::CursorVisible
```

### Expected behavior

`Write-Progress` shouldn't affect the state of `CursorVisible`

### Actual behavior

```PowerShell
PS > .\script.ps1
Before wp - False
After wp - True
```

### Error details

_No response_

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

The progress rendering code hides the cursor during rendering and makes the cursor visible again after rendering as it assumes the cursor was previously in a visible state.  However, if a script intentionally hides the cursor, then using progress will result in the cursor being visible.  However, it seems that only Windows supports reading the current cursor visibility state and a platform not supported exception is thrown on Linux and macOS.  So the fix is to just cache the current cursor on Windows and set it back when done rendering.  No change for Linux/macOS as we still want to explicitly hide the cursor when rendering progress so that you don't see the cursor moving quickly in the console to render progress.

## PR Context

Fix #16412

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Review by vexx32 — APPROVED** [review]
Looks good to me! Wish we could have a consistent impl across platforms, wonder why Unix can't check the cursor state 🤔

**Comment by SteveL-MSFT** [comment]
CI failure is due to a .NET install issue that's been reported to the .NET team

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressPane.cs [hunk 1]
```diff
@@ -301,7 +301,17 @@ private void WriteContent()
         {
             if (_content is not null)
             {
+#if UNIX
                 Console.CursorVisible = false;
+#else
+                // On Windows, we can check if the cursor is currently visible and not change it to visible
+                // if it is intentionally hidden.  On Unix, it is not currently supported to read the cursor visibility.
```
Comment (iSazonov) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressPane.cs:308]:
```suggestion
                // On Windows, we can check if the cursor is currently visible and not change it to visible
                // if it is intentionally hidden.  On Unix, it is not currently supported to read the cursor visibility.
#if UNIX
                Console.CursorVisible = false;
#else
```

**Review by iSazonov — APPROVED** [review]

**Review by TravisEz13 — APPROVED** [review]
