### PR TITLE
Fix `TypeName.GetReflectionType()` to work when the `TypeName` instance represents a generic type definition within a `GenericTypeName`

### LINKED ISSUE #24982: GetReflectionType only returns open generic types once per session
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [x] Search the existing issues.
- [x] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [x] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Open a fresh session of PowerShell
2. Run the following snippet in the new session and notice the result
3. Rerun it and notice the result

Snippet:
```
using namespace System.Management.Automation.Language
$RootAst = [Parser]::ParseInput('[System.Collections.Generic.List[string]]', [ref]$null, [ref]$null)
$TypeAst = $RootAst.Find({param($ast) $ast -is [TypeExpressionAst]}, $true)
$TypeAst.TypeName.TypeName.GetReflectionType()
```

### Expected behavior

```console
The following output every time:

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     List`1                                   System.Object
```

### Actual behavior

```console
The previously shown output once per session.
```

### Error details

```console

```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.6.0-preview.2
PSEdition                      Core
GitCommitId                    7.6.0-preview.2
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by daxian-dbw**
## PR Summary

Fix #24982

When a generic type expression is parsed for the second time, the generic type can be found in cache, and hence the symbol resolver won't go through the code path to resolve `genericTypeName.TypeName`, which represents the generic type definition. Therefore, unlike the first-time parsing, the cached type for `genericTypeName.TypeName` won't be set during the symbol resolving process for the second parsing.

However, the type resolution in `TypeName.GetReflectionType()` doesn't work for a generic type definition in most cases, for example, when the generic type expression is `[System.Collections.Generic.List[string]]`, `genericTypeName.TypeName` will be a `TypeName` instance with the full name `System.Collections.Generic.List` which will fail to be resolved. That's why the second time you parse the same generic type expression, `genericTypeName.TypeName.GetReflectionType()` will return null.

Why `genericTypeName.TypeName` can be resolved in the first-time resolution of `genericTypeName`, but doesn't work when directly calling `genericTypeName.TypeName.GetReflectionType()`? That's because for the former, within `VisitGenericTypeName(...)`, it uses a `TypeResolutionState` instance as the resolution context, which is constructed with the information from the `genericTypeName` (see [code here](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/parser/SymbolResolver.cs#L655-L657)). But when directly calling `genericTypeName.TypeName.GetReflectionType()`, it doesn't have that information and thus cannot use the same/equivalent `TypeResolutionState` instance as the context for type resolution.

The fix is to pass the generic argument count to `TypeName` when constructing a `GenericTypeName` instance, so that the `TypeName` instance can try resolving with an alternate name (i.e. ``typename`<n>``) when the original name fails to resolve.

The changes also fix another issue:

Before: assembly-qualified name `[System.Collections.Generic.List[string], System.Private.CoreLib]` cannot be resolved.
After: `[System.Collections.Generic.List[string], System.Private.CoreLib]` can be resolved as expected.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
  - [x] None
  - **OR**
  - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
    - [ ] Experimental feature name(s): 
- **User-facing changes**
  - [x] Not Applicable
  - **OR**
  - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
  - [x] N/A or can only be tested interactively

### CODE REVIEW

**Comment by daxian-dbw** [comment]
@MartinGC94 Can you please also review this PR? Thank you!

File: src/System.Management.Automation/engine/parser/SymbolResolver.cs [hunk 1]
```diff
@@ -697,6 +697,26 @@ private bool VisitGenericTypeName(GenericTypeName genericTypeName)
...
+                // - But in much more other cases, calling that method won't return the type definition,
+                //   for example, when the generic type is 'System.Collections.Generic.List[string]',
+                //   the call returns 'null' because 'System.Collections.Generic.List' is not a valid type.
+                //
+                // In the latter cases, given that we already have the generic type, we can get the type
+                // definition and assign it to the cached type of 'genericTypeName.TypeName'.
+                var genericDefinition = genericTypeName.TypeName;
+                if (genericDefinition.GetReflectionType() is null)
+                {
+                    ((ISupportsTypeCaching)genericDefinition).CachedType = foundType.GetGenericTypeDefinition();
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/parser/SymbolResolver.cs:717]: I wonder if previously we already put genericTypeName in cache why didn't we the assignment in that time?

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/parser/SymbolResolver.cs:717]: The assignment was done at that time, but that was targeting a different `TypeName` instance.

**Comment by MartinGC94** [comment]
It fixes my real world scenario and the fix itself seems reasonable. Thanks for the quick fix :)

File: src/System.Management.Automation/engine/parser/SymbolResolver.cs (hunk 1 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/parser/SymbolResolver.cs:717]: If the cache contains an instance (not string type name) I believe there is reason for that but it is not clear why the cache doesn't keep generic type definition as additional information (or full generic type name) if we exactly know that the current type is generic.

Also I discover ResolveTypeNameWithContext method with such pattern - should we fix it too?

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/parser/SymbolResolver.cs:717]: I'm not sure I understand the problem you were talking about.

The reason why `GetRefectionType()` doesn't work on in this case is that the type name is like `System.Collections.Generic.List` instead of ``System.Collections.Generic.List`1``. `GenericTypeName` handles that with the [GetGenericType](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/parser/ast.cs#L8887-L8900) method.

I did try a fix to always have the type name of `GenericTypeName.TypeName` with the correct `` `<count>`` part, but that turns out to be a breaking change because some types can have generic form, but also have non-generic form, for example, `System.Tuple`. Take `Tuple[string, string]` as an instance, calling `TypeName.GetReflectionType()` on that `GenericTypeName` instance today returns the `System.Tuple` type, but will return ``System.Tuple`1`` after the fix.

That's why I try to fix it from the caching code here instead.

Comment (iSazonov) [reply src/System.Management.Automation/engine/parser/SymbolResolver.cs:717]: I see the cache and conclude that performance is important here. But if this cache does not return an accurate result and correction is required, then performance drops. As far as I understand, this correction will be performed for each use of the type in the script. If this is not the case and the correction is needed only once for the whole script, then this is not a problem. But if it's for every use, then I don't like it.

This cache is generally very strange. It works seem by references, but not by names.
I just set a breakpoint and entered [System.Collections.Generic.List[string] on the command line. That's what I see
image

There are both names in the `s_cache`! - `[System.Collections.Generic.List` and `[System.Collections.Generic.List'1]`

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/parser/SymbolResolver.cs:717]: > But if this cache does not return an accurate result and correction is required, then performance drops.

I don't know anything about the "cache correction" part. As you can see, this PR doesn't change `s_cache`, but only update the `CachedType` of a `TypeName` object accordingly (when the `GenericTypeName.TypeName` doesn't need to be resolved as part of resolving the `GenericTypeName` itself). So, I believe what you observed is not related to changes in this PR, right? 

> There are both names in the `s_cache`! - `System.Collections.Generic.List` and `System.Collections.Generic.List'1`

The key of `s_cache` is a combination of a `ITypeName` object and a `TypeResolutionState` object.
The `...List` and ``...List`1`` you see are from the `ITypeName` objects. The resolution result for a `ITypeName` object can be different with different `TypeResolutionState` as the context.

For example, `TypeResolutionState` has the member `genericArgumentCount`, and when its value is `1`, then a `TypeName` object with the name `System.Collections.Generic.List` can be resolved to the generic type definition ``System.Collections.Generic.List`1`` too.

Comment (iSazonov) [reply src/System.Management.Automation/engine/parser/SymbolResolver.cs:717]: My main concern is that we don't cache that we found with your new code and do the expensive operation again and again.
So I ask myself are the operations expensive?

If understand right we call [GetGenericTypeDefinition()](https://source.dot.net/#System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs,3525)
It uses a cache. So it is not expensive. 
But I see it can throw if not IsGenericType. So maybe we need the check.

Before this we call GetReflectionType(). I see it uses local cache but before it call TypeResolver.ResolveTypeName() which can call TypeCache.Lookup() - this brings us back to the question why aren't we writing the result to the cache or why cannot we find it in the cache?

Earlier, you mentioned that you were trying to fix the cache, but I don't understand why you're talking about the `count` - it's not used in any way when searching the cache. The search in the cache is based on _references_ to objects. That's why I asked earlier why this cache uses comparer for object _references_ and not key _values_ from these objects.

I checked GetReflectionType() in debbuger without your change and example from related issue
```powershell
using namespace System.Management.Automation.Language
$RootAst = [Parser]::ParseInput('[System.Collections.Generic.List[string]]', [ref]$null, [ref]$null)
$TypeAst = $RootAst.Find({param($ast) $ast -is [TypeExpressionAst]}, $true)
$TypeAst.TypeName.TypeName.GetReflectionType()
```
 and the method really calls TypeCache.Lookup() but typeName, typeResolutionState objects there are different than at this point (VisitGenericTypeName), and I see the cache contains expected type and expected state.

I run the example with your change and the cache doesn't work too.

So first conclusion is that GetReflectionType() always does cache lookup with negative result so it is expensive. Really it is very, very expensive since after negative check in the cache it does many, many alternative actions.

Second conclusion is that if performance is important then the cache should work for generics. 
I hope it is possible to fix. TypeResolutionState class description says that it is for "current scope and scope above". Since we are all in the same scope, and the cache should work.

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/parser/SymbolResolver.cs]: >  ... Really it is very, very expensive ...

I don't think the call to `GetReflectionType()` is that expensive :)
But I agree it's not optimal to always call `GetReflectionType()` on `GenericTypeName.TypeName` when the `GenericTypeName` instance itself can be resolved from the cache. I believe in most cases, the member `GenericTypeName.TypeName` won't be accessed, so it's a waste to always resolve its type.

I went with another approach to fix this issue -- pass the generic argument count to the `TypeName` and update its `GetReflectionType()` to try an alternate name when the resolution fails with the original name.

File: src/System.Management.Automation/engine/parser/ast.cs [hunk 2]
```diff
@@ -8483,6 +8485,21 @@ public TypeName(IScriptExtent extent, string name, string assembly)
...
+        /// <param name="extent">The extent of the typename.</param>
+        /// <param name="name">The name of the type.</param>
+        /// <param name="genericArgumentCount">The number of generic arguments.</param>
+        internal TypeName(IScriptExtent extent, string name, int genericArgumentCount)
+            : this(extent, name)
+        {
+            if (genericArgumentCount > 0 && !_name.Contains('`'))
+            {
+                _genericArgumentCount = genericArgumentCount;
+            }
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/parser/ast.cs:8500]: Usually, we expect a constructor to throw an exception if the argument is unexpected. But here we perform a correction of the argument. It's amazing. I'm afraid this may provoke accidental misuse of this constructor in the future. At the very least, it would be good to add a comment with examples of the scenarios we address and explaining why this correction is needed in this place.  
Alternatively, we could perform a check at the call location and pass the correct arguments.
It could be even better to use a template like `private static TypeName TypeName.CreateAlternativeGenericTypeName()` with a comprehensive description.

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/parser/ast.cs:8500]: This "try alternate name" thing happens in multiple places, which is common when dealing with generic type resolution. Comments were added in the `GetReflectionType()` to explain why we only fall back to alternate name even if `genericArgumentCount` is set.

As for the scenario for using this constructor, the XML comment calls it out and it's also easy to understand by looking at where it's used. So, I don't think more comments are needed.

I can add a check to throw when `genericArgumentCount` is a negative value.

**Review by iSazonov — APPROVED** [review]

**Review by SeeminglyScience — APPROVED** [review]
LGTM!
