### PR TITLE
Display PM and WS in MB instead of KB

### LINKED ISSUE #2910: Get-Process should display PM and WS in MB instead of KB
Steps to reproduce
------------------
```powershell
PS C:\Program Files\PowerShell\6.0.0.14> get-process | Select-Object -First 1

 NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
 ------    -----      -----     ------     --  -- -----------
     14     4208      21604       3.70   7008   1 ApplicationFrameHost
```
On Servers, processes are more likely to take up multiple megs so displaying K is less useful

Expected behavior
-----------------
PM(M), WS(M)

Actual behavior
---------------
PM(K), WS(K)

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
PSRemotingProtocolVersion      2.3
PSEdition                      Core
CLRVersion
GitCommitId                    v6.0.0-alpha.14
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
PSVersion                      6.0.0-alpha
```

TFS:9750040

### PR DESCRIPTION
**Pull request by faheel**
Modify output of Get-Process to display PM and WS in MB instead of KB.
Closes #2910 

This is how it looks after the changes:
(Command run: `Get-Process | Sort-Object -Descending WS`)
image

### CODE REVIEW

File: src/System.Management.Automation/commands/utility/FormatAndOutput/common/DefaultFormatters/DotNetTypes_format_ps1xml.cs [hunk 1]
```diff
@@ -534,16 +534,16 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_System_Diagnostics_Proc
...
+                    .AddHeader(Alignment.Right, label: "WS(M)", width: 10)
                     .AddHeader(Alignment.Right, label: "CPU(s)", width: 10)
                     .AddHeader(Alignment.Right, width: 6)
                     .AddHeader(Alignment.Right, width: 3)
                     .AddHeader()
                     .StartRowDefinition()
                         .AddScriptBlockColumn("[long]($_.NPM / 1024)")
-                        .AddScriptBlockColumn("[long]($_.PM / 1024)")
-                        .AddScriptBlockColumn("[long]($_.WS / 1024)")
+                        .AddScriptBlockColumn("\"{0:N3}\" -f [float]($_.PM / (1024 * 1024))")
```
Comment (lzybkr) [inline src/System.Management.Automation/commands/utility/FormatAndOutput/common/DefaultFormatters/DotNetTypes_format_ps1xml.cs]: I would use `1mb` instead of `1024 * 1024` because PowerShell does not implement constant folding.
I think I would also use `:N2` instead of `:N3`, I don't think we require that much precision and helps avoid exceeding the maximum column width now that we see a `.` that wasn't there before.

Comment (faheel) [inline src/System.Management.Automation/commands/utility/FormatAndOutput/common/DefaultFormatters/DotNetTypes_format_ps1xml.cs]: Yes, changing `1024 * 1024` to `1MB` would be better. I didn't know that before.
As for the precision, if we use `:N2` then for processes which take up 1-9KB of memory, it would be shown as `0.00`, whereas using `:N3` would show, for example, `0.005`, which is the correct value.

Comment (lzybkr) [inline src/System.Management.Automation/commands/utility/FormatAndOutput/common/DefaultFormatters/DotNetTypes_format_ps1xml.cs]: I suppose seeing `0.00` looks wrong and some might investigate, that extra character is also causing problems - here is an example that I just tested with your changes:

```
   2663 ...6.016      0.004             11940   0 vmmem
   2655 ...6.016    234.953             12720   0 vmmem
```

And to me - this is worse - I worry more about processes using a lot of memory than those using little memory.

Comment (faheel) [inline src/System.Management.Automation/commands/utility/FormatAndOutput/common/DefaultFormatters/DotNetTypes_format_ps1xml.cs]: Ah yes, that looks bad. Changing precision to 2.

File: src/System.Management.Automation/commands/utility/FormatAndOutput/common/DefaultFormatters/DotNetTypes_format_ps1xml.cs [hunk 2]
```diff
@@ -534,16 +534,16 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_System_Diagnostics_Proc
...
+                    .AddHeader(Alignment.Right, label: "WS(M)", width: 10)
                     .AddHeader(Alignment.Right, label: "CPU(s)", width: 10)
                     .AddHeader(Alignment.Right, width: 6)
                     .AddHeader(Alignment.Right, width: 3)
                     .AddHeader()
                     .StartRowDefinition()
                         .AddScriptBlockColumn("[long]($_.NPM / 1024)")
-                        .AddScriptBlockColumn("[long]($_.PM / 1024)")
-                        .AddScriptBlockColumn("[long]($_.WS / 1024)")
+                        .AddScriptBlockColumn("\"{0:N3}\" -f [float]($_.PM / 1MB)")
```
Comment (lzybkr) [inline src/System.Management.Automation/commands/utility/FormatAndOutput/common/DefaultFormatters/DotNetTypes_format_ps1xml.cs]: I think we should use `N2`.

A process using 5kb will show `.01` because that gets rounded up, and very few processes use less than 5kb.

I also noticed in your screenshot that the CPU is showing 3 places after the decimal on Linux but we only see 2 on Windows.  I think it's reasonable to use `N2` for CPU to be consistent b/w Windows and Linux.

**Comment by faheel** [comment]
This is how the output looks now on Linux: 
image

File: src/System.Management.Automation/commands/utility/FormatAndOutput/common/DefaultFormatters/DotNetTypes_format_ps1xml.cs (hunk 2 above)
Comment (faheel) [inline src/System.Management.Automation/commands/utility/FormatAndOutput/common/DefaultFormatters/DotNetTypes_format_ps1xml.cs]: Done!

**Review by lzybkr — APPROVED** [review]
