### PR TITLE
Use culture invariant to-string convertor for lval in replace operator

### LINKED ISSUE #10948: -replace operator stringifies its LHS operand culture-sensitively
In many contexts PowerShell uses the invariant culture for string operations for predictable operation irrespective of the session's current culture.

For instance, `"$(1.2)"` (string interpolation in expandable strings) yields `'1.2'` even in cultures that use `,`, not `.` as the decimal mark, and cast to numeric types (e.g., `[double] '1.2'`) are similarly culture-invariant.

The `-split` and `-replace` operators implicitly convert their LHS operands to strings, if they aren't, but while `-split` commendable uses the culture-invariant conversion (as in expandable strings), 
**`-replace` is unexpectedly culture-sensitive**

# Steps to reproduce

```powershell
Describe "Culture-invariance tests for -split and -replace" {
  BeforeAll {
      $prevCulture = [cultureinfo]::CurrentCulture
      [cultureinfo]::CurrentCulture = 'fr' # The French culture uses "," as the decimal mark.
  }
  It "-skip: LHS stringification is not culture-sensitive" {
    1.2 -split ',' | Should -Be '1.2'
  }
  It "-replace: LHS stringification is not culture-sensitive" {
    1.2 -replace ',' | Should -Be '1.2'
  }
  AfterAll {
      [cultureinfo]::CurrentCulture = $prevCulture
  }
}
```

# Expected behavior

The tests should pass.

# Actual behavior

The `-replace` test fails:

```none
      Expected: '1.2'
      But was:  '12'
```

That is, `1.2` was unexpectedly stringified culture-_sensitively_, as `'1,2'`.

# Environment data

```none
PowerShell Core 7.0.0-preview.5
```

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Fix #10948

## PR Context

Options for the fix:
- lval.ToString()
    That is before the fix.
- Convert.ToString(lval, CultureInfo.InvariantCulture)
    Makes lval conversion being culture invariant.
- PSObject.ToStringParser(context, lval)
    Current fix. Makes lval conversion being culture invariant and add PowerShell magic conversions if lval is PSObject (ex., follow ETS) [See](https://github.com/PowerShell/PowerShell/blob/96eb361af8d04d7821343ea2d59f61f0efcdd54c/src/System.Management.Automation/engine/MshObject.cs#L1270)
    In the case behavior is as for -match operator
- PSObject.ToStringParser(context, PSObject.AsPSObject(lval))
    The same as previous but always use PowerShell magic conversions (follow ETS).
    In the case behavior is as for `-join` operator (with performance issue because of mandatory wrapping to PSObject)

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by mklement0** [comment]
Thanks for taking this on, @iSazonov.

Generally, it sounds we should follow the example of `-match` and `-split` (assuming they work consistently among them), which is `PSObject.ToStringParser(context, lval)`, which, from what I gather, is like using `"$var"` for a non-string value `$var`.

But I don't understand how `PSObject.ToStringParser(context, PSObject.AsPSObject(lval))` differs in practice from `PSObject.ToStringParser(context, lval)`.
Can you explain in more detail and give an example?

**Comment by iSazonov** [comment]
> But I don't understand how PSObject.ToStringParser(context, PSObject.AsPSObject(lval)) differs in practice from PSObject.ToStringParser(context, lval).
Can you explain in more detail and give an example?

In second case we could fall in fast way - TryFastTrackPrimitiveTypes() or IFormattable. In first case a code path is another - follow ETS at first.

**Comment by mklement0** [comment]
I see - but, speaking from observation (haven't looked a the code):

Apart from `[pscustomobject]` instances, ETS properties seem to only affect output formatting, not stringification (in expandable strings). Or are there cases where including ETS properties makes a difference for stringification? If so, what are they, and can you give a specific example?

**Comment by iSazonov** [comment]
@mklement0 The example is in https://github.com/PowerShell/PowerShell/pull/10389#issuecomment-527172983

> ETS properties seem to only affect output formatting

You confuse ETS (Extended Type System) with Formatting System.

**Comment by mklement0** [comment]
I see - you mean an ETS-overridden _`.ToString()` method_ (I was thinking _properties_ in general, which would only matter in formatting) - that's a helpful example.

So it sounds like `-join` is currently the only string-coercing operator that goes the ETS route.

`-match`, `-split`, `-like` do _not_.

In the case of #10389 the ruling was to prevent a behavioral `-join` change, even if that means forgoing a possible performance optimization.

Here, it comes down to this:

* `PSObject.ToStringParser(context, lval)` means aligning `-replace` with `-match`, `-split`, `-like` and results in _no_ behavior modification (except for the culture-sensitivity being fixed)

  * However, that means that an ETS `.ToString()` method is _ignored_.

* `PSObject.AsPSObject(lval))` is the _conceptually correct_ thing to do, as it corresponds to what `"$var"` does (and you would expect the ETS to be honored consistently):

  * It would result in a behavioral change - arguably for the better - in that an ETS `.ToString()` method then _would_ be respected, unlike before.

  * It would impact performance, as you state - I don't know to what extent.

I don't know what the performance implications are, but my personal recommendation would be to pick one of the following two options:

* Make _all_ string operators use `PSObject.AsPSObject(lval))` to ensure that ETS `.ToString()` methods are _consistently_ honored.
  * Technically, a breaking change, but in spirit it is more of a bug fix.

* Fix `-replace` only and align with the majority behavior there, not least because `-match`, `-split`, `-like` are not only _string_ operators but involve string _matching_, i.e., use `PSObject.ToStringParser(context, lval)` (and continue to have  ETS `.ToString()` methods ignored).

**Comment by iSazonov** [comment]
@mklement0 Great investigations! Thanks!

@SteveL-MSFT Perhaps PowerShell-Committee should weight these @mklement0 's proposed options.

**Review by rjmholt — APPROVED** [review]

**Comment by joeyaiello** [comment]
@PowerShell/powershell-committee reviewed this. It's definitely a breaking change (@BrucePay is calling it Bucket 2: Reasonable Gray Area), but we think it's the right thing to do. 

Given where we're at in the release cycle, and our new snap to .NET's 1-year release cycle, we want to take this as an experimental feature into 7.1-preview.1 so we can understand the breakage and whether we need to revert to old behavior.

File: src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs [hunk 1]
```diff
@@ -22,6 +22,14 @@ public class ExperimentalFeature
```
Comment (PoshChan) [inline src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs]: @iSazonov, your last commit had 1 failures in `PowerShell-CI-windows`
Enter-PSHostProcess tests.By CustomPipeName.Can enter, exit, and re-enter using CustomPipeName
```powershell
Expected $true, because The script was able to re-enter another process and grab the pipe of '14sezfew.snn'., but got $false.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Core\Enter-PSHostProcess.Tests.ps1: line 170
170:                     Should -BeTrue -Because "The script was able to re-enter another process and grab the pipe of '$pipeName'."
```

**Comment by iSazonov** [comment]
@daxian-dbw I use strong typed pattern for experimental feature. This simplify discovering where  codes or tests of the experimental feature is placed.

**Comment by daxian-dbw** [comment]
@iSazonov Please follow the existing code pattern for adding new engine experimental features, and don't add new public API.
If you prefer to put the experimental feature name in a variable, then you can declare an internal const string field in the `Const Member` section to hold your experimental feature name.

**Comment by iSazonov** [comment]
> If you prefer to put the experimental feature name in a variable, then you can declare an internal const string field in the Const Member section to hold your experimental feature name.

It makes no sense because we can not use strong typed names out of SMA.
I reverted the change.

**Comment by daxian-dbw** [comment]
> It makes no sense because we can not use strong typed names out of SMA.

If the experimental feature is not in SMA.dll, then it's not an engine feature and should not be declared in `ExperimentalFeature.cs`. Instead, it should be declared in the module where that dll is in.

**Comment by iSazonov** [comment]
@daxian-dbw Could you please continue?

File: src/System.Management.Automation/engine/lang/parserutils.cs [hunk 2]
```diff
@@ -967,7 +967,15 @@ internal static object ReplaceOperator(ExecutionContext context, IScriptExtent e
             IEnumerator list = LanguagePrimitives.GetEnumerator(lval);
             if (list == null)
             {
-                string lvalString = lval?.ToString() ?? string.Empty;
+                string lvalString;
+                if (ExperimentalFeature.IsEnabled("PSCultureInvariantReplaceOperator"))
+                {
+                    lvalString = PSObject.ToStringParser(context, lval) ?? string.Empty;
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/lang/parserutils.cs]: `PSObject.ToStringParser` won't return a null value, so `?? string.Empty` can be removed.

**Review by daxian-dbw — APPROVED** [review]
LGTM except for a comment.

File: src/System.Management.Automation/engine/lang/parserutils.cs (hunk 2 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/lang/parserutils.cs]: https://github.com/PowerShell/PowerShell/blob/384a7ba2d7b66b7099ac840915cbca36ae0494db/src/System.Management.Automation/engine/MshObject.cs#L1370

looks like a bug nonetheless it can return null.

**Comment by iSazonov** [comment]
Should we add `CL-Experimental` label?

File: src/System.Management.Automation/engine/lang/parserutils.cs (hunk 2 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/lang/parserutils.cs]: if `obj` is null, it won't reach that far, see
https://github.com/PowerShell/PowerShell/blob/384a7ba2d7b66b7099ac840915cbca36ae0494db/src/System.Management.Automation/engine/MshObject.cs#L1313-L1316

Comment (iSazonov) [reply src/System.Management.Automation/engine/lang/parserutils.cs]: ToString() can return null by design.

**Comment by daxian-dbw** [comment]
I think we can only use 1 `CL-xx` label, otherwise the script to generate the change log will be confused.

**Comment by iSazonov** [comment]
> I think we can only use 1 CL-xx label, otherwise the script to generate the change log will be confused.

It seems Travis said me that CL-Breaking can be used with another CL- label.

File: src/System.Management.Automation/engine/lang/parserutils.cs (hunk 2 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/lang/parserutils.cs]: Yes, but only if explicitly overridden to return null ..., which is practically not possible.
There will be too many places to change if we consider calling `ToString()` on a non-null object could return `null`.

**Comment by daxian-dbw** [comment]
I don't know about that, but what would you expect the script to do then? placing the same PR under both `Breaking Changes` and `Experimental Features` sections?
I think `CL-BreakingChange` wins in this case.

**Comment by daxian-dbw** [comment]
Hmm, by looking at the following code, it seems the script doesn't handle multiple labels even if `CL-breakingchange` is one of them ...

https://github.com/PowerShell/PowerShell/blob/384a7ba2d7b66b7099ac840915cbca36ae0494db/tools/releaseTools.psm1#L292-L313

**Comment by iSazonov** [comment]
> switch ($clLabel.Name) {

Here we will have an array and the switch will run for every value from the array.

**Comment by daxian-dbw** [comment]
Ah, you are right, I totally missed that.

File: src/System.Management.Automation/engine/lang/parserutils.cs (hunk 2 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/lang/parserutils.cs]: >  very much unlikely

The code process an generic/custom object so it is still possible.
If we enable nullable this will be reported.
We rarely use ToString() directly and if we enable nullable in the MshObject.cs we get dozen of errors for other cases. :-)

I added new commit.

File: src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs [hunk 3]
```diff
@@ -117,6 +117,9 @@ static ExperimentalFeature()
                 new ExperimentalFeature(
```
Comment (PoshChan) [inline src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs]: @iSazonov, your last commit had 7 failures in `PowerShell-CI-linux`
(These are 5 of the failures)

SemanticVersion api tests.Error handling.Missing parts: 'NullString': '$null'
```powershell
Expected an exception, with FullyQualifiedErrorId 'PSArgumentNullException' to be thrown, but the FullyQualifiedErrorId was 'FormatException'. from /home/vsts/work/1/s/test/powershell/engine/Basic/SemanticVersion.Tests.ps1:206 char:15
    +             { [SemanticVersion]::new($version) } | Should -Throw -Err ?
    +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/engine/Basic/SemanticVersion.Tests.ps1: line 206
206:             { [SemanticVersion]::new($version) } | Should -Throw -ErrorId $errorId
```
Alias tests.Export-Alias literal path.for CSV
```powershell
Expected <empty>, but got $null.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/alias.tests.ps1: line 57
57:                     $exportAliasError.FullyqualifiedErrorId | Should -Be $test.expectedError
```
Alias tests.Export-Alias literal path.for PS1
```powershell
Expected <empty>, but got $null.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/alias.tests.ps1: line 57
57:                     $exportAliasError.FullyqualifiedErrorId | Should -Be $test.expectedError
```
Alias tests.Export-Alias literal path.for Null
```powershell
Expected strings to be the same, but they were different.
Expected length: 95
Actual length:   102
Strings differ at index 32.
Expected: '...ErrorNullN...'
But was:  '...ErrorEmpty...'
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/alias.tests.ps1: line 57
57:                     $exportAliasError.FullyqualifiedErrorId | Should -Be $test.expectedError
```
Alias tests.Import-Alias literal path.for Null
```powershell
Expected an exception, with FullyQualifiedErrorId 'ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ImportAliasCommand' to be thrown, but the FullyQualifiedErrorId was 'ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.ImportAliasCommand'. from /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/alias.tests.ps1:110 char:45
    +                 { Import-Alias -LiteralPath $test.testFile -ErrorActi ?
    +                                             ~~~~~~~~~~~~~~
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/alias.tests.ps1: line 110
110:                 { Import-Alias -LiteralPath $test.testFile -ErrorAction SilentlyContinue } | Should -Throw -ErrorId $test.expectedError
```

Comment (PoshChan) [inline src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs]: @iSazonov, your last commit had 7 failures in `PowerShell-CI-windows`
(These are 5 of the failures)

SemanticVersion api tests.Error handling.Missing parts: 'NullString': '$null'
```powershell
Expected an exception, with FullyQualifiedErrorId 'PSArgumentNullException' to be thrown, but the FullyQualifiedErrorId was 'FormatException'. from D:\a\1\s\test\powershell\engine\Basic\SemanticVersion.Tests.ps1:206 char:15
    +             { [SemanticVersion]::new($version) } | Should -Throw -Err ?
    +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
at <ScriptBlock>, D:\a\1\s\test\powershell\engine\Basic\SemanticVersion.Tests.ps1: line 206
206:             { [SemanticVersion]::new($version) } | Should -Throw -ErrorId $errorId
```
Alias tests.Export-Alias literal path.for CSV
```powershell
Expected <empty>, but got $null.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Utility\alias.tests.ps1: line 57
57:                     $exportAliasError.FullyqualifiedErrorId | Should -Be $test.expectedError
```
Alias tests.Export-Alias literal path.for PS1
```powershell
Expected <empty>, but got $null.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Utility\alias.tests.ps1: line 57
57:                     $exportAliasError.FullyqualifiedErrorId | Should -Be $test.expectedError
```
Alias tests.Export-Alias literal path.for Null
```powershell
Expected strings to be the same, but they were different.
Expected length: 95
Actual length:   102
Strings differ at index 32.
Expected: '...ErrorNullN...'
But was:  '...ErrorEmpty...'
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Utility\alias.tests.ps1: line 57
57:                     $exportAliasError.FullyqualifiedErrorId | Should -Be $test.expectedError
```
Alias tests.Import-Alias literal path.for Null
```powershell
Expected an exception, with FullyQualifiedErrorId 'ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ImportAliasCommand' to be thrown, but the FullyQualifiedErrorId was 'ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.ImportAliasCommand'. from D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Utility\alias.tests.ps1:110 char:45
    +                 { Import-Alias -LiteralPath $test.testFile -ErrorActi ?
    +                                             ~~~~~~~~~~~~~~
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Utility\alias.tests.ps1: line 110
110:                 { Import-Alias -LiteralPath $test.testFile -ErrorAction SilentlyContinue } | Should -Throw -ErrorId $test.expectedError
```

Comment (PoshChan) [inline src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs]: @iSazonov, your last commit had 7 failures in `PowerShell-CI-macos`
(These are 5 of the failures)

SemanticVersion api tests.Error handling.Missing parts: 'NullString': '$null'
```powershell
Expected an exception, with FullyQualifiedErrorId 'PSArgumentNullException' to be thrown, but the FullyQualifiedErrorId was 'FormatException'. from /Users/runner/runners/2.163.1/work/1/s/test/powershell/engine/Basic/SemanticVersion.Tests.ps1:206 char:15
    +             { [SemanticVersion]::new($version) } | Should -Throw -Err ?
    +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
at <ScriptBlock>, /Users/runner/runners/2.163.1/work/1/s/test/powershell/engine/Basic/SemanticVersion.Tests.ps1: line 206
206:             { [SemanticVersion]::new($version) } | Should -Throw -ErrorId $errorId
```
Alias tests.Export-Alias literal path.for CSV
```powershell
Expected <empty>, but got $null.
at <ScriptBlock>, /Users/runner/runners/2.163.1/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/alias.tests.ps1: line 57
57:                     $exportAliasError.FullyqualifiedErrorId | Should -Be $test.expectedError
```
Alias tests.Export-Alias literal path.for PS1
```powershell
Expected <empty>, but got $null.
at <ScriptBlock>, /Users/runner/runners/2.163.1/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/alias.tests.ps1: line 57
57:                     $exportAliasError.FullyqualifiedErrorId | Should -Be $test.expectedError
```
Alias tests.Export-Alias literal path.for Null
```powershell
Expected strings to be the same, but they were different.
Expected length: 95
Actual length:   102
Strings differ at index 32.
Expected: '...ErrorNullN...'
But was:  '...ErrorEmpty...'
at <ScriptBlock>, /Users/runner/runners/2.163.1/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/alias.tests.ps1: line 57
57:                     $exportAliasError.FullyqualifiedErrorId | Should -Be $test.expectedError
```
Alias tests.Import-Alias literal path.for Null
```powershell
Expected an exception, with FullyQualifiedErrorId 'ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ImportAliasCommand' to be thrown, but the FullyQualifiedErrorId was 'ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.ImportAliasCommand'. from /Users/runner/runners/2.163.1/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/alias.tests.ps1:110 char:45
    +                 { Import-Alias -LiteralPath $test.testFile -ErrorActi ?
    +                                             ~~~~~~~~~~~~~~
at <ScriptBlock>, /Users/runner/runners/2.163.1/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/alias.tests.ps1: line 110
110:                 { Import-Alias -LiteralPath $test.testFile -ErrorAction SilentlyContinue } | Should -Throw -ErrorId $test.expectedError
```

Comment (PoshChan) [inline src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs]: @iSazonov, your last commit had 1 failures in `PowerShell-CI-windows`
Enter-PSHostProcess tests.By Process Id.Can enter using NamedPipeConnectionInfo
```powershell
Exception calling "Invoke" with "0" argument(s): "The runspace state is not valid for this operation."
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Core\Enter-PSHostProcess.Tests.ps1: line 136
136:                 $ps.AddScript('$pid').Invoke() | Should -Be $pwshId

```

File: src/System.Management.Automation/engine/lang/parserutils.cs (hunk 2 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/lang/parserutils.cs]: Some tests failed so I revert last commit. 
I think I will pull it in follow PR so that we could discuss.
