### PR TITLE
Make a variable assignment in a `ParenExpression` to return the variable value

### LINKED ISSUE #17165: Passing the value of a type-constrained assignment through via the grouping operator (`(...)`) passes the input value rather than the converted one
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note: This may not arise often in practice, but there are two concerns:

* The original behavior is surprising.
* _Repeating_ the command - for an already type-constrained variable - _changes_ the behavior.

```powershell
Remove-Variable -ErrorAction Ignore var # Make sure no $var variable exists.

([bool] $var = 42).GetType().Name # !! 'Int32', i.e. the type of the input rather than the stored converted value.

# Repeating the command - even with a different constraining type - then *does* return the converted value.
# NB: The symptom only surfaces with the same variable, i.e. with a *previously type-constrained* one.
([string] $var = 42).GetType().Name # !! 'String'
```

### Expected behavior

```console
Boolean
String
```

### Actual behavior

```console
Int32
String
```

### Error details

_No response_

### Environment data

```powershell
PowerShell Core 7.3.0-preview.3
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #17165
Make a variable assignment in a `ParenExpression` to return the variable value.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

File: src/System.Management.Automation/engine/runtime/Operations/VariableOps.cs [hunk 1]
```diff
@@ -46,6 +46,12 @@ internal static object SetVariableValue(VariablePath variablePath, object value,
                                      : GetAttributeCollection(attributeAsts);
                 var = new PSVariable(variablePath.UnqualifiedPath, value, ScopedItemOptions.None, attributes);
 
+                if (attributes.Count > 0)
+                {
+                    // When there is any attributes, it's possible the value was converted/transformed.
+                    value = var.Value;
```
Comment (SeeminglyScience) [inline src/System.Management.Automation/engine/runtime/Operations/VariableOps.cs:52]: This could potentially trigger a debugger stop since `Value` invokes `DebuggerCheckVariableRead`.

I'm unsure whether that would be desirable, I'm kind of leaning towards yes but it might make variable breakpoints with `ReadWrite` a little awkward. If we do want that behavior we should add an else here that is `else { var.DebuggerCheckVariableRead() }` so it's consistent.

If we don't want that it becomes a little tricky. We may need to add a `PSVariable.GetValueRaw` (there's an existing `SetValueRaw`) which just returns `_value`.

Very clever solution though I thought it was all going to need to be fixed in the code gen ❤️

**Review by SeeminglyScience — CHANGES_REQUESTED** [review]

File: src/System.Management.Automation/engine/runtime/Operations/VariableOps.cs (hunk 1 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/runtime/Operations/VariableOps.cs]: Good point about consistency. I did think about the debugger check for a minute, but didn't think of the consistency issue.
The method `GetValueRaw` is added, please take another look.

**Review by SeeminglyScience — APPROVED** [review]
LGTM! ❤️
