### PR TITLE
Don't use Win32 native APIs on non-Windows for crypto of secure string over remoting

### LINKED ISSUE #8723: SSH remoting Credential objects from OSX can hard-lock Powershell
# Steps to reproduce

From an OSX client to a Windows host:
```powershell
PS /Users/myuser> $cred = Get-Credential

PowerShell credential request
Enter your credentials.
User: domain\user
Password for user domain\user: ************

PS /Users/myuser> $session = New-PSSession -HostName "windows.host" -UserName "domain\user" -KeyFilePath "/Users/myuser/.ssh/id_rsa"
PS /Users/myuser> Invoke-Command -Session $session -ScriptBlock {param($c) $Global:Credential = $c} -ArgumentList $cred

#### PowerShell locks up here and doesn't respond.  It must be killed externally. ####
```

# Expected behavior

The `Invoke-Command` command should return and set a global parameter on the remote session.

# Actual behavior

PowerShell freezes and must be terminated externally.

# Additional Notes

I came across this issue because I was unable to run Get-Credential directly on the remote machine.  I suspect the issues are related.  When attempting to run Get-Credential directly on the remote machine, it hangs for a little bit, then returns an error:

```powershell
[domain\user@windows.host]: PS C:\Users\myuser> $cred = Get-Credential

PowerShell Credential Request: PowerShell credential request
Warning: A script or application on the remote computer WINDOWS.HOST is requesting your credentials. Enter your credentials only if you trust the remote computer and the application or script that is requesting them.

Enter your credentials.
User: domain\user
Password for user domain\user: ************
```
At this point, the system hangs until you press "ctrl-c" to terminate it.  Once you press "ctrl-c" it outputs the following before dumping you back into a shell.
```powershell
Unable to load shared library 'api-ms-win-security-cryptoapi-l1-1-0.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libapi-ms-win-security-cryptoapi-l1-1-0.dll, 1): image not found
+ CategoryInfo          : ResourceUnavailable: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException
```

# Environment data

```none
OSX Client:

Name                           Value
----                           -----
PSVersion                      6.1.1
PSEdition                      Core
GitCommitId                    6.1.1
OS                             Darwin 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


Windows Host:

Name                           Value
----                           -----
PSVersion                      6.1.1
PSEdition                      Core
GitCommitId                    6.1.1
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
## PR Summary

Remoting relies on Windows native crypto APIs to pass a secure string.  Of course these APIs don't work on non-Windows.  However, the remoting code does not expect this to fail so ends up in a hang waiting for an event that never happens.

Have not figured out how to return an error to the user in the case `Get-Credential` is called within a PSSession.  Currently it just quietly closes the remote connection.  @PaulHigin can you give a pointer to where this code would exist?  Debugging the current code, it has a bunch of error handlers which just result in the pssession being closed and not sure where throwing is appropriate.

Fix https://github.com/PowerShell/PowerShell/issues/8723

## PR Context  

Fix is to provide implementations of the Win32 native pinvoke apis that throw an exception.  The reason to do it this way is that there's a bunch of code that calls some of the APIs of the wrapper .Net class to setup structures that eventually get passed to the win32 api.  Throwing in the managed class causes other things to fail early that should work on non-Windows.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.  
- **User-facing changes**
    - [x] Not Applicable
    - **OR**  
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
The CodeFactor issues are all on existing code complaining about Hungarian notation which none of them are

File: src/System.Management.Automation/utils/CryptoUtils.cs [hunk 1]
```diff
@@ -80,6 +80,143 @@ internal class PSCryptoNativeUtils
...
+                                                    uint dwFlags,
+                                                    ref PSSafeCryptKey phKey)
+        {
+            throw new PSCryptoException();;
+        }
+
+        /// Return Type: DWORD->unsigned int
+        public static uint GetLastError()
+        {
+            throw new PSCryptoException();;
```
Comment (PaulHigin) [inline src/System.Management.Automation/utils/CryptoUtils.cs]: Don't need double ';'.

File: src/System.Management.Automation/engine/serialization.cs [hunk 2]
```diff
@@ -1109,46 +1109,39 @@ private bool HandleSecureString(object source, string streamName, string propert
                     // the principle used in serialization is that serialization
```
Comment (PaulHigin) [inline src/System.Management.Automation/engine/serialization.cs]: Please update comment to explain why we are throwing from serializer in this case when normally that is not allowed.

**Review by PaulHigin — CHANGES_REQUESTED** [review]
This seems Ok as a temporary change to prevent a hang, although the result for a client initiated key exchange is the termination of the remoting connection.  Only slightly better.  For a server initiated exchange, a Windows DPAPI dll exception is generated and returned to the user, but the connection remains.  We can easily change this (in serialization->HandleSecureString) to throw a better exception, but I see that the original exception gets lost and the user gets an obscure "Root element is missing" error, probably because the remoting packet XML is malformed (serializer is not supposed to throw but simply return nothing on errors).  But this may be Ok until we get this working correctly.

File: src/System.Management.Automation/engine/serialization.cs (hunk 2 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/serialization.cs]: Will update

**Comment by SteveL-MSFT** [comment]
@PaulHigin can you re-review?

**Review by PaulHigin — APPROVED** [review]

**Review by TravisEz13 — APPROVED** [review]
