### PR TITLE
Fix `Enter-PSSession -ContainerId` for newest Windows

### LINKED ISSUE #5794: `Enter-PSSession -ContainerId $id` returns `Object reference not set to an instance of an object.`
`Enter-PSSession -ContainerId $id` returns `Object reference not set to an instance of an object.`.

Steps to reproduce
------------------
1. Create a windows docker container like: `microsoft/powershell:windowsservercore` from https://hub.docker.com/r/microsoft/powershell/

2. open PSCore and run:
```powershell
Enter-PSSession -ContainerId $theContainersId
```

Expected behavior
-----------------

We see the prompt of the remote machine

Actual behavior
---------------

```none
Enter-PSSession : Object reference not set to an instance of an object.
At line:1 char:1
+ Enter-PSSession -ContainerId (Get-Container adoring_gates).ID
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Enter-PSSession], PSInvalidOperationException
+ FullyQualifiedErrorId : CreateRemoteRunspaceForContainerFailed,Microsoft.PowerShell.Commands.EnterPSSessionCommand
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-rc.2
PSEdition                      Core
GitCommitId                    v6.0.0-rc.2
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
## PR Summary

The code tries to retrieve the runtimeid of the container, but Hyper-V team changed the type name (namespace) and from a property to a field.  To support older Windows, we first check for the new type and then fallback to checking for the old type.

Fix https://github.com/PowerShell/PowerShell/issues/5794

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

File: src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs [hunk 1]
```diff
@@ -3177,12 +3177,19 @@ public void GetContainerProperties()
...
+        /// <param name="computeSystemPropertiesType">The HCS.Compute.System.Properties type.</param>
         /// <param name="hostComputeInteropType">The Microsoft.HostCompute.Interop.HostComputeInterop type.</param>
         private static void GetHostComputeInteropTypes(out Type computeSystemPropertiesType, out Type hostComputeInteropType)
         {
             Assembly schemaAssembly = Assembly.Load(new AssemblyName("Microsoft.HyperV.Schema, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"));
-            computeSystemPropertiesType = schemaAssembly.GetType("Microsoft.HyperV.Schema.Compute.System.Properties");
+
+            // The type name was changed in newer version of Windows so we check for new one first,
+            // then fallback to previous type name to support older versions of Windows
+            computeSystemPropertiesType = schemaAssembly.GetType("HCS.Compute.System.Properties");
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: Is the both assembly APIs public? What about compliance?

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: That's an excellent question.  I'll follow-up on that.

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: The apis being used are published at https://github.com/microsoft/dotnet-computevirtualization which is considered sufficient for compliance

Comment (iSazonov) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: I see another dll vmcompute.dll is used there not Microsoft.HyperV.Schema and Microsoft.HostCompute.Interop

File: src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs [hunk 2]
```diff
@@ -3177,12 +3177,19 @@ public void GetContainerProperties()
...
+            if (computeSystemPropertiesType == null)
```
Comment (PaulHigin) [inline src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: Now that we know namespace, type properties and fields can and will change on us, I think we need to check for null values and provide a better message than "Null Reference Exception".  In the longer term we should work with the Hyper-V team to have a less fragile way to get this information.  I agree with @iSazonov, that these APIs should be public and supported.

**Review by PaulHigin — CHANGES_REQUESTED** [review]

File: src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs (hunk 1 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: I see the same pinvokes in the repo.  I'll follow-up again to see if those exported functions are documented as i couldn't find them on docs.microsoft.com

File: src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs (hunk 2 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: I'll update this to be more robust

File: src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs (hunk 1 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: The response from Hyper-V team is that the .Net wrapper serves as documentation so from a compliance perspective, we are good here.  They also inform me that documentation on the pinvoked'd win32 api's should be documented in a few weeks.

Comment (iSazonov) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: So we should migrate to vmcompute.dl?

**Review by PaulHigin — APPROVED** [review]
LGTM

File: src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs [hunk 3]
```diff
@@ -3350,7 +3365,23 @@ private void GetContainerPropertiesInternal()
...
+                    if (fieldInfo != null)
+                    {
+                        RuntimeId = (Guid)fieldInfo.GetValue(computeSystemPropertiesHandle);
+                    }
+                    else
+                    {
+                        var propertyInfo = computeSystemPropertiesType.GetProperty("RuntimeId");
+                        if (propertyInfo == null)
+                        {
+                            throw new PSInvalidOperationException(StringUtil.Format(RemotingErrorIdStrings.CannotGetHostInteropTypes));
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: > StringUtil.Format(RemotingErrorIdStrings.CannotGetHostInteropTypes)

Since there's no argument, `StringUtil.Format` is not needed. Same to other instances of this error message above.

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: Fixed all instances in this file

**Review by daxian-dbw — APPROVED** [review]
