### PR TITLE
For `NormalView`, the command should also be in the error color

### LINKED ISSUE #18549: Minor flaw in error text coloring for "NormalView' still exists in v7.3.0
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Set `$ErrorView = 'NormalView'`

2. Produce an error by issuing for example `Write-Error "blabla"` or `dir "nonexistant path"` 

### Expected behavior

Expected behavior would be that ALL error text is colorized (according to settings in  $host.PrivateData)

### Actual behavior

Main error text in `'NormalView'` is colorized correctly, but the command name and colon is not colorized, as it is in `'ConciseView'` and in PowerShell 5.1.

In addition to this I just discovered that in `'NormalView'`, when entering a command alias, the alias is not exchanged with the full command name as in `'ConciseView'` (but not in PowerShell 5.1). I don't know if this is expected behavior or not, or if it is related to the coloring flaw.

See screenshot.

### Error details

_No response_

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

The formatting of errors is split between two script blocks and only the latter applied color correctly so when using `NormalView`, the command has the default writing color instead of the error color.  This was a regression on another change which moved from using the old PrivateData based colors to the $PSStyle based ones.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/18549

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs [hunk 1]
```diff
@@ -1000,6 +1000,11 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_System_Management_Autom
                                     if (@('NativeCommandErrorMessage','NativeCommandError') -notcontains $_.FullyQualifiedErrorId -and @('CategoryView','ConciseView','DetailedView') -notcontains $ErrorView)
                                     {
                                         $myinv = $_.InvocationInfo
+                                        $errorColor = ''
+                                        if ($Host.UI.SupportsVirtualTerminal) {
+                                            $errorColor = $PSStyle.Formatting.Error
+                                        }
```
Comment (daxian-dbw) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1006]: Maybe change to the following?
```
$retValue = if ($myinv -and $myinv.MyCommand)
{
  ....
}
elseif (....)
{
  ....
}

if ($retValue -and $Host.UI.SupportsVirtualTerminal) {
    $PSStyle.Formatting.Error + $retValue  ### do you want to add the `reset` sequence here?
}
```

Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1006]: `reset` isn't needed as this is just the first part of the error message

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs [hunk 2]
```diff
@@ -1046,6 +1050,8 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_System_Management_Autom
                                             $myinv.InvocationName + ' : '
                                         }
                                     }
+
+                                    $errorColor + $commandPrefix
```
Comment (daxian-dbw) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1054]: By looking purely at the `if ($myinv -and $myinv.MyCommand)` block, it's theoretically possible that this block doesn't return a string value (maybe that's not the case practically, but from a code analysis point of view, it's possible).

In the case that the `if` block doesn't return anything, we should not return anything back from this script block, but by putting this line here, we will return a sequence for the error color.

It may be better to do the following:
```
### within the "if (@('NativeCommandErrorMessage','NativeCommandError')  ..." block

$myinv = $_.InvocationInfo
$commandPrefix = if ($myinv -and $myinv.MyCommand) {
...
}

### Pre-pend the error color only if we have a command prefix to return.
if ($commandPrefix -and $Host.UI.SupportsVirtualTerminal) {
    $PSStyle.Formatting.Error + $commandPrefix
}
```

**Review by daxian-dbw — APPROVED** [review]
LGTM
