### PR TITLE
Fix the word wrapping in formatting to handle escape sequences properly

### LINKED ISSUE #17261: Word wrapping code in formatting doesn't take into account escape sequences in strings
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Quote from https://github.com/PowerShell/PowerShell/issues/16700#issuecomment-1103474523:

> Technically, Format-List is not affected by this, but colors don't work there either, because when it wraps, the second line gets no formatting, which is _really **gross**_: 

image

And this is done by resizing the window to make the list rendering need to do word wrapping. See https://github.com/PowerShell/PowerShell/issues/16700#issuecomment-1117601312 for details.

### Expected behavior

```console
The wrapped words should keep the same color decoration.
```

### Actual behavior

```console
The wrapped words lost their color decoration.
```

### Error details

```console
N/A
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.3
PSEdition                      Core
GitCommitId                    7.3.0-preview.3-68-gd1824b287b40c8a664b90d5c724e69c749d2cef2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #17261
Fix the word wrapping in formatting to handle escape sequences properly.
The changes are mainly in 3 utility methods to take into account possible escape sequences when manipulate strings:
- `SplitLines`: split a multi-line string. Make sure the escape sequences are kept for all lines after the splitting.
- `GetWords`: split a single-line string into words. Make sure all escape sequences are kept for each word, so the decoration to the individual words is the same as they are in the string.
- `GenerateLinesWithWordWrap`. When splitting a word across multiple lines, make sure all escape sequences are kept in the same order for all individual sub-strings, so the decoration to the sub-strings is the same as they are in the original string.

Here are some examples to demonstrate the fix:

**Multi-line string in list view**

```pwsh
$m = [pscustomobject] @{ b = "`e[33mPowerShell is a task automation and configuration management program from Microsoft.`nIt consists of a command-line shell and the associated scripting language" }
$m | Format-List
```
image

**Multi-line string in list view with word wrapping**
```pwsh
$PSStyle.OutputRendering = 'Ansi'
$m = [pscustomobject] @{ b = "`e[33mPowerShell is a task `e[31mautomation and configuration`e[33m management program from Microsoft.`nIt consists of a command-line shell and the associated scripting language" }
$m | Format-List | Out-String -Width 45
```
image

**Long word across multiple lines**
```pwsh
$PSStyle.OutputRendering = 'Ansi'
$m = [pscustomobject] @{ b = "`e[33mC:\repos\PowerShell\src\`e[31mpowershell-win-core`e[33m\bin\Debug\net7.0\win7-x64\publish\pwsh.exe"; vv = "Hello world" }
$m | Format-List | Out-String -Width 40
```
image

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

File: src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs [hunk 1]
```diff
@@ -591,15 +644,37 @@ private static StringCollection GenerateLinesWithWordWrap(DisplayCells displayCe
...
                         {
-                            char charToAdd = c;
-                            int charWidth = displayCells.Length(c);
+                            vtSeqs = new StringBuilder();
+                            vtRanges = new Dictionary<int, int>();
+                            foreach (Match match in ValueStringDecorated.AnsiRegex.Matches(wordToAdd))
+                            {
+                                vtRanges.Add(match.Index, match.Length);
+                            }
+                        }
```
Comment (iSazonov) [inline src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs:657]: Why don't we use the same pattern with `new ValueStringDecorated(s);`?

File: src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs [hunk 2]
```diff
@@ -353,27 +355,62 @@ static StringManipulationHelper()
...
+                    vtRanges.Add(match.Index, match.Length);
+                }
+            }
+
+            bool wordHasVtSeqs = false;
             for (int i = 0; i < s.Length; i++)
             {
-                // Soft hyphen = \u00AD - Should break, and add a hyphen if needed. If not needed for a break, hyphen should be absent
-                if (s[i] == ' ' || s[i] == '\t' || s[i] == s_softHyphen)
+                if (vtRanges?.TryGetValue(i, out int len) == true)
```
Comment (iSazonov) [inline src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs:375]: This is used some times too but I am not sure we can move this in ValueStringDecorated.

```suggestion
                if (vtRanges?.TryGetValue(i, out int len))
```

File: src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs [hunk 3]
```diff
@@ -382,10 +419,20 @@ private static IEnumerable<GetWordsResult> GetWords(string s)
...
             }
 
-            result.Word = sb.ToString();
-            result.Delim = string.Empty;
+            if (wordHasVtSeqs)
+            {
+                if (sb.Length == vtSeqs.Length)
+                {
+                    // This indicates 'sb' only contains all VT sequences, which may happen when the string ends with a word delimiter.
+                    sb.Clear();
```
Comment (iSazonov) [inline src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs:427]: The same.

File: src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs [hunk 4]
```diff
@@ -353,27 +355,62 @@ static StringManipulationHelper()
...
-                    sb.Clear();
-                    result.Delim = new string(s[i], 1);
+                    var vtSpan = s.AsSpan(i, len);
+                    sb.Append(vtSpan);
+                    vtSeqs.Append(vtSpan);
 
-                    yield return result;
+                    wordHasVtSeqs = true;
+                    i += len - 1;
+                    continue;
```
Comment (iSazonov) [inline src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs:383]: Why do we skip vt sequence if the line ends with delimiter and vt sequence?

File: src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs [hunk 5]
```diff
@@ -353,27 +355,62 @@ static StringManipulationHelper()
...
+            var valueStrDec = new ValueStringDecorated(s);
+            if (valueStrDec.IsDecorated)
+            {
+                vtSeqs = new StringBuilder();
+                vtRanges = new Dictionary<int, int>();
+                foreach (Match match in ValueStringDecorated.AnsiRegex.Matches(s))
+                {
+                    vtRanges.Add(match.Index, match.Length);
+                }
+            }
```
[the remark this answers is not in the document]
Comment (daxian-dbw) [reply src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs:370]: Very good point! Will move this to the `ValueStringDecorated` as a utility method.

File: src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs (hunk 2 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs:375]: I don't think this check plus the if block should be moved to a utility method, as the logic is very specific to the calling context.
Also, the `== true` is required as `vtRanges` could be null.

File: src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs [hunk 6]
```diff
@@ -353,27 +355,62 @@ static StringManipulationHelper()
...
-                // Non-breaking space = \u00A0 - ideally shouldn't wrap
-                // Hard hyphen = \u2011 - Should not break
                 else if (s[i] == s_hardHyphen || s[i] == s_nonBreakingSpace)
                 {
-                    result.Word = sb.ToString();
-                    sb.Clear();
-                    result.Delim = string.Empty;
+                    // Non-breaking space = \u00A0 - ideally shouldn't wrap.
+                    // Hard hyphen = \u2011 - Should not break.
+                    delimiter = string.Empty;
```
[the remark this answers is not in the document]
Comment (daxian-dbw) [reply src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs:397]: Honestly, I don't understand either. I just tried to keep the same logic to avoid any breaking changes.

File: src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs (hunk 4 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs:383]: Because in that case the last word/line will consist of VT sequences only, with no actual character to be rendered. To the formatting system, it's the same as an empty string, so we just skip to avoid unneeded string allocations.

File: src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs (hunk 3 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs:427]: See my reply in the below comment.

File: src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs:393]: I think it is minor bug. Could you please open tracking issue so that we can discuss this later?

File: src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs (hunk 4 above)
Comment (iSazonov) [reply src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs:379]: You think about formatting codes only but there are non-formatting codes too like OSC 2 - set windows title.

File: src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs [hunk 7]
```diff
@@ -353,27 +355,58 @@ static StringManipulationHelper()
         private static IEnumerable<GetWordsResult> GetWords(string s)
         {
             StringBuilder sb = new StringBuilder();
-            GetWordsResult result = new GetWordsResult();
+            StringBuilder vtSeqs = null;
+            Dictionary<int, int> vtRanges = null;
 
+            var valueStrDec = new ValueStringDecorated(s);
+            if (valueStrDec.IsDecorated)
```
Comment (iSazonov) [inline src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs:362]: Nit: The use of IsDecorated seems unwarranted. Rather, it should be an internal implementation of ValueStringDecorated.

File: src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs (hunk 4 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs:379]: What is OSC 2? And how does that go through the formatting code here? Can you show a couple examples where this is a problem?

File: src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs (hunk 7 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs:362]: > (In general, if now PowerShell Formatting System is based on VT sequences all string sent to it should be ValueStringDecorated.)

I don't think that is necessary, or, I should say I don't see the benefit from doing that.

File: src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (daxian-dbw) [reply src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs:393]: Opened the issue: https://github.com/PowerShell/PowerShell/issues/17337

File: src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs (hunk 4 above)
Comment (iSazonov) [reply src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs:379]: OSC 2 is "set windows title". I want to say VT sequences are not only formatting but control codes too.

File: src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs (hunk 7 above)
Comment (iSazonov) [reply src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs:362]: > I think we can discuss about your idea in #16643

Is it right link? I don't see my comment there.
And yes, my proposal was to move all formatting (and path case normalization) codes to formatting system.

Comment (daxian-dbw) [reply src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs:362]: I left a comment there about this topic: https://github.com/PowerShell/PowerShell/issues/16643#issuecomment-996984580
But it may be a better idea to open a new issue just about that, if one doesn't exist yet.

File: src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs (hunk 4 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs:379]: For the "set title" control sequence in particular, the syntax is: [`ESC]2;stringBEL`](https://tldp.org/HOWTO/Xterm-Title-3.html), so there is no point to keep the VT sequence if `stringBEL` part doesn't exist.

In general, you shouldn't expect control sequences to work with PowerShell formatting. Formatting by definition is just for visualizing objects, and in my opinion, accidentally making a control sequence take effect is a bad side effect of the formatting, but that's inevitable today given that our `AnsiRegex` cannot tell VT sequences for visual effects from other VT sequences.

**Review by SeeminglyScience — APPROVED** [review]
LGTM! Very well done ♥
