### PR TITLE
Replace 'api-ms-win-core-file-l1-2-2.dll' with 'Kernell32.dll'

### LINKED ISSUE #9144: Get-Item with stream:  Unable to load DLL 'api-ms-win-core-file-l1-2-2.dll'
# Steps to reproduce

```powershell
Get-Item test.txt -Stream *
```

# Expected behavior

```none
Success result info.
```

# Actual behavior

```none
Get-Item : Unable to load DLL 'api-ms-win-core-file-l1-2-2.dll' or one of its dependencies: Не найден указанный модуль. (Exception from HRESULT: 0x8007007E)
```

$error[0] | fl * -force
```none
PSMessageDetails      :
Exception             : System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-file-l1-2-2.dll' or one of its dependencies: Не найден указанный модуль. (Exception from HRESULT: 0x8007007E)
                           at System.Management.Automation.Internal.AlternateDataStreamUtilities.NativeMethods.FindFirstStreamW(String lpFileName, StreamInfoLevels InfoLevel, AlternateStreamNativeData lpFindStreamData, UInt32 dwFlags)
                           at System.Management.Automation.Internal.AlternateDataStreamUtilities.GetStreams(String path)
                           at Microsoft.PowerShell.Commands.FileSystemProvider.GetItem(String path)
                           at System.Management.Automation.SessionStateInternal.GetItemPrivate(CmdletProvider providerInstance, String path, CmdletProviderContext context)
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Get-Item], DllNotFoundException
FullyQualifiedErrorId : System.DllNotFoundException,Microsoft.PowerShell.Commands.GetItemCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

# Environment data

OS:  Windows 8.1 x64 (6.3.9600)
 $PSVersionTable
```none
Name                           Value
----                           -----
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Fix #9144 

For reference #10417

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 1]
```diff
@@ -8596,14 +8596,14 @@ internal enum StreamInfoLevels { FindStreamInfoStandard = 0 }
                 IntPtr lpSecurityAttributes, FileMode dwCreationDisposition,
                 int dwFlagsAndAttributes, IntPtr hTemplateFile);
 
-            [DllImport(PinvokeDllNames.FindFirstStreamDllName, ExactSpelling = true, CharSet = CharSet.Unicode, SetLastError = true)]
+            [DllImport("kernel32.dll", ExactSpelling = true, CharSet = CharSet.Unicode, SetLastError = true)]
```
Comment (SteveL-MSFT) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Wouldn't it be better to change `FindFirstStreamDllName` to point to `kernel32.dll`?

Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs]: I believe we could preserve these constants (as reminder) if we want revert the change after Windows 8 (and 7) EOL.

**Review by adityapatwardhan — APPROVED** [review]
