### PR TITLE
Fix Travis-CI macOS run

### LINKED ISSUE #5062: Travis CI macOS Builds are failing
It appears something has changed, possibly external, and all of the macOS builds are failing (including nightly)

```none
./installpsh-osx.sh: line 99: [: missing `]'

\n*** Installing PowerShell Core for osx...

Howebrew is already installed, skipping...

Installing cask...

Updating Homebrew...

==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz

######################################################################## 100.0%

==> Pouring portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz

/usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': Homebrew must be run under Ruby 2.3! (RuntimeError)

ERROR: Cask failed to install! Cannot install powershell...

The command "./install-powershell.sh" failed and exited with 2 during .
```

examples: 

- https://travis-ci.org/PowerShell/PowerShell/jobs/285387333
- https://travis-ci.org/PowerShell/PowerShell/jobs/285471140
- https://travis-ci.org/PowerShell/PowerShell/jobs/285293168
- https://travis-ci.org/PowerShell/PowerShell/jobs/285388460 (nightly)

Also, the nightly badge for Travis CI macOS reports success when it clearly failed.

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
Fixed some formatting and output issues.  Main fix to get the build working is moving `brew update` earlier (thanks @TravisEz13).  Removed sudo check as it fails on Travis-CI

Fix https://github.com/PowerShell/PowerShell/issues/5062

### CODE REVIEW

File: tools/installpsh-osx.sh [hunk 1]
```diff
@@ -93,14 +93,13 @@ if (( $EUID != 0 )); then
...
 #Check that sudo is available
-if [[ "$SUDO" -eq "sudo" ]]; then
-
-    $SUDO -v
-    if [ $? -ne 0]; then
-      echo "ERROR: You must either be root or be able to use sudo" >&2
-      exit 5
-    fi
-fi
+#if [[ "$SUDO" -eq "sudo" ]]; then
```
Comment (TravisEz13) [inline tools/installpsh-osx.sh]: We should remove this commented code if it's not needed

**Review by TravisEz13 — APPROVED** [review]

File: tools/installpsh-osx.sh (hunk 1 above)
Comment (SteveL-MSFT) [reply tools/installpsh-osx.sh]: It's not clear to me if this is needed for local execution of this script or if anyone actually uses these scripts locally outside of CI
