### PR TITLE
Fix incorrect name check when autoloading required modules

### LINKED ISSUE #8204: RequiredModules manifest property stopped working recently (noticed in daily build)
This issue started only in the last few days using the daily build and does not happen with `6.1` or `6.1-preview`.
Calling `Import-Module` on a module that declares `RequiredModules = @('C:\full\path\to\manifest.psd1')`, causes loading of it to fail. A specific example of such a manifest is [here](https://github.com/bergmeister/posh-profile/blob/master/source/posh-profile.psd1) but even if I change it to just one dependent module with a full path, it still happens, therefore I think the issue is generic to any manifest. with `RequiredModules`

Steps to reproduce
------------------

```powershell
Import-Module $PathToManifestThatDeclaresRequiredModules
```

Expected behavior
-----------------

Imports dependent modules

Actual behavior
---------------

Throws because it fails to import dependent modules.
```
Import-Module : The required module 'C:\Users\cberg\git\posh-profile\source\dotnetCli\dotnetCli.psd1' is not loaded. Load the module or remove the module from 'RequiredModules' in the file 'C:\Users\cberg\git\posh-profile\source\posh-profile.psd1'.
```
Loading the dependent module works fine but an `Import-Module` of the main module fails again with the same error

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.2.0-preview.864
PSEdition                      Core
GitCommitId                    6.2.0-preview.864
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by rjmholt**
## PR Summary

Fixes #8204.

The change I made in #7125 made the check too strict on the module we try to autoload it from requires and rejected it based on name.

This PR removes that name check but also sets up a fix for the more general problem that a `ModuleSpecification` can always specify a path rather than a name. I added some reusable logic to make this easier to service.

The main contribution is regression testing for `RequiredModules`, `#requires -Modules` and other cmdlets that can use `ModuleSpecification`s.

However, the general pervasive problem is that `ModuleSpecification`s contain raw user input and we don't do very much about handling paths that might be given as module names, namely:
  - Normalising directory separators
  - Resolving relative paths (which should be resolved differently depending on context)
  - Dealing with case-sensitivity
  - Handling trailing slashes
  - Matching on module directories accounting for the versioned directory structure
  - Working with special directory names like `.` and `..`

The methods I've added deal with these and I've applied them in one place to help correct the immediate problem and make it more efficient.

But the fact remains that we have no way in the type system to identify when this resolution has already occurred; there are over 120 uses of the `ModuleSpecification` type in the code base, and we don't have a way to differentiate when they contain raw user input and when they can be trusted to have a canonical path. The way the module cmdlets are written currently, we redo a fair amount of this validation and normalisation logic, and it's probably somewhere we could find serious perf improvements.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [x] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by bergmeister** [comment]
Thanks for handling the issue. I'd consider a regression test for this important feature to be essential.

**Comment by rjmholt** [comment]
Agreed that it's essential -- I'm pretty surprised we didn't have one already.

I'm halfway through writing some already.

**Comment by bergmeister** [comment]
Ok, feel free to add the test in a 2nd PR as I can understand that this is a time-pressing issue that can initially be verified with some manual testing (please include Windows as test platform though)

**Comment by rjmholt** [comment]
We also seem to do required module autoloading in `#requires` pragmas:
https://github.com/PowerShell/PowerShell/blob/4118fd2829cb1a0a64005bd5b84e08ca7ea354e2/src/System.Management.Automation/engine/CommandDiscovery.cs#L307-L313

If those are supposed to allow paths, I'll need to do the same path normalisation logic there.

**Comment by adityapatwardhan** [comment]
@rjmholt 1 new test is failing on Linux and macOS. Please have a look.

**Comment by adityapatwardhan** [comment]
@daxian-dbw  Please have a look at this.

**Comment by adityapatwardhan** [comment]
@rjmholt Restarted AppVeyor to pickup test fix.

File: src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs [hunk 1]
```diff
@@ -4541,16 +4552,21 @@ internal string GetAbsolutePath(string moduleBase, string path)
...
+        /// <summary>
+        /// Check if a path is rooted or "relative rooted".
+        /// </summary>
+        /// <param name="filePath">The file path to check.</param>
+        /// <returns>True if the path is rooted, false otherwise.</returns>
         internal static bool IsRooted(string filePath)
         {
-            return (Path.IsPathRooted(filePath) ||
+            return Path.IsPathRooted(filePath) ||
                 filePath.StartsWith(@".\", StringComparison.Ordinal) ||
```
[the remark this answers is not in the document]
Comment (rjmholt) [reply src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs]: Also the .NET team now recommends `Path.IsFullyQualified()` rather than `Path.IsRooted()`.

**Comment by rjmholt** [comment]
The failing AppVeyor test is passing on my machine. Looking into it.

File: src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs [hunk 2]
```diff
@@ -659,6 +667,114 @@ internal static bool IsModuleMatchingModuleSpec(out ModuleMatchFailure matchFail
...
+            moduleName = moduleName.Replace(Path.AltDirectorySeparatorChar, Path.DirectorySeparatorChar);
+
+            // Path.IsRooted() is deprecated -- see https://github.com/dotnet/corefx/issues/22345
+            if (!Path.IsPathFullyQualified(moduleName))
+            {
+                moduleName = Path.Join(basePath, moduleName);
+            }
+
+            // Use the PowerShell filesystem provider to fully resolve the path
+            return ModuleCmdletBase.GetResolvedPath(moduleName, executionContext).TrimEnd(Path.DirectorySeparatorChar);
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs]: What would happen if `GetResolvedPath` cannot resolve `moduleName`?

File: src/System.Management.Automation/engine/Modules/RemoveModuleCommand.cs [hunk 3]
```diff
@@ -84,6 +84,11 @@ protected override void ProcessRecord()
 
             if (FullyQualifiedName != null)
             {
+                // TODO:
+                // Paths in the module name may fail here because
+                // they the wrong directory separator or are relative.
+                // Fix with the code below:
+                // FullyQualifiedName = FullyQualifiedName.Select(ms => ms.WithNormalizedName(Context, SessionState.Path.CurrentLocation.Path)).ToArray();
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/Modules/RemoveModuleCommand.cs]: What's the concern about putting this fix in place? Regression? Perf degradation?

File: src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs]: Why not replace `Path.IsPathRooted` with `Path.IsPathFullyQualified`?

[the remark this answers is not in the document]
Comment (rjmholt) [reply src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs]: I don't depend on this method and don't want to break anything. Just wanted to note it here. Either way, it didn't help my needs since this method counts `"../here"` as "rooted".

An earlier version of my fix changed this method and used it, but I decided it's better not to touch too much.

File: src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs [hunk 4]
```diff
@@ -575,8 +581,10 @@ internal static bool IsModuleMatchingModuleSpec(out ModuleMatchFailure matchFail
             Version minimumRequiredVersion,
             Version maximumRequiredVersion)
         {
-            // If a name is required, check it matches
-            if (requiredName != null && !requiredName.Equals(moduleName, StringComparison.OrdinalIgnoreCase))
+            // If a name is required, check that it matches.
+            // A required module name may also be an absolute path, so check it against the given module's path as well.
+            if ((requiredName != null && !requiredName.Equals(moduleName, StringComparison.OrdinalIgnoreCase))
+                && !MatchesModulePath(modulePath, requiredName))
```
[the remark this answers is not in the document]
Comment (rjmholt) [reply src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs]: Yes, good catch

File: src/System.Management.Automation/engine/Modules/RemoveModuleCommand.cs (hunk 3 above)
Comment (rjmholt) [reply src/System.Management.Automation/engine/Modules/RemoveModuleCommand.cs]: Just keeping the fix constrained in this PR. It shouldn't cause regressions or perf degradations, but to ensure there are no regressions (since this PR is a regression fix itself) I just left it as a comment.

File: src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs (hunk 2 above)
Comment (rjmholt) [reply src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs]: We end up in this logic:
https://github.com/PowerShell/PowerShell/blob/caad7ed471d46629f155a2c7ccbbafa4ffc29355/src/System.Management.Automation/namespaces/LocationGlobber.cs#L121-L246

I think it's relatively safe and well tested -- it doesn't look like it's designed to throw.

The call to `ModuleBase.GetResolvedPath()` itself surrounds the globber call with a `try`/`catch` and if anything bad happens returns `null`.

I've added a line to check for the `null` return and replace it with the original "un-resolved" module name, just in case.

File: src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs]: > it didn't help my needs since this method counts "../here" as "rooted".

This is what I see:
```powershell
PS:2> [System.IO.Path]::IsPathRooted("../here")
False
PS:3> [System.IO.Path]::IsPathFullyQualified("../here")
False
```
I'm mainly curious about the different between `Path.IsPathRooted` and `Path.IsPathFullyQualified`. If there is no difference in behavior, then we should follow the guidance and replace it in our code.

[the remark this answers is not in the document]
Comment (rjmholt) [reply src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs]: Sorry I meant the `ModuleCmdletBase.IsRooted("../here")` method.

I didn't change the body in terms of how it works just in case I break it.

But agreed, we should probably change it.

There is a similar new change in .NET Core 2.1 with `Path.Join()` vs `Path.Combine()` which seems to just be a `ReadOnlySpan<char>` API difference, but we should look into it.

[the remark this answers is not in the document]
Comment (rjmholt) [reply src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs]: I've put the parens back into `ModuleCmdletBase.IsRooted` so that my PR doesn't touch it (since I don't use it now).

I think we should move over to `Path.IsFullyQualified` but do it in another PR. I haven't looked at `ModuleCmdletBase.IsRooted` very much here and haven't added any testing for regressions in it.

File: src/System.Management.Automation/engine/Modules/GetModuleCommand.cs [hunk 5]
```diff
@@ -374,6 +374,9 @@ protected override void ProcessRecord()
             var moduleSpecTable = new Dictionary<string, ModuleSpecification>(StringComparer.OrdinalIgnoreCase);
             if (FullyQualifiedName != null)
             {
+                // TODO: Paths here will not match a module name.
+                //       The table match logic will mean that a module with the right
+                //       name but wrong path or version will still get returned.
```
[the remark this answers is not in the document]
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/Modules/GetModuleCommand.cs]: Thanks for clarifying it. I think the comment should be split in two places.
Here, we can call out `"TODO: ModuleSpecification.Name could be a path while we assume it's always the module name in 'FilterModulesForSpecificationMatch', which is potentially a bug. We should normalize the ModuleSpecification.Name here."`

In `FilterModulesForSpecificationMatch`, we call out that `"TODO: The name of a 'ModuleSpecification' could be a path. If that's the case, we won't be able to find the module even if the same module is actually in 'moduleSpecificationTable'. We should consider to cover that case, by doing a path test in that case."`

Feel free to reword the comments :)

File: src/System.Management.Automation/engine/Modules/RemoveModuleCommand.cs (hunk 3 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/Modules/RemoveModuleCommand.cs]: Will you open issue to track all those `todo` comments? They can be easily forgotten :)

File: src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs [hunk 6]
```diff
@@ -760,7 +760,10 @@ internal static bool MatchesModulePath(string modulePath, string requiredPath)
             }
 
             // Use the PowerShell filesystem provider to fully resolve the path
-            return ModuleCmdletBase.GetResolvedPath(moduleName, executionContext).TrimEnd(Path.DirectorySeparatorChar);
+            // If there is a problem, null could be returned -- so default back to the pre-normalized path
+            string normalizedPath = ModuleCmdletBase.GetResolvedPath(moduleName, executionContext) ?? moduleName;
+                
+            return normalizedPath.TrimEnd(Path.DirectorySeparatorChar);
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs]: Maybe not important, but in case you get a `null` from `GetResolvedPath`, `TrimEnd` shouldn't be called on the original module name.

File: src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs [hunk 7]
```diff
@@ -750,8 +750,14 @@ internal static bool MatchesModulePath(string modulePath, string requiredPath)
...
 
+#if UNIX
+    // On *nix, Path.AltDirectorySeparatorChar is '/', but PowerShell also supports '\\' as a dir separator
+    const char altDirSeparatorChar = '\\';
+#else
+    const char altDirSeparatorChar = Path.AltDirectorySeparatorChar;
+#endif
             // Standardize directory separators
-            moduleName = moduleName.Replace(Path.AltDirectorySeparatorChar, Path.DirectorySeparatorChar);
+            moduleName = moduleName.Replace(altDirSeparatorChar, Path.DirectorySeparatorChar);
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs]: I expect `GetResolvedPath` will take care of the path normalization, but need to verify that. If that's the case, we don't need this path separator replacement.
And, in case we really need this, please use the existing `StringLiterals.DefaultPathSeparator` and `StringLiterals.AlternatePathSeparator`.

File: src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs (hunk 2 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs]: Yes, null reference is my main concern here. As long as that's guarded, it should be good.

File: src/System.Management.Automation/engine/Modules/ModuleSpecification.cs [hunk 8]
```diff
@@ -247,6 +247,31 @@ public static bool TryParse(string input, out ModuleSpecification result)
...
         }
 
+        /// <summary>
+        /// Copy the module specification while normalizing the name
+        /// so that paths become absolute and use the right directory separators.
+        /// </summary>
+        /// <param name="context">The current execution context. Used for path normalization.</param>
+        /// <param name="basePath">The base path where a relative path should be interpreted with respect to.</param>
+        /// <returns>A fresh module specification object with the name normalized for use internally.</returns>
+        internal ModuleSpecification WithNormalizedName(ExecutionContext context, string basePath)
```
[the remark this answers is not in the document]
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/Modules/ModuleSpecification.cs]: Thanks for the clarification. Looks good to me.

File: src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs [hunk 9]
```diff
@@ -659,6 +667,114 @@ internal static bool IsModuleMatchingModuleSpec(out ModuleMatchFailure matchFail
...
+
+            // Save some allocations here if module path doesn't sit under the required path
+            // (the required path may still refer to some nested module though)
+            if (!modulePath.StartsWith(requiredPath, strcmp))
+            {
+                return false;
+            }
+
+            // Otherwise, the required module may point to the module base directory
+            string moduleDirPath = Path.GetDirectoryName(modulePath);
```
[the remark this answers is not in the document]
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs]: It would be helpful to add comment with your words in this method.

File: src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs [hunk 10]
```diff
@@ -659,6 +668,124 @@ internal static bool IsModuleMatchingModuleSpec(out ModuleMatchFailure matchFail
...
+            {
+                moduleName = Path.Join(basePath, moduleName);
+            }
+
+            // Use the PowerShell filesystem provider to fully resolve the path
+            // If there is a problem, null could be returned -- so default back to the pre-normalized path
+            string normalizedPath = ModuleCmdletBase.GetResolvedPath(moduleName, executionContext)?.TrimEnd(StringLiterals.DefaultPathSeparator);
+
+            // ModuleCmdletBase.GetResolvePath will return null in the unlikely event that it failed.
+            // If it does, we return the fully qualified path we return the fully qualified path generated before.
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs]: > we return ... we return ...

Please fix the comment.

File: src/System.Management.Automation/engine/Modules/RemoveModuleCommand.cs (hunk 3 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/Modules/RemoveModuleCommand.cs]: Did you open an issue to track those todo's?

Comment (rjmholt) [reply src/System.Management.Automation/engine/Modules/RemoveModuleCommand.cs]: Next on my list

**Review by daxian-dbw — APPROVED** [review]
Only pending action item left is to open an issue tracking all "TODO" comments.

**Comment by adityapatwardhan** [comment]
Since the CodeFactor issues are for existing methods, re-ordering will cause larger diffs. We can ignore CodeFactor issues for this PR.
