### PR TITLE
Re-enable VT mode on Windows after running command in ConsoleHost

### LINKED ISSUE #14360: ANSI escape codes in prompt incorrectly rendered in some cases
After a pipeline that contains a some programs from Git for Windows (e.g., cat.exe), ANSI escape codes in the prompt are incorrectly rendered.

## Steps to reproduce

1. Setup a prompt function that sets the prompt to *MyPrompt* in green.
2. Run a command that pipes data through cat.exe from Git for Windows (problem also occurs with other programs as well, but cat.exe is the simplest).

```none
doug> function prompt { $ESC = [char]27; "$ESC[38;2;0;255;0mMyPrompt$ESC[0m>" }
MyPrompt>echo "n"| & 'C:\Program Files\Git\usr\bin\cat.exe'
n
←[38;2;0;255;0mMyPrompt←[0m>
```

## Expected behavior

*MyPrompt* should be green.

```none
MyPrompt>
```

## Actual behavior

The prompt is white with the color codes visible.

```none
←[38;2;0;255;0mMyPrompt←[0m>
```

## Environment data

```none
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Additional Notes

This problem does not occur in Windows Powershell.

This problem occurs with Powershell Core 7.1.0 both running in Windows Terminal and running PowerShell 7 directly.

This issue was originally reported to microsoft/terminal#8525, but some investigation led me to believe the problem is in PowerShell Core, not Windows Terminal (see details of that bug for more information).

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

On Windows, some popular native commands (like those shipped with Git) will disable console VT mode and doesn't set it back upon execution.  When the prompt comes back, you see escape sequence characters instead of rendered text.  Fix is to check if VT mode was previously enabled and try turning it back on.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/14360

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs [hunk 1]
```diff
@@ -64,6 +64,15 @@ internal ConsoleHostUserInterface(ConsoleHost parent)
 #if UNIX
             SupportsVirtualTerminal = true;
 #else
+            SupportsVirtualTerminal = TryTurnOnVtMode();
+#endif
```
Comment (iSazonov) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs:68]: We could move this in `TryTurnOnVtMode()` and have here:
```suggestion
            SupportsVirtualTerminal = TryTurnOnVtMode();
```

Comment (SteveL-MSFT) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs:68]: Since we compile specifically for non-Windows, seems unnecessary to have that helper for non-Windows.

**Review by Steg17 — APPROVED** [review]

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs (hunk 1 above)
Comment (iSazonov) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs:68]: `#if UNIX` would be in TryTurnOnVtMode(). This makes the code more readable.

**Comment by drichardson** [comment]
Any chance this could get a review from someone with write access? This one line change has been waiting for review for a few months now.

**Review by anmenaga — APPROVED** [review]
LGTM
