### PR TITLE
Use the same temp personal module path when env 'HOME' not defined

### LINKED ISSUE #13189: System.IO.DirectoryNotFoundException using -Parallel feature and Microsoft.PowerShell.SDK
This is a part 2 of https://github.com/PowerShell/PowerShell/issues/13132. I'm running PowerShell scripts using executed from a .NET program using **Microsoft.PowerShell.SDK**. The package bundle is created using `--runtime linux-x64` switch with `dotnet publish`.

Initially I it was always failing and with the previous issue it was discovered I need to move the Modules folder in the runtimes folder up to the root of the publish folder.

Now that I have implemented that workaround of moving the Module folder to the root of the publish folder I'm getting the following error about 10% of the time. 

The repo is the same as is explained in the https://github.com/PowerShell/PowerShell/issues/13132 except before executing the `runtimes/win/lib/netcoreapp3.1/Modules` folder is copied up to root of the publish folder.

@daxian-dbw

```
2020-07-15 23:21:04: [Error] - An unexpected error has occurred while processing ForEach-Object -Parallel input. This may mean that some of the piped input did not get processed. Error: System.IO.DirectoryNotFoundException: Could not find a part of the path '/tmp/32029fe7-1d55-4203-bdb1-898dfea7c7d0/.local/share/powershell/Modules'.
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at System.Management.Automation.Platform.SelectProductNameForDirectory(XDG_Type dirpath)
   at System.Management.Automation.ModuleIntrinsics.GetPersonalModulePath()
   at System.Management.Automation.ModuleIntrinsics.GetModulePath(String currentProcessModulePath, String hklmMachineModulePath, String hkcuUserModulePath)
   at System.Management.Automation.ModuleIntrinsics.SetModulePath()
   at System.Management.Automation.ModuleIntrinsics..ctor(ExecutionContext context)
   at System.Management.Automation.ExecutionContext.InitializeCommon(AutomationEngine engine, PSHost hostInterface)
   at System.Management.Automation.ExecutionContext..ctor(AutomationEngine engine, PSHost hostInterface, InitialSessionState initialSessionState)
   at System.Management.Automation.AutomationEngine..ctor(PSHost hostInterface, InitialSessionState iss)
   at System.Management.Automation.Runspaces.LocalRunspace.DoOpenHelper()
   at System.Management.Automation.Runspaces.LocalRunspace.OpenHelper(Boolean syncCall)
   at System.Management.Automation.Runspaces.RunspaceBase.CoreOpen(Boolean syncCall)
   at System.Management.Automation.Runspaces.RunspaceBase.Open()
   at System.Management.Automation.PSTasks.PSTaskBase.Start()
   at System.Management.Automation.PSTasks.PSTaskPool.Add(PSTaskBase task)
   at Microsoft.PowerShell.Commands.ForEachObjectCommand.<InitParallelParameterSet>b__63_2(Object _).

```

## Environment data

```json
{
  "SerializationVersion": {
    "Major": 1,
    "Minor": 1,
    "Build": 0,
    "Revision": 1,
    "MajorRevision": 0,
    "MinorRevision": 1
  },
  "WSManStackVersion": {
    "Major": 3,
    "Minor": 0,
    "Build": -1,
    "Revision": -1,
    "MajorRevision": -1,
    "MinorRevision": -1
  },
  "PSCompatibleVersions": [
    {
      "Major": 1,
      "Minor": 0,
      "Build": -1,
      "Revision": -1,
      "MajorRevision": -1,
      "MinorRevision": -1
    },
    {
      "Major": 2,
      "Minor": 0,
      "Build": -1,
      "Revision": -1,
      "MajorRevision": -1,
      "MinorRevision": -1
    },
    {
      "Major": 3,
      "Minor": 0,
      "Build": -1,
      "Revision": -1,
      "MajorRevision": -1,
      "MinorRevision": -1
    },
    {
      "Major": 4,
      "Minor": 0,
      "Build": -1,
      "Revision": -1,
      "MajorRevision": -1,
      "MinorRevision": -1
    },
    {
      "Major": 5,
      "Minor": 0,
      "Build": -1,
      "Revision": -1,
      "MajorRevision": -1,
      "MinorRevision": -1
    },
    {
      "Major": 5,
      "Minor": 1,
      "Build": 10032,
      "Revision": 0,
      "MajorRevision": 0,
      "MinorRevision": 0
    },
    {
      "Major": 6,
      "Minor": 0,
      "Build": 0,
      "Revision": -1,
      "MajorRevision": -1,
      "MinorRevision": -1
    },
    {
      "Major": 6,
      "Minor": 1,
      "Build": 0,
      "Revision": -1,
      "MajorRevision": -1,
      "MinorRevision": -1
    },
    {
      "Major": 6,
      "Minor": 2,
      "Build": 0,
      "Revision": -1,
      "MajorRevision": -1,
      "MinorRevision": -1
    },
    {
      "Major": 7,
      "Minor": 0,
      "Build": 2,
      "Revision": -1,
      "MajorRevision": -1,
      "MinorRevision": -1
    }
  ],
  "Platform": "Unix",
  "GitCommitId": "7.0.2",
  "PSRemotingProtocolVersion": {
    "Major": 2,
    "Minor": 3,
    "Build": -1,
    "Revision": -1,
    "MajorRevision": -1,
    "MinorRevision": -1
  },
  "PSVersion": {
    "Major": 7,
    "Minor": 0,
    "Patch": 2,
    "PreReleaseLabel": null,
    "BuildLabel": null
  },
  "PSEdition": "Core",
  "OS": "Linux 4.14.165-102.205.amzn2.x86_64 #1 SMP Fri Feb 14 22:46:57 UTC 2020"
}
```

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #13189

When the env variable `HOME` is not defined, every Runspace startup on Unix platforms will try creating a folder in the form of `/tmp/<new-guid>/.local/share/powershell/Modules` as the personal user module path. That means LOTs of such folders get created when `Foreach-Object -Parallel` is dealing with a lot of inputs. In that situation, it may not be surprising to see strange failures like the `DirectoryNotFoundException` reported in the issue.

This PR adds a static field to cache the temporary personal user module path, so all Runspace's will use the same temp directory path in case `HOME` env variable is not defined.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Review by rjmholt — APPROVED** [review]

**Comment by rjmholt** [comment]
> N/A or can only be tested interactively

I wonder if it's possible to test this by unsetting `$env:HOME`

**Review by PaulHigin — APPROVED** [review]
Thanks for fixing this!  I don't think we need tests for this change, and as long as current tests pass I feel we are good.

**Comment by rjmholt** [comment]
@PoshChan please remind me in 23 hours

File: src/System.Management.Automation/CoreCLR/CorePsPlatform.cs [hunk 1]
```diff
@@ -252,7 +254,8 @@ public static string SelectProductNameForDirectory(Platform.XDG_Type dirpath)
             string envHome = System.Environment.GetEnvironmentVariable(CommonEnvVariableNames.Home);
             if (envHome == null)
             {
-                envHome = GetTemporaryDirectory();
+                s_tempHomeDir ??= GetTemporaryDirectory();
+                envHome = s_tempHomeDir;
```
Comment (iSazonov) [inline src/System.Management.Automation/CoreCLR/CorePsPlatform.cs:258]: You assume that HOME could be defined on the fly (and preserve current behavior) but we could already put some files in previous folder :-(

**Comment by PoshChan** [comment]
@rjmholt, this is the reminder you requested 23 hours ago

**Comment by iSazonov** [comment]
Will be this backported to 7.0?

**Comment by rjmholt** [comment]
> Will be this backported to 7.0?

@PaulHigin @daxian-dbw

File: src/System.Management.Automation/CoreCLR/CorePsPlatform.cs (hunk 1 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/CoreCLR/CorePsPlatform.cs:258]: Sorry that I missed this comment. I think it would be very unlikely that the `HOME` env var changes it value after it's declared, so I'm not too worry about this.

**Comment by daxian-dbw** [comment]
Good question. Maybe it's worth backporting, given the fix is so simple.
Marked this PR `maintainer - review`
