### PR TITLE
Fix retrieving dynamic parameters from provider even if globbed path returns no results

### LINKED ISSUE #6527: Parameter binding error in Copy-Item -ToSession when using range wildcards in -Path
Steps to reproduce
------------------

```powershell
$sss = New-PSSession server
Copy-Item -Path 'c:\temp\[x]*' -Destination 'c:\temp' -ToSession $sss
```

Expected behavior
-----------------
Everything that starts with the letter 'x' in the temp folder was copied to server "server".

Actual behavior
---------------

```powershell
PS C:\> Copy-Item -Path 'c:\temp\[x]*' -Destination 'c:\temp' -ToSession $sss
Copy-Item : A parameter cannot be found that matches parameter name 'ToSession'.
At line:1 char:55
+ Copy-Item -Path 'c:\temp\[x]*' -Destination 'c:\temp' -ToSession $sss
+                                                       ~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Copy-Item], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
```

Environment data
----------------

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

The problem only occurs with a cmdlet that relies on a provider and the path has a wildcard that returns no results.  The simple repro is:

```powershell
$s = New-PSSession .
copy-item c:\foo* -Destination ~ -ToSession $s
```

You'll get a parameter binding error that `-ToSession` is not a valid parameter.  What's happening is that the parameter binder uses the path to find a provider.  It correctly finds the filesystem provider and then uses that to glob the wildcard for results.  Since the wildcard doesn't match any results, the logic incorrectly skips binding dynamic parameters, so the user gets an unhelpful error message.

The fix is to not require that globbing returns any results, just that a provider was returned.  Then I removed an assertion checking that the path is not null.  I looked through the source code for implementations of `CopyItemDynamicParameters()` and the FileSystemProvider doesn't even use the path so it doesn't matter if it's null or not.  The other cases already check if path is null and handles it so the assertion is not necessary even if it only affects debug builds.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/6527

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Review by vexx32 — APPROVED** [review]
LGTM!

File: src/System.Management.Automation/engine/SessionStateContainer.cs [hunk 1]
```diff
@@ -4681,7 +4681,7 @@ internal bool HasChildItems(string path, bool force, bool literalPath)
                 }
             }
 
-            if (providerPath != null)
+            if (providerInstance != null)
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/SessionStateContainer.cs:4684]: I was very wonder to read comments in the method above.
Is the method used for both FromSession and ToSession?
If so I wonder again because obviously the method is only for FromSession  scenario.

File: test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1 [hunk 2]
```diff
@@ -256,6 +256,11 @@ Describe "Parameter Binding Tests" -Tags "CI" {
         DynamicParamTest -PipelineVariable bar | ForEach-Object { $bar } | Should -Be "hi"
     }
 
+    It 'Dynamic parameter is found even if globbed path does not exist' {
+        $guid = New-Guid
+        { Copy-Item "~\$guid*" -Destination ~ -ToSession $null } | Should -Throw -ErrorId 'ParameterArgumentValidationError'
```
Comment (iSazonov) [inline test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1:261]: It is not correct test for the PR's issue.
```powershell
> copy-item c:\noexist -Destination C:\temp\ -ToSession $null

Copy-Item: Cannot validate argument on parameter 'ToSession'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
```

File: src/System.Management.Automation/engine/SessionStateContainer.cs (hunk 1 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/SessionStateContainer.cs:4684]: This is independent from `ToSession` and `FromSession`, it applies to all dynamic parameters

File: test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1 (hunk 2 above)
Comment (SteveL-MSFT) [reply test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1:261]: Perhaps I should add a comment to the test to clarify.  What this is validating is an error coming from the provider and not the parameter binder (which was the original issue)

File: src/System.Management.Automation/engine/SessionStateContainer.cs (hunk 1 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/SessionStateContainer.cs:4684]: I say that original design was broken - it makes no sense to check the path existence if it is on remote.
Next question is does it make sense to check the existence for local path? If it even makes sense this is the wrong place for it - all we need is the providerInstance as you said.

Do we really need globbing? I suggest to make minor breaking change and use GetUnresolvedProviderPathFromPSPath() or GetProviderPath().

Then if providerInstance is null then pathNotFoundOnClient is always true and we always effectively fall back to FileSystemProvider:

```c#
        internal object CopyItemDynamicParameters(
            string path,
            string destination,
            bool recurse,
            CmdletProviderContext context)
        {
            if (path is null)
            {
                return null;
            }

            ProviderInfo provider = null;
            string providerPath = null;
            try
            {
                providerPath =
                    context.ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath(
                        path,
                        context,
                        out provider,
                        out _);
            }
            catch (DriveNotFoundException)
            {
                // This exception is expected for remote sessions where drives exist in a remote session but not
                // on the client.
            }
            catch (ItemNotFoundException)
            {
                // This exception is expected for remote sessions where item exist in a remote session but not
                // on the client.
            }

            if (provider is null)
            {
                // At this point, we don't know if this is a remote use of copy-item because the FromSession
                // and ToSession dynamic parameters have not been retrieved yet.
                // Ignore these exceptions and use the FileSystem provider as default.  If this is a real drive
                // issue, or if the item does not exist, it will be caught later when the drive or item path is used.
                var fileSystemProviders = Providers["FileSystem"];
                if (fileSystemProviders.Count > 0)
                {
                    providerPath = path;
                    provider = fileSystemProviders[0];
                }
            }

            if (provider is null)
            {
                return null;
            }

            CmdletProvider providerInstance = ExecutionContext.EngineSessionState.GetProviderInstance(provider);
            return providerInstance is null ? null : CopyItemDynamicParameters(providerInstance, providerPath, destination, recurse, context);
        }
```

File: test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1 (hunk 2 above)
Comment (iSazonov) [reply test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1:264]: Without the fix I get `ParameterArgumentValidationError`.

File: src/System.Management.Automation/engine/SessionStateContainer.cs (hunk 1 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/SessionStateContainer.cs:4684]: I'm not sure what the original design intent was, but the path(s) after globbing are passed down to the dynamic parameter (so null is now possible where it wasn't before, but it's an assert so could have happened in retail builds anyways), so presumably a provider could use that information and we should probably not make that breaking change.

File: test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1 (hunk 2 above)
Comment (SteveL-MSFT) [reply test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1:264]: @iSazonov did you try this on Windows?  It seems to only repro on Windows now that I tried it on macOS

File: src/System.Management.Automation/engine/SessionStateContainer.cs (hunk 1 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/SessionStateContainer.cs:4684]: > the path(s) after globbing are passed down to the provider for dynamic parameters

> so presumably a provider could use that information

This just makes me think that it's much more useful to pass the original path than after globbing, otherwise in CopyItemDynamicParameters there's no way to know that globbing was used.  I believe it is more right design and the breaking change is under bracket 3 (unlikely breaking change).

Although if you find it totally unacceptable, it's worth cleaning up the code anyway, like in my sample.

> so null is now possible where it wasn't before

providerPath argument is never null in CopyItemDynamicParameters().

File: test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1 (hunk 2 above)
Comment (iSazonov) [reply test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1:264]: Yes, on Windows.

Comment (SteveL-MSFT) [reply test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1:264]: Did you make sure to include a wildcard?

```console
PS> copy-item c:\foo* -Destination ~ -tosession $null
Copy-Item: A parameter cannot be found that matches parameter name 'tosession'.
PS> copy-item c:\foo -Destination ~ -tosession $null
Copy-Item: Cannot validate argument on parameter 'ToSession'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
```

File: src/System.Management.Automation/engine/SessionStateContainer.cs (hunk 1 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/SessionStateContainer.cs:4684]: Not `providerPath`, but just `path`.  I think if provider authors would find value in the original search path, we would have heard about it.  I don't think it's worth making this change.

Comment (iSazonov) [reply src/System.Management.Automation/engine/SessionStateContainer.cs:4684]: > Not providerPath, but just path.

I don't understand. The method starts with:
```
            if (path == null)
            {
                return null;
            }
```

> I think if provider authors would find value in the original search path, we would have heard about it. I don't think it's worth making this change.

I guess nobody uses this :-) I mainly think that the binder is already too slow and we could make it faster.

File: test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1 (hunk 2 above)
Comment (iSazonov) [reply test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1:264]: Ah sorry, I copy-pasted the test with $guid null.

File: src/System.Management.Automation/engine/SessionStateContainer.cs (hunk 1 above)
Comment (PaulHigin) [reply src/System.Management.Automation/engine/SessionStateContainer.cs:4684]: I agree that this is code seems wrong and that parameter binding is not the right place to do path validation.  My guess is this code was here when copy-item was local only, and then adjusted when copy-item was extended to support remote copy.

I feel it is worth considering a breaking change to re-review this and possibly fix it.

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/SessionStateContainer.cs:4684]: I would prefer to take a small change now to improve the user experience (they would get an error from the provider instead of the parameter binder not helping them understand why it didn't work) and defer any potential breaking change.

**Review by iSazonov — APPROVED** [review]

File: src/System.Management.Automation/engine/SessionStateContainer.cs (hunk 1 above)
Comment (PaulHigin) [reply src/System.Management.Automation/engine/SessionStateContainer.cs:4684]: This is reasonable.  Can you create an issue to track it?

**Review by PaulHigin — APPROVED** [review]
