### PR TITLE
Dynamically evaluate width of LastWriteTime for formatting output on Unix

### LINKED ISSUE #19723: LastWriteTime column width on Linux is set too narrow to support all cultures
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The output of `Get-ChildItem` is fairly garbled due to `LastWriteTime` by default being broken to multiple lines when using locales that serialize dates to longer strings than the `en-US` localization. On an Ubuntu install where `LANG = hu_HU.UTF-8` one sees this:
```pwsh
PS /home/mate> gci                                                                                                      
    Directory: /home/mate                                         

UnixMode   User             Group                 LastWriteTime           Size Name
--------   ----             -----                 -------------           ---- ----
drwxr-xr-x mate             mate             2023. 06. 01. 01:2           4096 Asztal
                                                              7
drwxr-xr-x mate             mate             2023. 06. 01. 01:2           4096 Dokumentumok
                                                              7
drwxr-xr-x mate             mate             2023. 06. 01. 01:2           4096 Képek
                                                              7
drwxr-xr-x mate             mate             2023. 06. 01. 01:2           4096 Letöltések
                                                              7
drwxr-xr-x mate             mate             2023. 06. 01. 01:2           4096 Nyilvános
                                                              7
drwxr-xr-x mate             mate             2023. 06. 01. 01:2           4096 Sablonok
                                                              7
drwx------ mate             mate             2023. 05. 31. 21:5           4096 snap
                                                              5
drwxr-xr-x mate             mate             2023. 06. 01. 01:2           4096 Videók
                                                              7
drwxr-xr-x mate             mate             2023. 06. 01. 01:2           4096 Zenék
                                                              7

PS /home/mate> function Set-CultureWin([System.Globalization.CultureInfo] $culture) { [System.Threading.Thread]::CurrentThread.CurrentUICulture = $culture ; [System.Threading.Thread]::CurrentThread.CurrentCulture = $culture } ; Set-CultureWin en-US ; [system.threading.thread]::currentthread.currentculture

LCID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States)

PS /home/mate> gci                                                                                                      
    Directory: /home/mate                                         

UnixMode   User             Group                 LastWriteTime           Size Name
--------   ----             -----                 -------------           ---- ----
drwxr-xr-x mate             mate                 6/1/2023 01:27           4096 Asztal
drwxr-xr-x mate             mate                 6/1/2023 01:27           4096 Dokumentumok
drwxr-xr-x mate             mate                 6/1/2023 01:27           4096 Képek
drwxr-xr-x mate             mate                 6/1/2023 01:27           4096 Letöltések
drwxr-xr-x mate             mate                 6/1/2023 01:27           4096 Nyilvános
drwxr-xr-x mate             mate                 6/1/2023 01:27           4096 Sablonok
drwx------ mate             mate                5/31/2023 21:55           4096 snap
drwxr-xr-x mate             mate                 6/1/2023 01:27           4096 Videók
drwxr-xr-x mate             mate                 6/1/2023 01:27           4096 Zenék
```

### Expected behavior

```console
PS /home/mate> gci                                                                                                      
    Directory: /home/mate                                         

UnixMode   User             Group                 LastWriteTime           Size Name
--------   ----             -----                 -------------           ---- ----
drwxr-xr-x mate             mate            2023. 06. 01. 01:27           4096 Asztal
drwxr-xr-x mate             mate            2023. 06. 01. 01:27           4096 Dokumentumok
drwxr-xr-x mate             mate            2023. 06. 01. 01:27           4096 Képek
drwxr-xr-x mate             mate            2023. 06. 01. 01:27           4096 Letöltések
drwxr-xr-x mate             mate            2023. 06. 01. 01:27           4096 Nyilvános
drwxr-xr-x mate             mate            2023. 06. 01. 01:27           4096 Sablonok
drwx------ mate             mate            2023. 05. 31. 21:55           4096 snap
drwxr-xr-x mate             mate            2023. 06. 01. 01:27           4096 Videók
drwxr-xr-x mate             mate            2023. 06. 01. 01:27           4096 Zenék
```

### Actual behavior

```console
PS /home/mate> gci                                                                                                      
    Directory: /home/mate                                         

UnixMode   User             Group                 LastWriteTime           Size Name
--------   ----             -----                 -------------           ---- ----
drwxr-xr-x mate             mate             2023. 06. 01. 01:2           4096 Asztal
                                                              7
drwxr-xr-x mate             mate             2023. 06. 01. 01:2           4096 Dokumentumok
                                                              7
drwxr-xr-x mate             mate             2023. 06. 01. 01:2           4096 Képek
                                                              7
drwxr-xr-x mate             mate             2023. 06. 01. 01:2           4096 Letöltések
                                                              7
drwxr-xr-x mate             mate             2023. 06. 01. 01:2           4096 Nyilvános
                                                              7
drwxr-xr-x mate             mate             2023. 06. 01. 01:2           4096 Sablonok
                                                              7
drwx------ mate             mate             2023. 05. 31. 21:5           4096 snap
                                                              5
drwxr-xr-x mate             mate             2023. 06. 01. 01:2           4096 Videók
                                                              7
drwxr-xr-x mate             mate             2023. 06. 01. 01:2           4096 Zenék
                                                              7
```

### Error details

_No response_

### Environment data

```powershell
S /home/mate> $PSVersionTable 

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Linux 5.19.0-21-generic #21-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct 12 18:33:17 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by MathiasMagnus**
# PR Summary

Fixes #19723 

As per @iSazonov 's request, here is a screenshot of some output freom before and after the PR in en-US and a few trickier locales, including the motivating hu-HU locale. The table width visibly adapts to the time format length.

image

## PR Context

The issue which was unresolved has since been aggravated by another PR #18183. This PR adds the required characters to the LastWriteTime column to make it render correctly on all locales.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
  - [x] None
  - **OR**
  - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
    - [ ] Experimental feature name(s): 
- **User-facing changes**
  - [x] Not Applicable
  - **OR**
  - [] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
  - [x] N/A or can only be tested interactively
  - **OR**
  - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
  - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
  - **OR**
  - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
    - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
      - [ ] Issue filed: 
    - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
      - [ ] Issue filed: 
    - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
      - [ ] Issue filed: 
    - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
      - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/FileSystem_format_ps1xml.cs [hunk 1]
```diff
@@ -48,7 +48,11 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_FileSystemTypes(CustomC
                     .AddHeader(Alignment.Left, label: "UnixMode", width: 10)
                     .AddHeader(Alignment.Right, label: "User", width: 10)
                     .AddHeader(Alignment.Left, label: "Group", width: 10)
-                    .AddHeader(Alignment.Right, label: "LastWriteTime", width: 16)
+                    // Until LastWriteTime prints as '{0:d} {0:HH}:{0:mm}', it will always be local date + 6 wide.
+                    // Widest locales for date serialization are hr-HR, hu-HU, bg-BG (13 & 14).
+                    // width as a constant should not be less than 20
+                    // https://github.com/PowerShell/PowerShell/issues/19723
+                    .AddHeader(Alignment.Right, label: "LastWriteTime", width: 20)
```
Comment (iSazonov) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/FileSystem_format_ps1xml.cs:55]: This fix 23 languages and breaks (add extra spaces) over 750 languages. I think this is unacceptable.
Perhaps we could take the format of the current culture and calculate its size dynamically.

Comment (MathiasMagnus) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/FileSystem_format_ps1xml.cs]: Is this more along the lines of what you were thinking?

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/FileSystem_format_ps1xml.cs [hunk 2]
```diff
@@ -48,7 +49,9 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_FileSystemTypes(CustomC
                     .AddHeader(Alignment.Left, label: "UnixMode", width: 10)
                     .AddHeader(Alignment.Right, label: "User", width: 10)
                     .AddHeader(Alignment.Left, label: "Group", width: 10)
-                    .AddHeader(Alignment.Right, label: "LastWriteTime", width: 16)
+                    // Until LastWriteTime prints as '{0:d} {0:HH}:{0:mm}', it will always be local date + 6 wide.
+                    // https://github.com/PowerShell/PowerShell/issues/19723
+                    .AddHeader(Alignment.Right, label: "LastWriteTime", width: CultureInfo.CurrentCulture.DateTimeFormat.ShortDatePattern.Length + 6)
```
Comment (iSazonov) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/FileSystem_format_ps1xml.cs]: Is this works for all cultures?

Full list unique formats you can get with:
```powershell
(Get-Culture -ListAvailable).DateTimeFormat.ShortDatePattern | Sort -Unique
```

Comment (MathiasMagnus) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/FileSystem_format_ps1xml.cs]: I'm having trouble building the project as it is. I opened it in the provided container, installed the suggested extensions, rebased my work on latest master, set PS as the default project, run the build task, and it fails to compile.

```
VERBOSE: Using default feeds which are Microsoft, use -UseNuGetOrg to switch to Public feeds
VERBOSE: In Find-DotNet
VERBOSE: Executing:  dotnet --list-sdks 
VERBOSE: Find-DotNet: dotnetCLIInstalledVersion = 10.0.100-rc.1.25451.107; chosenDotNetVersion = 10.0.100-rc.1.25451.107
VERBOSE: Using configuration 'Debug'
VERBOSE: Using framework 'net10.0'
VERBOSE: Using runtime 'linux-x64'
VERBOSE: Top project directory is /PowerShell/src/powershell-unix
VERBOSE: Building without shim
Run dotnet publish /property:GenerateFullPaths=true /property:ErrorOnDuplicatePublishOutputFiles=false --output /PowerShell/debug --self-contained /property:IsWindows=false /property:AppDeployment=SelfContained --configuration Debug --framework net10.0 --runtime linux-x64 /property:SDKToUse=Microsoft.NET.Sdk from /PowerShell/src/powershell-unix
  PSVersionInfoGenerator succeeded (1.4s) → /PowerShell/src/System.Management.Automation/SourceGenerators/PSVersionInfoGenerator/bin/Debug/netstandard2.0/SMA.Generator.dll
  System.Management.Automation failed with 57 error(s) (17.3s)
    /PowerShell/src/System.Management.Automation/engine/hostifaces/HostUtilities.cs(100,70): error CS0117: 'SuggestionStrings' does not contain a definition for 'Suggestion_CommandExistsInCurrentDirectory_Legacy'
    /PowerShell/src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs(6241,47): error CS0117: 'TabCompletionStrings' does not contain a definition for 'RequiresModulesParameterDescription'
    /PowerShell/src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs(6242,49): error CS0117: 'TabCompletionStrings' does not contain a definition for 'RequiresPSEditionParameterDescription'
    /PowerShell/src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs(6243,58): error CS0117: 'TabCompletionStrings' does not contain a definition for 'RequiresRunAsAdministratorParameterDescription'
```

I don't really know how to fix this.

Comment (iSazonov) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/FileSystem_format_ps1xml.cs]: Start-PSBuild -ResGen

Comment (MathiasMagnus) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/FileSystem_format_ps1xml.cs]: I have done extensive testing for all locales, not just those with the latin alphabet. I have managed to all non-Arabic locales, which is an improvement, albeit not a complete solution. Arabic locales are currently broken on Unix even without this change, so if nothing else, it doesn't make things worse.

The current strategy of trying to devise the width of the table statically is kind-of backwards. Trying to relate the `ShortDatePattern` (The `{0:d}` part of the format string) to the resulting string seems kind-of underwhelming too, because a lot of locales have singular day and month designators/specifiers, which results in shorter anticipated date lengths than the actual ones, even if a single entry in a folder was last written on a day or month with double digits. Some locales even incorporate the era name in their `ShortDatePattern` which make things even more complicated.

I tested using this PS script:

```pwsh
(Get-Culture -ListAvailable) | % { if ([String]::Format( $_, '{0:d} {0:HH}:{0:mm}', (Get-Date)).Length -gt ($_.DateTimeFormat.ShortDatePattern.Length + (($_.DateTimeFormat.ShortDatePattern.ToCharArray() | where {$_ -eq 'd'}).count -eq 1 ? 1 : 0 ) + (($_.DateTimeFormat.ShortDatePattern.ToCharArray() | where {$_ -eq 'M'}).count -eq 1 ? 1 : 0 ) + (($_.DateTimeFormat.ShortDatePattern.ToCharArray() | where {$_ -eq 'g'}).count -eq 1 ? ($_.DateTimeFormat.GetEraName("1").Length + 1) : 0) + 6)) { Write-Host $_.Name 'has pattern:' $_.DateTimeFormat.ShortDatePattern } }
```

which is the PS port of the C# logic found in the PR. Only Arabic locales fall short in terms of the calculated column widths. The remaining issue must lie with right justification/alignment, but I can't figure out why the output is garbled the way it is.

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/FileSystem_format_ps1xml.cs [hunk 3]
```diff
@@ -49,9 +49,20 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_FileSystemTypes(CustomC
...
                     // https://github.com/PowerShell/PowerShell/issues/19723
-                    .AddHeader(Alignment.Right, label: "LastWriteTime", width: CultureInfo.CurrentCulture.DateTimeFormat.ShortDatePattern.Length + 6)
+                    .AddHeader(
+                        Alignment.Right,
+                        label: "LastWriteTime",
+                        width: CultureInfo.CurrentCulture.DateTimeFormat.ShortDatePattern.Length +
+                            (CultureInfo.CurrentCulture.DateTimeFormat.ShortDatePattern.AsSpan().Count('d') == 1 ? 1 : 0) +
+                            (CultureInfo.CurrentCulture.DateTimeFormat.ShortDatePattern.AsSpan().Count('M') == 1 ? 1 : 0) +
+                            (CultureInfo.CurrentCulture.DateTimeFormat.ShortDatePattern.AsSpan().Count('g') == 1 ? 1 + CultureInfo.CurrentCulture.DateTimeFormat.GetEraName(1).Length : 0) +
+                            6)
```
Comment (iSazonov) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/FileSystem_format_ps1xml.cs]: Hmm, why not test real value? I mean evaluate something like `Datetime.Utc.ToString().Length`.

Comment (MathiasMagnus) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/FileSystem_format_ps1xml.cs]: @iSazonov Indeed, that gave a good idea. Utc has seconds at the end, it's length is not fixed... BUT, all I really needed was the longest possible time string formatted as `{0:d} {0:HH}:{0:mm}` in the current locale. Enter `Calendar.MaxSupportedDateTime` 🎆. It is guaranteed to have as many year, month, day, hour and minutes digits as possible.

**Comment by iSazonov** [comment]
@MathiasMagnus LGTM. Please add screenshots in the PR description for hu_HU.UTF-8 (and maybe some other cultures) before and after the PR.

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
@MathiasMagnus Thank for your contribution and patience!
