### PR TITLE
Fix `ConciseView` to handle custom `ParserError` ErrorRecords

### LINKED ISSUE #19223: Convertfrom-cipolicy cmdlet error isn't being displayed on the console in PowerShell 7.3.3
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

[SupplementalPolicy.zip](https://github.com/PowerShell/PowerShell/files/10831509/SupplementalPolicy.zip)

Download the SupplementalPolicy.zip file I uploaded, it has a WDAC supplemental policy (.XML file) that has a wrong rule in it. If I run the command below in PowerShell 7.3.3, I don't see any errors and the cmdlet just silently doesn't create the `.cip` file.

```PowerShell
ConvertFrom-CIPolicy .\SupplementalPolicy.xml '{C791D8CB-14C4-4D01-B858-C671C3995287}.cip'
```

But If I run the same command in Windows PowerShell 5.1, it successfully shows me the error message and tells me what's wrong with the XML file.

I upload the XML file myself because explaining how to create it needs a whole blog post.

### Expected behavior

```console
This error should be shown on the console:


ConvertFrom-CIPolicy : Only base policies can have SupplementalSigners.
At line:1 char:1
+ ConvertFrom-CIPolicy .\SupplementalPolicy.xml '{C791D8CB-14C4-4D01-B8 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (Microsoft.Secur...CIPolicyCommand:ConvertFromCIPolicyCommand) [ConvertFrom
   -CIPolicy], CIPolicyException
    + FullyQualifiedErrorId : InvalidPolicyFile,Microsoft.SecureBoot.UserConfig.ConvertFromCIPolicyCommand
```

### Actual behavior

```console
No error is shown on the console
```

### Error details

_No response_

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.25300
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

image

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

The fundamental issue is that `ConciseView` has code to handle PowerShell `ParserError` category, but the cmdlet in the issue was returning an ErrorRecord with that category (which is allowed), but the `ConciseView` script was only expecting an object that looked like what PowerShell would return. See the comment thread https://github.com/PowerShell/PowerShell/pull/19239#discussion_r1119467127 for some more details.

During execution of this script during formatting, what you get an a `ParseException` is actually an `ErrorRecord` where the `Exception` is a `ParentContainsErrorRecordException`.  So the way to check it's a parse error from PowerShell is to check that the `Category` is `ParseError` and the `Exception` type is `ParentContainsErrorRecordException`.   Not ideal, but the `ParseException` seems to be created somewhere else that gets put onto `$Error` but not available to the script during formatting.

Also added a trap at the start of that script in case there are other unknown issues so that users will get an error message that can be reported to us rather than no error.

Note that the actual issue, however, only repros over remoting which does it's own wrapping of remote errors so a PS Job is used for the test to cover this case.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/19223

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs [hunk 1]
```diff
@@ -1106,7 +1108,7 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_System_Management_Autom
                                         $prefix = ''
 
                                         # Don't show line information if script module
-                                        if (($myinv -and $myinv.ScriptName -or $myinv.ScriptLineNumber -gt 1 -or $err.CategoryInfo.Category -eq 'ParserError') -and !($myinv.ScriptName.EndsWith('.psm1', [System.StringComparison]::OrdinalIgnoreCase))) {
+                                        if (($myinv -and $myinv.ScriptName -or $myinv.ScriptLineNumber -gt 1 -or $err.Type -is [System.Management.Automation.ParseException]) -and !($myinv.ScriptName -and $myinv.ScriptName.EndsWith('.psm1', [System.StringComparison]::OrdinalIgnoreCase))) {
```
Comment (daxian-dbw) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1111]: Does `$err` has a `Type` property?

Comment (daxian-dbw) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1111]: > !($myinv.ScriptName -and $myinv.ScriptName.EndsWith('.psm1', [System.StringComparison]::OrdinalIgnoreCase))

Maybe use `!($myinv.ScriptName?.EndsWith('.psm1', [System.StringComparison]::OrdinalIgnoreCase))` instead?

Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1111]: It seems that `-is` will simply return `$false` if the member doesn't exist

Comment (daxian-dbw) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1111]: Then how this will cover the original `$err.CategoryInfo.Category -eq 'ParserError'` check?

Also, can you please add comment about when there will be a `Type` member to `$err`, and what type `$err` will be in that case?

Comment (daxian-dbw) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1111]: Or, change it to `$myinv.ScriptName -notlike *.psm1`? The `-notlike` use case-insensitive check.

Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs]: This was changed to use `-match`

Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs]: This was changed quite a bit as when inside the script during formatting, the error instance is NOT a ParseException, but instead an ErrorRecord that contains a ParentContainsErrorRecordException.  So the change here is to check for that since you can't actually get the ParseException while inside this script.

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs [hunk 2]
```diff
@@ -1296,7 +1297,7 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_System_Management_Autom
 
                                     $posmsg = ''
                                     if ($ErrorView -eq 'ConciseView') {
-                                        $posmsg = Get-ConciseViewPositionMessage
+                                        $posmsg = Get-ConciseViewPositionMessage -Err $_
```
Comment (daxian-dbw) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1300]: You should pass in `$err` instead to keep the original behavior.
I'd prefer to not changing this. `$myinv` used in `Get-ConciseViewPositionMessage` also comes from the parent scope, so just continue to read both `$err` and `$myinv` from the parent scope.

Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1300]: That's fair.  Let me revert this change to keep it minimal.

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs [hunk 3]
```diff
@@ -1087,7 +1089,7 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_System_Management_Autom
                                         $accentColor = $PSStyle.Formatting.ErrorAccent
                                     }
 
-                                    function Get-ConciseViewPositionMessage {
+                                    function Get-ConciseViewPositionMessage() {
```
Comment (daxian-dbw) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1092]:
```suggestion
                                    function Get-ConciseViewPositionMessage {
```

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs [hunk 4]
```diff
@@ -1105,10 +1107,12 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_System_Management_Autom
                                         $message = ''
                                         $prefix = ''
 
-                                        # Don't show line information if script module
-                                        if (($myinv -and $myinv.ScriptName -or $myinv.ScriptLineNumber -gt 1 -or $err.CategoryInfo.Category -eq 'ParserError') -and !($myinv.ScriptName.EndsWith('.psm1', [System.StringComparison]::OrdinalIgnoreCase))) {
+                                        # The checks here determine if we show line detailed error information:
+                                        # - check if `ParserError` and comes from PowerShell which eventually results in a ParseException, but during this execution it's an ErrorRecord
```
Comment (daxian-dbw) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1111]: It's not a "ParseException" probably because of the following code before calling `Get-ConciseViewPositionMessage`.
A `ParserException` will fall in this if block, which will set `$err` to be the `ParserException.ErrorRecord` member.

https://github.com/PowerShell/PowerShell/blob/476af582d56b25913d1ff9dc8057e1a484f814a9/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs#L1278-L1281

You may want to re-evaluate if you need to do something about the remote error in the above if block instead.

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs [hunk 5]
```diff
@@ -1105,10 +1107,12 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_System_Management_Autom
...
+                                        # - check if invocation is a script or multiple lines in the console
+                                        # - check that it's not a script module as expectation is that users don't want to see the line of error within a module
+                                        if (((($err.CategoryInfo.Category -eq 'ParserError' -and $err.Exception -is 'System.Management.Automation.ParentContainsErrorRecordException') -or $myinv.ScriptName -or $myinv.ScriptLineNumber -gt 1)) -and !($myinv.ScriptName -match '\.psm1$')) {
```
Comment (daxian-dbw) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1114]: It looks like you add one extra pair of parentheses.
```suggestion
                                        if ((($err.CategoryInfo.Category -eq 'ParserError' -and $err.Exception -is 'System.Management.Automation.ParentContainsErrorRecordException') -or $myinv.ScriptName -or $myinv.ScriptLineNumber -gt 1) -and !($myinv.ScriptName -match '\.psm1$')) {
```

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs [hunk 6]
```diff
@@ -1105,10 +1107,12 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_System_Management_Autom
                                         $message = ''
                                         $prefix = ''
 
-                                        # Don't show line information if script module
-                                        if (($myinv -and $myinv.ScriptName -or $myinv.ScriptLineNumber -gt 1 -or $err.CategoryInfo.Category -eq 'ParserError') -and !($myinv.ScriptName.EndsWith('.psm1', [System.StringComparison]::OrdinalIgnoreCase))) {
```
Comment (daxian-dbw) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1109]: I'm not sure I understand what the root cause of the referenced issue is. Can you please explain the bold part of the following statement from the PR description?

> but the cmdlet in the issue was returning an ErrorRecord with that category (which is allowed), but **the ConciseView script was only expecting an object that looked like what PowerShell would return**.

Essentially, you make the 'parser-error' check more restricted by adding the `$err.Exception` check in addition to the `Category` check (it's an `-and`). So, does that mean for the issue https://github.com/PowerShell/PowerShell/issues/19223, the remote error is rendered with line detailed information when it shouldn't?

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs [hunk 7]
```diff
@@ -1105,10 +1107,12 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_System_Management_Autom
...
+                                        # The checks here determine if we show line detailed error information:
+                                        # - check if `ParserError` and comes from PowerShell which eventually results in a ParseException, but during this execution it's an ErrorRecord
+                                        # - check if invocation is a script or multiple lines in the console
+                                        # - check that it's not a script module as expectation is that users don't want to see the line of error within a module
+                                        if (((($err.CategoryInfo.Category -eq 'ParserError' -and $err.Exception -is 'System.Management.Automation.ParentContainsErrorRecordException') -or $myinv.ScriptName -or $myinv.ScriptLineNumber -gt 1)) -and !($myinv.ScriptName -match '\.psm1$')) {
                                             $useTargetObject = $false
-
```
Comment (daxian-dbw) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1111]: IMO, it's better to keep this new line as it makes it easier to read the scripts in this if block -- it gives a clear start of the following if block instead of making it a big chunk of code.

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs (hunk 4 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1111]: This is why during the investigation I passed the original `$_` to the function instead of the reassigned `$err` and even stepping in the debugger, it wasn't a `ParseException`.

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs (hunk 6 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1109]: In the original issue, the cmdlet was setting the `Category` to `ParserError` (which is perfectly allowed), so then the formatting would just see this and expect it to be a PowerShell parser error and thus the known members to be available.  Since it wasn't a PowerShell parser error, it was hitting a null ref exception due to trying to use a member that doesn't exist.  Since within the time of execution of the script during formatting, we don't have a `ParseException` (see above), the proposed fix was to add an additional check of the type of exception.  The remoting aspect seems to due to how it re-wraps the error and then the expected members aren't available, but when explicitly setting `Category` to `ParserError` locally, it works fine.

Comment (daxian-dbw) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1109]: Thanks! This is much clearer!

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs [hunk 8]
```diff
@@ -1105,8 +1107,11 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_System_Management_Autom
...
 
-                                        # Don't show line information if script module
-                                        if (($myinv -and $myinv.ScriptName -or $myinv.ScriptLineNumber -gt 1 -or $err.CategoryInfo.Category -eq 'ParserError') -and !($myinv.ScriptName.EndsWith('.psm1', [System.StringComparison]::OrdinalIgnoreCase))) {
+                                        # The checks here determine if we show line detailed error information:
+                                        # - check if `ParserError` and comes from PowerShell which eventually results in a ParseException, but during this execution it's an ErrorRecord
+                                        # - check if invocation is a script or multiple lines in the console
+                                        # - check that it's not a script module as expectation is that users don't want to see the line of error within a module
+                                        if ((($err.CategoryInfo.Category -eq 'ParserError' -and $err.Exception -is 'System.Management.Automation.ParentContainsErrorRecordException') -or $myinv.ScriptName -or $myinv.ScriptLineNumber -gt 1) -and !($myinv.ScriptName -match '\.psm1$')) {
```
Comment (daxian-dbw) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1114]:
```suggestion
                                        if ((($err.CategoryInfo.Category -eq 'ParserError' -and $err.Exception -is 'System.Management.Automation.ParentContainsErrorRecordException') -or $myinv.ScriptName -or $myinv.ScriptLineNumber -gt 1) -and $myinv.ScriptName -notmatch '\.psm1$') {
```

**Review by daxian-dbw — APPROVED** [review]
LGTM. Just a minor suggestion to reduce a pair of parentheses.
