### PR TITLE
Fix deadlock when piping to shell associated file extension

### LINKED ISSUE #19876: PSNativeCommandPreserveBytePipe hangs on piping to python scripts in Windows
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm trying out the preview feature PSNativeCommandPreserveBytePipe, and it seems to work in most cases but I've noticed it hangs when piping to Python scripts in certain situations. I have both Python 3.9.7 and 3.11.0 installed and the standard python launcher. I have some simple python scripts:

repr.py, which should print the escaped binary contents of stdin:
```
import sys
print(repr(sys.stdin.buffer.read()).lstrip('b'))
```
echo.py, which just prints it's arguments:
```
import sys
print(' '.join(sys.argv[1:]))
```
I also have cat.exe and echo.exe binaries from Cygwin 64-bit as well as WSL2 (Ubuntu).

The following commands hang with PSNativeCommandPreserveBytePipe enabled, until hitting Ctrl+C:
```
.\echo.py hello | .\repr.py
echo.exe hello | .\repr.py
wsl echo hello | .\repr.py
'hello' | cat.exe | .\repr.py
'hello' | wsl cat | .\repr.py
[byte[]](1, 2, 3) | cat.exe | .\repr.py
[byte[]](1, 2, 3) | wsl cat | .\repr.py
```

However, if I prefix the repr.py script with `python.exe` or `py.exe` (the python launcher) they work as expected:
```
> .\echo.py hello | py .\repr.py
'hello\r\n'
> [byte[]](1, 2, 3) | cat.exe | python .\repr.py
'\x01\x02\x03'
```
Also piping strings or bytes directly from Powershell to the un-prefixed script works:
```
> 'hello' | .\repr.py
'hello\r\n'
> [byte[]](1, 2, 3) | .\repr.py
'\x01\x02\x03'
```
So it seems that this only effects native-to-native commands involving the Python launcher launched implicitly via file association as the target of the pipe. I haven't tried using other scripting languages to see if it effects other implicitly launched binaries. I confirmed that this effects both Python 3.9 and 3.11.

Also `assoc` and `ftype` show the .py file association as:
```
> cmd /c assoc .py
.py=Python.File
> cmd /c ftype Python.File
Python.File="C:\WINDOWS\py.exe" "%L" %*
```

### Expected behavior

```console
The expected behavior for the first 5 hanging commands is to print `'hello\r\n'`, and the last 2 to print `'\x01\x02\x03'`.
```

### Actual behavior

```console
The commands hang and nothing happens until I hit Ctrl+C, which stops the command with no output.

Running the commands with PSNativeCommandPreserveBytePipe disabled does not hang and shows the legacy behavior (bytes are passed as line-separated strings).
```

### Error details

_No response_

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.4
PSEdition                      Core
GitCommitId                    7.4.0-preview.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by SeeminglyScience**
Fixes #19876

# PR Summary

Marking the process as initialized was done inside a `try` that can be part of normal operation if `shell32!FindExecutableW` finds a valid console subsystem executable. This change moves it after the try so that scenario will be caught as well.

~~Also reduced some allocations in `IsExecutable`. That change is separated into it's own commit for easier review, but I'm also fine with reverting that commit if desired.~~

I don't think there's an non-interactive way to set a file extension these days so I'm not sure how this could be tested. If you know of a way (that doesn't use undocumented APIs) please comment.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by iSazonov** [comment]
> I don't think there's an non-interactive way to set a file extension these days so I'm not sure how this could be tested. If you know of a way (that doesn't use undocumented APIs) please comment.

Search `cmd /c assoc` in our tests for examples.

File: src/System.Management.Automation/engine/NativeCommandProcessor.cs [hunk 1]
```diff
@@ -1700,28 +1701,30 @@ private void CalculateIORedirection(bool isWindowsApplication, out bool redirect
...
-            {
-                extensionList = new string[] { ".exe", ".com", ".bat", ".cmd" };
-            }
-            else
-            {
-                extensionList = pathext.Split(';');
-            }
+            ReadOnlySpan<char> extensionList = string.IsNullOrEmpty(pathext)
+                ? ".exe;.com;.bat;.cmd"
+                : pathext;
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/NativeCommandProcessor.cs:1716]: I guess nobody change default Windows value of the `PATHEXT`. Today it is `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL`. So we could use statics like:
```c#
const string PATHEXT_DEFAULT = ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL";
private static string[] _pathextDefault = new string[] { ".COM",".EXE",".BAT",".CMD",".VBS",".VBE",".JS",".JSE",".WSF",".WSH",".MSC",".CPL" }
string pathext = Environment.GetEnvironmentVariable("PATHEXT");
if (PATHEXT_DEFAULT  == pathext)
{}
else
{}

File: src/System.Management.Automation/engine/NativeCommandProcessor.cs [hunk 2]
```diff
@@ -1700,28 +1701,30 @@ private void CalculateIORedirection(bool isWindowsApplication, out bool redirect
...
+
+            int extensionCount = extensionList.Count(';') + 1;
+            Span<Range> extensions = extensionCount < 0x20
+                ? (stackalloc Range[0x20]).Slice(0, extensionCount)
+                : new Range[extensionCount];
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/NativeCommandProcessor.cs:1721]: Please use named constatnt for 0x20 like `const int MaxStackBuffer = 256;`

(And if you care about performance/best code generation you could use const stack alloc buffer explicitly.)

File: src/System.Management.Automation/engine/NativeCommandProcessor.cs [hunk 3]
```diff
@@ -1700,28 +1701,30 @@ private void CalculateIORedirection(bool isWindowsApplication, out bool redirect
...
 
-            foreach (string extension in extensionList)
+            extensions.Clear();
+            extensions = extensions.Slice(0, extensionList.Split(extensions, ';'));
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/NativeCommandProcessor.cs:1724]: Do we really need the Clear(). I thing .Net does this for us.

File: src/System.Management.Automation/engine/NativeCommandProcessor.cs (hunk 2 above)
Comment (SeeminglyScience) [reply src/System.Management.Automation/engine/NativeCommandProcessor.cs:1721]: > (And if you care about performance/best code generation you could use const stack alloc buffer explicitly.)

I'm just going to revert that change as it's unrelated and don't want it to hold up the PR.

That said, can you give an example of what you mean here? I am using a fixed sized stackalloc buffer. If you mean use stackalloc and never use an array, we can't be sure that's reasonable given we're getting user input in the form of a environment variable

File: src/System.Management.Automation/engine/NativeCommandProcessor.cs (hunk 3 above)
Comment (SeeminglyScience) [reply src/System.Management.Automation/engine/NativeCommandProcessor.cs]: I did actually mean to remove the `.Clear()` here because I think `Split` will be writing in a way where it doesn't matter if the stack buffer is zeroed.

That said, it's worth noting that I included it due to adding the `SkipLocalsInit` decoration. It's a common recommendation when using stack allocated buffers because .NET's default zeroing of stack allocated memory is very slow according to the .NET folks.

**Comment by SeeminglyScience** [comment]
> > I don't think there's an non-interactive way to set a file extension these days so I'm not sure how this could be tested. If you know of a way (that doesn't use undocumented APIs) please comment.
> 
> Search `cmd /c assoc` in our tests for examples.

Hmm does that work outside of CI? I wasn't able to get `assoc` to do anything meaningful on Windows 11. Maybe that still works in nano/Windows Server.

Thanks I'll look into it

File: src/System.Management.Automation/engine/NativeCommandProcessor.cs (hunk 2 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/NativeCommandProcessor.cs]: > That said, can you give an example of what you mean here?

If I remember correctly Roslyn optimizes  stackalloc with const size moving stack allocation before function call. If the stackalloc is under condition the optimization doesn't work and Roslyn has to generate more complex dynamic code for stack allocation and deallocation.
```c#
var arr = stackalloc string[256];
if (we_need > 256)
{
    arr = new string[we_need];
}
else
{
    arr = arr.Slice(we_need);
}

Comment (SeeminglyScience) [reply src/System.Management.Automation/engine/NativeCommandProcessor.cs]: > If I remember correctly Roslyn optimizes stackalloc with const size moving stack allocation before function call. If the stackalloc is under condition the optimization doesn't work and Roslyn has to generate more complex dynamic code for stack allocation and deallocation.

Ah alright then we're thinking of the same thing. It's doing `stackalloc char[something.Length]` that's bad. You want to allocate the max you're willing to and then just slice it afterwards. That's what my code did before I reverted.

The array part doesn't matter, it's just variable sized `stackalloc` that has a large perf hit

**Comment by SeeminglyScience** [comment]
> > > I don't think there's an non-interactive way to set a file extension these days so I'm not sure how this could be tested. If you know of a way (that doesn't use undocumented APIs) please comment.
> > 
> > 
> > Search `cmd /c assoc` in our tests for examples.
> 
> Hmm does that work outside of CI? I wasn't able to get `assoc` to do anything meaningful on Windows 11. Maybe that still works in nano/Windows Server.
> 
> Thanks I'll look into it

So even if `assoc` works in CI, it doesn't actually test what I'm fixing here. The deadlock only occurred once `kernel32!CreateProcess` has already failed and we then call `shell32!FindExecutable` to get the shell association. But if `assoc` works, then `kernel32!CreateProcess` will work, and the deadlock wouldn't get hit anyway.

File: src/System.Management.Automation/engine/NativeCommandProcessor.cs [hunk 4]
```diff
@@ -695,6 +682,12 @@ private void InitNativeProcess()
                         }
 #endif
                     }
+
+                    if (UpstreamIsNativeCommand)
+                    {
+                        _processInitialized ??= new SemaphoreSlim(0, 1);
+                        _processInitialized.Release();
+                    }
```
Comment (SeeminglyScience) [inline src/System.Management.Automation/engine/NativeCommandProcessor.cs:690]: btw I removed the lock because we're already in a lock for that object and I just didn't notice (line 596)

**Comment by iSazonov** [comment]
> > > > I don't think there's an non-interactive way to set a file extension these days so I'm not sure how this could be tested. If you know of a way (that doesn't use undocumented APIs) please comment.
> > > 
> > > 
> > > Search `cmd /c assoc` in our tests for examples.
> > 
> > 
> > Hmm does that work outside of CI? I wasn't able to get `assoc` to do anything meaningful on Windows 11. Maybe that still works in nano/Windows Server.
> > Thanks I'll look into it
> 
> So even if `assoc` works in CI, it doesn't actually test what I'm fixing here. The deadlock only occurred once `kernel32!CreateProcess` has already failed and we then call `shell32!FindExecutable` to get the shell association. But if `assoc` works, then `kernel32!CreateProcess` will work, and the deadlock wouldn't get hit anyway.

Interesting.... if it is possible to reproduce the issue with Python can we emulate the same behavior with cmd.exe and .bat and use this in tests?

**Comment by SeeminglyScience** [comment]
> Interesting.... if it is possible to reproduce the issue with Python can we emulate the same behavior with cmd.exe and .bat and use this in tests?

`.bat` just straight up works as if it were an executable file, handling for that is hard coded. Even if it wasn't though, the shell (explorer) already has an association for `.bat` so in theory that would work anyway.

The main issue is that in recent history it's been made explicitly unsupported to set shell associations outside of the UI. I've heard of some ways, but it involves reverse engineered formats that change between Windows versions? Something like that, but either way not something we'd want to use in a test.

**Review by daxian-dbw — APPROVED** [review]
LGTM

**Comment by rmccampbell** [comment]
Hi, do you know if there is going to be a preview and/or release build with this fix any time soon?
