### PR TITLE
Ensure -PipelineVariable is set for all output from script cmdlets

### LINKED ISSUE #10932: -PipelineVariable is only assigned output from the first execution of the first function block
# Steps to reproduce

```powershell
function foo {
  [cmdletbinding()]
  Param([parameter(ValueFromPipeline)]$a)
  Begin   {1}
  Process {2}
  End     {3}
}
Write-Host -ForegroundColor Green 'Expected:'
1..3|foo|%{$_} -pv x -ov y |select {$x},{$_},{$y}|out-host

Write-Host -ForegroundColor Green 'Actual:'
1..3|foo       -pv x -ov y |select {$x},{$_},{$y}|out-host
```

Output:

```
Expected:

$x $_            $y
-- --            --
 1  1             1
 2  2        {1, 2}
 2  2     {1, 2, 2}
 2  2  {1, 2, 2, 2}
 3  3 {1, 2, 2, 2…}

Actual:

$x $_            $y
-- --            --
 1  1             1
    2        {1, 2}
    2     {1, 2, 2}
    2  {1, 2, 2, 2}
    3 {1, 2, 2, 2…}
```

# Expected behavior

All output produced in any block (Begin, Process, or End) should be assigned to the PipelineVariable as it enters the pipeline. -OutVariable appears to behave correctly, i.e. it captures output that -PipelineVariable does not.

# Actual behavior

Only output produced by the first block to exectute, and only on the first execution of that block is assigned to the PipelineVariable.

Examples: 

* if a Begin block exists, the output from the Begin block will be assigned, but the output from the Process and End blocks will not.
* if a Begin block does not exists, the output from the first execution of the Process block will be assigned, but the output from subsequent executions of the Process block will not, and the output of the End block will not.

In the wild, on 5.1:

https://stackoverflow.com/questions/45782372/powershell-advanced-function-output-pipelinevariable-doesnt-work

https://www.reddit.com/r/PowerShell/comments/doboko/support_for_pipelinevariable_in_advanced_function/

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by vexx32**
# PR Summary

Previously, -PipelineVariable was only set for the first occurence of output from a script cmdlet. This change borrows some code from the handling for compiled commands to ensure -PipelineVariable is always set correctly and should behave as expected even for script cmdlets.

## PR Context

This PR resolves #10932, see this issue for further discussion.

We _will_ need to document the bugged behaviour for downlevel versions of PowerShell in docs so that users are aware. Most folks probably won't have noticed it, but people may still run into it from time to time on downlevel versions.

@SteveL-MSFT I'm not 100% sure, but this feels like the kind of fix y'all might want in a servicing release for 7.0. 🙂 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by vexx32** [comment]
Codefactor issue is an existing issue in this test file in an area I've not touched; not going to mess with that for now. 🙂

File: src/System.Management.Automation/engine/MshCommandRuntime.cs [hunk 1]
```diff
@@ -3740,6 +3740,13 @@ internal void SetVariableListsInPipe()
```
Comment (PoshChan) [inline src/System.Management.Automation/engine/MshCommandRuntime.cs:3740]: @vexx32, your last commit had 1 failures in `PowerShell-CI-linux`
Parameter Binding Tests.PipelineVariable shouldn't cause a NullRef exception when 'DynamicParam' block is present
```powershell
Cannot retrieve the dynamic parameters for the cmdlet. Object reference not set to an instance of an object.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1: line 256
256:         DynamicParamTest -PipelineVariable bar | ForEach-Object { $bar } | Should -Be "hi"

```

Comment (PoshChan) [inline src/System.Management.Automation/engine/MshCommandRuntime.cs:3740]: @vexx32, your last commit had 1 failures in `PowerShell-CI-macos`
Parameter Binding Tests.PipelineVariable shouldn't cause a NullRef exception when 'DynamicParam' block is present
```powershell
Cannot retrieve the dynamic parameters for the cmdlet. Object reference not set to an instance of an object.
at <ScriptBlock>, /Users/runner/runners/2.168.2/work/1/s/test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1: line 256
256:         DynamicParamTest -PipelineVariable bar | ForEach-Object { $bar } | Should -Be "hi"

```

Comment (PoshChan) [inline src/System.Management.Automation/engine/MshCommandRuntime.cs:3740]: @vexx32, your last commit had 1 failures in `PowerShell-CI-windows`
Parameter Binding Tests.PipelineVariable shouldn't cause a NullRef exception when 'DynamicParam' block is present
```powershell
Cannot retrieve the dynamic parameters for the cmdlet. Object reference not set to an instance of an object.
at <ScriptBlock>, D:\a\1\s\test\powershell\engine\ParameterBinding\ParameterBinding.Tests.ps1: line 256
256:         DynamicParamTest -PipelineVariable bar | ForEach-Object { $bar } | Should -Be "hi"

```

Comment (vexx32) [reply src/System.Management.Automation/engine/MshCommandRuntime.cs:3740]: That explains where this bug came from. Someone, at some point, tried to fix that issue and ended up introducing the current bug. This will probably get interesting... I'll do some debugging tomorrow.

**Comment by TravisEz13** [comment]
I think this falls into a bucket 3 breaking change and I think we should take the change.
@PowerShell/powershell-committee  Please review

**Review by rjmholt — APPROVED** [review]
This looks good to me

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this, we agree that the previous behavior was broken and falls under bucket 3 as a breaking change, so approve the intended new behavior

File: test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1 [hunk 2]
```diff
@@ -256,6 +256,62 @@ Describe "Parameter Binding Tests" -Tags "CI" {
...
+                param(
+                    [Parameter(ValueFromPipeline)]
+                    $a
+                )
+                begin { 1 }
+                process { 2 }
+                end { 3 }
+            }
+
+            $testScripts = @(
```
Comment (JamesWTruher) [inline test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1:274]: i'm a little concerned that there isn't enough validation. Can you think of additional edges here that we should be poking?

**Review by JamesWTruher — CHANGES_REQUESTED** [review]

File: test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1 (hunk 2 above)
Comment (vexx32) [reply test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1:274]: There are probably numerous odd cases where this might crop up, but I can't think of any that are really different from the test case here. At the very least, this does cover the test case that we know is broken. 

I've not seen any other cases crop up myself, nor had someone drop in the community channels with an issue that came down to this. I suspect that that's more due to `-PipelineVariable` being a bit more of a niche concept from the start, though.

Without knowing for sure about other broken cases, the best I can do is test a few other cases with multiple script cmdlets and various mixes of script / compiled cmdlets to see if the logic breaks down anywhere.

The only real unknown where I don't know what to actually expect is what is meant to happen if multiple cmdlets in the same pipeline declare the same pipeline variable. I'm not sure the expected behaviour there is even recorded anywhere. Best guess - the nearest command to the variable's usage will have its output in there at any given point...

If anyone else has cases they know to be broken / likely to break, I'd appreciate having those as well.

**Comment by TravisEz13** [comment]
@JamesWTruher  can you respond to @vexx32

**Comment by vexx32** [comment]
@JamesWTruher please update your review / let me know if you have additional cases to cover with tests. Thanks! 💖

**Review by JamesWTruher — APPROVED** [review]
we can always add more validation if we find additional cases.

**Comment by vexx32** [comment]
@TravisEz13 is there anything left pending here? 🙂

**Comment by rjmholt** [comment]
Merged this so we can include it in the next preview in order to validate it better
