### PR TITLE
Use dedicated threads to read the redirected output and error streams from the child process for out-of-proc jobs

### LINKED ISSUE #11659: Powershell jobs surprisingly slow...
On about 25% of the laptops in our group, the following command run in a _*new* powershell window_ is surprisingly slow -- 20 to 30 seconds for 10 empty jobs:

PS C:\temp> **(measure-command { 1..10 | %{ start-job { $null } }; get-job | wait-job; get-job | remove-job } ).totalseconds**
21.6354752
PS C:\temp>

Note that if you run the command a second time, it is up to 10x faster.  But if you wait a minute or two and try again, or open a new window and try again, it is slow again.  100% repeatable for systems with the issue (about 75% of the laptops in our group do _not_ have the issue, and I am guessing it is because they have more cores -- I have 4 cores, 16GB RAM, and Samsung EVO SSD.)

I have done a bunch of analysis here, and I am convinced the following happens...  For starters, the parent powershell launches 10 children, one at a time, with maybe a half of a second between each launch.  Then one or two of the children might start running, but most of them just sit there waiting for most of the 20'ish seconds.  Then the remaining 8 or 9 powershells start running at the same intervals as they launched -- like a half second between each run (as if the overall delay time is fixed for each process).  Then all processes complete together.

**Note that the system is idle for 90% of the time, at 0% CPU, while we wait 20 seconds for the empty jobs to complete.**  This is the bug -- an idle system waiting for over 15 seconds doing nothing.

You can see this by changing "$false" above to "c:\xxx.exe" -- then in procmon or xperf, you can see the (failed) references to c:\xxx.exe very close to the end of the trace.

It is possible this is because I have 4 cores in my system:

PS C:\temp> **(get-process -id 0).threads.count**
4
PS C:\temp>

I am richardt@microsoft.com.  I have tons of xperf and procmon traces, and have done a lot of initial digging into this -- it seems to be excess cleverness in the clr threadpool implementation that brings on pathologies in certain CPU configurations...  Please reach out to me before closing this as not repro or not important -- we're now moving away from powershell jobs for all our testing infrastructure (to C#, since if we have to go out-of-box to get powershell to work, it's not worth the risk -- we run our tests in VSO).  I hate to see folks be **unable to use powershell** for something as simple as launching background jobs -- this is 100% something folks should reliably be able to use powershell for!  I hope we can fix this!!!

Below/attached is xperf/wpa trace showing the 10 children processes start up sequentially, and then hang idle for 15 seconds, and then eventually shut down (also somewhat sequentially).

xperfwpa

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #11659
Use dedicated threads to read the redirected output and error streams from the child process for out-of-proc jobs.

## PR Context

Currently, when `Start-Job` starts a child PowerShell process, it depends on the `Process` events `OutputDataReceived` and `ErrorDataReceived` to handle messages from the output and error streams.
Internally, the `Process` implementation uses 2 thread-pool threads to read messages from those 2 streams. Even though the implementation calls `stream.ReadAsync` on those 2 streams, the actual read operation is synchronous because the underlying Win32 API `CreatePipe()` only allows the pipe handle to be created in `"synchronous"` mode.

This results in 2 thread-pool threads being held up indefinitely for each out-of-proc job created. When more out-of-proc jobs are created at the same time, it quickly depletes the thread pool, and causing thread starvation for other tasks that depend on thread-pool threads until the thread pool manager realize it's time to increase the pool.

**Thread-pool threads should be used for transient tasks that finish quickly, not for long-running tasks. In this case, reading from pipe in a blocking manner is obviously a long-running tasks and should be done with dedicated threads.**

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

File: src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs [hunk 1]
```diff
@@ -1123,28 +1123,15 @@ internal override void CreateAsync()
...
-                    }
-
                     _serverProcess.Exited += new EventHandler(OnExited);
-
-                    // serverProcess.Start();
                     _processInstance.Start();
 
-                    if (stdInWriter != null)
+                    stdInWriter = _processInstance.StdInWriter;
+                    if (stdInWriter == null)
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: @PaulHigin do we really need this check? I kept it since it's there today, but it doesn't seem we really need it.

Comment (PaulHigin) [reply src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: I don't know ... I didn't write this code.  It looks like an attempt to protect against CreateAsync() from being called multiple times, or re-using a 'PowerShellProcessInstance' object.  Background jobs don't do this but maybe Workflow jobs did.  Probably not needed.

File: src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs [hunk 2]
```diff
@@ -1172,6 +1159,46 @@ internal override void CreateAsync()
             SendOneItem();
         }
 
+        private void StartOutputAndErrorReaderThreads(Process serverProcess)
+        {
+            ParameterizedThreadStart func = arg => {
```
Comment (PaulHigin) [inline src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: Will this function be allocated for each transport created?  Would it make more sense to create a class method that takes reader argument or enum that defines data type?  I would prefer to avoid tuples if possible.

File: src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs [hunk 3]
```diff
@@ -1172,6 +1159,46 @@ internal override void CreateAsync()
...
+                var tuple = arg as Tuple<StreamReader, bool>;
+                if (tuple == null)
+                {
+                    return;
```
Comment (PaulHigin) [inline src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: Invalid arguments should be checked with Dbg.Assert()?  Should never happen.

**Review by PaulHigin — CHANGES_REQUESTED** [review]

File: src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs (hunk 2 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: This method will be made an instance method of the `OutOfProcTransportManager` by the compiler, but I can make it a separate private class method.

File: src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs (hunk 3 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: I can add Dbg.Assert() here, just in case.

File: src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs (hunk 2 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: Add `ProcessOutputData` and `ProcessErrorData` methods, and both take a `StreamReader` only.

File: src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs (hunk 3 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: Add `Dbg.Assert` to cover the invalid argument.

**Comment by iSazonov** [comment]
- Is ForEach -Parallel affected in a way?
- In original issue many jobs is created. Make sense to have dedicated thread pool for jobs?

**Comment by daxian-dbw** [comment]
> Is ForEach -Parallel affected in a way?

It creates its own thread, so it's not affected.

> In original issue many jobs is created. Make sense to have dedicated thread pool for jobs?

I don't think that's needed. Thread pool threads should only for short living tasks. When it comes to long-living tasks, even a separate dedicated thread pool will have the same starvation problem.

**Comment by PaulHigin** [comment]
Dedicated thread pool for thread jobs is not needed because both ThreadJob and ForEach-Object -Parallel have throttling and queuing, which is basically performs the same function as a thread pool.

File: src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs (hunk 1 above)
Comment (PaulHigin) [inline src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: Actually, after discussion with @daxian-dbw , this null check should not be here, because we need to start our listening threads regardless of whether we create the host process or it is passed in.

File: src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs [hunk 4]
```diff
@@ -1172,6 +1159,54 @@ internal override void CreateAsync()
...
+
+            outputThread.Start(serverProcess.StandardOutput);
+            errorThread.Start(serverProcess.StandardError);
+        }
+
+        private void ProcessOutputData(object arg)
+        {
+            if (arg is StreamReader reader)
+            {
+                string data = reader.ReadLine();
```
Comment (PaulHigin) [inline src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: One concern I have is if the host process exits suddenly.  We want to make sure that any exception the StreamReader throws is caught and reported, so that the client doesn't crash.  Please see SSH and NamedPipe transports.  We may need try/catch, something like:
```
catch (ObjectDisposedException)
            {
                // Normal reader thread end.
            }
            catch (Exception e)
            {
                string errorMsg = (e.Message != null) ? e.Message : string.Empty;
                _tracer.WriteMessage("SSHClientSessionTransportManager", "ProcessErrorThread", Guid.Empty,
                    "Transport manager error thread ended with error: {0}", errorMsg);

                PSRemotingTransportException psrte = new PSRemotingTransportException(
                    StringUtil.Format(RemotingErrorIdStrings.SSHClientEndWithErrorMessage, errorMsg),
                    e);
                HandleSSHError(psrte);
            }
```

**Review by PaulHigin — CHANGES_REQUESTED** [review]

File: src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs (hunk 4 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: `try/catch` was added to the output/error reader threads. Thanks @PaulHigin!

Here we do the same as what `Process.BeginOutputReadLine()` and `Process.BeginErrorReadLine()` do -- treat `IOException` as EOF.

File: src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs (hunk 1 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: The check is removed.

**Review by PaulHigin — APPROVED** [review]
LGTM

File: src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs [hunk 5]
```diff
@@ -1172,6 +1154,80 @@ internal override void CreateAsync()
...
+        private void ProcessOutputData(object arg)
+        {
+            if (arg is StreamReader reader)
+            {
+                try
+                {
+                    string data = reader.ReadLine();
+                    while (data != null)
+                    {
+                        HandleOutputDataReceived(data);
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: Since it runs in separate thread no race condition possible?

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: Race condition with what?

File: src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs [hunk 6]
```diff
@@ -1123,28 +1123,10 @@ internal override void CreateAsync()
                         _processInstance.RunspacePool.Dispose();
```
Comment (PoshChan) [inline src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: @daxian-dbw, your last commit had 1 failures in `PowerShell-CI-macos`
Invoke-WebRequest tests.Denial of service.Image Parsing
```powershell
Expected the actual value to be greater than 5, but got 0.38315472351302.
at <ScriptBlock>, /Users/runner/runners/2.164.6/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1: line 1932
1932:             $pathologicalRatio | Should -BeGreaterThan 5
```

**Comment by daxian-dbw** [comment]
@PoshChan Please retry mac

**Comment by PoshChan** [comment]
@daxian-dbw, I do not understand the build target(s) `mac`; I only allow `static`, `windows`, `macos`, `linux`, `all`

**Comment by daxian-dbw** [comment]
@PoshChan Please retry macos

**Comment by PoshChan** [comment]
@daxian-dbw, successfully started retry of `PowerShell-CI-macOS`

File: src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs (hunk 5 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: Previously the handler works in one thread for all jobs. Now it is called from different threads. It makes me think about some synchronization

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: > Previously the handler works in one thread for all jobs

That's not true. The handler was registered for each job child powershell process, and now it's the same. The different is only previously it was using a background thread, now it's using a dedicated thread.

**Review by iSazonov — APPROVED** [review]

**Comment by daxian-dbw** [comment]
Turns out the failure in Windows build is a real issue that needs to be looked into. I will investigate and report back.

**Comment by iSazonov** [comment]
@daxian-dbw Could you please address CI Windows fail?

**Comment by PaulHigin** [comment]
@daxian-dbw 
I think the issue may be in handling expected errors that reflect various ways listener loop can end.  You can see example code for the NamedPipe and SSH transports.

**Comment by daxian-dbw** [comment]
Thanks @PaulHigin for the pointers!
I was busy with some other work with higher priority. Will get back to this soon.

**Comment by iSazonov** [comment]
Is the PR ready to merge?

**Comment by daxian-dbw** [comment]
All tests passed now 😄
It turns out I forgot to remove the following two lines from `KillServerProcess()`:
```c#
_serverProcess.CancelOutputRead();
_serverProcess.CancelErrorRead();
```
They should be called only if we are actively using the `OutputDataReceived` and `ErrorDataReceived` events to asynchronously read the redirected output and error. Otherwise, they will throw exception which [got swollen silently](https://github.com/PowerShell/PowerShell/pull/11713/commits/b6b446a9a3895ea292837019d3914cb70d722127#diff-62032daf278902e44b9c801a37a8ec81R1299) by `KillServerProcess()` (by design), and thus the line [`_serverProcess.Kill()`](https://github.com/PowerShell/PowerShell/pull/11713/commits/b6b446a9a3895ea292837019d3914cb70d722127#diff-62032daf278902e44b9c801a37a8ec81R1280) will never be executed, which causes the child process started by `Start-Job` lingers around forever.

The issue results in 34 child pwsh processes not cleaned up after the jobs finish, which eat up the memory in the Windows CI environment. That's why we see the `stack overflow` and out-of-memory error thrown from CoreCLR (`Failed to create CoreCLR, HRESULT: 0x8007000E`).

**Review by PaulHigin — CHANGES_REQUESTED** [review]
Can we add a test to ensure the child process is cleaned up on background job completion?  Or whatever the scenario is that invokes KillServerProcess()?

**Comment by daxian-dbw** [comment]
Sure, I will add a test to verify the server process is terminated after the job is gone.

**Comment by daxian-dbw** [comment]
@PaulHigin, tests are added to verify that the background process is cleaned up after job is gone. Please review it when you have time. Thanks!

File: test/powershell/engine/Job/Jobs.Tests.ps1 [hunk 7]
```diff
@@ -338,4 +338,48 @@ Describe 'Basic Job Tests' -Tags 'Feature' {
...
         }
     }
+
+    Context 'Background pwsh process should terminate after job is done' {
+        It "Can clean up background pwsh process after job is done" {
+            $job = Start-Job { $pid }
+            $processId = Receive-Job $job -Wait
+
+            # The job is done, wait 2 seconds for the cleanup to finish.
+            Start-Sleep -Seconds 2
```
Comment (PaulHigin) [inline test/powershell/engine/Job/Jobs.Tests.ps1]: Sorry to be nit picky, but you could use the HelpersCommon module 'Wait-UntilTrue' here and loop until Get-Process returns $null.  The tests would probably run quite a bit faster than always waiting 2 seconds.

**Review by PaulHigin — CHANGES_REQUESTED** [review]

File: test/powershell/engine/Job/Jobs.Tests.ps1 (hunk 7 above)
Comment (daxian-dbw) [reply test/powershell/engine/Job/Jobs.Tests.ps1]: Sure, I will make the change.

File: src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs [hunk 8]
```diff
@@ -1098,7 +1098,6 @@ internal override void CreateAsync()
                 {
```
Comment (PoshChan) [inline src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: @daxian-dbw, your last commit had 3 failures in `PowerShell-CI-windows`
Basic Job Tests.Background pwsh process should terminate after job is done.Can clean up background pwsh process after job is done
```powershell
Expected an exception, with FullyQualifiedErrorId 'NoProcessFoundForGivenId,Microsoft.PowerShell.Commands.GetProcessCommand' to be thrown, but no exception was thrown.
at <ScriptBlock>, D:\a\1\s\test\powershell\engine\Job\Jobs.Tests.ps1: line 349
349:             { Get-Process -Id $processId -ErrorAction Stop } | Should -Throw `
```
Basic Job Tests.Background pwsh process should terminate after job is done.Can clean up background pwsh process when job is stopped
```powershell
Expected an exception, with FullyQualifiedErrorId 'NoProcessFoundForGivenId,Microsoft.PowerShell.Commands.GetProcessCommand' to be thrown, but no exception was thrown.
at <ScriptBlock>, D:\a\1\s\test\powershell\engine\Job\Jobs.Tests.ps1: line 365
365:             { Get-Process -Id $processId -ErrorAction Stop } | Should -Throw `
```
Basic Job Tests.Background pwsh process should terminate after job is done.Can clean up background pwsh process when job is removed
```powershell
Expected an exception, with FullyQualifiedErrorId 'NoProcessFoundForGivenId,Microsoft.PowerShell.Commands.GetProcessCommand' to be thrown, but no exception was thrown.
at <ScriptBlock>, D:\a\1\s\test\powershell\engine\Job\Jobs.Tests.ps1: line 381
381:             { Get-Process -Id $processId -ErrorAction Stop } | Should -Throw `
```

Comment (PoshChan) [inline src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: @daxian-dbw, your last commit had 3 failures in `PowerShell-CI-windows`
Basic Job Tests.Background pwsh process should terminate after job is done.Can clean up background pwsh process after job is done
```powershell
Expected $true, but got $false.
at <ScriptBlock>, D:\a\1\s\test\powershell\engine\Job\Jobs.Tests.ps1: line 350
350:             } -IntervalInMilliseconds 300 | Should -BeTrue
```
Basic Job Tests.Background pwsh process should terminate after job is done.Can clean up background pwsh process when job is stopped
```powershell
Expected $true, but got $false.
at <ScriptBlock>, D:\a\1\s\test\powershell\engine\Job\Jobs.Tests.ps1: line 370
370:             } -IntervalInMilliseconds 300 | Should -BeTrue
```
Basic Job Tests.Background pwsh process should terminate after job is done.Can clean up background pwsh process when job is removed
```powershell
Expected $true, but got $false.
at <ScriptBlock>, D:\a\1\s\test\powershell\engine\Job\Jobs.Tests.ps1: line 390
390:             } -IntervalInMilliseconds 300 | Should -BeTrue
```

Comment (PoshChan) [inline src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: @daxian-dbw, your last commit had 1 failures in `PowerShell-CI-macos`
Test-Connection.TraceRoute.TraceRoute works
```powershell
Expected exactly '10.79.0.117', but got 127.0.0.1.
at <ScriptBlock>, /Users/runner/runners/2.165.2/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1: line 257
257:             $result[0].TargetAddress | Should -BeExactly $realAddress
```

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: Not sure why it takes that long for the process to be gone on Windows CI ... Will look into the failures.
But good thing is that all other job tests are passing without the scary out-of-memory error :)

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: This is an intermittent failure that start to happen after moving macOS to the latest version.

**Review by PaulHigin — APPROVED** [review]

File: src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs (hunk 8 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs]: It turns out on Windows, the process object can still linger around after the process exists, so `Get-Process -Id $processId` may return a dead process. I will update the tests.

**Comment by daxian-dbw** [comment]
@iSazonov I think this is now ready to merge. But please take another look before you do so as there are changes after your last review.

**Review by iSazonov — APPROVED** [review]
