### PR TITLE
Fix `New-Item -Force` to error on invalid directory name

### LINKED ISSUE #21111: New-Item -Force does not throw an error
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The code below should throw an error, but does not in PowerShell 7.

```ps
New-Item C:\invalid? -Type Directory -Force -ErrorAction Stop
```

It correctly throws an error in PowerShell 5.

### Expected behavior

```console
PS C:\> New-Item C:\invalid? -Type Directory -Force
New-Item : Illegal characters in path.
At line:1 char:1
+ New-Item C:\invalid? -Type Directory -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (C:\invalid?:String) [New-Item], ArgumentException
    + FullyQualifiedErrorId : CreateDirectoryArgumentError,Microsoft.PowerShell.Commands.NewItemCommand
```

### Actual behavior

```console
PS C:\> New-Item C:\invalid? -Type Directory -Force
PS C:\>
```

### Error details

_No response_

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by kborowinski**
# PR Summary

Fix #21111

@SteveL-MSFT @iSazonov 

This PR ensures that `New-Item -Path 'Invalid?' -Force` correctly throws an error instead of being suppressed. The change specifically checks for `IOException` with the `HResult` code related to invalid characters and allows the exception to propagate, aligning behavior with PowerShell 5.1.

## PR Context

The `PowerShell Working Group` discussed this issue and agreed that, in the case of invalid characters, the cmdlet should return an error just like in PowerShell 5.1, even when `-Force` is used. The primary use case of `-Force` is to ensure success whether the target directory exists, but suppressing invalid character errors introduces inconsistencies. This PR implements a targeted fix by checking for the specific `HResult` associated with invalid characters, ensuring that such exceptions are not suppressed while maintaining existing behavior for other cases.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
  - [] None
  - **OR**
  - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
    - [ ] Experimental feature name(s): 
- **User-facing changes**
  - [ ] Not Applicable
  - **OR**
  - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
  - [ ] N/A or can only be tested interactively
  - **OR**
  - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
  - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
  - **OR**
  - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
    - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
      - [ ] Issue filed: 
    - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
      - [ ] Issue filed: 
    - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
      - [ ] Issue filed: 
    - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
      - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 1]
```diff
@@ -62,6 +62,9 @@ public sealed partial class FileSystemProvider : NavigationCmdletProvider,
 
         private const int COPY_FILE_ACTIVITY_ID = 0;
         private const int REMOVE_FILE_ACTIVITY_ID = 0;
+        
+        // Windows error code for invalid characters
+        private const int ERROR_INVALID_NAME = unchecked((int)0x8007007B);
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:67]: What about Linux and MacOS?

File: test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1 [hunk 2]
```diff
@@ -386,3 +386,13 @@ Describe "New-Item -Force allows to create an item even if the directories in th
         $FullyQualifiedFile | Should -Exist
     }
 }
+
+Describe "New-Item -Force should throw an error for invalid characters in directory path" -Tags "CI" {
+    BeforeAll {
+        $invalidPath = Join-Path -Path $TestDrive -ChildPath 'Invalid?'
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1:392]: The test should work on Linux and MacOS too.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 1 above)
Comment (kborowinski) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:67]: Unfortunately, I have limited knowledge about Linux or macOS. From what I have read, the only invalid character for directory name on Linux is `/` (forward slash). I did try force an exception on Ubuntu with `New-Item -Path Invalid/folder/name' -Type Directory`, and it does not error but instead creates a folder structure. What I can do is not suppress `IOException` when on Windows.

File: test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1 (hunk 2 above)
Comment (kborowinski) [reply test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1:392]: As mentioned before, I was not able to force invalid directory name error on Ubuntu, therefore I just propose to skip that test when running on Linux or macOS.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 1 above)
Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:67]: @mklement0 What do you think about non-Windows OS-s? Do you agree that the fix should be only for Windows?

File: test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1 (hunk 2 above)
Comment (mklement0) [reply test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1:392]: I think it's fine to limit the tests to Windows. The only way to construct an invalid directory path that I'm aware of on Unix-like platforms is to include `NUL` (`` `0 ``) characters, but there's a dedicated check for that already in place (`Null character in path.`)

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 1 above)
Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:67]: Since we don't use `RuntimeInformation.IsOSPlatform()` in the file, we prefer to wrap code with `#if UNIX`. So I suggest to move the const to code where it is used and use the directive.

**Review by iSazonov — APPROVED** [review]
