### PR TITLE
Fixing CA2014 warnings, and removing suppressions

### LINKED ISSUE #13531: Fix CA2014: Stackalloc in loops
We currently suppress warnings of [CA2014](https://docs.microsoft.com/visualstudio/code-quality/ca2014) in parts of the build. `stackalloc`s in loops can cause stack overflows, so we need to refactor our code to fix this.

See:

https://github.com/PowerShell/PowerShell/blob/78d0d0e3065d946a1f17cc97cf29b94c12ce9c9f/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs#L2579

https://github.com/PowerShell/PowerShell/blob/78d0d0e3065d946a1f17cc97cf29b94c12ce9c9f/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L308

https://github.com/PowerShell/PowerShell/blob/78d0d0e3065d946a1f17cc97cf29b94c12ce9c9f/src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs#L787-L788

Suppression added in https://github.com/PowerShell/PowerShell/pull/13530

### PR DESCRIPTION
**Pull request by creative-cloud**
# PR Summary
Fixes #13531 - No longer allocating memory in loops. Removed related suppress warnings.

Moved out the stackalloc statements for 2/3 cases, and removed the loop entirely for the other.

## PR Context
Copying context over from the issue - 

> We currently suppress warnings of [CA2014](https://docs.microsoft.com/visualstudio/code-quality/ca2014) in parts of the build. stackallocs in loops can cause stack overflows, so we need to refactor our code to fix this.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: https://github.com/PowerShell/PowerShell/issues/13531 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs [hunk 1]
```diff
@@ -2565,6 +2565,9 @@ internal static void WriteConsole(ConsoleHandle consoleHandle, ReadOnlySpan<char
             // We need to chop the output string if it is too long.
             int cursor = 0; // This records the chopping position in output string
             const int MaxBufferSize = 16383; // this is 64K/4 - 1 to account for possible width of each character.
+            var endOfLine = Environment.NewLine.AsSpan();
+            var endOfLineLength = endOfLine.Length;
+            Span<char> outBufferLine = stackalloc char[(output.Length % MaxBufferSize) + endOfLineLength];
```
Comment (iSazonov) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs:2570]: This change doesn't make sense.
Only value I see if we would allocate const size buffer, with small size (512 chars), and  slice it as needed if newline.

Comment (creative-cloud) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs:2570]: > This change doesn't make sense.

Why do you say so?
We would be allocating the same amount of space (as on line 2590), just pre-calculated, and outside the loop.

I'm not sure I fully understand your proposition of using a small buffer that can be sliced.
Can you elaborate on what would we store in said buffer, and how the slicing would come into play?

Comment (iSazonov) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs:2570]: Original code is not ideal but it does not allocate if no newline. It was a compromise.

---
Best practice for stackalloc is (1) allocate as small (<1Kb) buffer as possible (I think we could use 512 char buffer to cover hot scenarios), (2) allocate fixed size so that compiler can optimize (I think newline scenarios is hot and we can always allocate the stack buffer).

So I suggest you think in this direction.

Comment (creative-cloud) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs]: Refactored to remove the if-else block in the while loop.

This solution keeps the current implementation, but moves the base case outside the loop.
I think this work for our goal of removing stackalloc from within the loop.  
@iSazonov, let me know what your thoughts are.

**Comment by creative-cloud** [comment]
Pinging the original reviewers, to get a few more eyes on the PR.
@anmenaga @adityapatwardhan @daxian-dbw

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs [hunk 2]
```diff
@@ -2565,39 +2565,30 @@ internal static void WriteConsole(ConsoleHandle consoleHandle, ReadOnlySpan<char
...
-                    else
-                    {
-                        WriteConsole(consoleHandle, outBuffer);
-                    }
-                }
+            if (newLine)
+            {
+                var endOfLine = Environment.NewLine.AsSpan();
+                var endOfLineLength = endOfLine.Length;
+                Span<char> outBufferLine = stackalloc char[outBuffer.Length + endOfLineLength];
```
Comment (iSazonov) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs:2584]: Here we could allocate ~16KB (MaxBufferSize) in stack. That it is not good. I suggest to output the tail before the condition if the tail >= MaxStackAlloc ( MaxStackAlloc = 512).

Comment (creative-cloud) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs:2584]: @iSazonov 
I think what you are suggesting is that we should further split the `outBuffer` into 2 pieces -> MaxBufferSize - 512b and 512b, such that the span that is stacalloc'ed is 512 bytes.
(assuming that the size of the `outBuffer` is `MaxBufferSize`, in the worst case)

The first MaxBufferSize - 512b piece will need additional memory. This will also end up going on the stack since we are using spans. This route does not seem any better than allocating the entire MaxBufferSize.

Also, this will mean that we would now need to make two `WriteConsole` calls to finish writing the contents of the outBuffer, rather than 1. 
I don't think the memory allocation issue is significant enough to justify adding the perf of a whole other IO operation.

Let me know if I understood that right.

Comment (iSazonov) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs:2584]: I mean:
```c#
        internal static void WriteConsole(ConsoleHandle consoleHandle, ReadOnlySpan<char> output, bool newLine)
        {
            Dbg.Assert(!consoleHandle.IsInvalid, "ConsoleHandle is not valid");
            Dbg.Assert(!consoleHandle.IsClosed, "ConsoleHandle is closed");

            const char MaxStackAlloc = 512;
            Span<char> buffer = stackalloc char[MaxStackAlloc];
            ReadOnlySpan<char> outBuffer;

            // Native WriteConsole doesn't support output buffer longer than 64K.
            // We need to chop the output string if it is too long.
            // This records the chopping position in output string
            int cursor = 0;

            // this is 64K/4 - 1 to account for possible width of each character.
            const int MaxBufferSize = 16383;

            while (cursor <= output.Length - MaxBufferSize)
            {
                outBuffer = output.Slice(cursor, MaxBufferSize);
                cursor += MaxBufferSize;

                WriteConsole(consoleHandle, outBuffer);
            }

            if (cursor == output.Length)
            {
                if (newLine)
                {
                    WriteConsole(consoleHandle, Environment.NewLine);
                }

                return;
            }

            outBuffer = output.Slice(cursor);

            if (!newLine)
            {
                WriteConsole(consoleHandle, outBuffer);

                return;
            }

            if (outBuffer.Length < MaxStackAlloc - 1)
            {
                // We expect it is a hot path.
                var endOfLine = Environment.NewLine.AsSpan();
                var endOfLineLength = endOfLine.Length;
                buffer = buffer.Slice(0, outBuffer.Length + endOfLineLength);            }

                outBuffer.CopyTo(buffer);
                endOfLine.CopyTo(buffer.Slice(buffer.Length - endOfLineLength));

                WriteConsole(consoleHandle, buffer);
            }
            else
            {
                WriteConsole(consoleHandle, outBuffer);

                WriteConsole(consoleHandle, Environment.NewLine);
            }
        }
```

Comment (iSazonov) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs:2584]: Up.

**Review by daxian-dbw — APPROVED** [review]
LGTM

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs (hunk 2 above)
Comment (daxian-dbw) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs:2583]: @iSazonov I understand your concern here. But the `while (cursor + MaxBufferSize < output.Length)` comes from the existing `if (cursor + MaxBufferSize < output.Length)`, so it's not a problem introduced by this cleanup change. So, I'm fine merging this PR as is, and submit a new PR to address your concern.

Comment (iSazonov) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs:2583]: @daxian-dbw Agree.

**Comment by iSazonov** [comment]
@creative-cloud Thanks for your contribution!
