### PR TITLE
Port GetProcessorArchitecture()

### LINKED ISSUE #4474: GetProcessorArchitecture in PSUtil.cs is not ported
[GetProcessorArchitecture](https://github.com/PowerShell/PowerShell/blob/f0eda031d616760fd723c1db464ecd0585de5f27/src/System.Management.Automation/utils/PsUtils.cs#L536) uses Windows native API to detect a processor architecture.

This method is used in `ModuleCmdletBase.cs` to [test the required process architecture](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs#L1867), and thus that code is broken on Unix platforms as GetProcessorArchitecture depends on a win32 API to get process architecture.

We should use CoreFX API `[System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture`.

### LINKED ISSUE #6533: Module manifest .psd1 file on linux/mac doesn't support ProcessorArchitecture='AMD64' or 'x86'
Steps to reproduce
------------------

On Linux/Mac:
Open any module .psd1 file and update/ add the following line:
ProcessorArchitecture = 'Amd64'
OR
ProcessorArchitecture ='x86'

Please note: ProcessorArchitecture='None' seems to work.

Expected behavior
-----------------
The module should be discoverable using Get-Module -ListAvailable and Import-Module should work fine as it does on Windows.

Actual behavior
---------------

The module is not listed using Get-Module and Import-Module fails with this error:
```
Import-Module : Unable to load DLL 'api-ms-win-core-sysinfo-l1-1-0.dll': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
At line:1 char:1
+ Import-Module Standard
+ ~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Import-Module], DllNotFoundException
+ FullyQualifiedErrorId : System.DllNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand
```
Environment data
----------------

```powershell
> $PSVersionTable

```

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Fix #4474
Fix  #6533

Before the change GetProcessorArchitecture() call Windows P/Invoke so on Unix it would throw if user loaded a module with ProcessorArchitecture value in the module manifest. Now we use ProcessorArchitecture from current assembly.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

File: src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs [hunk 1]
```diff
@@ -1837,23 +1837,16 @@ private IEnumerable<PSModuleInfo> CreateFakeModuleObject(IEnumerable<ModuleSpeci
             else if ((requiredProcessorArchitecture != ProcessorArchitecture.None) &&
```
Comment (PoshChan) [inline src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs]: @iSazonov, your last commit had 1 failures in `PowerShell-CI-static-analysis`
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/powershell-beginners-guide.md.https://www.computerperformance.co.uk/powershell/index.htm should work
```powershell
retry of URL failed with error: Resource temporarily unavailable
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 117
117:                                     throw "retry of URL failed with error: $($_.Exception.Message)"

```

**Review by adityapatwardhan — APPROVED** [review]

**Comment by iSazonov** [comment]
@SteveL-MSFT Do you agree to merge the PR before GA?

**Comment by iSazonov** [comment]
@adityapatwardhan Please review the PR again.

After looking in depth how the method is used I very wonder that we implement the conversion of these two enums if we can request current value from an assembly using Reflection.

File: src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs [hunk 2]
```diff
@@ -1837,23 +1837,16 @@ private IEnumerable<PSModuleInfo> CreateFakeModuleObject(IEnumerable<ModuleSpeci
...
                      (requiredProcessorArchitecture != ProcessorArchitecture.MSIL))
             {
-                bool isRunningOnArm = false;
-                ProcessorArchitecture currentArchitecture = PsUtils.GetProcessorArchitecture(out isRunningOnArm);
+                ProcessorArchitecture currentArchitecture = PsUtils.GetProcessorArchitecture();
 
                 // For ARM Architectures, we need to do additional string-level comparison
```
Comment (alexbuzzbee) [inline src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs]: Is this still true?

Comment (iSazonov) [reply src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs]: Thanks! The comment was removed.

File: src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs [hunk 3]
```diff
@@ -1837,23 +1837,15 @@ private IEnumerable<PSModuleInfo> CreateFakeModuleObject(IEnumerable<ModuleSpeci
             else if ((requiredProcessorArchitecture != ProcessorArchitecture.None) &&
```
Comment (PoshChan) [inline src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs]: @iSazonov, your last commit had 20 failures in `PowerShell-CI-static-analysis`
(These are 5 of the failures)

Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/powershell-beginners-guide.md.https://docs.microsoft.com/powershell/scripting/core-powershell/running-remote-commands should work
```powershell
retry of URL failed with error: Response status code does not indicate success: 404 (Not Found).
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 117
117:                                     throw "retry of URL failed with error: $($_.Exception.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/README.md.https://docs.microsoft.com/powershell/scripting/setup/installing-powershell-core-on-linux?view=powershell-6 should work
```powershell
retry of URL failed with error: Response status code does not indicate success: 404 (Not Found).
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 117
117:                                     throw "retry of URL failed with error: $($_.Exception.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/README.md.https://docs.microsoft.com/powershell/scripting/setup/installing-powershell-core-on-macos?view=powershell-6 should work
```powershell
retry of URL failed with error: Response status code does not indicate success: 404 (Not Found).
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 117
117:                                     throw "retry of URL failed with error: $($_.Exception.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/learning-powershell/README.md.https://docs.microsoft.com/powershell/scripting/setup/installing-powershell-core-on-windows?view=powershell-6 should work
```powershell
retry of URL failed with error: Response status code does not indicate success: 404 (Not Found).
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 117
117:                                     throw "retry of URL failed with error: $($_.Exception.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/README.md.https://docs.microsoft.com/powershell/scripting/setup/installing-powershell-core-on-windows?view=powershell-6 should work
```powershell
retry of URL failed with error: Response status code does not indicate success: 404 (Not Found).
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 117
117:                                     throw "retry of URL failed with error: $($_.Exception.Message)"

```

**Comment by anmenaga** [comment]
@iSazonov , can you please double check that currently `GetProcessorArchitecture()` returns system-wide info and [comment on this function is wrong](https://github.com/PowerShell/PowerShell/blob/78d64664ceda59d4a6918be1842f16da38d68c7d/src/System.Management.Automation/utils/PsUtils.cs#L139)?
If that's the case, then probably to avoid future confusion:
1) current `GetProcessorArchitecture()` should be renamed across the code to something like `GetSystemProcessorArchitecture()`, and comment updated;
2) since the functionality of getting current process arch is also needed, code of this PR should go into `PsUtils` as a separate method like `GetCurrentProcessProcessorArchitecture()`.

**Comment by iSazonov** [comment]
@anmenaga If the name confuses you we could remove the method at all because it is used in one place/scenario. Th scenario is a module loading. We read ProcessorArchitecture parameter from the module manifest and check that we can load the module. The check is to compare the ProcessorArchitecture parameter and ProcessorArchitecture property from current assembly. And we can do this directly. I pulled the commit.

File: src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs (hunk 3 above)
Comment (PoshChan) [inline src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs]: @iSazonov, your last commit had 1 failures in `PowerShell-CI-windows`
Enter-PSHostProcess tests.By Process Id.Can enter using NamedPipeConnectionInfo
```powershell
Exception calling "Invoke" with "0" argument(s): "The runspace state is not valid for this operation."
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Core\Enter-PSHostProcess.Tests.ps1: line 136
136:                 $ps.AddScript('$pid').Invoke() | Should -Be $pwshId

```

**Comment by iSazonov** [comment]
@anmenaga Could you please continue?

**Comment by iSazonov** [comment]
@SteveL-MSFT @anmenaga I think the PR could be in 7.0.

**Comment by SteveL-MSFT** [comment]
@iSazonov can you add a test to cover https://github.com/PowerShell/PowerShell/issues/6533?

**Comment by iSazonov** [comment]
@SteveL-MSFT Sorry, I did not saw the issue. New tests are added.

File: src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs (hunk 3 above)
Comment (PoshChan) [inline src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs]: @iSazonov, your last commit had 2 failures in `PowerShell-CI-linux`
New-ModuleManifest tests.New-ModuleManifest works with assembly architecture: X86
```powershell
Cannot add type. Compilation errors occurred.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/engine/Module/NewModuleManifest.Tests.ps1: line 173
173:         Add-Type -TypeDefinition $a -CompilerOptions "/platform:$roslynArch" -OutputAssembly $assemblyPath

```
New-ModuleManifest tests.New-ModuleManifest works with assembly architecture: Amd64
```powershell
Cannot add type. Compilation errors occurred.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/engine/Module/NewModuleManifest.Tests.ps1: line 173
173:         Add-Type -TypeDefinition $a -CompilerOptions "/platform:$roslynArch" -OutputAssembly $assemblyPath

```

Comment (PoshChan) [inline src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs]: @iSazonov, your last commit had 2 failures in `PowerShell-CI-macos`
New-ModuleManifest tests.New-ModuleManifest works with assembly architecture: X86
```powershell
Cannot add type. Compilation errors occurred.
at <ScriptBlock>, /Users/runner/runners/2.163.1/work/1/s/test/powershell/engine/Module/NewModuleManifest.Tests.ps1: line 173
173:         Add-Type -TypeDefinition $a -CompilerOptions "/platform:$roslynArch" -OutputAssembly $assemblyPath

```
New-ModuleManifest tests.New-ModuleManifest works with assembly architecture: Amd64
```powershell
Cannot add type. Compilation errors occurred.
at <ScriptBlock>, /Users/runner/runners/2.163.1/work/1/s/test/powershell/engine/Module/NewModuleManifest.Tests.ps1: line 173
173:         Add-Type -TypeDefinition $a -CompilerOptions "/platform:$roslynArch" -OutputAssembly $assemblyPath

```

Comment (PoshChan) [inline src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs]: @iSazonov, your last commit had 1 failures in `PowerShell-CI-linux`
New-ModuleManifest tests.New-ModuleManifest works with assembly architecture: Amd64
```powershell
Cannot add type. Compilation errors occurred.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/engine/Module/NewModuleManifest.Tests.ps1: line 173
173:         Add-Type -TypeDefinition $a -CompilerOptions "/platform:$roslynArch" -OutputAssembly $assemblyPath

```

Comment (PoshChan) [inline src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs]: @iSazonov, your last commit had 1 failures in `PowerShell-CI-macos`
New-ModuleManifest tests.New-ModuleManifest works with assembly architecture: Amd64
```powershell
Cannot add type. Compilation errors occurred.
at <ScriptBlock>, /Users/runner/runners/2.163.1/work/1/s/test/powershell/engine/Module/NewModuleManifest.Tests.ps1: line 173
173:         Add-Type -TypeDefinition $a -CompilerOptions "/platform:$roslynArch" -OutputAssembly $assemblyPath

```

**Comment by iSazonov** [comment]
@SteveL-MSFT It seems I need help to fix tests on Unix-s. :-( I guess SMA compiled to MSIL on Unix-s. In the case I don't know how make functional tests on Unix-s.

File: test/powershell/engine/Module/NewModuleManifest.Tests.ps1 [hunk 4]
```diff
@@ -116,4 +116,68 @@ Describe "New-ModuleManifest tests" -tags "CI" {
...
+        $modulePath = Join-Path $testFolder "TP_$arch.psd1"
+        Add-Type -TypeDefinition $a -CompilerOptions "/platform:$roslynArch" -OutputAssembly $assemblyPath
+        New-ModuleManifest -Path $modulePath -NestedModules "TP_$arch.dll" -RequiredAssemblies "TP_$arch.dll" -ProcessorArchitecture $arch -CmdletsToExport "Get-TP"
+        Import-Module $modulePath
+
+
+        Get-TP -ErrorAction SilentlyContinue | Should -BeExactly "$arch"
+
+        Remove-Module "TP_$arch"
+        Remove-Item -LiteralPath $testFolder -Recurse -Force -ErrorAction SilentlyContinue > $null
```
Comment (SteveL-MSFT) [inline test/powershell/engine/Module/NewModuleManifest.Tests.ps1]: Should have in `finally` to ensure this cleans up if test fails for some reason

File: test/powershell/engine/Module/NewModuleManifest.Tests.ps1 [hunk 5]
```diff
@@ -116,4 +116,68 @@ Describe "New-ModuleManifest tests" -tags "CI" {
...
+        # We can not unload the module assembly and so we can not use Pester TestDrive without cleanup error reporting
+        $testFolder = Join-Path $([System.IO.Path]::GetTempPath()) $([System.IO.Path]::GetRandomFileName())
+        New-Item -Type Directory -Path $testFolder -Force > $null
+
+        $assemblyPath = Join-Path $testFolder "TP_$arch.dll"
+        $modulePath = Join-Path $testFolder "TP_$arch.psd1"
+        Add-Type -TypeDefinition $a -CompilerOptions "/platform:$roslynArch" -OutputAssembly $assemblyPath
+        New-ModuleManifest -Path $modulePath -NestedModules "TP_$arch.dll" -RequiredAssemblies "TP_$arch.dll" -ProcessorArchitecture $arch -CmdletsToExport "Get-TP"
+        Import-Module $modulePath
+
```
Comment (SteveL-MSFT) [inline test/powershell/engine/Module/NewModuleManifest.Tests.ps1]: Extra whitespace

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]

**Comment by SteveL-MSFT** [comment]
@iSazonov You can probably not even worry about Add-Type, the module manifest issue was at validation time when it is imported so you can just generate the module manifest with ProcessorArchitecture and it should succeed on compatible arch and fail on not-compatible arch

File: src/System.Management.Automation/utils/PsUtils.cs [hunk 6]
```diff
@@ -135,41 +133,6 @@ internal static Process GetParentProcess(Process current)
...
-                case NativeMethods.PROCESSOR_ARCHITECTURE_AMD64:
-                    result = ProcessorArchitecture.Amd64;
-                    break;
-                case NativeMethods.PROCESSOR_ARCHITECTURE_INTEL:
-                    result = ProcessorArchitecture.X86;
-                    break;
-                case NativeMethods.PROCESSOR_ARCHITECTURE_ARM:
-                    result = ProcessorArchitecture.None;
-                    isRunningOnArm = true;
-                    break;
```
Comment (daxian-dbw) [inline src/System.Management.Automation/utils/PsUtils.cs]: Can you please clean up the native method, struct and const values that are no longer needed?

File: test/powershell/engine/Module/NewModuleManifest.Tests.ps1 (hunk 4 above)
Comment (iSazonov) [reply test/powershell/engine/Module/NewModuleManifest.Tests.ps1]: Done.

File: test/powershell/engine/Module/NewModuleManifest.Tests.ps1 (hunk 5 above)
Comment (iSazonov) [reply test/powershell/engine/Module/NewModuleManifest.Tests.ps1]: Done.

File: src/System.Management.Automation/utils/PsUtils.cs (hunk 6 above)
Comment (iSazonov) [reply src/System.Management.Automation/utils/PsUtils.cs]: Done.

**Comment by iSazonov** [comment]
@SteveL-MSFT I try to create _functional_ tests to ensure that scenario like #6533 really works. But test failures show that _perhaps_ the PR doesn't fix #6533 in general (the PR only removes broken p/invoke but do not ensure that import-module works) because Roslyn works in another way on Unix-s and probably loader too. Now I set to skip new tests on Unix-s.

**Review by SteveL-MSFT — APPROVED** [review]

**Comment by iSazonov** [comment]
Notice. The code was not covered by tests. Now only Windows on Intel is covered. Unix-s and Arm are not covered.
