### PR TITLE
Fix up SSHConnectionInfo ssh PATH checks

### LINKED ISSUE #15641: Runspace with SSHConnectionInfo is not working on Linux or Windows
## Steps to reproduce

Create a simple program

```C#

using System;
using System.Management.Automation;
using System.Management.Automation.Remoting;
using System.Management.Automation.Runspaces;

namespace util
{
    class Program
    {
        static void Main(string[] args)
        {
            var connectionInfo = new SSHConnectionInfo("username", "machinename", null, port: 22)
            {
            };

            var runspace = RunspaceFactory.CreateRunspace(connectionInfo);
            runspace.Open();

            System.Console.WriteLine("Hit any key to exit...");
            System.Console.ReadKey();
        }
    }
}

```

Try to run:

dotnet run

## Expected behavior

Successful run.

## Actual behavior

```none

PS > dotnet run
Unhandled exception. System.Management.Automation.Remoting.PSRemotingDataStructureException: An error has occurred which PowerShell cannot handle. A remote session might have ended.
 ---> System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Management.Automation.Runspaces.SSHConnectionInfo.CreateProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32 creationFlags, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Management.Automation.Runspaces.SSHConnectionInfo.StartSSHProcess(ProcessStartInfo startInfo, StreamWriter& standardInput, StreamReader& standardOutput, StreamReader& standardError)
   at System.Management.Automation.Runspaces.SSHConnectionInfo.StartSSHProcessImpl(ProcessStartInfo startInfo, StreamWriter& stdInWriterVar, StreamReader& stdOutReaderVar, StreamReader& stdErrReaderVar)
   at System.Management.Automation.Runspaces.SSHConnectionInfo.StartSSHProcess(StreamWriter& stdInWriterVar, StreamReader& stdOutReaderVar, StreamReader& stdErrReaderVar)
   at System.Management.Automation.Remoting.Client.SSHClientSessionTransportManager.CreateAsync()
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl.SendNegotiationAsync(RemoteSessionState sessionState)
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl.HandleStateChanged(Object sender, RemoteSessionStateEventArgs arg)
   at System.Management.Automation.ExtensionMethods.SafeInvoke[T](EventHandler`1 eventHandler, Object sender, T eventArgs)
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerStateMachine.RaiseStateMachineEvents()
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerStateMachine.ProcessEvents()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.Open()
   at System.Management.Automation.Runspaces.RunspacePool.Open()
   at System.Management.Automation.RemoteRunspace.Open()
   at util.Program.Main(String[] args) in /mnt/c/work/util/Program.cs:line 17


```

## Environment data

Linux

```none
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

### LINKED ISSUE #25778: RunspaceFactory.CreateRunspace(SshConnectionInfo) is not working
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [x] Search the existing issues.
- [x] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [x] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This code is not working, can't create sunspace with RunspaceFactory.CreateRunspace(sshConnectionInfo).
this bug already was described and discussed in https://github.com/PowerShell/PowerShell/issues/15641 but without any fix
using System;
using System.Management.Automation;
using System.Management.Automation.Remoting;
using System.Management.Automation.Runspaces;

namespace util
{
    class Program
    {
        static void Main(string[] args)
        {
            var connectionInfo = new SSHConnectionInfo("username", "machinename", null, port: 22)
            {
            };

            var runspace = RunspaceFactory.CreateRunspace(connectionInfo);
            runspace.Open();

            System.Console.WriteLine("Hit any key to exit...");
            System.Console.ReadKey();
        }
    }
}

### Expected behavior

```console
new sunspace created
```

### Actual behavior

```console
Exception
```

### Error details

```console
System.Management.Automation.Remoting.PSRemotingDataStructureException: An error has occurred which PowerShell cannot handle. A remote session might have ended.
 ---> System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Management.Automation.Runspaces.SSHConnectionInfo.CreateProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32 creationFlags, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Management.Automation.Runspaces.SSHConnectionInfo.StartSSHProcess(ProcessStartInfo startInfo, StreamWriter& standardInput, StreamReader& standardOutput, StreamReader& standardError)
   at System.Management.Automation.Runspaces.SSHConnectionInfo.StartSSHProcessImpl(ProcessStartInfo startInfo, StreamWriter& stdInWriterVar, StreamReader& stdOutReaderVar, StreamReader& stdErrReaderVar)
   at System.Management.Automation.Runspaces.SSHConnectionInfo.StartSSHProcess(StreamWriter& stdInWriterVar, StreamReader& stdOutReaderVar, StreamReader& stdErrReaderVar)
   at System.Management.Automation.Remoting.Client.SSHClientSessionTransportManager.CreateAsync()
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl.SendNegotiationAsync(RemoteSessionState sessionState)
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl.HandleStateChanged(Object sender, RemoteSessionStateEventArgs arg)
   at System.Management.Automation.ExtensionMethods.SafeInvoke[T](EventHandler`1 eventHandler, Object sender, T eventArgs)
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerStateMachine.RaiseStateMachineEvents()
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerStateMachine.ProcessEvents()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.Open()
   at System.Management.Automation.Runspaces.RunspacePool.Open()
   at System.Management.Automation.RemoteRunspace.Open()
   at Program.<Main>$(String[] args) in /Users/onovikov/RiderProjects/helloworld/helloworld/Program.cs:line 25
```

### Environment data

```powershell
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.5.2
PSEdition                      Core
GitCommitId                    7.5.2
OS                             Darwin 24.5.0 Darwin Kernel Version 24.5.0: Tue Apr 22 19:52:00 PDT 2025; root:xnu-11417.121.6~2/RELEASE_ARM64_T6031
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by jborean93**
# PR Summary
Fix the logic for finding the ssh executable in the PATH when running in a context without an active Runspace. For example running it in an SDK hosted PowerShell instance will not have an active Runspace when creating the ssh process so cannot use the PowerShell command lookup class.

I'm not sure of a way to effectively test this in CI unfortunately.

## PR Context
Fixes: https://github.com/PowerShell/PowerShell/issues/15641
Fixes: https://github.com/PowerShell/PowerShell/issues/25778

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge. If this PR is a work in progress, please open this as a [Draft Pull Request and mark it as Ready to Review when it is ready to merge](https://docs.github.com/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests).
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
  - [x] None
  - **OR**
  - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
    - [ ] Experimental feature name(s): 
- **User-facing changes**
  - [x] Not Applicable
  - **OR**
  - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [ ] Issue filed: 
- **Testing - New and feature**
  - [x] N/A or can only be tested interactively
  - **OR**
  - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Review by daxian-dbw — APPROVED** [review]
LGTM!

File: src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs [hunk 1]
```diff
@@ -2206,12 +2206,51 @@ internal int StartSSHProcess(
...
                     filePath = cmdInfo.Path;
                 }
             }
+            else
+            {
+                // A Runspace may not be present in the TLS in SDK hosted apps
+                // or if running in another thread without a Runspace. While
+                // ProcessStartInfo can lookup the full path in PATH, we set
+                // the cwd to the parent directory of the found executable so
+                // we do a manual lookup here.
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: I don't see where we _explicitly_ set the cwd. So we could exclude manual lookup and do here simply:
```c#
    filePath = sshCommand;
```

**Review by iSazonov — COMMENTED** [review]
As for new test we could create simple xUnit test based on code from related issue.

File: src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs (hunk 1 above)
Comment (jborean93) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: It is used further down https://github.com/PowerShell/PowerShell/blob/ce76ae1def6d5b00fff0d855ec01575121268ef3/src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs#L2286.

I can optionally set `WorkingDirectory` but I'm unsure if pwsh has set this for security reasons to avoid things like accidentally adding extra libs to the dll/so rpath or something.

**Comment by jborean93** [comment]
> As for new test we could create simple xUnit test based on code from related issue.

I could split out the logic into it's own function and run that but I can't run the reproducer because it'll require an SSH endpoint that is configured with the PowerShell subsystem.

File: src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs (hunk 1 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: Thanks for the clarification! Now it's clear that by `cwd` you mean `WorkingDirectory` property.
If we explicitly set WorkingDirectory in line 2325, then according to the [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.workingdirectory?view=net-9.0), this affects the app search only if UseShellExecute is true but we set it to _false_ in line 2327.

**Comment by iSazonov** [comment]
> > As for new test we could create simple xUnit test based on code from related issue.
> 
> I could split out the logic into it's own function and run that but I can't run the reproducer because it'll require an SSH endpoint that is configured with the PowerShell subsystem.

The endpoint could be easily created in `Start-PSPester` but if MSFT team still hasn't considered it important for testing, then I'm not insisting.

File: src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs [hunk 2]
```diff
@@ -2206,12 +2206,51 @@ internal int StartSSHProcess(
...
             if (context != null)
             {
-                var cmdInfo = context.CommandDiscovery.LookupCommandInfo(sshCommand, CommandOrigin.Internal) as ApplicationInfo;
+                var cmdInfo = CommandDiscovery.LookupCommandInfo(
+                    sshCommand,
+                    CommandTypes.Application,
+                    SearchResolutionOptions.None,
+                    CommandOrigin.Internal,
+                    context) as ApplicationInfo;
                 if (cmdInfo != null)
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: Style nitpick.
```suggestion
                    context) as ApplicationInfo;

                if (cmdInfo != null)
```

File: src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs (hunk 1 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: The current logic `CommandDiscovery.LookupCommandInfo(...)` doesn't look at the current working directory. It only returns an application command that can be found in PATH. However, `ProcessStartInfo` first looks at the current working directory (the USERPROFILE path by default?) and then search in PATH. I guess that's why we try to resolve the `ssh` command before starting the process.

@jborean93 Can you please update the "ProcessStartInfo" part of the comment?

**Comment by jborean93** [comment]
@daxian-dbw sorry I can't seem to reply inline to your last review comment.

The comment around cwd is about PowerShell setting `psi.WorkingDirectory = Path.GetDirectoryName(filePath);` later down in the function.

https://github.com/PowerShell/PowerShell/blob/ea07b93a40f64274505e3a070c1fd91684ff2959/src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs#L2325

The comment is explaining that we can't rely on `ProcessStartInfo` to lookup `ssh` for us as we use the full path to determine what cwd to set later on so we need to look it up ourselves.

Happy to reword the comment if it's confusing but would probably need some suggestions on what to change to make it clearer.

File: src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs (hunk 1 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: @daxian-dbw Is that a problem?

LookupCommandInfo can also create a problem due to its own specifics. 

In the context of this PR, the behavior of the system call (ProcessStartInfo) seems more correct. In reality, the search will be performed in the following order:
- _the directory where pwsh is located_.
- the default system directory.
- paths from PATHs.

I believe that the user will expect standard system behavior. It's not clear why we should abandon it. The first thing the user will do when manually installing ssh from an archived distribution is to put ssh.exe next to pwsh.exe . I would expect the same thing from the host app. I would generally abandon LookupCommandInfo in this context, in order to get uniform behavior.

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: In my testing, `ProcessStartInfo` looks at the process-level working directory when resolving a command. For example, I create the file `abc.exe` under `e:\temp` and then start `pwsh` from CMD in that folder to make it the process-level working directory (`[System.Environment]::CurrentDirectory`). Then running the following code in the `pwsh` session will result in the error `"... The specified executable is not a valid application for this OS platform."`. It indicates that `ProcessStartInfo` searched the process-level working directory for the specified command name. It actually searches that first before PATH.

```powershell
$startInfo = New-Object System.Diagnostics.ProcessStartInfo
$startInfo.FileName = 'abc.exe'
$process = New-Object System.Diagnostics.Process
$process.StartInfo = $startInfo
$process.Start()
```

`LookupCommandInfo` doesn't search the process-level working directory, and it's safer to keep that behavior.

Comment (jborean93) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: So what's the action you want out of here? Sorry I replied out of this thread as the comment I saw didn't allow a reply at the time https://github.com/PowerShell/PowerShell/pull/25780#issuecomment-3137711415.

**Comment by daxian-dbw** [comment]
@jborean93 It may not be a big deal, but your current comment sounds like "we don't know why cwd is set to the parent directory below, but since it's doing that, we have to search PATH manually here".

Please take a look at my comment above (https://github.com/PowerShell/PowerShell/pull/25780#discussion_r2252379697). I think it my be better to say in the comment that "we search PATH manually to keep that behavior of 'LookupCommandInfo'". What do you think?

**Comment by jborean93** [comment]
The comment is just trying to say we do the manual lookup because we need the full path so we can set the cwd ourselves. I can try and update the comment to be clearer but without knowing why we set the cwd later on in the code it's hard to justify the extra work when ProcessStartInfo could do it for us.

I'm assuming it's because we don't want to use `ssh` that might be in the cwd as `LookupCommand` ignores that or some other reason.

File: src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs (hunk 1 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: How about changing to the following?

```suggestion
                // A Runspace may not be present in the TLS in SDK hosted apps
                // or if running in another thread without a Runspace. While
                // 'ProcessStartInfo' can lookup the full path in PATH, it searches
                // the process' working directory first. 'LookupCommandInfo' does
                // not search the process' working directory and we want to keep that
                // behavior. So, we do a manual lookup here only in PATH.
```

Comment (jborean93) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: That's not the full story though. The other issue is that we do this with the `filePath`

https://github.com/PowerShell/PowerShell/blob/ea07b93a40f64274505e3a070c1fd91684ff2959/src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs#L2325

So not only do we want to avoid looking up `ssh` in the pwd we need to know the full path to derive the parent path to set on the process' cwd before running it.

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: That's true. Can you please update the comment to capture both of those points? Thank you!

Comment (jborean93) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]:
```suggestion
                // A Runspace may not be present in the TLS in SDK hosted apps
                // or if running in another thread without a Runspace. While
                // 'ProcessStartInfo' can lookup the full path in PATH, it searches
                // the process' working directory first. 'LookupCommandInfo' does
                // not search the process' working directory and we want to keep that
                // behavior. We also get the parent dir of the full path to set as the
                // new WorkingDirectory. So, we do a manual lookup here only in PATH.
```

**Review by daxian-dbw — APPROVED** [review]
LGTM. Thanks!

**Comment by Nova-Logic** [comment]
Many thanks to @jborean93  and  all powershell team for fixing this!

**Comment by jborean93** [comment]
Thanks for the review/merge @daxian-dbw and @iSazonov

**Comment by Nova-Logic** [comment]
If that would help https://github.com/PowerShell/PowerShell/compare/release/v7.5...Nova-Logic:PowerShell:release/v7.5 that is the  same change  with small tweak to make it compatible with .net 9 which is used in 7.5
