### PR TITLE
pwsh -Login support

### LINKED ISSUE #975: PowerShell should support inheritance of default shell environment variables as a default shell
## Steps to reproduce

I tried this on OS X
- Set powershell as your default shell (so it doesn't inherit your default shell env variables)
- Run 

```
> $env:PATH
/usr/bin:/bin
```

It doesn't have `/usr/local/bin` in PATH
So I cannot run `powershell` (and `gitk`, which really was my motivation)
## Expected behavior

`/usr/local/bin` should be there
powershell should be able to run apps from it, i.e. `gitk`, `powershell`
## Actual behavior

Cannot run `powershell`
## Environment data

v0.3.0

### PR DESCRIPTION
**Pull request by rjmholt**
# PR Summary

Adds support for the `-Login` flag to PowerShell, execs /bin/sh to run the login profile, which then execs PowerShell.

## PR Context

This implements https://github.com/PowerShell/PowerShell-RFC/pull/186.

Fix https://github.com/PowerShell/PowerShell/issues/975

The startup performance can be profiled with the script [here](https://gist.github.com/rjmholt/1ec87842e1ab4655bac34405c7a719e2).

Some implementation details:

- The argument parsing for this is done as early as possible
- This passes the arguments through `exec` and through `/bin/sh` (`/bin/bash` on macOS) with `"$@"`
- I've tried to avoid any allocation or other unneccessary computations, but there might be other opportunities to improve

**NOTE**: This supersedes `-LoadProfile`, which is a breaking change, but of a feature that only exists in preview (and is for the same use case as `-Login`).

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed: https://github.com/MicrosoftDocs/PowerShell-Docs/pull/4528
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by ExE-Boss** [comment]
I don’t think we need to remove `‑LoadProfile`.

File: src/powershell/Program.cs [hunk 1]
```diff
@@ -19,7 +20,227 @@ public sealed class ManagedPSEntry
...
+        /// </param>
+        /// <returns>
+        /// An exit code if exec failed, but if successful the calling process will be overwritten.
+        /// </returns>
+        [DllImport("libc",
+            EntryPoint = "execv",
+            CallingConvention = CallingConvention.Cdecl,
+            CharSet = CharSet.Ansi,
+            SetLastError = true)]
+        private static extern int Exec(string path, string[] args);
```
Comment (ExE-Boss) [inline src/powershell/Program.cs]: This should probably be in an `#if UNIX` block.

**Comment by rjmholt** [comment]
> I don’t think we need to remove ‑LoadProfile, we’ll just need to change the abbreviation to something like ‑lp.
>
> This is so that we can override an alias that passes -NoProfile.

`-LoadProfile` was only added to be compatible with `-Login` and was supposed to be a no-op, but was actually more confusingly order dependent. I personally don't think it's really something we want in PowerShell, and I think we should try to keep exe options to a minimum

File: src/powershell/Program.cs [hunk 2]
```diff
@@ -19,7 +20,236 @@ public sealed class ManagedPSEntry
...
+        {
+            // We need the path to the current pwsh executable
+            string pwshPath = System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName;
+
+            // Create input for /bin/sh that execs pwsh
+            int quotedPwshPathLength = GetQuotedPathLength(pwshPath);
+            string pwshInvocation = string.Create(
+                10 + quotedPwshPathLength, // exec '{pwshPath}' "$@"
+                (pwshPath, quotedPwshPathLength),
+                CreatePwshInvocation);
```
Comment (iSazonov) [inline src/powershell/Program.cs]: I wonder that we do the optimization (and others) if we fork.

File: src/powershell/Program.cs [hunk 3]
```diff
@@ -19,7 +20,236 @@ public sealed class ManagedPSEntry
...
+        /// An exit code if exec failed, but if successful the calling process will be overwritten.
+        /// </returns>
+        [DllImport("libc",
+            EntryPoint = "execv",
+            CallingConvention = CallingConvention.Cdecl,
+            CharSet = CharSet.Ansi,
+            SetLastError = true)]
+        private static extern int Exec(string path, string[] args);
     }
+#endif
```
Comment (ExE-Boss) [inline src/powershell/Program.cs]: This should be before the above closing brace.

File: src/powershell/Program.cs (hunk 2 above)
Comment (rjmholt) [reply src/powershell/Program.cs]: Not sure I follow you here -- can you rephrase maybe?

File: src/powershell/Program.cs [hunk 4]
```diff
@@ -19,7 +20,236 @@ public sealed class ManagedPSEntry
...
+                string arg = args[i];
+
+                // Must look like '-<name>'
+                if (arg == null || arg.Length < 2 || arg[0] != '-')
+                { 
+                    continue;
+                }
+
+                // Check for "-Login" or some prefix thereof
+                if (IsParam(arg, "login", "LOGIN"))
```
[the remark this answers is not in the document]
Comment (rjmholt) [reply src/powershell/Program.cs]: Two reasons:
- `MatchSwitch()` lives in another assembly, and loading it will slow startup
- `MatchSwitch()` allocates and is more general code than this method, which is tailored to the three parameters we care about. I actually am still thinking about inlining it as direct array indexing

File: src/powershell/Program.cs (hunk 2 above)
Comment (iSazonov) [reply src/powershell/Program.cs]: All the code run only once - no need to optimize something. I think we get more short and readable code if we will use classic string operations and string.Format.

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs [hunk 5]
```diff
@@ -185,7 +185,7 @@ internal class CommandLineParameterParser
             "file",
```
Comment (PoshChan) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs]: @rjmholt, your last commit had 6 failures in `PowerShell-CI-macos`
(These are 5 of the failures)

ConsoleHost unit tests.-Login pwsh switch.Accepts the -l switch for -Login and behaves correctly
```powershell
Expected 3198520b-afb2-4339-b864-3c12ba3fa282, but got $null.
at <ScriptBlock>, /Users/vsts/agent/2.153.2/work/1/s/test/powershell/Host/ConsoleHost.Tests.ps1: line 295
295:             $result | Should -Be $guid
```
ConsoleHost unit tests.-Login pwsh switch.Accepts the -L switch for -Login and behaves correctly
```powershell
Expected 3198520b-afb2-4339-b864-3c12ba3fa282, but got $null.
at <ScriptBlock>, /Users/vsts/agent/2.153.2/work/1/s/test/powershell/Host/ConsoleHost.Tests.ps1: line 295
295:             $result | Should -Be $guid
```
ConsoleHost unit tests.-Login pwsh switch.Accepts the -login switch for -Login and behaves correctly
```powershell
Expected 3198520b-afb2-4339-b864-3c12ba3fa282, but got $null.
at <ScriptBlock>, /Users/vsts/agent/2.153.2/work/1/s/test/powershell/Host/ConsoleHost.Tests.ps1: line 295
295:             $result | Should -Be $guid
```
ConsoleHost unit tests.-Login pwsh switch.Accepts the -Login switch for -Login and behaves correctly
```powershell
Expected 3198520b-afb2-4339-b864-3c12ba3fa282, but got $null.
at <ScriptBlock>, /Users/vsts/agent/2.153.2/work/1/s/test/powershell/Host/ConsoleHost.Tests.ps1: line 295
295:             $result | Should -Be $guid
```
ConsoleHost unit tests.-Login pwsh switch.Accepts the -LOGIN switch for -Login and behaves correctly
```powershell
Expected 3198520b-afb2-4339-b864-3c12ba3fa282, but got $null.
at <ScriptBlock>, /Users/vsts/agent/2.153.2/work/1/s/test/powershell/Host/ConsoleHost.Tests.ps1: line 295
295:             $result | Should -Be $guid
```

**Comment by SteveL-MSFT** [comment]
@rjmholt please make corresponding doc change for PS7 and link to this PR

File: src/powershell/Program.cs [hunk 6]
```diff
@@ -19,7 +20,229 @@ public sealed class ManagedPSEntry
...
+                j++;
+            }
+
+            // A null is required by exec
+            execArgs[execArgs.Length - 1] = null;
+
+            // On macOS, sh doesn't support login, so we run /bin/bash
+            if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
+            {
+                return Exec("/bin/bash", execArgs);
```
Comment (SteveL-MSFT) [inline src/powershell/Program.cs]: We may want to just use zsh for macOS since that is where Apple is going

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]

File: src/powershell/Program.cs (hunk 2 above)
Comment (rjmholt) [reply src/powershell/Program.cs]: Right, the merits of various optimisations are dubious since we are just trying to exec as quickly as possible, which will then overwrite the whole process.

But I'm assuming that calls to things like malloc and the possibility of GC are still things we want to avoid. Similarly, if string formatting is handled by complex code in another assembly, I'd prefer to hardcode the small case here in an attempt to do our best to execute only the IL we know about here.

**Comment by rjmholt** [comment]
https://github.com/MicrosoftDocs/PowerShell-Docs/pull/4528/files

File: src/powershell/Program.cs [hunk 7]
```diff
@@ -19,7 +20,232 @@ public sealed class ManagedPSEntry
...
+        /// <param name="paramToCheck">The lowercase name of the parameter to check.</param>
+        /// <param name="paramToCheckUpper">The uppercase name of the parameter to check.</param>
+        /// <returns></returns>
+        private static bool IsParam(
+            string arg,
+            string paramToCheck,
+            string paramToCheckUpper)
+        {
+            // Quick fail if the argument is longer than the parameter
+            if (arg.Length > paramToCheck.Length + 1)
```
Comment (SteveL-MSFT) [inline src/powershell/Program.cs]: Should we cache `arg.length`?

File: src/powershell/Program.cs [hunk 8]
```diff
@@ -19,7 +20,232 @@ public sealed class ManagedPSEntry
...
+        /// The exit code of exec if it fails.
+        /// If exec succeeds, this process is overwritten so we never actually return.
+        /// </returns>
+        private static int ExecPwshLogin(string[] args, int loginArgIndex)
+        {
+            // We need the path to the current pwsh executable
+            string pwshPath = System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName;
+
+            // Create input for /bin/sh that execs pwsh
+            int quotedPwshPathLength = GetQuotedPathLength(pwshPath);
```
Comment (SteveL-MSFT) [inline src/powershell/Program.cs]: Does `pwshPath` actually get quoted?  I checked on Windows and macOS, and even with whitespace there's no quoting returned.

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]

File: src/powershell/Program.cs (hunk 7 above)
Comment (rjmholt) [reply src/powershell/Program.cs]: It's just a field on the string/array, and one I imagine the CLR is well optimised to retrieve and recognise calls to

File: src/powershell/Program.cs (hunk 8 above)
Comment (rjmholt) [reply src/powershell/Program.cs]: Looks like this on my machine:

Screen Shot 2019-07-08 at 16 39 11

The invocation looks like:

```
"exec '/Users/rjmholt/Documents/Dev/Microsoft/PowerShell/src/powershell-unix/bin/Debug/netcoreapp3.0/osx-x64/publish/pwsh' \"$@\""
```

How did you check in your case?

Also, this code path doesn't exist on Windows.

Comment (rjmholt) [reply src/powershell/Program.cs]: Oh I see you mean `pwshPath`; no that's what .NET gives us. That path is quoted inside `CreatePwshInvocation`, so no intermediate strings are created.

File: src/powershell/Program.cs [hunk 9]
```diff
@@ -19,7 +20,232 @@ public sealed class ManagedPSEntry
...
+        /// <param name="args">The argument vector passed to pwsh.</param>
+        /// <param name="loginArgIndex">The index of -Login in the argument vector.</param>
+        /// <returns>
+        /// The exit code of exec if it fails.
+        /// If exec succeeds, this process is overwritten so we never actually return.
+        /// </returns>
+        private static int ExecPwshLogin(string[] args, int loginArgIndex)
+        {
+            // We need the path to the current pwsh executable
+            string pwshPath = System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName;
```
Comment (rjmholt) [inline src/powershell/Program.cs]: We might be able to find a faster API to get the path to pwsh.exe or `$PSHOME` here, but need advice on what that is. One I was looking at was `Assembly.GetExecutingAssembly().Location`

File: src/powershell/Program.cs (hunk 8 above)
Comment (SteveL-MSFT) [reply src/powershell/Program.cs]: It seems that at this point `pwshPath` doesn't have any quotes, so the call to `GetQuotedPathLength()` is unnecessary.

File: src/powershell/Program.cs (hunk 9 above)
Comment (rjmholt) [reply src/powershell/Program.cs]: I've tried this now, and it's slower. Keeping the `GetCurrentProcess` version

File: src/powershell/Program.cs (hunk 8 above)
Comment (rjmholt) [reply src/powershell/Program.cs]: The path may have whitespace in it, in which case we need to put quotes around the whole thing for `exec`.

Imagine PowerShell is installed to `/Users/Rob Holt/apps/PowerShell/pwsh`, then not quoting will produce:

```sh
exec /Users/Rob Holt/apps/PowerShell/pwsh "$@"
```

In that case (which we support, because of binplace installation), exec will fail. So instead we quote it:

```sh
exec '/Users/Rob Holt/apps/PowerShell/pwsh' "$@"
```

**Comment by andschwa** [comment]
@rjmholt 🥇

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs [hunk 10]
```diff
@@ -717,21 +717,23 @@ private void ParseHelper(string[] args)
...
                 }
-                else if (MatchSwitch(switchKey, "help", "h") || MatchSwitch(switchKey, "?", "?"))
+
+                if (MatchSwitch(switchKey, "help", "h") || MatchSwitch(switchKey, "?", "?"))
                 {
                     _showHelp = true;
                     _showExtendedHelp = true;
                     _abortStartup = true;
                 }
+                else if (MatchSwitch(switchKey, "login", "l"))
```
Comment (rjmholt) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs]: Ideally we should move this to the bottom, since the check will never succeed and all switches below it will check this first.

But I left it here because of alpha ordering and also because I feel like it might be worth doing a wider investigation of the switch detection logic for startup performance.

File: src/powershell/Program.cs (hunk 7 above)
Comment (iSazonov) [reply src/powershell/Program.cs]: I would not hope for it - with TC many optimizations are skipped.

File: src/powershell/Program.cs (hunk 8 above)
Comment (iSazonov) [reply src/powershell/Program.cs]: I also doubt that this is necessary as we pass the parameters in execv "as is" - no parsing.

File: src/powershell/Program.cs (hunk 9 above)
Comment (iSazonov) [reply src/powershell/Program.cs]: We could compare with `Environment.CommandLine`.

Comment (rjmholt) [reply src/powershell/Program.cs]: That one might be more work; it depends on the invocation and may start with a relative path and contain arguments. In my current session `[Environment]::CommandLine`:

```
"C:\Program Files\PowerShell\7-preview\pwsh.dll" -WorkingDirectory ~
```

Also, like you can see in the code in this PR for `exec`, you can set `$0`, so that could almost be anything.

I also thought about `[Environment]::CurrentDirectory` and `[System.IO.Directory]::GetCurrentDirectory` but again those can both be changed.

File: src/powershell/Program.cs (hunk 7 above)
Comment (rjmholt) [reply src/powershell/Program.cs]: https://github.com/dotnet/coreclr/blob/48ff0937552e540f21835391b693daf47ffabece/src/System.Private.CoreLib/src/System/String.CoreCLR.cs#L46-L57

File: src/powershell/Program.cs (hunk 9 above)
Comment (iSazonov) [reply src/powershell/Program.cs]: If we say about login shell scenario I guess we have absolute path.

File: src/powershell/Program.cs (hunk 8 above)
Comment (rjmholt) [reply src/powershell/Program.cs]: This is a single parameter to execv. It looks like this:

```
execv("/bin/sh", "-l", "-c", "exec '/Path/to/pwsh' \"$@\"", <args>, <to>, <pwsh>)
```

(It's slightly more complicated than that, but this illustrates the required logic).

We exec twice, once with the syscall to get /bin/sh and once in /bin/sh with the builtin. The second case is a short shell command, and in that the path to pwsh needs escaping so that the `exec` *builtin* hits the right executable.

Comment (iSazonov) [reply src/powershell/Program.cs]: If we will consider only login shell scenario perhaps we could simplify preparing of the  arguments.

File: src/powershell/Program.cs (hunk 9 above)
Comment (SteveL-MSFT) [reply src/powershell/Program.cs]: Since you have to inspect `/proc` and call `sysctl()` anyways, you should use that to get this info

Comment (rjmholt) [reply src/powershell/Program.cs]: Yes I had the same thought! Trying to work out if that's possible on macOS

**Review by iSazonov — COMMENTED** [review]
I think all native code must be in PowerShell-Native as C code. Really we need 2 function - IsAlreadyLoginShell() and IsLoginArgumentPresent().
It simplify code in the repo and C code will be simple too. And it will be fastest.

Also the code in PowerShell Native could help us to resolve #3322 with additional GetCommandLine() function.

File: src/powershell/Program.cs [hunk 11]
```diff
@@ -19,7 +28,389 @@ public sealed class ManagedPSEntry
...
+        /// <returns>
+        /// The exit code of exec if it fails.
+        /// If exec succeeds, this process is overwritten so we never actually return.
+        /// </returns>
+        private static int ExecPwshLogin(string[] args, int loginArgIndex, string pwshPath, bool isMacOS)
+        {
+            // Create input for /bin/sh that execs pwsh
+            int quotedPwshPathLength = GetQuotedPathLength(pwshPath);
+            string pwshInvocation = string.Create(
+                19 + quotedPwshPathLength, // exec +pwsh '{pwshPath}' "$@"
```
Comment (ExE-Boss) [inline src/powershell/Program.cs]:
```suggestion
                19 + quotedPwshPathLength, // exec -a +pwsh '{pwshPath}' "$@"
```

File: test/powershell/Host/ConsoleHost.Tests.ps1 [hunk 12]
```diff
@@ -245,41 +245,64 @@ Describe "ConsoleHost unit tests" -tags "Feature" {
...
+            @{ LoginSwitch = '-l' }
+            @{ LoginSwitch = '-L' }
+            @{ LoginSwitch = '-login' }
+            @{ LoginSwitch = '-Login' }
+            @{ LoginSwitch = '-LOGIN' }
+            @{ LoginSwitch = '-log' }
+        ) {
+            param($LoginSwitch)
+
+            $result = & $powershell $LoginSwitch -Command "`$env:$envVarName"
```
Comment (SteveL-MSFT) [inline test/powershell/Host/ConsoleHost.Tests.ps1]: Should probably add `-noprofile` before $LoginSwitch to both cover the processing so that `-l` isn't first, but also don't exercise user PS profile in this test.

Comment (SteveL-MSFT) [inline test/powershell/Host/ConsoleHost.Tests.ps1]: Should have a test like:

```powershell
pwsh -noprofile -command 'function -login { "hello" }'; -login
```

File: test/powershell/Host/ConsoleHost.Tests.ps1 [hunk 13]
```diff
@@ -245,41 +245,64 @@ Describe "ConsoleHost unit tests" -tags "Feature" {
...
+                $LASTEXITCODE | Should -Be 0
+                return
             }
+
+            $result | Should -Be $guid
+            $LASTEXITCODE | Should -Be 0
         }
-    }
 
+        It "Starts as a login shell with '-' prepended to name" -Skip:([bool](Get-Command -Name bash -ErrorAction Ignore)) {
```
Comment (SteveL-MSFT) [inline test/powershell/Host/ConsoleHost.Tests.ps1]: Can you rely on `sh` instead of skipping if bash is not available?  Prefer not to skip if bash is not available as if for some reason AzDevOps removes bash from their Linux containers, we won't know if this test fails.

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]

File: test/powershell/Host/ConsoleHost.Tests.ps1 (hunk 13 above)
Comment (rjmholt) [reply test/powershell/Host/ConsoleHost.Tests.ps1]: `exec -a` which we need to start pwsh as `-pwsh` isn't available on `sh`

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs (hunk 5 above)
Comment (PoshChan) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs]: @rjmholt, your last commit had 1 failures in `PowerShell-CI-static-analysis`
Verify Markdown Links.Verify links in /home/vsts/work/1/s/CHANGELOG.md.https://dependabot.com should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```

File: test/powershell/Host/ConsoleHost.Tests.ps1 [hunk 14]
```diff
@@ -245,41 +245,78 @@ Describe "ConsoleHost unit tests" -tags "Feature" {
...
-            param($switch)
+        It "Doesn't run the login profile when -Login not used" {
+            $result = & $powershell -Command "`$env:$envVarName"
+            $result | Should -BeNullOrEmpty
+            $LASTEXITCODE | Should -Be 0
+        }
+
+        It "Doesn't falsely recognise -Login when elsewhere in the invocation" {
+            $result = & $powershell -nop -c 'Write-Output "-login"'
+            $result | Should -Be '-login'
```
Comment (SteveL-MSFT) [inline test/powershell/Host/ConsoleHost.Tests.ps1]:
```suggestion
            $result | Should -BeExactly '-login'
```

File: test/powershell/Host/ConsoleHost.Tests.ps1 [hunk 15]
```diff
@@ -245,41 +245,78 @@ Describe "ConsoleHost unit tests" -tags "Feature" {
...
-            if (Test-Path $profile) {
-                & pwsh $switch -command exit | Should -BeExactly "profile-loaded"
-            }
-            else {
-                # In CI, may not be able to write to $profile location, so just verify that the switch is accepted
-                # and no error message is in the output
-                & pwsh $switch -command exit *>&1 | Should -BeNullOrEmpty
+        It "Doesn't falsely recognise -Login when used after -Command" {
+            $result = & $powershell -nop -c 'Write-Output' -Login
+            $result | Should -Be '-login'
```
Comment (SteveL-MSFT) [inline test/powershell/Host/ConsoleHost.Tests.ps1]:
```suggestion
            $result | Should -BeExactly '-Login'
```

File: test/powershell/Host/ConsoleHost.Tests.ps1 [hunk 16]
```diff
@@ -245,41 +245,78 @@ Describe "ConsoleHost unit tests" -tags "Feature" {
...
+            $LASTEXITCODE | Should -Be 0
         }
-    }
 
+        It "Starts as a login shell with '-' prepended to name" -Skip:(-not (Get-Command -Name /bin/bash -ErrorAction Ignore)) {
+            $quoteEscapedPwsh = $powershell.Replace("'", "\'")
+            $pwshCommand = "`$env:$envVarName"
+            $bashCommand = "exec -a '-pwsh' '$quoteEscapedPwsh' -NoProfile -Command '`$env:$envVarName' ''"
+            $result = /bin/bash -c $bashCommand
+            $result | Should -Be $guid
```
Comment (SteveL-MSFT) [inline test/powershell/Host/ConsoleHost.Tests.ps1]:
```suggestion
            $result | Should -BeExactly $guid
```

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs (hunk 5 above)
Comment (PoshChan) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs]: @rjmholt, your last commit had 1 failures in `PowerShell-CI-static-analysis`
Verify Markdown Links.Verify links in /home/vsts/work/1/s/CHANGELOG.md.https://dependabot.com should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```

**Review by SteveL-MSFT — APPROVED** [review]

**Comment by rjmholt** [comment]
@PoshChan please retry

**Comment by PoshChan** [comment]
@rjmholt, I do not understand: please retry

Commands available in this repo for you:
  - `retry <target>` this will attempt to retry only the failed jobs for the target pipeline
  - `rebuild <target>` this will perform a complete rebuild of the target pipeline, `rerun` can be used in place of `rebuild`
    Supported values for \<target\> which can be a comma separated list are: `static`,`windows`,`macos`,`linux`,`all`
  - `get failures` this will attempt to get the latest failures for all of the target pipelines
  - `remind me in <value> <units>` this will create a reminder that will be posted after the specified duration
    \<value\> is a number, and \<units\> can be `minutes`, `hours`, or `days` (singular or plural)

**Comment by rjmholt** [comment]
@PoshChan please retry PowerShell-CI-static-analysis

**Comment by PoshChan** [comment]
@rjmholt, I do not understand the build target(s) `PowerShell-CI-static-analysis`; I only allow `static`, `windows`, `macos`, `linux`, `all`

**Comment by rjmholt** [comment]
@PoshChan thanks for playing

**Comment by PoshChan** [comment]
@rjmholt, all requests start with the magic word: `Please`

Commands available in this repo for you:
  - `retry <target>` this will attempt to retry only the failed jobs for the target pipeline
  - `rebuild <target>` this will perform a complete rebuild of the target pipeline, `rerun` can be used in place of `rebuild`
    Supported values for \<target\> which can be a comma separated list are: `static`,`windows`,`macos`,`linux`,`all`
  - `get failures` this will attempt to get the latest failures for all of the target pipelines
  - `remind me in <value> <units>` this will create a reminder that will be posted after the specified duration
    \<value\> is a number, and \<units\> can be `minutes`, `hours`, or `days` (singular or plural)

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs (hunk 5 above)
Comment (PoshChan) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs]: @rjmholt, your last commit had 1 failures in `PowerShell-CI-macos`
ConsoleHost unit tests.-Login pwsh switch.Doesn't falsely recognise -Login when used after -Command
```powershell
Expected strings to be the same, but they were different.
String lengths are both 6.
Strings differ at index 1.
Expected: '-login'
But was:  '-Login'
at <ScriptBlock>, /Users/vsts/agent/2.154.1/work/1/s/test/powershell/Host/ConsoleHost.Tests.ps1: line 285
285:             $result | Should -BeExactly '-login'
```

Comment (PoshChan) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs]: @rjmholt, your last commit had 1 failures in `PowerShell-CI-windows`
Set/New/Remove-Service cmdlet tests.Set-Service can change credentials of a service
```powershell
Expected a value, but got $null or empty.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Management\Set-Service.Tests.ps1: line 183
183:             $service | Should -Not -BeNullOrEmpty
```

**Review by iSazonov — COMMENTED** [review]
I suggest to move most of the code in PowerShell-Native. I guess this makes code more simple, allocation free, fastest and we can reuse it (see #3322).

Also we could use the here-docs to run bash http://tldp.org/LDP/abs/html/here-docs.html without escaping arguments.

**Comment by rjmholt** [comment]
> I suggest to move most of the code in PowerShell-Native

I spoke to @SteveL-MSFT and for now I think the preference is to keep this here to keep things relatively simple. I would prefer to implement this all natively as well (ideally before loading/running .NET at all) but that poses complexity and maintenance challenges. Adding this functionality to PowerShell-Native is something that requires more investigation, but I think the hope is that we will eventually be able to do away with PowerShell-Native as well.

**Comment by rjmholt** [comment]
Also we could use the here-docs to run bash http://tldp.org/LDP/abs/html/here-docs.html without escaping arguments.

That's a nice idea, although we only have to escape a single argument to `exec` and it sits between other arguments, making that a challenge. For now, the escaping logic is done. We can change it later if there are advantages to that.

**Comment by iSazonov** [comment]
Perhaps worth it to automatically publish PowerShell-Native prerelease nuget package versions. In the case we could easily reference its in the repo and test with CIs.
I think we still have time before 7.0 release "to make thinks right".

**Comment by anmenaga** [comment]
@adityapatwardhan any thoughts on @iSazonov's proposal?
@rjmholt new commandline parameter needs doc updates; please open an issue in doc repo and link it here in PR summary under 'Documentation needed'.

**Comment by rjmholt** [comment]
@anmenaga please see https://github.com/MicrosoftDocs/PowerShell-Docs/pull/4528 for docs

**Comment by adityapatwardhan** [comment]
@iSazonov - We do release `Micrsoft.PowerShell.Native` previews when there are changes. Example: https://www.nuget.org/packages/Microsoft.PowerShell.Native/7.0.0-preview.1

`PowerShell` and `PowerShell-Native` are separated on purpose to reduce build complexity. If there is a need to release `Microsoft.PowerShell.Native` earlier than the next release of `PowerShell` that is possible too.

**Comment by anmenaga** [comment]
Considering:
1) long-term plans for PowerShell-Native;
2) important part of this PR is that it adds a required functionality (with not-perfect, but ok-for-now implementation that can be changed later if necessary);
3) there is already 1 approval;
I don't think discussion about moving/not-moving this to PowerShell-Native should be blocking this PR. I plan to merge this in a couple of days unless there are strong objections.

@rjmholt please fix the `ManagedEntranceStrings.resx` conflict.

**Comment by rjmholt** [comment]
> please fix the ManagedEntranceStrings.resx conflict.

Done

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs [hunk 17]
```diff
@@ -183,7 +183,7 @@ internal class CommandLineParameterParser
             "file",
```
Comment (PoshChan) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs]: @rjmholt, your last commit had 4 failures in `PowerShell-CI-static-analysis`
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/testing-guidelines/CodeCoverageAnalysis.md.https://codecov.io/gh/PowerShell/PowerShell/tree/de5f69cf942a85839c907f11a29cf9c09f9de8b4/src should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/testing-guidelines/CodeCoverageAnalysis.md.https://codecov.io/gh/PowerShell/PowerShell should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/README.md.https://codecov.io/gh/PowerShell/PowerShell/branch/master/graph/badge.svg should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/README.md.https://codecov.io/gh/PowerShell/PowerShell should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```

Comment (SteveL-MSFT) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs]: This looks like a networking issue at the time this was run

**Comment by SteveL-MSFT** [comment]
@PoshChan please restart static

**Comment by PoshChan** [comment]
@SteveL-MSFT, I do not understand: please restart static

Commands available in this repo for you:
  - `retry <target>` this will attempt to retry only the failed jobs for the target pipeline
  - `rebuild <target>` this will perform a complete rebuild of the target pipeline, `rerun` can be used in place of `rebuild`
    Supported values for \<target\> which can be a comma separated list are: `static`,`windows`,`macos`,`linux`,`all`
  - `get failures` this will attempt to get the latest failures for all of the target pipelines
  - `remind me in <value> <units>` this will create a reminder that will be posted after the specified duration
    \<value\> is a number, and \<units\> can be `minutes`, `hours`, or `days` (singular or plural)

**Comment by SteveL-MSFT** [comment]
@PoshChan please retry static

**Comment by PoshChan** [comment]
@SteveL-MSFT, successfully started retry of `PowerShell-CI-static-analysis`

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs (hunk 17 above)
Comment (PoshChan) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs]: @rjmholt, your last commit had 8 failures in `PowerShell-CI-static-analysis`
(These are 5 of the failures)

Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/testing-guidelines/CodeCoverageAnalysis.md.https://codecov.io/gh/PowerShell/PowerShell/tree/de5f69cf942a85839c907f11a29cf9c09f9de8b4/src should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/testing-guidelines/CodeCoverageAnalysis.md.https://codecov.io/gh/PowerShell/PowerShell should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/README.md.https://codecov.io/gh/PowerShell/PowerShell/branch/master/graph/badge.svg should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/README.md.https://codecov.io/gh/PowerShell/PowerShell should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/README.md.https://codecov.io/gh/PowerShell/PowerShell/branch/master/graph/badge.svg should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```

**Comment by SteveL-MSFT** [comment]
@PoshChan please retry static

**Comment by PoshChan** [comment]
@SteveL-MSFT, successfully started retry of `PowerShell-CI-static-analysis`

File: src/powershell/Program.cs [hunk 18]
```diff
@@ -19,7 +59,439 @@ public sealed class ManagedPSEntry
...
+                if (IsParam(arg, "login", "LOGIN"))
+                {
+                    loginIndex = i;
+                    return true;
+                }
+
+                // After -File and -Command, all parameters are passed
+                // to the invoked file or command, so we can stop looking.
+                if (IsParam(arg, "file", "FILE")
+                    || IsParam(arg, "command", "COMMAND"))
```
Comment (daxian-dbw) [inline src/powershell/Program.cs]: Shall we check for `-Version | -v` as well here? Flags specified after `-v` will be ignored.
Are there any other similar flags?

File: src/powershell/Program.cs [hunk 19]
```diff
@@ -19,7 +59,439 @@ public sealed class ManagedPSEntry
...
+        /// </returns>
+        private static int ExecPwshLogin(string[] args, int loginArgIndex, string pwshPath, bool isMacOS)
+        {
+            // Create input for /bin/sh that execs pwsh
+            int quotedPwshPathLength = GetQuotedPathLength(pwshPath);
+
+            // /bin/sh does not support the exec -a feature
+            int pwshExecInvocationLength = isMacOS
+                ? quotedPwshPathLength + 19  // exec -a +pwsh '{pwshPath}' "$@"
+                : quotedPwshPathLength + 10; // exec '{pwshPath}' "$@"
```
Comment (daxian-dbw) [inline src/powershell/Program.cs]: Talked to @rjmholt about this optimization for platform that supports `exec -a`.
If environment variable can be preserved after `exec`, then using an env variable might be better in that we wouldn't need to check for `-login` or `-l` for Linux as well.

File: src/powershell/Program.cs [hunk 20]
```diff
@@ -19,7 +59,439 @@ public sealed class ManagedPSEntry
...
+            // Set up the arguments for /bin/sh
+            var execArgs = new string[args.Length + 5];
+
+            // execArgs[0] is set below to the correct shell executable
+
+            // The command arguments
+
+            // First argument is the command name.
+            // Setting this to /bin/sh enables sh emulation in zsh (which examines $0 to determine how it should behave).
+            execArgs[0] = "/bin/sh";
```
Comment (daxian-dbw) [inline src/powershell/Program.cs]: We run `zsh` on macOS, should this arg be `/bin/zsh` then?

File: src/powershell/Program.cs (hunk 18 above)
Comment (rjmholt) [reply src/powershell/Program.cs]: Ah good catch!

File: src/powershell/Program.cs (hunk 19 above)
Comment (rjmholt) [reply src/powershell/Program.cs]: Will document. Also going to investigate using an environment variable.

File: src/powershell/Program.cs (hunk 20 above)
Comment (rjmholt) [reply src/powershell/Program.cs]: Using `/bin/sh` means `zsh` starts in `sh` emulation mode. I might try enhancing the comment above to make that clearer

File: src/powershell/Program.cs [hunk 21]
```diff
@@ -19,7 +59,439 @@ public sealed class ManagedPSEntry
...
+
+            span[j] = '\'';
+        }
+
+        /// <summary>
+        /// If the given exit code is negative, throws a StartupException.
+        /// </summary>
+        /// <param name="call">The native call that was attempted.</param>
+        /// <param name="code">The exit code it returned.</param>
+        private static void ThrowIfFails(string call, int code)
```
Comment (daxian-dbw) [inline src/powershell/Program.cs]: Minor: maybe name it as `ThrowOnFailure`.

File: src/powershell/Program.cs (hunk 18 above)
Comment (rjmholt) [reply src/powershell/Program.cs]: How about `-EncodedCommand` and `-Help`? Docs don't say it, but they also don't say `-EncodedCommand` is mutually exclusive with `-Command`. I tried `-?` with `-Version` and it prints both, but `-?` before `-Command` only shows the help...

**Comment by rjmholt** [comment]
Spoke to @daxian-dbw offline about p/invokes vs native code. We agreed that the current implementation is good enough for now and we want to investigate moving the underlying logic into PSNative for performance benefits

File: src/powershell/Program.cs [hunk 22]
```diff
@@ -19,7 +63,458 @@ public sealed class ManagedPSEntry
...
+                    // If argv[0][0] == '-', we have been invoked as login.
+                    // Doing this, the buffer we populated also recorded `exec_path`,
+                    // which is the path to our executable `pwsh`.
+                    // We can reuse this value later to prevent needing to call a .NET API
+                    // to generate our exec invocation.
+
+
+                    // We don't care about argc's value, since argv[0] must always exist.
+                    // Skip over argc, but remember where exec_path is for later
+                    execPathPtr = IntPtr.Add(procargs, sizeof(int));
```
Comment (daxian-dbw) [inline src/powershell/Program.cs]: The variable name `execPathPtr` is misleading as we are calling `exec` below. The var name seems indicating it holds the path to the `exec` utility.
I suggest to change it to `executablePathPtr`.

File: src/powershell/Program.cs [hunk 23]
```diff
@@ -19,7 +63,458 @@ public sealed class ManagedPSEntry
...
+        /// <summary>
+        /// If the given exit code is negative, throws a StartupException.
+        /// </summary>
+        /// <param name="call">The native call that was attempted.</param>
+        /// <param name="code">The exit code it returned.</param>
+        private static void ThrowOnFailure(string call, int code)
+        {
+            if (code < 0)
+            {
+                code = Marshal.GetLastWin32Error();
```
Comment (daxian-dbw) [inline src/powershell/Program.cs]: I doubt this will have any effect. According to the [doc](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getlastwin32error?view=netcore-3.0), this works only if the unmanaged function can call the [`SetLastError`](https://docs.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-setlasterror) Windows API.

File: src/powershell/Program.cs [hunk 24]
```diff
@@ -19,7 +63,458 @@ public sealed class ManagedPSEntry
...
+                if (arg.Equals("/?"))
+                {
+                    return false;
+                }
+
+                // Must look like '-<name>'
+                if (arg[0] != '-')
+                {
+                    continue;
+                }
```
Comment (daxian-dbw) [inline src/powershell/Program.cs]: Think about this: `pwsh script.ps1 -log`. With the current code, we will treat it incorrectly as a login shell.

**Comment by daxian-dbw** [comment]
> Spoke to @daxian-dbw offline about p/invokes vs native code. We agreed that the current implementation is good enough for now and we want to investigate moving the underlying logic into PSNative for performance benefits

Yes, talked with Rob on this. P/Invoke itself is expensive, plus Jitting the P/Invoke code possibly will be more expensive than non-P/Invoke code.
By moving some of the P/Invoke code (e.g. the code to get the first byte of the executable name and the executable path) to native code and simply calling one P/Invoke from managed code to get what we need would be more efficient.
But that can happen in a follow-up PR, not this one.

File: src/powershell/Program.cs (hunk 22 above)
Comment (rjmholt) [reply src/powershell/Program.cs]: Well it's actually a pointer to `exec_path`; I was hoping my use of `Path` would indicate that. But I can change the name

File: src/powershell/Program.cs (hunk 23 above)
Comment (rjmholt) [reply src/powershell/Program.cs]: It looks like I need to indicate `SetLastError` in the `DllImport` but otherwise, [I think this should work](https://developers.redhat.com/blog/2019/03/25/using-net-pinvoke-for-linux-system-functions/)

File: src/powershell/Program.cs (hunk 22 above)
Comment (daxian-dbw) [reply src/powershell/Program.cs]: Yes, I understand it's pointing to `exec_path`, and it's natural to name the var as `execPathxxx` with no question. The thing is, in our situation here, we are invoking `exec` subsequently, and `exec_path` makes it look like _the path to exec_ whereas it actually means _the path of the executable_ and that's the part I found confusing when looking at the code initially.

File: src/powershell/Program.cs (hunk 23 above)
Comment (daxian-dbw) [reply src/powershell/Program.cs]: The MSDN document about `GetLastWin32Error()` needs to be updated

File: src/powershell/Program.cs (hunk 22 above)
Comment (rjmholt) [reply src/powershell/Program.cs]: Well `exec` doesn't have a path; it's either a builtin or a syscall. It lives only in memory

Comment (daxian-dbw) [reply src/powershell/Program.cs]: True, maybe it's just because I'm not familiar with whether `exec` is an utility or a builtin shell command :)

**Comment by rjmholt** [comment]
I've amended the logic here to only recognise `-Login` when it's the first argument. This is so we don't have to reimplement all of argument parsing at this early stage. When we work on a native implementation, we can have a look at whether improving that is feasible.

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs (hunk 17 above)
Comment (PoshChan) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs]: @rjmholt, your last commit had 6 failures in `PowerShell-CI-macos`
(These are 5 of the failures)

ConsoleHost unit tests.-Login pwsh switch.Accepts the -l switch for -Login and behaves correctly
```powershell
Expected exactly 5701bc7f-2198-4485-97d5-e3cbeca0856e, but got $null.
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/s/test/powershell/Host/ConsoleHost.Tests.ps1: line 307
307:             $result | Should -BeExactly $guid
```
ConsoleHost unit tests.-Login pwsh switch.Accepts the -L switch for -Login and behaves correctly
```powershell
Expected exactly 5701bc7f-2198-4485-97d5-e3cbeca0856e, but got $null.
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/s/test/powershell/Host/ConsoleHost.Tests.ps1: line 307
307:             $result | Should -BeExactly $guid
```
ConsoleHost unit tests.-Login pwsh switch.Accepts the -login switch for -Login and behaves correctly
```powershell
Expected exactly 5701bc7f-2198-4485-97d5-e3cbeca0856e, but got $null.
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/s/test/powershell/Host/ConsoleHost.Tests.ps1: line 307
307:             $result | Should -BeExactly $guid
```
ConsoleHost unit tests.-Login pwsh switch.Accepts the -Login switch for -Login and behaves correctly
```powershell
Expected exactly 5701bc7f-2198-4485-97d5-e3cbeca0856e, but got $null.
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/s/test/powershell/Host/ConsoleHost.Tests.ps1: line 307
307:             $result | Should -BeExactly $guid
```
ConsoleHost unit tests.-Login pwsh switch.Accepts the -LOGIN switch for -Login and behaves correctly
```powershell
Expected exactly 5701bc7f-2198-4485-97d5-e3cbeca0856e, but got $null.
at <ScriptBlock>, /Users/vsts/agent/2.155.1/work/1/s/test/powershell/Host/ConsoleHost.Tests.ps1: line 307
307:             $result | Should -BeExactly $guid
```

Comment (PoshChan) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs]: @rjmholt, your last commit had 6 failures in `PowerShell-CI-linux`
(These are 5 of the failures)

ConsoleHost unit tests.-Login pwsh switch.Accepts the -l switch for -Login and behaves correctly
```powershell
Expected exactly f3d556fd-5834-4676-a2a8-cfc793ace122, but got $null.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Host/ConsoleHost.Tests.ps1: line 307
307:             $result | Should -BeExactly $guid
```
ConsoleHost unit tests.-Login pwsh switch.Accepts the -L switch for -Login and behaves correctly
```powershell
Expected exactly f3d556fd-5834-4676-a2a8-cfc793ace122, but got $null.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Host/ConsoleHost.Tests.ps1: line 307
307:             $result | Should -BeExactly $guid
```
ConsoleHost unit tests.-Login pwsh switch.Accepts the -login switch for -Login and behaves correctly
```powershell
Expected exactly f3d556fd-5834-4676-a2a8-cfc793ace122, but got $null.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Host/ConsoleHost.Tests.ps1: line 307
307:             $result | Should -BeExactly $guid
```
ConsoleHost unit tests.-Login pwsh switch.Accepts the -Login switch for -Login and behaves correctly
```powershell
Expected exactly f3d556fd-5834-4676-a2a8-cfc793ace122, but got $null.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Host/ConsoleHost.Tests.ps1: line 307
307:             $result | Should -BeExactly $guid
```
ConsoleHost unit tests.-Login pwsh switch.Accepts the -LOGIN switch for -Login and behaves correctly
```powershell
Expected exactly f3d556fd-5834-4676-a2a8-cfc793ace122, but got $null.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Host/ConsoleHost.Tests.ps1: line 307
307:             $result | Should -BeExactly $guid
```

**Review by daxian-dbw — APPROVED** [review]
LGTM

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs (hunk 17 above)
Comment (PoshChan) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs]: @rjmholt, your last commit had 2 failures in `PowerShell-CI-static-analysis`
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/cmdlet-example/command-line-simple-example.md.https://www.microsoft.com/net/core#linuxubuntu should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/building/windows-core.md.https://www.microsoft.com/net/core#windowscmd should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 111
111:                                 throw "retry of URL failed with error: $($_.Message)"

```

**Comment by daxian-dbw** [comment]
@PoshChan please retry static

**Comment by PoshChan** [comment]
@daxian-dbw, successfully started retry of `PowerShell-CI-static-analysis`

File: src/powershell/Program.cs [hunk 25]
```diff
@@ -19,7 +63,433 @@ public sealed class ManagedPSEntry
...
+
+        /// <summary>
+        /// The `getpid` POSIX syscall we use to quickly get the current process PID on macOS.
+        /// </summary>
+        /// <returns>The pid of the current process.</returns>
+        [DllImport("libc",
+            EntryPoint = "getpid",
+            CallingConvention = CallingConvention.Cdecl,
+            CharSet = CharSet.Ansi,
+            SetLastError = true)]
```
Comment (iSazonov) [inline src/powershell/Program.cs]: We can remove the last two unused arguments.

File: src/powershell/Program.cs [hunk 26]
```diff
@@ -19,7 +63,433 @@ public sealed class ManagedPSEntry
...
+        /// </summary>
+        /// <param name="path">The path to the executable to exec.</param>
+        /// <param name="args">
+        /// The arguments to send through to the executable.
+        /// Array must have its final element be null.
+        /// </param>
+        /// <returns>
+        /// An exit code if exec failed, but if successful the calling process will be overwritten.
+        /// </returns>
+        [DllImport("libc",
```
Comment (iSazonov) [inline src/powershell/Program.cs]: Please use const for "libc".

File: src/powershell/Program.cs [hunk 27]
```diff
@@ -19,7 +63,433 @@ public sealed class ManagedPSEntry
...
+            {
+                Environment.SetEnvironmentVariable(LOGIN_ENV_VAR_NAME, null);
+                return;
+            }
+
+            bool isLinux = RuntimeInformation.IsOSPlatform(OSPlatform.Linux);
+
+            // The first byte (ASCII char) of the name of this process, used to detect '-' for login
+            byte procNameFirstByte;
+            // The path to the executable this process was started from
```
[the remark this answers is not in the document]
Comment (ExE-Boss) [reply src/powershell/Program.cs]:
```suggestion

            // The path to the executable this process was started from
```

File: src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx [hunk 28]
```diff
@@ -131,8 +131,8 @@ Type 'help' to get help.</value>
                   [-ConfigurationName &lt;string&gt;] [-CustomPipeName &lt;string&gt;]
                   [-EncodedCommand &lt;Base64EncodedCommand&gt;]
                   [-ExecutionPolicy &lt;ExecutionPolicy&gt;] [-InputFormat {Text | XML}]
-                  [-Interactive] [-LoadProfile] [-MTA] [-NoExit] [-NoLogo] [-NonInteractive] [-NoProfile]
-                  [-OutputFormat {Text | XML}]  [-SettingsFile &lt;filePath&gt;] [-STA] [-Version]
+                  [-Interactive] [-Login] [-MTA] [-NoExit] [-NoLogo] [-NonInteractive] [-NoProfile]
```
Comment (SteveL-MSFT) [inline src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx]: This needs to be updated to reflect that `-Login` needs to be first

File: src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx [hunk 29]
```diff
@@ -293,10 +293,11 @@ All parameters are case-insensitive.</value>
     Present an interactive prompt to the user. Inverse for NonInteractive
     parameter.
 
--LoadProfile | -l
+-Login | -l
 
-    Load the PowerShell profiles. This is the default behavior even if this is
-    not specified.
+    On Linux and macOS, starts PowerShell as a login shell,
```
Comment (SteveL-MSFT) [inline src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx]: This needs to be updated to reflect that -Login needs to be first

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]
You'll probably also need to update your docs PR to reflect that `-l` must be first

File: src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx (hunk 28 above)
Comment (rjmholt) [reply src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx]: What's the best way to reflect that here?

Comment (daxian-dbw) [reply src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx]: Ignore the alphabetic order and move [-Login] to the first one.

File: src/powershell/Program.cs [hunk 30]
```diff
@@ -19,7 +63,433 @@ public sealed class ManagedPSEntry
...
+            string pwshPath;
+
+            // On Linux, we can simply use the /proc filesystem
+            if (isLinux)
```
[the remark this answers is not in the document]
Comment (daxian-dbw) [reply src/powershell/Program.cs]: Given we are planning to move most of this method into native code, I wouldn't bother to refactor this code for now.

File: src/powershell/Program.cs (hunk 25 above)
Comment (daxian-dbw) [reply src/powershell/Program.cs]: `CharSet.Ansi` maybe be default on Unix platform, which I don't know for sure. But I think `SetLasterror = true` is needed if you are calling `GetLastWin32Error()` after P/Invoke.

**Comment by daxian-dbw** [comment]
@SteveL-MSFT Can you please take another look to see if you are OK with the updates?

**Review by SteveL-MSFT — APPROVED** [review]

**Comment by anmenaga** [comment]
No blocking issues; merging so it would get into next release.

File: src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx (hunk 28 above)
Comment (rjmholt) [reply src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx]: Ok, mindful that we use the same syntax-description syntax for both `pwsh.exe` and cmdlets, but cmdlets aren't parameter-order sensitive. OTOH, there are already (undocumented) order-sensitive parameters in `pwsh.exe`.

Comment (ExE-Boss) [reply src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx]: That would be `-Interactive` and `-NonInteractive` (the first one is needed because of Unix, where non‑interactive is the default by convention)
