### PR TITLE
Fix infinite loop in variable type inference

### LINKED ISSUE #25205: Latest PowerShell build from main crashes on property completion
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [x] Search the existing issues.
- [x] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [x] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Tab complete following line:
```powershell
$x = Get-Random; $x = $x.Where{$_.
```

### Expected behavior

```console
Should not crash.
```

### Actual behavior

```console
PowerShell process abruptly terminates.
```

### Partial call-stack

```console
   at System.Management.Automation.TypeInferenceVisitor.GetExpressionType(System.Management.Automation.Language.ExpressionAst, Boolean)
   at System.Management.Automation.TypeInferenceVisitor.InferTypesFrom(System.Management.Automation.Language.MemberExpressionAst)
   at System.Management.Automation.TypeInferenceVisitor.InferTypeFrom(System.Management.Automation.Language.VariableExpressionAst, System.Collections.Generic.List`1<System.Management.Automation.PSTypeName>)
   at System.Management.Automation.TypeInferenceVisitor.System.Management.Automation.Language.ICustomAstVisitor.VisitVariableExpression(System.Management.Automation.Language.VariableExpressionAst)
   at System.Management.Automation.TypeInferenceVisitor.InferTypeFrom(System.Management.Automation.Language.VariableExpressionAst, System.Collections.Generic.List`1<System.Management.Automation.PSTypeName>)
   at System.Management.Automation.TypeInferenceVisitor.System.Management.Automation.Language.ICustomAstVisitor.VisitVariableExpression(System.Management.Automation.Language.VariableExpressionAst)
   at System.Management.Automation.AstTypeInference.InferTypeOf(System.Management.Automation.Language.Ast, System.Management.Automation.TypeInferenceContext, System.Management.Automation.TypeInferenceRuntimePermissions)
   at System.Management.Automation.CompletionCompleters.CompleteMember(System.Management.Automation.CompletionContext, Boolean, Int32 ByRef)
   at System.Management.Automation.CompletionAnalysis.GetResultHelper(System.Management.Automation.CompletionContext, Int32 ByRef, Int32 ByRef)
   at System.Management.Automation.CompletionAnalysis.GetResults(System.Management.Automation.PowerShell, Int32 ByRef, Int32 ByRef)
   at System.Management.Automation.CommandCompletion.CompleteInputImpl(System.Management.Automation.Language.Ast, System.Management.Automation.Language.Token[], System.Management.Automation.Language.IScriptPosition, System.Collections.Hashtable)
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Type, System.String, Int32, System.Collections.Hashtable)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[[System.__Canon, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Runtime.CompilerServices.CallSite, System.__Canon, System.__Canon, Int32, System.__Canon)
   at System.Management.Automation.Interpreter.DynamicInstruction`5[[System.__Canon, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.Interpreter.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[[System.__Canon, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon)
   at System.Management.Automation.PSScriptCmdlet.RunClause(System.Action`1<System.Management.Automation.Language.FunctionContext>, System.Object, System.Object)
   at System.Management.Automation.CommandProcessorBase.Complete()
   at System.Management.Automation.CommandProcessorBase.DoComplete()
   at System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(System.Management.Automation.CommandProcessorBase)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   at System.Threading.Thread+StartHelper.RunWorker()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.6.0-preview.3
PSEdition                      Core
GitCommitId                    7.6.0-preview.3-50-geef334de1b0f648512859bd032356f9c8df7cb91
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Image

### PR DESCRIPTION
**Pull request by MartinGC94**
# PR Summary
Fixes a crash due to an infinite loop when inferring the type of a variable that is being reused, like here: `$x = Get-Random; $x = $x.Where{$_}` where the last assignment of `$x` was considered the `$x.Where...` statement instead of `Get-Random`.

## PR Context
Fixes https://github.com/PowerShell/PowerShell/issues/25205
Regression was added in https://github.com/PowerShell/PowerShell/pull/19830 and https://github.com/PowerShell/PowerShell/pull/21143

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
  - [X] None
  - **OR**
  - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
    - [ ] Experimental feature name(s): 
- **User-facing changes**
  - [X] Not Applicable
  - **OR**
  - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
  - [ ] N/A or can only be tested interactively
  - **OR**
  - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
  - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
  - **OR**
  - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
    - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
      - [ ] Issue filed: 
    - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
      - [ ] Issue filed: 
    - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
      - [ ] Issue filed: 
    - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
      - [ ] Issue filed:

### CODE REVIEW

**Comment by iSazonov** [comment]
@MartinGC94 I had a lot of doubts about this approach. On the one hand, it is very tempting to have it, users get useful features when editing scripts. On the other hand, this approach has many problems. This code is difficult to understand, has limitations in its capabilities, and most importantly, it is almost impossible to cover it with exhaustive tests. I expected users to report problems, but it turned out to be even worse - the first message was about a crash.

So I think we should revert these two PRs and use a different approach to realize these opportunities.
I think it is more correct to use the already used approach based on "safe evaluating".

**Comment by MartinGC94** [comment]
@iSazonov I don't understand what you mean about the old code being based on "safe evaluating".  
The old code was also finding and analyzing relevant asts, the only difference is that I use a custom visitor while the old approach used an AstSearcher. However, it's not like the custom visitor is fundamentally less safe than the old approach. I managed to make a similar infinite loop bug when updating the type inference for `$_` in switch statements: https://github.com/PowerShell/PowerShell/issues/21221 and here I used the old loop approach.
I'm also using a very similar approach in the variable completion code and that has been running fine since June 2023: https://github.com/PowerShell/PowerShell/pull/19595

I think it would be a mistake to completely abandon a perfectly fine way to handle type inference for variables just because of one mistake that happened to cause a crash.

**Comment by iSazonov** [comment]
@MartinGC94 It's not just a single mistake or that this approach has been used before. The problem is how to prove the correctness of this code - although we added a lot of tests, we did not see this problem. 
Moreover, using this approach in the past does not guarantee that it is the best one.

I have no intention of forcing you to rewrite all the code in this feature, I'm just expressing my opinion and I feel that the code is becoming more complex, although it was originally conceived as a simplified workaround that works on older computers twenty years ago. Now we have more powerful computers (and besides, we prefer the IDE to the command line). That's why I keep coming back to the idea that maybe it's time to do these calculations in a more advanced way.

**Comment by MartinGC94** [comment]
@iSazonov What do you mean with safe eval and more powerful computers? We can't just execute all the previous statements to get the actual value because those statements could have side effects. A quick example would be: `$VM = New-VM; $VM.<Tab>`. where tab completing obviously shouldn't result in a new VM being created every time.
Static analysis that determines what command set a value, and then checking the possible output from that command seems like the only reasonable way to do this, but if you can think of a better way then feel free to share it.

File: src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs [hunk 1]
```diff
@@ -2930,7 +2930,7 @@ private sealed class VariableAssignmentVisitor : AstVisitor2
 
             private void SetLastAssignment(Ast ast, bool enumerate = false, bool redirectionAssignment = false)
             {
-                if (LastAssignmentOffset < ast.Extent.StartOffset)
+                if (LastAssignmentOffset < ast.Extent.StartOffset && !VariableTarget.Extent.IsWithin(ast.Extent))
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs:2933]: Have we the same issue in next method SetLastAssignmentType?

Comment (MartinGC94) [reply src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs:2933]: My initial thought was no because it's only used for variable redirection and the OutVar parameters in commands so there was no fear of infinite loops. However, for the sake of correctness I've also fixed that so it excludes variables assigned like that when inferring a variable inside the commandAst as you wouldn't be able to use it there anyway.

**Comment by kborowinski** [comment]
@MartinGC94 Here are my 2 cents. I'm a heavy terminal user, and the enhancements you've delivered have significantly improved my experience. I understand Ilya's point about proceeding with care, but from my perspective, the advantages are well worth it—even if minor bugs pop up along the way.

File: src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs (hunk 1 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs:2933]: Since it is not related to infinite loop please move the commit to new PR.

Comment (daxian-dbw) [inline src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs:2933]: @MartinGC94 Could you please add a comment to explain why we need the `!VariableTarget.Extent.IsWithin(ast.Extent)` part to make it easier to understand? I think it'd be good to include the example `$x = Get-Random; $x = $x.Where{$_.<tab>}` in the comment. Thanks!

**Review by daxian-dbw — APPROVED** [review]
LGTM

**Review by iSazonov — APPROVED** [review]
