### PR TITLE
Set the output encoding to [Console]::OutputEncoding for native commands

### LINKED ISSUE #10789: [Console]::OutputEncoding doesn't work to parse exe with unicode output
# Steps to reproduce
I have a Windows executable that produces unicode (utf-16) output. In PowerShell 5.1, I can set the [Console]::OutputEncoding property so the output of that command gets correctly interpreted. On PowerShell Core 6.2.3, that doesn't appear to work.

I've also tried setting [Console]::InputEncoding and $OutputEncoding, but the problem persists.

For example, I use the wsl.exe binary here, so this should repro on any system that has the Windows Subsystem for Linux installed.

```powershell
[Console]::OutputEncoding = [System.Text.Encoding]::Unicode
wsl.exe --list -v | ForEach-Object { $_ }
```

# Expected behavior

```none
PS C:\Users\svgroot> [Console]::OutputEncoding = [System.Text.Encoding]::Unicode
PS C:\Users\svgroot> wsl.exe --list -v | ForEach-Object { $_ }
  NAME            STATE           VERSION
* Ubuntu          Stopped         2
  Ubuntu-18.04    Stopped         2
  Alpine          Stopped         1
```

# Actual behavior

```none
PS C:\Users\svgroot> [Console]::OutputEncoding = [System.Text.Encoding]::Unicode
PS C:\Users\svgroot> wsl.exe --list -v | ForEach-Object { $_ }
    N A M E                         S T A T E                       V E R S I O N

 *   U b u n t u                     S t o p p e d                   2

     U b u n t u - 1 8 . 0 4         S t o p p e d                   2

     A l p i n e                     S t o p p e d                   1
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.19001
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

This is a regression from Windows PowerShell due to a breaking change in .NET Core.  If you don't explicitly set `StandardOutputEncoding`, on .NET Core it defaults to the current code page.  Previously, it defaulted to `Console.OutputEncoding`.  Fix is to restore Windows PowerShell behavior by explicitly setting `StandardOutputEncoding` and `StandardErrorEncoding` to use `Console.OutputEncoding`.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/10789

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

File: src/System.Management.Automation/engine/NativeCommandProcessor.cs [hunk 1]
```diff
@@ -1101,11 +1101,13 @@ private ProcessStartInfo GetProcessStartInfo(bool redirectOutput, bool redirectE
                 if (redirectOutput)
```
Comment (PoshChan) [inline src/System.Management.Automation/engine/NativeCommandProcessor.cs]: @SteveL-MSFT, your last commit had 2 failures in `PowerShell-CI-windows`
TestAppDomainProcessExitEvenHandlerNotLeaking
```powershell
Assert.DoesNotContain() Failure
Found:    (filter expression)
In value: Delegate[] [EventHandler { Method = Void DisposeOnShutdown(System.Object, System.EventArgs), Target = null }, EventHandler { Method = Void CurrentDomain_ProcessExit(System.Object, System.EventArgs), Target = null }]
   at PSTests.Sequential.RunspaceTests.TestAppDomainProcessExitEvenHandlerNotLeaking() in D:\a\1\s\test\xUnit\csharp\test_Runspace.cs:line 127
```
Resources strings in System.Management.Automation (was -ResGen used with Start-PSBuild).'ParserStrings' should be an available type and the strings should be correct
```powershell
You cannot call a method on a null-valued expression.
at <ScriptBlock>, D:\a\1\s\test\powershell\engine\ResourceValidation\TestRunner.ps1: line 63
63:                     $resourceStringToCheck = $resourceType.GetProperty($inResource.name,$bindingFlags).GetValue(0)

```

**Comment by SteveL-MSFT** [comment]
@PoshChan  please retry windows

**Comment by PoshChan** [comment]
@SteveL-MSFT, successfully started retry of `PowerShell-CI-Windows`

File: src/System.Management.Automation/engine/NativeCommandProcessor.cs (hunk 1 above)
Comment (PoshChan) [inline src/System.Management.Automation/engine/NativeCommandProcessor.cs]: @SteveL-MSFT, your last commit had 2 failures in `PowerShell-CI-windows`
TestAppDomainProcessExitEvenHandlerNotLeaking
```powershell
Assert.DoesNotContain() Failure
Found:    (filter expression)
In value: Delegate[] [EventHandler { Method = Void DisposeOnShutdown(System.Object, System.EventArgs), Target = null }, EventHandler { Method = Void CurrentDomain_ProcessExit(System.Object, System.EventArgs), Target = null }]
   at PSTests.Sequential.RunspaceTests.TestAppDomainProcessExitEvenHandlerNotLeaking() in D:\a\1\s\test\xUnit\csharp\test_Runspace.cs:line 127
```
Resources strings in System.Management.Automation (was -ResGen used with Start-PSBuild).'ParserStrings' should be an available type and the strings should be correct
```powershell
You cannot call a method on a null-valued expression.
at <ScriptBlock>, D:\a\1\s\test\powershell\engine\ResourceValidation\TestRunner.ps1: line 63
63:                     $resourceStringToCheck = $resourceType.GetProperty($inResource.name,$bindingFlags).GetValue(0)

```

File: test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1 [hunk 2]
```diff
@@ -128,6 +128,18 @@ Describe "Native Command Processor" -tags "Feature" {
             $ps.Dispose()
         }
     }
+
+    It "OutputEncoding should be used" -Skip:(!$IsWindows -or !(Get-Command sfc.exe)) {
+
+        $originalOutputEncoding = [Console]::OutputEncoding
+        try {
+            [Console]::OutputEncoding = [System.Text.Encoding]::Unicode
+            sfc | Out-String | Should -Not -Match "`0"
```
Comment (iSazonov) [inline test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1]: sfc.exe requires elevated rights. Also I run the exe in latest build and I don't see problem.

Comment (vexx32) [reply test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1]: It does, but the error it generates running in non-privileged mode is still in Unicode so will still work for this test. 🙂

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
Interesting, should we do the same for [Console]::InputEncoding too?

**Comment by SteveL-MSFT** [comment]
@iSazonov discussed that with @JamesWTruher, it seems that the code later overwrites it with the unfortunately named `$OutputEncoding` (which represents the encoding of output that is input to a native command) so it didn't serve any purpose to change that code.

**Comment by Erhie** [comment]
is it not able to type
```
echo €
```
without problems
this dialog interrupts the normal text input:
```
cmdlet Write-Output at command pipeline position 1
Supply values for the following parameters:
InputObject[0]: €
InputObject[1]:
€
```
[See also](https://social.technet.microsoft.com/Forums/windowsserver/en-US/5915d51b-fcb5-43c8-b22d-fd9154aeda35/unicode-in-powershell-console?forum=winserverpowershell)
