### PR TITLE
Fix for #6976 -replace operator slowed down after adding scriptblock support

### LINKED ISSUE #6976: Combining the -replace operator with a lookbehind assertion slowed down by a factor of 30+ between v6.0.2 and v6.1.0-preview.2
Note: I have not tried to analyze whether the problem is in PowerShell or CoreFx; on the PowerShell side, new features were recently added to `-replace` - see #6029 - but I have no idea whether this symptom relates to that.

The problem appears to be specific to `-replace`; using `-match` does not exhibit the symptom.

Steps to reproduce
------------------

Run the following command line:

* first on v6.0.2 (the current stable release as of this writing).

* then on v6.1.0-preview.2 (the current preview release).

```powershell
$arr =  (, 'fooo') * 1e6; (Measure-Command { $arr -replace '(?<=.{3}).+' }).TotalSeconds
```

Expected behavior
-----------------

Similar timings.

Actual behavior
---------------

Here are sample timings, in seconds, from a Windows 10 VM:

```none
# v6.0.2
1.8444752

# v6.1.0-preview.2
# !! more than 30 times slower
61.5428622
```

Environment data
----------------

```powershell
PowerShell Core v6.0.2
PowerShell Core v6.1.0-preview.2
```

### PR DESCRIPTION
**Pull request by BrucePay**
## PR Summary

Fix #6976.

The performance of `-replace` was greatly reduced when scriptblock support was added. This is because of the way the code selected what type of replacement to do. In the old code, the first choice was string. In the modified code, the last choice was string and an earlier clause used `TryConvertTo()` to see if the substitution object was (or could be transformed into) a `MatchEvaluator` object. It was this (very expensive) call to `TryConvertTo()` that was slowing everything down. I added a clause for strings (the most common case) to the beginning of the switch statement so it's fast again. I also added a call to `PSObject.Base()` to make sure the test for strings is correct.  

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by daxian-dbw — APPROVED** [review]
LGTM.

File: src/System.Management.Automation/engine/lang/parserutils.cs [hunk 1]
```diff
@@ -908,7 +908,7 @@ internal static object ReplaceOperator(ExecutionContext context, IScriptExtent e
                     pattern = rList[0];
                     if (rList.Count > 1)
                     {
-                        substitute = rList[1];
+                        substitute = PSObject.Base(rList[1]);
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/lang/parserutils.cs]: Could you please add a comment why it is needed? what we break without this?

Comment (BrucePay) [reply src/System.Management.Automation/engine/lang/parserutils.cs]: Sure, This is actually a pretty fundamental operation in PowerShell. Anywhere you receive something of type `object`, you have to deal with the case where it might be wrapped in a `PSObject`. So before you can use it as `string` or `ScriptBlock`, you have to get the base object. The `PSObject.Base()` method encapsulates this operation. If it's passed a PSObject, it returns the core object otherwise it just returns the object.

**Comment by iSazonov** [comment]
LGTM.

**Review by lzybkr — APPROVED** [review]
