### PR TITLE
Set pipeline thread stack size

### LINKED ISSUE #4268: "call depth overflow" exception in Powershell scripts on Mac
Some of of my PowerShell scripts that I run on Mac failed with the following exception:
"The script failed due to call depth overflow."
After some investigation, I came to the conclusion that the allow call depth in PowerShell v6.0 alpha,
is smaller than the defined in PowerShell v5.0 (which I find is 100).
Could you change or increase in PowerShell for Unix that fixed call depth to be at least 1000?

### PR DESCRIPTION
**Pull request by iSazonov**
## PR Summary

Fix #4268 
Overlap #5927 (see PowerShell Committee conclusion)

Set default stack size in 10 MB for local pipeline threads.

Each platform uses different default for the thread stack size:
      - Windows 2 MB
      - Linux   8 Mb
      - MacOs   512 KB
 
We should use the same default for all platforms to get predictable behavior.

## PR Checklist

Note: Please mark anything not applicable to this PR `NA`.

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [x] Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] User facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [ ] Issue filed - Issue link:
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
    - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.

### CODE REVIEW

File: src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs [hunk 1]
```diff
@@ -152,12 +161,12 @@ protected override void StartPipelineExecution()
...
                         // No ApartmentState/ThreadStackSize In CoreCLR
-                        Thread invokeThread = new Thread(new ThreadStart(this.InvokeThreadProc));
+                        Thread invokeThread = new Thread(new ThreadStart(this.InvokeThreadProc), DefaultPipelineStackSize);
                         SetupInvokeThread(invokeThread, true);
 #else
                         //Start execution of pipeline in another thread
                         // 2004/05/02-JonN Specify maxStack parameter
-                        Thread invokeThread = new Thread(new ThreadStart(this.InvokeThreadProc), MaxStack);
+                        Thread invokeThread = new Thread(new ThreadStart(this.InvokeThreadProc), DefaultPipelineStackSize);
                         SetupInvokeThread(invokeThread, true);
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs]: It's better to change it to:
```
//Start execution of pipeline in another thread
Thread invokeThread = new Thread(new ThreadStart(this.InvokeThreadProc), DefaultPipelineStackSize);
SetupInvokeThread(invokeThread, true);

#if !CORECLR
ApartmentState apartmentState;
...
#endif
```

File: src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs [hunk 2]
```diff
@@ -1219,25 +1179,25 @@ protected override
...
     {
         /// <summary>
-        /// Creates the worker thread and waits for it to be ready
+        /// Creates the worker thread and waits for it to be ready.
         /// </summary>
 #if CORECLR
         internal PipelineThread()
         {
-            _worker = new Thread(WorkerProc);
+            _worker = new Thread(WorkerProc, LocalPipeline.DefaultPipelineStackSize);
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs]: nit: maybe use `DefaultPipelineStackSize` too, just like in rest of the places.

**Review by daxian-dbw — CHANGES_REQUESTED** [review]

File: src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs (hunk 1 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs]: Fixed.

File: src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs (hunk 2 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs]: I don't understand your request - use `DefaultPipelineStackSize` instead of `LocalPipeline.DefaultPipelineStackSize`? - but it is another class.

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs]: Ah, never mind, I saw you changed the `DefaultPipelineStackSize` in the below method to `LocalPipeline.DefaultPipelineStackSize`.

**Review by daxian-dbw — APPROVED** [review]

File: src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs [hunk 3]
```diff
@@ -20,6 +20,15 @@ namespace System.Management.Automation.Runspaces
...
     internal sealed class LocalPipeline : PipelineBase
     {
+        // Default stack size in bytes for local pipeline threads.
+        //
+        // Each platform uses different default for the thread stack size:
+        //      - Windows 2 MB
+        //      - Linux   8 Mb
+        //      - MacOs   512 KB
+        // We should use the same default for all platforms to get predictable behavior.
+        internal const int DefaultPipelineStackSize = 10_000_000;
```
Comment (SteveL-MSFT) [inline src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs]: It may be worthwhile to add a comment that the 10MB default is inherited from Windows PowerShell

**Review by SteveL-MSFT — DISMISSED** [review]

**Comment by iSazonov** [comment]
@daxian-dbw Thanks for fast review and help!
