### PR TITLE
Don't add trailing spaces to last column when using Format-Table

### LINKED ISSUE #5532: When copying output to the clipboard on macOS, output is padded to 80 columns wide with whitespace
Steps to reproduce
------------------
Install PowerShell on macOS
Open a new PowerShell instance
Do something that causes text to be output to the terminal
Copy and paste this text into somewhere else, e.g. a text editor or an email.
There is extraneous whitespace at the end of every line to pad it out to the width of my Terminal window, which is by default 80 columns.

Expected behavior
-----------------
It is expected that the text output in the Terminal will not have extra whitespace at the end of each and every line.

Actual behavior
---------------
Output is padded to the width of the Terminal window.
e.g. if you look at the output for $PSVersionTable below, copy and paste it into a text editor and you will notice that every line is 150 characters long, padded out with the space character. My Terminal window was 150 characters wide so that it could fit in the output for the OS line without truncating it.

Environment data
----------------
```
PS /Users/kai> $PSVersionTable                                                                                                                        

Name                           Value                                                                                                                 
----                           -----                                                                                                                 
PSVersion                      6.0.0-rc                                                                                                              
PSEdition                      Core                                                                                                                  
GitCommitId                    v6.0.0-rc                                                                                                             
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64        
Platform                       Unix                                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                                   
SerializationVersion           1.1.0.1                                                                                                               
WSManStackVersion              3.0                                                                                                                   
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
Separate fixes for the header and the data rows.  If it's the last column, don't add trailing padding.

Also fixed some Format-Table tests that were `Pending` but the issue was closed.

One side-effect is that using `out-file -width` you don't get the padding on the right most column which seems fine as the parameter is for limiting the width rather than ensuring the width.  But it is a breaking change.

Fixes https://github.com/PowerShell/PowerShell/issues/5532

### CODE REVIEW

**Comment by iSazonov** [comment]
I think we should be more flexible - while we trim trailing whitespaces by default the `out-file -width` (and maybe `Format-Table -Width`) should be padding.

**Comment by SteveL-MSFT** [comment]
I'll bring this up at the Committee meeting today.  I think it depends on what `-width` means.  Does it mean exact width or max width.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and `-width` should be maximum width only.  This is consistently with behavior today such as:

```powershell
"hello" | out-file -width 100 -path .\hello.txt
```
Also, formatting has not been guaranteed to be a specific format, so this is not a breaking change.

File: src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs [hunk 1]
```diff
@@ -248,11 +248,18 @@ private string[] GenerateTableRow(string[] values, int[] alignment, DisplayCells
...
 
             StringCollection[] scArray = new StringCollection[validColumnCount];
+            bool addPadding = true;
             for (int k = 0; k < scArray.Length; k++)
             {
+                // for the last column, don't pad it with trailing spaces
+                if (k == scArray.Length-1)
+                {
+                    addPadding = false;
+                }
```
Comment (iSazonov) [inline src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs]: See my comment below.

File: src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs [hunk 2]
```diff
@@ -339,8 +349,15 @@ private string GenerateRow(string[] values, int[] alignment, DisplayCells dc)
...
             StringBuilder sb = new StringBuilder();
 
+            bool addPadding = true;
             for (int k = 0; k < _si.columnInfo.Length; k++)
             {
+                // don't pad the last column
+                if (k == _si.columnInfo.Length -1)
+                {
+                    addPadding = false;
+                }
```
[the remark this answers is not in the document]
Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs]: I think for outputting table which is mostly an interactive experience, I don't think performance has a big implication here.

[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs]: We have CPU spikes mainly because of the reoutput of symbols.

Closed.

**Comment by adityapatwardhan** [comment]
@daxian-dbw @JamesWTruher @anmenaga Can you have a look?

**Comment by adityapatwardhan** [comment]
@daxian-dbw @JamesWTruher @anmenaga  ping ...

**Comment by adityapatwardhan** [comment]
@daxian-dbw @JamesWTruher @anmenaga ping ...

File: test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1 [hunk 3]
```diff
@@ -138,42 +138,32 @@ Describe "Format-Table DRT Unit Tests" -Tags "CI" {
...
-				$result = $p|Format-Table -Property "foo","bar"|Out-String
-				$result | Should BeNullOrEmpty
+				$result = $p | Format-Table -Property "foo","bar" -Force | Out-String
+				$result.Replace(" ","").Replace([Environment]::NewLine,"") | Should BeExactly "foobar------"
 		}
 
-		#pending on issue#900
-		It "Format-Table with multiple line string for End-To-End should work" -pending{
+		It "Format-Table with multiple line string for End-To-End should work" {
 				$p = "Line1\nLine2"
```
Comment (JamesWTruher) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1]: shouldn't this be 
```
$p = "Line1`nLine2"
```
This looks like it was migrated incorrectly from c#

**Review by JamesWTruher — CHANGES_REQUESTED** [review]

File: test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1 (hunk 3 above)
Comment (SteveL-MSFT) [reply test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1]: Yes, the escaped newline is wrong, but I'm actually not sure what this test is supposed to be validating.  The multiline doesn't have an effect on format-table.  Is that the test?

**Comment by adityapatwardhan** [comment]
@JamesWTruher  Can you have another look?

File: test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1 (hunk 3 above)
Comment (JamesWTruher) [reply test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1]: I believe that is the test, but I'm having trouble reconciling the title of the test with the code. If we want to check multiple line strings in format-table, I see 2 tests which are interesting:
```
[pscustomobject]@{ foo = "line1`nline2"; bar = 2 }| format-table -prop foo,bar -wrap | out-string -str | where-object {$_}
foo   bar
---   ---
l1      1
l2
```
and
```
[pscustomobject]@{ foo = "line1`nline2"; bar = 2 }| format-table -prop foo,bar | out-string -str | where-object {$_}
foo   bar
---   ---
l1...   1
```
but I didn't go back and look at all the tests in this file to see if those cases are covered.
certainly it's not a blocking issue, and the test has some utility now as is

**Review by JamesWTruher — APPROVED** [review]
