### PR TITLE
Fix four issues for the WDAC logging feature

### LINKED ISSUE #20768: System lockdown / WDAC: Use of new audit-only mode prevents use of `[pscustomobject]` literals, behaves as if `ConstrainedLanguage` mode were in effect
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

If I understand correctly, the [new audit-only mode](https://learn.microsoft.com/en-us/powershell/scripting/learn/application-control?view=powershell-7.4#wdac-policy-auditing) - despite technically reporting `ConstrainedLanguage` via `$ExecutionContext.SessionState.LanguageMode` - is meant to be a _what-if_ constrained mode:

* In effect behave like `FullLanguageMode`, but _log_ operations that _would_ be prevented if `ConstrainedLanguage` mode were actually _enforced_.

However, with respect to `[pscustomobject]` literals that isn't the case: Their use _fails quietly_:

```powershell
#requires -RunAsAdministrator

# Simulate entering audit-only system lockdown
[Environment]::SetEnvironmentVariable("__PSLockdownPolicy", "0x80000008", 'Machine')

# Launch a new process that tries to use a [pscustomobject] literal
Start-Process -Wait pwsh '-NoProfile -C [pscustomobject] @{ foo = 1 } | Out-Host; pause'

# Turn lockdown back off
[Environment]::SetEnvironmentVariable("__PSLockdownPolicy", $null, 'Machine')
```

The **workaround**  is to simply execute `$ExecutionContext.SessionState.LanguageMode = 'FullLanguage'` in a session that was started in audit mode. (Is the ability to do so by design?)
However, even that doesn't work in other use cases: see
* #20785

As an aside:

* Arguably, `[pscustomobject]` literals should also work in true `ConstrainedLanguage` mode, but currently do not - see #20767

### Expected behavior

A `[pscustomobject]` instance should be constructed and output.

### Actual behavior

No output, i.e. the expression _fails quietly_ (but may be _logged_ - haven't verified that).

### Error details

_No response_

### Environment data

```powershell
PowerShell 7.4.0 on W11 22H2
```

### Visuals

_No response_

### LINKED ISSUE #20785: Constrained Language Audit mode breaks az.resources
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Previously, in 7.3.9, I could use the Get-AzADGroup cmdlet from az.resources. This now fails in 7.4.0, logging the following warning to the event log, apparently due to Constrained Language mode. I have read the notes at https://learn.microsoft.com/en-us/powershell/scripting/learn/application-control?view=powershell-7.4#wdac-policy-enforcement but my understanding is that this is in warning-only mode, so not sure why this breaks.

Confirm 7.4.0 works fine where WDAC doesn't get involved. In both cases, $ExecutionContext.SessionState.LanguageMode reads as "FullLanguage" but with WDAC, we get the below error.

Can also confirm that rolling back to 7.3.9, Get-AZADGroup works fine again.

### Expected behavior

```console
PS > get-azadgroup -displayname azurevirtualdesktop

DisplayName         Id                 MailNickname Description
-----------         --                 ------------ -----------
AzureVirtualDesktop 4b5fc7cb.....745ff 61b71d76-7   Azure Virtual Desktop users
```

### Actual behavior

```console
PowerShell 7.4.0
[Constrained Language AUDIT Mode : No Restrictions]
PS > ipmo az.resources

PS> get-azadgroup -DisplayName azurevirtualdesktop
ParentContainsErrorRecordException: ....\Documents\PowerShell\Modules\az.resources\6.12.0\MSGraph.Autorest\exports\ProxyCmdletDefinitions.ps1:3532
Line |
3532 |          $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvoc …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "GetSteppablePipeline" with "1" argument(s): "The expression after '&' in a pipeline element
     | produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
     | object."

PS > $ExecutionContext.SessionState.LanguageMode = 'FullLanguage'

PS > get-azadgroup -DisplayName azurevirtualdesktop
ParentContainsErrorRecordException: ....\Documents\PowerShell\Modules\az.resources\6.12.0\MSGraph.Autorest\exports\ProxyCmdletDefinitions.ps1:3532
Line |
3532 |          $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvoc …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "GetSteppablePipeline" with "1" argument(s): "The expression after '&' in a pipeline element
     | produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
     | object."
```
```


### Error details

```console
From PowershellCore/Operational:

Error Message = Exception calling "GetSteppablePipeline" with "1" argument(s): "The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object."
Fully Qualified Error ID = RuntimeException


Context:
        Severity = Warning
        Host Name = ConsoleHost
        Host Version = 7.4.0
        Host ID = e0d32791-7e3c-44a6-bbb3-c46817f36700
        Host Application = C:\Program Files\PowerShell\7\pwsh.dll
        Engine Version = 7.4.0
        Runspace ID = 33297d30-ce4f-4807-ba84-84f0aa1b96de
        Pipeline ID = 17
        Command Name = 
        Command Type = 
        Script Name = ....\Documents\PowerShell\Modules\az.resources\6.12.0\MSGraph.Autorest\exports\ProxyCmdletDefinitions.ps1
        Command Path = 
        Sequence Number = 10
        Connected User = 
        Shell ID = Microsoft.PowerShell


User Data:
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #20785 
Fix #20768

Address 4 issues for the WDAC logging feature:
- Hashtable-to-object conversion checking was wrong;
- A call to `GetPowerShell` and a call to `GetSteppablePipeline` show different behaviors when it's truly in Constrained mode, but the Audit feature didn't cover them.
- For the property/method access check in binder, fix the target name to also capture the target when `targetValue` is not a `Type` object.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

**Comment by iSazonov** [comment]
@daxian-dbw Could you please look #20910 why you are in the context?

File: src/System.Management.Automation/engine/LanguagePrimitives.cs [hunk 1]
```diff
@@ -3986,26 +3986,8 @@ internal ConvertViaNoArgumentConstructor(ConstructorInfo constructor, Type type)
...
-                            // The method invocation is disabled for "Hashtable to Object conversion" (Win8:649519), but we need to keep it enabled for New-Object for compatibility to PSv2
-                            IDictionary properties = valueToConvert as IDictionary;
-                            SetObjectProperties(result, properties, resultType, CreateMemberNotFoundError, CreateMemberSetValueError, enableMethodCall: false);
-                        }
-
-                        typeConversion.WriteLine("Constructor result: \"{0}\".", result);
-                    }
-                    else
+                    bool canProceedWithConversion = ecFromTLS == null || (ecFromTLS.LanguageMode == PSLanguageMode.FullLanguage && !ecFromTLS.LanguageModeTransitionInParameterBinding);
+                    if (!canProceedWithConversion)
```
Comment (SteveL-MSFT) [inline src/System.Management.Automation/engine/LanguagePrimitives.cs:3990]: this works, but reads a bit confusing since audit doesn't result in `canProceedWithConversion` but then does.  It may be less confusing for future readers to simply have the audit message written outside of this check and have this check include audit.

**Review by SteveL-MSFT — APPROVED** [review]
One non-blocking suggestion

File: src/System.Management.Automation/engine/remoting/client/RunspaceRef.cs [hunk 2]
```diff
@@ -94,7 +95,22 @@ private PSCommand ParsePsCommandUsingScriptBlock(string line, bool? useLocalScop
...
+                    inFullLanguage = true;
+                    SystemPolicy.LogWDACAuditMessage(
+                        context: context,
+                        title: RemotingErrorIdStrings.WDACGetPowerShellLogTitle,
+                        message: RemotingErrorIdStrings.WDACGetPowerShellLogMessage,
+                        fqid: "GetPowerShellMayFail",
+                        dropIntoDebugger: true);
+                }
+
+                bool isTrustedInput = !isConfiguredLoopback && inFullLanguage;
```
Comment (JamesWTruher) [inline src/System.Management.Automation/engine/remoting/client/RunspaceRef.cs:113]: I'm not sure about this - we're changing behavior with audit mode being enabled. Could you add a comment about why this is the right thing to do? If we're in CLM and because we're auditing now it's full language?

**Review by JamesWTruher — COMMENTED** [review]
just a couple of questions

File: src/System.Management.Automation/engine/LanguagePrimitives.cs (hunk 1 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/LanguagePrimitives.cs:3990]: Made a bit refactoring and add a comment to make it clearer.

[the remark this answers is not in the document]
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/LanguagePrimitives.cs:3990]: The Audit mode enables `ConstrainedLangaugeMode`, but it only logs the behavior difference resulted by this `ConstrainedLanguageMode` setting, without actually enforcing them. So, from the user's perspective, the script still runs in `FullLanguageMode`.

The exception originally at line 4021 will be thrown only if it is NOT running in `FullLanguageModule`, or it's in the transition from `ConstrainedLanguageMode` to `FullLanguageMode`. Both checks don't matter when it's in Audit mode, we should just log what would really happen in `ConstrainedLanguageMode`, but still allow the conversion to proceed.

File: src/System.Management.Automation/engine/remoting/client/RunspaceRef.cs (hunk 2 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/client/RunspaceRef.cs:113]: The Audit mode enables `ConstrainedLangaugeMode`, but it only logs the behavior difference resulted by this `ConstrainedLanguageMode` setting, without actually enforcing them. So, from the user's perspective, the script still runs in `FullLanguageMode`.

So here, if `context.LanguageMode == PSLanguageMode.ConstrainedLanguage` and we are in Audit, then we don't enforce the `ConstrainedLanguageMode`, but instead, assuming it's in `FullLanauge`. So, the user's script runs as if it's in the `FullLanguageMode`, but they receive events about what will/may not work in the real `ConstrainedLanguage`.

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/client/RunspaceRef.cs:113]: > we're changing behavior with audit mode being enabled.

Put it in another way, when in `Audit` mode, the script should behavior as if they are running in `FullLanguage` mode. We are not changing that behavior, but just logging what will/may fail in the real `ConstrainedLanguage` mode.

Comment (JamesWTruher) [reply src/System.Management.Automation/engine/remoting/client/RunspaceRef.cs:113]: I didn't understand that audit mode implies constrained language mode - do you think a comment explaining this should be placed here (or above)?

**Review by JamesWTruher — APPROVED** [review]

File: src/System.Management.Automation/engine/remoting/client/RunspaceRef.cs (hunk 2 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/client/RunspaceRef.cs:113]: A description about this should be put in the documentation of this Audit feature. I will check the documentation.

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/client/RunspaceRef.cs:113]: It's already in the documentation at https://learn.microsoft.com/en-us/powershell/scripting/learn/application-control?view=powershell-7.4#wdac-policy-auditing:
> In audit mode, PowerShell runs the untrusted scripts in **Constrained Language** mode without errors, but logs messages to the event log instead. The log messages describe what restrictions would apply if the policy was in Enforce mode.
