### PR TITLE
Filter completion for enum parameter against ValidateRange-attributes

### LINKED ISSUE #2849: ValidateRange should not allow iteration over invalid range values
Steps to reproduce
------------------
In any module that uses an Enum value to be passed. For example: -Type { Start, Stop, Pause} if you use the ValidateRange(Start, Stop) attribute tab completion will still cycle through -Type Pause too even though executing this would fail. It would be really cool if the tab completion didnt iterate over invalid ranges.

Expected behavior
-----------------
Tab completion would only iterate over { Start, Stop }

Actual behavior
---------------
It iterates over all enum values.

Environment data
----------------

```powershell
> $PSVersionTable

```

### PR DESCRIPTION
**Pull request by fflaten**
# PR Summary

Updates parameter completion for enums to exclude values not allowed by `ValidateRange`-attributes.

## PR Context

See [this comment](https://github.com/PowerShell/PowerShell/issues/17546#issuecomment-1165989939)

Fix #2849

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by fflaten** [comment]
Tested devbuild with vscode-powershell (stable). It also shows filtered values as expected.

**Comment by iSazonov** [comment]
I suggest to put enum value list and code to check range in ValidateRangeAttribute class.

**Comment by fflaten** [comment]
> I suggest to put enum value list and code to check range in ValidateRangeAttribute class.

I agree. Also just realized I forgot about rangekind.
Initially intended to reuse `ValidateElement()` with a try/catch, but it's currently protected. Any rules blocking me from making it internal?

**Comment by iSazonov** [comment]
I thinks really we need internal helper method in ValidateRangeAttribute to return a list of filtered strings for enum base type.

**Comment by fflaten** [comment]
> I thinks really we need internal helper method in ValidateRangeAttribute to return a list of filtered strings for enum base type.

Thanks. Better now?

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs [hunk 1]
```diff
@@ -1770,17 +1770,23 @@ internal static string ConcatenateStringPathArguments(CommandElementAst stringAs
             {
                 RemoveLastNullCompletionResult(result);
 
-                string enumString = LanguagePrimitives.EnumSingleTypeConverter.EnumValues(parameterType);
-                string separator = CultureInfo.CurrentUICulture.TextInfo.ListSeparator;
-                string[] enumArray = enumString.Split(separator, StringSplitOptions.RemoveEmptyEntries);
+                var enumValues = parameterType.GetEnumValues().Cast<Enum>().ToList();
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:1773]: I think we have no need to do such conversions again and again since we already have the values in TypeConverter hash and on other hand ValidateElement does the conversion too.
So I suggest add new helper in EnumSingleTypeConverter class and use it here (and there is another one more place in CompleteStatementFlags() where we can use it):
```c#
            internal static string[] GetEnumValues(Type enumType)
                => EnumSingleTypeConverter.GetEnumHashEntry(enumType).names;
```

Comment (fflaten) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:1773]: They don't have the same requirements unfortunately. `ValidateElement()` will cast to a common `_promotedType`. For `[ValidateRange(1,3)][ConsoleColor]$color` or `[ValidateRange([ConsoleColor]::Black,10)][ConsoleColor]$color` that will be `Int32` and not the enum-type, so we need to provide the `Enum` directly for the validation to work.

I can add a `Array GetEnumValues(Type enumType)` returning `GetEnumHashEntry(enumType).values`. Though it feels a bit wrong to add methods unrelated to conversion to `EnumSingleTypeConverter`. Is it that much faster than `Enum.GetValues(parameterType)` directly?

I can submit a separate code cleanup-PR for `CompleteStatementFlags()` to use a  `internal string[] GetEnumNames(Type)` helper if you'd like.

File: src/System.Management.Automation/engine/Attributes.cs [hunk 2]
```diff
@@ -1311,6 +1311,21 @@ private static Type GetCommonType(Type minType, Type maxType)
...
+        {
+            var result = new List<T>();
+            foreach (var value in elements)
+            {
+                try
+                {
+                    ValidateElement(value);
+                    result.Add(value);
+                }
+                catch { }
```
[the remark this answers is not in the document]
Comment (fflaten) [reply src/System.Management.Automation/engine/Attributes.cs:1325]: Yeah it didn't warrant duplicate code or a complete refactor (yet) 👍
I'll limit the catch to the expected `ValidationMetadataException` and add a comment to at least make the intention clear - it basically means "value not in range, ignore".

File: src/System.Management.Automation/engine/Attributes.cs [hunk 3]
```diff
@@ -1311,6 +1311,21 @@ private static Type GetCommonType(Type minType, Type maxType)
 
             return resultType;
         }
+
+        internal List<T> FilterElements<T>(IEnumerable<T> elements)
```
[the remark this answers is not in the document]
Comment (fflaten) [reply src/System.Management.Automation/engine/Attributes.cs:1315]: I'll rename to `GetValidatedElements` and add XML comment

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs (hunk 1 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:1773]: PowerShell is smart enough if we use right type:
```powershell
function ColorValidation {
   param(
      [ValidateRange([ConsoleColor]::Black, [ConsoleColor]::Gray)]
      [ConsoleColor]$color
   )
   Write-Output "Color validated!!!"
}

ColorValidation "Black"
ColorValidation "White"
```

Comment (fflaten) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs]: True, but it's a different scenario. In that demo, the arguments is already converted to enum-type before validation -> ValidateElement() can always compare ConsoleColor or int (converted if min/max is int or mixed type).

When calling it from the completer, we don't have that safeguard, so with mixed type min/max in the attribute, passing the string to `FilterElements()`->`ValidateElement()` would throw when trying to convert enum name string to `_promotedType` which is int in that case.

Anyhow, I've added a helper and cleanup up a bit. Not sure how to avoid the `.Cast<Enum>.ToList()` called once since the enum values are returned as `Array`. If possible, let me know 🙂 I appreciate the feedback so I may learn.

Comment (iSazonov) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs]: > When calling it from the completer, we don't have that safeguard, so with mixed type min/max in the attribute, passing the string to `FilterElements()`->`ValidateElement()` would throw when trying to convert enum name string to `_promotedType` which is int in that case.

Int? I wonder. Do you mean `ColorValidation 0<Tab>`? I don't think we have to worry about this scenario.

Comment (fflaten) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs]: Yes. Attribute ctor converts to a common type, ex.

```powershell
[ValidateRange]::new(1, [System.ConsoleColor]::DarkCyan).MaxRange.GetType() # int32 even though MaxRange arg was enum
```

So if you call `ValidateElement("Black")` on the attribute above it would throw in a inner call to `TryConvertTo()` when trying to convert to "Black" string to int32 (the calculated common type set in `_promotedType`). 

If the attribute was created with enum-type for both Min-/MaxRange the call would work, but technically the code above is allowed.

Comment (iSazonov) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs]: I don't understand why an user would specify int in the attribute. Enum is exactly what you need to use meaningful names instead of numbers.

Comment (fflaten) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs]: 100% agree.

It is intentionally supported though so this PR should be compatible with it, which it is atm. :) Might be because of `[ValidateRange(rangeKind)]` so you could allow only positive values in some advanced scenarios

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs [hunk 4]
```diff
@@ -1770,28 +1770,35 @@ internal static string ConcatenateStringPathArguments(CommandElementAst stringAs
             {
                 RemoveLastNullCompletionResult(result);
 
-                string enumString = LanguagePrimitives.EnumSingleTypeConverter.EnumValues(parameterType);
-                string separator = CultureInfo.CurrentUICulture.TextInfo.ListSeparator;
-                string[] enumArray = enumString.Split(separator, StringSplitOptions.RemoveEmptyEntries);
+                IList<Enum> enumValues = LanguagePrimitives.EnumSingleTypeConverter.GetEnumValues(parameterType).Cast<Enum>().ToList();
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:1773]: I still think we have no need to cast because ValidateElement parameter type is _object_.
Also we have no need to collect filtered list.
```suggestion
                IEnumerable enumValues = LanguagePrimitives.EnumSingleTypeConverter.GetEnumValues(parameterType);
```

File: src/System.Management.Automation/engine/Attributes.cs [hunk 5]
```diff
@@ -1311,6 +1311,29 @@ private static Type GetCommonType(Type minType, Type maxType)
...
+                    result.Add(el);
+                }
+                catch (ValidationMetadataException)
+                {
+                    // Element was not in range - drop
+                }
+            }
+
+            return result;
+        }
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/Attributes.cs:1336]:
```suggestion
        internal static IEnumerable GetValidatedElements(IEnumerable elementsToValidate)
        {
            foreach (var element in elementsToValidate)
            {
                try
                {
                    ValidateElement(element );
                    yield return element;
                }
                catch (ValidationMetadataException)
                {
                    // Element was not valid - drop
                }
            }
        }
```

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs [hunk 6]
```diff
@@ -1770,28 +1770,35 @@ internal static string ConcatenateStringPathArguments(CommandElementAst stringAs
...
+                // Exclude values not accepted by ValidateRange-attributes
+                foreach (ValidateArgumentsAttribute att in parameter.Parameter.ValidationAttributes)
+                {
+                    if (att is ValidateRangeAttribute rangeAtt)
+                    {
+                        enumValues = rangeAtt.GetValidatedElements(enumValues);
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:1779]: With my proposal above this can not compile - then define new variable.

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs (hunk 4 above)
Comment (fflaten) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:1773]: True. Just preferred generic in general to get a typed result in future use of this helper, but I don't currently depend on type so I'll drop it.

File: src/System.Management.Automation/engine/Attributes.cs (hunk 5 above)
Comment (fflaten) [reply src/System.Management.Automation/engine/Attributes.cs:1336]: `IList` was used to be explicit about order being kept (and initially `for`-loop), but will change. 👍

Assuming `static` was typo. 🙂

File: src/System.Management.Automation/engine/Attributes.cs [hunk 7]
```diff
@@ -1311,6 +1311,27 @@ private static Type GetCommonType(Type minType, Type maxType)
...
+                try
+                {
+                    ValidateElement(el);
+                }
+                catch (ValidationMetadataException)
+                {
+                    // Element was not in range - drop
+                    continue;
+                }
+                yield return el;
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/Attributes.cs:1332]:
```suggestion
                }

                yield return el;
```

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs [hunk 8]
```diff
@@ -1770,28 +1770,35 @@ internal static string ConcatenateStringPathArguments(CommandElementAst stringAs
             {
                 RemoveLastNullCompletionResult(result);
 
-                string enumString = LanguagePrimitives.EnumSingleTypeConverter.EnumValues(parameterType);
-                string separator = CultureInfo.CurrentUICulture.TextInfo.ListSeparator;
-                string[] enumArray = enumString.Split(separator, StringSplitOptions.RemoveEmptyEntries);
+                IEnumerable enumValues = LanguagePrimitives.EnumSingleTypeConverter.GetEnumValues(parameterType);
+                // Exclude values not accepted by ValidateRange-attributes
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:1774]:
```suggestion
                IEnumerable enumValues = LanguagePrimitives.EnumSingleTypeConverter.GetEnumValues(parameterType);

                                // Exclude values not accepted by ValidateRange-attributes
```

**Review by iSazonov — APPROVED** [review]

**Comment by fflaten** [comment]
Hi @adityapatwardhan . Any ETA on review?
Would be great it this would make 7.4 as LTS releases are deployed in enterprises.

**Comment by adityapatwardhan** [comment]
I will prioritize this for community day tomorrow.

**Review by adityapatwardhan — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
@fflaten thank you for your contribution!
