### PR TITLE
Fix parameter completion when script requirements fail

### LINKED ISSUE #4549: Parameter completion should work even when #requires fails
Steps to reproduce
------------------
In a non-elevated PowerShell, try to tab complete parameters to a script that looks like:

```powershell
#requires -RunAsAdministrator
param($ABC)
```

Expected behavior
-----------------
Completion works. Note that the current behavior is slightly useful as an indicator that the script won't run even after finishing the command line, but it is poor behavior in an editor that probably isn't running elevated.

Actual behavior
---------------
Completion fails silently

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.5
OS                             Microsoft Windows 10.0.16262
Platform                       Win32NT
```

### PR DESCRIPTION
**Pull request by MartinGC94**
# PR Summary
Allows tab completion for parameters to continue working when script requirements like `#requires -RunAsAdministrator` fail due to the current session not meeting the script requirements.

## PR Context
Fixes https://github.com/PowerShell/PowerShell/issues/4549

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by MartinGC94** [comment]
Looking at the test failures, I guess we can't just ignore those errors in every scenario. I assumed I could because Experimental and hidden param attributes are ignored.  
One solution could be to only ignore errors for type constraints but that won't help scenarios where scripts are using an attribute that hasn't been loaded yet.  
Are there any other solutions?

**Comment by iSazonov** [comment]
WG discussion tag.

On the one hand it makes sense to have more freedom with `#requires -RunAsAdministrator` or hidden scenarios for example, but on the other hand I don't see the point of doing this for types that are not loaded.

File: src/System.Management.Automation/engine/parser/Compiler.cs [hunk 1]
```diff
@@ -1807,7 +1807,15 @@ private static RuntimeDefinedParameter GetRuntimeDefinedParameter(ParameterAst p
...
                 var attributeAst = parameterAst.Attributes[index];
-                var attribute = attributeAst.GetAttribute();
+                Attribute attribute;
+                try
+                {
+                    attribute = attributeAst.GetAttribute();
+                }
+                catch (RuntimeException)
+                {
+                    continue;
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/parser/Compiler.cs:1817]: Since it is Compiler can this change a behavior of real script execution?

Comment (MartinGC94) [reply src/System.Management.Automation/engine/parser/Compiler.cs:1817]: I don't know. We need someone that is more familiar with the engine to answer that question.

**Comment by daxian-dbw** [comment]
@MartinGC94 Sorry for taking so long to review. Can you please resolve the conflicts for this PR?

**Comment by iSazonov** [comment]
@MartinGC94 Please resolve merge conflicts and rebase.

File: src/System.Management.Automation/engine/ExecutionContext.cs [hunk 2]
```diff
@@ -478,6 +478,11 @@ internal LocationGlobber LocationGlobber
         /// </summary>
         internal Dictionary<string, Assembly> AssemblyCache { get; private set; }
 
+        /// <summary>
+        /// Ignores script requirements that fail.
+        /// </summary>
+        internal bool IgnoreFailedScriptRequirements { get; set; }
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/ExecutionContext.cs:484]: This is an important internal structure, and I cannot accept adding a new property to it for the sake of a rare scenario in an interactive session.
I don't think it's worth it.
If you do not agree, then we must wait for the conclusion of the working group.

Comment (MartinGC94) [reply src/System.Management.Automation/engine/ExecutionContext.cs:484]: I think the reason why I went with a property was because otherwise I'd have to update a bunch of methods with an extra parameter. I'd have to take another look to know if I still think it's the best way all these years later, but what's the harm in adding an internal property? It's hard to imagine how it would break anything by simply being there.

Comment (iSazonov) [reply src/System.Management.Automation/engine/ExecutionContext.cs:484]: > what's the harm in adding an internal property?

It is out of completion code. I can't make a personal decision without the approval of MSFT team.
And as I said, this change is too much edge to make many changes in code. It's better to spend time on something more useful.

File: test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1 [hunk 3]
```diff
@@ -1659,6 +1659,27 @@ class InheritedClassTest : System.Attribute
         }
     }
 
+    Context "Script parameter completion" {
+        BeforeAll {
+            Setup -File -Path 'ScriptParamTabCompletionTest.ps1' -Content @'
+#requires -Modules ThisModuleDoesNotExist
```
Comment (iSazonov) [inline test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1:1665]: Original issue says about RunAsAdministrator. 
```suggestion
#requires -RunAsAdministrator
```
Since we run the test as regular user the test will check the original scenario. Will it pass?

Comment (MartinGC94) [reply test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1:1665]: Don't we run tests both with and without elevated permissions? But yes, we can change the test to RunAsAdministrator if you prefer.

File: src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs [hunk 4]
```diff
@@ -1198,13 +1198,18 @@ private bool PrepareCommandElements(ExecutionContext context, CommandParameterAs
             string commandName = null;
             try
             {
+                context.IgnoreFailedScriptRequirements = true;
                 processor = PrepareFromAst(context, out commandName) ?? context.CreateCommand(commandName, dotSource);
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs:1202]: I see PrepareFromAst() uses a flag `forCompletion`. Maybe do the same for `context.CreateCommand()`?

Comment (iSazonov) [reply src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs]: Yes, this can be merged. Only please review the last commit - many style issues.

File: src/System.Management.Automation/engine/CommandDiscovery.cs [hunk 5]
```diff
@@ -258,6 +258,7 @@ internal void AddSessionStateCmdletEntryToCache(SessionStateCmdletEntry entry, b
         /// </param>
         /// <param name="commandOrigin">Location where the command was dispatched from.</param>
         /// <param name="useLocalScope">
+        /// <param name="forCompletion">
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/CommandDiscovery.cs:261]: You insert new block to existing block. Please move below, add description and add closing part.

File: src/System.Management.Automation/engine/CommandDiscovery.cs [hunk 6]
```diff
@@ -271,22 +272,22 @@ internal void AddSessionStateCmdletEntryToCache(SessionStateCmdletEntry entry, b
...
-            CommandOrigin commandOrigin, bool? useLocalScope)
+            CommandOrigin commandOrigin, bool? useLocalScope, bool forCompletion = false)
         {
             CommandProcessorBase processor = null;
             CommandInfo commandInfo = LookupCommandInfo(commandName, commandOrigin);
 
             if (commandInfo != null)
             {
-                processor = LookupCommandProcessor(commandInfo, commandOrigin, useLocalScope, null);
+                processor = LookupCommandProcessor(commandInfo, commandOrigin, useLocalScope, null, forCompletion);
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/CommandDiscovery.cs:282]:
```suggestion
                processor = LookupCommandProcessor(commandInfo, commandOrigin, useLocalScope, null, forCompletion);

```

File: src/System.Management.Automation/engine/CommandDiscovery.cs [hunk 7]
```diff
@@ -340,12 +341,18 @@ private CommandProcessorBase CreateScriptProcessorForSingleShell(ExternalScriptI
...
         // #Requires -PSEdition
         // #Requires -Module
-        internal static void VerifyScriptRequirements(ExternalScriptInfo scriptInfo, ExecutionContext context)
+        internal static void VerifyScriptRequirements(ExternalScriptInfo scriptInfo, ExecutionContext context, bool forCompletion = false)
         {
-            VerifyElevatedPrivileges(scriptInfo);
-            VerifyPSVersion(scriptInfo);
-            VerifyPSEdition(scriptInfo);
-            VerifyRequiredModules(scriptInfo, context);
+            // No point in checking these requirements if failures will be ignored
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/CommandDiscovery.cs:346]: Please reword since it is for completion scenario.

File: src/System.Management.Automation/engine/CommandDiscovery.cs [hunk 8]
```diff
@@ -340,12 +341,18 @@ private CommandProcessorBase CreateScriptProcessorForSingleShell(ExternalScriptI
...
+            // VerifyRequiredModules will attempt to load the required modules which is useful.
+            if (!forCompletion)
+            {
+                VerifyElevatedPrivileges(scriptInfo);
+                VerifyPSVersion(scriptInfo);
+                VerifyPSEdition(scriptInfo);
+            }
+
+            VerifyRequiredModules(scriptInfo, context, forCompletion);
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/CommandDiscovery.cs:355]: Maybe try-catch and ignore exceptions for completion scenario?

File: src/System.Management.Automation/engine/CommandDiscovery.cs [hunk 9]
```diff
@@ -426,6 +433,7 @@ internal static void VerifyElevatedPrivileges(ExternalScriptInfo scriptInfo)
         /// False if not.  Null if command discovery should default to something reasonable
         /// for the command discovered.
         /// </param>
+        /// <param name="forCompletion"></param>
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/CommandDiscovery.cs:436]: Please add useful description.

File: test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1 (hunk 3 above)
Comment (iSazonov) [reply test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1:1665]: Better to have both tests if we take into account modules.

**Review by iSazonov — APPROVED** [review]

File: src/System.Management.Automation/engine/CommandDiscovery.cs (hunk 8 above)
Comment (MartinGC94) [reply src/System.Management.Automation/engine/CommandDiscovery.cs:358]: There is already a try catch in the pseudo binder that starts this whole chain of events.

Comment (MartinGC94) [reply src/System.Management.Automation/engine/CommandDiscovery.cs:358]: VerifyRequiredModules already have:
```
if (!forCompletion && error is not null)
                    {
                    {
                        ScriptRequiresException scriptRequiresException =
                        ScriptRequiresException scriptRequiresException =
                            new ScriptRequiresException(
                            new ScriptRequiresException(
                                scriptInfo.Name,
                                scriptInfo.Name,
                                new Collection<string> { requiredModule.GetRequiredModuleNotFoundVersionMessage() },
                                new Collection<string> { requiredModule.GetRequiredModuleNotFoundVersionMessage() },
                                "ScriptRequiresMissingModules",
                                "ScriptRequiresMissingModules",
                                false,
                                false,
                                error);
                                error);
                        throw scriptRequiresException;
                        throw scriptRequiresException;
                    }
                    }
```

Which prevents throwing if it's for completion.

**Review by iSazonov — APPROVED** [review]
