### PR TITLE
Fix formatting of header of table when center aligned

### LINKED ISSUE #8428: Format-Table with centered calculated property misaligns the column label
This is a regression from Windows PowerShell.

# Steps to reproduce

```powershell
[pscustomobject] @{ one = 1 } |
  Format-Table @{ l='one'; e='one'; width=10; alignment='center' }
```

# Expected behavior

```none

   one
   ---
    1


```

# Actual behavior

```none

one
   ---
    1

```

Note how the column header (`one`) is misaligned.

# Environment data

```none
PowerShell Core v6.2.0-preview.2 on macOS 10.14.1
PowerShell Core v6.2.0-preview.2 on Ubuntu 18.04.1 LTS
PowerShell Core v6.2.0-preview.2 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.407)
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
## PR Summary

In a previous change, it only applied padding if alignment was "right", but it should have applied padding whenever alignment was not "left" so that "center" alignment was also padded.  Some existing tests needed to be updated where the third column was using `center` alignment and the test was expecting the header to be `left` aligned (due to this bug) when the header also needed to be `center` aligned.

Fix https://github.com/PowerShell/PowerShell/issues/8428

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

File: src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs [hunk 1]
```diff
@@ -371,7 +371,7 @@ private StringCollection GenerateMultiLineRowField(string val, int k, int alignm
         {
             StringCollection sc = StringManipulationHelper.GenerateLines(dc, val,
                                         _si.columnInfo[k].width, _si.columnInfo[k].width);
-            if (addPadding || alignment == TextAlignment.Right)
+            if (addPadding || alignment != TextAlignment.Left)
```
Comment (iSazonov) [inline src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs]: Maybe it makes sense to check explicit values - right and center - because there may be "width" alignment?

File: test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1 [hunk 2]
```diff
@@ -476,7 +476,7 @@ er
             @{ view = "Default"; widths = 4,7,5; variation = "narrow values"; values = [PSCustomObject]@{First=1;Second=2;Third=3}; wrap = $false; expectedTable = @"
 
 Long*Header2*Heade
-Long*********r3
+Long**********r3
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1]: Please clarify why do old tests need to be updated?

File: src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs (hunk 1 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs]: Good point.  Will change.

File: test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1 (hunk 2 above)
Comment (SteveL-MSFT) [reply test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1]: The old tests had the `center` aligned header `left` aligned, so they need to be shifted to be centered when it got wrapped.  I'll add a comment to the PR description.

**Review by iSazonov — APPROVED** [review]

**Review by anmenaga — APPROVED** [review]
