### PR TITLE
PSVersionTable should have entry for OS and Platform

### LINKED ISSUE #1635: PSVersionTable should have entry for OS
## Steps to reproduce

```
$PSVersionTable.OS
```
## Expected behavior

Something useful
## Actual behavior

empty string
## Environment data

``` powershell
> $PSVersionTable

```

### PR DESCRIPTION
**Pull request by chunqingchen**
This is to resolve #1635

$PSVersionTable.OS now outputs [Runtime.InteropServices.RuntimeInformation]::OSDescription ([System.Environment]::OSVersion if not under coreclr)
$PSVersionTable.Platform outputs [System.Environment]::OSVersion.Platform

### CODE REVIEW

**Comment by mirichmo** [comment]
@JamesWTruher - Please review this change as well

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 1]
```diff
@@ -64,10 +64,13 @@ static PSVersionInfo()
             s_psVersionTable[PSVersionInfo.SerializationVersionName] = new Version(InternalSerializer.DefaultVersion);
             s_psVersionTable[PSVersionInfo.PSRemotingProtocolVersionName] = RemotingConstants.ProtocolVersion;
             s_psVersionTable[PSVersionInfo.WSManStackVersionName] = GetWSManStackVersion();
+            s_psVersionTable["Platform"] = Environment.OSVersion.Platform.ToString();
 #if CORECLR
+            s_psVersionTable["OS"] = Runtime.InteropServices.RuntimeInformation.OSDescription;
             s_psVersionTable["CLRVersion"] = null;
 #else
             s_psVersionTable["CLRVersion"] = Environment.Version;
+            s_psVersionTable["OS"] = Environment.OSVersion;
```
Comment (SteveL-MSFT) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: Shouldn't this use .ToString() as OSVersion is an object?

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]

**Comment by chunqingchen** [comment]
@SteveL-MSFT Thank you, your comment has been resolved.

File: test/powershell/Host/PSVersionTable.Tests.ps1 [hunk 2]
```diff
@@ -22,4 +24,22 @@ Describe "PSVersionTable" -Tags "CI" {
...
+    It "Should have the correct OS info" {
+    if ($IsCoreCLR)
+    {
+        $OSDescription = [String][System.Runtime.InteropServices.RuntimeInformation]::OSDescription
+	    [String]$PSVersionTable["OS"] | Should Be $OSDescription
+    }
+    else
+    {
+        $OSDescription = [String][System.Environment]::OSVersion
+        [String]$PSVersionTable["OS"] | Should Be [System.Environment]::OSVersion
```
Comment (SteveL-MSFT) [inline test/powershell/Host/PSVersionTable.Tests.ps1]: Part of me thinks we shouldn't make any changes for FullCLR, but if we're making the change it seems this line would fail as the right hand side should use ToString()

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]

File: test/powershell/Host/PSVersionTable.Tests.ps1 (hunk 2 above)
Comment (chunqingchen) [inline test/powershell/Host/PSVersionTable.Tests.ps1]: resolved

**Comment by chunqingchen** [comment]
@SteveL-MSFT comment resolved.

**Review by SteveL-MSFT — APPROVED** [review]
LGTM

File: test/powershell/Host/PSVersionTable.Tests.ps1 [hunk 3]
```diff
@@ -1,6 +1,6 @@
 Describe "PSVersionTable" -Tags "CI" {
     It "Should have version table entries" {
-	$PSVersionTable.Count | Should Be 9
+	$PSVersionTable.Count | Should Be 11
```
Comment (mirichmo) [inline test/powershell/Host/PSVersionTable.Tests.ps1]: Please fix the indentation within this file. It looks like you may have added tab characters instead of spaces. My comment applies to all changes made within this file.

**Review by mirichmo — CHANGES_REQUESTED** [review]

**Comment by chunqingchen** [comment]
@mirichmo I have tried to modify all the tab previous file contains into space.

**Review by mirichmo — APPROVED** [review]

**Comment by mirichmo** [comment]
Thanks. I'll merge it once it passes CI. I restarted since Travis failed with a possible unrelated issue.
