### PR TITLE
Use ProgressView.Classic if Virtual Terminal is not supported

### LINKED ISSUE #15047: Progress rendering is mangled in non-VT terminals
## Steps to reproduce

```powershell
Expand-Archive ./big.zip
```

## Expected behavior

Writes a standard progress bar.

## Actual behavior

image

## Environment data

image

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

On older Windows systems that don't support VT, they will get VT escape sequences if they enable certain ExperimentalFeatures that rely on VT.  Change to check if VT is supported before emitting.  In the case of Progress, we can't check deep in the Progress code as the host isn't available and it doesn't seem to make sense to pass it all the way down just for this.  Instead, we check in the consolehost and change to `Classic` progress view if VT is not supported.

I also noticed that the OSCIndicator code wasn't properly protected against older systems that don't support VT, so added that.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/15047

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfaceProgress.cs [hunk 1]
```diff
@@ -48,7 +48,7 @@ class ConsoleHostUserInterface : System.Management.Automation.Host.PSHostUserInt
 
                 _pendingProgress = null;
 
-                if (ExperimentalFeature.IsEnabled(ExperimentalFeature.PSAnsiProgressFeatureName) && PSStyle.Instance.Progress.UseOSCIndicator)
+                if (SupportsVirtualTerminal && ExperimentalFeature.IsEnabled(ExperimentalFeature.PSAnsiProgressFeatureName) && PSStyle.Instance.Progress.UseOSCIndicator)
```
Comment (iSazonov) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfaceProgress.cs:51]: I wonder why do not check SupportsVirtualTerminal in time we create PSStyle.Instance? It would seem be more generic.

Comment (rjmholt) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfaceProgress.cs:51]: Yeah the way we decide within the methods what behaviour to have here isn't great design and while this change seems ok, I think we need to register the need to do this better.

An alternative perspective on how the code should be structured: `PSHostUserInterface` is an abstract class intended to be overridden with the implementation to actually provide. The right object-oriented approach would be to build the user interface object for the given settings, with shared functionality implemented in a common base class.

**Review by rjmholt — APPROVED** [review]

**Comment by rjmholt** [comment]
I've rerun the Windows tests and they continue to fail. @SteveL-MSFT can you try rebasing this PR?
