### PR TITLE
Fix completion of provider paths when a path returns itself instead of its children

### LINKED ISSUE #24744: Tab-completion in custom provider adds spurious repeated path on non-container items
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Here's some repro code to create a provider where:

- the items are all integers from 0 to 9
- even numbers are containers
- odd numbers are non-container items

<details>
<summary>multi-file code content that defines IntProvider</summary>

- paket.references:

    ```
    System.Management.Automation
    ```

- IntProvider.csproj:

    ```
    <?xml version="1.0" encoding="utf-8"?>
    <Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <Import Project=".paket\Paket.Restore.targets" />
    </Project>
    ```

- IntProvider.cs:

    ```
    using System;
    using System.Linq;
    using System.Management.Automation;
    using System.Management.Automation.Provider;

    namespace BugRepro
    {
        public class IntItemInfo
        {
            public string Name;
            public IntItemInfo(string name) => Name = name;
        }

        [CmdletProvider("Int", ProviderCapabilities.None)]
        public class IntProvider : NavigationCmdletProvider
        {
            public static string[] ToChunks(string path) => path.Split("/", StringSplitOptions.RemoveEmptyEntries);

            protected string _ChildName(string path)
            {
                var name = ToChunks(path).LastOrDefault();
                return name ?? string.Empty;
            }

            protected string Normalize(string path) => string.Join("/", ToChunks(path));

            protected override string GetChildName(string path)
            {
                var name = _ChildName(path);
                // if (!IsItemContainer(path)) { return string.Empty; }
                return name;
            }

            protected override bool IsValidPath(string path) => int.TryParse(GetChildName(path), out int _);

            protected override bool IsItemContainer(string path)
            {
                var name = _ChildName(path);
                if (!int.TryParse(name, out int value))
                {
                    return false;
                }
                if (ToChunks(path).Count() > 3)
                {
                    return false;
                }
                return value % 2 == 0;
            }

            protected override bool ItemExists(string path)
            {
                foreach (var chunk in ToChunks(path))
                {
                    if (!int.TryParse(chunk, out int value))
                    {
                        return false;
                    }
                    if (value < 0 || value > 9)
                    {
                        return false;
                    }
                }
                return true;
            }

            protected override void GetItem(string path)
            {
                var name = GetChildName(path);
                if (!int.TryParse(name, out int _))
                {
                    return;
                }
                WriteItemObject(new IntItemInfo(name), path, IsItemContainer(path));
            }
            protected override bool HasChildItems(string path) => IsItemContainer(path);

            protected override void GetChildItems(string path, bool recurse)
            {
                if (!IsItemContainer(path)) { GetItem(path); return; }

                for (var i = 0; i <= 9; i++)
                {
                    var _path = $"{Normalize(path)}/{i}";
                    if (recurse)
                    {
                        GetChildItems(_path, recurse);
                    }
                    else
                    {
                        GetItem(_path);
                    }
                }
            }
        }
    }
    ```

- IntProvider.psd1:

    ```
    @{
        RootModule = 'IntProvider.psm1'
        NestedModules = @('./IntProvider.dll')
        ModuleVersion = '0.0.1'
        FunctionsToExport = @()
        CmdletsToExport = @()
        VariablesToExport = '*'
        AliasesToExport = @()
    }
    ```

- IntProvider.psm1:

    ```
    if (-not (Test-Path $PSScriptRoot/IntProvider.dll))
    {
        $CS = Get-Content -Raw $PSScriptRoot/IntProvider.cs
        Add-Type -TypeDefinition $CS -OutputAssembly $PSScriptRoot/IntProvider.dll
    }
    ```

- To build:

    ```
    dotnet tool install paket --create-manifest-if-needed
    dotnet tool restore
    dotnet build
    ```

</details>

- Set up PSDrive:

    ```
    ipmo IntProvider.psm1  # compile the C#
    ipmo IntProvider.psd1  # import the assembly - apparently it needs to be a nested module...?
    New-PSDrive -Name Int -PSProvider Int -Root "/"
    ```

### Expected behavior

When tab-completing in `FileSystemProvider`, no completions are offered as children of non-container items. E.g.:

```
❯ gi ./IntProvider.csproj/<tab>
```

Tab-completion strips the trailing slash.

```console
# either the child name, or an exception if the child name is suffixed with dir sep

❯ $inputScript = "gi ./IntProvider.csproj"
❯ [System.Management.Automation.CommandCompletion]::CompleteInput($inputScript, $inputScript.Length, $null).CompletionMatches

CompletionText       ListItemText         ResultType ToolTip
--------------       ------------         ---------- -------
./IntProvider.csproj IntProvider.csproj ProviderItem /home/freddie/gitroot/BugRepro/IntProvider.csproj


❯ $inputScript = "gi ./IntProvider.csproj/"
❯ [System.Management.Automation.CommandCompletion]::CompleteInput($inputScript, $inputScript.Length, $null).CompletionMatches
MethodInvocationException: Exception calling "CompleteInput" with "3" argument(s): "Could not find a part of the path '/home/freddie/gitroot/BugRepro/IntProvider.csproj'."
```

### Actual behavior

When tab-completing in a custom provider, completions are offered as children of non-container items. E.g.:

```
❯ gi Int:/2/3/<tab>
```

completes, incorrectly, to `Int:/2/3/2/3` (or to `Int:/2/3/3` as pointed out by MartinGC94). Both of these are incorrect.

Tab-completion strips the trailing slash.
```console
# this is correct:
❯ $inputScript = "gi Int:/2/3"
❯ [System.Management.Automation.CommandCompletion]::CompleteInput($inputScript, $inputScript.Length, $null).CompletionMatches

CompletionText ListItemText   ResultType ToolTip
-------------- ------------   ---------- -------
Int:/2/3       3            ProviderItem /2/3


# this is the wrong behaviour.
# "3" is not a container, so nothing should be appended
❯ $inputScript = "gi Int:/2/3/"                                                                                              
❯ [System.Management.Automation.CommandCompletion]::CompleteInput($inputScript, $inputScript.Length, $null).CompletionMatches

CompletionText ListItemText   ResultType ToolTip
-------------- ------------   ---------- -------
Int:/2/3//2/3/ /2/3/        ProviderItem /2/3//2/3/
```

### Error details

_No response_

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Fedora Linux 40 (Workstation Edition)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

# problem also reproduces on master branch, as of c29e9140bf6d47494a3c85b9031db81583b78b20 (2025-01-06)
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by MartinGC94**
# PR Summary
Fixes an issue when trying to complete an item in a path as if it was a container in providers that returns the item itself when calling `Get-ChildItem` on an item. This would make it complete the same item name again like this: `Provider::Container1\Item1\<Tab>` -> `Provider::Container1\Item1\Item1`

## PR Context
Fixes https://github.com/PowerShell/PowerShell/issues/24744

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
  - [X] None
  - **OR**
  - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
    - [ ] Experimental feature name(s): 
- **User-facing changes**
  - [X] Not Applicable
  - **OR**
  - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
  - [X] N/A or can only be tested interactively
  - **OR**
  - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
  - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
  - **OR**
  - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
    - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
      - [ ] Issue filed: 
    - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
      - [ ] Issue filed: 
    - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
      - [ ] Issue filed: 
    - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
      - [ ] Issue filed:

### CODE REVIEW

**Comment by iSazonov** [comment]
We could use a test provider from related issue and compile it with Add-Type. (There are examples in our tests, one or more is in Add-Type.Tests.ps1)

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs [hunk 1]
```diff
@@ -4810,6 +4810,14 @@ private static List<CompletionResult> GetDefaultProviderResults(
                 bool hadErrors;
                 var childItemOutput = context.Helper.ExecuteCurrentPowerShell(out _, out hadErrors);
 
+                if (childItemOutput.Count == 1 &&
+                    (pathInfo.Provider.FullName + "::" + pathInfo.ProviderPath).EqualsOrdinalIgnoreCase(childItemOutput[0].Properties["PSPath"].Value as string))
+                {
+                    // Get-ChildItem returned the item itself instead of the children so there must be no child items to complete.
+                    // The filesystem provider does this when pointing to files: Get-ChildItem C:\pagefile.sys -Force and other providers may follow this pattern.
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:4817]: As for this provider, I think the only thing worth mentioning is that this code doesn't work for it.

Comment (iSazonov) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:4817]: I mean to remove the line:
```
// The filesystem provider does this when pointing to files: Get-ChildItem C:\pagefile.sys -Force and other providers may follow this pattern.
```

**Review by iSazonov — APPROVED** [review]
