### PR TITLE
Fix ConciseView to handle case where there isn't a console to obtain the width

### LINKED ISSUE #11776: Bug in Formatting while being without console
Hello,
running pwsh 7.0.0-rc2 on my build server the following happens when my own cmdlet raises an exception:
`

05-Feb-2020 10:35:56 |  
-- | --
05-Feb-2020 10:35:56 | OperationStopped:
05-Feb-2020 10:35:56 | Line \|
05-Feb-2020 10:35:56 | 161 \|  …         if ([Console]::WindowWidth -gt 0 -and ($message.Length - $pre …
05-Feb-2020 10:35:56 |  
05-Feb-2020 10:35:56 | \|                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
05-Feb-2020 10:35:56 | \| Das Handle ist ungültig.
`

You are trying to read WindowWidth but there is no window. So you get Invalid Handle for the non existing console window.

Happens here on line 1154: https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs 

Please fix.

Thanks!

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

ConciseView relied on the window width for calculating line wrapping.  In the case where PowerShell is run on a system without a console, the call to get the console windowwidth throws.  Fix is to wrap the use of `[Console]::WindowWidth` in a try..catch and use a default value for the width if it throws.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/11776

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs [hunk 1]
```diff
@@ -1151,15 +1151,23 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_System_Management_Autom
```
Comment (PoshChan) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs]: @SteveL-MSFT, your last commit had 1 failures in `PowerShell-CI-macos`
Test-Connection.TraceRoute.TraceRoute works
```powershell
Expected strings to be the same, but they were different.
String lengths are both 14.
Strings differ at index 6.
Expected: 'Mac-1158.local'
But was:  'Mac-1169.local'
at <ScriptBlock>, /Users/runner/runners/2.164.7/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1: line 256
256:             $result[0].Source | Should -BeExactly $hostName
```

**Review by iSazonov — APPROVED** [review]

**Comment by SteveL-MSFT** [comment]
@iSazonov can you merge this so I can make a fix for the other issue with these changes to avoid a merge conflict?
