### PR TITLE
Fix 'ForEach' method so it can set property on a scalar object as expected

### LINKED ISSUE #16666: Setting property values with the .ForEach() array method doesn't work with a single [pscustomobject] instance.
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`.ForEach()` has an overload that allows setting property values by name and (array of) property values.

This works in general, but unexpectedly not with  a _single_ `[pscustomobject]` instance (as later discovered, it _does_ work with _arrays_ of `[pscustomobject]` instances).

```powershell
($obj = [pscustomobject] @{ p = 1 }).ForEach('p', 42)
```

### Expected behavior

No output, and `$obj.p` should report `42` afterwards.

### Actual behavior

`1` - the current property value - is output, and the attempt to assign a new value is ignored.

### Error details

_No response_

### Environment data

```powershell
PowerShell Core 7.3.0-preview.1
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #16666

Fix 'ForEach' method so it can set property on a scalar object as expected.
We didn't pass in all the argument when taking the code path that handles calling `.ForEach` on a scalar object.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

File: src/System.Management.Automation/engine/runtime/Binding/Binders.cs [hunk 1]
```diff
@@ -7454,7 +7454,20 @@ internal static object InvokeAdaptedMember(object obj, string methodName, object
...
+                    int length = args.Length - 1;
+                    argsToPass = new object[length];
+                    Array.Copy(args, sourceIndex: 1, argsToPass, destinationIndex: 0, length: length);
+                }
+                else
+                {
+                    argsToPass = Array.Empty<object>();
+                }
+
+                return EnumerableOps.ForEach(enumerator, args[0], argsToPass);
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/runtime/Binding/Binders.cs:7470]: Could we convert argsToPass to args.AsSpan(1) to avoid extra coping?

**Review by SeeminglyScience — APPROVED** [review]
LGTM! ❤️
