### PR TITLE
Fix spurious error generated when importing cmdlets from an in-memory assembly

### LINKED ISSUE #4025: Error noise in Start-PSPester run
Repro:

```powershell
Start-PSPester
```

Expected:
No red text

Actual:
```
Describing Argument transformation attribute on optional argument with explicit $null
Import-Module : Could not load file or assembly 'vq0eguqn.tqg, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
The system cannot find the file specified.
At C:\Users\slee\repos\PowerShell\test\powershell\Language\Parser\ParameterBinding.Tests.ps1:50 char:5
+     Import-Module $mod[0].Assembly
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], RuntimeException
    + FullyQualifiedErrorId : Module_ImportModuleError,Microsoft.PowerShell.Commands.ImportModuleCommand

 [+] Script function takes object 565ms
 [+] Script function takes uint64 33ms
 [+] csharp cmdlet takes object 22ms
 [+] csharp cmdlet takes uint64 27ms
 [+] script function takes object when parameter is null 23ms
 [+] script function takes unit64 when parameter is null 31ms
 [+] script csharp cmdlet takes object when parameter is null 23ms
 [+] script csharp cmdlet takes uint64 when parameter is null 27ms
```

### PR DESCRIPTION
**Pull request by BrucePay**
Fixes #4025 where a test importing cmdlets from an in-memory assembly produced an spurious error.

### CODE REVIEW

**Review by PaulHigin — APPROVED** [review]
LGTM

File: src/System.Management.Automation/engine/InitialSessionState.cs [hunk 1]
```diff
@@ -4494,10 +4494,15 @@ internal void ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module)
...
-            SessionStateAssemblyEntry assemblyEntry =
-                new SessionStateAssemblyEntry(assembly.FullName, assemblyPath);
+            // If this is an in-memory assembly, don't added it to the list of AssemblyEntries
+            // since it can't be loaded by path or name
+            if (! string.IsNullOrEmpty(assembly.Location))
+            {
+                SessionStateAssemblyEntry assemblyEntry =
+                    new SessionStateAssemblyEntry(assembly.FullName, assemblyPath);
+                this.Assemblies.Add(assemblyEntry);
+            }
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/InitialSessionState.cs]: Please remove the extra line.

Comment (daxian-dbw) [inline src/System.Management.Automation/engine/InitialSessionState.cs]: Extra line removed.

**Review by daxian-dbw — APPROVED** [review]
