### PR TITLE
Fix various about topic help issues

### LINKED ISSUE #3782: Get-Help about_* bugs (conceptual help topics)
Note: This is an attempt to consolidate the related existing issues:
* #2653 
* #3503
* #3728
* #3781

The **behavior as of beta1**, verified on Windows 10, macOS 10.12, Ubuntu 16.04:

* `Get-Help about_*` (using wildcards)
  * Windows: OK
  * Unix: Broken
      * No success output, only error `get-help : Unable to find type [wmiclass].`
      * Problem starts with as few chars.  as `Get-Help ab*`, but, curiously, _doesn't_ break with `Get-Help a*`, in which case only matching _non-conceptual_ topics are output.

* `Get-Help about_Variable` (any individual topic, specified _in full, without wildcards_)  
  * Windows: Broken
     * Shows a _list_ of 2 _duplicates_ rather than the text of the help topic itself.
  * Unix: OK

* Tab completion with `about_*` topics:
   * Windows: OK
   * Unix: Broken
        * Nothing happens when you press <kbd>tab</kbd> after typing `Get-Help about_`, for instance.

### PR DESCRIPTION
**Pull request by adityapatwardhan**
Fixes #3782 #2565 #4011 #4013

* Fix double help topic printing issue
* Fix regressions introduced by change a52adcd
* Use WildcardPattern to fix tab completion

### CODE REVIEW

**Comment by adityapatwardhan** [comment]
@powercode I changed some code CompletionCompleters.cs which was modified by you recently. Can you please have a look?

**Comment by chunqingchen** [comment]
signed off

**Review by chunqingchen — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
@PowerShell/powershell-maintainers This PR is ready to merge.

File: src/System.Management.Automation/help/MUIFileSearcher.cs [hunk 1]
```diff
@@ -304,12 +304,17 @@ private static Collection<String> NormalizeSearchPaths(string target, Collection
...
-            string returnValue = CommandDiscovery.GetShellPathFromRegistry(Utils.DefaultPowerShellShellID);
+            string returnValue = Utils.GetApplicationBase(Utils.DefaultPowerShellShellID);
 
+            //On CoreCLR we use ApplicationBase assembly location. That gives us the directory name.
+            //Hence we do not need to extract the directory name from returnValue.
+
+#if !CORECLR
             if (returnValue != null)
             {
                 returnValue = Path.GetDirectoryName(returnValue);
```
Comment (daxian-dbw) [inline src/System.Management.Automation/help/MUIFileSearcher.cs]: This is not needed even for FullCLR if you use `Utils.GetApplicationBase(Utils.DefaultPowerShellShellID)`. It returns the pshome path.

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs [hunk 2]
```diff
@@ -5952,14 +5953,15 @@ private static string GetNamespaceToRemove(CompletionContext context, TypeComple
...
+            var dirPath = Utils.GetApplicationBase(Utils.DefaultPowerShellShellID) + Path.DirectorySeparatorChar + CultureInfo.CurrentCulture.Name;
             var wordToComplete = context.WordToComplete + "*";
             var topicPattern = WildcardPattern.Get("about_*.help.txt", WildcardOptions.IgnoreCase);
             string[] files = null;
 
             try
             {
-                files = Directory.GetFiles(dirPath, wordToComplete);
+                var wildcardPattern = WildcardPattern.Get(wordToComplete, WildcardOptions.IgnoreCase);
+                files = Directory.GetFiles(dirPath).Where(f => wildcardPattern.IsMatch(Path.GetFileName(f))).ToArray();
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs]: It's recommended to avoid LINQ in perf-sensitive code path (see [pref-considerations](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/coding-guidelines.md#performance-considerations)). Tab completion is perf sensitive, so could you please replace this with a loop?

File: src/System.Management.Automation/help/MUIFileSearcher.cs (hunk 1 above)
Comment (adityapatwardhan) [inline src/System.Management.Automation/help/MUIFileSearcher.cs]: GetMshDefaultInstallationPath had only one reference, replaced where it was called with ```Utils.GetApplicationBase(Utils.DefaultPowerShellShellID); ``` And deleted the function GetMshDefaultInstallationPath

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs (hunk 2 above)
Comment (adityapatwardhan) [inline src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs]: Fixed.

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs [hunk 3]
```diff
@@ -4089,11 +4089,11 @@ internal static IEnumerable<CompletionResult> CompleteFilename(CompletionContext
                     wordToComplete = WildcardPattern.Escape(wordToComplete, Utils.Separators.StarOrQuestion);
                 }
 
-                if (!defaultRelative && wordToComplete.Length >= 2 && wordToComplete[1] == ':' && char.IsLetter(wordToComplete[0]) && executionContext != null)
+                if (!defaultRelative && wordToComplete.Length >= 2 && wordToComplete[1] == ':' && char.IsLetter(wordToComplete[0]) && context.ExecutionContext != null)
                 {
                     // We don't actually need the drive, but the drive must be "mounted" in PowerShell before completion
                     // can succeed.  This call will mount the drive if it wasn't already.
-                    executionContext.SessionState.Drive.GetAtScope(wordToComplete.Substring(0, 1), "global");
+                    context.ExecutionContext.SessionState.Drive.GetAtScope(wordToComplete.Substring(0, 1), "global");
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs]: You don't need to replace `executionContext` with `context.ExecutionContext` at the two spots here.

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs [hunk 4]
```diff
@@ -5952,14 +5952,22 @@ private static string GetNamespaceToRemove(CompletionContext context, TypeComple
         internal static List<CompletionResult> CompleteHelpTopics(CompletionContext context)
         {
             var results = new List<CompletionResult>();
-            var dirPath = Utils.GetApplicationBase(Utils.DefaultPowerShellShellID) + "\\" + CultureInfo.CurrentCulture.Name;
+            var dirPath = Utils.GetApplicationBase(Utils.DefaultPowerShellShellID) + Path.DirectorySeparatorChar + CultureInfo.CurrentCulture.Name;
             var wordToComplete = context.WordToComplete + "*";
             var topicPattern = WildcardPattern.Get("about_*.help.txt", WildcardOptions.IgnoreCase);
-            string[] files = null;
+            ArrayList files = new ArrayList();
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs]: Could you please use `List<string>` here? We prefer to strongly typed generic collection whenever possible, it will avoid a cast from `object` to `string` in the `foreach (string file in files)` loop later.

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs (hunk 3 above)
Comment (adityapatwardhan) [inline src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs]: Fixed.

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs (hunk 4 above)
Comment (adityapatwardhan) [inline src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs]: Fixed.

**Comment by adityapatwardhan** [comment]
Opened issue https://github.com/PowerShell/PowerShell/issues/4037 as discussed for refactoring.

**Comment by daxian-dbw** [comment]
@adityapatwardhan If you search `new CompletionContext { ` in `CompletionCompleters.cs` you will find 5 more instances of it which are not updated in this PR. Do they need to be fixed as well?

**Comment by adityapatwardhan** [comment]
@daxian-dbw Fixed.

**Review by daxian-dbw — APPROVED** [review]
