### PR TITLE
Treat `[NullString]::Value` as the string type when resolving methods

### LINKED ISSUE #18072: Method overload resolution: [NullString]::Value doesn't guide toward picking a [string]-based overload
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

` [NullString]::Value` was specifically introduced to pass a true `$null` value to `string`-typed method parameters.
Yet, during method overload resolution, it doesn't reliably select a `[string]`-based overload:

```powershell
class Foo {
  [string] Test([bool] $bar) { return 'bool'}
  [string] Test([string] $bar) { return 'string' }
}

# *Should* select the `[string]` overload, but doesn't.
[Foo]::new().Test([NullString]::Value)
# OK, with cast:
[Foo]::new().Test([string] [NullString]::Value)
```

### Expected behavior

```console
string
string
```

### Actual behavior

```console
bool
string
```

### Error details

_No response_

### Environment data

```powershell
PowerShell Core 7.3.0-preview.7
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #18072
Treat `[NullString]::Value` as the string type when resolving methods.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

File: src/System.Management.Automation/engine/CoreAdapter.cs [hunk 1]
```diff
@@ -1670,18 +1670,21 @@ private static Type[] ResolveGenericTypeParameters(object[] genericTypeParameter
...
+            arg = PSObject.Base(arg);
+            if (arg is null)
             {
-                arg = PSObject.Base(arg);
-                object[] argAsArray = arg as object[];
-                if (argAsArray != null && argAsArray.Length > 0 && PSObject.Base(argAsArray[0]) != null)
+                return typeof(LanguagePrimitives.Null);
+            }
+
+            if (arg is object[] array && array.Length > 0)
```
Comment (dkaszews) [inline src/System.Management.Automation/engine/CoreAdapter.cs:1679]: I'd rather keep the old descriptive name `argAsArray` the new `array` leaves no clue about what the variable holds, its like a `String string` or `int i` - fine in some context, don't see a point in changing it here.

File: src/System.Management.Automation/engine/CoreAdapter.cs [hunk 2]
```diff
@@ -1693,13 +1696,19 @@ internal static Type EffectiveArgumentType(object arg)
...
                 }
-
-                return arg.GetType();
             }
-            else
+
+            return GetObjectType(arg, skipBasing: true);
+        }
+
+        internal static Type GetObjectType(object obj, bool skipBasing)
```
Comment (dkaszews) [inline src/System.Management.Automation/engine/CoreAdapter.cs:1704]: 1. Is `basing` a word? `skipBaseResolution` sounds better to me.
2. Please add a comment why you are resolving the base exactly once, instead of e.g. all the way to root.
3. Finally, is this base resolution even reasonable inside this method? `GetObjectType` does not sound like anything that should deal with hierarchy, only the current object type. If caller wants to use the base type, they should pass `PSObject.Base(obj)` themselves explicitly.

File: src/System.Management.Automation/engine/CoreAdapter.cs [hunk 3]
```diff
@@ -1693,13 +1696,19 @@ internal static Type EffectiveArgumentType(object arg)
...
+        {
+            if (!skipBasing)
             {
-                return typeof(LanguagePrimitives.Null);
+                obj = PSObject.Base(obj);
             }
+
+            return obj == NullString.Value ? typeof(string) : obj?.GetType();
```
Comment (dkaszews) [inline src/System.Management.Automation/engine/CoreAdapter.cs:1711]: I could imagine this logic being required in the future for different types, so hardcoding it here in the ternary does not look maintainable to me. How about making `NullString` implement something like `interface ITypeOverloadOverride { Type TypeForOverloadResolution`? Then you could replace this ternary with a generic `obj is ITypeOverloadOverride overridden ? overridden?.TypeForOverloadResolution : obj?.GetType();`

File: src/System.Management.Automation/engine/runtime/Binding/Binders.cs [hunk 4]
```diff
@@ -7349,11 +7349,15 @@ internal static bool IsHomogenousArray<T>(object[] args)
                 return false;
             }
 
-            return args.All(element =>
-                            {
-                                var obj = PSObject.Base(element);
-                                return obj != null && obj.GetType().Equals(typeof(T));
-                            });
+            foreach (object element in args)
```
Comment (dkaszews) [inline src/System.Management.Automation/engine/runtime/Binding/Binders.cs:7352]: Why replace LINQ `All` with a `foreach`? The former looks way clearer to me, I don't need to analyse what the loop does, the algorithm is clearly stated.

File: src/System.Management.Automation/engine/runtime/Binding/Binders.cs [hunk 5]
```diff
@@ -7381,11 +7385,15 @@ internal static bool IsHeterogeneousArray(object[] args)
                 return true;
             }
 
-            return args.Skip(1).Any(element =>
-                                    {
-                                        var obj = PSObject.Base(element);
-                                        return obj == null || !firstType.Equals(obj.GetType());
-                                    });
+            for (int i = 1; i < args.Length; i++)
```
Comment (dkaszews) [inline src/System.Management.Automation/engine/runtime/Binding/Binders.cs:7388]: Same as above: LINQ is more readable

File: test/powershell/Language/Scripting/Scripting.Followup.Tests.ps1 [hunk 6]
```diff
@@ -90,4 +90,43 @@ Describe "Scripting.Followup.Tests" -Tags "CI" {
 
         TestFunc2 | Should -Be @("1", "2")
     }
+
+    It "'[NullString]::Value' should be treated as string type when resolving .NET method" {
+
+        $testType = 'NullStringTest' -as [type]
+        if (-not $testType) {
+            Add-Type -TypeDefinition @"
+    using System;
```
Comment (dkaszews) [inline test/powershell/Language/Scripting/Scripting.Followup.Tests.ps1:99]: Weird indent, why not keep it all the way to the left if you're not aligning to the PowerShell code

File: test/powershell/Language/Scripting/Scripting.Followup.Tests.ps1 [hunk 7]
```diff
@@ -90,4 +90,43 @@ Describe "Scripting.Followup.Tests" -Tags "CI" {
 
         TestFunc2 | Should -Be @("1", "2")
     }
+
+    It "'[NullString]::Value' should be treated as string type when resolving .NET method" {
+
+        $testType = 'NullStringTest' -as [type]
+        if (-not $testType) {
+            Add-Type -TypeDefinition @"
```
Comment (dkaszews) [inline test/powershell/Language/Scripting/Scripting.Followup.Tests.ps1:98]: Suggestion: if you're not using string interpolation/substitution, you should use single quoted strings to show that it is a pure literal

File: test/powershell/Language/Scripting/Scripting.Followup.Tests.ps1 [hunk 8]
```diff
@@ -90,4 +90,43 @@ Describe "Scripting.Followup.Tests" -Tags "CI" {
 
         TestFunc2 | Should -Be @("1", "2")
     }
+
+    It "'[NullString]::Value' should be treated as string type when resolving .NET method" {
+
+        $testType = 'NullStringTest' -as [type]
+        if (-not $testType) {
```
Comment (dkaszews) [inline test/powershell/Language/Scripting/Scripting.Followup.Tests.ps1:97]: What is the scenario when this branch is not taken? Leftovers from another test? How can we make sure that another test defines `NullStringTest` exactly how we want? Removing the type in `AfterEach` is more reasonable to me.

File: src/System.Management.Automation/engine/CoreAdapter.cs (hunk 2 above)
Comment (SeeminglyScience) [reply src/System.Management.Automation/engine/CoreAdapter.cs:1704]: > * Please add a comment why you are resolving the base exactly once, instead of e.g. all the way to root.

`PSObject.Base` gets the first non-`PSObject` base object. In other words, it does base all the way to the root.

> * Finally, is this base resolution even reasonable inside this method? `GetObjectType` does not sound like anything that should deal with hierarchy, only the current object type. If caller wants to use the base type, they should pass `PSObject.Base(obj)` themselves explicitly.

`PSObject` is a wrapper that helps with engine implementation details (and it's a property bag). It's not related to hierarchy.

File: src/System.Management.Automation/engine/runtime/Binding/Binders.cs (hunk 4 above)
Comment (SeeminglyScience) [reply src/System.Management.Automation/engine/runtime/Binding/Binders.cs:7352]: > Why replace LINQ `All` with a `foreach`? The former looks way clearer to me, I don't need to analyse what the loop does, the algorithm is clearly stated.

It's an abstraction that isn't free unfortunately. In most places it's fine, but performance sensitive code should avoid it when possible.

File: src/System.Management.Automation/engine/CoreAdapter.cs (hunk 3 above)
Comment (SeeminglyScience) [reply src/System.Management.Automation/engine/CoreAdapter.cs:1711]: > I could imagine this logic being required in the future for different types, so hardcoding it here in the ternary does not look maintainable to me. How about making `NullString` implement something like `interface ITypeOverloadOverride { Type TypeForOverloadResolution`? Then you could replace this ternary with a generic `obj is ITypeOverloadOverride overridden ? overridden?.TypeForOverloadResolution : obj?.GetType();`

`NullString` is a bit of a special case because it's the only type PowerShell tries to pretend as if it's a valuetype. I don't think it's likely we'll have to add another. Maybe would be a good issue to open but out of scope of this PR imo

**Review by SeeminglyScience — APPROVED** [review]
LGTM!

File: src/System.Management.Automation/engine/CoreAdapter.cs (hunk 2 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/CoreAdapter.cs:1704]: It turns out we already use the word [`debase`](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/LanguagePrimitives.cs#L4761) to indicate if `PSObject.Base` should be called. Will update to follow the existing naming and pattern.

File: test/powershell/Language/Scripting/Scripting.Followup.Tests.ps1 (hunk 8 above)
Comment (daxian-dbw) [reply test/powershell/Language/Scripting/Scripting.Followup.Tests.ps1:97]: When running the test multiple times within the same PowerShell session, the type would have already been declared, and calling `Add-Type` again will result in an error.
The type is made available by `Add-Type`, and thus cannot be removed until the current PS process exits.

File: test/powershell/Language/Scripting/Scripting.Followup.Tests.ps1 (hunk 7 above)
Comment (daxian-dbw) [reply test/powershell/Language/Scripting/Scripting.Followup.Tests.ps1:98]: Updated using single quote.

File: test/powershell/Language/Scripting/Scripting.Followup.Tests.ps1 (hunk 6 above)
Comment (daxian-dbw) [reply test/powershell/Language/Scripting/Scripting.Followup.Tests.ps1:99]: Move to the very left.

File: src/System.Management.Automation/engine/CoreAdapter.cs (hunk 1 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/CoreAdapter.cs:1679]: The `is` expression makes the variable quite descriptive, as in "arg is an array".

File: src/System.Management.Automation/engine/CoreAdapter.cs [hunk 9]
```diff
@@ -1693,13 +1696,19 @@ internal static Type EffectiveArgumentType(object arg)
...
+
+        internal static Type GetObjectType(object obj, bool debase)
+        {
+            if (debase)
             {
-                return typeof(LanguagePrimitives.Null);
+                obj = PSObject.Base(obj);
             }
+
+            return obj == NullString.Value ? typeof(string) : obj?.GetType();
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/CoreAdapter.cs:1711]: Is it really hot path code? If so we could think about more tier-compilation-friendly methods:
```c#
        internal static Type GetObjectTypeAfterDebase(object obj)
        {
            obj = PSObject.Base(obj);

            return obj == NullString.Value ? typeof(string) : obj?.GetType();
    }

        internal static Type GetObjectTypeWithoutDebase(object obj) => 
obj == NullString.Value ? typeof(string) : obj?.GetType();

**Review by iSazonov — APPROVED** [review]
LGTM with one notice.

File: src/System.Management.Automation/engine/CoreAdapter.cs (hunk 9 above)
Comment (dkaszews) [reply src/System.Management.Automation/engine/CoreAdapter.cs:1711]: I think I know C# pretty well but never considered it from performance side. In C++, this function would be almost guaranteed to be inlined and the `if` discarded or made unconditional. Is C#'s optimizer really not capable of it? Do you have some optimization guidelines I could read, e.g. when to use `[AggressivelyInline]` I saw in some `WriteToConsole` overloads?

**Review by dkaszews — APPROVED** [review]

File: src/System.Management.Automation/engine/runtime/Binding/Binders.cs (hunk 4 above)
Comment (dkaszews) [reply src/System.Management.Automation/engine/runtime/Binding/Binders.cs:7352]: Do you have some performance measurements to show the difference? Or, more generally, does PowerShell have performance regression tests in CI?

Back at university I wrote a constraint solver that was pretty much just couple dozen expression-bodied functions immediately returning a LINQ expression. So every single line of LINQ was in hot path. I benched it against unrolled for loops and saw no statistically significant difference. And that was 5 years ago, I would imagine compiler/runtime get even better in optimizing abstractions to make them zero cost.

File: src/System.Management.Automation/engine/CoreAdapter.cs (hunk 9 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/CoreAdapter.cs:1711]: For reading https://devblogs.microsoft.com/dotnet/performance_improvements_in_net_7/

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/CoreAdapter.cs:1711]: This seems to be a micro-optimization that we should avoid, as I don't think the difference is measurable.
