### PR TITLE
Fix `help` function to check if `less` is available before using

### LINKED ISSUE #9830: Are the Utils PowerShell Core Depends on in Linux managed and published?
The Get-Help on Linux Depends on "less" command - this is an Amazon Linux 2 container (which - as provided by AWS - has a completely minimalized package footprint) and I get this error:
image

This raises the questions:
- is there a managed list of what PowerShell core assumes is on the system?
- shouldn't the packages for PowerShell Core check for and resolve these dependencies if system commands depend on them?
- or should it just not depend on any OS packages?

Apologies if this is covered somewhere - if so, please drop a link in this issue :)

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

The `help` function assumes on non-Windows that `less` is available as a pager.  However, on some Linux systems, `less` is not installed by default so using `help` fails that `less` is not found.  FIx is to check if `less` is available before using and, if not, just output the help text instead of paging.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/9830

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

File: src/System.Management.Automation/engine/InitialSessionState.cs [hunk 1]
```diff
@@ -4276,6 +4276,9 @@ .FORWARDHELPCATEGORY Cmdlet
         else {
             $pagerCommand = 'less'
             $pagerArgs = '-Ps""Page %db?B of %D:.\. Press h for help or q to quit\.$""'
+            if ($null -eq (Get-Command -Name $pagerCommand -Type Application -ErrorAction Ignore)) {
+                $pagerCommand = $null
+            }
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/InitialSessionState.cs]: It seems it is a dup of line 4313. We could remove this.

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/InitialSessionState.cs]: Not exactly the same, but I can see some efficiency here.  Making a change.

**Review by iSazonov — APPROVED** [review]

**Review by TravisEz13 — APPROVED** [review]

**Comment by TravisEz13** [comment]
Should we continue to include less in the docker images?

**Comment by SteveL-MSFT** [comment]
@TravisEz13 I would think most use of docker images are non-interactive, so `less` is probably not needed, but don't have a strong opinion on this.
