### PR TITLE
Fix splatting being treated as positional parameter

### LINKED ISSUE #3650: Intellisense: Splatting is treated as a positional parameter
From: https://github.com/PowerShell/vscode-powershell/issues/696

# Overview

When splatting parameters onto a command, PowerShell assumes that the splat is taking the place of the first parameter. Therefore, when you attempt to auto-complete parameters, the first parameter is removed from the Intellisense list, even if that parameter doesn't appear in the Splatting HashTable.

For example, take a look at the first parameter of the Amazon Web Services (AWS) `Get-ECSClusterService` command. The first parameter is `-Cluster`.

screen shot 2017-04-25 at 3 11 24 pm

However, when I splat a couple of "common parameters," specifically `-Region` and `-ProfileName`, you can see that `-Cluster` is removed from the Intellisense results.

screen shot 2017-04-25 at 3 14 31 pm

When automating against AWS, I use the Intellisense list to build a second Splatting HashTable with service-specific parameters, and then Splat both the common parameters and the service-specific parameters. Hence, the missing parameter causes me a bit of grief. Minor annoyance. :)

```powershell
### Define common parameters
$Common = @{
  ProfileName = 'awsprofile'
  Region = 'us-west-2'
}

### Define service-specific parameters
$ECSService = @{
  Cluster = $ECSCluster.ClusterName
  ServiceName = 'testservice'
  TaskDefinition = 'windows-test'
  DesiredCount = 1
}

### Splat both common and service-specific parameters
New-ECSService @Common @ECSService
```

Cheers,
Trevor Sullivan

### PR DESCRIPTION
**Pull request by MartinGC94**
# PR Summary
Fixes https://github.com/PowerShell/PowerShell/issues/3650 where if you use splatting it counts as a positional argument so you lose the parameter in the tab completion suggestions.  
For example `Get-ChildItem @Splat -P` won't suggest the Path parameter because @Splat is incorrectly being treated as a value for the Path parameter.

## PR Context
It's annoying to forget about a parameter because IntelliSense didn't show it to you.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

File: src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs [hunk 1]
```diff
@@ -1862,13 +1862,17 @@ private static bool IsTypeEquivalent(Type argType, Type paramType)
             while (unboundArgumentsIndex < unboundArgumentsCollection.Count)
             {
                 AstParameterArgumentPair argument = unboundArgumentsCollection[unboundArgumentsIndex++];
-                if (!argument.ParameterSpecified)
+                bool splatted = (argument is AstPair a) && (a.Argument is VariableExpressionAst v) && v.Splatted;
+                if (!argument.ParameterSpecified && splatted == false)
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs:1866]: Testing a boolean value for equality is unneeded; `if (x == false) { ... }` is the same as `if (!x) { ... }`.

```suggestion
                bool splatted = argument is AstPair astPair
                    && astPair.Argument is VariableExpressionAst argumentVariable
                    && argumentVariable.Splatted;
                if (!splatted && !argument.ParameterSpecified)
```

File: src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs [hunk 2]
```diff
@@ -1862,13 +1862,17 @@ private static bool IsTypeEquivalent(Type argType, Type paramType)
...
                 {
                     result = argument;
                     break;
                 }
 
-                nonPositionalArguments.Add(argument);
+                if (splatted == false)
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs:1872]:
```suggestion
                if (!splatted)
```

**Review by AungMinKo070 — APPROVED** [review]

File: src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs [hunk 3]
```diff
@@ -1862,13 +1862,19 @@ private static bool IsTypeEquivalent(Type argType, Type paramType)
             while (unboundArgumentsIndex < unboundArgumentsCollection.Count)
             {
                 AstParameterArgumentPair argument = unboundArgumentsCollection[unboundArgumentsIndex++];
-                if (!argument.ParameterSpecified)
+                bool splatted = argument is AstPair astPair
+                    && astPair.Argument is VariableExpressionAst argumentVariable
+                    && argumentVariable.Splatted;
+                if (!splatted && !argument.ParameterSpecified)
```
Comment (rkeithhill) [inline src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs:1868]: I think this could be simplified to:
```csharp
if (splatted)
{
    continue;
}
```
Then the rest of the loop can go back to the code as it was before.

**Review by rkeithhill — APPROVED** [review]
LGTM other than the code complexity check that is failing

File: src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs [hunk 4]
```diff
@@ -1862,6 +1862,14 @@ private static bool IsTypeEquivalent(Type argType, Type paramType)
             while (unboundArgumentsIndex < unboundArgumentsCollection.Count)
             {
                 AstParameterArgumentPair argument = unboundArgumentsCollection[unboundArgumentsIndex++];
+                bool splatted = argument is AstPair astPair
+                    && astPair.Argument is VariableExpressionAst argumentVariable
+                    && argumentVariable.Splatted;
+                if (splatted)
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs:1868]:
```suggestion
                if (argument is AstPair astPair
                    && astPair.Argument is VariableExpressionAst argumentVariable
                    && argumentVariable.Splatted)
```

**Review by rjmholt — APPROVED** [review]
