### PR TITLE
Fix ForEach-Object -Parallel when passing in script block variable

### LINKED ISSUE #16445: ForEach-Object -Parallel does not accept a scriptblock variable containing a $using
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

After upgrading to PS 7.2 from PS 7.1.5 I am not able to pass a scriptblock variable containing a $using anymore. This works fine in PS 7.1.5

### Expected behavior

```console
Using PS 7.1.5

PS>$data = 'hi'
PS>$script = [scriptblock]::Create('Write-Host $using:data')
PS>1..2 | ForEach-Object -Parallel $script
hi
hi
```

### Actual behavior

```console
Using PS 7.2.0

PS>$data = 'hi'
PS>$script = [scriptblock]::Create('Write-Host $using:data')
PS>1..2 | ForEach-Object -Parallel $script
InvalidOperation: A Using variable cannot be retrieved. A Using variable can be used only with Invoke-Command, Start-Job, or InlineScript in the script workflow. When it is used with Invoke-Command, the Using variable is valid only if the script block is invoked on a remote computer.
InvalidOperation: A Using variable cannot be retrieved. A Using variable can be used only with Invoke-Command, Start-Job, or InlineScript in the script workflow. When it is used with Invoke-Command, the Using variable is valid only if the script block is invoked on a remote computer.
```

### Error details

```console
Exception             :
    Type        : System.Management.Automation.RuntimeException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : A Using variable cannot be retrieved. A Using variable can be used only with Invoke-Command,
Start-Job, or InlineScript in the script workflow. When it is used with Invoke-Command, the Using variable is valid
only if the script block is invoked on a remote computer.
            HResult : -2146233087
        CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : UsingWithoutInvokeCommand
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : -1
            Line             : Write-Host $using:data
            PositionMessage  : At line:1 char:1
                               + Write-Host $using:data
                               + ~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite  :
        Name          : GetUsingValue
        DeclaringType : System.Management.Automation.VariableOps, System.Management.Automation, Version=7.2.0.500,
Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : A Using variable cannot be retrieved. A Using variable can be used only with Invoke-Command,
Start-Job, or InlineScript in the script workflow. When it is used with Invoke-Command, the Using variable is valid
only if the script block is invoked on a remote computer.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.VariableOps.GetUsingValue(MutableTuple tuple, String usingExpressionKey, Int32
index, ExecutionContext context)
   at System.Management.Automation.Interpreter.FuncCallInstruction`5.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : UsingWithoutInvokeCommand
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : Write-Host $using:data
    PositionMessage  : At line:1 char:1
                       + Write-Host $using:data
                       + ~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by PaulHigin**
# PR Summary

This change fixes #16445, where using variables were not being evaluated correctly when the -Parallel script block is passed in as a variable.

## PR Context

ForeEach-Object -Parallel using variable processing walks the script block AST to determine if the using variable was defined in the current scope, and does this by tracking the number of 'ForEach-Object -Parallel' commands in the call chain.
However, the provided script block is different, depending on whether it is passed in as a variable or via parameter binding.

```powershell
$myScript = '"Hello!"'
1 | ForEach-Object -Parallel ([scriptblock]::Create($myScript))
# Script block Ast does not contain the 'ForEach-Object' command in the call chain

1 | ForEach-Object -Parallel { "Hello!" }
# Script block Ast does contain the 'ForEach-Object' command in the call chain
```

This change takes into account the two forms of script blocks

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/engine/hostifaces/PSTask.cs [hunk 1]
```diff
@@ -192,6 +192,7 @@ internal sealed class PSJobTask : PSTaskBase
         /// <param name="dollarUnderbar">Dollar underbar variable value for script block.</param>
         /// <param name="currentLocationPath">Current working directory.</param>
         /// <param name="job">Job object associated with task.</param>
+        /// </summary>
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/hostifaces/PSTask.cs:195]: Typo? We already have the tag above.

File: src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs [hunk 2]
```diff
@@ -336,6 +336,9 @@ private ScriptBlockToPowerShellConverter()
             // Foreach-Object -Parallel call scope. This will filter the using variable map to variables 
             // only within the current (outer) Foreach-Object -Parallel call scope.
             var usingAsts = UsingExpressionAstSearcher.FindAllUsingExpressions(scriptBlock.Ast).ToList();
+            // If the scriptblock ast parent is null, then it comes from a scriptblock variable and does
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs:339]:
```suggestion

            // If the scriptblock ast parent is null, then it comes from a scriptblock variable and does
```

**Comment by iSazonov** [comment]
Could you please clarify why do we need to support `$using` if Foreach-Object execute the script block in _current_ scope.

**Comment by PaulHigin** [comment]
@iSazonov  The `$using` keyword is only supported for `ForEach-Object` and the `-Parallel` parameter set, in which case the script block is executed in multiple runspaces in parallel.  Since runspaces are isolation units, the `$using` keyword is needed to pass in variables from the current session to each parallel runspace sessions, similar to how it is used for remoting.  Otherwise they would need to be passed in via the argument list.

**Comment by iSazonov** [comment]
Do you mean `Foreach-Object` execute the scriptblock in current scope and `Foreach-Object` execute the scriptblock in another scope?
image


If so, we got a very confusing UX. :-( 
Ex.: an user has large scriptblock, add -Parallel switch and now the scriptblock doesn't work.

**Comment by PaulHigin** [comment]
?? This is all discussed in the RFC created for this feature.

https://github.com/PowerShell/PowerShell-RFC/pull/194

**Comment by iSazonov** [comment]
> ?? This is all discussed in the RFC created for this feature.
> 
> [PowerShell/PowerShell-RFC#194](https://github.com/PowerShell/PowerShell-RFC/pull/194)

:-) Yes, and I objected to this `$using` support. I believe that the feedback now clearly shows the UX and performance issues. We should consider designing a new cmdlet to address these requests.

**Comment by PaulHigin** [comment]
@daxian-dbw  Please review.

File: src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs [hunk 3]
```diff
@@ -336,6 +336,10 @@ private ScriptBlockToPowerShellConverter()
             // Foreach-Object -Parallel call scope. This will filter the using variable map to variables 
             // only within the current (outer) Foreach-Object -Parallel call scope.
             var usingAsts = UsingExpressionAstSearcher.FindAllUsingExpressions(scriptBlock.Ast).ToList();
+            
+            // If the scriptblock ast parent is null, then it comes from a scriptblock variable and does
+            // not include the initiating Foreach-Object -Parallel command.
+            bool astIncludesForEachCommand = scriptBlock.Ast.Parent is not null;
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs:342]: The following script also fails today, but the script block AST's parent is not null:
```
PS:9> $data = "hi"
>> $sb = { Write-Host $using:data }
>> 1 | forEach-Object -Parallel $sb
InvalidOperation: A Using variable cannot be retrieved. A Using variable can be used only with Invoke-Command, Start-Job, or InlineScript in the script workflow. When it is used with Invoke-Command, the Using variable is valid only if the script block is invoked on a remote computer.
[C:\]
PS:10> $sb.Ast.Parent

ScriptBlock                StaticType                               Extent                     Parent
-----------                ----------                               ------                     ------
{ Write-Host $using:data } System.Management.Automation.ScriptBlock { Write-Host $using:data } { Write-Host $using:data }
```
It doesn't seem this scenario is handled by this test, does it?

**Review by daxian-dbw — CHANGES_REQUESTED** [review]

**Comment by daxian-dbw** [comment]
@iSazonov `ForEach-Object -Parallel` runs the given script block in a separate Runspsace, so of course the script block will not run in the current scope.

**Comment by daxian-dbw** [comment]
@PaulHigin Can you please also review #12378 and see if that can be closed after your fix.

File: src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs (hunk 3 above)
Comment (PaulHigin) [reply src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs:342]: Yes, it does not handle this case `$sb = { ... }`.  There may other variations as well.  I can try looking for an assignment statement as well.

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs:342]: Yep, there will be other variants, such as a script block returned from a function ...
I will look closely later today and see if I can provide any suggestions.

Comment (PaulHigin) [reply src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs:342]: I am working on a fix now.  Thanks for pointing this out.

**Comment by PaulHigin** [comment]
@daxian-dbw   #12378 is a different issue.

File: src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs [hunk 4]
```diff
@@ -413,34 +478,10 @@ private ScriptBlockToPowerShellConverter()
             while (currentParent != null)
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs:478]: You can avoid `foreachNestedCount` and `CheckScriptBlockForForeachCommand` if you make this check to be `while (currentParent != scriptBlock.Ast)`.

That while-check means the inspection goes up the AST chain until it reaches at the `ScriptBlockAst` that is going to be executed, so as soon as you find one `ForEach-Object -Parallel` during this walkup, you will know the `usingAst` is in a nested `ForEach-Object -Parallel` and can return false.

File: src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs [hunk 5]
```diff
@@ -382,16 +383,80 @@ private ScriptBlockToPowerShellConverter()
...
+        private static readonly string[] forEachNames = new string[]
+        {
+            "ForEach-Object",
+            "foreach",
+            "%"
+        };
+
+        private static bool FindForEachInCommand(CommandAst commandAst)
+        {
+            foreach (var commandElement in commandAst.CommandElements)
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs:399]: I think you should only check on the first `CommandElement` since only that one is considered to be the command name. For example, I think a `CommandAst` representing `abc foreach -Parallel` will make this method return `true`.

**Review by daxian-dbw — CHANGES_REQUESTED** [review]

**Comment by PaulHigin** [comment]
@daxian-dbw  ping...

**Review by daxian-dbw — APPROVED** [review]

**Comment by PaulHigin** [comment]
@daxian-dbw  Thanks for the review!

**Comment by TravisEz13** [comment]
@PowerShell/powershell-maintainers 
We only take security fixes and regression to LTS.  This is appropriate for 7.3.  Rejecting back-port.

Allow some bake time and reconsider to verify that this is stable.

**Comment by SeeminglyScience** [comment]
@TravisEz13 Just to clarify this one was actually a regression (worked in 7.1.5, broke in 7.2, thank you @jborean93). Unsure if that was discussed in the meeting but if not, it may be worth another pass.

**Comment by PaulHigin** [comment]
The progressive changes include not only the regression, but also new behavior.  So I feel backporting this to LTS branches is risky, and that we should at least wait for it to bake longer in preview versions.

**Comment by iSazonov** [comment]
@adityapatwardhan Ping!

**Comment by adityapatwardhan** [comment]
This is in the backlog.. Currently working on fixing the build break in 7.2.6
