### PR TITLE
Fixing API set versioning to get PowerShell Core working on Windows 7

### LINKED ISSUE #1705: Win7SP1 x64 PowerShell.exe crash
I built using the Win7 CoreCLR runtime.

`Start-PSBuild -Runtime win7-x64`

pasted image at 2016_08_09 06_44 pm

### PR DESCRIPTION
**Pull request by mirichmo**
Fixes #1705 by correcting the API set versions used to match those shipped with CoreCLR's downlevel API set package.

This makes it possible to run PS on Win 7.
I verified remoting with WMF 4.0 and ran the Nano Server test pass against it. I got an 83% pass rate, so there are additional issues to resolve for Win 7.

### CODE REVIEW

File: src/System.Management.Automation/CoreCLR/CorePsExtensions.cs [hunk 1]
```diff
@@ -1227,12 +1227,12 @@ private static class Win32Native
             // Win32 return type is BOOLEAN (which is 1 byte and not BOOL which is 4bytes)
             internal static extern byte GetUserNameEx(int format, [Out] StringBuilder domainName, ref uint domainNameLen);
 
-            [DllImport("api-ms-win-core-localization-l1-2-1.dll", CharSet = CharSet.Unicode)]
+            [DllImport("api-ms-win-core-localization-l1-2-0.dll", CharSet = CharSet.Unicode)]
```
Comment (lzybkr) [inline src/System.Management.Automation/CoreCLR/CorePsExtensions.cs]: Can we replace the string literal with the constant from `PinvokeDllNames`?

File: src/System.Management.Automation/utils/PInvokeDllNames.cs [hunk 2]
```diff
@@ -40,70 +40,70 @@ internal static class PinvokeDllNames
...
         internal const string GetConsoleOutputCPDllName = "api-ms-win-core-console-l1-1-0.dll";              /*85*/
-        internal const string GetConsoleWindowDllName = "api-ms-win-core-kernel32-legacy-l1-1-1.dll";        /*86*/
-        internal const string GetDCDllName = "ext-ms-win-ntuser-dc-access-ext-l1-1-0.dll";                   /*87*/
-        internal const string ReleaseDCDllName = "ext-ms-win-ntuser-dc-access-ext-l1-1-0.dll";               /*88*/
-        internal const string TranslateCharsetInfoDllName = "ext-ms-win-gdi-font-l1-1-1.dll";                /*89*/
-        internal const string GetTextMetricsDllName = "ext-ms-win-gdi-font-l1-1-1.dll";                      /*90*/
-        internal const string GetCharWidth32DllName = "ext-ms-win-gdi-font-l1-1-1.dll";                      /*91*/
+        internal const string GetConsoleWindowDllName = "api-ms-win-core-kernel32-legacy-l1-1-0.dll";        /*86*/
+        internal const string GetDCDllName = "ext-ms-win-ntuser-dc-access-ext-l1-1-0.dll";                   /*87*/ // This DLL is not shipped as a downlevel forwarder, so we might want to revert to user32.dll
```
Comment (daxian-dbw) [inline src/System.Management.Automation/utils/PInvokeDllNames.cs]: > // This DLL is not shipped as a downlevel forwarder, so we might want to revert to user32.dll

Revert to user32.dll/kernel32.dll will break it on NanoServer and IoT, so maybe we need `Platform.IsInbox` for situations like this. Do we have an issue for this? Leave those "action-required" comments in code without a tracking issue is not very good, because we will soon forget this comment and it would be quite confusing for future maintainers.

And also, would it break on NanoServer and IoT by changing the versions of some API set dlls?

File: src/System.Management.Automation/CoreCLR/CorePsExtensions.cs (hunk 1 above)
Comment (mirichmo) [inline src/System.Management.Automation/CoreCLR/CorePsExtensions.cs]: Fixed

File: src/System.Management.Automation/utils/PInvokeDllNames.cs (hunk 2 above)
Comment (mirichmo) [inline src/System.Management.Automation/utils/PInvokeDllNames.cs]: I created issue #2091 to track the issue you brought up. It needs additional research, but should not block this PR to establish initial Win 7 support.

**Comment by daxian-dbw** [comment]
LGTM.
