### PR TITLE
Fallback to `CopyAndDelete()` when `MoveTo()` fails due to an IOException

### LINKED ISSUE #15072: Move-Item: Move directory to another drive fails
## Steps to reproduce

```powershell
Move-Item -LiteralPath 'D:\work\testdir' -Destination 'I:\work\testdir'
```

`D:` and `I:` are just two different simple volume on two different HDD, not DFS or something.

## Expected behavior
Directory `testdir` is moved from `D:` to `I:` without error, which is the case with PowerShell-7.2.0-**preview.3**.

```none
PS D:\tools\PowerShell-7.2.0-preview.3-win-x64> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.3
PSEdition                      Core
GitCommitId                    7.2.0-preview.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS D:\tools\PowerShell-7.2.0-preview.3-win-x64> Get-ChildItem -LiteralPath 'D:\work'

    Directory: D:\work

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2021/03/20    21:47                testdir

PS D:\tools\PowerShell-7.2.0-preview.3-win-x64> Get-ChildItem -LiteralPath 'I:\work'
PS D:\tools\PowerShell-7.2.0-preview.3-win-x64> Move-Item -LiteralPath 'D:\work\testdir' -Destination 'I:\work\testdir'
PS D:\tools\PowerShell-7.2.0-preview.3-win-x64> Get-ChildItem -LiteralPath 'D:\work'
PS D:\tools\PowerShell-7.2.0-preview.3-win-x64> Get-ChildItem -LiteralPath 'I:\work'

    Directory: I:\work

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2021/03/20    21:59                testdir

PS D:\tools\PowerShell-7.2.0-preview.3-win-x64>
```

## Actual behavior
In PowerShell-7.2.0-**preview.4**, Move-Item returns error.

```none
PS D:\tools\PowerShell-7.2.0-preview.4-win-x64> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.4
PSEdition                      Core
GitCommitId                    7.2.0-preview.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS D:\tools\PowerShell-7.2.0-preview.4-win-x64> Get-ChildItem -LiteralPath 'D:\work'

    Directory: D:\work

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2021/03/20    21:59                testdir

PS D:\tools\PowerShell-7.2.0-preview.4-win-x64> Get-ChildItem -LiteralPath 'I:\work'
PS D:\tools\PowerShell-7.2.0-preview.4-win-x64> Move-Item -LiteralPath 'D:\work\testdir' -Destination 'I:\work\testdir'
Move-Item: Source and destination path must have identical roots. Move will not work across volumes.
PS D:\tools\PowerShell-7.2.0-preview.4-win-x64> Get-ChildItem -LiteralPath 'D:\work'

    Directory: D:\work

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2021/03/20    21:59                testdir

PS D:\tools\PowerShell-7.2.0-preview.4-win-x64> Get-ChildItem -LiteralPath 'I:\work'
PS D:\tools\PowerShell-7.2.0-preview.4-win-x64>
```

Error details
```none
PS D:\tools\PowerShell-7.2.0-preview.4-win-x64> Get-Error

Exception             :
    Type       : System.IO.IOException
    TargetSite :
        Name          : MoveTo
        DeclaringType : System.IO.DirectoryInfo
        MemberType    : Method
        Module        : System.IO.FileSystem.dll
    StackTrace :
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Microsoft.PowerShell.Commands.FileSystemProvider.MoveDirectoryInfoUnchecked(DirectoryInfo directory, String destinationPath, Boolean force)
   at Microsoft.PowerShell.Commands.FileSystemProvider.MoveDirectoryInfoItem(DirectoryInfo directory, String destination, Boolean force)
    Message    : Source and destination path must have identical roots. Move will not work across volumes.
    Source     : System.IO.FileSystem
    HResult    : -2146232800
TargetObject          : D:\work\testdir
CategoryInfo          : WriteError: (D:\work\testdir:DirectoryInfo) [Move-Item], IOException
FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand
InvocationInfo        :
    MyCommand        : Move-Item
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 4
    Line             : Move-Item -LiteralPath 'D:\work\testdir' -Destination 'I:\work\testdir'
    PositionMessage  : At line:1 char:1
                       + Move-Item -LiteralPath 'D:\work\testdir' -Destination 'I:\work\testdi …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Move-Item
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```
In my quick analysis, #14913 may affect this issue. DirectoryInfo.MoveTo returns IOException with `HResult = -2146232800(0x80131620)`, not `-2147024891(0x80070005)`, which fallback condition for CopyAndDelete expects.

## Environment data

```none
PS D:\tools\PowerShell-7.2.0-preview.4-win-x64> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.4
PSEdition                      Core
GitCommitId                    7.2.0-preview.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

The PR https://github.com/PowerShell/PowerShell/pull/14913 introduced a regression by removing some Windows specific code thinking it was no longer needed.  That code checked if the root of a file path starts with the same drive letter and if not, uses `CopyAndDelete()` as `MoveTo()` would fail.  This change instead will use `CopyAndDelete()` for any `IOException`.  Based on the .NET code, there's only two cases where `IOException` is raised for `MoveTo()` so falling back to `CopyAndDelete()` is fine for these two cases.

A new test was added leveraging `subst` to emulate different drive volumes on Windows.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/15072

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 1]
```diff
@@ -6074,24 +6074,43 @@ protected override bool IsItemContainer(string path)
...
-            try
+            if (!IsSameWindowsVolume(directory.FullName, destinationPath))
             {
-                if (InternalTestHooks.ThrowExdevErrorOnMoveDirectory)
-                {
-                    throw new IOException("Invalid cross-device link", hresult: MOVE_FAILED_ERROR);
-                }
-
-                directory.MoveTo(destinationPath);
+                CopyAndDelete(directory, destinationPath, force);
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:6079]: I again very wonder why we do the check if .Net DirectoryInfo.MoveTo() method already does this for us and throw IOException? https://github.com/dotnet/runtime/blob/82ca681cbac89d813a3ce397e0c665e6c051ed67/src/libraries/System.IO.FileSystem/src/System/IO/DirectoryInfo.cs#L212-L216
So why beat around the bush?
This method behaves the same for both Unix and Windows - no need to have two code paths.
We only need to exclude the fallback to CopyAndDelete() for FileNotFoundException, DirectoryNotFoundException, PathTooLongException, and SecurityException (not UnauthorizedAccessException!).
It may be a more aggressive fallback for unknown IO errors that wraps a driver errors - what's wrong with that if we use the same template anyway - try and fallback?

Comment (SteveL-MSFT) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:6079]: I missed that, we can certainly check for that specific error instead of having this method

Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:6079]: What do you see dangerous in the call to CopyAndDelete() in the case of these IOException-s? In the best case, the tree will be moved, in the worst case, we will receive an exception and can return an error to the user.

Comment (PaulHigin) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:6079]: You could just early return here, and remove the `else` block.

**Review by PaulHigin — APPROVED** [review]
Minor comment.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 1 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs]: ok, looking at the .NET code, it seems reasonable to try CopyAndDelete for the 2 cases of IOException

Comment (SteveL-MSFT) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs]: With the simplification of the code, this is no longer relevant as there isn't an `else` clause

Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs]: I think it makes no sense to fallback to CopyAndDelete for FileNotFoundException, DirectoryNotFoundException, PathTooLongException, SecurityException and UnauthorizedAccessException - it is better to re-throw and write an error message in MoveDirectoryInfoItem() as previously.

**Review by adityapatwardhan — APPROVED** [review]

**Comment by iSazonov** [comment]
My comment https://github.com/PowerShell/PowerShell/pull/15077#discussion_r600227620 was not addressed but it _must_ otherwise we have a regression.
