### PR TITLE
Fix -NoEnumerate behaviour in Write-Output

### LINKED ISSUE #5955: Write-Output -NoEnumerate outputs PSObject[] rather than Object[] and generally doesn't respect the input collection type
<sup>Related: #5122</sup>

* `Write-Output -NoEnumerate`, when given a collection, always returns a `PSObject[]` rather than a regular `object[]]` array, which is unexpected.

* Additionally, this means that if a different collection type such as `[System.Collections.ArrayList]` was passed, it is _not_ preserved.
  * [`Write-Output`'s documentation](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Write-Output.md), which currently only states, "prevents Write-Output from enumerating output", which **sounds like the input collection - whatever its type - is simply _passed through_** - a sensible expectation that _Windows PowerShell_ versions up to v5.1  indeed honor.

I suspect this regression is a consequence of the ill-fated #2038 PR that arose out of issue #2035.

Steps to reproduce
------------------

```powershell
(Write-Output -NoEnumerate 1, 2).GetType().Name
(Write-Output -NoEnumerate ([System.Collections.ArrayList] (1, 2))).GetType().Name
```

Expected behavior
-----------------

```none
Object[]
ArrayList
```

This is how it still works in _Windows PowerShell_ v5.1

Actual behavior
---------------

```none
PSObject[]
PSObject[]
```

As stated, this affects PS _Core_ only.

Environment data
----------------

```powershell
PowerShell Core v6.0.0 on macOS 10.13.2
PowerShell Core v6.0.0 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.0 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

### PR DESCRIPTION
**Pull request by vexx32**
# PR Summary

Write-Output's `InputObject` parameter was typed as `PSObject[]`. This was forcing **all** collections to be enumerated during parameter binding, making `-NoEnumerate` essentially useless; use of the switch would result in a `PSObject[]`-typed output collection instead of the usual `object[]`, but it was completely impossible to retain the original collection(s) via the switch.

Fixes #5955, a long-standing regression from Windows PowerShell.

Adds regression test.

~~As I was digging through the underlying code before I came upon the true cause, I also came across a pair of methods with names that are just _asking_ for misinterpretation. I renamed one of the pairs, the pair with only one reference each. As they are private methods, I doubt this will affect anything much, but it should make maintaining those code paths less confusing going forward.~~ Moved to #9074.

## PR Context

See issue #5955 for context.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

File: src/System.Management.Automation/engine/MshCommandRuntime.cs [hunk 1]
```diff
@@ -249,7 +249,7 @@ public void WriteObject(object sendToPipeline, bool enumerateCollection)
 
 #if CORECLR
             // SecurityContext is not supported in CoreCLR
-            DoWriteObjects(sendToPipeline);
+            DoWriteEnumeratedObject(sendToPipeline);
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/MshCommandRuntime.cs]: Please make new PR for cleanups.

Comment (vexx32) [reply src/System.Management.Automation/engine/MshCommandRuntime.cs]: Yeah, I suppose that makes the most sense. I'll cut&paste this commit to another PR. 🙂

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this.  We agree that we should fix this to get back to the Windows PowerShell behavior which is the correct behavior.

**Comment by iSazonov** [comment]
@vexx32 Please open new issue in Docs repo if needed.

**Review by PaulHigin — APPROVED** [review]
LGTM

**Comment by iSazonov** [comment]
@mklement0 Could you please look the PR before we merge?

**Comment by daxian-dbw** [comment]
The parameter type of `InputObject` for `Write-Output` is `psobject[]` on Windows PowerShell, and it behaves as expected:
```
PS:3> (Write-Output -NoEnumerate 1, 2).GetType().Name
Object[]
PS:4> (Write-Output -NoEnumerate ([System.Collections.ArrayList] (1, 2))).GetType().Name
ArrayList
```
So I wonder what is the actual change that breaks it on PowerShell Core ...

**Comment by iSazonov** [comment]
> So I wonder what is the actual change that breaks it on PowerShell Core …

Perhaps https://github.com/PowerShell/PowerShell/issues/2035

**Comment by vexx32** [comment]
@daxian-dbw Yeah, I can see where that's confusing... And knowing what PSObject is for more than I used to, I think it makes more sense behaving as it currently does... but I am _very_ sure that sentiment wouldn't necessarily be shared by most PowerShell users.

**Comment by daxian-dbw** [comment]
Yes, the regression was caused by #2038. See another related issue: #5122
Unfortunately, due to #2038, `Write-Output` still doesn't behave completely the same as on Windows PowerShell even with this PR:

```
# on windows powershell
(Write-Output -NoEnumerate 1).GetType().FullName
> System.Int32
```
```
# on powershell core with this PR
(Write-Output -NoEnumerate 1).GetType().FullName
> System.Collections.Generic.List`1[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
```

**Comment by vexx32** [comment]
@daxian-dbw I shall do some digging to where that occurs and what can be done about it.

**Comment by daxian-dbw** [comment]
@vexx32 After #2038, the remaining argument are handled in a similar way as `params` in C#:
if the remaining argument is a collection, then use that collection directly, otherwise, wrap the argument(s) to a `List<object>`.
I double there is anything we can do in `Write-Output` to make behave the same as in Windows PowerShell in those particular cases :(

**Comment by vexx32** [comment]
Hmm. I guess that makes some sense.

It does seem rather unlikely that folks would _deliberately_ use -NoEnumerate and then _not_ expect a collection to be the result. :thinking:

**Comment by iSazonov** [comment]
Make alternative attribute?

**Comment by PrzemyslawKlys** [comment]
Maybe instead of fixing Write-Output -NoEnumerate (which would be nice of course) behavior for  [OutputType()] could be changed to keep output type untouched if it's defined. Right now even without  [OutputType()] defined you still get unwrap for a single object.

**Comment by vexx32** [comment]
Not sure I follow what you mean there. That attribute generally is metadata and more of a documentation attribute that anything else. As far as I know, it has no effect during execution.

**Comment by PrzemyslawKlys** [comment]
I see. Well, I thought that it's more than metadata. And the only reason I would use NoEnumerate is to preserve Array on function return. If it has other uses, that's cool too. 

What I mean is, if that change wouldn't go thru because of other reasons I would still want some other way to have that feature. If it goes thru, that's great.

**Comment by vexx32** [comment]
Gotcha. Yeah, that might work on a surface level. Unfortunately it would probably mean enumerating the collection twice (once in the parameter binder -> PSObject[], and once before output -> OutputType) which is a bit much imo.

It would also not be retaining the original collection, so if it originally had NoteProperty or other ETS members, they would be stripped. In the few cases where -NoEnumerate are needed, this might be one motivation for using it.

**Review by daxian-dbw — APPROVED** [review]
LGTM
