### PR TITLE
Fix Hyper-V Remoting when using remoting import

### LINKED ISSUE #24014: Enter-PSSession with VMName gives cast error
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Enter-PSSession -VMName 'testvm' -Credential $credential ends with an error message. Changing the VMName or omit the Credential flag doesn't fix it. 

### Expected behavior

```console
Shell into guest vm
```

### Actual behavior

```console
Error: "Enter-PSSession: Unable to cast object of type 'System.String' to type 'VMState'."
```

### Error details

```console
Exception             :
    Type       : System.InvalidCastException
    TargetSite :
        Name          : GetRunspaceForVMSession
        DeclaringType : [Microsoft.PowerShell.Commands.EnterPSSessionCommand]
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message    : Unable to cast object of type 'System.String' to type 'VMState'.
    Source     : System.Management.Automation
    HResult    : -2147467262
    StackTrace :
   at Microsoft.PowerShell.Commands.EnterPSSessionCommand.GetRunspaceForVMSession()
   at Microsoft.PowerShell.Commands.EnterPSSessionCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Enter-PSSession], InvalidCastException
FullyQualifiedErrorId : System.InvalidCastException,Microsoft.PowerShell.Commands.EnterPSSessionCommand
InvocationInfo        :
    MyCommand        : Enter-PSSession
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 9
    Line             : Enter-PSSession -VMName 'testvm' -Credential $credential
    Statement        : Enter-PSSession -VMName 'testvm' -Credential $credential
    PositionMessage  : At line:1 char:1
                       + Enter-PSSession -VMName 'testvm' -Credential $credential
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Enter-PSSession
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by jborean93**
# PR Summary
When on a Windows version that cannot load the Hyper-V module the State property will be of the string type. This change ensures that PowerShell can still parse this value to the VMState type as expected when the module was loaded natively. This should allow PSRemoting cmdlets that call Get-VM to properly get the VM State property.

## PR Context
Fixes: https://github.com/PowerShell/PowerShell/issues/24014

I don't have a Server 2016 host to test against but it seems like the only other props used from `Get-VM` are a `String` and `Guid` types which should work without any issues in an implicitly remoted module import.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
  - [x] None
  - **OR**
  - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
    - [ ] Experimental feature name(s): 
- **User-facing changes**
  - [x] Not Applicable
  - **OR**
  - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
  - [x] N/A or can only be tested interactively
  - **OR**
  - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
  - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
  - **OR**
  - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
    - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
      - [ ] Issue filed: 
    - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
      - [ ] Issue filed: 
    - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
      - [ ] Issue filed: 
    - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
      - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs [hunk 1]
```diff
@@ -445,6 +445,40 @@ internal enum VMState
...
+            else if (rawState is string stringState && Enum.TryParse(stringState, true, out VMState result))
+            {
+                // If the Hyper-V module was imported through implicit remoting on old
+                // Windows versions we get a string back which we will try and parse
+                // as the enum label.
+                return result;
+            }
+
+            // Unknown scenario, this should not happen.
+            return null;
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs:478]: Same here, please throw an exception about the unexpected value in case this happens.

File: src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs [hunk 2]
```diff
@@ -445,6 +445,40 @@ internal enum VMState
...
+                return null;
+            }
+
+            object? rawState = stateProps[0].Value;
+            if (rawState is Enum enumState)
+            {
+                // If the Hyper-V module was directly importable we have the VMState enum
+                // value which we can just cast to our VMState type.
+                return (VMState)enumState;
+            }
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs:468]: Will this work?
```suggestion
            if (rawState is VMState result)
            {
                // If the Hyper-V module was directly importable we have the VMState enum
                // value which we can just cast to our VMState type.
                return result;
            }
```

**Review by daxian-dbw — CHANGES_REQUESTED** [review]

File: src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs (hunk 2 above)
Comment (jborean93) [reply src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs:468]: Unfortunately no, `VMState` is an enum defined in this class whereas the `Hyper-V` module returns its own enum type. So this is checking if the value is an enum and casts it to the copy of it here. The alternative is making a dep on whatever library the Hyper-V modules are using which I don't think is really possible.

File: src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs (hunk 1 above)
Comment (jborean93) [reply src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs:478]: What about the check at the start of the method when there is no `State` property on the `PSObject`?

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs:478]: It seems one of my comments was not posted as expected :) Added.

File: src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs [hunk 3]
```diff
@@ -445,6 +445,40 @@ internal enum VMState
...
+        /// <returns>The VMState value of the State property if present and parsable, otherwise null.</returns>
+        internal VMState? GetVMStateProperty(PSObject value)
+        {
+            ReadOnlyPSMemberInfoCollection<PSPropertyInfo> stateProps = value.Properties.Match("State");
+            if (stateProps.Count == 0)
+            {
+                return null;
+            }
+
+            object? rawState = stateProps[0].Value;
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs:462]: It seems we are expecting the "State" property exists and the code doesn't handle the case when it doesn't exist, so can you get the raw state just like before the change? (I assume `value.Properties["State"]` would throw when the property name doesn't exist, but didn't check to be sure)

```suggestion
            object? rawState =value.Properties["State"].Value;
```

File: src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs (hunk 2 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs:468]: That's good to know.

File: src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs (hunk 3 above)
Comment (jborean93) [reply src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs:462]: Sure I can change it back to just getting the value and having it throw. I added this check before as a way to not have it fail if the returned object was not expected but can easily change it back.

Comment (jborean93) [reply src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs]: Updated to just get the state through the indexer so it'll throw that way now.

File: src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs (hunk 1 above)
Comment (jborean93) [reply src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs]: Updated to throw `InvalidOperationException` if it's null or a type we don't expect.

**Review by daxian-dbw — APPROVED** [review]
LGTM!
