### PR TITLE
Fix FileSystemProvider to work with volume and pipe paths

### LINKED ISSUE #15872: Get-ChildItem of (Get-Volume) Paths does not work as expected
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

During the creation of a module, I run back and forth between 5.1 and pwsh (currently 7.1.3) to make sure the module will work in both versions.

While running in PWSH-7.1.3:

$ISO = 'C:\WindowsImages\Win10_21H1_English_x64.iso'
$Drive = Mount-DiskImage $ISO -StorageType ISO -NoDriveLetter -PassThru
gci -LiteralPath (Get-Volume | ?{($_.DriveType -match 'CD') -and ($_.Size -match $Drive.Size)}).Path -fo -re

I get back a live list of all the files found in 'C:\'

### Expected behavior

```console
In powershell 5.1, I get back all the files found in:

Directory: \\?\Volume{1a1cbe60-f411-11eb-aec7-001a7dda7113}
```

### Actual behavior

```console
In PWSH 7.1.3, I get back all the files found in:

Directory: C:\
```

### Error details

```console
No Errors, I just dont get the correct results path in PWSH
```

### Environment data

```powershell
Name                           Value                                                                                                  
----                           -----                                                                                                  
PSVersion                      5.1.19041.1023                                                                                         
PSEdition                      Desktop                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                
BuildVersion                   10.0.19041.1023                                                                                        
CLRVersion                     4.0.30319.42000                                                                                        
WSManStackVersion              3.0                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                    
SerializationVersion           1.1.0.1                                                                                                


&



Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Powershell 5.1

image

Powershell 7.1.3

image

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

A change in the FileSystemProvider to get the correct casing for a path regressed working with NTFS volume paths that start with `\\?\` as it's not a UNC path so skips that handling.  Also, the logic for handling a trailing directory separator relied on there to be no content so something like: "c:\\foo\\\\bar" would handle this incorrectly.

Fix is to skip the first parts of the path even if it's not a UNC path, but starts with "\\\\?\\".  Then we only check for empty content if we are at the end of the path to handle trailing separator correctly.

Also supports `\\.\pipe` on Windows

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/15872

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 1]
```diff
@@ -123,28 +123,29 @@ private static string GetCorrectCasedPath(string path)
             {
                 string exactPath = string.Empty;
                 int itemsToSkip = 0;
-                if (Utils.PathIsUnc(path))
+                if (Utils.PathIsUnc(path) || path.StartsWith("\\\\?\\"))
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:126]: Oh, I am not like the change because it is seem _partial_ - general PowerShell design is to bypass paths started with `\\?\`. So I'd expect the check is done in PathIsUnc() but the last method is used 17 times and there are contradictions. For example, there is IsValidPath() method and PathIsNetworkPath(). 
Also I see we never test and review all scenarios with `\\?\`.

Notice, cmd.exe is not support the scenario too
```
C:\>dir \\?\Volume{0qq60da1-0000-0000-0000-100000000000}\
The parameter is incorrect.
```

**Comment by fMichaleczek** [comment]
@SteveL-MSFT Maybe good to take the [#11898](https://github.com/PowerShell/PowerShell/issues/11898) in consideration while resolving this path problem.

Both examples work on Windows PowerShell
```
Get-ChildItem '//./pipe/'
Get-ChildItem '\\.\pipe\'
```

Found in this Rancher Wins documentation
https://github.com/rancher/wins#examples

**Comment by iSazonov** [comment]
I'd merge #14469 first. Then we could start moving to new .Net API with #12834 and continue with other scenarios. After all, it would have corrected most of the issues we know in FileSystem provider.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 1 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:126]: I originally thought about putting it in `PathIsUnc()`, but it's technically not UNC so didn't.  However, I don't think there's anything functionally different from a UNC path that just happens to point to a local location, so it probably makes sense to encapsulate it there.

Comment (SteveL-MSFT) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:126]: Looks like we already handle `wsl$` path in `PathIsUnc()` so makes even more sense to have it there

File: src/System.Management.Automation/engine/Utils.cs [hunk 2]
```diff
@@ -1293,8 +1293,8 @@ internal static bool PathIsUnc(string path)
                 return false;
             }
 
-            // handle special cases like \\wsl$\ubuntu which isn't a UNC path, but we can say it is so the filesystemprovider can use it
-            if (path.StartsWith(WslRootPath, StringComparison.OrdinalIgnoreCase))
+            // handle special cases like \\wsl$\ubuntu and \\?\ which aren't a UNC path, but we can say it is so the filesystemprovider can use it
+            if (path.StartsWith(WslRootPath, StringComparison.OrdinalIgnoreCase) || path.StartsWith("\\\\?\\"))
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/Utils.cs:1297]: `internal static bool PathIsNetworkPath(string path)` now return true for the volume path. Is it ok?

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/Utils.cs:1297]: I'll review all the uses of that to make sure

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/Utils.cs:1297]: This will cause some problems as the usage expects it to only be a network path.  My plan is to add a paraneter to `PathIsUnc(bool networkOnly = false)` that can be used in a single wrapper function so that only UNC returns true and not WSL or `\\?\`

File: src/System.Management.Automation/engine/Utils.cs [hunk 3]
```diff
@@ -1294,7 +1294,7 @@ internal static bool PathIsUnc(string path)
             }
 
             // handle special cases like \\wsl$\ubuntu and \\?\ which aren't a UNC path, but we can say it is so the filesystemprovider can use it
-            if (path.StartsWith(WslRootPath, StringComparison.OrdinalIgnoreCase) || path.StartsWith("\\\\?\\"))
+            if (!networkOnly && (path.StartsWith(WslRootPath, StringComparison.OrdinalIgnoreCase) || path.StartsWith("\\\\?\\")))
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/Utils.cs:1297]: Makes sense to add `\\.\` too?

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/Utils.cs:1297]: I don't believe you can use the period to refer to the local computer as part of a UNC path, it has to be the computer name, localhost, 127.0.0.1, etc...

Comment (iSazonov) [reply src/System.Management.Automation/engine/Utils.cs:1297]: What about @fMichaleczek's example `Get-ChildItem '\\.\pipe\'`?

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/Utils.cs:1297]: That doesn't work for me even in WinPS 5.1

Comment (iSazonov) [reply src/System.Management.Automation/engine/Utils.cs:1297]: This works for me in WinPS 5.1 but not in cmd.exe.
image

Comment (iSazonov) [reply src/System.Management.Automation/engine/Utils.cs:1297]: /cc @jborean93

Comment (fMichaleczek) [reply src/System.Management.Automation/engine/Utils.cs:1297]: @iSazonov

```
\\ServerName\pipe\PipeName

where ServerName is either the name of a remote computer or a period, to specify the local computer.

```
The reference page : 
https://docs.microsoft.com/en-us/windows/win32/ipc/pipe-names

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/Utils.cs:1297]: Still not working for me, do I need to do something else?

image

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/Utils.cs:1297]: Ok, looks like the trailing backslash is REQUIRED

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/Utils.cs:1297]: I'll include `\\.\` and add a test

**Comment by iSazonov** [comment]
For reference #10805

**Comment by adityapatwardhan** [comment]
@SteveL-MSFT Can you resolve conflicts?

**Comment by SteveL-MSFT** [comment]
@adityapatwardhan fixed merge conflict

File: test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1 [hunk 4]
```diff
@@ -228,6 +228,18 @@ Describe "Get-ChildItem" -Tags "CI" {
             $barFiles = Get-ChildItem -Path testdrive:/foo/bar -Recurse
             $barFiles.Count | Should -Be 2
         }
+
+        It 'Works with Windows volume paths' -Skip:(!$IsWindows) {
+            $volume = (Get-Volume -DriveLetter $env:SystemDrive[0]).Path
+            $items = Get-ChildItem -LiteralPath "${volume}Windows"
+            $items[0].Parent | Should -BeExactly "${volume}Windows"
+            $items.Count | Should -Be (Get-ChildItem $env:SystemRoot).Count
```
Comment (adityapatwardhan) [inline test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1:236]:
```suggestion
            $items | Should -HaveCount (Get-ChildItem $env:SystemRoot).Count
```

**Review by adityapatwardhan — CHANGES_REQUESTED** [review]

**Review by adityapatwardhan — APPROVED** [review]
