### PR TITLE
Enhance Remove-Item to work with OneDrive (Third)

### LINKED ISSUE #15466: Remove-Item does not work correctly with long paths
From https://github.com/PowerShell/PowerShell/pull/15260#issuecomment-849160511.

`Rename-Item` and `Set-Location` are also affected by this issue.

## Steps to reproduce

```powershell
$testdrive = "$env:TEMP/test"
$longDir = 'a' * 250
$longSubDir = 'b' * 250
$fileName = "file1.txt"
$topPath = Join-Path $TestDrive $longDir
$longDirPath = Join-Path $topPath $longSubDir
$longFilePath = Join-Path $longDirPath $fileName
new-item -itemtype file -path $longFilePath -force
remove-item -Path $longFilePath
```

## Expected behavior

*file is removed successfully*

## Actual behavior

```none
> remove-item -Path $longFilePath
Remove-Item: The system cannot find the path specified.
C:\Users\rjmho
> get-error

Exception             :
    Type            : System.ComponentModel.Win32Exception
    NativeErrorCode : 3
    ErrorCode       : -2147467259
    TargetSite      :
        Name          : IsReparsePointLikeSymlink
        DeclaringType : Microsoft.PowerShell.Commands.InternalSymbolicLinkLinkCodeMethods
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace      :
   at Microsoft.PowerShell.Commands.InternalSymbolicLinkLinkCodeMethods.IsReparsePointLikeSymlink(FileSystemInfo
fileInfo) in System.Management.Automation.dll:token 0x60016f5+0x57
   at Microsoft.PowerShell.Commands.RemoveItemCommand.ProcessRecord() in
Microsoft.PowerShell.Commands.Management.dll:token 0x60004dd+0x2e2
   at System.Management.Automation.CommandProcessor.ProcessRecord() in System.Management.Automation.dll:token
0x60020f6+0x1ae
    Message         : The system cannot find the path specified.
    Source          : System.Management.Automation
    HResult         : -2147467259
CategoryInfo          : NotSpecified: (:) [Remove-Item], Win32Exception
FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.RemoveItemCommand
InvocationInfo        :
    MyCommand        : Remove-Item
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 4
    Line             : remove-item -Path $longFilePath
    PositionMessage  : At line:1 char:1
                       + remove-item -Path $longFilePath
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : remove-item
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

## Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.6
PSEdition                      Core
GitCommitId                    7.2.0-preview.6
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

## Proposed solution

Implement long paths:

```diff
diff --git a/src/System.Management.Automation/namespaces/FileSystemProvider.cs b/src/System.Management.Automation/namespaces/FileSystemProvider.cs
index b37b4d10c..da0e4cb2d 100644
--- a/src/System.Management.Automation/namespaces/FileSystemProvider.cs
+++ b/src/System.Management.Automation/namespaces/FileSystemProvider.cs
@@ -8243,6 +8243,12 @@ namespace Microsoft.PowerShell.Commands

             WIN32_FIND_DATA data = default;
             string fullPath = Path.TrimEndingDirectorySeparator(fileInfo.FullName);
+
+            if (fullPath.Length > MAX_PATH)
+            {
+                fullPath = "\\\\?\\" + fullPath;
+            }
+
             using (var handle = FindFirstFileEx(fullPath, FINDEX_INFO_LEVELS.FindExInfoBasic, ref data, FINDEX_SEARCH_OPS.FindExSearchNameMatch, IntPtr.Zero, 0))
             {
```

Also ensure that the actual file exists before calling the Windows API on it so that the proper error can be thrown if not:

https://github.com/PowerShell/PowerShell/blob/dd5cf8670a49dec25ce5763814efaf2092e321f8/src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs#L2701-L2702

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Fix #15466

Continue #15260

`EnsureExtendedPrefix` is copy-pasted from .Net Runtime repository.

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 1]
```diff
@@ -8216,28 +8230,55 @@ internal static bool IsReparsePoint(FileSystemInfo fileInfo)
...
+                    // Our handle could be invalidated by something else touching the filesystem,
+                    // so ensure we deal with that possibility here
+                    int lastError = Marshal.GetLastWin32Error();
+                    throw new Win32Exception(lastError);
+                }
+
+                // We already have the file attribute information from our Win32 call,
+                // so no need to take the expense of the FileInfo.FileAttributes call
+                const int FILE_ATTRIBUTE_REPARSE_POINT = 0x0400;
+                if ((data.dwFileAttributes & FILE_ATTRIBUTE_REPARSE_POINT) == 0)
```
Comment (jborean93) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:8264]: By doing this check before `FindFirstFileEx` you save a call from happening on the dir which can add up when dealing with SMB paths or lots of files in a recursive `gci`. We should add the `IsReparsePoint(fileInfo)` and return if `false` check before the `FindFirstFileEx` call to avoid all this.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 2]
```diff
@@ -8216,28 +8230,55 @@ internal static bool IsReparsePoint(FileSystemInfo fileInfo)
...
+            }
+
+            using (var handle = FindFirstFileEx(fullPath, FINDEX_INFO_LEVELS.FindExInfoBasic, ref data, FINDEX_SEARCH_OPS.FindExSearchNameMatch, IntPtr.Zero, 0))
             {
+                if (handle.IsInvalid)
+                {
+                    // Our handle could be invalidated by something else touching the filesystem,
+                    // so ensure we deal with that possibility here
+                    int lastError = Marshal.GetLastWin32Error();
+                    throw new Win32Exception(lastError);
```
Comment (jborean93) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:8258]: IIRC by omiting all arguments in the constructor `Win32Exception` does the `Marshal.GetLastWin32Error()` call. The current behaviour here ignores an error as well, this might introduce a failure that is currently ignored for this particular check.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 3]
```diff
@@ -8216,28 +8230,55 @@ internal static bool IsReparsePoint(FileSystemInfo fileInfo)
...
+                return !InternalTestHooks.OneDriveTestRecurseOn;
             }
-#if !UNIX
-            // It is a reparse point and we should check some reparse point tags.
-            var data = new WIN32_FIND_DATA();
-            using (var handle = FindFirstFileEx(fileInfo.FullName, FINDEX_INFO_LEVELS.FindExInfoBasic, ref data, FINDEX_SEARCH_OPS.FindExSearchNameMatch, IntPtr.Zero, 0))
+
+            WIN32_FIND_DATA data = default;
+            string fullPath = Path.TrimEndingDirectorySeparator(fileInfo.FullName);
+            if (fullPath.Length > MAX_PATH)
```
Comment (jborean93) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:8246]: Personally I think we should always just ensure the extended prefix is set. This means you are always testing the same type of path and if there is any faulty logic there it will always be apparent and fixed up rather than hidden behind a less common scenario.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 1 above)
Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:8264]: In the scenario we call IsReparsePointLikeSymlink only if checkReparsePoint is true - that is de-facto we already have called  IsReparsePoint.

Comment (jborean93) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:8264]: Is that true? I cannot seem to find that logic and can see multiple ways where this is not the case. It also means we do these unnecessary checks anyway for Unix and here as well.

Even if it was actually the case it's still good to optimize the code in case something in the future calls `IsReparsePointLikeSymlink` and doesn't check beforehand.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 3 above)
Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:8246]: This would be perf regression.
Here we follow .Net Runtime practice.

Comment (jborean93) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:8246]: Performance regression in the sense we concat a string or some other reason? I'm very new to the .NET world when it comes to performance tuning so I'm surprised that this would be considered a performance problem.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 2 above)
Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:8258]: Sorry I don't understand your comment. Please reword.

Comment (jborean93) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:8258]: Doing `throw new Win32Exception(Marshal.GetLastWin32Error());` is the same as just `throw new WIn32Exception();`. The empty constructor gets the last win32 error itself if you don't supply it.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 1 above)
Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:8264]: > Is that true? I cannot seem to find that logic

See `checkReparsePoint` in the PR.

> can see multiple ways where this is not the case.

There are only 4 places where we call IsReparsePointLikeSymlink and I don't see where we need to worry about regression.

> Even if it was actually the case it's still good to optimize the code in case something in the future calls IsReparsePointLikeSymlink and doesn't check beforehand.

The perf optimization removes extra p/invokes calls - no need do p/invoke with IsReparsePoint() if we need only check target existence.

As for future, it is internal code and we free to change it as needed. 

But most likely this code will be removed altogether soon (I expect it will be in .Net 7.0), since there is a discussion going on about adding these features to .Net (symlink and reparsepoint tags API, and appropriate enhancements to path enumeration API).

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 2 above)
Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:8258]: Thanks for clarify! The pattern comes from history - 40 times in our code. If we want to change this we should fix all in follow PR.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 1 above)
Comment (jborean93) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:8264]: > There are only 4 places where we call IsReparsePointLikeSymlink and I don't see where we need to worry about regression.

It's not a regression but an improvement.

* https://github.com/PowerShell/PowerShell/blob/35ebe2c9ac36810b369decf807686371815c31f5/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L2067 - No check for reparse point `IsReparsePointLikeSymlink` is called regardless
* https://github.com/PowerShell/PowerShell/blob/35ebe2c9ac36810b369decf807686371815c31f5/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L3107 - Removal code, `IsReparsePointLikeSymlink` is called without a reparse point check

So instead of adding a check in `Dir` you are better off doing it just once in `IsReparsePointLikeSymlink` so it all gets it by default.

> The perf optimization removes extra p/invokes calls - no need do p/invoke with IsReparsePoint() if we need only check target existence.

Only for the `Dir` function, the other 2 I linked to doesn't have this optimisation. My point is put the `ReparsePoint` check in `IsReparsePointLikeSymlink` instead so all 3 invocations can take advantage of this optimisation and you can remove the extra code in `Dir`.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 3 above)
Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:8246]: Performance has several varieties:
1. External API delays (like IO waiting)
2. High CPU usage
3. High memory allocations with GC pressure.

If you did run an profiler you could see how many allocations PowerShell does. 
We should avoid extra allocations.
This is the case here.

---
Generally speaking, PowerShell only supports long paths because .Net does. So you won't find our code adding extended prefixes anywhere.
So it's advantageous for us to migrate to .Net API wherever possible, because this API is always implemented with long path support in at its best perf.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 1 above)
Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:8264]: > Only for the Dir function, the other 2 I linked to doesn't have this optimisation. 

No :-) Exactly the opposite.

We have 2 API where we do (expensive) p/invokes - (1) in File.Attributes properties (follow calls use a cache) - used in IsReparsePoint(), (2) FindFirstFileEx, used in IsReparsePointLikeSymlink
If we need only FindFirstFileEx we shouldn't do first p/invoke since FindFirstFileEx returns all we need.

Comment (jborean93) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:8264]: Hmm I think I see what you are saying now, `File/Directory.Attributes` will call `FindFirstFileEx` internally but only on demand. not when the object is constructed. So since `Dir` already needed the `Attributes` for another call we already had that to skip the subsequent call but the others haven't had that optimisation yet.

**Comment by iSazonov** [comment]
@rjmholt Friendly ping :-)

File: src/System.Management.Automation/utils/PathUtils.cs [hunk 4]
```diff
@@ -447,5 +448,105 @@ internal static bool TryDeleteFile(string filepath)
...
+        private static bool IsDevice(string path)
+        {
+            return IsExtended(path)
+                ||
+                (
+                    path.Length >= DevicePrefixLength
+                    && IsDirectorySeparator(path[0])
+                    && IsDirectorySeparator(path[1])
+                    && (path[2] == '.' || path[2] == '?')
+                    && IsDirectorySeparator(path[3])
```
[the remark this answers is not in the document]
Comment (rjmholt) [reply src/System.Management.Automation/utils/PathUtils.cs:491]: Also does `//?` work like `\\?` as far as PowerShell is concerned?

File: src/System.Management.Automation/engine/Utils.cs [hunk 5]
```diff
@@ -2100,6 +2100,13 @@ public static class InternalTestHooks
 
         internal static bool ThrowExdevErrorOnMoveDirectory;
 
+        // To emulate OneDrive behavior we use the hard-coded symlink.
+        // If OneDriveTestRecuseOn is false then the symlink works as regular symlink.
+        // If OneDriveTestRecuseOn is true then we resurce into the symlink as OneDrive should work.
+        internal static bool OneDriveTestOn;
+        internal static bool OneDriveTestRecurseOn;
+        internal static string OneDriveTestSymlinkName = "link-Beta";
```
[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/engine/Utils.cs:2108]: I'd do not want to pass anything to Engine because of  security concerns. We've always avoided it.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 6]
```diff
@@ -8216,28 +8230,55 @@ internal static bool IsReparsePoint(FileSystemInfo fileInfo)
...
+            {
+                fullPath = PathUtils.EnsureExtendedPrefix(fullPath);
+            }
+
+            using (var handle = FindFirstFileEx(fullPath, FINDEX_INFO_LEVELS.FindExInfoBasic, ref data, FINDEX_SEARCH_OPS.FindExSearchNameMatch, IntPtr.Zero, 0))
```
[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:8251]: Done.

File: src/System.Management.Automation/utils/PathUtils.cs [hunk 7]
```diff
@@ -447,5 +448,105 @@ internal static bool TryDeleteFile(string filepath)
...
+
+        /// <summary>
+        /// Returns true if the given character is a valid drive letter
+        /// </summary>
+        private static bool IsValidDriveChar(char value)
+        {
+            return ((value >= 'A' && value <= 'Z') || (value >= 'a' && value <= 'z'));
+        }
+
+        internal static string EnsureExtendedPrefix(string path)
```
[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/utils/PathUtils.cs:470]: Done.

File: src/System.Management.Automation/utils/PathUtils.cs [hunk 8]
```diff
@@ -447,5 +448,105 @@ internal static bool TryDeleteFile(string filepath)
...
+        {
+            if (IsPartiallyQualified(path) || IsDevice(path))
+                return path;
+
+            // Given \\server\share in longpath becomes \\?\UNC\server\share
+            if (path.StartsWith(UncPathPrefix, StringComparison.OrdinalIgnoreCase))
+                return path.Insert(2, UncDevicePrefixToInsert);
```
[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/utils/PathUtils.cs:477]: The code is copy-pasted from .Net and I would prefer not to change it.

File: src/System.Management.Automation/utils/PathUtils.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/utils/PathUtils.cs:491]: 1. The code is copy-pasted from .Net and I would prefer not to change it.

2. The path always comes from FileSystemInfo and we have no need to concern about normalization.

I hope in next milestone PowerShell team support my efforts to migrate new .Net API. As result all PowerShell helper code related links will be removed.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 2 above)
Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:8258]: @rjmholt If you agree to review :-) I will fix all these patterns in follow PR.

File: src/System.Management.Automation/engine/Utils.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (rjmholt) [reply src/System.Management.Automation/engine/Utils.cs:2112]: I'm not sure I understand. Can you add a comment to explain this property?

**Comment by rjmholt** [comment]
@iSazonov please add comments around code that's been copy/pasted from .NET about where it's come from

**Comment by iSazonov** [comment]
> @iSazonov please add comments around code that's been copy/pasted from .NET about where it's come from

There is already `#region Helpers for long paths from .Net Runtime`.

File: src/System.Management.Automation/engine/Utils.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (iSazonov) [reply src/System.Management.Automation/engine/Utils.cs:2113]: Added.

File: src/System.Management.Automation/utils/PathUtils.cs [hunk 9]
```diff
@@ -447,5 +448,105 @@ internal static bool TryDeleteFile(string filepath)
 
             return false;
         }
+
+        #region Helpers for long paths from .Net Runtime
```
Comment (rjmholt) [inline src/System.Management.Automation/utils/PathUtils.cs:452]:
```suggestion
        #region Helpers for long paths from .Net Runtime
        
        // Code here is copied from .NET's internal path helper implementation:
        // https://github.com/dotnet/runtime/blob/dcce0f56e10f5ac9539354b049341a2d7c0cdebf/src/libraries/System.Private.CoreLib/src/System/IO/PathInternal.Windows.cs
        // It has been left as a verbatim copy.
```

File: src/System.Management.Automation/engine/Utils.cs [hunk 10]
```diff
@@ -2104,6 +2104,14 @@ public static class InternalTestHooks
 
         internal static bool ThrowExdevErrorOnMoveDirectory;
 
+        // To emulate OneDrive behavior we use the hard-coded symlink.
+        // If OneDriveTestRecuseOn is false then the symlink works as regular symlink.
+        // If OneDriveTestRecuseOn is true then we resurce into the symlink as OneDrive should work.
```
Comment (SteveL-MSFT) [inline src/System.Management.Automation/engine/Utils.cs:2109]:
```suggestion
        // If OneDriveTestRecuseOn is true then we recurse into the symlink as OneDrive should work.
```

File: src/System.Management.Automation/engine/Utils.cs [hunk 11]
```diff
@@ -2104,6 +2104,14 @@ public static class InternalTestHooks
 
         internal static bool ThrowExdevErrorOnMoveDirectory;
 
+        // To emulate OneDrive behavior we use the hard-coded symlink.
+        // If OneDriveTestRecuseOn is false then the symlink works as regular symlink.
```
Comment (SteveL-MSFT) [inline src/System.Management.Automation/engine/Utils.cs:2108]:
```suggestion
        // If OneDriveTestRecurseOn is false then the symlink works as regular symlink.
```

File: src/System.Management.Automation/engine/Utils.cs [hunk 12]
```diff
@@ -2104,6 +2104,14 @@ public static class InternalTestHooks
...
+        // If OneDriveTestRecuseOn is true then we recurse into the symlink as OneDrive should work.
```
Comment (SteveL-MSFT) [inline src/System.Management.Automation/engine/Utils.cs:2109]:
```suggestion
        // If OneDriveTestRecurseOn is true then we recurse into the symlink as OneDrive should work.
```

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 13]
```diff
@@ -1891,9 +1891,14 @@ protected override void InvokeDefaultAction(string path)
...
 
                             bool hidden = false;
+                            bool checkReparsePoint = true;
                             if (!Force)
                             {
                                 hidden = (recursiveDirectory.Attributes & FileAttributes.Hidden) != 0;
+
+                                // We've already taken the expense of initializing the Attributes property here,
+                                // so we can use that to avoid needing to call IsReparsePointLikeSymlink() later.
+                                checkReparsePoint = (recursiveDirectory.Attributes & FileAttributes.ReparsePoint) != 0;
```
Comment (SteveL-MSFT) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:1901]: use HasFlag() instead

Comment (rjmholt) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:1901]:
```suggestion
                                checkReparsePoint = recursiveDirectory.Attributes.HasFlag(FileAttributes.ReparsePoint);
```

**Comment by rjmholt** [comment]
@PoshChan please remind me in 1 hour

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 14]
```diff
@@ -1891,9 +1891,14 @@ protected override void InvokeDefaultAction(string path)
                             }
 
                             bool hidden = false;
+                            bool checkReparsePoint = true;
                             if (!Force)
                             {
                                 hidden = (recursiveDirectory.Attributes & FileAttributes.Hidden) != 0;
```
Comment (SteveL-MSFT) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:1897]:
```suggestion
                                hidden = recursiveDirectory.Attributes.HasFlag(FileAttributes.Hidden);
```

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 15]
```diff
@@ -8057,7 +8071,7 @@ protected override bool ReleaseHandle()
         }
 
         // SetLastError is false as the use of this API doesn't not require GetLastError() to be called
```
Comment (SteveL-MSFT) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:8073]: shouldn't this comment be removed now?

Comment (rjmholt) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:8073]:
```suggestion
```

**Comment by PoshChan** [comment]
@rjmholt, this is the reminder you requested 1 hour ago

**Review by rjmholt — APPROVED** [review]
