### PR TITLE
Fix error formatting for pipeline enumeration exceptions

### LINKED ISSUE #20181: An attempt to modify a collection while it is being enumerated doesn't always result in an error
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Attempting modification of a collection while it is being enumerated should result in an _error_:
* `An error occurred while enumerating through a collection: Collection was modified; enumeration operation may not execute.`

This error isn't consistently surfaced - note that this is a regression from Windows PowerShell:

```powershell
# OK: Reports an error for the attempt to modify the collection being enumerated.
'--- foreach'
$l = [System.Collections.Generic.List[string]] @('one', 'two')
foreach ($e in $l) { $l.Remove($e) }

# !! Fails QUIETLY in PS CORE as of v7.4.0-preview.5
'--- pipeline'
$l = [System.Collections.Generic.List[string]] @('one', 'two')
$l | ForEach-Object { $l.Remove($_) }
```

**Important**: The quiet failure only occurs when the code is executed _via a script file_; if you paste the last two statements into an _interactive_ console, the error does surface.

**[_Update_: NOT PowerShell's fault - see [below](https://github.com/PowerShell/PowerShell/issues/20181#issuecomment-1699515501)]** The following WinForms example affects Windows PowerShell too (both interactively and in a script):

```powershell
using namespace System.Windows.Forms
Add-Type -Assembly System.Windows.Forms

$f = [Form]::new()
$f.Controls.AddRange((
  [CheckBox]::new(),
  [CheckBox]::new()
))

# !! Should fail with an error message, but quietly aborts after the first .Remove() call.
$f.Controls | ForEach-Object { $f.Controls.Remove($_) }

$f.Controls.Count # !! still nonzero
```

### Expected behavior

First snippet:

* Both the `foreach` and the `ForEach-Object` statement should report the expected error.

Second snippet:

* The expected error should occur.

### Actual behavior

First snippet:

* The `ForEach-Object` statement doesn't report an error and quietly aborts the pipeline after the first `.Remove()` call

Second snippet:

* The expected error doesn't occur; quietly aborts the pipeline after the first `.Remove()` call.

### Error details

_No response_

### Environment data

```powershell
PowerShell 7.4.0-preview.5
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by SeeminglyScience**
# PR Summary

When the pipeline was invoking a `IEnumerator.MoveNext` implementation that threw an exception, that exception was failing to render. This was occuring because the formatter was trying to test for `TargetObject.Line`. The `TargetObject` in this case was the enumerator, so the engine attempted member access enumeration which threw the same exception.

This change fixes that by explicitly testing the type of `TargetObject` prior to attempting member access.

Fixes #20181

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]
Changes look fine to me, but your test is failing

**Comment by SeeminglyScience** [comment]
@SteveL-MSFT Ah yep, I tested outside of an `it` block forgetting that pester will set error action in a way where the parameter level specification doesn't work.

Fixed!

**Review by SteveL-MSFT — APPROVED** [review]

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs [hunk 1]
```diff
@@ -1111,34 +1113,47 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_System_Management_Autom
                                         $message = ''
                                         $prefix = ''
 
+                                        # Handle case where there is a TargetObject from a Pester `Should` assertion failure and we can show the error at the target rather than the script source
+                                        # Note that in some versions, this is a Dictionary<,> and in others it's a hashtable. So we explicitly cast to a shared interface in the method invocation
+                                        # to force using `IDictionary.Contains`. Hashtable does have it's own `ContainKeys` as well, but if they ever opt to use a custom `IDictionary`, that may not.
+                                        $useTargetObject = $null -ne $err.TargetObject -and
```
Comment (daxian-dbw) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1119]: I cannot find where `$err` is defined before this use. Can you please point me to it?

**Review by daxian-dbw — CHANGES_REQUESTED** [review]

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs (hunk 1 above)
Comment (SeeminglyScience) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1119]: > I cannot find where `$err` is defined before this use. Can you please point me to it?

Yeah it's a little confusing. This is inside the nested function `Get-ConciseViewPositionMessage`. Then look at this 

image

As labeled:

1. is the ending bracket for the function *definition* of `Get-ConciseViewPositionMessage`
2. is where `$err` is set
3. is where the function is called in the main body of the format view

I kept with the existing style, but at some point it may be worth rewriting some parts of this for maintainability.

**Review by daxian-dbw — APPROVED** [review]

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs (hunk 1 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:1119]: Thank you!
