### PR TITLE
Fix TabExpansion2 variable leak when completing variables

### LINKED ISSUE #1969: Leaky implementation of tab-completion / IntelliSense surfaces phantom variables named for the parameters of the TabExpansion2 function
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Note: 

* I've observed the symptom in the context of tab-completion in Visual Studio Code, but I assume the underlying problem is relevant to this repo.

---

* The editor's tab completion / IntelliSense always "knows" the following phantom variables due to a leaky implementation detail (they correspond to the parameter names of the `TabExpansion2` function):

  * `$ast`, `$tokens`, `$positionOfCursor`, `$options`

* Tab-completion / IntelliSense results of these variables is based on the type these (parameter) variables have _in `Tabexpansion2`_, _even if you explicitly define them with a value of a different type_.

  * For instance, even if you define `[int] $positionOfCursor = 42` in your script, tab-completion on a later line still shows the properties of the `[IScriptPosition]` type that the `-positionOfCursor` parameter is typed as.

  * Even if you don't define your own versions of these variables, their mere (ostensible) presence during tab-completion is confusing.

In an empty `.ps1` file open in Visual Studio Code, type the following

```powershell
$tokens.
```

### Expected behavior

_No_ IntelliSense results, given that `$tokens` isn't defined.

### Actual behavior

IntelliSense results are the `[array]` type's instance property names, because the `-token` parameter of `TabExpansion2` happens to be array-typed (`Token[]]`)

### Error details

_No response_

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

PowerShell Extension v2022.11.0

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by MartinGC94**
# PR Summary
Fixes https://github.com/PowerShell/PowerShellEditorServices/issues/1969 where tab completing variables would show Variables/Parameters from TabExpansion2.
This approach could probably be extended to fix a similar issue with `PSConsoleHostReadLine`  (see https://github.com/PowerShell/PowerShell/issues/16941 ) but I'm not sure if I can add PSReadLine specific code here.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by kilasuit** [comment]
@MartinGC94 - PSReadline specific code would need to be pushed to that repo as it can then be used not only in v7 but also v5.1 too

File: src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs [hunk 1]
```diff
@@ -537,43 +537,23 @@ private static CommandCompletion CompleteInputImpl(Ast ast, Token[] tokens, IScr
...
+                    if (context.CurrentCommandProcessor.Command.CommandInfo.Name.Equals("TabExpansion2", StringComparison.OrdinalIgnoreCase))
                     {
-                        dynamic stackEntryAsPSObj = PSObject.AsPSObject(stackEntry);
-                        if (stackEntryAsPSObj.Command.Equals("TabExpansion2", StringComparison.OrdinalIgnoreCase))
-                        {
-                            tupleForFrameToSkipPast = stackEntry.FunctionContext._localsTuple;
-                            break;
-                        }
+                        scopeToRestore = context.EngineSessionState.CurrentScope;
+                        context.EngineSessionState.CurrentScope = scopeToRestore.Parent;
```
Comment (SeeminglyScience) [inline src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs:546]: If `TabExpansion2` is defined in a module this will revert to the module's `script` scope rather than the actual previous scope.

Also if `TabExpansion2` is dot sourced from global, `Parent` will be null here

Comment (MartinGC94) [reply src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs:546]: > If `TabExpansion2` is defined in a module then this will revert to the module's `script` scope rather than the actual previous scope.

What's the difference? If I look at the session state API it seems to simply use the Parent property to move to different scopes:

https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/SessionStateScopeAPIs.cs#L128
https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/SessionStateScopeEnumerator.cs#L30
https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/SessionStateVariableAPIs.cs#L1791

Can you show a simple example where it would cause a problem?

> Also if `TabExpansion2` is dot sourced from global, `Parent` will be null here

How do you dot source from global? Do you mean like this: `. $Function:TabExpansion2 "$"` because if so it won't use the parent because the command name isn't "TabExpansion2".

Comment (SeeminglyScience) [reply src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs:546]: > What's the difference? If I look at the session state API it seems to simply use the Parent property to move to different scopes:

A `SessionState` is sort of like a `Stack` of scopes. Every module has its own stack. To move to a different stack, `EngineSessionState` needs to be assigned. Though, afaik the previous `SessionState` is only stored in a local variable inside a few different`try/finally`s.

> How do you dot source from global? Do you mean like this: `. $Function:TabExpansion2 "$"` because if so it won't use the parent because the command name isn't "TabExpansion2".

You'd do `. TabExpansion2 'etc'`, or the more likely route would be calling `PowerShell.AddCommand("TabExpansion2", useLocalScope: false)` from a host application.

Comment (MartinGC94) [reply src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs:547]: All right, thanks for the explanation. I've added a null check for the dot sourcing scenario.  
As for the module scope, would it be any different from the current behavior? If you are tab completing a variable today it's just calling `Get-Item variable:\*` from the tabexpansion2 scope which as far as I can tell retrieves variables from that scope and traverses through the `Parent` property on each scope. So with my change the only difference would be that it skips the initial TabExpansion2 scope, right?

Comment (MartinGC94) [reply src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs:547]: > Ideally we'd be able to detect that TabExpansion2 was dot sourced and abort the attempt to revert scope. I don't know of a reliable way to tell that from here though

I think you do without realizing. There's a `UseLocalScope` property in the `CurrentCommandProcessor` and you said that `PowerShell.AddCommand("TabExpansion2", useLocalScope: false)` is equivalent to dot sourcing, so can't we just use that? It seems to toggle back and forth like I would expect when I dotsource or run it normally.

Alternatively, instead of changing the scope we could just add the parent scope as an additional property to the CompletionContext object and update the variable/member completion code to use the parent scope if it's available. I don't think any other completion paths is affected by the session state but I could be wrong.

Comment (SeeminglyScience) [reply src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs:548]: > I think you do without realizing. There's a `UseLocalScope` property in the `CurrentCommandProcessor` and you said that `PowerShell.AddCommand("TabExpansion2", useLocalScope: false)` is equivalent to dot sourcing, so can't we just use that?

Oh yay I was wrong! 😁 I must have been thinking of when you only have the call stack, good catch!

**Comment by adityapatwardhan** [comment]
@MartinGC94 I would need signoff from either @daxian-dbw or @SeeminglyScience before this can be merged, as the as SMEs.

**Comment by SeeminglyScience** [comment]
FYI I haven't forgotten about this, I need some time to play around with it and see if any issues crop up

**Review by JamesWTruher — APPROVED** [review]
This looks fine, it seems that the automatic variables which are created by the use of `[CmdletBinding()]` for TabExpansion2 should also be removed from completion, yes?

**Comment by MartinGC94** [comment]
> it seems that the automatic variables which are created by the use of `[CmdletBinding()]` for TabExpansion2 should also be removed from completion, yes?

You mean variables like `$PSCmdlet`? I think they are in the list of built-in variables that are always added without looking at the session state or script text. I don't think that's a problem because people should be aware of them so they don't accidentally end up with conflicts when changing a function from basic to advanced because they happened to use the same var name.

**Review by SeeminglyScience — APPROVED** [review]
I couldn't find a way to break this so LGTM! Thanks again @MartinGC94! ❤️

**Comment by daxian-dbw** [comment]
This also fixes the following scenario:

```
$ast = [System.Management.Automation.Language.Parser]::ParseInput('$a = ''abc''', [ref]$null, [ref]$null)
$ast.End<tab>
```
It didn't work before because the variable `$ast` is defined in the `TabExpansion2` scope.
