### PR TITLE
Reset output attributes if column had ESC char when using `Format-Table`; Replace "..." with unicode ellipsis

### LINKED ISSUE #7767: Strings with Virtual Terminal (VT) / ANSI escape sequences that are truncated for display make effects linger
<sup>Related: #7744</sup>

[Virtual Terminal escape sequences](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences) allow, among other things, formatting of console (terminal) output, notably to produce _colored_ output.

An escape sequence that changes the output color - e.g., `` "`e[32m" `` to switch to green - stays in effect until the color is reset - e.g., with `` "`e[m" ``

Example:

```powershell
"before `e[32mgreen`e[m after"  # prints only the word "green" in green.
```

Therefore, if PowerShell _truncates_ strings for output formatting, a string may get cut off so that the reset sequence is _not_ output, which means that the color unexpectedly stays in effect.

#7744 shows the problem in the context of using an [OSC escape sequence](https://en.wikipedia.org/wiki/ANSI_escape_code#Escape_sequences) to construct a hyperlink (which only some terminals support; others render just the link label).

This is a nontrivial problem to solve, because PowerShell would have to be aware of all potential escape sequences and _know how to reset their effects_ so that the appropriate escape sequence can be appended to the truncated string.

Steps to reproduce
------------------

```powershell
[pscustomobject] @{ test1="before `e[32mgreen`e[m after"; test2='next col' } | Format-Table @{ e='test1'; width=17 }, test2
```

Expected behavior
-----------------

```none
test1              test2
-----              -----
before gr...       next col
```

`gr...` should render green, but `next col` should render with the default color.

Actual behavior
---------------

```none
test1             test2
-----             -----
before gr...  next col
```

That is, `next col` too is printed in green, and green output stays in effect (the prompt rendered after the command will be green too).

Additionally, note that the column alignment is off.

Environment data
----------------

```powershell
PowerShell Core v6.1.0-rc.1 on macOS 10.13.6
PowerShell Core v6.1.0-rc.1 on Ubuntu 16.04.4 LTS
PowerShell Core v6.1.0-rc.1 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.165)
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
change ellipsis when truncating to single unicode character
reset console output if previous column contains ESC
update existing format-table tests

## PR Summary

If content included a VT100 ESC sequence (like changing color), this affected all output after that cell in the table.  Fix is to detect that a cell contained ESC and reset the console after it.  Also, change the 3 character ellipsis `...` to use the single unicode character `…` so that more text is available.

Fix https://github.com/PowerShell/PowerShell/issues/7767

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [x] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

File: src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs [hunk 1]
```diff
@@ -574,7 +586,8 @@ private static string GenerateRowField(string val, int width, int alignment, Dis
             return s;
         }
 
-        private const string ellipsis = "...";
+        private const char ellipsis = '\u2026';
```
Comment (anmenaga) [inline src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs]: Is there any other scenarios, apart from `Format-Table`, where we truncate the output?

File: src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs [hunk 2]
```diff
@@ -413,7 +414,18 @@ private string GenerateRow(string[] values, ReadOnlySpan<int> alignment, Display
...
                 }
+
+                if (resetVt100)
+                {
+                    sb.Append("\u001b[m");
+                    resetVt100 = false;
+                }
+
                 sb.Append(GenerateRowField(values[k], _si.columnInfo[k].width, alignment[k], dc, addPadding));
+                if (values[k].Contains("\u001b"))
```
[the remark this answers is not in the document]
Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs]: Yes, we would need to as it will affect the next row.  Will fix.

File: src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs (hunk 1 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs]: A search for "..." across the code base found other hits, will address them in this PR.

File: src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs [hunk 3]
```diff
@@ -413,7 +413,13 @@ private string GenerateRow(string[] values, ReadOnlySpan<int> alignment, Display
                         sb.Append(StringUtil.Padding(_startColumn));
                     }
                 }
+
                 sb.Append(GenerateRowField(values[k], _si.columnInfo[k].width, alignment[k], dc, addPadding));
+                if (values[k].Contains("\u001b"))
```
Comment (iSazonov) [inline src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs]: We could use char const (more informative) and `IndexOf(ReserChar)` (more fast).

File: src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs [hunk 4]
```diff
@@ -574,7 +580,8 @@ private static string GenerateRowField(string val, int width, int alignment, Dis
             return s;
         }
 
-        private const string ellipsis = "...";
+        private const char Ellipsis = '\u2026';
+        private const int EllipsisSize = 1;
```
Comment (iSazonov) [inline src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs]: Should it be `EllipsisSize = sizeof(Ellipsis )`?

File: src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs [hunk 5]
```diff
@@ -19,7 +19,7 @@ namespace Microsoft.PowerShell.Commands.Internal.Format
     /// </summary>
     internal static class PSObjectHelper
     {
-        internal const string ellipses = "...";
+        internal const char Ellipsis = '…';
```
Comment (iSazonov) [inline src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs]: Please use \u  notation to keep file in ASCII.

File: src/System.Management.Automation/engine/ErrorPackage.cs [hunk 6]
```diff
@@ -462,7 +462,7 @@ public override string ToString()
         /// control the maximum length of the GetMessage() string, we
         /// ellipsize these strings.  The current heuristic is to take
         /// strings longer than 40 characters and ellipsize them to
-        /// the first and last 15 characters plus "..." in the middle.
+        /// the first and last 19 characters plus "…" in the middle.
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/ErrorPackage.cs]: Please replace the ellipsis char with an ASCII string to keep file in ASCII..

File: src/System.Management.Automation/engine/ErrorPackage.cs [hunk 7]
```diff
@@ -476,8 +476,8 @@ internal static string Ellipsize(CultureInfo uiCultureInfo, string original)
             {
                 return original;
             }
-            string first = original.Substring(0, 15);
-            string last = original.Substring(original.Length - 15, 15);
+            string first = original.Substring(0, 19);
+            string last = original.Substring(original.Length - 19, 19);
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/ErrorPackage.cs]: Why we use 19 const? Please add comment.

File: src/System.Management.Automation/engine/Modules/ScriptAnalysis.cs [hunk 8]
```diff
@@ -184,7 +184,7 @@ public override AstVisitAction VisitFunctionDefinition(FunctionDefinitionAst fun
             ModuleIntrinsics.Tracer.WriteLine("Discovered function definition: {0}", functionName);
 
             // Check if they've defined any aliases
-            // function Foo-Bar { [Alias("Alias1", "...")] param() ... }
+            // function Foo-Bar { [Alias("Alias1", "…")] param() ... }
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/Modules/ScriptAnalysis.cs]: Please replace ellipsis char with ASCII string to keep file in ASCII.

File: src/System.Management.Automation/engine/debugger/debugger.cs [hunk 9]
```diff
@@ -3984,7 +3984,7 @@ internal void TraceVariableSet(string varName, object value)
 
             if (valAsString.Length > msgLength)
             {
-                valAsString = valAsString.Substring(0, msgLength) + "...";
+                valAsString = valAsString.Substring(0, msgLength) + "…";
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/debugger/debugger.cs]: Please use \u notation. Or why not `PSObjectHelper.Ellipsis`?

File: src/System.Management.Automation/engine/hostifaces/HostUtilities.cs [hunk 10]
```diff
@@ -250,7 +250,7 @@ internal static string GetMaxLines(string source, int maxLines)
 
                 if (lineCount == maxLines)
                 {
-                    returnValue.Append("...");
+                    returnValue.Append('…');
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/hostifaces/HostUtilities.cs]: The same.

File: src/System.Management.Automation/engine/remoting/commands/PushRunspaceCommand.cs [hunk 11]
```diff
@@ -1151,7 +1151,7 @@ private void SetRunspacePrompt(RemoteRunspace remoteRunspace)
 
                     case ContainerIdParameterSet:
                         targetName = (this.ContainerId.Length <= 15) ? this.ContainerId
-                                                                     : this.ContainerId.Remove(12) + "...";
+                                                                     : this.ContainerId.Remove(14) + "…";
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/remoting/commands/PushRunspaceCommand.cs]: The same.

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs [hunk 12]
```diff
@@ -1294,7 +1294,7 @@ internal static void AddKeyValuePair(IDictionary hashtable, object key, object v
 
                 if (errorKeyString.Length > 40)
                 {
-                    errorKeyString = errorKeyString.Substring(0, 40) + "...";
+                    errorKeyString = errorKeyString.Substring(0, 40) + "…";
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: The same.

File: src/System.Management.Automation/resources/ErrorPackage.resx [hunk 13]
```diff
@@ -118,7 +118,7 @@
     <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
   </resheader>
   <data name="Ellipsize" xml:space="preserve">
-    <value>{0}...{1}</value>
+    <value>{0}…{1}</value>
```
Comment (iSazonov) [inline src/System.Management.Automation/resources/ErrorPackage.resx]: Can we use \u notation here too to keep the file in ASCII?

File: test/powershell/Modules/Microsoft.PowerShell.Utility/Format-List.Tests.ps1 [hunk 14]
```diff
@@ -75,7 +75,7 @@ Describe "Format-List DRT basic functionality" -Tags "CI" {
         $info = @{}
         $info.array = $al
         $result = $info | Format-List | Out-String
-        $result | Should -Match "Name  : array\s+Value : {0, 1, 2, 3...}"
+        $result | Should -Match "Name  : array\s+Value : {0, 1, 2, 3…}"
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Format-List.Tests.ps1]: Please use `u{ } and add a comment.

File: test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1 [hunk 15]
```diff
@@ -31,7 +31,7 @@ Describe "Format-Table" -Tags "CI" {
                 $info = @{}
                 $info.array = $al
                 $result = $info | Format-Table | Out-String
-                $result | Should -Match "array\s+{0, 1, 2, 3...}"
+                $result | Should -Match "array\s+{0, 1, 2, 3…}"
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1]: The same.
Below too.

File: src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs (hunk 4 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs]: sizeof(char) is 2 (Unicode)

Comment (iSazonov) [reply src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs]: Size in the name confuses me. 😕

**Comment by iSazonov** [comment]
@SteveL-MSFT Please look CodeFactor issues.

**Review by iSazonov — APPROVED** [review]

**Review by anmenaga — APPROVED** [review]

**Comment by SteveL-MSFT** [comment]
@iSazonov I believe VT100 is already the de facto and de jure standard (at least in terms of the console).  Cloud Shell and the integrated terminal in VSCode are javascript based and support parsing VT100 escape codes already.  I would agree that we haven't thought through how this will work with something like `ConvertTo-Html`, but I would imagine ideally it would be some translation of VT100 to HTML.  

Even if we support a PowerShell dialect for the equivalent of VT100 escape sequences, we would still need to handle VT100 escape sequences that could be emitted by any tool that runs in the console.

**Comment by iSazonov** [comment]
>I believe VT100 is already the de facto and de jure standard (at least in terms of the console). Cloud Shell and the integrated terminal in VSCode are javascript based and support parsing VT100 escape codes already.

I wrote about this above:  I believe that this investments is aimed, among other things, at ensuring compatibility with Unix vty and _existing_ software. And this does not mean that modern software should work according to protocols of 40 years old.
I guess this is a wrong design.
And I can continue that PowerShell is high level language and have many _magic_ abstractions, for output formatting too.
Initially, PowerShell _was not based_ on VT100. If the output should be based on VT100, then we definitely need to accept this as an RFC. And this is definitely a fundamental decision and fundamental change.

I consider VT100 as a low-level assembler. It is not user-friendly.  Nobody uses Intel assembler - developers prefer absractions of high level languages. Why? Because they need to accomplish their goal quickly and simply. I’m sure that PowerShell should also provide sufficient abstractions so that users _don’t think_ about VT100 escape sequences. PowerShell style is using ` Write-Host -BackgroundColor Blue` but not using `Write-Host 0x1A ...`. _We should consider VT100 as one of the options for implementing high-level abstractions._
We should not lower to the lower level in the PowerShell language itself. The use of abstractions allows us to be comfortable, fast and reliable with any consoles. As PowerShell engine developer we are free to use vty or Windows console api (why we'd need reject the api if it allows us to make great-look a progress bar? and it is more multi-thread friendly). We can switch free to ncurses or Web (not only HTML, we can use any api over https!). At the same time, users should use simple and powerful abstractions to easily write scripts that work on any platform and with any terminal.
Another thing that worries me is that with the allowing of escapes, we bind to the vty but will not we format the table cells on the Web? The right design would be to delegate this to the conhost implementation. Escapes is and should be implementation details. So I am sure that these escapes are not what should be in PowerShell _language_.

**Comment by iSazonov** [comment]
Continuing to think this over, I recall our implementation of the Markdown. It is tied to vty. Again this is too much of a limitation.
I suppose all types of rendering should be abstracted in engine and implemented in a conhost so that the engine works consistently with any console and we could switch on the fly.
I am increasingly convinced that we should invest in an engine abstraction of a markup language. We don't even have to invent anything. This might be an RFC for a subset of HTML (to support format-table, Markdown and so on).
In this case, the output will be as simple as
```powershell
Write-Host -HTML "HTMLstring" -Markdown "markdownstring" -SimpleString "simplestring"
"string" | Format-Table [-HTML | -Markdown]
```
where default parameter is defined in current console type.

**Comment by iSazonov** [comment]
@DHowett-MSFT Thanks for feedback! All you are talking about is _a low level_ of work with a console. This is a standard because we can hardly think of something simpler for this low level. The issue is about _high level_ - why we are starting to expose the low level to PowerShell language level and user level: (1) why PowerShell users should thinking about escapes and use its? why the users should remember the escapes? (2) Do we know high level languages which explicitly exposes the escapes to users rejecting absractions?

> Unfortunately, that may not be how PowerShell was designed.

PowerShell is designed to expose users high level and magic things. Low level should stay on low level. In the case _an implementing of rendering_ is the low level, high level is PowerShell language abstractions (like `Write-Host -BackgroundColor Blue` and perhaps interpalated strings as I metioned above).
Currently PowerShell conhost class has already needed abstractions to works (1) on windows (buffered console API), (2)  on Unix (vty). So my thoughts is (1) use/enhance PowerShell conhost class abstractions, (2) move rendering implementations to console adapters.

I assume that this problem comes from the fact that PowerShell mainly works with a simple console. In fact, it should work with any console and any remote protocol (as I mentioned above).

**Comment by SteveL-MSFT** [comment]
@iSazonov I think it's fine to think of VT100 as an implementation detail and not something we want to expose to users although they can freely use it.  We should have something higher level to make it easier for non-developers to leverage a subset of VT100 for formatting.  Perhaps something like "`e{green}" but this needs a RFC and some thought.  I don't think providing a higher level abstraction precludes the changes in this PR.

**Comment by iSazonov** [comment]
>Perhaps something like "`e{green}" but this needs a RFC and some thought.

It's low level again. Currently we have Markdown implementation based solely on escapes. Why? If we would have a universal api we could not use the escapes and get rendering on any "console".

> I don't think providing a higher level abstraction precludes the changes in this PR.

We can look at it from the other side. _Nothing prevents users from using escapes now._ Users can even make their own cmdlet to display tables. But why should we complicate our rendering? I am increasingly confident that this is not justified.
I think that this change just shows that we doom ourselves to an _infinite number of bugs_ if we don’t say now that keeping escapes out of our redering is "by-design".
If you started to implement Markdown we could do the same for other markup languages (what about HTML or YAML?). This means that we need a common power abstract API to support this uniformly.

> Perhaps something like "`e{green}"

Yeah, what I'm trying to say here is that the following is better:
```powershell
echo [html]"<a><bold>Hello world!<\a>"
```
that should works with any target (VT, ghost, web...)

**Comment by SteveL-MSFT** [comment]
@iSazonov I think you should open a new issue to discuss that.  It seem you are proposing we should prevent people from embedding VT100 escape sequences which seems too strict to me.

**Comment by iSazonov** [comment]
> I think you should open a new issue to discuss that

Will do.

> It seem you are proposing we should prevent people from embedding VT100 escape sequences which seems too strict to me.

I propose to keep our engine and formatting _implementation-detail-independent_ and move rendering implementation to conhost.

**Comment by SteveL-MSFT** [comment]
@iSazonov are you ok with taking this change?  We can continue the higher level discussion separate from this.

**Comment by iSazonov** [comment]
@SteveL-MSFT Sorry that I still have not opened a new discussion. Will do. As for this PR, as I said above, I do not agree that this should be because we will have to parse and process __each__ line before outputting it (not partially like in this PR)  that unnecessarily complicates the output formatting system and complicates the addition of support for other consoles. I propose to postpone it as it is not a security change.  I delegate this to your team.

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs [hunk 16]
```diff
@@ -1298,13 +1298,13 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_Microsoft_PowerShell_Co
                         .AddItemScriptBlock(@"
                                   $result = $_.Content
                                   $result = $result.Substring(0, [Math]::Min($result.Length, 200) )
-                                  if($result.Length -eq 200) { $result += ""..."" }
+                                  if($result.Length -eq 200) { $result += ""`u{2026}"" }
```
Comment (TravisEz13) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs]: Just an FYI.  I've seen some places where unicode doesn't render with the change to using the null replacement character, but they are few.

Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs]: Discussed offline, we are ok with this change and can revisit pending customer feedback as the major distros support rendering.

File: src/System.Management.Automation/resources/ErrorPackage.resx [hunk 17]
```diff
@@ -118,7 +118,7 @@
     <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
   </resheader>
   <data name="Ellipsize" xml:space="preserve">
-    <value>{0}...{1}</value>
+    <value>{0}\u2026{1}</value>
```
Comment (KalleOlaviNiemitalo) [inline src/System.Management.Automation/resources/ErrorPackage.resx]: I suppose this should have been `&#x2026;` rather than `\u2026`; see #9586.
