### PR TITLE
Make Get-ChildItem continue enumeration when encountering error on contained item (#2856)

### LINKED ISSUE #2856: Get-ChildItem on Linux terminates abruptly when accessing directory fails with access denied or file not found
```powershell
PS > /home/<user>/ dir

dir : Access to path '/home/<user>/.gvfs' is denied

PS >
```

Result:
------
Enumeration of paths and files terminates on access denied error

Expected
------
Get-ChildItem should skip inaccessible paths (with error) and continue enumerating files and paths that are accessible.

### PR DESCRIPTION
**Pull request by jeffbi**
Fix #2856 

Added try/catch within the enumeration loop to allow the enumeration to continue after encountering an error such as an item within the directory being deleted or renamed.

To assist in testing, two new internal test hooks have been added which cause Get-ChildItem to either delete or rename a specific file (file name hard-coded) when encountered during enumeration.

### CODE REVIEW

**Comment by iSazonov** [comment]
@jeffbi I added link on Issue

File: src/System.Management.Automation/engine/Utils.cs [hunk 1]
```diff
@@ -13,6 +13,7 @@
 using System.Globalization;
 using System.IO;
 using System.Linq;
+using System.Collections;
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/Utils.cs]: Is it really need?

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 2]
```diff
@@ -1659,51 +1659,80 @@ protected override void InvokeDefaultAction(string path)
...
-                        bool switchFilterHidden = false;     // "Hidden" is specified somewhere in the parameters
-
-                        if (null != evaluator)
-                        {
-                            attributeFilter = evaluator.Evaluate(filesystemInfo.Attributes);  // expressions
-                            filterHidden = evaluator.ExistsInExpression(FileAttributes.Hidden);
-                        }
-                        if (null != switchEvaluator)
+                        // Internal test code, run only if the
+                        // "GciEnumerationActionFilename" test hook is set
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Usually we use single quota.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 3]
```diff
@@ -1659,51 +1659,80 @@ protected override void InvokeDefaultAction(string path)
...
+                        var testActionFilename = InternalTestHooks.GciEnumerationActionFilename;
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: For discussion - We never do that but it seems we should mask test hooks by `#if Debug`.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 4]
```diff
@@ -1659,51 +1659,80 @@ protected override void InvokeDefaultAction(string path)
...
-                                ((filesystemInfo.Attributes & FileAttributes.Directory) != 0)));
-
-                        if (attributeSatisfy && (filterHidden || switchFilterHidden || Force || !hidden))
+                        try
                         {
-                            if (nameOnly)
+                            bool attributeFilter = true;
+                            bool switchAttributeFilter = true;
+                            bool filterHidden = false;           // "Hidden" is specified somewhere in the expression
+                            bool switchFilterHidden = false;     // "Hidden" is specified somewhere in the parameters
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: The same about single quota.
And please put comments on separate lines before codes.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 5]
```diff
@@ -1659,51 +1659,80 @@ protected override void InvokeDefaultAction(string path)
...
+
+                            if (null != evaluator)
                             {
-                                WriteItemObject(
-                                    filesystemInfo.Name,
-                                    filesystemInfo.FullName,
-                                    false);
+                                attributeFilter = evaluator.Evaluate(filesystemInfo.Attributes);  // expressions
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Please remove the comment or put on separate line before the code and expand it.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 6]
```diff
@@ -1659,51 +1659,80 @@ protected override void InvokeDefaultAction(string path)
...
+                                filterHidden = evaluator.ExistsInExpression(FileAttributes.Hidden);
                             }
-                            else
+                            if (null != switchEvaluator)
                             {
-                                if (filesystemInfo is FileInfo)
-                                    WriteItemObject(filesystemInfo, filesystemInfo.FullName, false);
+                                switchAttributeFilter = switchEvaluator.Evaluate(filesystemInfo.Attributes);  // switch parameters
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Please remove the comment or put on separate line before the code and expand it.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 7]
```diff
@@ -1659,51 +1659,80 @@ protected override void InvokeDefaultAction(string path)
...
+                                switchFilterHidden = switchEvaluator.ExistsInExpression(FileAttributes.Hidden);
+                            }
+
+                            bool hidden = false;
+                            if (!Force) hidden = (filesystemInfo.Attributes & FileAttributes.Hidden) != 0;
+
+                            // if "Hidden" is explicitly specified anywhere in the attribute filter, then override
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: The same about single quota.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 8]
```diff
@@ -1659,51 +1659,80 @@ protected override void InvokeDefaultAction(string path)
...
+                            if (null != switchEvaluator)
                             {
-                                if (filesystemInfo is FileInfo)
-                                    WriteItemObject(filesystemInfo, filesystemInfo.FullName, false);
+                                switchAttributeFilter = switchEvaluator.Evaluate(filesystemInfo.Attributes);  // switch parameters
+                                switchFilterHidden = switchEvaluator.ExistsInExpression(FileAttributes.Hidden);
+                            }
+
+                            bool hidden = false;
+                            if (!Force) hidden = (filesystemInfo.Attributes & FileAttributes.Hidden) != 0;
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Please use full pattern:
```c#
if (...)
{
    ...
}
```

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 9]
```diff
@@ -1659,51 +1659,80 @@ protected override void InvokeDefaultAction(string path)
...
+
+                            // if "Hidden" is explicitly specified anywhere in the attribute filter, then override
+                            // default hidden attribute filter.
+                            // if specification is to return all containers, then do not do attribute filter on
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Typos - begin with capital letters.

File: test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1 [hunk 10]
```diff
@@ -60,6 +60,28 @@ Describe "Get-ChildItem" -Tags "CI" {
             $file.Count | Should be 1
             $file.Name | Should be "pagefile.sys"
         }
+        It "Should continue enumerating a directory when a contained item is deleted" -Skip:($IsWindows) {
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1]: Why we skip Windows?

**Comment by jeffbi** [comment]
@iSazonov Thanks for adding the link. I keep thinking that putting it in the title works, but of course it doesn't.

File: test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1 (hunk 10 above)
Comment (jeffbi) [inline test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1]: Because the error condition doesn't appear on Windows. Unlike Unix, deleting or renaming a file does not have an adverse effect on the enumeration---the file is listed in its original form.

File: src/System.Management.Automation/engine/Utils.cs (hunk 1 above)
Comment (jeffbi) [inline src/System.Management.Automation/engine/Utils.cs]: No, removed.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 2 above)
Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Fixed

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 3 above)
Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Fixed

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 4 above)
Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Fixed

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 5 above)
Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Fixed

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 6 above)
Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Fixed

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 8 above)
Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Fixed

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 7 above)
Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Fixed

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 9 above)
Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Fixed

File: test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1 (hunk 10 above)
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1]: So the test is ok on Windows too?

Comment (jeffbi) [inline test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1]: No. On Windows the test will fail because the enumeration will succeed with no errors emitted in the middle of the process, and `$Error.Count` will be zero.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 3 above)
Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: @iSazonov  I think I need to revert this change. Wrapping that code in `#if debug` is causing the error condition to not occur, and thus the tests and CI to fail.

File: test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1 (hunk 10 above)
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1]: We need to change those tests so that they work the same on all platforms.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 3 above)
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: @daxian-dbw @lzybkr  Could you please clarify should we leave test codes in Release build?

File: test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1 (hunk 10 above)
Comment (jeffbi) [inline test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1]: But the underlying behavior is not the same on all platforms. On Unix, if a file is deleted or renamed during enumeration over the result of `DirectoryInfo.EnumerateFiles()`an exception is thrown when attempting to access a property on the `FileSystemInfo` object. On Windows, no exception is thrown, the property is successfully accessed, and the enumeration goes happily on.

The test hook code does not force an error. It sets up the _condition_ which may or may not trigger an error. If the same condition triggers an error on one platform but not on another, how are the tests for _how the error is handled_ expected to behave the same on both platforms?

Comment (jeffbi) [inline test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1]: Sorry, I think I just realized what you meant. You want to change the test so that `if ($IsWindows)` the error count is zero, otherwise it is one. Is that right?

Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1]: Original Issue:
>Expected
Get-ChildItem should skip inaccessible paths (with error) and continue enumerating files and paths that are accessible.

Our tests must be simple as that expected: dir without throw return expected list (different on different platforms).

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 3 above)
Comment (lzybkr) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: We do leave test hooks in all builds because we primarily test release builds./

File: test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1 (hunk 10 above)
Comment (jeffbi) [inline test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1]: I hope this is what you're looking for. On Unix the tests check that the error was emitted and that the deleted/renamed item was left out of the list. On Windows the tests check that no error was emitted and that the list is complete.

I have also removed the `#if DEBUG` to allow the CI checks to succeed. I would rather the hook code be in debug-only, but the CI and `Start-PSBuild`builds seem to be release builds.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 11]
```diff
@@ -1659,51 +1659,85 @@ protected override void InvokeDefaultAction(string path)
...
+                        var testActionFilename = InternalTestHooks.GciEnumerationActionFilename;
+                        if (filesystemInfo.Name == testActionFilename)
                         {
-                            switchAttributeFilter = switchEvaluator.Evaluate(filesystemInfo.Attributes);  // switch parameters
-                            switchFilterHidden = switchEvaluator.ExistsInExpression(FileAttributes.Hidden);
+                            var fullName = Path.Combine(directory.FullName, filesystemInfo.Name);
+                            var newFilename = InternalTestHooks.GciEnumerationActionRename;
+                            if (String.IsNullOrEmpty(newFilename))
+                            {
+                                File.Delete(fullName);
```
Comment (lzybkr) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: This test hook frightens me - please think through the security implications of this.

Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: We can hard code the test file names and call InternalTestHooks.GciEnumerationAction to only enable/disable the hook.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 3 above)
Comment (daxian-dbw) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: I would love to have those test hooks readonly in the release build, so they cannot be messed around to change powershell behavior. Problem is that some tests won't be able to run in a release build, which is not wanted.

File: test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1 (hunk 10 above)
Comment (jeffbi) [inline test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1]: Here's a version in which the hook now only allow the test script to select what actions to take, but the hook code internally is hard-coded to use specific file names.

File: src/System.Management.Automation/engine/Utils.cs [hunk 12]
```diff
@@ -1580,8 +1580,11 @@ public static class InternalTestHooks
         // Simulate 'System.Diagnostics.Stopwatch.IsHighResolution is false' to test Get-Uptime throw
         internal static bool StopwatchIsNotHighResolution;
 
+        // Will be either "delete" or "rename" during tests.
+        internal static string GciEnumerationAction = null;
+
         /// <summary>This member is used for internal test purposes.</summary>
-        public static void SetTestHook(string property, bool value)
+        public static void SetTestHook(string property, object value)
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/Utils.cs]: We can leave the parameter as bool and define two variables `internal static bool GciEnumerationActionDelete = false;` and `internal static bool GciEnumerationActionRename = false;`

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 13]
```diff
@@ -1659,51 +1659,87 @@ protected override void InvokeDefaultAction(string path)
...
-                        bool switchFilterHidden = false;     // "Hidden" is specified somewhere in the parameters
-
-                        if (null != evaluator)
+                        // Internal test code, run only if the
+                        // 'GciEnumerationAction' test hook is set
+                        if (InternalTestHooks.GciEnumerationAction == "delete")
                         {
-                            attributeFilter = evaluator.Evaluate(filesystemInfo.Attributes);  // expressions
-                            filterHidden = evaluator.ExistsInExpression(FileAttributes.Hidden);
+                            if (filesystemInfo.Name == "c")
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: We need to try to avoid a match with real names. Maybe use Guid-based names for test file names?

File: src/System.Management.Automation/engine/Utils.cs (hunk 12 above)
Comment (jeffbi) [inline src/System.Management.Automation/engine/Utils.cs]: I feel like it would be better to not allow both to be set at the same time, which the string property accomplishes.

Comment (iSazonov) [inline src/System.Management.Automation/engine/Utils.cs]: I talked about two variables - you can enable hooks at different times.

Comment (jeffbi) [inline src/System.Management.Automation/engine/Utils.cs]: Changed. If both are set at the same time, only the delete will be done.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 13 above)
Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Fixed. Using GUID-based names.

File: test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1 [hunk 14]
```diff
@@ -34,25 +40,25 @@ Describe "Get-ChildItem" -Tags "CI" {
...
+            $files[3].Name     | Should Be $item_c
+            $files[4].Name     | Should Be $item_D
         }
 
         It "Should list hidden files as well when 'Force' parameter is used" {
             $files = Get-ChildItem -path $TestDrive -Force
             $files | Should not be $null
             $files.Count | Should be 6
-            $files.Name.Contains(".F")
+            $files.Name.Contains($item_F)
```
Comment (jeffbi) [inline test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1]: No doubt. Fixed.

File: test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1 [hunk 15]
```diff
@@ -4,12 +4,18 @@ Describe "Get-ChildItem" -Tags "CI" {
 
         BeforeAll {
             # Create Test data
-            $null = New-Item -Path $TestDrive -Name "a" -ItemType "File" -Force
-            $null = New-Item -Path $TestDrive -Name "B" -ItemType "File" -Force
-            $null = New-Item -Path $TestDrive -Name "c" -ItemType "File" -Force
-            $null = New-Item -Path $TestDrive -Name "D" -ItemType "File" -Force
-            $null = New-Item -Path $TestDrive -Name "E" -ItemType "Directory" -Force
-            $null = New-Item -Path $TestDrive -Name ".F" -ItemType "File" -Force | %{$_.Attributes = "hidden"}
+            $item_a = "a3fe710a-31af-4834-bc29-d0b584589838"
```
Comment (jeffbi) [inline test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1]: The original filenames were `a`, `B`, `c`, `D`, `E`, and `.F`, in that letter casing, which appeared to have been a deliberate choice. To avoid disrupting any existing tests, I elected to keep the same letter casing in the GUID filenames.

It does look like I made a copy/paste error when I was generating GUID-based filenames. The filename for `$Item_E` should have begun with the letter/hex digit `E`. It now does.

Comment (jeffbi) [inline test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1]: The reason I used lower-case in the variable names was to call out that casing was significant.

**Comment by iSazonov** [comment]
LGTM.

@jeffbi Thanks! Great work!

File: src/System.Management.Automation/engine/Utils.cs [hunk 16]
```diff
@@ -1580,6 +1580,10 @@ public static class InternalTestHooks
         // Simulate 'System.Diagnostics.Stopwatch.IsHighResolution is false' to test Get-Uptime throw
         internal static bool StopwatchIsNotHighResolution;
 
+        // Will be either "delete" or "rename" during tests.
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/Utils.cs]: The comment should describe where these hooks are used, and used for what.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 17]
```diff
@@ -1659,51 +1659,87 @@ protected override void InvokeDefaultAction(string path)
...
+                        // Internal test code, run only if one of the
+                        // 'GciEnumerationAction' test hooks are set.
+                        if (InternalTestHooks.GciEnumerationActionDelete)
                         {
-                            attributeFilter = evaluator.Evaluate(filesystemInfo.Attributes);  // expressions
-                            filterHidden = evaluator.ExistsInExpression(FileAttributes.Hidden);
+                            if (filesystemInfo.Name == "c283d143-2116-4809-bf11-4f7d61613f92")
+                            {
+                                var fullName = Path.Combine(directory.FullName, filesystemInfo.Name);
+                                File.Delete(fullName);
```
Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: That was a safety choice. What actually triggers the error is invoking `filesystemInfo.Attributes` further down in the code. I wanted to avoid invoking any properties that might involve lazy evaluation, to avoid having the error occur while running test-hook code.

If we can be sure that using `filesystemInfo.FullName` won't cause the file system to be hit I would be happy to use it instead.

Comment (daxian-dbw) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: I changed it to `filesystemInfo.FullName` and the test passed on windows. I didn't try on Linux or OSX. Are you seeing issue with `filesystemInfo.FullName`?

Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: I haven't seen an issue, no. I was just trying to avoid one. I'll go ahead and make the change to `FullName`.

Comment (daxian-dbw) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Just tried on Ubuntu 16.04, `filesystemInfo.FullName` also works fine 😄

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 18]
```diff
@@ -1659,51 +1659,87 @@ protected override void InvokeDefaultAction(string path)
...
 
-                        bool attributeFilter = true;
-                        bool switchAttributeFilter = true;
-                        bool filterHidden = false;           // "Hidden" is specified somewhere in the expression
-                        bool switchFilterHidden = false;     // "Hidden" is specified somewhere in the parameters
-
-                        if (null != evaluator)
+                        // Internal test code, run only if one of the
+                        // 'GciEnumerationAction' test hooks are set.
+                        if (InternalTestHooks.GciEnumerationActionDelete)
```
Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: I'm concerned about hoisting this out of the loop. The point is to have a file go away while the enumeration is in progress. If we do the test outside the loop I don't think we've met the requirement---we've acquired the enumerator but have not yet started the enumeration. That's why we've chosen files that will not be the first in the enumeration.

Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: It seems we can put this **after** `IEnumerable<FileSystemInfo> sortedChildList = childList.OrderBy(c => c.Name, StringComparer.CurrentCultureIgnoreCase);`

Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: I'm not sure that solves the problem. Again, we have an enumerable object but enumeration doesn't start until the `foreach`.

Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: I think we get already the list in `foreach (IEnumerable<FileSystemInfo> childList in target)` - so after that we can safely delete/remove test file.

Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: `target` is just a `List` of `IEnumerable` objects, containing only 1 or 2 entries---an `IEnumerable` for directory names and an `IEnumerable` for file names. I don't think the act of getting a reference to an enumerable object from a list causes enumeration to begin.

Comment (daxian-dbw) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: @jeffbi This is a very good point. Let's keep it as is.

Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: I catched an enumaration issue second time in last week - need to go to school. :-)

The last question is whether to make a test for such normal runtime error?

File: src/System.Management.Automation/engine/Utils.cs (hunk 16 above)
Comment (jeffbi) [inline src/System.Management.Automation/engine/Utils.cs]: Fixed

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 19]
```diff
@@ -1659,51 +1659,87 @@ protected override void InvokeDefaultAction(string path)
...
+                            }
                         }
-                        if (null != switchEvaluator)
+                        else if (InternalTestHooks.GciEnumerationActionRename)
                         {
-                            switchAttributeFilter = switchEvaluator.Evaluate(filesystemInfo.Attributes);  // switch parameters
-                            switchFilterHidden = switchEvaluator.ExistsInExpression(FileAttributes.Hidden);
+                            if (filesystemInfo.Name == "B1B691A9-B7B1-4584-AED7-5259511BEEC4")
+                            {
+                                var fullName = Path.Combine(directory.FullName, filesystemInfo.Name);
```
Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Fixed

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 20]
```diff
@@ -1659,51 +1659,87 @@ protected override void InvokeDefaultAction(string path)
...
+                                File.Delete(fullName);
+                            }
                         }
-                        if (null != switchEvaluator)
+                        else if (InternalTestHooks.GciEnumerationActionRename)
                         {
-                            switchAttributeFilter = switchEvaluator.Evaluate(filesystemInfo.Attributes);  // switch parameters
-                            switchFilterHidden = switchEvaluator.ExistsInExpression(FileAttributes.Hidden);
+                            if (filesystemInfo.Name == "B1B691A9-B7B1-4584-AED7-5259511BEEC4")
```
Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Fixed

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 17 above)
Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Fixed

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 21]
```diff
@@ -1659,51 +1659,85 @@ protected override void InvokeDefaultAction(string path)
...
-                        bool switchFilterHidden = false;     // "Hidden" is specified somewhere in the parameters
-
-                        if (null != evaluator)
+                        // Internal test code, run only if one of the
+                        // 'GciEnumerationAction' test hooks are set.
+                        if (InternalTestHooks.GciEnumerationActionDelete)
                         {
-                            attributeFilter = evaluator.Evaluate(filesystemInfo.Attributes);  // expressions
-                            filterHidden = evaluator.ExistsInExpression(FileAttributes.Hidden);
+                            if (string.Equals(filesystemInfo.Name, "c283d143-2116-4809-bf11-4f7d61613f92", StringComparison.Ordinal))
```
Comment (daxian-dbw) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: The `string.Equals` check below uses `StringComparison.InvariantCulture` and this one uses `StringComparison.Ordinal`. It's better to be consistent.

**Comment by daxian-dbw** [comment]
@jeffbi thanks for the thorough thinking on the fix and test. One minor comment and it should be good to go once that's addressed.

**Review by daxian-dbw — APPROVED** [review]

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 21 above)
Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: D'oh! Leftover artifact, thanks for spotting that.

Fixed.
