### PR TITLE
Fix inconsistent exception message in -replace operator

### LINKED ISSUE #12333: Replace Operator InvalidOperation Exception Message
# Steps to reproduce

There are three variations of the Replacement Operator:
  * `-replace` is implicitly case-insensitive.
  * `-ireplace` is explicitly case-insensitive.
  * `-creplace` is case-sensitive.

The exception message returned when passing three or more comma separated values to `-replace`, `-ireplace` or `-creplace` is counterintuitive:

| Command                       | Exception Message                                                                      |
| ----------------------------- |--------------------------------------------------------------------------------------|
| `"foo" -replace "o", "e", "e"`  | `InvalidOperation: The -ireplace operator allows only two elements to follow it, not 3.` |
| `"foo" -ireplace "o", "e", "e"` | `InvalidOperation: The -ireplace operator allows only two elements to follow it, not 3.` |
| `"foo" -creplace "o", "e", "e"` | `InvalidOperation: The -replace operator allows only two elements to follow it, not 3.`  |

As the table above demonstrates, when either the `-replace` or `-ireplace` operator is used, the message content refers to `-ireplace`. This is not ideal but since `-replace` and `-ireplace` are functionally equivalent it's perhaps not a big deal. But what is particularly inappropriate is that the exception message for `-creplace` refers to `-replace`.

# Expected behavior

The exception message should ideally refer to the respective operator that was used. Else at a minimum, the message returned for the `-creplace` operator should refer to `-creplace`.

# Environment data

The same result is exhibited in PowerShell 5.1, 7.0.0 and 7.1.0-preview.1, full version details below:

```none
Name                           Value
----                           -----
PSVersion                      5.1.18362.628
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.628
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name                           Value
----                           -----
PSVersion                      7.1.0-preview.1
PSEdition                      Core
GitCommitId                    7.1.0-preview.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by jackdcasey**
# PR Summary

Fix inconsistent exception message in `-replace` operator

## PR Context

The exception message returned when passing three or more values to `-replace`, `-ireplace` or `-creplace` is not consistent with the actual operator used:

```
PS> "foo" -replace "f", "j", "h"
InvalidOperation: The -ireplace operator allows only two elements to follow it, not 3.
```
```
PS> "foo" -ireplace "f", "j", "h"
InvalidOperation: The -ireplace operator allows only two elements to follow it, not 3.
```
```
PS> "foo" -creplace "f", "j", "h"
InvalidOperation: The -replace operator allows only two elements to follow it, not 3.
```

My proposed changes would change the exception messages to: 
```
PS> "foo" -replace "f", "j", "h"
InvalidOperation: The -ireplace/-replace operator allows only two elements to follow it, not 3.
```
```
PS> "foo" -ireplace "f", "j", "h"
InvalidOperation: The -ireplace/-replace operator allows only two elements to follow it, not 3.
```
```
PS> "foo" -creplace "f", "j", "h"
InvalidOperation: The -creplace operator allows only two elements to follow it, not 3.
```
Due to the way these parameters are passed as a boolean, we don't have visibility into exactly what parameter was used. For this reason `-ireplace` and `-replace` "share" the same error message.

Closes #12333 

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [X] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Review by iSazonov — APPROVED** [review]

File: src/System.Management.Automation/engine/lang/parserutils.cs [hunk 1]
```diff
@@ -927,7 +927,7 @@ internal static object ReplaceOperator(ExecutionContext context, IScriptExtent e
                 {
                     // only allow 1 or 2 arguments to -replace
                     throw InterpreterError.NewInterpreterException(rval, typeof(RuntimeException), errorPosition,
-                        "BadReplaceArgument", ParserStrings.BadReplaceArgument, ignoreCase ? "-ireplace" : "-replace", rList.Count);
+                        "BadReplaceArgument", ParserStrings.BadReplaceArgument, ignoreCase ? "-replace/-ireplace" : "-creplace", rList.Count);
```
Comment (IISResetMe) [inline src/System.Management.Automation/engine/lang/parserutils.cs:930]: Why not inspect the original script text to find out whether the caller explicitly invoked `-ireplace`? 

```csharp
    string operatorText = "-creplace";
    if(ignoreCase)
    {
        if(errorPosition.Text.IndexOf("ireplace", StringComparison.InvariantCultureIgnoreCase){
            operatorText = "-ireplace";
        }
        else
        {
            operatorText = "-replace";
        }
    }

    throw InterpreterError.NewInterpreterException(rval, typeof(RuntimeException), errorPosition,
        "BadReplaceArgument", ParserStrings.BadReplaceArgument, operatorText, rList.Count)

**Review by IISResetMe — CHANGES_REQUESTED** [review]

File: src/System.Management.Automation/engine/lang/parserutils.cs (hunk 1 above)
Comment (jackdcasey) [reply src/System.Management.Automation/engine/lang/parserutils.cs:930]: @IISResetMe Good catch! It must have been late when I worked on this, I missed the parameter being available in `errorPosition.Text`. From what I've found, using this value directly works to generate the correct error message: 
```csharp
throw InterpreterError.NewInterpreterException(rval, typeof(RuntimeException), errorPosition,
    "BadReplaceArgument", ParserStrings.BadReplaceArgument, errorPosition.Text, rList.Count);
```
Here's an example of the errors: 
```
PS >"foo" -replace "a", "b", "c"
InvalidOperation: The -replace operator allows only two elements to follow it, not 3.

PS >"foo" -creplace "a", "b", "c"
InvalidOperation: The -creplace operator allows only two elements to follow it, not 3.

PS >"foo" -ireplace "a", "b", "c"
InvalidOperation: The -ireplace operator allows only two elements to follow it, not 3.
```

I'm a fan of this method, I believe it's honestly more readable than the ternary operator currently being used 😁

**Review by iSazonov — APPROVED** [review]

File: src/System.Management.Automation/engine/lang/parserutils.cs (hunk 1 above)
Comment (IISResetMe) [reply src/System.Management.Automation/engine/lang/parserutils.cs]: Beautiful! 😍  

Was unsure whether the `errorPosition` extent was for the operator itself or the whole expression.

**Review by adityapatwardhan — APPROVED** [review]

**Comment by iSazonov** [comment]
@jackdcasey  Thanks for your contribution!

**Comment by TravisEz13** [comment]
I don't think this meets the bar to backport

**Comment by TravisEz13** [comment]
Triage determined this does not meet the bar for backport

**Comment by iSazonov** [comment]
Should we set 7.1.0-preview.3 for history?

**Comment by TravisEz13** [comment]
Not possible at this point.
