### PR TITLE
Use the original precision (prior-dotnet-core-3) for double/fload-to-string conversion

### LINKED ISSUE #9779: Float sum precision regression on 7.0.0-preview1
# Steps to reproduce

```powershell
@(1.1) * 10 | measure -Sum  
```

# Expected behavior
This is 6.2.0 behavior
```none
Count             : 10
Average           : 
Sum               : 11
Maximum           : 
Minimum           : 
StandardDeviation : 
Property          : 
```

# Actual behavior
This is 7.0.0-preview.1
```none
Count             : 10
Average           : 
Sum               : 10.999999999999998
Maximum           : 
Minimum           : 
StandardDeviation : 
Property          : 
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.1
PSEdition                      Core
GitCommitId                    7.0.0-preview.1
OS                             Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #9779 

.NET Core changes to return "shortest roundtrippable string" by default for the `ToString()` method of `double` and `float` types. This results in `ToString()` for `double`/`float` values sometimes return a string in 17-digit/9-digit precision format. This PR updated the double/float-to-string conversion in PowerShell to continue using the old precision specifier before the change in .NET Core 3.0.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by PoshChan** [comment]
@daxian-dbw, your last commit had 14 failures in `PowerShell-CI-linux`
(These are 5 of the failures)

TabCompletion.Should complete abbreviated cmdlet
```powershell
Expected exactly 'Import-PowerShellDataFile', but got $null.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1: line 16
16:         $res | Should -BeExactly 'Import-PowerShellDataFile'
```
TabCompletion.Should complete abbreviated function
```powershell
Expected the actual value to be greater than or equal to 1, but got 0.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1: line 21
21:         $res.Count | Should -BeGreaterOrEqual 1
```
Temp: drive.TEMP: drive exists
```powershell
Expected exactly 'Temp', but got $null.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/Get-PSDrive.Tests.ps1: line 64
64:         $res.Name | Should -BeExactly "Temp"
```
Get-Command Feature tests.-UseAbbreviationExpansion tests.Can return multiple results relying on auto module loading
```powershell
Expected a collection with size 2, but got an empty collection.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Command.Tests.ps1: line 39
39:             $results | Should -HaveCount 2
```
Get-Command Feature tests.-UseAbbreviationExpansion tests.Can return multiple results for cmdlets matching abbreviation
```powershell
Expected 'Invoke-Command' to be found in collection @(), but it was not found.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Command.Tests.ps1: line 69
69:             $results.Name | Should -Contain "Invoke-Command"
```

**Comment by PoshChan** [comment]
@daxian-dbw, your last commit had 8 failures in `PowerShell-CI-macos`
(These are 5 of the failures)

Temp: drive.TEMP: drive exists
```powershell
Expected exactly 'Temp', but got $null.
at <ScriptBlock>, /Users/vsts/agent/2.152.1/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/Get-PSDrive.Tests.ps1: line 64
64:         $res.Name | Should -BeExactly "Temp"
```
Get-Command Feature tests.-UseAbbreviationExpansion tests.Can return multiple results relying on auto module loading
```powershell
Expected a collection with size 2, but got an empty collection.
at <ScriptBlock>, /Users/vsts/agent/2.152.1/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Command.Tests.ps1: line 39
39:             $results | Should -HaveCount 2
```
Get-Command Feature tests.-UseAbbreviationExpansion tests.Can return multiple results for cmdlets matching abbreviation
```powershell
Expected 'Invoke-Command' to be found in collection @(), but it was not found.
at <ScriptBlock>, /Users/vsts/agent/2.152.1/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Command.Tests.ps1: line 69
69:             $results.Name | Should -Contain "Invoke-Command"
```
Get-Command Feature tests.-UseAbbreviationExpansion tests.Will return multiple results for functions matching abbreviation
```powershell
Expected a collection with size 2, but got an empty collection.
at <ScriptBlock>, /Users/vsts/agent/2.152.1/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Command.Tests.ps1: line 87
87:                 $results | Should -HaveCount 2
```
Get-Command Feature tests.-UseAbbreviationExpansion tests.Valid cmdlets works with name i-psdf and module $null
```powershell
Expected a collection with size 1, but got an empty collection.
at <ScriptBlock>, /Users/vsts/agent/2.152.1/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Command.Tests.ps1: line 62
62:             $results | Should -HaveCount 1
```

File: src/System.Management.Automation/engine/MshObject.cs [hunk 1]
```diff
@@ -1294,20 +1290,46 @@ internal static string ToString(ExecutionContext context, object obj, string sep
...
-
+                        str = dbl.ToString(LanguagePrimitives.DoublePrecision, formatProvider);
+                        break;
                     case TypeCode.Single:
                         float sgl = (float)obj;
-                        return sgl.ToString(formatProvider);
+                        str = sgl.ToString(LanguagePrimitives.SinglePrecision, formatProvider);
+                        break;
+                    default:
+                        success = false;
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/MshObject.cs]: Rather than create a `success` variable that readers must follow the state of in the function I'd just have:

```csharp
switch (typecode)
{
    case TypeCode.String:
        ...
        break;

    default:
        return false;
}

return true;
```

File: src/System.Management.Automation/engine/MshObject.cs [hunk 2]
```diff
@@ -1269,23 +1269,19 @@ internal static string ToStringParser(ExecutionContext context, object obj, IFor
...
-
-            #region plain object
-            if (mshObj == null)
+            bool TryFastTrackPrimitiveTypes(object obj, out string str)
             {
-                if (obj == null)
-                {
-                    return string.Empty;
-                }
+                str = null;
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/MshObject.cs]: I'm a bit averse to having the defaults be to return `true` with `str = null`, and that also loses the nice compile-time check that `str` was set properly.

I think the compiler is smart enough to move `str = null` to the `default` case and still allow the program, while ensuring that any further changes won't return `true` with a null string.

File: src/System.Management.Automation/engine/MshObject.cs [hunk 3]
```diff
@@ -1269,23 +1269,19 @@ internal static string ToStringParser(ExecutionContext context, object obj, IFor
         /// </exception>
         internal static string ToString(ExecutionContext context, object obj, string separator, string format, IFormatProvider formatProvider, bool recurse, bool unravelEnumeratorOnRecurse)
         {
-            PSObject mshObj = obj as PSObject;
-
-            #region plain object
-            if (mshObj == null)
+            bool TryFastTrackPrimitiveTypes(object obj, out string str)
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/MshObject.cs]: Is this a new nested method syntax? I'm in two minds about it; other than making the body of this method noisier, I'm not sure what it offers beyond a normal `private` method. For example, I don't see why the JIT would be less able to inline the latter.

I can also imagine this method having broader usage in `LanguagePrimitives`.

File: src/System.Management.Automation/engine/MshObject.cs [hunk 4]
```diff
@@ -1294,20 +1290,46 @@ internal static string ToString(ExecutionContext context, object obj, string sep
...
+
+            #region plain object
+            if (mshObj == null)
+            {
+                if (obj == null)
+                {
+                    return string.Empty;
+                }
+
+                // Fast-track the primitive types...
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/MshObject.cs]: This comment doesn't really add new information beyond the method name

File: src/System.Management.Automation/engine/MshObject.cs (hunk 1 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/MshObject.cs]: I like what you proposed. Updated.

File: src/System.Management.Automation/engine/MshObject.cs (hunk 2 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/MshObject.cs]: Updated.

File: src/System.Management.Automation/engine/MshObject.cs (hunk 4 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/MshObject.cs]: Comments removed.

File: src/System.Management.Automation/engine/MshObject.cs (hunk 3 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/MshObject.cs]: It's a local function.

> I'm not sure what it offers beyond a normal private method.

C# make it more efficient to access the variables from the enclosing method via `ref` reference (vs. parameter argument passed to a private method). Here, I do access the `formatProvider` variable directly within the local function, but there is no much difference from passing `formatProvider` to a private method. This logic was scoped only to this method, so I tend to keep it that way until it actually gets used elsewhere.

**Comment by PoshChan** [comment]
@daxian-dbw, your last commit had 4 failures in `PowerShell-CI-linux`
DotNetAPI.Should be able to use static .NET classes and get a constant
```powershell
Expected regular expression '2.718281828459045' to match 2.71828182845905, but it did not match.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Language/Interop/DotNet/DotNetAPI.Tests.ps1: line 9
9: 	[System.Math]::E  | Should -Match $posh_E.ToString()
```
ParserTests (admin\monad\tests\monad\src\engine\core\ParserTests.cs).Numerical Notations Tests (starting at line 2374 to line 2452).-3.402823E+38 should return -3.4028235E+38, with type [double]
```powershell
Expected '-3.4028235E+38', but got -3.402823E+38.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Language/Parser/Parser.Tests.ps1: line 937
937:             ExecuteCommand $Script | Should -Be $ExpectedValue
```
ParserTests (admin\monad\tests\monad\src\engine\core\ParserTests.cs).Numerical Notations Tests (starting at line 2374 to line 2452).3.402823E+38 should return 3.4028235E+38, with type [double]
```powershell
Expected '3.4028235E+38', but got 3.402823E+38.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Language/Parser/Parser.Tests.ps1: line 937
937:             ExecuteCommand $Script | Should -Be $ExpectedValue
```
Join-String.Should join numeric values Formatted
```powershell
Expected strings to be the same, but they were different.
Expected length: 16
Actual length:   13
Strings differ at index 3.
Expected: '1.20; 3.40; 5.60'
But was:  '1.2; 3.4; 5.6'
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Join-String.Tests.ps1: line 67
67:         $actual | Should -BeExactly $expected
```

**Comment by daxian-dbw** [comment]
Enforcing `G15` for double type results in a few test failures. Will look into them.

**Review by iSazonov — APPROVED** [review]
LGTM with 2 minor comments.

File: src/System.Management.Automation/engine/MshObject.cs [hunk 5]
```diff
@@ -1269,23 +1269,16 @@ internal static string ToStringParser(ExecutionContext context, object obj, IFor
...
-            #region plain object
-            if (mshObj == null)
+            bool TryFastTrackPrimitiveTypes(object obj, out string str)
             {
-                if (obj == null)
-                {
-                    return string.Empty;
-                }
+                Type valueType = obj.GetType();
+                TypeCode code = valueType.GetTypeCode();
```
[the remark this answers is not in the document]
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/MshObject.cs]: Changed to use `Convert.GetTypeCode(object)`.

File: src/System.Management.Automation/engine/MshObject.cs (hunk 3 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/MshObject.cs]: Renamed the `obj` parameter to `value`.

**Comment by daxian-dbw** [comment]
@iSazonov @rjmholt The `TryFastTrackPrimitiveTypes` method was updated to always honor the `format` and `formatProvider`.

File: test/powershell/Language/Interop/DotNet/DotNetAPI.Tests.ps1 [hunk 6]
```diff
@@ -6,8 +6,8 @@ Describe "DotNetAPI" -Tags "CI" {
     $posh_pi = 3.14159265358979
 
     It "Should be able to use static .NET classes and get a constant" {
-	[System.Math]::E  | Should -Match $posh_E.ToString()
-	[System.Math]::PI | Should -Match $posh_pi.ToString()
+	[System.Math]::E  | Should -Match $posh_E.ToString("G15")
```
Comment (rjmholt) [inline test/powershell/Language/Interop/DotNet/DotNetAPI.Tests.ps1]: The semantics in this test seem hard to reason about; it expects a numerical constant, stringified by language primitives to be equal to a particular direct stringification when it's turned into a regex.

That seems like a good test (except for the regex bit), but doesn't feel like what the name of the test implies, which I would write like:

```powershell
It "Should be able to use static .NET classes and get a constant" {
    [System.Math]::E | Should -Be 2.7182818284590451
    [System.Math]::PI | Should -Be 3.1415926535897931
}
```

Comment (rjmholt) [reply test/powershell/Language/Interop/DotNet/DotNetAPI.Tests.ps1]: And then it's useful to keep the `ToString(...)` tests as a different .NET API test

**Review by rjmholt — APPROVED** [review]
Looks good. Left a minor comment

File: src/System.Management.Automation/engine/MshObject.cs [hunk 7]
```diff
@@ -1287,23 +1284,18 @@ bool TryFastTrackPrimitiveTypes(object obj, out string str)
...
-                        str = obj.ToString();
-                        break;
                     case TypeCode.DateTime:
-                        DateTime dt = (DateTime)obj;
-                        str = dt.ToString(formatProvider);
-                        break;
                     case TypeCode.Decimal:
-                        Decimal dec = (Decimal)obj;
-                        str = dec.ToString(formatProvider);
+                        var formattable = (IFormattable)value;
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/MshObject.cs]: Interesting! Can you clarify why we use the interface?
I see there is many types supported the interface
https://source.dot.net/#System.Private.CoreLib/shared/System/IFormattable.cs,09da57c2c21a3a44,references - Single, Double, Datetime, Int16/32/64 and so on. Make sense use the interface for them?

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/MshObject.cs]: > Can you clarify why we use the interface?

Because ... all those primitive types support `ToString(string format, IFormatProvider)` (since they implement `IFormattable`), and we want to honor the passed in `format` and `formatProvider` when they are not null.

> Single, Double, Datetime, Int16/32/64 and so on. Make sense use the interface for them?

I already do that in the code. Now they honor the `format` and `formatProvider` passed in.

File: test/powershell/Language/Interop/DotNet/DotNetAPI.Tests.ps1 (hunk 6 above)
Comment (daxian-dbw) [reply test/powershell/Language/Interop/DotNet/DotNetAPI.Tests.ps1]: Sure, will do that.

File: src/System.Management.Automation/engine/MshObject.cs (hunk 7 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/MshObject.cs]: Ah, sorry - float is below.

**Review by iSazonov — APPROVED** [review]

**Comment by daxian-dbw** [comment]
Rebased to master to force Windows CI to work properly.

**Comment by iSazonov** [comment]
Restarted MacOs Ci.

**Comment by daxian-dbw** [comment]
@iSazonov All CI builds passed. This PR is ready to be merged :)

**Comment by iSazonov** [comment]
.NET Core changes to return "shortest roundtrippable string" by default for the ToString() method of double and float types. This results in ToString() for double/float values sometimes return a string in 17-digit/9-digit precision format. This PR updated the double/float-to-string conversion in PowerShell to continue using the old precision specifier before the change in .NET Core 3.0.

**Comment by vors** [comment]
Thank you, guys! Appreciate it 🙏 🙏 🙏
