### PR TITLE
Fix 'StringBuilder' initialization

### LINKED ISSUE #3457: Suspicious StringBuilder using
Hi.
Please look this code fragment:
1) https://github.com/PowerShell/PowerShell/blob/4d0e21f6d2fa8280fb69e858b2f4b61bc52841f8/src/System.Management.Automation/engine/InitialSessionState.cs#L3940
```
 var allErrors = new StringBuilder('\n');

```

StringBuilder constructor with a char argument constructs a string with no characters in it ( this argument  specified  initial capacity) .

You may see example - http://ideone.com/1pPHlZ
I hope this may help you

These possible defects found with [AppChecker](https://npo-echelon.ru/en/solutions/appchecker.php)

### PR DESCRIPTION
**Pull request by iSazonov**
Close #3457

### CODE REVIEW

File: src/System.Management.Automation/engine/InitialSessionState.cs [hunk 1]
```diff
@@ -3937,7 +3937,8 @@ internal void UpdateTypes(ExecutionContext context, bool updateOnly)
 
             if (errors.Count > 0)
             {
-                var allErrors = new StringBuilder('\n');
+                // Bug: don't use '\n' ('char' convert implicitly to 'ushort' and 'int' and initialize 'StringBuilder' size)
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/InitialSessionState.cs]: Good catch @iSazonov 👍 
Can you change `Bug:` to `Note:` please? `Bug:` usually indicates there is a potential bug here that needs to be revisited.

**Review by daxian-dbw — APPROVED** [review]

File: src/System.Management.Automation/engine/InitialSessionState.cs [hunk 2]
```diff
@@ -3937,7 +3937,8 @@ internal void UpdateTypes(ExecutionContext context, bool updateOnly)
 
             if (errors.Count > 0)
             {
-                var allErrors = new StringBuilder('\n');
+                // Note: don't use '\n' ('char' convert implicitly to 'ushort' and 'int' and initialize 'StringBuilder' size)
```
Comment (lzybkr) [inline src/System.Management.Automation/engine/InitialSessionState.cs]: While the comment is interesting, I think it's a distraction from understanding the code.

Comment (iSazonov) [inline src/System.Management.Automation/engine/InitialSessionState.cs]: This should only protect against reverting. 
(Feel free to approve the comment.)

Comment (lzybkr) [inline src/System.Management.Automation/engine/InitialSessionState.cs]: I still don't think it's helpful - education of weird aspects of an api don't really belong in random places in code unless it's extremely likely that you'll hit the problem again.

In this case, I think it's unlikely.

Comment (iSazonov) [inline src/System.Management.Automation/engine/InitialSessionState.cs]: What is the preferred solution do you see here? Remove the comment?
Complete solution I believe should be in the compiler.
Also we can do here:
```powershell
var allErrors = new StringBuilder(); 
allErrors.Append('\n'); 
```

Comment (lzybkr) [inline src/System.Management.Automation/engine/InitialSessionState.cs]: I think removing the comment is sufficient as it's mostly obvious that a string argument initializes the instance.

If you'd like to make other improvements though - it's good practice to pass the estimated capacity when constructing a `StringBuilder` to minimize extra allocations, but only if it's easy to estimate (e.g. use a constant, avoid computing the "estimate").

And calling `Append` with a char might be slightly better than passing a string to the constructor, but honestly the performance here doesn't really matter.

Comment (iSazonov) [inline src/System.Management.Automation/engine/InitialSessionState.cs]: @lzybkr  Thanks for great comment!
Here we cannot use a constant, the capacity is ~(1+ 2 * errors.Count).

Do it make sense to open CoreFX issue to add new constructor for StringBuilder ?
`StringBuilder new(char value)`

Comment (lzybkr) [inline src/System.Management.Automation/engine/InitialSessionState.cs]: To be clear, a reasonable estimate is probably better than the default, and constant, or easily computed value, e.g. count*80 our something like that is reasonable. But again, it really doesn't matter here.

As for a CoreFX issue - it's up to you. I feel like they might discuss it, but reject it in favor of fewer APIs because it should if you properly test, you'd notice your character is missing.

Comment (iSazonov) [inline src/System.Management.Automation/engine/InitialSessionState.cs]: I opened Issue https://github.com/dotnet/corefx/issues/17745
