### PR TITLE
Turn off AMSI member invocation on *nix release builds

### LINKED ISSUE #21492: AMSI logging implemented on Linux
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The AMSI logging is still being performed on Linux even though there are no AMSI modules installed.

As demonstrated in [#21473](https://github.com/PowerShell/PowerShell/issues/21473) this can lead to excessive heap usage

### Expected behavior

```console
#!/usr/bin/env pwsh
$env:__PSDumpAMSILogContent='1'
$bytes = new-object byte[] -ArgumentList @(,200554320)
$random = new-object Random
$random.NextBytes($bytes)

Should not print anything
```

### Actual behavior

```console
#!/usr/bin/env pwsh
$env:__PSDumpAMSILogContent='1'
$bytes = new-object byte[] -ArgumentList @(,200554320)
$random = new-object Random
$random.NextBytes($bytes)

Prints the following log

=== Amsi notification report content ===
<System.Random>.NextBytes(<System.Byte[]>)
=== Amsi notification report success: False ===
```

### Error details

```console
No actual error other than incorrect behaviour
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Debian GNU/Linux 11 (bullseye)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by jborean93**
# PR Summary
Turn off the AMSI member invocation logging for non-Windows release builds. This is slightly more efficient as there's no extra work to create the AMSI string.

Fixes: https://github.com/PowerShell/PowerShell/issues/21492

## PR Context
https://github.com/PowerShell/PowerShell/issues/21492#issuecomment-2070926281

> WG reviewed this and agreed that the .NET method invocation logging for AMSI should only apply to Windows. The change should be separate and not dependent on the env var.

It doesn't make sense for this feature to be on for a proper release build as writing to stdout will affect anything calling PowerShell. The env var name also indicates this is an internal optional and not a publicly supported feature so shouldn't be under any API contract.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
  - [x] None
  - **OR**
  - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
    - [ ] Experimental feature name(s): 
- **User-facing changes**
  - [x] Not Applicable
  - **OR**
  - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
  - [x] N/A or can only be tested interactively
  - **OR**
  - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
  - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
  - **OR**
  - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
    - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
      - [ ] Issue filed: 
    - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
      - [ ] Issue filed: 
    - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
      - [ ] Issue filed: 
    - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
      - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs [hunk 1]
```diff
@@ -3694,6 +3694,10 @@ private static string ArgumentToString(object arg)
 
         internal static void LogMemberInvocation(string targetName, string name, object[] args)
         {
+#if UNIX && !DEBUG
```
Comment (mklement0) [inline src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs:3697]: Thanks for tackling this, but, given that there seems to be only one call to this method (in `Binders.cs`), wouldn't it be better for performance reasons to conditionally exclude that call instead?

Comment (SeeminglyScience) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs:3697]: Nah the JIT should optimize it out

Comment (iSazonov) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs:3697]: It should have, but ... does it and at what point (interpreter)?

Comment (mklement0) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs:3697]: Taking a closer look at the call site, it seems that  a (cached) reference to the method is passing as an argument to another method, and it's not clear to me how that could be optimized away (but I'm not familiar with the subtleties of JIT compilation), especially since it seems desirable to prevent that other method call altogether.

https://github.com/PowerShell/PowerShell/blob/623c45174ac7c455518f1e0f11fa485110bcb45d/src/System.Management.Automation/engine/runtime/Binding/Binders.cs#L6946-L6958

Comment (iSazonov) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs:3697]: @mklement0 The code you referenced does only one thing - call `LogMemberInvocation` method. This is the code that should have been excluded.

Comment (mklement0) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs:3697]: Ah, of course, thanks. I agree.

Comment (jborean93) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs:3697]: The reason why I put the change here is in case the method is called in multiple places in the future. I can certainly change it so the expression tree doesn't call it but I'm not sure if there is any actual overhead to care about with just calling a method that is ultimately a no-op. Will defer to the pwsh team to see what they decide here.

Comment (mklement0) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs:3697]: Thanks, Jordan. I suppose a pragmatic way to handle this would be to to use `#if UNIX && !DEBUG` around _both_ the currently known only call site as well as inside the method.

**Review by SeeminglyScience — CHANGES_REQUESTED** [review]
Feel free to ping me on discord when the changes are made (or you've otherwise responded) and I'll get this merged. Thanks Jordan! ❤️

File: src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs (hunk 1 above)
Comment (jborean93) [reply src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs]: Updated to follow this pattern.

**Review by SeeminglyScience — APPROVED** [review]
LGTM! Thank you Jordan!

File: src/System.Management.Automation/engine/runtime/Binding/Binders.cs [hunk 2]
```diff
@@ -6947,15 +6947,7 @@ internal static DynamicMetaObject InvokeDotNetMethod(
...
-                expr = Expression.Block(
-                    Expression.Call(
-                        CachedReflectionInfo.MemberInvocationLoggingOps_LogMemberInvocation,
-                        Expression.Constant(targetName),
-                        Expression.Constant(name),
-                        Expression.NewArrayInit(
-                            typeof(object),
-                            args.Select(static e => e.Expression.Cast(typeof(object))))),
-                    expr);
+                MaybeAddMemberInvocationLogging(expr, targetName, name, args);
```
Comment (mklement0) [inline src/System.Management.Automation/engine/runtime/Binding/Binders.cs:6950]: I may be missing something,  but it looks like the return value from this method call is never used; shouldn't that be `expr =  MaybeAddMemberInvocationLogging(expr, targetName, name, args);`?

Comment (jborean93) [reply src/System.Management.Automation/engine/runtime/Binding/Binders.cs:6950]: Good pickup, sorry for missing that. @SeeminglyScience will be submitting a new PR to fix that.

Comment (iSazonov) [reply src/System.Management.Automation/engine/runtime/Binding/Binders.cs:6950]: That says there are no tests.
