### PR TITLE
Get/Add-Content throws improved error when targeting a container

### LINKED ISSUE #2686: Bad error message when using Get-Content with a Directory
I just installed the latest release of the Powershell by typing:
`sudo dpkg -i powershell_6.0.0-alpha.12-1ubuntu1.16.04.1_amd64.deb`

There was no errors during installation, but it seems that I have no access to Linux paths from Powershell (**even as a root**).

Steps to reproduce
------------------
Run powershell and type:
`Get-Content ~`

Expected behavior
-----------------
Should provide content of the home directory of current user (similarly as Linux command `ls ~`).

Please note that even if I run powershell as root (by typing `sudo powershell`) I receive mentioned error.

Actual behavior
---------------
"PermissionDenied" error

```
powershell

PS /home/testingdata> Get-Content ~                                             
Get-Content : Access to the path '/home/testingdata' is denied.
At line:1 char:1
+ Get-Content ~
+ ~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (/home/testingdata:String) [Ge 
   t-Content], UnauthorizedAccessException
    + FullyQualifiedErrorId : GetContentReaderUnauthorizedAccessError,Microsof 
   t.PowerShell.Commands.GetContentCommand
 
PS /home/testingdata> whoami                                                    
testingdata
PS /home/testingdata> 
```

Trying as a root:

```
sudo su
cd ~

PS /root>  Get-Content ~                                                        
Get-Content : Access to the path '/root' is denied.
At line:1 char:1
+ Get-Content ~
+ ~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (/root:String) [Get-Content],  
   UnauthorizedAccessException
    + FullyQualifiedErrorId : GetContentReaderUnauthorizedAccessError,Microsof 
   t.PowerShell.Commands.GetContentCommand
 
PS /root> whoami                                                                
root
```

Environment data
----------------

I use Ubuntu 16.04 LTS 64-bit.

> Name                           Value                                           
> ----                           -----                                           
> PSVersion                      6.0.0-alpha                                     
> PSEdition                      Core                                            
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
> BuildVersion                   3.0.0.0                                         
> GitCommitId                    v6.0.0-alpha.12                                 
> CLRVersion                                                                     
> WSManStackVersion              3.0                                             
> PSRemotingProtocolVersion      2.3                                             
> SerializationVersion           1.1.0.1

```

### LINKED ISSUE #7770: Get-Content throws confusing error when targeting a container
Rather than either producing a sensible error, or behaving in a reasonably predictable manner, `Get-Content` incorrectly throws an `Access Denied` error when pointed at a container object. This is *also* the case when using the variable accessor syntax.

Steps to reproduce
------------------

```powershell
PS> Get-Content c:\
```
or
```powershell
PS> ${c:\}
```

Expected behavior
-----------------

Option #1: A sensible error is produced
```none
Get-Content : Unable to access item contents as it is a container. You may be looking for Get-ChildItem instead.
At line:1 char:1
+ Get-Content c:\
+ ~~~~~~~~~~~~~~~
+ CategoryInfo          : ***: (C:\:String) [Get-Content], ***
+ FullyQualifiedErrorId : ***,Microsoft.PowerShell.Commands.GetContentCommand
```
Option #2: Route the call through to Get-ChildItem instead.
What is the "content" of a container if not its child items? It would make at least intuitive sense for Get-Content to simply call Get-ChildItem if passed a path to a container object instead of a leaf object.
```none
Directory: C:\


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/20/2017   2:55 PM                msys64
d-----        4/11/2018   7:38 PM                PerfLogs
d-r---        9/11/2018   2:11 PM                Program Files
d-r---        8/27/2018   6:53 AM                Program Files (x86)
d-----       10/17/2017   2:52 PM                tmp
d-r---        5/16/2018   3:10 AM                Users
d-----        11/6/2017   2:57 PM                usr
d-----         9/3/2018   5:02 AM                Windows
```

Actual behavior
---------------

(Cmdlet access)
```none
Get-Content : Access to the path 'C:\' is denied.
At line:1 char:1
+ Get-Content c:\
+ ~~~~~~~~~~~~~~~
+ CategoryInfo          : PermissionDenied: (C:\:String) [Get-Content], UnauthorizedAccessException
+ FullyQualifiedErrorId : GetContentReaderUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetContentCommand
```
(Variable access syntax)
```none
Access to the path 'C:\' is denied.
At line:1 char:1
+ ${C:\}
+ ~~~~~~
+ CategoryInfo          : PermissionDenied: (C:\:String) [], UnauthorizedAccessException
+ FullyQualifiedErrorId : GetContentReaderUnauthorizedAccessError
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

In my opinion, given the fact that the variable access syntax is a bit... edge case at the best of times (although undoubtedly also very handy at times) it would seem to make sense that Get-ChildItem would be called in these cases, so that it's possible to explore a provider in this fashion without necessitating use of the cmdlets at all.

### PR DESCRIPTION
**Pull request by kvprasoon**
## PR Summary

Fix #7770
Fix #2686 

Enhancing the error message as per #7770 and #2686

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed - Issue link: #7770
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by kvprasoon** [comment]
I think more rules are added to CodeFactor, issues are in untouched lines.
Even CI failure is something different.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 1]
```diff
@@ -6514,6 +6523,15 @@ public IContentWriter GetContentWriter(string path)
 
             try
             {
+                // Throw error if path is a directory.
+                if (Directory.Exists(path))
+                {
+                    string errMsg = StringUtil.Format(SessionStateStrings.GetContainerContentException, path);
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: We need another message for "write" cmdlets.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 2]
```diff
@@ -6366,9 +6366,18 @@ public IContentReader GetContentReader(string path)
...
+                    ErrorRecord error = new ErrorRecord(new InvalidOperationException(errMsg), "GetContainerContentException", ErrorCategory.InvalidOperation, null);
+                    WriteError(error);
+                    return stream;
+                }
+
                 // Users can't both read as bytes, and specify a delimiter
                 if (delimiterSpecified)
-                {
+                {
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Please fix the line.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 3]
```diff
@@ -6366,9 +6366,18 @@ public IContentReader GetContentReader(string path)
 
             try
             {
+                // Throw error if path is a directory.
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Please remove obvious comment.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 4]
```diff
@@ -6514,6 +6523,15 @@ public IContentWriter GetContentWriter(string path)
...
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Please remove obvious comment.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 1 above)
Comment (kvprasoon) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Added different error message for Write to container exception.

File: src/System.Management.Automation/resources/SessionStateStrings.resx [hunk 5]
```diff
@@ -281,7 +281,10 @@
   </data>
   <data name="GetContainerContentException" xml:space="preserve">
     <value>Unable to access '{0}' contents as it is a directory. Please use 'Get-ChildItem' instead.</value>
-  </data>  
+  </data>
+  <data name="WriteContainerContentException" xml:space="preserve">
+    <value>Unable to access '{0}' contents as it is a directory.</value>
```
Comment (iSazonov) [inline src/System.Management.Automation/resources/SessionStateStrings.resx]: I'd prefer `{0}` on end of the string because we support long paths.
```powershell
Unable to write content because it is a directory: {0}
```
For `GetContainerContentException` too.
/cc @SteveL-MSFT

Comment (kvprasoon) [reply src/System.Management.Automation/resources/SessionStateStrings.resx]: Sure, that makes sense.

Comment (SteveL-MSFT) [reply src/System.Management.Automation/resources/SessionStateStrings.resx]: I think the updated error messages are fine, even for `GetContainerContentException`.

**Comment by SteveL-MSFT** [comment]
The package validation on NJsonSchema is a known issue not related to this PR

**Review by SteveL-MSFT — APPROVED** [review]
LGTM

**Comment by iSazonov** [comment]
Reopen the PR to restart all CIs.

**Comment by SteveL-MSFT** [comment]
@kvprasoon can you rebase off master to pick up test fixes?

**Comment by iSazonov** [comment]
@kvprasoon I rebased for you. 

Further please create _new branch_ in your fork for every new change (don't put commits in forked master).

**Comment by kvprasoon** [comment]
@iSazonov Sure, will do it, learning OSS collaboration via each PR... thanks
