### PR TITLE
NoClobber WinCompat module import

### LINKED ISSUE #11419: Windows PowerShell modules have a priority if WinCompat feature is enabled
If WinCompat feature is enabled and loaded a Windows PowerShell module ,cmdlets from the module have a priority over PowerShell Core cmdlets.
/cc @anmenaga 

# Steps to reproduce

`Get-Date -UFormat "%s"` was changed in PowerShell Core and we use this in follow demo. 

image

# Expected behavior

Get-Date from PowerShell Core is involved.

I'd expect that PowerShell Core cmdlets have a priority or it is better WinCompat feature exports only requested cmdlet which explicitly presents in a feature list. Perhaps we could do `Enable/Disable-WindowsPowerShellCmdlet -Module <name> -Cmdlet <name>`

# Actual behavior

Get-Date from Windows PowerShell is involved.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6-71-g36d3b3c0e45937d56650b2747effde94c20b42aa
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### LINKED ISSUE #12014: Get-Item for files outputs PSObject instead of FileSystemInfo after Get-WmiObject
`Get-Item` normally outputs System.IO.FileInfo or System.IO.DirectoryInfo objects for the FileSystem provider.  After invoking `Get-WmiObject`, however, `Get-Item` outputs PSObject objects instead.  This causes binding to any command expecting one of the specific FileSystemInfo types to fail.

# Steps to reproduce

```powershell
(Get-Item .).GetType().Name
Get-WmiObject bogus -ea si
(Get-Item .).GetType().Name
```

# Expected behavior

```none
DirectoryInfo
DirectoryInfo
```

# Actual behavior

```none
DirectoryInfo
PSObject
```

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by anmenaga**
# PR Summary
Fix #11419
This addresses an issue where Windows PowerShell proxy modules have a priority over PS Core modules during WinCompat module import. (see  #11419 )

## PR Context

Implicit PS Remoting code (reused by WinCompat) is doing `Export-PSSession -AllowClobber`.
The fix is to omit `-AllowClobber` parameter if WinCompat:
1) is either importing a module that is one of the [`engine modules`](https://github.com/PowerShell/PowerShell/blob/b7cb335f03fe2992d0cbd61699de9d9aafa1d7c1/src/System.Management.Automation/engine/InitialSessionState.cs#L1586):
```
"Microsoft.PowerShell.Utility",
"Microsoft.PowerShell.Management",
"Microsoft.PowerShell.Diagnostics",
"Microsoft.PowerShell.Host",
"Microsoft.PowerShell.Security",
"Microsoft.WSMan.Management",
"Microsoft.PowerShell.Commands.Utility",
"Microsoft.PowerShell.Commands.Management",
"Microsoft.PowerShell.Commands.Diagnostics",
"Microsoft.PowerShell.ConsoleHost"
```
2) or is importing a module specified in `powershell.config.json` in `WindowsPowerShellCompatibilityNoClobberModuleList` list. (this list is empty by default)

If a module falls into one of these buckets, then PS-Core version of the module is imported first (for `engine modules` from `$PSHOME\Modules`), then proxies are generated for WinPS version of the module without `-AllowClobber` flag. This result s in proxy modules not having PS Core commands.

Fix #11419 
Fix #12014 

Also fixed a bug where WinCompat module DenyList was not working for module names containing dots `.` in some cases.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [X] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [X] Issue filed: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5724
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by iSazonov** [comment]
Do we want to have the fix as servicing one for 7.0 LTS?

**Comment by daxian-dbw** [comment]
@PoshChan please retry windows

**Comment by PoshChan** [comment]
@daxian-dbw, successfully started retry of `PowerShell-CI-Windows`

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs [hunk 1]
```diff
@@ -591,6 +591,27 @@ private void ImportModule_ViaAssembly(ImportModuleOptions importModuleOptions, A
             }
         }
 
+        private PSModuleInfo ImportModule_LocallyViaName_Wrapper(ImportModuleOptions importModuleOptions, string name)
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:594]: The name of this method doesn't really describe what the added functionality is. Perhaps something like `ImportModule_LocallyViaName_WithTelemetry` or `ImportModule_LocallyViaName_ForWinCompat`?

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs [hunk 2]
```diff
@@ -1890,7 +1907,11 @@ private bool IsModuleInDenyList(string[] moduleDenyList, string moduleName, Modu
             if (!string.IsNullOrEmpty(moduleName))
             {
                 // moduleName can be just a module name and it also can be a full path to psd1 from which we need to extract the module name
-                exactModuleName = Path.GetFileNameWithoutExtension(moduleName);
+                exactModuleName = moduleName;
+                if (Path.IsPathRooted(moduleName))
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:1911]: If we use a module name like `./relative/path/to/module.psm1`, will this continue to work with this change? A brief experiment shows that `IsPathRooted` returns false in this case.

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs [hunk 3]
```diff
@@ -1941,6 +1962,56 @@ private List<T> FilterModuleCollection<T>(IEnumerable<T> moduleCollection)
             return filteredModuleCollection;
         }
 
+        private void PrepareNoClobberWinCompatModuleImport(string moduleName, ModuleSpecification moduleSpec, ref ImportModuleOptions importModuleOptions)
+        {
+            List<string> NoClobberModuleList = PowerShellConfig.Instance.GetWindowsPowerShellCompatibilityNoClobberModuleList();
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:1967]:
```suggestion
            List<string> noClobberModuleList = PowerShellConfig.Instance.GetWindowsPowerShellCompatibilityNoClobberModuleList();
```

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs [hunk 4]
```diff
@@ -1941,6 +1962,56 @@ private List<T> FilterModuleCollection<T>(IEnumerable<T> moduleCollection)
...
+
+            // moduleName can be just a module name and it also can be a full path to psd1 from which we need to extract the module name
+            var coreModuleToLoad = moduleName;
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:1970]: Module specs might also have the name field be a path, which we support, since `RequiredModules` depends on it.

```suggestion
            string coreModuleToLoad = moduleSpec?.Name ?? moduleName;
            if (Path.IsPathRooted(coreModuleToLoad)) // Also need to deal with relative paths here -- helper function?
            {
                coreModuleToLoad = Path.GetFileNameWithoutExtension(coreModuleToLoad);
            }
```

Also, what's the behaviour here for relative paths?

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs [hunk 5]
```diff
@@ -1941,6 +1962,56 @@ private List<T> FilterModuleCollection<T>(IEnumerable<T> moduleCollection)
...
+            if (moduleSpec != null)
+            {
+                coreModuleToLoad = moduleSpec.Name;
+            }
+            else if (Path.IsPathRooted(moduleName))
+            {
+                coreModuleToLoad = Path.GetFileNameWithoutExtension(moduleName);
+            }
+
+            var coreModuleToLoadIsEngineModule = InitialSessionState.IsEngineModule(coreModuleToLoad);
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:1980]:
```suggestion
            bool isModuleToLoadEngineModule = InitialSessionState.IsEngineModule(coreModuleToLoad);
```

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs [hunk 6]
```diff
@@ -1941,6 +1962,56 @@ private List<T> FilterModuleCollection<T>(IEnumerable<T> moduleCollection)
...
+            if (coreModuleToLoadIsEngineModule || ((NoClobberModuleList != null) && NoClobberModuleList.Contains(coreModuleToLoad, StringComparer.OrdinalIgnoreCase)))
+            {
+                // if it is one of engine modules - first try to load it from $PSHOME\Modules
+                // otherwise rely on $env:PSModulePath (in which WinPS module location has to go after CorePS module location)
+                if (coreModuleToLoadIsEngineModule)
+                {
+                    var expectedCoreModulePath = Path.Combine(ModuleIntrinsics.GetPSHomeModulePath(), coreModuleToLoad);
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:1987]:
```suggestion
                    string expectedCoreModulePath = Path.Combine(ModuleIntrinsics.GetPSHomeModulePath(), coreModuleToLoad);
```

Comment (rjmholt) [reply src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:1987]: (The type of the LHS is not explicitly inferable from the RHS, and also has a predefined short type name)

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs [hunk 7]
```diff
@@ -1941,6 +1962,56 @@ private List<T> FilterModuleCollection<T>(IEnumerable<T> moduleCollection)
...
+                else
+                {
+                    ModuleSpecification tmpModuleSpec = new ModuleSpecification()
+                        {
+                            Guid = moduleSpec.Guid,
+                            MaximumVersion = moduleSpec.MaximumVersion,
+                            Version = moduleSpec.Version,
+                            RequiredVersion = moduleSpec.RequiredVersion,
+                            Name = coreModuleToLoad
+                        };
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:2007]:
```suggestion
                    {
                        Guid = moduleSpec.Guid,
                        MaximumVersion = moduleSpec.MaximumVersion,
                        Version = moduleSpec.Version,
                        RequiredVersion = moduleSpec.RequiredVersion,
                        Name = coreModuleToLoad
                    };
```

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs [hunk 8]
```diff
@@ -1968,6 +2039,24 @@ internal override IList<PSModuleInfo> ImportModulesUsingWinCompat(IEnumerable<st
                 return new List<PSModuleInfo>();
             }
 
+            // perform necessary preparations if module has to be imported with NoClobber mode
+            if (filteredModuleNames != null)
+            {
+                foreach(var moduleName in filteredModuleNames)
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:2045]:
```suggestion
                foreach(string moduleName in filteredModuleNames)
```

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs [hunk 9]
```diff
@@ -1968,6 +2039,24 @@ internal override IList<PSModuleInfo> ImportModulesUsingWinCompat(IEnumerable<st
...
+                {
+                    PrepareNoClobberWinCompatModuleImport(moduleName, null, ref importModuleOptions);
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:2047]: Calling like this, where one of two parameters is always null, suggests that there should be two overloads to me

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs [hunk 10]
```diff
@@ -1941,6 +1962,56 @@ private List<T> FilterModuleCollection<T>(IEnumerable<T> moduleCollection)
             return filteredModuleCollection;
         }
 
+        private void PrepareNoClobberWinCompatModuleImport(string moduleName, ModuleSpecification moduleSpec, ref ImportModuleOptions importModuleOptions)
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:1965]: This method is called `Prepare...` but it actually does the import, no? If so, I think it should just be called something like `ImportWinCompatModule` or `ImportWinCompatModuleNoClobber`

File: src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs [hunk 11]
```diff
@@ -99,6 +99,12 @@ protected internal struct ImportModuleOptions
             /// This will be allowed when the manifest explicitly exports functions which will limit all visible module functions.
             /// </summary>
             internal bool AllowNestedModuleFunctionsToExport;
+
+            /// <summary>
+            /// Flag that controls Export-PSSession -AllowClobber parameter in generating proxy modules from remote sessions.
+            /// Historically -AllowClobber in these scenarios was set as True.
+            /// </summary>
+            internal bool NoClobberExportPSSession;
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs:107]: It seems unusual to me that this and the field above are both fields rather than properties, but not private to this class. I think they should be changed to properties.

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs (hunk 3 above)
Comment (rjmholt) [reply src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:1967]: Also, this setting isn't needed for another few lines -- perhaps it makes more sense to keep it local to the condition below

File: test/powershell/Modules/Microsoft.PowerShell.Core/CompatiblePSEditions.Module.Tests.ps1 [hunk 12]
```diff
@@ -554,6 +554,79 @@ Describe "Additional tests for Import-Module with WinCompat" -Tag "Feature" {
...
+
+        It "NoClobber WinCompat import works for an engine module through command discovery" {
+
+            ConvertFrom-String -InputObject '1,2,3' -Delimiter ',' | Out-Null
+            $modules = Get-Module -Name Microsoft.PowerShell.Utility
+            $modules.Count | Should -Be 2
+            $proxyModule = $modules | Where-Object {$_.ModuleType -eq 'Script'}
+            $coreModule = $modules | Where-Object {$_.ModuleType -eq 'Manifest'}
+
+            $proxyModule.ExportedCommands.Keys | Should Contain "ConvertFrom-String"
```
Comment (rjmholt) [inline test/powershell/Modules/Microsoft.PowerShell.Core/CompatiblePSEditions.Module.Tests.ps1:576]: I think we're supposed to use the parameter forms now

```suggestion
            $proxyModule.ExportedCommands.Keys | Should -Contain "ConvertFrom-String"
```

File: test/powershell/Modules/Microsoft.PowerShell.Core/CompatiblePSEditions.Module.Tests.ps1 [hunk 13]
```diff
@@ -554,6 +554,79 @@ Describe "Additional tests for Import-Module with WinCompat" -Tag "Feature" {
...
+            $proxyModule.ExportedCommands.Keys | Should Not Contain "Get-Date"
```
Comment (rjmholt) [inline test/powershell/Modules/Microsoft.PowerShell.Core/CompatiblePSEditions.Module.Tests.ps1:577]:
```suggestion
            $proxyModule.ExportedCommands.Keys | Should -Not -Contain "Get-Date"
```

File: test/powershell/Modules/Microsoft.PowerShell.Core/CompatiblePSEditions.Module.Tests.ps1 [hunk 14]
```diff
@@ -554,6 +554,79 @@ Describe "Additional tests for Import-Module with WinCompat" -Tag "Feature" {
...
+
+            $coreModule.ExportedCommands.Keys | Should Contain "Get-Date"
+            $coreModule.ExportedCommands.Keys | Should Not Contain "ConvertFrom-String"
+
+            $proxyModule | Remove-Module -Force
+        }
+
+        It "NoClobber WinCompat import works for an engine module through -UseWindowsPowerShell parameter" {
+
+            Import-Module Microsoft.PowerShell.Management -UseWindowsPowerShell
```
Comment (rjmholt) [inline test/powershell/Modules/Microsoft.PowerShell.Core/CompatiblePSEditions.Module.Tests.ps1:587]: Ideally we should also have a test using a module specification, given the code devoted to making that work

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs [hunk 15]
```diff
@@ -1024,7 +1062,10 @@ private PSModuleInfo ImportModule_LocallyViaName(ImportModuleOptions importModul
                 {
                     powerShell.AddCommand("Export-PSSession");
                     powerShell.AddParameter("OutputModule", wildcardEscapedPath);
-                    powerShell.AddParameter("AllowClobber", true);
+                    if (!importModuleOptions.NoClobberExportPSSession)
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:1065]: Just FYI, the PSCommand API is designed to support the builder pattern so you can save some boilerplate here:

```csharp
    powerShell.AddCommand("Export-PSSession")
        .AddParameter("OutputModule", wildcardEscapedPath)
        .AddParameter("Module", remoteModuleName)
        .AddParameter("FormatTypeName", "*")
        .AddParameter("Force");

    if (!importModuleOptions.NoClobberExportPSSession)
    {
        powerShell.AddParameter("AllowClobber");
    }
```

(Also `AddParameter()` with a single argument adds a switch parameter)

File: src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs (hunk 11 above)
Comment (rjmholt) [reply src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs:107]: The other thing is that this is a boolean field with `No` in the name, but only gets used in the negated form. That makes sense for a publicly exposed switch parameter, but I think for an internal field/property it's more confusing that simply calling it `ClobberExportPSSession`

**Review by rjmholt — CHANGES_REQUESTED** [review]
Generally looks good, but I think there are some cases with module specifications that need dealing with. Also left some style comments

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs (hunk 5 above)
Comment (rjmholt) [reply src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:1980]: Reading the variable name, I see `coreModuleToLoad` and think this is an object, and then see `IsEngineModule` and the [garden path](https://en.wikipedia.org/wiki/Garden-path_sentence) turns to boolean. Starting the variable name with `is` primes me for a boolean

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs [hunk 16]
```diff
@@ -820,6 +841,23 @@ private PSModuleInfo ImportModule_LocallyViaName(ImportModuleOptions importModul
...
 
+        private PSModuleInfo ImportModule_LocallyViaFQName(ImportModuleOptions importModuleOptions, ModuleSpecification modulespec)
+        {
+            RequiredVersion = modulespec.RequiredVersion;
+            MinimumVersion = modulespec.Version;
+            MaximumVersion = modulespec.MaximumVersion;
+            BaseGuid = modulespec.Guid;
+
+            PSModuleInfo foundModule = ImportModule_LocallyViaName(importModuleOptions, modulespec.Name);
+            ApplicationInsightsTelemetry.SendTelemetryMetric(TelemetryType.ModuleLoad, foundModule.Name);
```
Comment (SteveL-MSFT) [inline src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:852]: Couldn't foundModule be null here?

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs (hunk 1 above)
Comment (anmenaga) [reply src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:594]: It's hard to tell from the diff, but this is actually a cut-and-paste from existing code. I had to resuse it, so moved it out to this separate function. Didn't come up with anything better than `_Wrapper`.  Though `_WithTelemetry` is probably better; updated.

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs (hunk 2 above)
Comment (anmenaga) [reply src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:1911]: I found out that we're handling all these cases (1: possible full or relative paths 2: module names with dots in them) in `ModuleIntrinsics.GetModuleName` function, so updated code to using it instead.

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs (hunk 3 above)
Comment (anmenaga) [reply src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:1967]: renamed and moved lower.

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs (hunk 4 above)
Comment (anmenaga) [reply src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:1970]: Updated to use `ModuleIntrinsics.GetModuleName` and use it for `moduleSpec.Name` as well.

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs (hunk 5 above)
Comment (anmenaga) [reply src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:1980]: renamed.

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs (hunk 6 above)
Comment (anmenaga) [reply src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:1987]: updated.

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs (hunk 7 above)
Comment (anmenaga) [reply src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:2007]: updated.

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs (hunk 8 above)
Comment (anmenaga) [reply src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:2045]: updated.

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs (hunk 9 above)
Comment (anmenaga) [reply src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:2047]: I agree, but this syntax historically was used in `ipmo` code, so I'll leave it for now.

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs (hunk 10 above)
Comment (anmenaga) [reply src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:1965]: Well... it **conditionally** *imports* a core version of the module **as preparation** for *WinCompat import* of the WinPS module. :)
I don't know what is the best name for this...

File: src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs (hunk 11 above)
Comment (anmenaga) [reply src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs:107]: that would  force changing the default, and add another term for the same concept.
`NoClobber` is the most famous one, that's why I went with it.

File: test/powershell/Modules/Microsoft.PowerShell.Core/CompatiblePSEditions.Module.Tests.ps1 (hunk 12 above)
Comment (anmenaga) [reply test/powershell/Modules/Microsoft.PowerShell.Core/CompatiblePSEditions.Module.Tests.ps1:576]: Updated in all cases.

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs (hunk 15 above)
Comment (anmenaga) [reply src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:1065]: good to know.

File: src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs (hunk 16 above)
Comment (anmenaga) [reply src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:852]: Moved it into the following `if (foundModule != null)`.

File: test/powershell/Modules/Microsoft.PowerShell.Core/CompatiblePSEditions.Module.Tests.ps1 (hunk 14 above)
Comment (anmenaga) [reply test/powershell/Modules/Microsoft.PowerShell.Core/CompatiblePSEditions.Module.Tests.ps1:587]: Added test for ModuleSpecifications.

**Comment by anmenaga** [comment]
@PoshChan please retry windows

**Comment by PoshChan** [comment]
@anmenaga, successfully started retry of `PowerShell-CI-Windows`

**Review by rjmholt — APPROVED** [review]

**Review by SteveL-MSFT — APPROVED** [review]

File: src/System.Management.Automation/engine/PSConfiguration.cs [hunk 17]
```diff
@@ -240,6 +241,18 @@ internal string[] GetWindowsPowerShellCompatibilityModuleDenyList()
             return settingValue;
         }
 
+        internal List<string> GetWindowsPowerShellCompatibilityNoClobberModuleList()
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/PSConfiguration.cs:244]: Can you make this method returns `string[]` like `GetWindowsPowerShellCompatibilityModuleDenyList`? It looks inconsistent to return different type when the methods roughly have the same functionalities.

**Review by daxian-dbw — APPROVED** [review]

File: src/System.Management.Automation/engine/PSConfiguration.cs (hunk 17 above)
Comment (anmenaga) [reply src/System.Management.Automation/engine/PSConfiguration.cs]: Updated to string array.
