### PR TITLE
Fix bytewise operators to work on enum types with 'System.Byte' as the underlying type

### LINKED ISSUE #2310: Binary operations on Byte enums throw exceptions in PS 5+
Steps to reproduce
------------------
```
[System.Security.AccessControl.AceFlags]::ObjectInherit -bor [System.Security.AccessControl.AceFlags]::ContainerInherit
```

Expected behavior
-----------------
`3`

Actual behavior
---------------
On v5 i get
```
Specified cast is not valid.
At line:1 char:1
+ [System.Security.AccessControl.AceFlags]::ObjectInherit -bor [System. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], InvalidCastException
    + FullyQualifiedErrorId : System.InvalidCastException
```

on v6 alpha 10 I'm getting
```
Unable to cast object of type 'System.Int32' to type 'System.Security.AccessControl.AceFlags'.
At line:1 char:1
+ [System.Security.AccessControl.AceFlags]::ObjectInherit -bor [System. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], InvalidCastException
    + FullyQualifiedErrorId : System.InvalidCastException
```

Environment data
----------------
This works on my v4/Server 2012 R2, but not anywhere I've installed v5 or v6.

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.34209
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### PR DESCRIPTION
**Pull request by daxian-dbw**
Fix #2310

This is because we were casting the result expression to an object before casting it to the enum type.
If the target enum type has `System.Int32` as underlying type, then the cast of `(int-enum)(object)(int)` works in C#.
But if the target enum type has `System.Byte` as underlying type, then the cast of `(byte-enum)(object)(int)` fails in C# with error "Specified cast is not valid" in FullCLR, and "Unable to cast object of type 'System.Int32' to type" in CoreCLR.

The fix is to cast the expression to the enum type before casting it to object.

### CODE REVIEW

File: src/System.Management.Automation/engine/runtime/Binding/Binders.cs [hunk 1]
```diff
@@ -2940,13 +2940,15 @@ private DynamicMetaObject BinaryBitwiseAnd(DynamicMetaObject target, DynamicMeta
...
+                    var expr = exprGenerator(numericTarget.Expression.Cast(numericTarget.LimitType).Cast(opType),
+                                             numericArg.Expression.Cast(numericArg.LimitType).Cast(opType));
 
                     if (target.LimitType.GetTypeInfo().IsEnum)
                     {
-                        expr = expr.Cast(target.LimitType).Cast(typeof(object));
+                        expr = expr.Cast(target.LimitType);
                     }
+
+                    expr = expr.Cast(typeof(object));
```
Comment (lzybkr) [inline src/System.Management.Automation/engine/runtime/Binding/Binders.cs]: Why was this cast moved outside of the IsEnum code? None of the tests you wrote demonstrate the need here.

Comment (daxian-dbw) [inline src/System.Management.Automation/engine/runtime/Binding/Binders.cs]: `.Cast(typeof(object))` is removed from `var expr = exprGenerator(...)`. In case the target is not a enum, the `if (target.LimitType.GetTypeInfo().IsEnum)` block will not run, but we still want the final expression to be converted to `System.Object`. That's why I removed the cast outside the IsEnum block.

Comment (lzybkr) [inline src/System.Management.Automation/engine/runtime/Binding/Binders.cs]: Ah, thanks.

Comment (lzybkr) [inline src/System.Management.Automation/engine/runtime/Binding/Binders.cs]: Ah, thanks.

**Review by lzybkr — APPROVED** [review]
