### PR TITLE
Invariable order of $PSVersionTable

### LINKED ISSUE #3031: Order of PSVersionTable keeps changing
I'm okay being told that this isn't important, but it does feel a little annoying for anyone trying to build muscle memory on where to glance when checking for the `PSVersion`, `GitCommitId`, or `PSEdition`. 

Steps to reproduce
------------------
Call $PSVersionTable from any version of PowerShell Core 6.0

Expected behavior
-----------------
The ordering of the output should remain the same between versions. 

Actual behavior
---------------
The ordering of the output has changed for every alpha:

image

### PR DESCRIPTION
**Pull request by iSazonov**
Fix #3031.
Provides output $PSVersionTable properties in alphabetical order.

### CODE REVIEW

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 1]
```diff
@@ -5,6 +5,8 @@
 using System.Diagnostics;
 using System.Reflection;
 using System.Collections;
+using System.Collections.Generic;
+using System.Linq;
```
Comment (SteveL-MSFT) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: Why did you add this?

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]

**Comment by SteveL-MSFT** [comment]
Please add a test

File: src/System.Management.Automation/engine/PSVersionInfo.cs (hunk 1 above)
Comment (iSazonov) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: I've been playing with different options.
Removed.

**Comment by iSazonov** [comment]
@SteveL-MSFT I added tests.

**Review by SteveL-MSFT — APPROVED** [review]

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 2]
```diff
@@ -316,6 +316,43 @@ internal static SemanticVersion PSV6Version
     }
 
     /// <summary>
+    /// Represents an implementation of '$PSVersionTable' variable.
+    /// The implementation contains ordered 'Keys' and 'GetEnumerator' to get user-friendly output.
+    /// </summary>
+    public sealed class PSVersionHashTable : Hashtable, IEnumerable
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: > public class Hashtable : IDictionary, ICollection, IEnumerable, ...

Hashtable implements IEnumerable, so do you still need to specify `IEnumerable` here?

Comment (iSazonov) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: VS Code detects this as error and build failed too without explicity adding `IEnumerable`.

File: src/System.Management.Automation/engine/PSVersionInfo.cs [hunk 3]
```diff
@@ -316,6 +316,43 @@ internal static SemanticVersion PSV6Version
...
+        /// <summary>
+        /// Returns ordered collection with Keys of 'PSVersionHashTable'
+        /// </summary>
+        public override ICollection Keys
+        {
+            get
+            {
+                Array arr = new string[base.Keys.Count];
+                base.Keys.CopyTo(arr, 0);
+                Array.Sort(arr, StringComparer.OrdinalIgnoreCase);
```
Comment (lzybkr) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: I'm not sure I like this sorting - today `PSVersion` shows up first, or at least it should.
With this change, it will be somewhat harder to see

Comment (rkeithhill) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: Agree 100%.  About the **only** thing I ever look for from this info is `PSVersion`.  This will make it harder to see that version.

Comment (daxian-dbw) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: Maybe an `OrderedDictionary` should be used here.

Comment (iSazonov) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: We have several open discussions on adding additional rows. Alphabetical order will be even more useful after that.

If you want only PSVersion why don't use `$PSVersionTable.PSVersion`?

I wonder how it makes Windows PowerShell for `PSVersionHashTable` _hashtable_ ?

I could slightly change this code to move PSVersion in the first place without moving to `OrderedDictionary`

Comment (daxian-dbw) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: > Update: Moving to OrderedDictionary may be not easy. I review the code - GetPSVersionTableForDownLevel is used in serialization.cs and it is based on hashtable. So I didn't even imagine that there can be broken.

This is a good point. Thanks @iSazonov

Comment (rkeithhill) [inline src/System.Management.Automation/engine/PSVersionInfo.cs]: Consider putting PSVersion **and** PSEdition in the first and second positions.  After that, I don't care much about the order. I suppose alphabetical after the first two would be fine.
