### PR TITLE
Make ResourceManagerCache check for alternative resource paths

### LINKED ISSUE #3057: Errors occurred while loading the format data file
Steps to reproduce
------------------
Attempt to Import [PowerShellHumanizer](https://www.powershellgallery.com/packages/PowerShellHumanizer/3.1) module v3.1.

Expected behavior
-----------------
PowerShell loads the custom type data files.

Actual behavior
---------------
Errors about `CustomEntries` and `CustonItem` Xml nodes. An error about `resource FileSystemProviderStrings` missing from `System.Management.Automation`
```
ipmo : Errors occurred while loading the format data file:
C:\powershell6\Modules\PowerShellHumanizer\3.1\FileInfo.format.ps1xml, Error at XPath
/Configuration/Controls/Control[1]/CustomControl/CustomEntries in file
C:\powershell6\Modules\PowerShellHumanizer\3.1\FileInfo.format.ps1xml: CustomEntry failed to load.
C:\powershell6\Modules\PowerShellHumanizer\3.1\FileInfo.format.ps1xml, Error at XPath
/Configuration/Controls/Control[1]/CustomControl/CustomEntries/CustomEntry[1] in file
C:\powershell6\Modules\PowerShellHumanizer\3.1\FileInfo.format.ps1xml: Node CustomItem is missing.
C:\powershell6\Modules\PowerShellHumanizer\3.1\FileInfo.format.ps1xml, Error at XPath
/Configuration/Controls/Control[1]/CustomControl/CustomEntries/CustomEntry[1]/CustomItem in file
C:\powershell6\Modules\PowerShellHumanizer\3.1\FileInfo.format.ps1xml: Frame failed to load.
C:\powershell6\Modules\PowerShellHumanizer\3.1\FileInfo.format.ps1xml, Error at XPath
/Configuration/Controls/Control[1]/CustomControl/CustomEntries/CustomEntry[1]/CustomItem/Frame[1] in file
C:\powershell6\Modules\PowerShellHumanizer\3.1\FileInfo.format.ps1xml: Node CustomItem is missing.
C:\powershell6\Modules\PowerShellHumanizer\3.1\FileInfo.format.ps1xml, Error at XPath
/Configuration/Controls/Control[1]/CustomControl/CustomEntries/CustomEntry[1]/CustomItem/Frame[1]/CustomItem in file
C:\powershell6\Modules\PowerShellHumanizer\3.1\FileInfo.format.ps1xml: Text failed to load.
C:\powershell6\Modules\PowerShellHumanizer\3.1\FileInfo.format.ps1xml, Error at XPath
/Configuration/Controls/Control[1]/CustomControl/CustomEntries/CustomEntry[1]/CustomItem/Frame[1]/CustomItem/Text[1]
in file C:\powershell6\Modules\PowerShellHumanizer\3.1\FileInfo.format.ps1xml: The resource FileSystemProviderStrings
in assembly C:\System.Management.Automation is not found.
```

Environment data
----------------

```powershell

Name                           Value                                                                                   
----                           -----                                                                                   
BuildVersion                   3.0.0.0                                                                                 
GitCommitId                    v6.0.0-alpha.15                                                                         
SerializationVersion           1.1.0.1                                                                                 
CLRVersion                                                                                                             
WSManStackVersion              3.0                                                                                     
PSVersion                      6.0.0-alpha                                                                             
PSRemotingProtocolVersion      2.3                                                                                     
PSEdition                      Core                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
```

### PR DESCRIPTION
**Pull request by anmenaga**
This PR is for 2 things:
1) From WindowsPS to PSCore resource paths have changed like this example:
WindowsPS: `FileSystemProviderStrings`
PSCore: `System.Management.Automation.resources.FileSystemProviderStrings`
... and some existing modules use 'WindowsPS' syntax in their "format.ps1xml" files; for example:
`<Text AssemblyName="System.Management.Automation" BaseName="FileSystemProviderStrings" ResourceId="DirectoryDisplayGrouping"/>`
So in these cases resource is not found and Import-Module/Update-FormatData returns error on PSCore.
The fix is to check for alternative resource path if original fails.

2) when a resource is not found, currently error message has wrong assembly path which was tried for loading the resource; for example:
`... resource NonExistingResource in assembly C:\System.Management.Automation is not found.`
This is rather confusing, specifically because assembly, containing the resource, can be located anywhere in the filesystem. The fix makes error message accurate: `... resource NonExistingResource in assembly C:\GitHub\PowerShell\src\powershell-win-core\bin\Debug\netcoreapp2.0\win10-x64\publish\System.Management.Automation.dll is not found.`

Results on PSCore after the fix:
afterfix

Results on PSCore before the fix:
beforefix

Fix #3057

### CODE REVIEW

File: src/System.Management.Automation/utils/ResourceManagerCache.cs [hunk 1]
```diff
@@ -177,8 +177,37 @@ internal static bool DFT_DoMonitorFailingResourceLookup
...
+                const string resourcesSubstring = ".resources.";
+                int resourcesSubstringIndex = baseName.IndexOf(resourcesSubstring);
+                string newBaseName = string.Empty;
+                if (resourcesSubstringIndex != -1)
+                {
+                    newBaseName = baseName.Substring(resourcesSubstringIndex + resourcesSubstring.Length); // e.g.  "FileSystemProviderStrings"
+                }
+                else
+                {
+                    newBaseName = assembly.GetName().Name + resourcesSubstring + baseName; // e.g. "System.Management.Automation.resources.FileSystemProviderStrings"
```
Comment (adityapatwardhan) [inline src/System.Management.Automation/utils/ResourceManagerCache.cs]: Do not concatenate strings, use a StringBuilder.

File: test/powershell/Modules/Microsoft.PowerShell.Utility/FileInfo.format.ps1xml [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+                            <TableColumnItem>
+                                <PropertyName>Name</PropertyName>
+                            </TableColumnItem>
+                        </TableColumnItems>
+                    </TableRowEntry>
+                </TableRowEntries>
+            </TableControl>
+        </View>
+    </ViewDefinitions>
+</Configuration>
```
Comment (adityapatwardhan) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/FileInfo.format.ps1xml]: Missing newline

File: test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1 [hunk 3]
```diff
@@ -57,3 +57,50 @@ Describe "Update-FormatData basic functionality" -Tags "CI" {
...
+	    }
+		It "Verify assembly path in error message when resource is Not found" {
+			$format = Get-Content -Path $templatePath -Raw
+			$format.Replace("%BaseName%","NonExistingResource") | Set-Content -Path $formatFilePath -Force
+			$null = $ps.AddScript("Update-FormatData -PrependPath $formatFilePath")
+			$ps.Streams.Error.Clear()
+            $ps.Invoke()
+			$sma = [appdomain]::CurrentDomain.GetAssemblies() | ? { if ($_.Location) {$_.Location.EndsWith("System.Management.Automation.dll")}}
+			$smaLocation = $sma.Location
+			$ps.Streams.Error | %{ $_.Exception.Message.Contains($smaLocation) | Should be $true }
```
Comment (adityapatwardhan) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1]: Can you do:
```Powershell
$_.Exception.Message | Should Match $smaLocation
```

File: test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1 [hunk 4]
```diff
@@ -57,3 +57,50 @@ Describe "Update-FormatData basic functionality" -Tags "CI" {
...
+	    }
+    }
+}
```
Comment (adityapatwardhan) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1]: Missing newline

Comment (adityapatwardhan) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1]: Can we add a test where we lookup are string resource which does not exist and expect an MissingManifestResourceException

**Review by adityapatwardhan — DISMISSED** [review]

File: src/System.Management.Automation/utils/ResourceManagerCache.cs (hunk 1 above)
Comment (lzybkr) [inline src/System.Management.Automation/utils/ResourceManagerCache.cs]: A single call to `string.Concat` with 4 or fewer arguments could be better than using a `StringBuilder` - the length of the string can be pre-calculated, so there would only be 1 allocation instead of multiple for the `StringBuilder`, the array of characters in `StringBuilder`, and the final string allocation.

File: test/powershell/Modules/Microsoft.PowerShell.Utility/FileInfo.format.ps1xml (hunk 2 above)
Comment (lzybkr) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/FileInfo.format.ps1xml]: I think the test should not look anything like something that is built-in - otherwise it might cause problems with other tests.

File: src/System.Management.Automation/utils/ResourceManagerCache.cs (hunk 1 above)
Comment (anmenaga) [inline src/System.Management.Automation/utils/ResourceManagerCache.cs]: Updated to string.Concat

File: test/powershell/Modules/Microsoft.PowerShell.Utility/FileInfo.format.ps1xml (hunk 2 above)
Comment (anmenaga) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/FileInfo.format.ps1xml]: added newline;
renamed the format file to indicate relation to tests;
these tests are run in separate PowerShell/Runspace instances, so there should be no conflict with other tests.

File: test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1 (hunk 3 above)
Comment (anmenaga) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1]: this fails with
`parsing 'C:\Users\GitHub\PowerShell\New\src\powershell-win-core\bin\Debug\netcoreapp2.0\win10-x64\publish\System.Management.Automation.dll' - Unrecognized escape sequence \\U.`

File: test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1 (hunk 4 above)
Comment (anmenaga) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1]: updated

Comment (anmenaga) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1]: this last test is for when resource is not found;
I've added check for FullyQualifiedErrorId

File: test/powershell/Modules/Microsoft.PowerShell.Utility/FileInfo.format.ps1xml (hunk 2 above)
Comment (lzybkr) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/FileInfo.format.ps1xml]: Today there is no conflict.

You should write the test so there can never be a conflict, even if the code is reused.

It's really simple to use a type name specific to this scenario, so I see no reason to not do as I've suggested.

File: test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1 [hunk 5]
```diff
@@ -57,3 +57,50 @@ Describe "Update-FormatData basic functionality" -Tags "CI" {
         { Update-FormatData -Prepend $testfile -WhatIf } | Should Not Throw
 	}
 }
+
+
+Describe "Update-FormatData with resources in CustomControls" -Tags "CI" {
+
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1]: The file has multiple wrong indentations. See raw view https://raw.githubusercontent.com/anmenaga/PowerShell/fd95dd19b90e7cb5d0094f52503b59c59ec1ca5b/test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1
It seems you copy-paste tabs.
Could you please reformat by first commit and put new code in next commits?

File: test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1 (hunk 3 above)
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1]: Maybe `MatchExactly` ?

Comment (anmenaga) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1]: MatchExactly fails as well.

File: src/System.Management.Automation/utils/ResourceManagerCache.cs [hunk 6]
```diff
@@ -177,8 +177,37 @@ internal static bool DFT_DoMonitorFailingResourceLookup
...
             }
 
-            ResourceManager resourceManager = GetResourceManager(assembly, baseName);
-            string text = resourceManager.GetString(resourceId);
+            ResourceManager resourceManager = null;
+            string text = string.Empty;
+
+            // FYI: for a non-existing resource defined by {assembly,baseName,resourceId}
+            // MissingManifestResourceException is thrown only at the time when resource retrieval method such as ResourceManager.GetString or ResourceManager.GetObject is called,
+            // Not when you instantiate a ResourceManager object.
```
Comment (anmenaga) [inline src/System.Management.Automation/utils/ResourceManagerCache.cs]: Updated.

File: src/System.Management.Automation/utils/ResourceManagerCache.cs [hunk 7]
```diff
@@ -177,8 +177,37 @@ internal static bool DFT_DoMonitorFailingResourceLookup
...
+            try
+            {
+                // try with original baseName
```
Comment (anmenaga) [inline src/System.Management.Automation/utils/ResourceManagerCache.cs]: Updated.

File: test/powershell/Modules/Microsoft.PowerShell.Utility/FileInfo.format.ps1xml [hunk 8]
```diff
@@ -0,0 +1,88 @@
+<Configuration>
+    <SelectionSets>
```
Comment (anmenaga) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/FileInfo.format.ps1xml]: moved it.

File: test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1 (hunk 5 above)
Comment (anmenaga) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1]: fixed indentations.

File: src/System.Management.Automation/utils/ResourceManagerCache.cs (hunk 6 above)
Comment (iSazonov) [inline src/System.Management.Automation/utils/ResourceManagerCache.cs]: Closed.

File: src/System.Management.Automation/utils/ResourceManagerCache.cs (hunk 7 above)
Comment (iSazonov) [inline src/System.Management.Automation/utils/ResourceManagerCache.cs]: Closed.

File: test/powershell/Modules/Microsoft.PowerShell.Utility/FileInfo.format.ps1xml (hunk 8 above)
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/FileInfo.format.ps1xml]: Closed.

File: test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1 (hunk 5 above)
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1]: Closed.

Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1]: Closed.

**Comment by TravisEz13** [comment]
@adityapatwardhan  Can you update your review?

File: test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1 [hunk 9]
```diff
@@ -48,12 +48,60 @@ Describe "Update-FormatData basic functionality" -Tags "CI" {
...
+        $ps.Dispose()
+    }
+    Context "Validate Update-FormatData" {
+        It "Resources in WindowsPS syntax should be loaded successfully" {
+            $format = Get-Content -Path $templatePath -Raw
+            $format.Replace("%BaseName%","FileSystemProviderStrings") | Set-Content -Path $formatFilePath -Force
+            $null = $ps.AddScript("Update-FormatData -PrependPath $formatFilePath")
+            $ps.Streams.Error.Clear()
+            $ps.Invoke()
+            $ps.HadErrors | Should be $false
```
Comment (TravisEz13) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1]: Would testing `$ps.Streams.Error` give a more meaningful error if something went wrong in the test?

File: test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1 [hunk 10]
```diff
@@ -48,12 +48,60 @@ Describe "Update-FormatData basic functionality" -Tags "CI" {
...
+
+        }
+        It "Resources in CorePS syntax should be loaded successfully" {
+            $format = Get-Content -Path $templatePath -Raw
+            $format.Replace("%BaseName%","System.Management.Automation.resources.FileSystemProviderStrings") | Set-Content -Path $formatFilePath -Force
+            $null = $ps.AddScript("Update-FormatData -PrependPath $formatFilePath")
+            $ps.Streams.Error.Clear()
+            $ps.Invoke()
+            $ps.HadErrors | Should be $false
```
Comment (TravisEz13) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1]: See previous

**Review by TravisEz13 — COMMENTED** [review]
No blocking issues

File: test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1 (hunk 9 above)
Comment (anmenaga) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1]: good idea;   updated.

File: test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1 (hunk 10 above)
Comment (anmenaga) [inline test/powershell/Modules/Microsoft.PowerShell.Utility/Update-FormatData.Tests.ps1]: updated.

**Review by TravisEz13 — APPROVED** [review]

**Review by adityapatwardhan — APPROVED** [review]
LGTM
