### PR TITLE
Fix parameter name in the Get-Variable cmdlet error message.

### LINKED ISSUE #7383: Wrong parameter name in the Get-Variable cmdlet error message.
When using `Get-Variable` (or `Get-Alias`) cmdlet with the **-Scope** parameter with wrong value, the error message refers to **scopeID** parameter.
Even though it is the real parameter of the `GetScopeByID` and  `GetScopeByID` internal methods, the error message returns to the user, who used the **-Scope** parameter.

So it would be nice, if the error messages refer to the **-Scope** parameter.

Steps to reproduce
------------------

```powershell
Get-Variable -Scope 100
Get-Variable -Scope SomeWrongScopeName
```

Expected behavior
-----------------

```none
Get-Variable : The scope number '100' exceeds the number of active scopes.
Parameter name: Scope
Actual value was 100.
At line:1 char:1
+ Get-Variable -Scope 100
+ ~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Get-Variable], PSArgumentOutOfRangeException
+ FullyQualifiedErrorId : ArgumentOutOfRange,Microsoft.PowerShell.Commands.GetVariableCommand


Get-Variable : Cannot process argument because the value of parameter "Scope" is not valid.
Valid values are "Global", "Local", or "Script", or a number relative to the current scope 
(0 through the number of scopes where 0 is the current scope and 1 is its parent). 
Change the value of the "Scope" parameter and run the operation again.
At line:1 char:1
+ Get-Variable -Scope SomeWrongScopeName
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Get-Variable], PSArgumentException
+ FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.GetVariableCommand
```

Actual behavior
---------------

```none
Get-Variable : The scope number '100' exceeds the number of active scopes.
Parameter name: scopeID
Actual value was 100.
At line:1 char:1
+ Get-Variable -Scope 100
+ ~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Get-Variable], PSArgumentOutOfRangeException
+ FullyQualifiedErrorId : ArgumentOutOfRange,Microsoft.PowerShell.Commands.GetVariableCommand


Get-Variable : Cannot process argument because the value of argument "scopeID" is not valid.
Valid values are "Global", "Local", or "Script", or a number relative to the current scope 
(0 through the number of scopes where 0 is the current scope and 1 is its parent). 
Change the value of the "scopeID" argument and run the operation again.
At line:1 char:1
+ Get-Variable -Scope SomeWrongScopeName
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Get-Variable], PSArgumentException
+ FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.GetVariableCommand
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by sethvs**
## PR Summary

When using `Get-Variable` (or `Get-Alias`) cmdlet with the **-Scope** parameter with wrong value, the error message refers to **scopeID** parameter.
Even though it is the real parameter of the `GetScopeByID` and  `GetScopeByID` internal methods, the error message returns to the user, who used the **-Scope** parameter.

Fix #7383 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

File: src/System.Management.Automation/engine/SessionStateScopeAPIs.cs [hunk 1]
```diff
@@ -92,18 +92,18 @@ internal SessionStateScope GetScopeByID(string scopeID)
 
                         if (scopeNumericID < 0)
                         {
-                            throw PSTraceSource.NewArgumentOutOfRangeException("scopeID", scopeID);
+                            throw PSTraceSource.NewArgumentOutOfRangeException("Scope", scopeID);
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/SessionStateScopeAPIs.cs]: We could use "readonly const".

**Review by iSazonov — APPROVED** [review]

**Review by anmenaga — APPROVED** [review]

**Comment by iSazonov** [comment]
@sethvs Thanks for the fix!
