### PR TITLE
Fix code errors found by PVS-Studio

### LINKED ISSUE #2587: Analysis of 'PowerShell' source code by PVS-Studio static code analyzer
Developers of PVS-Studio C/C++/C# static analyzer present their check report of the source code of 'PowerShell' in the article, containing the review of the most suspicious code fragments they discovered.

You can read article at the official site:
http://www.viva64.com/en/b/0447/

I have provided links to GitHub for each code fragment to make viewing more comfortable. Nevertheless, a lot of fragments, detected by the analyzer weren't given in the article. That's why I would suggest trying out the analyzer and viewing other warnings besides fixing the given code fragments.

### PR DESCRIPTION
**Pull request by vors**
Fix #2587

Thank you @VasilievSerg!

### CODE REVIEW

**Review by lzybkr — APPROVED** [review]

File: src/System.Management.Automation/utils/PowerShellETWTracer.cs [hunk 1]
```diff
@@ -1085,7 +1085,7 @@ public bool TraceJob(Job job)
             {
                 return DebugChannel.TraceDebug(PowerShellTraceEvent.Job,
                                                PowerShellTraceOperationCode.Method, PowerShellTraceTask.None,
-                                               job.Id.ToString(CultureInfo.InvariantCulture), job.InstanceId.ToString(), "NULL job");
+                                               "", "", "NULL job");
```
Comment (JamesWTruher) [inline src/System.Management.Automation/utils/PowerShellETWTracer.cs]: >"", [](start = 47, length = 3)

should these be `String.Empty`, since we're using that elsewhere in this file

Comment (lzybkr) [inline src/System.Management.Automation/utils/PowerShellETWTracer.cs]: I have a slight preference for `""` over `String.Empty`.  A constant should generate less IL, though the net result might not matter as the JIT has special knowledge of `String.Empty`.

Comment (JamesWTruher) [inline src/System.Management.Automation/utils/PowerShellETWTracer.cs]: the only reason i mention it is because of the use of String.Empty and this is consistent with that use
