### PR TITLE
Fix for #2442 - automounted drives in modules

### LINKED ISSUE #2442: When a volume is mounted after a module is loaded, that volume is not visible from the module code
## Steps to reproduce

```
param($VHDPath = "${env:TEMP}\test.vhd")

function CreateVHD ($VHDPath, $Size)
{
  $drive = (New-VHD -path $vhdpath -SizeBytes $size -Dynamic   | `
              Mount-VHD -Passthru |  `
              get-disk -number {$_.DiskNumber} | `
              Initialize-Disk -PartitionStyle MBR -PassThru | `
              New-Partition -UseMaximumSize -AssignDriveLetter:$False -MbrType IFS | `
              Format-Volume -Confirm:$false -FileSystem NTFS -force | `
              get-partition | `
              Add-PartitionAccessPath -AssignDriveLetter -PassThru | `
              get-volume).DriveLetter

    $drive
}

$m = New-Module {
    function Test-DrivePresence
    {
        param ([String]$Path)

        Write-Output "Testing path: $Path"
        if (Test-Path $Path)
        {
            Write-Output "Exists"
        }
        else 
        {
            Write-Output "Does not exist"
        }

        Write-Output "Running Get-PSDrive"
        Get-PSDrive | Out-Host

        Write-Output "Testing path: $Path"
        if (Test-Path $Path)
        {
            Write-Output "Exists"
        }
        else 
        {
            Write-Output "Does not exist"
        }
    }

    Export-ModuleMember -Function Test-DrivePresence
}

Write-Output "Precondition: start from fresh PS session, do not have the media mounted"
try
{
    ipmo $m
    $drive = CreateVHD -VHDPath $VHDPath -Size 25mb
    Test-DrivePresence -Path "${drive}:"
}
finally
{
    Remove-Module $m
    Dismount-VHD $VHDPath
    del $VHDPath
}
```

Thanks goes to @lzybkr for making this repro script.
## Expected behavior

1) Load a module
2) Mount a VHD
3) VHD should be visible from the context of the module, without needing to run Get-PSDrive (e.g. when doing parameter validation using ValidateScript)
## Actual behavior

1) Load a module
2) Mount a VHD
3) The mounted volume is not visible, until Get-PSDrive is invoked. This is very non-intuitive.
## Environment data

```
PS D:\temp\aaa.ps1> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.14393.187
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.187
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### PR DESCRIPTION
**Pull request by anmenaga**
This fixes #2442
Added tests using: 1) 'subst.exe' utility 2) New-VHD/Mount-VHD cmdlets .
Also added tests that verify automounted drives without modules in the picture to use as baseline.

Test results on Hyper-V machine after fix:
afterfix_onhypervmachine
Test results on Non-Hyper-V machine after fix:
afterfix_onsimplevm

For reference - test results on Hyper-V machine before fix:
beforefix_onhypervmachine
For reference - test results on Non-Hyper-V machine before fix:
beforefix_onsimplevm

### CODE REVIEW

File: src/System.Management.Automation/engine/SessionStateDriveAPIs.cs [hunk 1]
```diff
@@ -508,12 +508,13 @@ private PSDriveInfo GetDrive(string name, bool automount)
...
             if (result == null && automount)
             {
-                result = AutomountBuiltInDrive(name);
-            }
-
-            if (result == null && this == ExecutionContext.TopLevelSessionState)
-            {
-                result = AutomountFileSystemDrive(name);
+                // first try to automount as a file system drive
+                result = AutomountFileSystemDrive(name);
```
Comment (lzybkr) [inline src/System.Management.Automation/engine/SessionStateDriveAPIs.cs]: The old code only created file system drives if the current scope was global.
Will your change create the drive in global scope or module scope?
Personally, I would expect the drive to be in global scope.
I would also like to see tests to cover that scenario either way.

File: test/powershell/Provider/AutomountSubstDrive.ps1 [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+        & $global:CoreScriptPath -Path $FullPath
+    }
+}
+finally
+{
+    if ($useModule)
+    {
+        Remove-Module $m
+    }
+}
```
Comment (lzybkr) [inline test/powershell/Provider/AutomountSubstDrive.ps1]: Files should end with a newline.

File: test/powershell/Provider/AutomountVHDDrive.ps1 [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+}
+finally
+{
+    if ($useModule)
+    {
+        Remove-Module $m
+    }
+    Dismount-VHD $VHDPath
+    Remove-Item $VHDPath
+}
```
Comment (lzybkr) [inline test/powershell/Provider/AutomountVHDDrive.ps1]: Files should end with a newline.

File: test/powershell/Provider/Pester.AutomountedDrives.Tests.ps1 [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+        It "Test automounting using subst.exe" -Skip:$SubstNotFound {
+           & $powershell -noprofile -command "$AutomountSubstDriveScriptPath -useModule -FullPath $substDir" | Should Be "Drive found"
+        }
+        
+        It "Test automounting using New-VHD/Mount-VHD" -Skip:$VHDToolsNotFound {
+            $vhdPath = Join-Path $TestDrive 'TestAutomountVHD.vhd'
+            & $powershell -noprofile -command "$AutomountVHDDriveScriptPath -useModule -VHDPath $vhdPath" | Should Be "Drive found"
+        }
+    }
+}
```
Comment (lzybkr) [inline test/powershell/Provider/Pester.AutomountedDrives.Tests.ps1]: Files should end with a newline.

File: test/powershell/Provider/Pester.AutomountedDrives.Tests.ps1 [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+            Remove-Item $tmpVhdPath
+        }
+        catch
+        { $VHDToolsNotFound = $true }
+    }
+    
+    Context "Validating automounting FileSystem drives" {
+        
+        It "Test automounting using subst.exe" -Skip:$SubstNotFound {
+           & $powershell -noprofile -command "$AutomountSubstDriveScriptPath -FullPath $substDir" | Should Be "Drive found"
```
Comment (lzybkr) [inline test/powershell/Provider/Pester.AutomountedDrives.Tests.ps1]: This could fail in a couple ways if there are spaces in the path, a fix would look something like this:

You can use:
```powershell
& $powershell -noprofile -command "& '$AutomountSubstDriveScriptPath' -FullPath '$substDir'" | Should Be "Drive found"
```

File: src/System.Management.Automation/engine/SessionStateDriveAPIs.cs (hunk 1 above)
Comment (anmenaga) [inline src/System.Management.Automation/engine/SessionStateDriveAPIs.cs]: After this change, new drives will be created in global scope; I've added a check for this to tests.

File: test/powershell/Provider/AutomountSubstDrive.ps1 (hunk 2 above)
Comment (anmenaga) [inline test/powershell/Provider/AutomountSubstDrive.ps1]: Fixed.

File: test/powershell/Provider/AutomountVHDDrive.ps1 (hunk 3 above)
Comment (anmenaga) [inline test/powershell/Provider/AutomountVHDDrive.ps1]: Fixed.

File: test/powershell/Provider/Pester.AutomountedDrives.Tests.ps1 (hunk 5 above)
Comment (anmenaga) [inline test/powershell/Provider/Pester.AutomountedDrives.Tests.ps1]: Updated; Thank you.

File: test/powershell/Provider/Pester.AutomountedDrives.Tests.ps1 (hunk 4 above)
Comment (anmenaga) [inline test/powershell/Provider/Pester.AutomountedDrives.Tests.ps1]: Fixed.
