### PR TITLE
Don't fail if SaferPolicy API is not available on Win10 IoT or NanoServer

### LINKED ISSUE #6750: pwsh.exe does not start on Windows 10 IOT (arm32)
pwsh does not start on Windows 10 IOT arm32 and nanoserver amd64. The issue is with the usage of GetSaferPolicy, which is not supported on Windows IOT. The other issue with setting up remoting endpoint is with usage of 
`[System.Environment+SpecialFolder]` in Install-PowerShellRemoting.ps1 script.

The error shown is:
```
.\pwsh.exe : Cannot load PSReadline module.  Console is running without PSReadline.
    + CategoryInfo          : NotSpecified: (Cannot load PSR...out PSReadline.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

FailFast:
This function is not supported on this system
   at System.Environment.FailFast(System.String, System.Exception)
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
Exception details:
System.ComponentModel.Win32Exception: This function is not supported on this system
   at System.Management.Automation.Internal.SecuritySupport.GetSaferPolicy(String path, SafeHandle handle) in
C:\PowerShell\src\System.Management.Automation\security\SecuritySupport.cs:line 558
   at System.Management.Automation.Security.SystemPolicy.TestSaferPolicy(String testPathScript, String testPathModule)
in C:\PowerShell\src\System.Management.Automation\security\wldpNativeMethods.cs:line 331
   at System.Management.Automation.Security.SystemPolicy.GetAppLockerPolicy(String path, SafeHandle handle) in
C:\PowerShell\src\System.Management.Automation\security\wldpNativeMethods.cs:line 209
   at System.Management.Automation.Security.SystemPolicy.GetLockdownPolicy(String path, SafeHandle handle) in
C:\PowerShell\src\System.Management.Automation\security\wldpNativeMethods.cs:line 94
   at System.Management.Automation.Security.SystemPolicy.GetSystemLockdownPolicy() in
C:\PowerShell\src\System.Management.Automation\security\wldpNativeMethods.cs:line 56
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceInitialization(Boolean skipProfiles, String initialCommand, String
configurationName, Collection`1 initialCommandArgs) in
C:\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleHost.cs:line 1705
   at Microsoft.PowerShell.ConsoleHost.DoCreateRunspace(String initialCommand, Boolean skipProfiles, Boolean staMode,
String configurationName, Collection`1 initialCommandArgs) in
C:\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleHost.cs:line 1652
   at Microsoft.PowerShell.ConsoleHost.CreateRunspace(Object runspaceCreationArgs) in
C:\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleHost.cs:line 1532
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1
initialCommandArgs, Boolean staMode, String configurationName) in
C:\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleHost.cs:line 1453
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned) in
C:\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleHost.cs:line 1402
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, String[] args) in
C:\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleHost.cs:line 270
   at Microsoft.PowerShell.ConsoleShell.Start(String bannerText, String helpText, String[] args) in
C:\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleShell.cs:line 29
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String consoleFilePath, String[] args, Int32 argc) in
C:\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ManagedEntrance.cs:line 64
```

Steps to reproduce
------------------
Install PowerShell 6.1.0-preview.2  and start pwsh.exe

Expected behavior
-----------------
pwsh starts

Actual behavior
---------------
Failure to start

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
## PR Summary

We P/Invoke to the SaferPolicy APIs which are not available on Win10 IoT or NanoServer.
If the Win32 error indicates that the api is not supported, we default to Allowed.

Updated `Install-PowerShellRemoting.ps1` to work correctly on Windows PowerShell Core 5 so that you can install PSCore6 remoting on Win10 IoT.

Fix https://github.com/PowerShell/PowerShell/issues/6750

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by daxian-dbw — APPROVED** [review]

**Review by adityapatwardhan — APPROVED** [review]

File: src/System.Management.Automation/security/SecuritySupport.cs [hunk 1]
```diff
@@ -555,7 +562,15 @@ internal static SaferPolicy GetSaferPolicy(string path, SafeHandle handle)
             }
             else
             {
-                throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());
+                int lastError = Marshal.GetLastWin32Error();
+                if (lastError == NativeConstants.FUNCTION_NOT_SUPPORTED)
+                {
+                    _saferApiSupported = false;
```
Comment (anmenaga) [inline src/System.Management.Automation/security/SecuritySupport.cs]: The var name "_saferApiSupported" is kind of misleading because it is broad in a sense that there are other native API calls (Cert-related) in this file that neither utilize this 'global flag' nor set it in case of similar error handling (Win32Exception(Marshal.GetLastWin32Error())).
So for consistency either this"_saferApiSupported" flag should be added to them; or simply renamed to something more narrow like "_SaferIdentifyLevelApiSupported".

**Review by TravisEz13 — COMMENTED** [review]
other than the issue we discussed offline, looks good to me

**Review by TravisEz13 — APPROVED** [review]

File: src/System.Management.Automation/security/nativeMethods.cs [hunk 2]
```diff
@@ -86,6 +86,9 @@ internal partial class NativeConstants
 
         /// MAX_PATH -> 260
         internal const int MAX_PATH = 260;
+
+        /// This function is not supported on this system
```
Comment (iSazonov) [inline src/System.Management.Automation/security/nativeMethods.cs]: :-) CodeFactor says that we use incorrect documentation header.

File: src/System.Management.Automation/security/SecuritySupport.cs [hunk 3]
```diff
@@ -477,6 +477,8 @@ private static string GetLocalPreferenceValue(string shellId, ExecutionPolicySco
 
 #endregion execution policy
 
+        private static bool _SaferIdentifyLevelApiSupported = true;
```
Comment (iSazonov) [inline src/System.Management.Automation/security/SecuritySupport.cs]: From CodeFactor - Variable names and private field names must start with a lower-case letter.

File: src/System.Management.Automation/security/nativeMethods.cs (hunk 2 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/security/nativeMethods.cs]: I'll fix this file

File: src/System.Management.Automation/security/SecuritySupport.cs (hunk 3 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/security/SecuritySupport.cs]: will change

**Review by PaulHigin — APPROVED** [review]

**Review by iSazonov — APPROVED** [review]
