### PR TITLE
Direct Clear-Host output to terminal

### LINKED ISSUE #10181: PSCore: Linux - Clear-Host injects data into function return value
# Steps to reproduce

```
Function Get-SomeData {
    Clear-Host
    $somedata="somedata"
    return $somedata
}

$myData = Get-SomeData

$myData[0]     # will clear the screen
$myData[1]     # "somedata"
$myData.Count  # will be 2

```

# Expected behavior

```
Function should return a single value ("somedata")
```

# Actual behavior

```
Function returns an array with the Clear-Host command as the first object

```

# Environment data
Verified in:
|Name|Value|
|---|---|
|PSVersion|6.2.0|
|PSEdition|Core|
|GitCommitId|6.2.0|
|OS|Linux 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019|
|Platform|Unix|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.2.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Fix #10181

Clear-Host on Unix calls `clear` command which issues escapes. Before the change we write them to PowerShell output stream and it could be unwantedly intercepted. After the change we write the escapes directly to console as suggested by @mklement0 .

Added test is formal and we need manual check on Linux and MacOs too.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

File: src/System.Management.Automation/engine/InitialSessionState.cs [hunk 1]
```diff
@@ -4078,7 +4078,9 @@ internal static string GetClearHostFunctionText()
             {
                 // Porting note: non-Windows platforms use `clear`
                 return @"
-& (Get-Command -CommandType Application clear | Select-Object -First 1).Definition
+[Console]::Write((
```
Comment (SteveL-MSFT) [inline src/System.Management.Automation/engine/InitialSessionState.cs]: Should we use `Write-Host` here instead?  There may be cases where there isn't a console?

Comment (mklement0) [reply src/System.Management.Automation/engine/InitialSessionState.cs]: @SteveL-MSFT: In principle, `$host.UI.Write()` is better than `[Console]::Write()`, but note that we're calling a _terminal-specific_  utility anyway - see also: https://github.com/PowerShell/PowerShell/issues/10181#issuecomment-537510875

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/InitialSessionState.cs]: @iSazonov can you validate if this works remotely?

Comment (mklement0) [reply src/System.Management.Automation/engine/InitialSessionState.cs]: @SteveL-MSFT: No, it doesn't (see linked comment), but it also didn't work before. However, if we're willing to assume an `xterm` terminal (which sounds like a safe bet), we can fix it as follows before calling `clear`: `if (-not $env:TERM) { $env:TERM='xterm' }` - probably better to reset the variable afterwards.

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/InitialSessionState.cs]: Ok, we can defer the remote scenario since it doesn't work today (and I think there's a issue on that already).  We can take this with the current change to address the specific problem of the VT codes emitted to the pipeline.

**Review by SteveL-MSFT — APPROVED** [review]
Ok with the changes scoped to the specific problem being fixed.  We can defer the other issues as they are existing issues.

File: src/System.Management.Automation/engine/InitialSessionState.cs (hunk 1 above)
Comment (mklement0) [reply src/System.Management.Automation/engine/InitialSessionState.cs]: @SteveL-MSFT: Couldn't find an issue relating to remoting specifically.

As it turns out, my suggested `$env:TERM='xterm'` workaround for remoting only works with `$host.UI.Write()` (`Write-Host -NoNewline`), not with `[console]::Write()`, because the escape sequences must be sent to the _caller's_ terminal.

In light of that - if you don't want to incorporate the full workaround yet - it's better to switch to `$host.UI.Write()`.

For the record, here's the complete workaround (from my personal notes):

---

To fix the remoting problem, `$env:TERM` can be set to `xterm` temporarily, under the assumption that pretty much all terminals are Xterm-compatible these days - and that it is the _caller_ that uses such a terminal, because the escape sequences must be printed to the _caller's_ terminal:

```powershell
  function Clear-Host {
    if ($noTerm = -not $env:TERM) { $env:TERM = 'xterm' }
    $host.UI.Write((
      & (Get-Command -CommandType Application clear | Select-Object -First 1).Definition
    ))
    if ($noTerm) { $env:TERM = $null }
  }
```

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/InitialSessionState.cs]: I like the suggestion to switch to `$host.UI.Write()`.  Not so sure about the assumption that terminals are xterm compatible.  The issue I was thinking about is https://github.com/PowerShell/PowerShell/issues/8606 where remoting was discussed but wasn't the focus.

Comment (iSazonov) [reply src/System.Management.Automation/engine/InitialSessionState.cs]: I will look `$host.UI.Write()` today. I hope we could implement this step-by-step (first for local host. then remote one that would be more tricky)

Comment (mklement0) [reply src/System.Management.Automation/engine/InitialSessionState.cs]: Thanks for the link, @SteveL-MSFT, but resolving #8608 will not address the remoting problem; while there is a single comment - https://github.com/PowerShell/PowerShell/issues/8606#issuecomment-452435884 - that touches on the need to support non-console hosts, a separate issue should really be opened for that.

As for assuming `xterm`: Anecdotally, I'd say it's a pretty safe bet, but the better solution would be to extend the `$PSSenderInfo` object to include the caller's `$env:TERM` value, if any, and have `Clear-Host` consult that.
