### PR TITLE
Never load a module targeting the PSReadLine module's `SessionState`

### LINKED ISSUE #24904: StackOverflowException when PSReadLine is imported inside another imported module
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [x] Search the existing issues, especially the pinned issues.

### Exception report

```console
Repeated 69441 times:
--------------------------------
   at System.Management.Automation.PSModuleInfo.GetExportedTypeDefinitions()
--------------------------------
   at System.Management.Automation.Language.Compiler.LoadUsingsImpl(System.Collections.Generic.IEnumerable`1<System.Management.Automation.Language.UsingStatementAst>, System.Reflection.Assembly[] ByRef)
   at System.Management.Automation.Language.Compiler.GenerateLoadUsings(System.Collections.Generic.IEnumerable`1<System.Management.Automation.Language.UsingStatementAst>, Boolean, System.Collections.Generic.List`1<System.Linq.Expressions.Expression>)
   at System.Management.Automation.Language.Compiler.GenerateTypesAndUsings(System.Management.Automation.Language.ScriptBlockAst, System.Collections.Generic.List`1<System.Linq.Expressions.Expression>)
   at System.Management.Automation.Language.Compiler.CompileSingleLambda(System.Collections.ObjectModel.ReadOnlyCollection`1<System.Management.Automation.Language.StatementAst>, System.Collections.ObjectModel.ReadOnlyCollection`1<System.Management.Automation.Language.TrapStatementAst>, System.String, System.Management.Automation.Language.IScriptExtent, System.Management.Automation.Language.IScriptExtent, System.Management.Automation.Language.ScriptBlockAst)
   at System.Management.Automation.Language.Compiler.CompileNamedBlock(System.Management.Automation.Language.NamedBlockAst, System.String, System.Management.Automation.Language.ScriptBlockAst)
   at System.Management.Automation.Language.Compiler.VisitScriptBlock(System.Management.Automation.Language.ScriptBlockAst)
   at System.Management.Automation.Language.Compiler.Compile(System.Management.Automation.CompiledScriptBlockData, Boolean)
   at System.Management.Automation.CompiledScriptBlockData.ReallyCompile(Boolean)
   at System.Management.Automation.CompiledScriptBlockData.CompileOptimized()
   at System.Management.Automation.CompiledScriptBlockData.Compile(Boolean)
   at System.Management.Automation.PSScriptCmdlet..ctor(System.Management.Automation.ScriptBlock, Boolean, Boolean, System.Management.Automation.ExecutionContext)
   at System.Management.Automation.CommandProcessor.Init(System.Management.Automation.IScriptCommandInfo)
   at System.Management.Automation.CommandDiscovery.GetScriptAsCmdletProcessor(System.Management.Automation.IScriptCommandInfo, System.Management.Automation.ExecutionContext, Boolean, Boolean, System.Management.Automation.SessionStateInternal)
   at System.Management.Automation.CommandDiscovery.CreateCommandProcessorForScript(System.Management.Automation.ExternalScriptInfo, System.Management.Automation.ExecutionContext, Boolean, System.Management.Automation.SessionStateInternal)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(System.Management.Automation.CommandInfo, System.Management.Automation.CommandOrigin, System.Nullable`1<Boolean>, System.Management.Automation.SessionStateInternal)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(System.String, System.Management.Automation.CommandOrigin, System.Nullable`1<Boolean>)
   at System.Management.Automation.ExecutionContext.CreateCommand(System.String, Boolean)
   at System.Management.Automation.Language.PseudoParameterBinder.PrepareCommandElements(System.Management.Automation.ExecutionContext, System.Management.Automation.Language.CommandParameterAst)
   at System.Management.Automation.Language.PseudoParameterBinder.DoPseudoParameterBinding(System.Management.Automation.Language.CommandAst, System.Type, System.Management.Automation.Language.CommandParameterAst, BindingType, Boolean)
   at System.Management.Automation.CompletionCompleters.CompleteCommandParameter(System.Management.Automation.CompletionContext)
   at System.Management.Automation.CompletionAnalysis.GetResultForIdentifier(System.Management.Automation.CompletionContext, Int32 ByRef, Int32 ByRef)
   at System.Management.Automation.CompletionAnalysis.GetResultHelper(System.Management.Automation.CompletionContext, Int32 ByRef, Int32 ByRef)
   at System.Management.Automation.CompletionAnalysis.GetResults(System.Management.Automation.PowerShell, Int32 ByRef, Int32 ByRef)
   at System.Management.Automation.CommandCompletion.CompleteInputImpl(System.Management.Automation.Language.Ast, System.Management.Automation.Language.Token[], System.Management.Automation.Language.IScriptPosition, System.Collections.Hashtable)
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Type, System.String, Int32, System.Collections.Hashtable)
   at System.Management.Automation.Interpreter.DynamicInstruction`5[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.Interpreter.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon)
   at System.Management.Automation.PSScriptCmdlet.RunClause(System.Action`1<System.Management.Automation.Language.FunctionContext>, System.Object, System.Object)
   at System.Management.Automation.CommandProcessorBase.Complete()
   at System.Management.Automation.CommandProcessorBase.DoComplete()
   at System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(System.Management.Automation.CommandProcessorBase)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.LocalPipeline.StartPipelineExecution()
   at System.Management.Automation.Runspaces.PipelineBase.CoreInvoke(System.Collections.IEnumerable, Boolean)
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(System.Collections.IEnumerable)
   at System.Management.Automation.PowerShell+Worker.ConstructPipelineAndDoWork(System.Management.Automation.Runspaces.Runspace, Boolean)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Management.Automation.PSDataCollection`1<System.__Canon>, System.Management.Automation.PSDataCollection`1<System.__Canon>, System.Management.Automation.PSInvocationSettings)
   at System.Management.Automation.PowerShell.CoreInvoke[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Management.Automation.PSDataCollection`1<System.__Canon>, System.Management.Automation.PSDataCollection`1<System.__Canon>, System.Management.Automation.PSInvocationSettings)
   at System.Management.Automation.PowerShell.Invoke(System.Collections.IEnumerable, System.Management.Automation.PSInvocationSettings)
   at System.Management.Automation.CommandCompletion.CallScriptWithStringParameterSet(System.String, Int32, System.Collections.Hashtable, System.Management.Automation.PowerShell)
   at System.Management.Automation.CommandCompletion.CompleteInput(System.String, Int32, System.Collections.Hashtable, System.Management.Automation.PowerShell)
   at Microsoft.PowerShell.PSConsoleReadLine+<>c__DisplayClass33_0.<Microsoft.PowerShell.Internal.IPSConsoleReadLineMockableMethods.CompleteInput>b__0()
   at PlatformWindows.CallPossibleExternalApplication[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Func`1<System.__Canon>)
   at Microsoft.PowerShell.PSConsoleReadLine.CallPossibleExternalApplication[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Func`1<System.__Canon>)
   at Microsoft.PowerShell.PSConsoleReadLine.Microsoft.PowerShell.Internal.IPSConsoleReadLineMockableMethods.CompleteInput(System.String, Int32, System.Collections.Hashtable, System.Management.Automation.PowerShell)
   at Microsoft.PowerShell.PSConsoleReadLine.GetCompletions()
   at Microsoft.PowerShell.PSConsoleReadLine.Complete(Boolean)
   at Microsoft.PowerShell.PSConsoleReadLine.TabCompleteNext(System.Nullable`1<System.ConsoleKeyInfo>, System.Object)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(Microsoft.PowerShell.PSKeyInfo, System.Collections.Generic.Dictionary`2<Microsoft.PowerShell.PSKeyInfo,KeyHandler>, Boolean, System.Object)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(System.Management.Automation.Runspaces.Runspace, System.Management.Automation.EngineIntrinsics, System.Threading.CancellationToken, System.Nullable`1<Boolean>)
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Type, System.Object, System.Object, System.Object)
   at System.Management.Automation.Interpreter.DynamicInstruction`5[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.Interpreter.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon)
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(System.Action`1<System.Management.Automation.Language.FunctionContext>, System.Object, System.Object)
   at System.Management.Automation.DlrScriptCommandProcessor.Complete()
   at System.Management.Automation.CommandProcessorBase.DoComplete()
   at System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(System.Management.Automation.CommandProcessorBase)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
```

### Screenshot

Image

### Environment data

```console
PS Version: 7.5.0
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.3.6
PSReadLine EditMode: Windows
OS: 10.0.26100.1 (WinBuild.160101.0800)
BufferWidth: 210
BufferHeight: 50
```

### Steps to reproduce

* Create a psm1 module which through either `Import-Module` or `Using module` imports PSReadLine
* Create a ps1 script with a param block
* Import the psm1 module from the ps1 script
* Try to tab complete an argument from the ps1 script

---

test.psm1
```powershell
using module @{
    ModuleName = "PSReadLine";
    ModuleVersion = "2.3.6";
}
```

test.ps1
```powershell
using module .\test.psm1

param()
```

### Expected behavior

That there is no StackOverflowException and tab completion works.

### Actual behavior

StackOverflowException and crash of the powershell session.

### PR DESCRIPTION
**Pull request by daxian-dbw**
## PR Summary

Fix #24904

Module loading could happen in PSReadLine module's context because
1. it may be due to tab completion triggered by PSReadLine,
2. it may be due to a command run triggered by key-binding press

But that doesn't mean the module should be loaded targeting the PSReadLine module's session state. In this case, we should use the `Global` session state instead. PSReadLine doesn't depend on any other modules and should not have any module loaded into its session state.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
  - [x] None
  - **OR**
  - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
    - [ ] Experimental feature name(s): 
- **User-facing changes**
  - [x] Not Applicable
  - **OR**
  - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
  - [x] N/A or can only be tested interactively **because the module loading needs to be triggered from within PSReadLine**
  - **OR**
  - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
  - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

File: src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs [hunk 1]
```diff
@@ -140,11 +140,16 @@ internal SessionState TargetSessionState
...
                 }
                 else
                 {
-                    return this.Context.SessionState;
+                    // Module loading could happen during tab completion triggered by PSReadLine,
+                    // but that doesn't mean the module should be loaded targeting the PSReadLine
+                    // module's session state. In that case, use Global session state instead.
+                    return Context.EngineSessionState.Module?.Name is "PSReadLine"
+                        ? Context.TopLevelSessionState.PublicSessionState
+                        : Context.SessionState;
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs:152]: Could you please make the code more readable:
```c#
        internal SessionState TargetSessionState
        {
            // Module loading could happen during tab completion triggered by PSReadLine,
            // but that doesn't mean the module should be loaded targeting the PSReadLine
            // module's session state. In that case, use Global session state instead.
            get => BaseGlobal || Context.EngineSessionState.Module?.Name is "PSReadLine"
                   ? Context.TopLevelSessionState.PublicSessionState
                   : Context.SessionState;
        }
```

**Review by iSazonov — APPROVED** [review]
LGTM with one minor comment.
