### PR TITLE
Enhance Remove-Item to work with OneDrive (Second)

### LINKED ISSUE #15248: On Windows, Remove-Item unexpectedly fails if the target directory path happens to end in a backslash
## Steps to reproduce

```powershell
# Switch to a temporary directory.
Push-Location -ea Stop ($tmpDir = (New-Item -Type Directory -Force (Join-Path Temp:/ $PID)).FullName)

try {

  # Create two directories with one file each in them.
  $null = New-Item -Type Directory -force foo1, foo2
  $null = New-Item -force foo1\t.txt, foo2\t.txt

  # Remove the first one with WITHOUT a trailing "\"
  { Remove-Item .\foo1 -Recurse -ErrorAction Stop } | Should -Not -Throw

  # Remove the second one with WITH a trailing "\"
  # This is also what you'd get with tab-completion.
  { Remove-Item .\foo2\ -Recurse -ErrorAction Stop } | Should -Not -Throw

} finally {
  # Clean up.
  Pop-Location; Remove-Item $tmpDir -Recurse
}
```

## Expected behavior

Both tests should succeed: whether the target directory is specified with a trailing path separator or not should not make a difference.

## Actual behavior

On Windows, removal fails when the target path ends in `\`:

```none
Cannot remove item C:\Users\jdoe\AppData\Local\Temp\8656\foo2\: The directory is not empty.
```

Note:
* The problem only occurs if the target dir. is _non-empty_.
* It seems to have been introduced in v7.2.0-preview.5

## Environment data

```none
PowerShell Core v7.2.0-preview.5 on Microsoft Windows 10 Pro (64-bit; Version 20H2, OS Build: 19042.928)
```

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary
Better to review commit by commit:
1. First commit comes from #14902
2. Second commit fix #15248 (see also #15253)
3. Third commit reformat old tests
4. Fourth commit add new test

--------

About second commit.

Partial regression in #14902. Partial because there are other code paths (a path comes from public with trailing backslash) which can raise an issue in the place.

[Docs](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstfileexw#parameters) say that  FindFirstFileEx does not accept a path with a trailing backslash (\\).

The fix is always removing a trailing backslash from path string before calling FindFirstFileEx.

--------

Before the fix only enumeration (Get-ChildItem) worked on OneDrive. 
Now Remove-Item correctly removes folders and files on OneDrive too.

1. Enhance IsReparsePointLikeSymlink() method so that exclude non named surrogates from reparse points. As result PowerShell recurse into such reparse points which is a OneDrive entities.
1.  Use updated IsReparsePointLikeSymlink() method in RemoveDirectoryInfoItem() and NameString() methods 
1. Add new tests and a test hook to emulate old PowerShell behavior and test new PowerShell behavior on OneDrive.
1. Add small perf improvement in Dir() and IsReparsePointLikeSymlink() methods to exclude extra p/invoke in most scenarios. 

## PR Context

Replace #14860 and #14902 (reverted in #15253)

Related #9246

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by TravisEz13** [comment]
@rjmholt See how to run the CI that tests the issue here:  https://github.com/PowerShell/PowerShell/pull/15260#issuecomment-822691420

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 1]
```diff
@@ -1890,9 +1890,17 @@ protected override void InvokeDefaultAction(string path)
...
+                            bool checkReparsePoint = true;
                             if (!Force)
                             {
                                 hidden = (recursiveDirectory.Attributes & FileAttributes.Hidden) != 0;
+
+                                // Performance optimization.
+                                // Since we have already checked Attributes for Hidden we have already did a p/invoke
+                                // and initialized Attributes property.
+                                // So here we can check for ReparsePoint without new p/invoke.
+                                // If it is not a reparse point we skip one p/invoke in IsReparsePointLikeSymlink() below.
```
Comment (rjmholt) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:1902]:
```suggestion
                                // We've already taken the expense of initializing the Attributes property here,
                                // so we can use that to avoid needing to call IsReparsePointLikeSymlink() later.
```

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 2]
```diff
@@ -8215,28 +8232,49 @@ internal static bool IsReparsePoint(FileSystemInfo fileInfo)
...
-            var data = new WIN32_FIND_DATA();
-            using (var handle = FindFirstFileEx(fileInfo.FullName, FINDEX_INFO_LEVELS.FindExInfoBasic, ref data, FINDEX_SEARCH_OPS.FindExSearchNameMatch, IntPtr.Zero, 0))
+
+            WIN32_FIND_DATA data = default;
+            string fullPath = Path.TrimEndingDirectorySeparator(fileInfo.FullName);
+            using (var handle = FindFirstFileEx(fullPath, FINDEX_INFO_LEVELS.FindExInfoBasic, ref data, FINDEX_SEARCH_OPS.FindExSearchNameMatch, IntPtr.Zero, 0))
             {
+                if (handle.IsInvalid)
+                {
+                    // We should never be here.
```
Comment (rjmholt) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:8252]: Worth saying _why_ it shouldn't be possible to get here I think

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 3]
```diff
@@ -8215,28 +8232,49 @@ internal static bool IsReparsePoint(FileSystemInfo fileInfo)
...
+                    int lastError = Marshal.GetLastWin32Error();
+                    throw new Win32Exception(lastError);
+                }
+
+                // To exclude one extra p/invoke in some scenarios
+                // we don't check fileInfo.FileAttributes
```
Comment (rjmholt) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:8258]:
```suggestion
                // We already have the file attribute information from our Win32 call,
                // so no need to take the expense of the FileInfo.FileAttributes call
```

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 4]
```diff
@@ -8215,28 +8232,49 @@ internal static bool IsReparsePoint(FileSystemInfo fileInfo)
...
+                    // Not a reparse point.
+                    return false;
+                }
+
                 // The name surrogate bit 0x20000000 is defined in https://docs.microsoft.com/windows/win32/fileio/reparse-point-tags
                 // Name surrogates (0x20000000) are reparse points that point to other named entities local to the filesystem
                 // (like symlinks and mount points).
                 // In the case of OneDrive, they are not name surrogates and would be safe to recurse into.
-                if (!handle.IsInvalid && (data.dwReserved0 & 0x20000000) == 0 && (data.dwReserved0 != IO_REPARSE_TAG_APPEXECLINK))
+                if ((data.dwReserved0 & 0x20000000) == 0 && (data.dwReserved0 != IO_REPARSE_TAG_APPEXECLINK))
```
Comment (rjmholt) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:8270]: Is `0x20000000` a value that could be named as a `const`?

**Review by rjmholt — APPROVED** [review]

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 2 above)
Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:8249]: I cannot describe a specific scenario. Most likely, an error will occur if the file is deleted at this moment or the access rights have changed. This is _unlikely_. But in any case, we cannot simply ignore the error.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 4 above)
Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:8267]: If I remember correctly Windows SDK has not a name for the constant.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 2 above)
Comment (rjmholt) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs:8249]: Ah, ok, so _never_ isn't quite true and we're really protecting against the fundamental unsafety of the filesystem. Perhaps something like:

```suggestion
                    // Our handle could be invalidated by something else touching the filesystem,
                    // so ensure we deal with that possibility here
```

**Comment by rjmholt** [comment]
Ok this seems to be passing CI so I'm going to merge, but we'll just need to keep an eye out for CI failures later on

**Comment by TravisEz13** [comment]
Verified this passed CI after merge: 
https://dev.azure.com/powershell/PowerShell/_build/results?buildId=77087&view=results

**Comment by rjmholt** [comment]
We've picked up a test failure during release testing that we think is caused by this change.

The failing tests are these:

https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1#L960-L999

And the error message is this:

```
PS:31> Remove-Item -Path $longFilePath
Remove-Item: The system cannot find the path specified.
```

Exception:
```
NativeErrorCode : 3
ErrorCode       : -2147467259
TargetSite      : Boolean IsReparsePointLikeSymlink(System.IO.FileSystemInfo)
StackTrace      :    at Microsoft.PowerShell.Commands.InternalSymbolicLinkLinkCodeMethods.IsReparsePointLikeSymlink(Fil
                  eSystemInfo fileInfo) in System.Management.Automation.dll:token 0x60016f5+0x97
                     at Microsoft.PowerShell.Commands.RemoveItemCommand.ProcessRecord() in
                  Microsoft.PowerShell.Commands.Management.dll:token 0x60004dd+0x2e2
                     at System.Management.Automation.CommandProcessor.ProcessRecord() in
                  System.Management.Automation.dll:token 0x60020f6+0x1ae
Message         : The system cannot find the path specified.
Data            : {}
InnerException  :
HelpLink        :
Source          : System.Management.Automation
HResult         : -2147467259
```

It appears that using [`FindFirstFileExW`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstfileexw), we need to:

- Ensure the path exists before calling the Windows API
- Ensure that long paths are converted to the long path format appropriately

It also seems that the long path tests to catch this did not in our daily builds and we need to investigate why.

**Comment by iSazonov** [comment]
> We've picked up a test failure during **release testing** that we think is caused by this change.

I wonder CIs was passed successfully.

File: test/powershell/Modules/Microsoft.PowerShell.Management/Remove-Item.Tests.ps1 [hunk 5]
```diff
@@ -1,170 +1,195 @@
...
+            { Remove-Item $testdirectory -Recurse -ErrorAction Stop } | Should -Not -Throw
 
-	It "Should be able to remove a directory" {
-	    { Remove-Item $testdirectory } | Should -Not -Throw
+            Test-Path $testdirectory | Should -BeFalse
+        }
 
-	    Test-Path $testdirectory | Should -BeFalse
-	}
+        It "Should be able to recursively delete a directory with a trailing backslash" {
```
Comment (rkeithhill) [inline test/powershell/Modules/Microsoft.PowerShell.Management/Remove-Item.Tests.ps1:146]: Thanks for adding this regression test!

Comment (iSazonov) [reply test/powershell/Modules/Microsoft.PowerShell.Management/Remove-Item.Tests.ps1:146]: Really we have _very_ small code coverage. I hope WGs start work and we add more tests to exclude regressions.

**Comment by rjmholt** [comment]
I discussed this with @daxian-dbw, @adityapatwardhan and @anmenaga and rather than trying to fix this as is, we think the previous bug is easier to live with than the new bug and that we need to revert it. We can accept a full solution later.
