### PR TITLE
Fix `PlainText` output to correctly remove Reset VT sequence w/o number

### LINKED ISSUE #19246: `StringDecorated` class doesn't recognize `<esc>[m ` as the  ANSI reset escape sequence, requires `<esc>[0m`
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

``"`e[m "`` is a valid ANSI escape sequence that resets current formatting, short for ``"`e[0m "`` 

The `StringDecorated` currently doesn't recognize it, and retains it as part of the data when plain-text conversion is requested.

```powershell
# If you output the string directly to the terminal, you'll see that the trailing "." is NOT green anymore,
# proving that "`e[m"` was effective in resetting the color.
([System.Management.Automation.Internal.StringDecorated]::new("`e[32mgreen`e[m.")).ToString('PlainText') | Format-Hex
```

Note:

* Because _terminals_ recognize ``"`e[m "`` correctly, the problem is usually _hidden_ when the class is used behind the scenes in conjunction with `$PSStyle.OutputRendering = 'PlainText'`,  e.g. with
`$PSStyle.OutputRendering = 'PlainText'; wsl -e printf '\e[32mgreen\e[m.' | Out-Host`.

* However, due to the - inappropriately closed - #18771 - it currently _does_ surface in `conhost.exe` windows on Windows.

### Expected behavior

```console
Label: String (System.String) <7E780A95>

          Offset Bytes                                           Ascii
                 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
          ------ ----------------------------------------------- -----
0000000000000000 67 72 65 65 6E 2E                               green.
```

### Actual behavior

```console
Label: String (System.String) <56784E4B>

          Offset Bytes                                           Ascii
                 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
          ------ ----------------------------------------------- -----
0000000000000000 67 72 65 65 6E 1B 5B 6D 2E                      green�[m.
```

Note the extraneous `�[m` part in the `Ascii` column, showing that `` `e[m `` was unexpectedly retained.

### Error details

_No response_

### Environment data

```powershell
PowerShell Core 7.4.0-preview.1
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

Apparently `ESC[m` is valid short hand for `ESC[0m` so the regex used to remove ESC sequences needed to be adjusted to not require a digit.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/19246

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/FormatAndOutput/common/StringDecorated.cs [hunk 1]
```diff
@@ -98,7 +98,7 @@ private string PlainText
         }
 
         // graphics/color mode ESC[1;2;...m
-        private const string GraphicsRegex = @"(\x1b\[\d+(;\d+)*m)";
+        private const string GraphicsRegex = @"(\x1b\[\d*(;\d+)*m)";
```
Comment (daxian-dbw) [inline src/System.Management.Automation/FormatAndOutput/common/StringDecorated.cs:101]: This allows a string like `esc[;2m` -- is this considered a valid escape sequence?

Comment (iSazonov) [reply src/System.Management.Automation/FormatAndOutput/common/StringDecorated.cs:101]: /cc @mklement0

Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/common/StringDecorated.cs:101]: Testing with zsh and iTerm2, `ESC[;35m` renders as purple, so it seems to be accepted

**Review by daxian-dbw — APPROVED** [review]
LGTM
