### PR TITLE
Discover assemblies loaded by 'Assembly.Load(byte[])' and 'Assembly.LoadFile'

### LINKED ISSUE #12052: Powershell 7.x : Cannot use type from dll (built for netstandard2.0)
# Steps to reproduce 

Provided that there is a dotnet core sdk istalled, run script as below.
What script does:
 - Displays some debug stuff (dotnet core version, powershell version)
 - Crates some directories e.g. where published library will be copied
 - Creates ad hoc dot net core class lib project (targeted for `netstandard2.0`)
 - Compiles the project into dll
 - Loads the dll into powershell
 - Calls function `Hello` from the dll and expects to receive predefined output (== "Works!")

```powershell
Function ShowErrorDetails
{
    param(
        $ErrorRecord = $Error[0]
    )

    $out=""
    $out+= $($ErrorRecord | Format-List -Property * -Force | out-string)
    $out+= $($ErrorRecord.InvocationInfo | Format-List -Property * | out-string)
    $Exception = $ErrorRecord.Exception
    for ($depth = 0; $Exception -ne $null; $depth++)
    {
        $out+= $("$depth" * 80)
        $out+= $($Exception | Format-List -Property * -Force | out-string)
        $Exception = $Exception.InnerException
    }
    # emit return object
    $out
}
 
 $myLibName="MyLib"
 $myLibDllName="${myLibName}.dll"
 $csProjName = "${myLibName}.csproj"
 $thisDir = Get-Location  
 $workdir = Join-Path $thisDir "workdir"
 $libraryCodeDir = Join-Path $workdir $myLibName
 $csProjFilePath = Join-Path $libraryCodeDir $csProjName 
 $publishedOutputDir = Join-Path $workdir "published"
 $dllFilePath = Join-Path $publishedOutputDir $myLibDllName
 
 Write-Host "thisDir            : '$thisDir'"
 Write-Host "myLibName          : '$myLibName'"
 Write-Host "csProjName         : '$csProjName'"
 Write-Host "workdir            : '$workdir'"
 Write-Host "libraryCodeDir     : '$libraryCodeDir'"
 Write-Host "csProjFilePath     : '$csProjFilePath'"
 Write-Host "publishedOutputDir : '$publishedOutputDir'"
 Write-Host "myLibDllName       : '$myLibDllName'"
 Write-Host "dllFilePath        : '$dllFilePath'"

 Write-host "------ >>>>>   Powershell version : "
 $PsVersionTable | Out-Host
 
 Write-Host "------ >>>>>   Dotnet core version: "
 dotnet --info
 
 Write-host "------ >>>>>   Creating $libraryCodeDir..."
 New-item $libraryCodeDir -ItemType Directory -Force
 
 Write-Host "`n------ >>>>>   Creating library template in '$libraryCodeDir'"
 dotnet new classlib --name $myLibName --output $libraryCodeDir --framework "netstandard2.0" --force
 

$expectedOutput = "Works!"

$codeContent = @"
public static class MyClass
{ 
    public static string Hello()
    {
      return "${expectedOutput}";
    }
}
"@

try 
{
  Set-Content -Path $libraryCodeDir/Class1.cs -Value $codeContent
  dotnet publish -c Debug -o ${publishedOutputDir} ${csProjFilePath}
   # if compilation was not successful
  if($global:LASTEXITCODE -ne 0 )
  {
    Write-Error "------ >>>>>   Compilation failed, cannot continue with the script.."
    Exit 1
  }
  else
  {
    Write-Host "------ >>>>>   OK: compilation successful"
  }

  Write-Host "------ >>>>>   Loading library..."
  $bytes = [System.IO.File]::ReadAllBytes($dllFilePath)
  $loadedLib = [System.Reflection.Assembly]::Load($bytes)
  $loadedLib.GetTypes() | Out-Host
  $functionCallResult = [MyClass]::Hello()
  
  if($functionCallResult -eq  $expectedOutput )
  {
     Write-Host "------ >>>>>   SUCCESS: Function call returned expected result"
  }
  else
  {
    Write-Error "------ >>>>>   FAILURE: Function call unxpected result '${functionCallResult}' while expecting '${expectedOutput}'"
    Exit 1
  }
}
catch {
  ShowErrorDetails | Out-Host
}

```

# Expected behavior
 After the script finishes , user should see line like
```none
------ >>>>>   SUCCESS: Function call returned expected result
```

# Actual behavior
I've added a debug function `ShowErrorDetails` to show full error details (code taken from book `Windows Powershell in action` 3rd edition) if something goes wrong.
Powershell 7.0 cannot find the type from the library and at the end of error output it prints something like:

```none
00000000000000000000000000000000000000000000000000000000000000000000000000000000
ErrorRecord                 : Unable to find type [MyClass].
WasThrownFromThrowStatement : False
TargetSite                  : Void CheckActionPreference(System.Management.Automation.Language.FunctionContext, System.Exception)
StackTrace                  :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                                 at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Message                     : Unable to find type [MyClass].
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              :
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087
```

# Environment data

The issue is related only for powershell 7: 
I tested it on :
Windows
```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Ubuntu:
```none

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Linux 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

I have verified that this correctly WORKS  platforms such as
windows powershell 5.1
```none
Name                           Value
----                           -----
PSVersion                      5.1.17763.1007
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1007
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

windows powershell core 6.2.4
```none
Name                           Value
----                           -----
PSVersion                      6.2.4
PSEdition                      Core
GitCommitId                    6.2.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

ubuntu powrshell core 6.2.4
```none
Name                           Value
----                           -----
PSVersion                      6.2.4
PSEdition                      Core
GitCommitId                    6.2.4
OS                             Linux 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

[ubuntu_pwsh6.2.4_output.txt](https://github.com/PowerShell/PowerShell/files/4298867/ubuntu_pwsh6.2.4_output.txt)
[ubuntu_pwsh7_output.txt](https://github.com/PowerShell/PowerShell/files/4298868/ubuntu_pwsh7_output.txt)
[windows_powershell_output.txt](https://github.com/PowerShell/PowerShell/files/4298869/windows_powershell_output.txt)
[windows_pwsh6.2.4_output.txt](https://github.com/PowerShell/PowerShell/files/4298870/windows_pwsh6.2.4_output.txt)
[windows_pwsh7_output.txt](https://github.com/PowerShell/PowerShell/files/4298871/windows_pwsh7_output.txt)

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #12052

Fix a regression in PS 7.0 introduced by #11088 
PowerShell should discover assemblies loaded by `Assembly.Load(byte[])` and `Assembly.LoadFile` as in prior versions.

Assemblies loaded by `Assembly.Load(byte[])` and `Assembly.LoadFile` are placed in special `AssemblyLoadContext` instances of the type `System.Runtime.Loader.IndividualAssemblyLoadContext`. PowerShell should return assemblies from those load context instances.

Also include a minor change to ignore the `.ionide` folders, which are auto-generated by VS Code C# extension to hold symbol caches.

/cc @SeeminglyScience 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -1,5 +1,6 @@
 bin/
```
Comment (PoshChan) [inline .gitignore]: @daxian-dbw, your last commit had 1 failures in `PowerShell-CI-macos`
Test-Connection.TraceRoute.TraceRoute works
```powershell
Expected exactly '10.79.3.146', but got 127.0.0.1.
at <ScriptBlock>, /Users/runner/runners/2.165.2/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1: line 257
257:             $result[0].TargetAddress | Should -BeExactly $realAddress
```

Comment (vexx32) [reply .gitignore]: @TravisEz13 this test seems to come up fairly often but it always resolves itself. Do you know if we have an open issue tracking this?

Comment (TravisEz13) [reply .gitignore]: I'm not aware of an open issue.

Comment (TravisEz13) [reply .gitignore]: I believe it started when me move to catalina.

File: src/System.Management.Automation/utils/ClrFacade.cs [hunk 2]
```diff
@@ -58,9 +58,36 @@ internal static IEnumerable<Assembly> GetAssemblies(TypeResolutionState typeReso
...
+        }
+
+        /// <summary>
+        /// Return assemblies from the default load context and the 'individual' load contexts.
+        /// The 'individual' load contexts are the ones holding assemblies loaded via 'Assembly.Load(byte[])' and 'Assembly.LoadFile'.
+        /// Assemblies loaded in any custom load contexts are not consider visible to PowerShell to avoid type identity issues.
+        /// </summary>
+        private static IEnumerable<Assembly> GetPSVisibleAssemblies()
+        {
+            const string IndividualAssemblyLoadContext = "System.Runtime.Loader.IndividualAssemblyLoadContext";
```
Comment (iSazonov) [inline src/System.Management.Automation/utils/ClrFacade.cs]: My concern is that `IndividualAssemblyLoadContext` is _internal_ class and .Net is free to change the name.
Maybe more reliable to use an assembly context name (`"Assembly.Load(byte[], ...)"` and `"Assembly.LoadFile({0})"`). It is public contract and has one prefix `Assembly.Load` for both.

Comment (daxian-dbw) [reply src/System.Management.Automation/utils/ClrFacade.cs]: Any one can create a ALC instance with the name "Assembly.Load(byte[], ...)" or "Assembly.LoadFile(".
It's less reliable to depend on the name than the type. They can change the type name, but I think that possibility is very low, and we have test to catch the failure if the type name really changes.

File: src/System.Management.Automation/utils/ClrFacade.cs [hunk 3]
```diff
@@ -58,9 +58,36 @@ internal static IEnumerable<Assembly> GetAssemblies(TypeResolutionState typeReso
...
+            {
+                if (!assembly.FullName.StartsWith(TypeDefiner.DynamicClassAssemblyFullNamePrefix, StringComparison.Ordinal))
+                {
+                    yield return assembly;
+                }
+            }
+
+            foreach (AssemblyLoadContext context in AssemblyLoadContext.All)
+            {
+                if (IndividualAssemblyLoadContext.Equals(context.GetType().FullName, StringComparison.Ordinal))
```
Comment (iSazonov) [inline src/System.Management.Automation/utils/ClrFacade.cs]: Can we do:
```suggestion
                if (context is IndividualAssemblyLoadContext)
```

Comment (SeeminglyScience) [reply src/System.Management.Automation/utils/ClrFacade.cs]: `is` won't work dynamically, it takes a type metadata reference instead of a `System.Type` object (even in raw IL it isn't possible).  You could do `typeof(int).Assembly.GetType("FullTypeNameHere.IALC").IsAssignableFrom(context.GetType())` but then you depend on the assembly where the non-public type is located staying the same.

**Review by rjmholt — APPROVED** [review]

**Review by iSazonov — APPROVED** [review]
