### PR TITLE
Fix rendering of DisplayRoot for network PSDrive

### LINKED ISSUE #19903: Get-PSDrive doesn't report the DisplayRoot properly for mounted drive letters correctly in 7.4.0-preview.4
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

If a drive letter corresponds to a mounted network path, `Get-PSDrive` outputs an object whose `DisplayRoot` property corresponds to the network UNC path.

In 7.4.0-preview.4, the value of the property is `System.Span<UInt16>[0]` instead of the expected UNC path.

The behavior is correct in 7.3.5

### Expected behavior

```console
PS> (get-psdrive -Name s).DisplayRoot.ToString()
\\server\share
```

### Actual behavior

```console
PS> (get-psdrive -Name s).DisplayRoot.ToString()
System.Span<UInt16>[0]
```

### Error details

_No response_

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.4
PSEdition                      Core
GitCommitId                    7.4.0-preview.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

As part of some refactoring work to use spans, it appears that the code to get the DisplayRoot simply used `ToString()` on the ushort buffer.  However, `ToString()` only works on a span of chars, so this resulted in returning the type and size instead of the contents.  Fix is to get a Unicode string from the ushort buffer as bytes.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/19903

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by iSazonov** [comment]
@SteveL-MSFT Now we remove the workaround with `ushort` and use `char`. I attached the updated file.
[WNetGetConnection.zip](https://github.com/PowerShell/PowerShell/files/13487003/WNetGetConnection.zip)

File: src/System.Management.Automation/engine/Interop/Windows/WNetGetConnection.cs [hunk 1]
```diff
@@ -52,26 +49,26 @@ internal static int GetUNCForNetworkDrive(char drive, out string? uncPath)
 
             if (errorCode == ERROR_SUCCESS)
             {
-                uncPath = uncBuffer.Slice((int)bufferSize).ToString();
+                uncPath = uncBuffer.Slice(0, (int)bufferSize).ToString();
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/Interop/Windows/WNetGetConnection.cs:52]: In debugger I see extra `\0` last char in `uncPath`. If you see the same we should (below too) something like:
```suggestion
                uncPath = uncBuffer.Slice(0, (int)(bufferSize - 1)).ToString();
```

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/Interop/Windows/WNetGetConnection.cs]: I thought that `ToString()` would handle the null terminator, but looking at the dotnet/runtime code, it'll happily keep the null terminator.  Fixed.

**Review by iSazonov — APPROVED** [review]
