### PR TITLE
Recognize CONOUT$ and CONIN$ as reserved device names

### LINKED ISSUE #13046: IsReservedDeviceName does not recognize CONIN$, CONOUT$
# Steps to reproduce

```powershell
"hello" > world
Move-Item world CONOUT$
```

## Expected behavior

```none
Move-Item: Cannot process path 'C:\Temp\u\CONOUT$' because the target represents a reserved device name.
```

## Actual behavior

Move-Item outputs `hello` to the console. After that, neither `world` nor `CONOUT$` exists as a file in the directory.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Notes

<https://github.com/PowerShell/PowerShell/blob/ab7460365ffdd40e1c3ae67958a27f210c6b594a/src/System.Management.Automation/engine/Utils.cs#L1254-L1256>

That also lists `CLOCK$`, `COM0`, and `LPT0` even though those names are not reserved in Win32. IIRC, MS-DOS has a `CLOCK$` or `CONFIG$` device.

### PR DESCRIPTION
**Pull request by davidreis97**
# PR Summary

Fixes #13046.

Adds `CONOUT$` and  `CONIN$` to the list of reserved device names. The existing range of filename lengths to be checked for reserved names excluded `CONOUT$` since it only checked names of up to 6 characters. To include `CONOUT$`, this range has been bumped to 7 characters.

With these changes, attempting to execute filesystem commands with these names as targets will now raise an exception, as defined in the expected behaviour section of the linked issue.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - The Pester test for reserved names has been modified to test against the names added in this pull request.
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by iSazonov** [comment]
@DHowett Have you any thoughts about blocking CONIN$ and CONOUT$ in PowerShell file operations?
`Copy-Item <text file> CONOUT$` works like Get-Content and this looks good and we could expect `copy-item  CONIN$ <file path>` works too but no. Also we have New-Item and others and this force us to think that we should follow the best practice and block these reserved names.
In my opinion, we should ban these names in order to eliminate misunderstandings and unjustified expectations.

**Comment by vexx32** [comment]
Yeah, we're already blocking the majority of them, so probably it would make sense to block all of them.

Maybe a subset of them could be useful for specific provider cmdlets, but I don't think any of them would be universally useful for all the provider cmdlets to support.

**Comment by DHowett** [comment]
So, here's the thing that worries me about the windows reserved names.

I don't know how we handle them in a world where pwsh also runs on Linux (and can access `/dev/sda1`, or `/dev/fd/0` which is a lot like `CONOUT$`) and macOS (`/dev/rdisk0`, `/dev/tty`).

Do we have a holistic story that covers how powershell handles devicelike file handles in general? If not, is this just putting a band-aid over a problem?

**Comment by DHowett** [comment]
But, here: **We should block these names.**

There are better wats to write output to the console or read input from the console. It is generally a bad thing that we would allow PowerShell users -- users who have opted into a _higher-level abstraction_ -- direct unmanaged access to the raw I/O handles.

CMD should be able to do it. Perhaps PowerShell should bend users towards using the object model instead.

**Comment by vexx32** [comment]
/cc @SteveL-MSFT not sure who best to answer @DHowett's question regarding similarly reserved names on MacOS/Linux, but maybe worth opening an issue for? 🤔 

Otherwise... yep, agreed. 🙂

**Comment by iSazonov** [comment]
> Do we have a holistic story that covers how powershell handles devicelike file handles in general? If not, is this just putting a band-aid over a problem?

We follow the naming convention https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions but CONIN$/CONOUT$ is not documented there.

 > I don't know how we handle them in a world where pwsh also runs on Linux (and can access /dev/sda1, or /dev/fd/0 which is a lot like CONOUT$) and macOS (/dev/rdisk0, /dev/tty).

In Unix-s they are files. Users could do `cd ~; mkdir /dev/sda1` and access this by `cat ./dev/sda1`. But in Windows `./` prefix optional and users can do `type CONOUT$` and it is not clear whether this a file or a device.

**Review by iSazonov — APPROVED** [review]
Perhaps IsReservedDeviceName() is on hot path and we could measure and optimize its performance in follow PR.

File: src/System.Management.Automation/engine/Utils.cs [hunk 1]
```diff
@@ -1258,14 +1258,14 @@ internal static bool IsAdministrator()
...
+            string[] reservedDeviceNames = { "CON", "PRN", "AUX", "CLOCK$", "NUL", "CONIN$", "CONOUT$",
                                              "COM0", "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9",
                                              "LPT0", "LPT1", "LPT2", "LPT3", "LPT4", "LPT5", "LPT6", "LPT7", "LPT8", "LPT9" };
             string compareName = Path.GetFileName(destinationPath);
             string noExtensionCompareName = Path.GetFileNameWithoutExtension(destinationPath);
 
-            if (((compareName.Length < 3) || (compareName.Length > 6)) &&
-                ((noExtensionCompareName.Length < 3) || (noExtensionCompareName.Length > 6)))
+            if (((compareName.Length < 3) || (compareName.Length > 7)) &&
+                ((noExtensionCompareName.Length < 3) || (noExtensionCompareName.Length > 7)))
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/Utils.cs:1268]: This comment is not blocking. It looks to me we only need to check on `noExtensionCompareName`. The checking on `compareName` seems not needed. /cc @anmenaga @iSazonov

**Review by daxian-dbw — APPROVED** [review]

File: src/System.Management.Automation/engine/Utils.cs (hunk 1 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/Utils.cs:1268]: I open new tracking issue #13618.

**Comment by iSazonov** [comment]
@anmenaga The PR is ready to merge.

**Comment by iSazonov** [comment]
@davidreis97 Thanks for your contribution!
