### PR TITLE
Special case the posix locale in WildcardPattern

### LINKED ISSUE #10177: New-Item cmdlet fails to create folder on PowerShell 7.0.0-preview.2
# Steps to reproduce

1.	Create Ubuntu 18.04 VM in Azure
2.	wget https://github.com/PowerShell/PowerShell/releases/download/v7.0.0-preview.2/powershell-preview_7.0.0-preview.2-1.ubuntu.18.04_amd64.deb
3.	sudo apt install ./powershell-preview_7.0.0-preview.2-1.ubuntu.18.04_amd64.deb
4.	pwsh-preview
5.	new-item -ItemType Directory ./newfolder

In bash run
```bash
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
pwsh
```

Then, run
```powershell
 New-Item -ItemType Directory ./bas
```

# Expected behavior

new folder is created.

```none

```

# Actual behavior

PS /home/amitsaraf> new-item -ItemType Directory ./newfolder
new-item : The type is not a known type for the file system. Only "file","directory" or "symboliclink" can be specified.
At line:1 char:1
+ new-item -ItemType Directory ./newfolder
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [New-Item], PSArgumentException
+ FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.NewItemCommand

```none

```

# Environment data

```none

```

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #10177
Special case the posix locale in WildcardPattern.
When `WildcardOptions.IgnoreCase` is specified and the current culture is `en-us-POSIX`, we use `StringComparison.OrdinalIgnoreCase` instead of `StringComparison.CurrentCultureIgnoreCase`, because the Posix culture compares in case-sensitive manner only.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

File: src/System.Management.Automation/engine/regex.cs [hunk 1]
```diff
@@ -142,7 +142,11 @@ StringComparison GetStringComparison()
                 {
                     stringComparison = Options.HasFlag(WildcardOptions.CultureInvariant)
                         ? StringComparison.InvariantCultureIgnoreCase
-                        : StringComparison.CurrentCultureIgnoreCase;
+                        : CultureInfo.CurrentCulture.Name.Equals("en-US-POSIX", StringComparison.OrdinalIgnoreCase)
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/regex.cs]: Looking how we use WildcardPattern.IsMatch() I am sure that in most of cases we can definitely replace `StringComparison.CurrentCultureIgnoreCase` with `StringComparison.OrdinalIgnoreCase`. One place where we should be careful is HelpSystem but where we could use Regex directly.

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/regex.cs]: I'm not sure about it. Quoted from doc about [StringComparer.OrdinalIgnoreCase](https://docs.microsoft.com/en-us/dotnet/api/system.stringcomparer.ordinalignorecase?view=netframework-4.8#remarks):
>The StringComparer returned by the OrdinalIgnoreCase property treats the characters in the strings to compare as if they were converted to uppercase **using the conventions of the invariant culture**, and then performs a simple byte comparison that is independent of language.

So when using `OrdinalIgnoreCase`, it will actually use `invariant culture` to convert characters to upper cases. This makes me nervous about using `OrdinalIgnoreCase` in general for wildcard matching.

Comment (iSazonov) [reply src/System.Management.Automation/engine/regex.cs]: Sorry, my comment was out of the context. I meant that we do culture-sensitive comparisons while we should be culture-insensitive (ordinal) in most of cases where WildcardPattern is used.

As for your fix  it is LGTM.

**Review by iSazonov — APPROVED** [review]

File: src/System.Management.Automation/engine/regex.cs (hunk 1 above)
Comment (TravisEz13) [inline src/System.Management.Automation/engine/regex.cs]: Should we add a test case?

We have one for.. hashtable.

Comment (TravisEz13) [reply src/System.Management.Automation/engine/regex.cs]: https://github.com/PowerShell/PowerShell/blob/1ce2de4a15836a2b57d84b115d74039e53d6b056/test/powershell/Language/Parser/LanguageAndParser.TestFollowup.Tests.ps1#L307

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/regex.cs]: Test added. Two things to be noted:
1. Setting the current culture to be 'en-us-POSIX' doesn't do anything on Windows -- `[string]::Equals("a", "A", [System.StringComparison]::CurrentCultureIgnoreCase)` always returns `true`.
2. It seems to be the existing way of changing culture works fine. The following script writes out `false` as expected.
```
try {
      $oldCulture = [System.Globalization.CultureInfo]::CurrentCulture
      [System.Globalization.CultureInfo]::CurrentCulture = [System.Globalization.CultureInfo]::new('en-US-POSIX')
      [string]::Equals("a", "A", [System.StringComparison]::CurrentCultureIgnoreCase)
}
finally {
     [System.Globalization.CultureInfo]::CurrentCulture = $oldCulture
}
```
