### PR TITLE
Fix class searcher to ignore hidden properties

### LINKED ISSUE #7187: `Get-Help -Category Class` results in unhandled exception
This is a regression from 6.1-Preview.3.  Doesn't repro unless you have a module with a class that has hidden members.  Test module PSSysLog is such a module.

Steps to reproduce
------------------

```powershell
Import-Module build.psm1
Get-Help -Category Class
```

Expected behavior
-----------------

```none
Nothing returned
```

Actual behavior
---------------

Release build
```none
get-help : Object reference not set to an instance of an object.
At line:1 char:1
+ get-help -Category Class
+ ~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Get-Help], NullReferenceException
+ FullyQualifiedErrorId :System.NullReferenceException,Microsoft.PowerShell.Commands.GetHelpCommand
```

Debug build
```none
Assertion Failed                                                                                                                                                                                                                            PropertyType cannot be null                                                                                                                                                                                                                                                                                                                                                                                                                                                                at System.Management.Automation.Diagnostics.Assert(Boolean condition, String whyThisShouldNeverHappen, String detailMessage) in /Users/steve/repos/PowerShell/src/System.Management.Automation/utils/assert.cs:line 195                     at System.Management.Automation.Diagnostics.Assert(Boolean condition, String whyThisShouldNeverHappen) in /Users/steve/repos/PowerShell/src/System.Management.Automation/utils/assert.cs:line 130                                        
   at System.Management.Automation.PSClassSearcher.ConvertToClassInfo(PSModuleInfo module, ScriptBlockAst ast, TypeDefinitionAst statement) in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/PSClassSearcher.cs:line 303
   at System.Management.Automation.PSClassSearcher.CachedItemToPSClassInfo(WildcardPattern classNameMatcher, String modulePath) in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/PSClassSearcher.cs:line 238
   at System.Management.Automation.PSClassSearcher.FindTypeByModulePath(WildcardPattern classNameMatcher) in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/PSClassSearcher.cs:line 188
   at System.Management.Automation.PSClassSearcher.GetNextClass() in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/PSClassSearcher.cs:line 138
   at System.Management.Automation.PSClassSearcher.MoveNext() in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/PSClassSearcher.cs:line 90
   at System.Management.Automation.PSClassHelpProvider.GetHelpInfo(PSClassSearcher searcher)+MoveNext() in /Users/steve/repos/PowerShell/src/System.Management.Automation/help/PSClassHelpProvider.cs:line 132
   at System.Management.Automation.PSClassHelpProvider.SearchHelp(HelpRequest helpRequest, Boolean searchOnlyContent)+MoveNext() in /Users/steve/repos/PowerShell/src/System.Management.Automation/help/PSClassHelpProvider.cs:line 89
   at System.Management.Automation.HelpSystem.SearchHelp(HelpRequest helpRequest)+MoveNext() in /Users/steve/repos/PowerShell/src/System.Management.Automation/help/HelpSystem.cs:line 497
   at System.Management.Automation.HelpSystem.DoGetHelp(HelpRequest helpRequest)+MoveNext() in /Users/steve/repos/PowerShell/src/System.Management.Automation/help/HelpSystem.cs:line 318
   at Microsoft.PowerShell.Commands.GetHelpCommand.ProcessRecord() in /Users/steve/repos/PowerShell/src/System.Management.Automation/help/HelpCommands.cs:line 278
   at System.Management.Automation.Cmdlet.DoProcessRecord() in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/cmdlet.cs:line 172
   at System.Management.Automation.CommandProcessor.ProcessRecord() in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/CommandProcessor.cs:line 358
   at System.Management.Automation.CommandProcessorBase.DoExecute() in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/CommandProcessorBase.cs:line 539
   at System.Management.Automation.Internal.PipelineProcessor.Inject(Object input, Boolean enumerate) in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/pipeline.cs:line 1159
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input) in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/pipeline.cs:line 499
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext) in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs:line 454
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame) in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/interpreter/CallInstruction.Generated.cs:line 566
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/interpreter/ControlFlowInstructions.cs:line 356
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/interpreter/ControlFlowInstructions.cs:line 356
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame) in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/interpreter/Interpreter.cs:line 111
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0) in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/interpreter/LightLambda.Generated.cs:line 77
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess) in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/ScriptCommandProcessor.cs:line 515
   at System.Management.Automation.DlrScriptCommandProcessor.Complete() in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/ScriptCommandProcessor.cs:line 416
   at System.Management.Automation.CommandProcessorBase.DoComplete() in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/CommandProcessorBase.cs:line 613
   at System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(CommandProcessorBase commandRequestingUpstreamCommandsToStop) in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/pipeline.cs:line 606
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input) in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/pipeline.cs:line 518
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper() in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs:line 377
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc() in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs:line 573
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc() in /Users/steve/repos/PowerShell/src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs:line 1254
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

Environment data
----------------

<!-- provide the output of $PSVersionTable -->

```powershell
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.3
PSEdition                      Core
GitCommitId                    v6.1.0-preview.3-47-ge8d2a6b27827dd366f638468f96487ddf2de1db4
OS                             Darwin 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
## PR Summary

The ConvertToClassInfo method attempts to convert a PowerShell class into a PSClassInfo.  When it encounters a hidden property, it fails as the `PropertyType` member is null.  Fix is to ignore hidden members to allow it to succeed.

Looks like the bug has always been there, but exposed by https://github.com/PowerShell/PowerShell/pull/6025

Fix https://github.com/PowerShell/PowerShell/issues/7187

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

File: src/System.Management.Automation/engine/PSClassSearcher.cs [hunk 1]
```diff
@@ -297,7 +297,7 @@ private PSClassInfo ConvertToClassInfo(PSModuleInfo module, ScriptBlockAst ast,
             foreach (var member in statement.Members)
             {
                 PropertyMemberAst propAst = member as PropertyMemberAst;
-                if (propAst != null)
+                if (propAst != null && (propAst.PropertyAttributes & PropertyAttributes.Hidden) != PropertyAttributes.Hidden)
```
Comment (BrucePay) [inline src/System.Management.Automation/engine/PSClassSearcher.cs]: Perhaps use 'is' :  `if (member is PropertyMemberAst propAst && (propAst.PropertyAttributes & PropertyAttributes.Hidden) != PropertyAttributes.Hidden)`

**Review by BrucePay — APPROVED** [review]
LGTM

**Review by BrucePay — APPROVED** [review]

File: test/powershell/engine/Help/HelpSystem.Tests.ps1 [hunk 2]
```diff
@@ -309,6 +309,10 @@ Describe "Get-Help should find pattern help files" -Tags "CI" {
         )
         $command.Invoke() | Should -Be $result
     }
+
+    It "Get-Help should not fail searching for class help" {
+        Get-Help -Category Class | Should -BeNullOrEmpty
```
Comment (iSazonov) [inline test/powershell/engine/Help/HelpSystem.Tests.ps1]: The test can take a very long time. Can we use `-Name` parameter?

File: src/System.Management.Automation/engine/PSClassSearcher.cs [hunk 3]
```diff
@@ -296,8 +296,7 @@ private PSClassInfo ConvertToClassInfo(PSModuleInfo module, ScriptBlockAst ast,
 
             foreach (var member in statement.Members)
             {
-                PropertyMemberAst propAst = member as PropertyMemberAst;
-                if (propAst != null)
+                if (member is PropertyMemberAst propAst && (propAst.PropertyAttributes & PropertyAttributes.Hidden) != PropertyAttributes.Hidden)
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/PSClassSearcher.cs]: > (propAst.PropertyAttributes & PropertyAttributes.Hidden) != PropertyAttributes.Hidden

This can be changed to `!propAst.PropertyAttributes.HasFlag(PropertyAttributes.Hidden)`. The perf issue with `HasFlag` is fixed in 2.1

File: test/powershell/engine/Help/HelpSystem.Tests.ps1 (hunk 2 above)
Comment (SteveL-MSFT) [reply test/powershell/engine/Help/HelpSystem.Tests.ps1]: Because we don't ship any script classes, this operation doesn't take very long.  It's only hit when the test modules are in your PSModulePath specifically the PSLogItem class.  If you run this test directly w/o using build.psm1 which adds the test modules to your path, this test will fail as it wouldn't find `PSLogItem` class.  I think for now we can just leave it as-is.

Comment (iSazonov) [reply test/powershell/engine/Help/HelpSystem.Tests.ps1]: Maybe add a class in the test to exclude problems in future? 
I run on Windows PowerShell - it is very long.

Comment (SteveL-MSFT) [reply test/powershell/engine/Help/HelpSystem.Tests.ps1]: @iSazonov that's a reasonable request.  I was testing on macOS and it's pretty fast.

File: test/powershell/engine/Help/HelpSystem.Tests.ps1 [hunk 4]
```diff
@@ -309,6 +317,22 @@ Describe "Get-Help should find pattern help files" -Tags "CI" {
...
+    It "Get-Help should fail expectedly searching for class help with hidden members" {
+        $testModule = @'
+        class foo
+        {
+            hidden static $monthNames = @('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun','Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')
+        }
+'@
+        $modulesFolder = Join-Path $TestDrive "Modules"
+        $modulePath = Join-Path $modulesFolder "TestModule"
+        New-Item -ItemType Directory -Path $modulePath -Force
```
Comment (adityapatwardhan) [inline test/powershell/engine/Help/HelpSystem.Tests.ps1]: `> $null`

File: test/powershell/engine/Help/HelpSystem.Tests.ps1 [hunk 5]
```diff
@@ -309,6 +317,22 @@ Describe "Get-Help should find pattern help files" -Tags "CI" {
...
     }
+
+    It "Get-Help should fail expectedly searching for class help with hidden members" {
+        $testModule = @'
+        class foo
+        {
+            hidden static $monthNames = @('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun','Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')
+        }
+'@
+        $modulesFolder = Join-Path $TestDrive "Modules"
```
Comment (adityapatwardhan) [inline test/powershell/engine/Help/HelpSystem.Tests.ps1]: Maybe use `-AdditionalChildPath` instead of two `Join-Path`

**Review by adityapatwardhan — CHANGES_REQUESTED** [review]

File: test/powershell/engine/Help/HelpSystem.Tests.ps1 (hunk 5 above)
Comment (SteveL-MSFT) [reply test/powershell/engine/Help/HelpSystem.Tests.ps1]: `$modulesFolder` and `$modulePath` are used independently

**Review by daxian-dbw — APPROVED** [review]

**Review by adityapatwardhan — APPROVED** [review]
