### PR TITLE
Fix issue with incomplete results when completing paths with wildcards in non-filesystem providers

### LINKED ISSUE #24756: Wildcard completions in non-filesystem providers return incomplete results
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Using this code as an example:
```
$keys = New-Item -Path @(
                'HKCU:\AB1'
                'HKCU:\AB2'
                'HKCU:\AB2\Test'
            )
$res = TabExpansion2 -inputScript 'Get-ChildItem -Path HKCU:\AB?\'
```
You'd expect to see `'HKCU:\AB2\Test'` in the results but it's not there. This is because of an early return in the completion code that skips evaluating the completions for other resolved paths, if any of the previous ones contains no items.

### Expected behavior

```console
Results should include `'HKCU:\AB2\Test'`
```

### Actual behavior

```console
Results are empty.
```

### Error details

_No response_

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.5.0-rc.1
PSEdition                      Core
GitCommitId                    7.5.0-rc.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by MartinGC94**
# PR Summary
Replaces an early return with a continue so the completion code continues to evaluate other resolved paths when encountering an empty path.
This resolves scenarios like:
```
$keys = New-Item -Path @(
                'HKCU:\AB1'
                'HKCU:\AB2'
                'HKCU:\AB2\Test'
            )
$res = TabExpansion2 -inputScript 'Get-ChildItem -Path HKCU:\AB?\'
```

where you wouldn't get `HKCU:\AB2\Test` in the results because AB1 is empty.

## PR Context
Fixes: https://github.com/PowerShell/PowerShell/issues/24756

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
  - [X] None
  - **OR**
  - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
    - [ ] Experimental feature name(s): 
- **User-facing changes**
  - [X] Not Applicable
  - **OR**
  - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
  - [ ] N/A or can only be tested interactively
  - **OR**
  - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
  - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
  - **OR**
  - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
    - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
      - [ ] Issue filed: 
    - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
      - [ ] Issue filed: 
    - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
      - [ ] Issue filed: 
    - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
      - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs [hunk 1]
```diff
@@ -4869,7 +4869,7 @@ private static List<CompletionResult> GetDefaultProviderResults(
 
                 if (childNameList.Count == 0)
                 {
-                    return results;
+                    continue;
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:4872]: Does the code path work for FileSystem provider? Has it the issue too?

Comment (MartinGC94) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:4872]: No. There's 2 separate provider completer methods: One for the filesystem provider, and a generic one for the others. I only made this mistake in the generic one.

File: test/powershell/Host/TabCompletion/BugFix.Tests.ps1 [hunk 2]
```diff
@@ -43,6 +43,28 @@ Describe "Tab completion bug fix" -Tags "CI" {
...
+
+            $res = TabExpansion2 -inputScript 'Get-ChildItem -Path HKCU:\AB?\'
+            $res.CompletionMatches.Count | Should -Be 1
+            $res.CompletionMatches[0].CompletionText | Should -BeExactly "HKCU:\AB2\Test"
+        }
+        finally
+        {
+            if ($keys)
+            {
+                Remove-Item -Path HKCU:\AB? -Recurse
```
Comment (iSazonov) [inline test/powershell/Host/TabCompletion/BugFix.Tests.ps1:63]:
```suggestion
                Remove-Item -Path HKCU:\AB? -Recurse -ErrorAction SilentlyContinue
```

**Comment by iSazonov** [comment]
@vexx32 Is anything you want to discuss with WG or we can merge?

**Comment by vexx32** [comment]
As long as you're happy with the tests and behaviour after the fix, I think this is okay to merge, myself. Just wanted to make sure it got a review.

**Review by iSazonov — APPROVED** [review]
