### PR TITLE
Remove use of `Test-Path` in ConciseView

### LINKED ISSUE #12671: `$ErrorView = "ConciseView"` does not print any errors with module autoloading disabled
PowerShell Core version: v7.0.1

# Steps to reproduce
Run the following lines in `pwsh -noprofile`:
```PowerShell
$PSModuleAutoLoadingPreference = "None"
$ErrorView = "ConciseView"
NonExistentCmdlet
$ErrorView = "NormalView"
NonExistentCmdlet
$ErrorView = "ConciseView"
NonExistentCmdlet
```

# Expected behavior
3 error messages are thrown, 1st and 3rd one formatted as concise error messages, 2nd one as normal error message.

# Actual behavior
When `$ErrorView` is set to `"ConciseView"`, the errors are silently ignored and nothing is displayed. `"NormalView"` works correctly.
image

When running with `Set-PSDebug -Trace 2`, the following output is displayed:
image

The output indicates that while printing output, the ConciseView error printing code uses `Test-Path`, which is not loaded because of the disabled auto-loading.

Then, I attempted to first run `Import-Module Microsoft.PowerShell.Management`, which contains the `Test-Path` cmdlet. After the import, with auto-loading still disabled, errors now correctly print in ConciseView.

**This leads me to believe that the issue is in `Get-ConciseViewPositionMessage` function attempting to use `Test-Path`, which is unavailable due to disabled auto-loading.**

# Environment data

PowerShell Core:
```none
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

Both `ConciseView` and `Get-Error` used `Test-Path` which wouldn't be available if `$PSModuleAutoLoadingPreference` is set to `none`.  Fix is to simply check against `$null` instead of using that cmdlet.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/12671

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs [hunk 1]
```diff
@@ -766,14 +766,14 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_System_Management_Autom
                             $maxDepth = 10
```
Comment (PoshChan) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:766]: @SteveL-MSFT, your last commit had 1 failures in `PowerShell-CI-macos`
Tests for $ErrorView.ConciseView tests.Error shows if $PSModuleAutoLoadingPreference is set to 'none'
```powershell
Expected like wildcard '*cmdletThatDoesntExist*' to match <empty>, but it did not match.
at <ScriptBlock>, /Users/runner/runners/2.168.2/work/1/s/test/powershell/engine/Formatting/ErrorView.Tests.ps1: line 111
111:             $e | Should -BeLike "*cmdletThatDoesntExist*"
```

Comment (PoshChan) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:766]: @SteveL-MSFT, your last commit had 1 failures in `PowerShell-CI-linux`
Tests for $ErrorView.ConciseView tests.Error shows if $PSModuleAutoLoadingPreference is set to 'none'
```powershell
Expected like wildcard '*cmdletThatDoesntExist*' to match <empty>, but it did not match.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/engine/Formatting/ErrorView.Tests.ps1: line 111
111:             $e | Should -BeLike "*cmdletThatDoesntExist*"
```

Comment (PoshChan) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:766]: @SteveL-MSFT, your last commit had 1 failures in `PowerShell-CI-windows`
Tests for $ErrorView.ConciseView tests.Error shows if $PSModuleAutoLoadingPreference is set to 'none'
```powershell
Expected like wildcard '*cmdletThatDoesntExist*' to match <empty>, but it did not match.
at <ScriptBlock>, D:\a\1\s\test\powershell\engine\Formatting\ErrorView.Tests.ps1: line 111
111:             $e | Should -BeLike "*cmdletThatDoesntExist*"
```

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs [hunk 2]
```diff
@@ -766,14 +766,14 @@ private static IEnumerable<FormatViewDefinition> ViewsOf_System_Management_Autom
...
                             $ellipsis = ""`u{2026}""
                             $resetColor = ''
-                            if ($Host.UI.SupportsVirtualTerminal -and !(Test-Path env:__SuppressAnsiEscapeSequences)) {
+                            if ($Host.UI.SupportsVirtualTerminal -and ($null -eq $env:__SuppressAnsiEscapeSequences)) {
```
Comment (vexx32) [inline src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:769]: I think the `env:` provider will return empty strings rather than null if a value doesn't exist (in the same way, setting an env var to `[string]::Empty`/`""` will remove it in the .NET API for `SetEnvironmentVariable()`).

Probably safest to use `[string]::IsNullOrEmpty()` for these.

**Comment by iSazonov** [comment]
@SteveL-MSFT Please look CI failures.

**Comment by iSazonov** [comment]
@SteveL-MSFT Could you please fix CIs?

File: src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs (hunk 2 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs:769]: will update

File: 1 [hunk 3]
```diff
@@ -0,0 +1,6 @@
+[91mParserError: 
+[96mLine |
+[96m   1 | [0m foreach[96m [0mabc
+[96m     | [91m        ~
+[91m[96m     | [91mMissing opening '(' after keyword 'foreach'.
+[0m
```
Comment (vexx32) [inline 1:6]: stray file? ^^

Comment (SteveL-MSFT) [reply 1:6]: yeah, I'll remove

File: test/powershell/engine/Formatting/ErrorView.Tests.ps1 [hunk 4]
```diff
@@ -102,12 +102,13 @@ Describe 'Tests for $ErrorView' -Tag CI {
...
 
-            $e = & "$PSHOME/pwsh" -noprofile -command "foreach abc" | Out-String
+            $e = & "$PSHOME/pwsh" -noprofile -command "foreach abc" 2>&1 | out-string
+            $e | Should -Not -BeNullOrEmpty
             $e | Should -Not -BeLike "*At line*"
         }
 
         It "Error shows if `$PSModuleAutoLoadingPreference is set to 'none'" {
-            $e = & "$PSHOME/pwsh" -noprofile -command '$PSModuleAutoLoadingPreference = ""none""; cmdletThatDoesntExist' | Out-String
+            $e = & "$PSHOME/pwsh" -noprofile -command '$PSModuleAutoLoadingPreference = ""none""; cmdletThatDoesntExist' 2>&1 | out-string
```
Comment (iSazonov) [inline test/powershell/engine/Formatting/ErrorView.Tests.ps1:111]:
```suggestion
            $e = & "$PSHOME/pwsh" -noprofile -command '$PSModuleAutoLoadingPreference = ""none""; cmdletThatDoesntExist' 2>&1 | Out-String
```

File: test/powershell/engine/Formatting/ErrorView.Tests.ps1 [hunk 5]
```diff
@@ -102,9 +102,15 @@ Describe 'Tests for $ErrorView' -Tag CI {
 
         It "Position message does not contain line information" {
 
-            $e = & "$PSHOME/pwsh" -noprofile -command "foreach abc" | Out-String
+            $e = & "$PSHOME/pwsh" -noprofile -command "foreach abc" 2>&1 | out-string
```
Comment (iSazonov) [inline test/powershell/engine/Formatting/ErrorView.Tests.ps1:105]:
```suggestion
            $e = & "$PSHOME/pwsh" -noprofile -command "foreach abc" 2>&1 | Out-String
```

**Review by iSazonov — APPROVED** [review]
