### PR TITLE
Make New-Item -Force overwrite on Junction

### LINKED ISSUE #17656: New-Item -Force does not have expected behavior for all types
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [x] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Issue is `-Force` does not seem to understand junctions. It thinks they are directories and fails to remove them because they are not empty.

Works fine with file types. (see screenshot)

Most types including registry entries allow `-Force` to overwrite the item. Logically `-Force` should do the same for a Junction.

Due to `-Force` not working you must first `Remove-Item` prior to `New-Item`, which works perfectly fine.  `Remove-Item` simply removes the junction and does not complain that it is not empty.  `New-Item -Force` needs the same intelligence.

### Expected behavior

```console
PS> New-Item MyWindows -Type Junction -Value C:\Windows\
PS> New-Item MyWindows -Type Junction -Value C:\Windows\ -Force
PS>
```

### Actual behavior

```console
PS> New-Item MyWindows -Type Junction -Value C:\Windows\
PS> New-Item MyWindows -Type Junction -Value C:\Windows\ -Force
New-Item: Directory C:\Temp\MyWindows cannot be removed because it is not empty.
PS>
```

### Error details

```console
Exception             :
    Type    : System.IO.IOException
    Message : Directory C:\Temp\MyWindows cannot be removed because it is not empty.
    HResult : -2146232800
TargetObject          : C:\Temp\MyWindows
CategoryInfo          : WriteError: (C:\Temp\MyWindows:String) [New-Item], IOException
FullyQualifiedErrorId : DirectoryNotEmpty,Microsoft.PowerShell.Commands.NewItemCommand
InvocationInfo        :
    MyCommand        : New-Item
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 5
    Line             : New-Item MyWindows -Type Junction -Value C:\Windows\ -Force
    PositionMessage  : At line:1 char:1
                       + New-Item MyWindows -Type Junction -Value C:\Windows\ -Force
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : New-Item
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

image

### PR DESCRIPTION
**Pull request by GigaScratch**
# PR Summary
When performing `New-Item <itemname> -Type Junction -Value <path> -Force`, it will fail with `"<path> cannot be removed because it is not empty."`. 

This has been resolved by moving the Child Item check from before force is checked, to the else condition of the force check.

## PR Context
This PR aims to fix #17656.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by GigaScratch** [comment]
Making this WIP as my build environment is unhappy so I'll be testing off the build artifact. 😅

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 1]
```diff
@@ -2656,9 +2648,19 @@ public static string LastWriteTimeString(PSObject instance)
...
+                            {
+                                string message = StringUtil.Format(FileSystemProviderStrings.DirectoryNotEmpty, path);
+                                WriteError(new ErrorRecord(new IOException(message), "DirectoryNotEmpty", ErrorCategory.WriteError, path));
+                                return;
+                            }
+                        }
                     }
                     else
-                    {
+                    {
```
Comment (GigaScratch) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:2663]: Does the PR merge config squash line trails?

**Comment by iSazonov** [comment]
You could look
`Describe "Hard link and symbolic link tests" -Tags "CI", "RequireAdminOnWindows"` 
in FileSystem.Tests.ps1

**Comment by GigaScratch** [comment]
> Please add a test.

I added a simple overwrite test, but ideally I would like a way to verify that the object created is actually new and to throw an error if it is not.
 In a FAT32 or EXFAT FS I would just compare the creation date by epoch, but afaik Windows doesn't store the milliseconds in item creation 😐. Is there a way you would recommend to compare the first and second junction to verify the second is actually new?

**Comment by iSazonov** [comment]
You could use another target in second New-Item and check that target is changed after first command.

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 [hunk 2]
```diff
@@ -601,8 +603,12 @@ Describe "Hard link and symbolic link tests" -Tags "CI", "RequireAdminOnWindows"
             Test-Path $junctionToDir | Should -BeTrue
         }
         It "New-Item -Force can overwrite a junction" -Skip:(-Not $IsWindows){
+            $rd2 = Get-Item -Path $realDir2
             New-Item -ItemType Junction -Path $junctionToDir -Value $realDir > $null -Force
-            New-Item -ItemType Junction -Path $junctionToDir -Value $realDir > $null -Force
+            New-Item -ItemType Junction -Path $junctionToDir -Value $realDir2 > $null -Force
+            $Junction = Get-Item -Path $junctionToDir
+            $Junction.Target | Should -BeExactly $rd2.ToString()
+
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1:611]: I'd add one more check if no force parameter (please replace "????,Microsoft.PowerShell.Commands.NewItemCommand" with real value):
```suggestion
            { New-Item -ItemType Junction -Path $junctionToDir -Value $realDir2 > $null } | Should -Throw -ErrorId "????,Microsoft.PowerShell.Commands.NewItemCommand"
            New-Item -ItemType Junction -Path $junctionToDir -Value $realDir2 > $null -Force
            $Junction = Get-Item -Path $junctionToDir
            $Junction.Target | Should -BeExactly $rd2.ToString()
```

**Review by iSazonov — CHANGES_REQUESTED** [review]

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 3]
```diff
@@ -2627,19 +2627,13 @@ public static string LastWriteTimeString(PSObject instance)
...
-                            return;
-                        }
-
                         if (Force)
                         {
                             try
                             {
                                 pathDirInfo.Delete();
+                                CreateDirectory(path, false);
+                                pathDirInfo = new DirectoryInfo(path);
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:2636]: Formally we can catch a race condition if `pathDirInfo.Delete()` throws.
I think it is better to move the new two line after the `try-catch` block.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 4]
```diff
@@ -2655,6 +2647,18 @@ public static string LastWriteTimeString(PSObject instance)
                                     throw;
                                 }
                             }
+                            CreateDirectory(path, false);
+                            pathDirInfo = new DirectoryInfo(path);
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:2651]:
```suggestion

                            CreateDirectory(path, false);
                            pathDirInfo = new DirectoryInfo(path);
```

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 [hunk 5]
```diff
@@ -600,6 +602,15 @@ Describe "Hard link and symbolic link tests" -Tags "CI", "RequireAdminOnWindows"
             New-Item -ItemType Junction -Path $junctionToDir -Value $realDir > $null
             Test-Path $junctionToDir | Should -BeTrue
         }
+        It "New-Item -Force can overwrite a junction" -Skip:(-Not $IsWindows){
+            $rd2 = Get-Item -Path $realDir2
+            New-Item -Name testfile.txt -ItemType file -Path $realDir
+            New-Item -ItemType Junction -Path $junctionToDir -Value $realDir > $null
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1:608]: I wonder why we create the `testfile.txt`?

Comment (GigaScratch) [reply test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1:608]: so there are contents of the directory, the error on no force only appears that way.

Comment (GigaScratch) [reply test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1:608]: Actually I can't get the error to throw in the test.  Even though I can recreate it locally. Can you see anything wrong? I think the folder structure in my screenshot should be the same as the mock in the test context... 😕
image

Comment (iSazonov) [reply test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1:608]: Locally you create the file in second folder, in CI test - in first one.

Comment (GigaScratch) [reply test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1:608]: image
I don't think that is right. 
`$junctionToDir` will point to contents of `$realDir` on the first two runs, and testfile.txt is inside $realDir?

Comment (iSazonov) [reply test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1:608]: In the case are you sure you use right build locally?

Comment (GigaScratch) [reply test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1:608]: Yes, I downloaded it from the PR artifact here - https://dev.azure.com/powershell/PowerShell/_build/results?buildId=111574&view=artifacts&pathAsName=false&type=publishedArtifacts

Comment (iSazonov) [reply test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1:608]: It is side effect from previous test where the junction was already created. I think we should remove the juction in previous test.

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 [hunk 6]
```diff
@@ -596,9 +598,14 @@ Describe "Hard link and symbolic link tests" -Tags "CI", "RequireAdminOnWindows"
             $link.LinkType | Should -BeExactly "SymbolicLink"
             $link.Target | Should -BeExactly $real.ToString()
         }
-        It "New-Item can create a directory junction to a directory" -Skip:(-Not $IsWindows) {
+        It "New-Item -Force can overwrite a junction" -Skip:(-Not $IsWindows){
+            $rd2 = Get-Item -Path $realDir2
+            New-Item -Name testfile.txt -ItemType file -Path $realDir
             New-Item -ItemType Junction -Path $junctionToDir -Value $realDir > $null
-            Test-Path $junctionToDir | Should -BeTrue
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1:601]: I think we should keep the line in new test.

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 (hunk 5 above)
Comment (GigaScratch) [reply test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1]: Unfortunately that wasn't the issue I think. 
https://dev.azure.com/powershell/PowerShell/_build/results?buildId=111582&view=ms.vss-test-web.build-test-results-tab&runId=1957440&resultId=100074&paneView=debug

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 [hunk 7]
```diff
@@ -596,9 +598,14 @@ Describe "Hard link and symbolic link tests" -Tags "CI", "RequireAdminOnWindows"
...
+            { New-Item -ItemType Junction -Path $junctionToDir -Value $realDir > $null } | Should -Throw -ErrorId "DirectoryNotEmpty,Microsoft.PowerShell.Commands.NewItemCommand"
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1:605]:
```suggestion
            { New-Item -ItemType Junction -Path $junctionToDir -Value $realDir > $null -ErrorAction Stop} | Should -Throw -ErrorId "DirectoryNotEmpty,Microsoft.PowerShell.Commands.NewItemCommand"
```

**Comment by GigaScratch** [comment]
@microsoft-github-policy-service agree [company=""]

**Comment by GigaScratch** [comment]
@microsoft-github-policy-service agree

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 (hunk 7 above)
Comment (GigaScratch) [reply test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1]: Thank you! I thought that would stop the entire test so I didn't add it 😅

**Review by iSazonov — APPROVED** [review]

**Review by daxian-dbw — APPROVED** [review]
LGTM. Made a quick fix and rebased the branch.
