### PR TITLE
Turn on and off DECCKM to modify keyboard mode for unix native commands to work correctly

### LINKED ISSUE #12268: Linux pwsh enables DECCKM, but Windows pwsh cannot handle it; arrow keys stop working after exiting linux powershell
# Steps to reproduce

1. Use Windows PowerShell 7 and PowerShell 7 in WSL.
2. Launch Windows Powershell in Windows Terminal
3. Launch wsl, `pwsh`
4. Exit Linux powershell
5. Observe the arrow keys

Linux powershell emits the escape sequence `DECSET` `DECCKM`[1] on startup before it emits the first prompt.

This reconfigures the cursor keys, which usually emit `CSI A...D`, to emit `SS3 A...D` instead.

Linux powershell can handle `SS3` arrow key sequences. This is fine.

When Linux powershell exits, it _does not restore `DECCKM` to its original state_. All applications that manipulate global terminal state are expected to return the terminal to "normal" once they are done.

Because the state is not restored when you exit Linux powershell, Windows powershell (which doesn't know that the terminal state has been changed) will start to receive `SS3` arrow key sequences.

Windows powershell _cannot_ handle `SS3` arrow key sequences, and it ignores them, so the arrow keys do not work.

This also reproduces when you SSH to a linux machine, but WSL is easier for a self-contained repro.

# Expected behavior

`DECCKM` is disabled on exit.

# Actual behavior

`DECCKM` remains enabled on exit, downstream applications get confused.

# Environment data

```none
(dhowett-sl) ~ % $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

(dhowett-sl) ~ % wsl pwsh -c '\$PSVersionTable'

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Linux 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

[1] Notes about DECCKM

```
CSI ? Pm h
          DEC Private Mode Set (DECSET).
            Ps = 1  ⇒  Application Cursor Keys (DECCKM), VT100.
```

DECCKM reconfigures the arrow keys as follows

```
Key            Normal     Application
-------------+----------+-------------
Cursor Up    | CSI A    | SS3 A
Cursor Down  | CSI B    | SS3 B
Cursor Right | CSI C    | SS3 C
Cursor Left  | CSI D    | SS3 D
-------------+----------+-------------
```

[2] I've investigated PowerShell, PSReadline and dotnet/runtime, and I cannot determine where DECCKM is being enabled.

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

Dotnet runtime sets keyboard mode to application on Unix systems and does not currently reset on exit.  This change emits the DECRTS 1 sequence on pwsh exit on Unix systems (if VT is supported and interactive) to put keyboard mode back to default so that arrow keys do not emit escape sequences.

In the case of an interactive shell, we turn on DECCKM before showing prompt and turn if off before execution.  This follows what zsh does.

Validated manually with `gh auth login` works with these changes and fails without.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/12268

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by iSazonov** [comment]
It is not full fix for #12268 
We need to address external applications run. See https://github.com/PowerShell/PowerShell/issues/12268#issuecomment-761724502

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs [hunk 1]
```diff
@@ -254,6 +254,11 @@ internal static int Start(string bannerText, string helpText)
                 {
 #if LEGACYTELEMETRY
                     TelemetryAPI.ReportExitTelemetry(s_theConsoleHost);
+#endif
+#if UNIX
+                    // https://github.com/dotnet/runtime/issues/27626 leaves terminal in application mode
+                    // for now, we explicitly emit DECRST 1 sequence
+                    s_theConsoleHost.UI.Write("\x1b[?1l");
```
Comment (iSazonov) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs:261]: Should we check VT mode?

Comment (SteveL-MSFT) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs:261]: Yes, also it seems that we should only emit for interactive

**Comment by SteveL-MSFT** [comment]
I'll update to set and reset in the native command processor

**Comment by iSazonov** [comment]
Start-Process?

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs (hunk 1 above)
Comment (SteveL-MSFT) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs:261]: if `pwsh -noninteractive` is used, we should not emit as it gets added to the output which is what causes the build to fail

**Comment by SteveL-MSFT** [comment]
@iSazonov it seems that if we follow zsh, then the set/reset should be in console host repl loop and not in native command processor nor start-process.

**Comment by iSazonov** [comment]
1. Why do we only Unix fix if the issue was reported as Windows bug?
2. I still think we could safely skip `s_theConsoleHost.IsInteractive` check.

**Comment by SteveL-MSFT** [comment]
@iSazonov it's not a Windows bug, it was WSL.  .NET on Windows doesn't use ANSI escape sequences for keyboard input.  As for why check for interactive, the problem is that if you do something like: `pwsh -command 1`, then you get back `1ESC[?1l` as the output from that command.  Even if you don't explicitly use `-noninteractive` the console host knows that `-command` without `-noexit` is non-interactive so we don't want to emit the ESC sequence that will be part of the stdout output.

**Review by iSazonov — APPROVED** [review]

**Review by adityapatwardhan — APPROVED** [review]
