### PR TITLE
Skip compiling the non-supported cmdlets in System.Management.Automation.dll

### LINKED ISSUE #6886: Assertion failure in master: "new Cmdlet added to System.Management.Automation.dll - update InitializeCoreCmdletsAndProviders"
Running PowerShell from `master` on Ubuntu 18.04.

Looks like a new cmdlet has been added to PowerShell and [InitializeCoreCmdletsAndProviders](https://github.com/PowerShell/PowerShell/blob/4e3db1bb93b17228752de9e3e99f89defbdc01b0/src/System.Management.Automation/engine/InitialSessionState.cs#L5334) has not been updated?

Not sure if this is just me -- may need someone else to reproduce this...

Steps to reproduce
------------------
1. Clone master (commit `4e3db1bb93b17228752de9e3e99f89defbdc01b0`) on a supported UNIX-like.
1. Build in `Debug` configuration.
1. Execute the generated PowerShell binary.

Expected behavior
-----------------
PowerShell starts and presents a prompt.

Actual behavior
---------------

```none
PS /home/rob/Documents/Dev/Microsoft/PowerShell> ./src/powershell-unix/bin/Debug/netcoreapp2.1/linux-x64/publish/pwsh                                                                                     
Assertion Failed
new Cmdlet added to System.Management.Automation.dll - update InitializeCoreCmdletsAndProviders

   at System.Management.Automation.Diagnostics.Assert(Boolean condition, String whyThisShouldNeverHappen, String detailMessage) in /home/rob/Documents/Dev/Microsoft/PowerShell/src/System.Management.Automation/utils/assert.cs:line 195
   at System.Management.Automation.Diagnostics.Assert(Boolean condition, String whyThisShouldNeverHappen) in /home/rob/Documents/Dev/Microsoft/PowerShell/src/System.Management.Automation/utils/assert.cs:line 130
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Boolean isModuleLoad, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& helpFile) in /home/rob/Documents/Dev/Microsoft/PowerShell/src/System.Management.Automation/engine/InitialSessionState.cs:line 5113
   at System.Management.Automation.Runspaces.InitialSessionState.ImportPSSnapIn(PSSnapInInfo psSnapInInfo, PSSnapInException& warning) in /home/rob/Documents/Dev/Microsoft/PowerShell/src/System.Management.Automation/engine/InitialSessionState.cs:line 3766
   at System.Management.Automation.Runspaces.InitialSessionState.ImportCorePSSnapIn() in /home/rob/Documents/Dev/Microsoft/PowerShell/src/System.Management.Automation/engine/InitialSessionState.cs:line 3691
   at System.Management.Automation.Runspaces.InitialSessionState.CreateDefault2() in /home/rob/Documents/Dev/Microsoft/PowerShell/src/System.Management.Automation/engine/InitialSessionState.cs:line 1609
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String consoleFilePath, String[] args, Int32 argc) in /home/rob/Documents/Dev/Microsoft/PowerShell/src/Microsoft.PowerShell.ConsoleHost/host/msh/ManagedEntrance.cs:line 62
   at Microsoft.PowerShell.ManagedPSEntry.Main(String[] args) in /home/rob/Documents/Dev/Microsoft/PowerShell/src/powershell/Program.cs:line 22
```
(Failing assertion is [here](https://github.com/PowerShell/PowerShell/blob/4e3db1bb93b17228752de9e3e99f89defbdc01b0/src/System.Management.Automation/engine/InitialSessionState.cs#L5113))

Environment data
----------------

```
PS /home/rob/Documents/Dev/Microsoft/PowerShell> uname -a                                            
Linux hyperion 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

PS /home/rob/Documents/Dev/Microsoft/PowerShell> cat /etc/os-release                                 
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### PR DESCRIPTION
**Pull request by daxian-dbw**
## PR Summary

Fix #6886 
Our configuration definition 'Linux' caused our Linux build to be unoptimized, and we didn't realize until recently. This was fixed in #6853, which makes our Linux build adopts the same configuration settings as on Windows -- debug and release.

`Start-PSBuild -Clean` on Linux starts to use the debug configuration by default, which reveals another issue on Linux build -- we use a cache in `InitialSessionState` to initialize cmdlets from S.M.A.dll in order to speed up powershell startup and items in cache drifts from actual cmdlet types available in S.M.A.dll in Unix platforms.

This is because there are some cmdlets not supported on Unix, which are if/def'ed out in the cache code, but they are still compiled in S.M.A.dll on Unix. We have some code that only runs in debug configuration to check if the cache is in sync with the real status of S.M.A.dll, but we never got to run in debug configuration because of the 'Linux' configuration we used before.

This PR skips compiling the non-supported cmdlets in S.M.A.dll, to keep the cache in InitialSessionState in sync with the actually available cmdlet types in System.Management.Automation.dll.

## Change Details

**Note that** some of the cmdlet source files contain codes that are used in other places outside the cmdlet. Those codes are moved out to `PSRemotingCmdlet.cs`, a more general place where base classes and helper classes for remoting command are located. The following type/methods are moved:
1. Class `QueryRunspaces` and enum `SessionFilterState` from `ConnectPSSession.cs`
2. Class `PSSessionOption` and enum `ProxyAccessType` from `NewPSSessionOptionCommand.cs`
3. Methods `CheckIfPowerShellVersionIsInstalled` and `CheckPSVersion` from `CustomShellCommands.cs` to class `RemotingCommandUtils` in `PSRemotingCmdlet.cs`

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [x] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

File: src/System.Management.Automation/engine/remoting/commands/NewPSSessionConfigurationFile.cs [hunk 1]
```diff
@@ -15,6 +15,7 @@
 
 namespace Microsoft.PowerShell.Commands
 {
+#if !UNIX
     /// <summary>
     /// New-PSSessionConfigurationFile command implementation
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/remoting/commands/NewPSSessionConfigurationFile.cs]: Maybe split the file by classes and exclude a new file from compile on Unix?

If we look CodeFactor issues it recommends to use one-class-per-file - if we move code in the PR maybe follow this rule?

**Review by iSazonov — COMMENTED** [review]
Leave a comment

**Comment by iSazonov** [comment]
Can we close #1998?

File: src/System.Management.Automation/engine/remoting/commands/NewPSSessionConfigurationFile.cs (hunk 1 above)
Comment (BrucePay) [reply src/System.Management.Automation/engine/remoting/commands/NewPSSessionConfigurationFile.cs]: Once-class-per-file is ridiculous. We have modern editors with all kinds of features for managing large files. I'm much happier navigating within a few files than having to deal with hundreds of tabs. I vote we suppress this rule.

**Review by BrucePay — APPROVED** [review]
LGTM

**Review by rjmholt — APPROVED** [review]
Oh no I never submitted my review before!

All looks good to me.

File: src/System.Management.Automation/engine/remoting/commands/NewPSSessionConfigurationFile.cs (hunk 1 above)
Comment (rjmholt) [reply src/System.Management.Automation/engine/remoting/commands/NewPSSessionConfigurationFile.cs]: Agree with @BrucePay in the general case of having multiple classes per file. Sometimes it's overkill to make a class nested, but it makes a lot more sense contextually to have it in the same file as a larger class. Enums are a good motivating example I find. Also, it's nice to feel like I've moved on from this historical holdover of Java and MATLAB...

Comment (iSazonov) [reply src/System.Management.Automation/engine/remoting/commands/NewPSSessionConfigurationFile.cs]: My question was only about the file. The rule wasalready disabled in PR #6930.

**Comment by iSazonov** [comment]
@daxian-dbw Please fix CI Appveyor issues.

**Comment by daxian-dbw** [comment]
@iSazonov Will fix the build today.

File: src/System.Management.Automation/engine/remoting/commands/NewPSSessionConfigurationFile.cs (hunk 1 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/remoting/commands/NewPSSessionConfigurationFile.cs]: @iSazonov The reason I was using `#if !UNIX` in this file is because the class `SessionConfigurationUtils` in this file is heavily used and only used in those two cmdlets (`New-PSSessionConfigurationFile` and `New-PSRoleCapabilityFile`), so it makes sense to keep them close to each other in the same file.

**Comment by daxian-dbw** [comment]
@iSazonov I had to rebase the branch to build. The new changes are only in the second commit.

**Comment by daxian-dbw** [comment]
`QueryRunspaces` is used in `Connect-PSSession`/`Receive-PSSession`/`Get-PSSession` and it's also directly used by the abstract class `PSRunspaceCmdlet` from `PSRemotingCmdlet.cs`, that's why I thought it probably fit in the `"Helper Classes"` region in `PSRemotingCmdlet.cs`.

I'm happy to move `QueryRunspaces` and `SessionFilterState` to a separate file, but we cannot skip compiling that file yet until all uses are properly diabled (if/def'ed out) for Unix platform. That work is out scope for this PR, as this PR is for fixing the crashing debug build on Unix platforms.

I opened the issue #7008 to track the work to properly disable all code related to session connection/disconnection for the Unix build.

**Comment by rjmholt** [comment]
I'll give this a try on my Ubuntu machine later, but it looks good to me

**Comment by iSazonov** [comment]
@rjmholt Congratulations on your first review! :-)

**Comment by rjmholt** [comment]
Tests all pass (except for 4 known problems) on Ubuntu 16.04 in Debug configuration.
