### PR TITLE
Fix running 'pwsh' produced from 'dotnet build'

### LINKED ISSUE #5783: Running 'pwsh.exe' from the parent folder of 'publish' after 'Start-PSBuild -Clean' fails
Steps to reproduce
------------------

```powershell
> Start-PSBuild -Clean
> Get-PSOptions
E:\PowerShell\src\powershell-win-core\bin\Debug\netcoreapp2.0\win7-x64\publish\pwsh.exe
## Run the 'pwsh.exe' from the parent folder of 'publish'
> E:\PowerShell\src\powershell-win-core\bin\Debug\netcoreapp2.0\win7-x64\pwsh.exe
```

Expected behavior
-----------------

Should work. I remember it used to work.

Actual behavior
---------------

```none
PowerShell v6.0.0-rc.2-76-gb057d4545d24eb152558fbc42c9c0bc65fc13273
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

The shell cannot be started. A failure occurred during initialization:
The static PrimaryRunspace property can only be set once, and has already been set.
<process-hang>
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-rc.2
PSEdition                      Core
GitCommitId                    v6.0.0-rc.2-76-gb057d4545d24eb152558fbc42c9c0bc65fc13273
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by daxian-dbw**
## PR Summary

Fix #5783
Fix running `pwsh` from the parent folder of the `publish` folder after `Start-PSBuild -Clean`. (e.g. `C:\PowerShell\src\powershell-win-core\bin\Debug\netcoreapp2.0\win7-x64`).
This also enables running `dotnet pwsh.dll` after building with `dotnet build`.

### Root Cause
1. The file `powershell.config.json` is not bin-placed to the output directory by the build, which might cause loading `PSReadline` to fail due to the execution policy.
2. `Runspace.PrimaryRunspace` was set in `OpenConsoleRunspace` before the Runspace has been successfully opened. When the first attempt to open the default Runspace fails because of the failure to load `PSReadline`, `OpenConsoleRunspace` will be called again to open the Runspace without `PSReadline`, but `Runspace.PrimaryRunspace` has already been set and thus caused the crash. The fix is to set `Runspace.PrimaryRunspace` after the default Runspace has been opened.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by PaulHigin — CHANGES_REQUESTED** [review]
Please include a small summary of what the fix did that is more than "fixed the problem". There is no mention of what the problem was and why the changes were necessary. I am guessing the output directory was missing needed information and the PrimaryRunspace was being set to a runspace that failed to open.

**Comment by daxian-dbw** [comment]
@PaulHigin The PR summary has been updated with the root cause.

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs [hunk 1]
```diff
@@ -1612,6 +1612,7 @@ private void DoCreateRunspace(string initialCommand, bool skipProfiles, bool sta
                     OpenConsoleRunspace(consoleRunspace, staMode);
                 }
 
+                Runspace.PrimaryRunspace = consoleRunspace;
```
Comment (PaulHigin) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs]: It seems like PrimaryRunspace gets set again within OpenConsoleRunspace if it fails to open the first time.  But I agree it makes more sense to set it here.

**Review by PaulHigin — APPROVED** [review]

**Review by adityapatwardhan — APPROVED** [review]

**Comment by daxian-dbw** [comment]
Closed and re-opened PR to get AppVeypr build unstuck.
