### PR TITLE
Fix Verbs<> class strings  #2716

### LINKED ISSUE #2716: Many definitions of cmdlets use 'string' instead Verbs<> class strings
Would we have to fix it?

Full list attached. [cmdletverbs.txt](https://github.com/PowerShell/PowerShell/files/599195/cmdletverbs.txt)

Samples:

Now | Must Be
-|-
`[Cmdlet("Export", "Counter",`  |  `[Cmdlet(VerbsData.Export, "Counter",`
`[Cmdlet("Invoke", "Item",`       | `[Cmdlet(VerbsLifecycle.Invoke, "Item",`

### PR DESCRIPTION
**Pull request by iSazonov**
Close #2716 

PS:
Now there is no Verbs<> consts for "Sort","Tee", "Foreach" and "Where". Whether to add them?

### CODE REVIEW

File: src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs [hunk 1]
```diff
@@ -54,7 +54,7 @@ namespace Microsoft.PowerShell.Commands
     /// Create a new runspace and use it to execute a command on a remote machine
     ///     $runspace = New-PSSession -computername "Server1"
     ///     $credential = get-credential "user01"
-    ///     invoke-command -command {get-process} �Crunspace $runspace -credential $credential
+    ///     invoke-command -command {get-process} �Crunspace $runspace -credential $credential
```
Comment (lzybkr) [inline src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs]: What is this change?

Comment (iSazonov) [inline src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs]: VS Code again catch a special character 😕 Obviously this is considered to be `-runspace`
MS VS also corrupt this.
Can I fix it in the PR?

**Review by vors — APPROVED** [review]
:shipit:

File: src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs (hunk 1 above)
Comment (vors) [inline src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs]: Sure, please do

Comment (iSazonov) [inline src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs]: Fixed.

File: src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs [hunk 2]
```diff
@@ -54,7 +54,7 @@ namespace Microsoft.PowerShell.Commands
     /// Create a new runspace and use it to execute a command on a remote machine
     ///     $runspace = New-PSSession -computername "Server1"
     ///     $credential = get-credential "user01"
-    ///     invoke-command -command {get-process} �Crunspace $runspace -credential $credential
+    ///     invoke-command -command {get-process} -runspace $runspace -credential $credential
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs]: It should be `-Session` :) It can be implied from `$runspace = New-PSSession -computername "Server1"`

Comment (daxian-dbw) [inline src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs]: On page editing is really handy 😄

Comment (iSazonov) [inline src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs]: 😊 I thought it was something new in 6.0.

**Review by daxian-dbw — APPROVED** [review]

**Comment by daxian-dbw** [comment]
> Now there is no Verbs<> consts for "Sort","Tee", "Foreach" and "Where". Whether to add them?

Let's leave them as is for now.

**Comment by lzybkr** [comment]
Note that `Sort`, `Tee`, `ForEach`, and `Where` are not approved verbs, which is why we don't have strings for them and `Get-Verb` doesn't return them.  They were considered special cases.

**Comment by iSazonov** [comment]
Thanks for clarification!
