### PR TITLE
Fix CompleteInput error for empty scripts

### LINKED ISSUE #5743: CompleteInput fails when passed an empty string/AST
Steps to reproduce
------------------

```powershell
[System.Management.Automation.CommandCompletion]::CompleteInput('', 0, @{})
```

Or

```powershell
[System.Management.Automation.CommandCompletion]::CompleteInput(
	{}.Ast,
	@(),
	{}.Ast.Extent.StartScriptPosition,
	@{})
```

Expected behavior
-----------------

```none
CurrentMatchIndex ReplacementIndex ReplacementLength CompletionMatches
----------------- ---------------- ----------------- -----------------
               -1                0                 0 {}
```

Alternatively if throwing is a design choice, throw an `ArgumentException` instead of letting `Enumerable.Last` fail.

Actual behavior
---------------

```none
> [System.Management.Automation.CommandCompletion]::CompleteInput('', 0, @{})
Exception calling "CompleteInput" with "3" argument(s): "Sequence contains no elements"
At line:1 char:1
+ [System.Management.Automation.CommandCompletion]::CompleteInput('', 0 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : InvalidOperationException

> $Error[0].Exception.InnerException | Format-List * -Force
Message        : Sequence contains no elements
Data           : {}
InnerException :
TargetSite     : TSource Last[TSource](System.Collections.Generic.IEnumerable`1[TSource])
StackTrace     :    at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
                    at
                 System.Management.Automation.CompletionAnalysis.InitializeCompletionContext(TypeInferenceContext
                 typeInferenceContext)
                    at System.Management.Automation.CompletionAnalysis.GetResults(PowerShell powerShell, Int32&
                 replacementIndex, Int32& replacementLength)
                    at System.Management.Automation.CommandCompletion.CompleteInputImpl(Ast ast, Token[] tokens,
                 IScriptPosition positionOfCursor, Hashtable options)
                    at System.Management.Automation.CommandCompletion.CompleteInput(String input, Int32 cursorIndex,
                 Hashtable options)
                    at CallSite.Target(Closure , CallSite , Type , String , Int32 , Hashtable )
HelpLink       :
Source         : System.Linq
HResult        : -2146233079
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-rc.2
PSEdition                      Core
GitCommitId                    v6.0.0-rc.2
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by MartinGC94**
# PR Summary
Fixes a crash when attempting to tab complete an empty script.

## PR Context
Fixes https://github.com/PowerShell/PowerShell/issues/5743

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Review by JamesWTruher — APPROVED** [review]
lgtm

**Review by daxian-dbw — COMMENTED** [review]
I think we should return `s_emptyCommandCompletion` early in `CompletInput` overloads in case the passed-in script is an empty string or the passed-in AST has `ast.Extent.Text` being an empty string.

File: src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs [hunk 1]
```diff
@@ -155,6 +155,11 @@ internal static AstAnalysisContext ExtractAstContext(Ast inputAst, Token[] input
                 ast => IsCursorWithinOrJustAfterExtent(positionForAstSearch, ast.Extent),
                 searchNestedScriptBlocks: true).ToList();
 
+            if (relatedAsts.Count == 0)
+            {
+                relatedAsts.Add(inputAst);
+            }
+
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs:162]: With the early return in `CompleteInput`, do we still need this change here? Are there any other cases where `relatedAsts` will be empty when code flow reaches here?

Comment (MartinGC94) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs:162]: Yes. See this call from the public "PredictionContext": https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/Subsystem/PredictionSubsystem/ICommandPredictor.cs#L194

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs:162]: Right, thanks. IMHO, it's logically correct for `relatedAsts` to be empty in this particular case. It's just that we had incorrectly assumed it being always not empty when used in the tab completion code.

Now with the early return in `CompleteInput`, I think we're good with the tab completion code (please correct me if I'm wrong).

For the predictor caller, I'd prefer it to return an empty list in this case. So, how about removing this change but add `relatedAsts.Count > 0` to the subsequent `if (relatedAsts[^1].Extent ....` check?

Comment (MartinGC94) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs:162]: To me it feels inconsistent/illogical. If you have an empty scriptblock like this: `{}` then it reports there's no related asts, but if you have a scriptblock with just a space: `{ }` then the root script block is reported as related. From an API consumer perspective it also seems simpler to not have to handle an empty scriptblock differently from one with just whitespaces.
Also, something I've thought about that could be nice in the future would be completion of commands and keywords with no text at the cursor.
That way an editor/user could trigger completion on empty lines and let the editor do the filtering (many editors have some fuzzy search).

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs:162]: > Now with the early return in CompleteInput, I think we're good with the tab completion code (please correct me if I'm wrong).

My assumption was wrong. Whether it has any related asts depends on where the cursor is at.
For a non-empty script block, if the cursor is 0, then it's still considered no related asts (no AST is surrounding the cursor position). An example here is: `[System.Management.Automation.CommandCompletion]::CompleteInput('get-comm', 0, @{})`. The following is the screenshot with changes in this PR:

image

I would expect `CompleteInput('get-comma', 0, @{})` returns the same result as `CompleteInput('get-comma', 1, @{})`.

How about we changing the check in [IsCursorWithinOrJustAfterExtent](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs#L83) to be `... cursor.Offset >= extent.StartOffset && ...` instead? Do you see any problems if we make that change?

Comment (MartinGC94) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs:162]: Updating IsCursorWithinOrJustAfterExtent with >= breaks a bunch of tests. It also feels wrong because in a scenario like: `$SomeVar<Tab>.SomeProperty` it would see that as if you were completing the member and not the variable.

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs:162]: Thanks for trying out that idea. Then I guess it's by design that `CompleteInput('what-ever-script', 0, @{})` return an empty completion result.

Also, given that whether it has any related asts depends on where the cursor is at, I agree it makes sense to have the `relatedAsts.Add(inputAst)` code in.

**Review by daxian-dbw — APPROVED** [review]
LGTM
