### PR TITLE
Fix crash when terminal is reset

### LINKED ISSUE #6776: Soft reset on plus cursor key input causes crash macOS
Steps to reproduce
------------------
1. Open the Terminal Application.
2. Open a PowerShell session if the user's shell is not set to `pwsh` already: 
```
$ pwsh
PowerShell v6.0.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

Loading personal and system profiles took 799ms.
~> 
```
3. Remove the PSReadline module from the current environment:
```
~> Remove-Module PSReadLine
~>
```
4. Click the `Shell` menu, then choose the `Reset` menu item.
5. Press the up cursor key once; notice that a capital `A` is entered on the screen.
6. Press the up cursor key once more.

Expected behavior
-----------------
PowerShell should continue running.

Actual behavior
---------------
PowerShell crashes:
```none
~> FailFast: Specified argument was out of the range of valid values.
Parameter name: startIndex

   at System.Environment.FailFast(System.String, System.Exception)
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Darwin 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.2}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
## PR Summary

When terminal is reset, the state of the string buffer is wrong so the built-in readline code tries to insert a character beyond the length of the buffer and thus crashes.  Fix is to check if the index is greater than the size of the buffer and set it to the end of the buffer.  Validated manually.

Fix https://github.com/PowerShell/PowerShell/issues/6776

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs [hunk 1]
```diff
@@ -1791,10 +1791,16 @@ private string ReadLineFromConsole(bool endOnTab, string initialContent, bool ca
                     }
 
                     // Modify string
-                    if (!insertMode) // then overwrite mode
+                    if (!insertMode && s != "") // then overwrite mode
                     {
                         s = s.Remove(index, 1);
```
Comment (daxian-dbw) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs]: When it's the overwrite mode, `index` could be out of range here too, right?
And, if we check `index` here, it seems no reason to keep `&& s != ""`.

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs [hunk 2]
```diff
@@ -1791,10 +1791,16 @@ private string ReadLineFromConsole(bool endOnTab, string initialContent, bool ca
...
                     }
+
+                    if (index > s.Length)
```
Comment (daxian-dbw) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs]: I think it would be helpful to have a comment explain when `index > s.Length` would happen.

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs (hunk 1 above)
Comment (SteveL-MSFT) [reply src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs]: Yes, move check up

File: src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs [hunk 3]
```diff
@@ -1790,11 +1790,18 @@ private string ReadLineFromConsole(bool endOnTab, string initialContent, bool ca
...
+                    // Handle case where terminal gets reset and the index is outside of the buffer
+                    if (index > s.Length)
+                    {
+                        index = s.Length;
+                    }
+
                     // Modify string
                     if (!insertMode) // then overwrite mode
                     {
                         s = s.Remove(index, 1);
```
Comment (daxian-dbw) [inline src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs]: When `index == s.Length`, this line will throw. The if check probably should be updated to `if (!insertMode && index < s.Length)`

**Review by daxian-dbw — APPROVED** [review]

**Review by anmenaga — APPROVED** [review]

**Review by adityapatwardhan — APPROVED** [review]
