### PR TITLE
Fix class parsing (issue 3083)

### LINKED ISSUE #3083: Error with class parsing
The code below is failed with PSReadLine loaded. Without PSReadLine the code is succeeed.
It is the parser issue not PSReadLine https://github.com/lzybkr/PSReadLine/issues/500#issuecomment-276768379

>This is a bug in the parser - it should be throwing an  IncompleteParseException  instead of a  ParseException .

Steps to reproduce
------------------
Copy-Paste the code:

```powershell
class foo
{
    [void]q() { $a=1 }

    [string]$bar
}
```

Expected behavior
-----------------
Pass parsing without errors.

Actual behavior
---------------

```powershell
PS C:\> class foo
>>> {
>>>     [void]q() { $a=1 }
>>>
At line:3 char:5
+     [void]q() { $a=1 }
+     ~~~~~~~~~~~~~~~~~~
Missing closing '}' in statement block or type definition.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEndCurlyBrace

PS C:\>     [string]$bar

PS C:\> }
At line:1 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

Environment data
----------------

<!-- provide the output of $PSVersionTable -->

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.0.10240.17146
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10011.16384
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3

Name                           Value
----                           -----
CLRVersion
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
GitCommitId                    v6.0.0-alpha.14-61-gfe3d01627a0e7a1a7882d880299ed9e2cb88c97e-dirty
BuildVersion                   3.0.0.0
PSVersion                      6.0.0-alpha
PSRemotingProtocolVersion      2.3
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
PSEdition                      Core

```

### PR DESCRIPTION
**Pull request by iSazonov**
Close #3083

This problem only appears in the interactive session with manual input
(or right click) and with PSReadLine loaded so no tests.

### CODE REVIEW

**Comment by vors** [comment]
What's the error message on the motivation example now?
I think it would be better to modify parser to allow blank lines in the interactive session. That would greatly improve copy-paste story.

Essentially the smallest repro is 

```powershell
class foo {

}
```

**Comment by iSazonov** [comment]
The fix just allow blank lines.

**Comment by vors** [comment]
Oh, that's very interesting. From the diff it seems that it just changes extent, but keeps reporting the error. Let me check with a local build.

**Comment by vors** [comment]
Verified. Great change!

**Comment by iSazonov** [comment]
Yes it is slightly a trick. :-)
Perhaps we should replace `ExtentOf` on `After`?

**Review by vors — DISMISSED** [review]
@lzybkr can you, please double-check?

**Comment by vors** [comment]
@iSazonov yeah, `After` seems more of a pattern in parser. I actually tried replace it by After, but it didn't work for me. And I didn't have ability to debug it at the moment.

**Comment by iSazonov** [comment]
I found as apply `After`. Looks better for me.

**Comment by lzybkr** [comment]
The use of `After` looks incorrect, or at least inconsistent to me. In that overload, the first parameter is where we want to report the error, so on the opening curly is fine, and consistent with most of the other places we report similar errors.

The important part is reporting where the error was detected, the second parameter - and that should be sufficient to fix the bug.

**Comment by vors** [comment]
> where we want to report the error, so on the opening curly is fine

I think it's more usable to report non-closed curly closer to the expected place.
Imagine 100 lines class. Would you rather see error on the first open curly or on the last line?

Also, the fix itself exploits the implementation of `ReportIncompleteInput`: if reported extent happens at the last token, we actually don't error out and waiting for more input. So extent here has to be at the end. It's consistent with how do you treat things like

```
& { 1


}
```

**Comment by lzybkr** [comment]
Yes, but it's somewhat difficult to infer where the closing brace should go.  End of file is often the best we can do, and that's worse than pointing to the opening brace.

**Comment by lzybkr** [comment]
Oh, the proposed fix moves the point where the error is reported by 1 character - the character after the curly - so it's not really much different, and it's not consistent with most other places we report the same error.

**Comment by iSazonov** [comment]
I tried looking for `if (rCurly.Kind != TokenKind.RCurly)` and found:
1. We should fix the same issue with `Enum` - [Line](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/parser/Parser.cs#L4272)
2. We have working pattern for `@{}` - [Line](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/parser/Parser.cs#L6348) - We can use this to fix `Class` and `Enum`.

**Comment by lzybkr** [comment]
The hash literal might be a bad example, I think the error should point to the `@{`.

Consider an example like:

```PowerShell
function foo
{

function bar
{
}
```

`foo` is missing the matching brace, but it can't be detected until after `bar`. If we reported from opening brace to end of file, you get ugly red squiggles filing up the screen and it's a bit slow rendering that - not too useful for folks who don't like typing the closing brace right away.

By reporting the error on the opening brace, assuming sane indentation, it's usually easy to figure out where the missing brace goes.

So I'd say hash literals, class, and enum should all be modified to report the error after the opening brace, and make sure to pass the position the error is detected to ensure we correctly report an incomplete parse for interactive command line use.

**Comment by iSazonov** [comment]
Fix for hash, class, and enum is ready. Now the error position is reported after the opening brace.

File: src/System.Management.Automation/engine/parser/Parser.cs [hunk 1]
```diff
@@ -6344,8 +6344,8 @@ private ExpressionAst HashExpressionRule(Token atCurlyToken, bool parsingSchemaE
                 // Note -  the error handling function inspects the error message body to extra the ParserStrings property name. It uses this value as the errorid.
                 var errorMessageExpression = parsingSchemaElement ?
                     (Expression<Func<string>>)(() => ParserStrings.IncompletePropertyAssignmentBlock)
-                    : (Expression<Func<string>>)(() => ParserStrings.IncompleteHashLiteral);
-                ReportIncompleteInput(keyValuePairs.Any() ? After(keyValuePairs.Last().Item2) : After(atCurlyToken), rCurly.Extent, errorMessageExpression);
+                    : (Expression<Func<string>>)(() => ParserStrings.MissingEndCurlyBrace);
+                ReportIncompleteInput(After(atCurlyToken), rCurly.Extent, errorMessageExpression);
```
Comment (lzybkr) [inline src/System.Management.Automation/engine/parser/Parser.cs]: This looks like it might degrade the quality of the error on:
```PowerShell
@{
a =
}
```
or something like that - please try variants of this (for example: with and without the closing curly, with and without the `=`).

Comment (iSazonov) [inline src/System.Management.Automation/engine/parser/Parser.cs]: I see. I tried to fix.

After that there is another question: Are NewLine and Semi terminators having the same rights? Compare:
```powershell

@{
a = 
b =1
c =2
}


@{
a = ;
b =1;
c =2;
}
```
If we will fix this (require that the expression begin immediately after the equal on the same line) of cause it will be a breaking change.

Comment (lzybkr) [inline src/System.Management.Automation/engine/parser/Parser.cs]: Interesting, I don't recall explicitly supporting multiple statement terminators (you can have multiple semicolons as well) - so we shouldn't break anybody even though that's kinda broken.

**Comment by daxian-dbw** [comment]
@iSazonov Great commit description! It helps me quickly understand the problem and the fix. Thanks!

File: src/System.Management.Automation/engine/parser/Parser.cs (hunk 1 above)
Comment (iSazonov) [inline src/System.Management.Automation/engine/parser/Parser.cs]: Clear. Thanks!
