### PR TITLE
Fix incorrect references and improve formatting in PSCommand XML comments

### LINKED ISSUE #15537: Doc Bug in AddScript API
Copied from https://github.com/MicrosoftDocs/PowerShell-Docs/issues/4472

This is a bug in the API documentation for AddScript(). The API documentation comes from `///` comments in the source code to this must be fixed in the source code. The example shown in the docs is using AddCommand() instead of AddScript. Also the line break and indentation could be improved for readability.

Both overloads are affected:

https://github.com/PowerShell/PowerShell/blob/659dff09e4e1fd15e9f404b4f3460bd9f239ea90/src/System.Management.Automation/engine/hostifaces/PSCommand.cs#L153-L156

https://github.com/PowerShell/PowerShell/blob/659dff09e4e1fd15e9f404b4f3460bd9f239ea90/src/System.Management.Automation/engine/hostifaces/PSCommand.cs#L195-L198

### PR DESCRIPTION
**Pull request by ghost**
# PR Summary

- ~~Changes parameter name from `command` to `cmdlet` in `AddCommand(string command)` to match its overload `AddCommand(string cmdlet, bool useLocalScope)`~~
- ~~Fixes a bug where the value passed into the constructor for an Argument Null Exception object does not match the name of the relevant parameter~~
- Corrects references to the wrong methods and parameters in the XML comments
- Improves formatting for code samples in the XML comments

## PR Context

Closes #15537 

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by iSazonov** [comment]
@octos4murai Please sign CLA. Without this we can not merge the PR.

**Comment by octos4murai** [comment]
> @octos4murai Please sign CLA. Without this we can not merge the PR.

Done. Thanks for the reminder.

File: src/System.Management.Automation/engine/hostifaces/PSCommand.cs [hunk 1]
```diff
@@ -63,14 +63,14 @@ internal PSCommand(Command command)
         #region Command / Parameter Construction
 
         /// <summary>
-        /// Add a command to construct a command pipeline.
+        /// Add a cmdlet to construct a command pipeline.
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/hostifaces/PSCommand.cs:66]: Actually more than strict cmdlets can be used here. The path to a script will work as well, for example

File: src/System.Management.Automation/engine/hostifaces/PSCommand.cs [hunk 2]
```diff
@@ -85,19 +85,19 @@ internal PSCommand(Command command)
         /// <exception cref="ArgumentNullException">
         /// cmdlet is null.
         /// </exception>
-        public PSCommand AddCommand(string command)
+        public PSCommand AddCommand(string cmdlet)
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/hostifaces/PSCommand.cs:88]: [Changing this is a breaking change](https://stackoverflow.com/a/8018728)

**Review by rjmholt — CHANGES_REQUESTED** [review]
The example changes are much needed, thanks!

The parameter name changes we can't take, and I don't think the terminology changes add clarity here

File: src/System.Management.Automation/engine/hostifaces/PSCommand.cs (hunk 1 above)
Comment (octos4murai) [reply src/System.Management.Automation/engine/hostifaces/PSCommand.cs:66]: An overload for this method refers to `cmdlet` in its XML comments summary. Its parameter is also named `cmdlet` but as you mentioned elsewhere, this would be a breaking change.

Do you suggest to:

- Keep this the same and change the overload method's XML comments to also use `command` to connote that more than strict cmdlets can be used, or
- Allow the apparent inconsistency and make no changes?

File: src/System.Management.Automation/engine/hostifaces/PSCommand.cs (hunk 2 above)
Comment (octos4murai) [reply src/System.Management.Automation/engine/hostifaces/PSCommand.cs:88]: Noted. I will exclude this breaking change.

File: src/System.Management.Automation/engine/hostifaces/PSCommand.cs (hunk 1 above)
Comment (rjmholt) [reply src/System.Management.Automation/engine/hostifaces/PSCommand.cs:66]: > Its parameter is also named cmdlet but as you mentioned elsewhere, this would be a breaking change.

Yes, it's an unfortunate inconsistency, but one that we must now live with. The parameter name is part of the API.

Feel free to add any extra documentation around the XML, but the parameter names themselves can't be changed.

File: src/System.Management.Automation/engine/hostifaces/PSCommand.cs [hunk 3]
```diff
@@ -85,19 +85,19 @@ internal PSCommand(Command command)
...
         {
-            if (command == null)
+            if (cmdlet == null)
             {
-                throw PSTraceSource.NewArgumentNullException("cmdlet");
```
Comment (octos4murai) [inline src/System.Management.Automation/engine/hostifaces/PSCommand.cs:92]: @rjmholt I think there is a bug here where a potential null argument is referred to using string "cmdlet". The actual argument name is not "cmdlet" but rather "command". If you agree, perhaps I can replace this line with:

`throw PSTraceSource.NewArgumentNullException(nameof(command));`

Comment (iSazonov) [reply src/System.Management.Automation/engine/hostifaces/PSCommand.cs]: Please pull new PR with the change.

Comment (octos4murai) [reply src/System.Management.Automation/engine/hostifaces/PSCommand.cs]: > Please pull new PR with the change.

Just would like some clarification -- should I create a new GitHub issue and then create a new PR linked to that issue?

Comment (iSazonov) [reply src/System.Management.Automation/engine/hostifaces/PSCommand.cs]: Issues are need only for discussions to understand what we should do or not do. Here we see simple inconsistency and can accept new PR.

Comment (octos4murai) [reply src/System.Management.Automation/engine/hostifaces/PSCommand.cs]: > Issues are need only for discussions to understand what we should do or not do. Here we see simple inconsistency and can accept new PR.

Got it. Thank you.

**Review by rjmholt — APPROVED** [review]
