### PR TITLE
If SMA.dll location is not found, use host exe to determine `$PSHOME` location

### LINKED ISSUE #23797: .NET App using Powershell.SDK fails to run, when building as SingeFile
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a .NET 8 Application executing a lot of Powershell commands, but when I build it as a SingleFile it throws an exception.
Issue is already documented in [#13540](https://github.com/PowerShell/PowerShell/issues/13540) 

I also opened an issue in the dotnet repo, which is to find under: [dotnet/runtime #102193](https://github.com/dotnet/runtime/issues/102193). There is already a very helpful comment which shows a possible way fixing the issue:  [Comment](https://github.com/dotnet/runtime/issues/102193#issuecomment-2110290621) 

------

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.4.2"  />
  </ItemGroup>
</Project>
```

```
using System;
using System.Management.Automation;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            String cmd = "New-Item -Force -Type Directory -Path '%userprofile%\test123'";
             PowerShell ps1 = PowerShell.Create().AddScript(cmd);
             ps1.Invoke();
        }
    }
}
```

`dotnet publish -r win-x64 --self-contained false /p:PublishSingleFile=true`

### Expected behavior

```console
Publish and run successfully.
```

### Actual behavior

Publish works, but application doesn' t run. At the first execution of a powershell script, following exception is thrown:

```
ERROR: 2024-05-14T12:33:51.8318820Z - Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at System.Management.Automation.PSSnapInReader.ReadEnginePSSnapIns()
   at System.Management.Automation.Runspaces.InitialSessionState.CreateDefault()
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(PSHost host)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace()
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke()
```

### Error details

_No response_

### Environment data

* .NET 8
* Win10-x64
* PowerShell.SDK 7.4.2

### Visuals

_No response_

### LINKED ISSUE #24070: Getting ArgumentNullException exception on calling System.Management.Automation.PowerShell.Create() when publishing a single file exe
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Create a dotnet console app.
2.  Add nuget package System.Management.Automation, Microsoft.Powershell.SDK
3. Write below code in  Program.cs of the console application

```C#
var shell = PowerShell.Create()
            .AddCommand("Set-ExecutionPolicy")
            .AddParameter("Scope", "Process")
            .AddParameter("ExecutionPolicy", "Unrestricted")
            .AddScript(
                $"Write-Host 'Hello World!'");

        var results = await shell.InvokeAsync();
```
4. Run `dotnet publish -c Release -o .\bin\Publish --self-contained true --runtime win-x64 /p:PublishSingleFile=true`
5. then `cd  .\bin\Publish
6. run the exe file.
7. You'll get below error:
```C#
 System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
         at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
         at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location ---
```

### Expected behavior

```console
should not throw exception.
```

### Actual behavior

```console
Throwing System.ArgumentNullException exception
```

### Error details

_No response_

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

PowerShell uses the SMA.dll file location to determine it's base location.  However, if a hosted app is built as a single exe, that location is empty which causes PowerShell init to fail.

Change is if SMA.dll file location is empty, use the host exe location instead.

Tested manually building pwsh as singleexe.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/24070
Fix https://github.com/PowerShell/PowerShell/issues/23797

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
  - [x] None
  - **OR**
  - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
    - [ ] Experimental feature name(s): 
- **User-facing changes**
  - [x] Not Applicable
  - **OR**
  - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
  - [x] N/A or can only be tested interactively
  - **OR**
  - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
  - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
  - **OR**
  - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
    - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
      - [ ] Issue filed: 
    - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
      - [ ] Issue filed: 
    - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
      - [ ] Issue filed: 
    - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
      - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/engine/Utils.cs [hunk 1]
```diff
@@ -482,9 +482,19 @@ internal static string GetWindowsPowerShellVersionFromRegistry()
...
+                // need to remove any trailing directory separator characters
+                baseDirectory = baseDirectory.TrimEnd(Path.DirectorySeparatorChar);
+            }
+            else
+            {
+                // host path can be empty if hosted in WinRM, so fallback to using SMA.dll location
+                baseDirectory = Path.GetDirectoryName(typeof(PSObject).Assembly.Location);
+            }
+
+            return baseDirectory;
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/Utils.cs:497]: [Current AppContext.BaseDirectory implementation](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/AppContext.AnyOS.cs,24) return `Assembly.GetEntryAssembly()?.Location` for not AOT (for pwsh.exe it is `pwsh.dll` location). It can be not that we want in some scenarios. Also do we really need `APP_CONTEXT_BASE_DIRECTORY`?
I think logic could be:
```c#
var baseDirectory = Path.GetDirectoryName(typeof(PSObject).Assembly.Location);
if (string.IsNullOrEmpty(baseDirectory))
{
    baseDirectory = Environment.ProcessPath;
}
```

**Comment by iSazonov** [comment]
For information comment from @fMichaleczek https://github.com/PowerShell/PowerShell/issues/13540#issuecomment-704828916

**Comment by fMichaleczek** [comment]
@iSazonov For Browser (Wasm), I will use a native preprocessor (#if BROWSER) to escape from the standard behavior.

**Comment by daxian-dbw** [comment]
@SteveL-MSFT Can you take another look at https://github.com/PowerShell/PowerShell/pull/18674 and see if all the problems listed there are fixed in this PR?

**Comment by SteveL-MSFT** [comment]
> @SteveL-MSFT Can you take another look at #18674 and see if all the problems listed there are addressed in this PR? The main blocking thing that I can tell is how to ship the modules for Win/Unix respectively in the `Microsoft.PowerShell.SDK` NuGet package: [#18674 (comment)](https://github.com/PowerShell/PowerShell/pull/18674#issuecomment-1476712973)

Let me look into this

**Review by iSazonov — APPROVED** [review]

**Comment by fMichaleczek** [comment]
> Change of thought, I'll update the PR is that if SMA.dll location is valid, we'll use that otherwise fall through to host location. This should resolve the app compat concerns.

The problem with Hosting is when Assembly.Location is null or empty (I dont rembember which one).
I dont ever see a wrong Assembly.Location (but I may be wrong)

```powershell
PS > [System.IO.Path]::GetDirectoryName([string]::Empty)
Exception calling "GetDirectoryName" with "1" argument(s): "The path is not of a legal form."
```

```CSharp
var smaAssembly = typeof(PSObject).Assembly;
if (!string.IsNullOrEmpty(smaAssembly.Location))
{
    return Path.GetDirectoryName(smaAssembly.Location);
}
return AppContext.BaseDirectory.TrimEnd(Path.DirectorySeparatorChar);
```

**Comment by SteveL-MSFT** [comment]
I built a custom single-exe of pwsh and 81 tests fail specifically because SMA.dll no longer exists (it's inside the exe). 

```powershell
PS> [psobject].Assembly | fl *

CodeBase            :
FullName            : System.Management.Automation, Version=7.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
EntryPoint          :
DefinedTypes        : {<>f__AnonymousType0`2[<cacheEntry>j__TPar,<splittedName>j__TPar], <>f__AnonymousType1`2[<<>h__TransparentIdentifier0>j__TPar,<cachedClassName>j__TPar],
                      <>f__AnonymousType2`2[<<>h__TransparentIdentifier1>j__TPar,<cachedModuleName>j__TPar],
                      <>f__AnonymousType3`2[<<>h__TransparentIdentifier2>j__TPar,<cachedResourceName>j__TPar]…}
IsCollectible       : False
ManifestModule      : System.Management.Automation.dll
ReflectionOnly      : False
Location            :
ImageRuntimeVersion : v4.0.30319
GlobalAssemblyCache : False
HostContext         : 0
IsDynamic           : False
ExportedTypes       : {System.Management.Automation.PowerShellAssemblyLoadContextInitializer, System.Management.Automation.PowerShellUnsafeAssemblyLoad,
                      System.Management.Automation.Platform, System.Management.Automation.PSTransactionContext…}
IsFullyTrusted      : True
CustomAttributes    : {[System.Runtime.CompilerServices.ExtensionAttribute()], [System.Runtime.CompilerServices.CompilationRelaxationsAttribute((Int32)8)],
                      [System.Runtime.CompilerServices.RuntimeCompatibilityAttribute(WrapNonExceptionThrows = True)],
                      [System.Diagnostics.DebuggableAttribute((System.Diagnostics.DebuggableAttribute+DebuggingModes)263)]…}
EscapedCodeBase     :
Modules             : {<Unknown>}
SecurityRuleSet     : None
```

Note that even with 81 failures, 12310 tests passed.

**Comment by iSazonov** [comment]
> Note that even with 81 failures, 12310 tests passed. More work will be needed to get a single-exe to actually work, but it's not clear to me if there's value of this for PS7 itself vs hosted apps.

More recently, things were much worse there. We did not make any efforts in this direction, nevertheless, the situation has become much better!
I don't know where else there are problems, but maybe they are not so difficult to remove them over time.
It's a question for the committee whether we need to support this single-exe scenario.

**Comment by fMichaleczek** [comment]
@iSazonov In any case, PowerShell's internal APIs need to be made "FileLess" compatible.

On Browser, we are in the extreme case where API like Environment.ProcessPath is empty.
I have used `BROWSER` preprocessor directive to set $PSHome to an arbitrary path /opt/microsoft/powershell,
because I need a fixed path in the boot json

image

image
image

**Comment by iSazonov** [comment]
> @iSazonov In any case, PowerShell's internal APIs need to be made "FileLess" compatible.

I tried that but that path was rejected. Since we have a progress we're on that path, but implicitly :smile:. We're closest to realizing the single exe scenario. "Browser" scenario is more difficult to implement. And I honestly don't understand why we need to load the pwsh engine in the browser (Compare with Windows PowerShell Web Access/Console).

**Comment by fMichaleczek** [comment]
> We're closest to realizing the single exe scenario.

+2 important needed fixes : 

https://github.com/PowerShell/PowerShell/blob/f69a4b542bac0082544f3a38b5e7a54274c26872/src/System.Management.Automation/help/CommandHelpProvider.cs#L482

https://github.com/PowerShell/PowerShell/blob/f69a4b542bac0082544f3a38b5e7a54274c26872/src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs#L645


> And I honestly don't understand why we need to load the pwsh engine in the browser (Compare with Windows PowerShell Web Access/Console).

Be hosted on github pages for free. (and make free tools)

**Comment by SteveL-MSFT** [comment]
We should probably do this iteratively.  The main priority for me is enabling hosted single-exe scenarios.  `pwsh` itself as single-exe I don't think is that interesting (other than academically since we can't trim any of .NET which is needed for scripts) and eventually enable web hosted WASM.

File: src/System.Management.Automation/engine/Utils.cs [hunk 2]
```diff
@@ -482,9 +482,14 @@ internal static string GetWindowsPowerShellVersionFromRegistry()
 
         internal static string GetApplicationBase(string shellId)
         {
-            // Use the location of SMA.dll as the application base.
-            Assembly assembly = typeof(PSObject).Assembly;
-            return Path.GetDirectoryName(assembly.Location);
+            var baseDirectory = Path.GetDirectoryName(typeof(PSObject).Assembly.Location);
+            if (string.IsNullOrEmpty(baseDirectory))
+            {
+                // need to remove any trailing directory separator characters
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/Utils.cs:488]:
```suggestion
                // Need to remove any trailing directory separator characters
```

File: src/System.Management.Automation/engine/Utils.cs [hunk 3]
```diff
@@ -482,9 +482,14 @@ internal static string GetWindowsPowerShellVersionFromRegistry()
 
         internal static string GetApplicationBase(string shellId)
         {
-            // Use the location of SMA.dll as the application base.
-            Assembly assembly = typeof(PSObject).Assembly;
-            return Path.GetDirectoryName(assembly.Location);
+            var baseDirectory = Path.GetDirectoryName(typeof(PSObject).Assembly.Location);
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/Utils.cs:485]:
```suggestion
            // Use the location of SMA.dll as the application base if it exists,
            // otherwise, use the base directory from `AppContext`.
            var baseDirectory = Path.GetDirectoryName(typeof(PSObject).Assembly.Location);
```

**Review by daxian-dbw — APPROVED** [review]
