### PR TITLE
When formatting, if collection is modified, don't fail the entire pipeline

### LINKED ISSUE #11797: Helper method converting PSObject to string may fail
This was encountered by a MS Partner team.  When calling a cmdlet that outputs lots of objects, the [SmartToString()](https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs#L205) helper throws the exception "InvalidOperationException: Collection was modified after the enumerator was instantiated" as the PSObject is modified before the conversion completes.  There is already code to catch an ExtendedTypeSystemException and we could extend that for any exception and just return string.empty.  Or alternatively, we could make a copy of the object but that would impact perf.

In the repro, it was explicitly going through the `Format-List` code, although `Format-Table` may also use this helper.

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

If a cmdlet emitting objects in a collection inadvertently modifies an instance within the collection, an InvalidOperationException gets thrown.  This results in the entire pipeline failing as the exception is not being handled.  Customers are seeing this with apps that use PowerShell to enumerate a large collection like AD users, then piping that to `Format-List` (and then `Out-String`).

The proposed fix is to modify the existing exception handling block to also cover InvalidOperationException.

Originally, the decision was to emit a warning message, however, the code calling this helper method is also within the engine for formatting which itself doesn't have a means to write a warning message.  Since the existing code for ExtendedTypeSystemException already has this behavior, it seems acceptable to extend it to InvalidOperationException.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/11797

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

File: src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs [hunk 1]
```diff
@@ -290,17 +291,20 @@ internal static string SmartToString(PSObject so, PSPropertyExpressionFactory ex
                 // take care of the case there is no base object
                 return so.ToString();
             }
-            catch (ExtendedTypeSystemException e)
+            catch (Exception e)
```
Comment (rjmholt) [inline src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs:294]: Consider:

```csharp
catch (Exception e) when (e is ExtendedTypeSystemException || e is InvalidOperationException)
{
    if (formatErrorObject != null)
    {
        formatErrorObject.sourceObject = so;
        formatErrorObject.exception = e;
    }

    return string.Empty;
}
```

File: src/System.Management.Automation/resources/FormatAndOut_format_xxx.resx [hunk 2]
```diff
@@ -179,4 +179,7 @@
   <data name="FormattingError" xml:space="preserve">
     <value>Failed to interpret format string "{0}".</value>
   </data>
+  <data name="SmartToStringError" xml:space="preserve">
+    <value>Object skipped: {0}.</value>
+  </data>
```
Comment (rjmholt) [inline src/System.Management.Automation/resources/FormatAndOut_format_xxx.resx:184]: This has been created, but is it used anywhere? If so, is it possible to provide a more context-informative error message? If not, this should be removed.

File: src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs (hunk 1 above)
Comment (rjmholt) [reply src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs:294]: Alternatively, since the two errors don't really have a common provenance, it might make sense for them to have different code paths:

```csharp
catch (ExtendedTypeSystemException etsEx)
{
    if (formatErrorObject != null)
    {
        formatErrorObject.sourceObject = so;
        formatErrorObject.exception = e;
    }

    return string.Empty;
}
catch (InvalidOperationException invalidOpEx)
{
    // Handling appropriate for the InvalidOperationException
}
```

An `InvalidOperationException` is a pretty generic and high-level exception though and one that's seldom caught, so I wonder about catching them in general.

I would be a lot more comfortable knowing more about when and why this exception is thrown to understand what handling should be done other than just sitting on it.

File: src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs [hunk 3]
```diff
@@ -290,17 +291,20 @@ internal static string SmartToString(PSObject so, PSPropertyExpressionFactory ex
...
                 {
-                    formatErrorObject.sourceObject = so;
-                    formatErrorObject.exception = e;
+                    if (formatErrorObject != null)
+                    {
+                        formatErrorObject.sourceObject = so;
+                        formatErrorObject.exception = e;
+                    }
+
+                    return string.Empty;
```
Comment (iSazonov) [inline src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs:304]: So users will see empty line instead of list of lines?

File: src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs (hunk 1 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs:294]: There isn't different handling for the two exception types, so will go with first proposal

File: src/System.Management.Automation/resources/FormatAndOut_format_xxx.resx (hunk 2 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/resources/FormatAndOut_format_xxx.resx:184]: Left over that needs to be removed

File: src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs (hunk 3 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs:304]: This is augmenting the existing behavior to handle an additional exception case.

File: src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs [hunk 4]
```diff
@@ -290,10 +291,8 @@ internal static string SmartToString(PSObject so, PSPropertyExpressionFactory ex
                 // take care of the case there is no base object
                 return so.ToString();
             }
-            catch (ExtendedTypeSystemException e)
+            catch (Exception e) when (e is ExtendedTypeSystemException || e is InvalidOperationException)
             {
-                // NOTE: we catch all the exceptions, since we do not know
-                // what the underlying object access would throw
```
Comment (iSazonov) [inline src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs:296]: Maybe update the comment? It would be nice for readers to understand why we catch these two exceptions.

Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs:296]: will update

Comment (iSazonov) [reply src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs:296]: Since we silently return empty string it is difficult to discover for users why they get empty string instead of object list. I suggest add a trace/log here.

Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs:296]: added trace

File: src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs [hunk 5]
```diff
@@ -19,6 +20,11 @@ namespace Microsoft.PowerShell.Commands.Internal.Format
     /// </summary>
     internal static class PSObjectHelper
     {
+        #region tracer
+        [TraceSource("PSObjectHelper", "PSObjectHelper")]
+        internal static readonly PSTraceSource Tracer = PSTraceSource.GetTracer("PSObjectHelper", "PSObjectHelper");
```
Comment (iSazonov) [inline src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs:25]:
```suggestion
        private static readonly PSTraceSource s_tracer = PSTraceSource.GetTracer("PSObjectHelper", "PSObjectHelper");
```

File: src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs [hunk 6]
```diff
@@ -290,10 +296,12 @@ internal static string SmartToString(PSObject so, PSPropertyExpressionFactory ex
...
                 return so.ToString();
             }
-            catch (ExtendedTypeSystemException e)
+            catch (Exception e) when (e is ExtendedTypeSystemException || e is InvalidOperationException)
             {
-                // NOTE: we catch all the exceptions, since we do not know
-                // what the underlying object access would throw
+                // These exceptions are being caught and handled by returning an empty string when
+                // the object cannot be stringified due to ETS or an instance in the collection has been modified
+                Tracer.WriteLine("Exception during conversion to string, emitting empty string.");
```
Comment (iSazonov) [inline src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs:303]: Maybe TraceWarning()?
```suggestion
                s_tracer.TraceWarning("SmartToString method: Exception during conversion to string, emitting empty string.");
```

**Review by iSazonov — APPROVED** [review]

**Comment by krishnayalavarthi** [comment]
@SteveL-MSFT Can we close this?

File: src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs [hunk 7]
```diff
@@ -290,10 +296,12 @@ internal static string SmartToString(PSObject so, PSPropertyExpressionFactory ex
...
                 return so.ToString();
             }
-            catch (ExtendedTypeSystemException e)
+            catch (Exception e) when (e is ExtendedTypeSystemException || e is InvalidOperationException)
             {
-                // NOTE: we catch all the exceptions, since we do not know
-                // what the underlying object access would throw
+                // These exceptions are being caught and handled by returning an empty string when
+                // the object cannot be stringified due to ETS or an instance in the collection has been modified
+                s_tracer.TraceWarning("SmartToString method: Exception during conversion to string, emitting empty string.");
```
Comment (rjmholt) [inline src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs:303]: Wonder if it's worth logging the exception here

**Review by rjmholt — APPROVED** [review]

**Review by PaulHigin — APPROVED** [review]

File: src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs (hunk 7 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs:303]: Good suggestion, will add Exception.Message
