### PR TITLE
Make `AnsiRegex` able to capture Hyperlink ansi sequences

### LINKED ISSUE #16420: Format-Table doesn't know about $psStyle.FormatHyperlink
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Format-Table is able to understand that escape sequences don't print when sizing text (otherwise nothing would align) but it has a blind spot when the sequence is for a URL 

`dir  | ft @{n="link";e={$PSStyle.FormatHyperlink($_.name, ("some random text as a link" + "x" * (random -Max 5) ) )}},  lastwritetime` 
Will demonstrate it 

### Expected behavior

```console
link                            LastWriteTime
----                            -------------
6Print                          13/11/2019 10:06:51
archive-vsteam                  13/09/2020 10:57:30
azure-devops-auth-samples       13/11/2019 17:48:16
blog                            25/08/2021 16:45:12
Exiftool                        01/07/2018 11:07:43
```

### Actual behavior

```console
link                                                                        LastWriteTime
----                                                                        -------------
6Print                            13/11/2019 10:06:51
archive-vsteam                    13/09/2020 10:57:30
azure-devops-auth-samples          13/11/2019 17:48:16
blog                            25/08/2021 16:45:12
Exiftool                            01/07/2018 11:07:43
```
```


### Error details

_No response_

### Environment data

```powershell
ame                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #16420
Make `AnsiRegex` able to capture Hyperlink ansi sequences.

With this fix, the repro `dir | ft @{n="link";e={$PSStyle.FormatHyperlink($_.name, ("some random text as a link" + "x" * (random -Max 5) ) )}}, lastwritetime` get the following output

image

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

**Review by iSazonov — APPROVED** [review]

**Review by PaulHigin — APPROVED** [review]

File: src/System.Management.Automation/FormatAndOutput/common/StringDecorated.cs [hunk 1]
```diff
@@ -109,8 +109,11 @@ private string PlainText
         // CSI escape sequences
         private const string CsiRegex = @"(\x1b\[\?\d+[hl])";
 
+        // Hyperlink escape sequences. Note: '.*?' makes '.*' do non-greedy match.
+        private const string HyperlinkRegex = @"(\x1b\]8;;.*?\x1b\\)";
```
Comment (SteveL-MSFT) [inline src/System.Management.Automation/FormatAndOutput/common/StringDecorated.cs:113]: Can we make this more specific instead of using `.*?` which accepts any characters up to an escape?

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]

File: src/System.Management.Automation/FormatAndOutput/common/StringDecorated.cs (hunk 1 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/FormatAndOutput/common/StringDecorated.cs:113]: A hyperlink sequence looks like this: ``"`e]8;;link-url-string`e\link-description-string`e]8;;`e\"``.

Good catch. This regex will remove the whole `link-url-string` which could contain arbitrary characters, such as `//`, `#`, or any other comment indicators in other languages.

I thought about doing validation on the `link-url-string` part and only treat it as hyperlink sequence if the `link-url-string` part is valid http/https urls. But that doesn't work because valid url can have `#` in it, which is the comment indicator for any scripting languages.

I think we need to fix `Out-File` to not change anything if the piped in object is text. It should do the VT sequence striping only when it has to go through the formatting system -- meaning only strip the VT sequences that are added during formatting.

Comment (daxian-dbw) [reply src/System.Management.Automation/FormatAndOutput/common/StringDecorated.cs:113]: Opened issue https://github.com/PowerShell/PowerShell/issues/17452, and also here is the PR to fix `Out-File` and `Out-String`: https://github.com/PowerShell/PowerShell/pull/17455. The proposed behavior for `Out-File` and `Out-String` is "Leave ANSI out of object formatting, but leave strings alone".

Comment (SteveL-MSFT) [reply src/System.Management.Automation/FormatAndOutput/common/StringDecorated.cs:113]: Yes, I think this is resolved

**Review by SteveL-MSFT — APPROVED** [review]
Ok with this change given the other PR

**Comment by jhoneill** [comment]
Confirmed that the original problem is newly fixed in 7.3 preview 5 - thanks everyone.
