### PR TITLE
Fix null reference when markdown content is empty

### LINKED ISSUE #7453: NullReferenceException in ConvertFrom-Markdown -AsVT100EncodedString with empty alt text
Steps to reproduce
------------------

```powershell
ConvertFrom-Markdown '![](https://raw.github.com/junegunn/i/master/fzf.gif)' -AsVT100EncodedString
```

This is a valid markdown (well any text is valid markdown really, but this one as well)
```
![](https://raw.github.com/junegunn/i/master/fzf.gif)
```

It produces the following:

Expected behavior
-----------------

No error

Actual behavior
---------------

```none
ConvertFrom-Markdown : A positional parameter cannot be found that accepts argument '![](https://raw.github.com/junegunn/i/master/fzf.gif)'.
At line:1 char:1
+ ConvertFrom-Markdown '![](https://raw.github.com/junegunn/i/master/fz ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [ConvertFrom-Markdown], ParameterBindingException
+ FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.ConvertFromMarkdownCommand
```

Stack Trace:

```
   at Microsoft.PowerShell.MarkdownRender.LinkInlineRenderer.Write(VT100Renderer renderer, LinkInline obj) in /PowerShell/src/Microsoft.PowerShell.MarkdownRender/LinkInlineRenderer.cs:line 22
   at Markdig.Renderers.RendererBase.Write[T](T obj)
   at Markdig.Renderers.RendererBase.WriteChildren(ContainerInline containerInline)
   at Microsoft.PowerShell.MarkdownRender.ParagraphBlockRenderer.Write(VT100Renderer renderer, ParagraphBlock obj) in /PowerShell/src/Microsoft.PowerShell.MarkdownRender/ParagraphBlockRenderer.cs:line 20
   at Markdig.Renderers.RendererBase.Write[T](T obj)
   at Markdig.Renderers.RendererBase.WriteChildren(ContainerBlock containerBlock)
   at Markdig.Renderers.RendererBase.Write[T](T obj)
   at Markdig.Renderers.TextRendererBase.Render(MarkdownObject markdownObject)
   at Microsoft.PowerShell.MarkdownRender.MarkdownConverter.Convert(String markdownString, MarkdownConversionType conversionType, MarkdownOptionInfo optionInfo) in /PowerShell/src/Microsoft.PowerShell.MarkdownRender/MarkdownConverter.cs:line 81
   at Microsoft.PowerShell.Commands.ConvertFromMarkdownCommand.ConvertEachFile(IEnumerable`1 paths, MarkdownConversionType conversionType, Boolean isLiteral, MarkdownOptionInfo optionInfo)
   at Microsoft.PowerShell.Commands.ConvertFromMarkdownCommand.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by adityapatwardhan**
Fix #7453

## PR Summary

Fix cases where markdown content can be empty and we get a null reference exception.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

File: src/Microsoft.PowerShell.MarkdownRender/HeaderBlockRenderer.cs [hunk 1]
```diff
@@ -16,38 +16,43 @@ internal class HeaderBlockRenderer : VT100ObjectRenderer<HeadingBlock>
     {
         protected override void Write(VT100Renderer renderer, HeadingBlock obj)
         {
-            // Format header and then add blank line to improve readability.
-            switch (obj.Level)
+            string headerText = obj.Inline?.FirstChild?.ToString();
```
Comment (iSazonov) [inline src/Microsoft.PowerShell.MarkdownRender/HeaderBlockRenderer.cs]: Should we check `obj != null` too?

File: src/Microsoft.PowerShell.MarkdownRender/LinkInlineRenderer.cs [hunk 2]
```diff
@@ -19,11 +19,11 @@ protected override void Write(VT100Renderer renderer, LinkInline obj)
             // Format link as image or link.
             if (obj.IsImage)
             {
-                renderer.Write(renderer.EscapeSequences.FormatImage(obj.FirstChild.ToString()));
+                renderer.Write(renderer.EscapeSequences.FormatImage(obj.FirstChild?.ToString()));
             }
             else
             {
-                renderer.Write(renderer.EscapeSequences.FormatLink(obj.FirstChild.ToString(), obj.Url));
+                renderer.Write(renderer.EscapeSequences.FormatLink(obj.FirstChild?.ToString(), obj.Url));
```
Comment (iSazonov) [inline src/Microsoft.PowerShell.MarkdownRender/LinkInlineRenderer.cs]: We check `obj.FirstChild != null` in both code path in the "if-else" - seems we should move the check to new "if":
```c#
if (obj.FirstChild != null)
{
    if (obj.IsImage)
    {
        renderer.Write(renderer.EscapeSequences.FormatImage(obj.FirstChild.ToString()));
    }
    else
    {
        renderer.Write(renderer.EscapeSequences.FormatLink(obj.FirstChild.ToString(), obj.Url));
    }
}

**Review by iSazonov — COMMENTED** [review]
I wonder that we have to check so many null references. Seems we need review all the code (not in the PR).

File: src/Microsoft.PowerShell.MarkdownRender/LinkInlineRenderer.cs (hunk 2 above)
Comment (rjmholt) [reply src/Microsoft.PowerShell.MarkdownRender/LinkInlineRenderer.cs]: The question marks here would have different semantics of course, but I imagine `FormatLink` will thrown an NRE if its first argument is `null`.

So I would do similar to @iSazonov (just a style change):
```csharp
if (obj.FirstChild == null)
{
    return;
}

if (obj.IsImage)
{
    renderer.Write(renderer.EscapeSequences.FormatImage(obj.FirstChild.ToString()));
}
else
{
    renderer.Write(renderer.EscapeSequences.FormatLink(obj.FirstChild.ToString(), obj.Url));
}
```

File: src/Microsoft.PowerShell.MarkdownRender/FencedCodeBlockRenderer.cs [hunk 3]
```diff
@@ -16,25 +16,28 @@ internal class FencedCodeBlockRenderer : VT100ObjectRenderer<FencedCodeBlock>
     {
         protected override void Write(VT100Renderer renderer, FencedCodeBlock obj)
         {
-            foreach (var codeLine in obj.Lines.Lines)
+            if (obj?.Lines != null && obj.Lines.Lines != null)
```
[the remark this answers is not in the document]
Comment (adityapatwardhan) [reply src/Microsoft.PowerShell.MarkdownRender/FencedCodeBlockRenderer.cs]: Updated to `obj?.Lines.Lines != null` 

`obj.Lines` is of type StringLineGroup which cannot be null.

File: src/Microsoft.PowerShell.MarkdownRender/FencedCodeBlockRenderer.cs [hunk 4]
```diff
@@ -16,25 +16,28 @@ internal class FencedCodeBlockRenderer : VT100ObjectRenderer<FencedCodeBlock>
...
             {
-                if (!string.IsNullOrWhiteSpace(codeLine.ToString()))
+                foreach (var codeLine in obj?.Lines.Lines)
```
[the remark this answers is not in the document]
Comment (adityapatwardhan) [reply src/Microsoft.PowerShell.MarkdownRender/FencedCodeBlockRenderer.cs]: Fixed

File: src/Microsoft.PowerShell.MarkdownRender/HeaderBlockRenderer.cs (hunk 1 above)
Comment (adityapatwardhan) [reply src/Microsoft.PowerShell.MarkdownRender/HeaderBlockRenderer.cs]: Fixed.

File: src/Microsoft.PowerShell.MarkdownRender/LinkInlineRenderer.cs (hunk 2 above)
Comment (adityapatwardhan) [reply src/Microsoft.PowerShell.MarkdownRender/LinkInlineRenderer.cs]: We support having empty alt-text for images and empty link text. So updated accordingly.

**Comment by adityapatwardhan** [comment]
@rjmholt @iSazonov Addressed the comments please have another look.

File: src/Microsoft.PowerShell.MarkdownRender/FencedCodeBlockRenderer.cs [hunk 5]
```diff
@@ -16,25 +16,28 @@ internal class FencedCodeBlockRenderer : VT100ObjectRenderer<FencedCodeBlock>
     {
         protected override void Write(VT100Renderer renderer, FencedCodeBlock obj)
         {
-            foreach (var codeLine in obj.Lines.Lines)
+            if (obj?.Lines.Lines != null)
             {
-                if (!string.IsNullOrWhiteSpace(codeLine.ToString()))
+                foreach (var codeLine in obj.Lines.Lines)
```
Comment (rjmholt) [inline src/Microsoft.PowerShell.MarkdownRender/FencedCodeBlockRenderer.cs]: `string` instead of `var` would be more obvious here

File: src/Microsoft.PowerShell.MarkdownRender/LinkInlineRenderer.cs [hunk 6]
```diff
@@ -16,14 +16,16 @@ internal class LinkInlineRenderer : VT100ObjectRenderer<LinkInline>
     {
         protected override void Write(VT100Renderer renderer, LinkInline obj)
         {
+            string text = obj?.FirstChild?.ToString();
+
             // Format link as image or link.
             if (obj.IsImage)
```
Comment (rjmholt) [inline src/Microsoft.PowerShell.MarkdownRender/LinkInlineRenderer.cs]: If `obj` is `null`, this will cause an NRE. Would the logic be preserved like this:
```csharp
string text = obj?.FirstChild?.ToString();
if (text == null)
{
    return;
}

// Golden path code...
```
?

File: src/Microsoft.PowerShell.MarkdownRender/FencedCodeBlockRenderer.cs (hunk 5 above)
Comment (adityapatwardhan) [reply src/Microsoft.PowerShell.MarkdownRender/FencedCodeBlockRenderer.cs]: Fixed

File: src/Microsoft.PowerShell.MarkdownRender/LinkInlineRenderer.cs (hunk 6 above)
Comment (adityapatwardhan) [reply src/Microsoft.PowerShell.MarkdownRender/LinkInlineRenderer.cs]: `obj` can never be null, hence removed `?` after `obj`.

We allow text to be null hence the above logic holds.

**Comment by adityapatwardhan** [comment]
@rjmholt Updated.

**Review by rjmholt — APPROVED** [review]
LGTM!

File: src/Microsoft.PowerShell.MarkdownRender/LinkInlineRenderer.cs (hunk 6 above)
Comment (iSazonov) [reply src/Microsoft.PowerShell.MarkdownRender/LinkInlineRenderer.cs]: ` if (obj.IsImage) ` - can cause an NRE.

Comment (adityapatwardhan) [reply src/Microsoft.PowerShell.MarkdownRender/LinkInlineRenderer.cs]: @iSazonov  `obj` is guaranteed to be not null. If it is null the renderer is not called.

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
@daxian-dbw @SteveL-MSFT The PR is ready to merge if you haven't comments.
