### PR TITLE
Void codemethod call should not crash

### LINKED ISSUE #4826: CodeMethod invoke fails with dot syntax but works with Foreach-Object -MemberName
Steps to reproduce
------------------

```powershell
using namespace System.Management.Automation
class Y{
    [int] $Id
}

class X{    
	static [void] OpenUri([psobject] $obj) {
		$id = $obj.Id
		start-process "http://baseuri/$id"
	}

    static [void] UpdateTypeData(){
        $td = [Runspaces.Typedata]::new([Y])		
		$td.Members.Add("OpenUri",
			[Runspaces.CodeMethodData]::new("OpenUri", [X]::GetMethodInfo([X], "OpenUri")));
		Update-TypeData -TypeData $td -Force
    }
    
    hidden static [Reflection.MethodInfo] GetMethodInfo([Type] $type, [string] $method) {
		return $type.GetMethod($method, [Reflection.BindingFlags]::Static -bor [Reflection.BindingFlags]::Public -bor [Reflection.BindingFlags]::IgnoreCase);
	}
}
[X]::UpdateTypeData()

$y = [Y]::new()

#works
$y | % OpenUri
#fails with No coercion operator is defined between types 'System.Void' and 'System.Object'.
$y.OpenUri()

```

Expected behavior
-----------------
Same behavior invoking method with dot syntax as when invoked via `Foreach-Object -MemberName`

Actual behavior
---------------
fails with
```
No coercion operator is defined between types 'System.Void' and 'System.Object'.
At line:1 char:1
+ $y.OpenUri()
```
```
PS C:\Program Files\PowerShell\6.0.0-beta.6> $y | gm

   TypeName: Y

Name        MemberType Definition
----        ---------- ----------
OpenUri     CodeMethod static void OpenUri(psobject obj)
```

Environment data
----------------
All versions (beta 6 and win 5.1)

### PR DESCRIPTION
**Pull request by powercode**
Fixes #4826 

Adding a check if the method to be called is void, and in that case wrap it in a block that returns null.

Looking at some other code, there seems to be a `CSharpBinderFlags.ResultDiscarded` when they to this in C#. Can reviewers please check if this or something similar needs to be used here?

### CODE REVIEW

File: src/System.Management.Automation/engine/runtime/Binding/Binders.cs [hunk 1]
```diff
@@ -6568,9 +6568,16 @@ public override DynamicMetaObject FallbackInvokeMember(DynamicMetaObject target,
             var codeMethod = methodInfo as PSCodeMethod;
             if (codeMethod != null)
             {
-                return new DynamicMetaObject(
-                    InvokeMethod(codeMethod.CodeReference, null, args.Prepend(target).ToArray(), false, MethodInvocationType.Ordinary)
-                    .Cast(typeof(object)), restrictions).WriteToDebugLog(this);
+                Expression expr = InvokeMethod(codeMethod.CodeReference, null, args.Prepend(target).ToArray(), false, MethodInvocationType.Ordinary);
+                if (codeMethod.CodeReference.ReturnType == typeof(void))
+                {
+                    expr = Expression.Block(expr, Expression.Default(typeof(object)));
```
Comment (lzybkr) [inline src/System.Management.Automation/engine/runtime/Binding/Binders.cs]: This should be:
```C#
                    expr = Expression.Block(expr, ExpressionCache.AutomationNullConstant);
```
Otherwise it might be possible to use the return value.

**Review by lzybkr — CHANGES_REQUESTED** [review]
Just one small change and I think it's good.

**Review by lzybkr — APPROVED** [review]
