### PR TITLE
Fix completion crash for the SCCM provider

### LINKED ISSUE #20803: Function & Cmdlet Name Tab Completion Broken in the ConfigManager (CMSITE) Provider
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

## Summary

7.4.0 seems to have broken cmdlet & function **name** tab completion for **all** cmdlet & functions while the location is set to the Config Manager provider (`CMSITE`). This was working just fine in previous versions of PowerShell 7.

## Scope

- Tab completion for cmdlet & function **parameter** names & values is **not** broken, even when the location is set to the `CMSITE` provider.
- Cmdlet & Function **name** tab completion is **not** broken when the location is set to **any** of the [built-in providers](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_providers?view=powershell-7.4#built-in-providers).
- I can reproduce this on multiple machines.

## Workaround

Reverting back to a previous version of PowerShell, i.e. `7.3.10`, fixes the issue.

## Background Info

My version of the `ConfigurationManager` module shouldn't matter since reverting back to PowerShell 7.3.10 fixes the issue, but just in case I am using version `5.2303.1089.1000` of the module.

## Setup Code

```
PS C:\> Import-Module ConfigurationManager
PS C:\> $SiteCode = Get-PSDrive -PSProvider CMSITE
PS C:\> Set-Location -Path "$($SiteCode.Name):\"
PS DCC:\> Get-Ite{Tab}
PS DCC:\> function Test-TabCompletion {}
PS DCC:\> Test-TabCompletio{Tab}
```

### Expected behavior

```console
PS DCC:\> Get-Item
PS DCC:\> Test-TabCompletion
```

### Actual behavior

```console
PS DCC:\> Get-Ite
PS DCC:\> Test-TabCompletio
```

### Error details

_No response_

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by MartinGC94**
# PR Summary
Supersedes https://github.com/PowerShell/PowerShell/pull/20815 and actually fixes the issue this time:
image

It turns out that the SCCM provider returns the items as strings and adds all the various PS* properties as NoteProperties and none of the PS* properties include the actual value, see:
image

## PR Context
Fixes https://github.com/PowerShell/PowerShell/issues/20803 (for real this time)

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [X] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs [hunk 1]
```diff
@@ -4857,10 +4857,22 @@ internal static IEnumerable<CompletionResult> CompleteFilename(CompletionContext
 
         private static string GetChildNameFromPsObject(dynamic psObject, char separator)
         {
-            // The obvious solution would be to use the "PSChildName" property
-            // but some providers don't have it (like the Variable provider)
-            // So we use a substring of "PSPath" instead.
-            string childName = psObject.PSPath ?? string.Empty;
+            if (((PSObject)psObject).BaseObject is string result)
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:4860]: Have you considered `PSObject.Base(psObject)`?

Comment (MartinGC94) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:4860]: No I didn't consider that. I've looked at the `Base` method and it does some unnecessary checks that makes it slower than just casting it. And I think the cast is needed because how else would I check that it's a string?

Comment (iSazonov) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:4860]: > how else would I check that it's a string?

psObject is dynamic.

Comment (MartinGC94) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:4860]: Elaborate please, I don't understand how the code would be written. Are you saying that: `psObject is string result` (where psObject is the variable name) would work the same way as the current code? My understanding is that I need to unwrap the PSObject before I can do the type check.

Comment (iSazonov) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:4860]: I think `if ((psObject.BaseObject is string result)` should work because old code was `string childName = psObject.PSPath ?? string.Empty;` - without cast.

**Comment by daxian-dbw** [comment]
@MartinGC94 https://github.com/PowerShell/PowerShell/pull/20815 was already merged, can you please rebase this PR against the master branch, so it's easy to see the changes on top?

**Comment by daxian-dbw** [comment]
@MartinGC94 Thanks for rebasing. A question before moving on to review the code: are the changes from #20815 still relevant? I assume those changes are relevant to the fix and should be kept but want you to confirm.

**Comment by MartinGC94** [comment]
@daxian-dbw They are not. I tried reverting them with https://github.com/PowerShell/PowerShell/pull/20915/commits/ab72ca78f2f5b0c7310e9510dde74b1f958b5bed but I don't see that in the changes overview https://github.com/PowerShell/PowerShell/pull/20915/files so I must be doing something wrong.

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs (hunk 1 above)
Comment (MartinGC94) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:4867]: I just tested it and it does not seem to work. I guess it's because the dynamic implementation on PSObject only looks for members on the unwrapped object with no fallback to the original PSObject properties. My `psObject is string result` idea also doesn't work.

**Comment by daxian-dbw** [comment]
> They are not. I tried reverting them with https://github.com/PowerShell/PowerShell/commit/ab72ca78f2f5b0c7310e9510dde74b1f958b5bed but I don't see that in the changes overview

Thanks for confirming. I submitted the https://github.com/PowerShell/PowerShell/pull/20919 to revert them then.

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs (hunk 1 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:4860]: > I just tested it and it does not seem to work. 

I wonder that `string childName = psObject.PSPath ?? string.Empty;` work. Exactly works? Or it is bug?
Maybe follow works:
```c#
object tmp = psObject.BaseObject;
if (tmp is string result)
...
```

I don't understand difference between `psObject.PSPath` and `psObject.BaseObject`. `PSPath` says that `psObject` is _always_ PSObject. Why do we define it as dynamic?
I tend to think that this code either doesn't work correctly or it's too gimmicky and at the very least needs refactoring.

Comment (MartinGC94) [reply src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:4860]: > I wonder that string childName = psObject.PSPath ?? string.Empty; work. Exactly works? Or it is bug?
The null check can probably be removed. I don't remember why I put it there but if it's null then there's something wrong so it's better to just throw.

> I don't understand difference between psObject.PSPath and psObject.BaseObject. PSPath says that psObject is always PSObject. Why do we define it as dynamic?
It's so we can access the dynamic members more easily. We could make it a PSObject and use the appropriate properties/methods to access those members but the old code used dynamic so I figured it was fine to use here during the rewrite.

**Comment by daxian-dbw** [comment]
@alexlarner could you please try this fix again and see if it solves the problem? Thanks!

**Comment by alexlarner** [comment]
> @alexlarner could you please try this fix again and see if it solves the problem? Thanks!

Yep, that did the trick. Thanks!

**Review by daxian-dbw — APPROVED** [review]

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs (hunk 1 above)
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:4860]:
```suggestion
            if (psObject.GetType() == typeof(string))
```

**Review by daxian-dbw — APPROVED** [review]
Simplify the string-type check a bit.

File: src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs [hunk 2]
```diff
@@ -4857,10 +4857,22 @@ internal static IEnumerable<CompletionResult> CompleteFilename(CompletionContext
...
         {
-            // The obvious solution would be to use the "PSChildName" property
-            // but some providers don't have it (like the Variable provider)
-            // So we use a substring of "PSPath" instead.
-            string childName = psObject.PSPath ?? string.Empty;
+            if (psObject.GetType() == typeof(string))
+            {
+                // The "Get-ChildItem" call for this provider returned a string that we assume is the child name.
+                // This is what the SCCM provider returns.
+                return result;
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs:4864]:
```suggestion
                return psObject.ToString();
```

**Review by daxian-dbw — APPROVED** [review]
