### PR TITLE
Change behavior of Remove-Item on symbolic links (#621)

### LINKED ISSUE #621: Fix Remove-Item <symbolic link to directory>
If you make a symbolic link to a directory on Windows (with administrative privileges of course), and then try to delete said link, you get this:

```
|Y> Yes |A> Yes to All |N> No |L> No to All |S> Suspend [Default is (Y]
PS C:\Users\anschwa\src\PowerShell> remove-item -Force .\foobar\
Confirm
The item at C:\Users\anschwa\src\PowerShell\foobar\ has children and the Recurse parameter was not specified. If you con
tinue, all children will be removed with the item. Are you sure you want to continue?

|Y> Yes |A> Yes to All |N> No |L> No to All |S> Suspend [Default is (Y]
n
PS C:\Users\anschwa\src\PowerShell> remove-item -Force .\foobar\ -Recurse
remove-item : There is a mismatch between the tag specified in the request and the tag present in the reparse point
At line:1 char:1
+ remove-item -Force .\foobar\ -Recurse
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-Item], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.RemoveItemCommand

PS C:\Users\anschwa\src\PowerShell> $error[0].Exception.StackTrace
   at Microsoft.PowerShell.Commands.InternalSymbolicLinkLinkCodeMethods.DeleteJunction(String junctionPath) in C:\Users\
anschwa\src\PowerShell\src\monad\monad\src\namespaces\FileSystemProvider.cs:line 8447
   at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveDirectoryInfoItem(DirectoryInfo directory, Boolean recurse,
 Boolean force, Boolean rootOfRemoval) in C:\Users\anschwa\src\PowerShell\src\monad\monad\src\namespaces\FileSystemProvi
der.cs:line 2859
   at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveItem(String path, Boolean recurse) in C:\Users\anschwa\src\
PowerShell\src\monad\monad\src\namespaces\FileSystemProvider.cs:line 2733
   at System.Management.Automation.Provider.ContainerCmdletProvider.RemoveItem(String path, Boolean recurse, CmdletProvi
derContext context) in C:\Users\anschwa\src\PowerShell\src\monad\monad\src\namespaces\ContainerProviderBase.cs:line 422
   at System.Management.Automation.SessionStateInternal.RemoveItem(CmdletProvider providerInstance, String path, Boolean
 recurse, CmdletProviderContext context) in C:\Users\anschwa\src\PowerShell\src\monad\monad\src\engine\SessionStateConta
iner.cs:line 1152
```

`Remove-Item` is thinking the link is a directory and so failing to delete it.

If the code is changed such that `File.Delete(junction)` is used instead of native calls, you get:

```
PS C:\Users\anschwa\src\PowerShell> rm .\foobar\ -Force
Confirm
The item at C:\Users\anschwa\src\PowerShell\foobar\ has children and the Recurse parameter was not specified. If you con
tinue, all children will be removed with the item. Are you sure you want to continue?

|Y> Yes |A> Yes to All |N> No |L> No to All |S> Suspend [Default is (Y]
y
rm : Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
At line:1 char:1
+ rm .\foobar\ -Force
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-Item], FormatException
    + FullyQualifiedErrorId : System.FormatException,Microsoft.PowerShell.Commands.RemoveItemCommand

PS C:\Users\anschwa\src\PowerShell> $error[0].Exception.StackTrace
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object arg0)
   at System.Management.Automation.Internal.StringUtil.Format(String formatSpec, Object o) in C:\Users\anschwa\src\Power
Shell\src\monad\monad\src\utils\StringUtil.cs:line 18
   at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveDirectoryInfoItem(DirectoryInfo directory, Boolean recurse,
 Boolean force, Boolean rootOfRemoval) in C:\Users\anschwa\src\PowerShell\src\monad\monad\src\namespaces\FileSystemProvi
der.cs:line 2863
   at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveItem(String path, Boolean recurse) in C:\Users\anschwa\src\
PowerShell\src\monad\monad\src\namespaces\FileSystemProvider.cs:line 2733
   at System.Management.Automation.Provider.ContainerCmdletProvider.RemoveItem(String path, Boolean recurse, CmdletProvi
derContext context) in C:\Users\anschwa\src\PowerShell\src\monad\monad\src\namespaces\ContainerProviderBase.cs:line 422
   at System.Management.Automation.SessionStateInternal.RemoveItem(CmdletProvider providerInstance, String path, Boolean
 recurse, CmdletProviderContext context) in C:\Users\anschwa\src\PowerShell\src\monad\monad\src\engine\SessionStateConta
iner.cs:line 1152
```

It fails even sooner (I think because there aren't actually any children to pass delete recursively, so it gets an empty list; just a guess).

If you use `Directory.Delete(junctionPath)`, it works just fine!

### PR DESCRIPTION
**Pull request by jeffbi**
When `Remove-Item` is used to remove a symbolic link in Windows, only the link itself is removed. The `-Force` switch is no longer required.

If the directory pointed to by the link has child items, the cmdlet no longer prompts the user to remove the child items---those child items are *not* removed. The `-Recurse` switch, if given, is ignored.

This brings `Remove-Item more in line with the behavior of the 'rm'` command on Unix.

Partially fix #621

### CODE REVIEW

**Comment by PaulHigin** [comment]
Please provide more information on the issue along with example of current behavior and example of expected behavior.  What do you expect the recursive switch parameter to do, remove all files as well?  This sounds like a breaking change (Remove-Item no longer just removes a symbolic link) and if so we should mark this PR accordingly.  Also please discuss the fix.  It is not clear to me how these changes solve the problem.

**Comment by daxian-dbw** [comment]
Close/Reopen the PR to trigger the stuck CI build.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 1]
```diff
@@ -2863,15 +2863,6 @@ private void RemoveDirectoryInfoItem(DirectoryInfo directory, bool recurse, bool
                 continueRemoval = ShouldProcess(directory.FullName, action);
             }
 
-            //if this is a reparse point and force is not specified then warn user but dont remove the directory.
```
Comment (PaulHigin) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Why is this removed.  It seems like the -Force parameter was required before removing and was Windows only.  So I assume removing this requirement makes Windows and Linux behavior the same.  Please make this clear in the PR description.

Also if we remove this code we should also remove the associated FileSystemProviderStrings.DirectoryReparsePoint message string since it is no longer used.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 2]
```diff
@@ -3327,13 +3318,14 @@ protected override bool HasChildItems(string path)
...
 
             // First check to see if it is a directory
-
             try
             {
                 DirectoryInfo directory = new DirectoryInfo(path);
 
                 // If the above didn't throw an exception, check to
-                // see if it contains any directories
+                // see if we should proceed and if it contains any children
```
Comment (PaulHigin) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: This is a bit surprising.  What case does this cover where an exception is not thrown but Attributes is not Directory?  Please add a comment to clarify.

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 [hunk 3]
```diff
@@ -246,6 +246,171 @@ Describe "Basic FileSystem Provider Tests" -Tags "CI" {
     }
 }
 
+Describe "Hard link and symbolic link tests" -Tags "CI", "RequireAdminOnWindows" {
```
Comment (PaulHigin) [inline test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1]: Your description mentions that the -Recurse parameter switch was ignored.  But I don't see any tests to verify that it is fixed.

**Review by PaulHigin — CHANGES_REQUESTED** [review]

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 2 above)
Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: The `DirectoryInfo` constructor will succeed if the given path does not exist or if it actually refers to a file. In the former case the `Exists` property will be false, in the latter the `Attributes` property will lack the `Directory` attribute.

The myriad other ways the constructor will fail are explicitly called out in the various `catch` blocks.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 1 above)
Comment (jeffbi) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: I've updated the PR description and removed the unused DirectoryReparsePoint message string.

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 (hunk 3 above)
Comment (jeffbi) [inline test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1]: Added a test using the -Recurse parameter when removing a symlink to a directory

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 [hunk 4]
```diff
@@ -409,6 +409,21 @@ Describe "Hard link and symbolic link tests" -Tags "CI", "RequireAdminOnWindows"
...
+            $link = Join-Path $TestDrive "sym-to-folder"
+            New-Item -ItemType Directory -Path $folder >$null
+            New-Item -ItemType File -Path $file -Value "some content" >$null
+            New-Item -ItemType SymbolicLink -Path $link -value $folder >$null
+            $childA = Get-Childitem $folder
+            Remove-Item -Path $link -Recurse
+            $childB = Get-ChildItem folder
+            $childB.Count | Should Be 1
+            $childB.Count -eq $childA.Count | Should Be $true
+            $childB.Name -eq $childA.Name | Should Be $true
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1]: Please use common template:
```powershell
$childB.Count | Should BeExactly $childA.Count
$childB.Name  | Should BeExactly $childA.Name 
```

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 [hunk 5]
```diff
@@ -409,6 +409,21 @@ Describe "Hard link and symbolic link tests" -Tags "CI", "RequireAdminOnWindows"
...
+
+        It "Remove-Item ignores -Recurse switch when deleting symlink to directory" {
+            $folder = Join-Path $TestDrive "folder"
+            $file = Join-Path $TestDrive "folder" "file"
+            $link = Join-Path $TestDrive "sym-to-folder"
+            New-Item -ItemType Directory -Path $folder >$null
+            New-Item -ItemType File -Path $file -Value "some content" >$null
+            New-Item -ItemType SymbolicLink -Path $link -value $folder >$null
+            $childA = Get-Childitem $folder
+            Remove-Item -Path $link -Recurse
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1]: Should we use `-Force` and `-ErrorAction SilentlyContinue` or maybe `-ErrorAction Continue`?

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 [hunk 6]
```diff
@@ -246,6 +246,186 @@ Describe "Basic FileSystem Provider Tests" -Tags "CI" {
...
+        New-Item -ItemType Directory -Path $realDir >$null
+    }
+
+    Context "New-Item and hard/symbolic links" {
+        It "New-Item can create a hard link to a file" {
+            New-Item -ItemType HardLink -Path $hardLinkToFile -Value $realFile
+            Test-Path $hardLinkToFile | Should Be $true
+            $link = Get-Item -Path $hardLinkToFile
+            $link.LinkType | Should Be "HardLink"
+            Get-Content -Path $hardLinkToFile | Should be $fileContent
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1]: I would prefer `BeExactly` for _strings_ in all test in the file.

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 [hunk 7]
```diff
@@ -246,6 +246,186 @@ Describe "Basic FileSystem Provider Tests" -Tags "CI" {
...
+                    Name = "Remove-Item can remove a symbolic link to a file"
+                    Link = $symLinkToFile
+                    Target = $realFile
+                }
+            )
+
+            # New-Item on Windows will not create a "plain" symlink to a directory
+            $unixTestCases = @(
+                @{
+                    Name = "Remove-Item can remove a symbolic link to a directory"
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1]: Plaese add "on Unix" in titles.

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 [hunk 8]
```diff
@@ -246,6 +246,186 @@ Describe "Basic FileSystem Provider Tests" -Tags "CI" {
...
+                    Link = $symLinkToDir
+                    Target = $realDir
+                }
+            )
+
+            # Junctions and directory symbolic links are Windows and NTFS only
+            $windowsTestCases = @(
+                @{
+                    Name = "Remove-Item can remove a symbolic link to a directory"
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1]: Plaese add "on Windows" in titles.

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 (hunk 5 above)
Comment (jeffbi) [inline test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1]: Not quite clear on this one. This test shows that when we use `-Recurse` when deleting a symlink, it is ignored. `Remove-Item` should not *fail* in this circumstance, it should just remove the symlink without even trying to recurse into the linked-to directory.

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 (hunk 4 above)
Comment (jeffbi) [inline test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1]: Fixed

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 (hunk 6 above)
Comment (jeffbi) [inline test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1]: Fixed.

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 (hunk 7 above)
Comment (jeffbi) [inline test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1]: Fixed.

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 (hunk 8 above)
Comment (jeffbi) [inline test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1]: Fixed.

**Comment by jeffbi** [comment]
@PaulHigin @iSazonov Can I get an updated review, please?

**Review by PaulHigin — APPROVED** [review]
LGTM

**Comment by daxian-dbw** [comment]
@jeffbi The tests are beautiful. Thanks!

**Comment by daxian-dbw** [comment]
Thanks @iSazonov and @PaulHigin for the review!

**Comment by iSazonov** [comment]
@jeffbi Great work! Thanks!

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 [hunk 9]
```diff
@@ -246,6 +246,186 @@ Describe "Basic FileSystem Provider Tests" -Tags "CI" {
...
+                    Link = $symLinkToDir
+                    Target = $realDir
+                }
+                @{
+                    Name = "Remove-Item can remove a directory symbolic link to a directory on Windows"
+                    Link = $dirSymLinkToDir
+                    Target = $realDir
+                }
+                @{
+                    Name = "Remove-Item can remove a junction to a directory"
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1]: "on Windows" skipped 😄
