### PR TITLE
Fix formatting truncation to handle strings with VT sequences

### LINKED ISSUE #16700: Console output truncated with an ellipsis causes remaining text to shift to the left when using $PSStyle
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Console output truncated with an ellipsis causes remaining text to shift to the left when using $PSStyle

I have a .ps1xml format file that defines a view for file and directory objects which uses $PSStyle to highlight parts of the output, e.g.:
```
<?xml version="1.0" encoding="utf-8"?>
<Configuration>
    <SelectionSets>
        <SelectionSet>
            <Name>FileSystemTypes</Name>
            <Types>
                <TypeName>System.IO.DirectoryInfo</TypeName>
                <TypeName>System.IO.FileInfo</TypeName>
            </Types>
        </SelectionSet>
    </SelectionSets>
    <ViewDefinitions>
        <View>
            <Name>children</Name>
            <ViewSelectedBy>
                <SelectionSetName>FileSystemTypes</SelectionSetName>
            </ViewSelectedBy>
            <TableControl>
                <TableHeaders>
                    <TableColumnHeader> <Label>Name</Label>                <Width>30</Width>  <Alignment>Left</Alignment>  </TableColumnHeader>
                    <TableColumnHeader> <Label>LastWriteTime      </Label> <Width>19</Width>  <Alignment>Left</Alignment>  </TableColumnHeader>
                    <TableColumnHeader> <Label>Size      </Label>          <Width>10</Width>  <Alignment>Right</Alignment> </TableColumnHeader>
                    <TableColumnHeader> <Label>FullName</Label>                               <Alignment>Left</Alignment>  </TableColumnHeader>
                </TableHeaders>
                <TableRowEntries>
                    <TableRowEntry>
                        <TableColumnItems>
                            <TableColumnItem>
                                <ScriptBlock>
                                    "$($PSStyle.Reverse)$($_.Name)$($PSStyle.Reset)"
                                </ScriptBlock>
                            </TableColumnItem>
                            <TableColumnItem>
                                <ScriptBlock>
                                    $_.LastWriteTime.ToString('yyyy-MM-dd HH:mm:ss')
                                </ScriptBlock>
                            </TableColumnItem>
                            <TableColumnItem>
                                <ScriptBlock>
                                    ($_.Length/1MB).ToString('0.000')+' MB'
                                </ScriptBlock>
                            </TableColumnItem>
                            <TableColumnItem>
                                <ScriptBlock>
                                    $_.FullName
                                </ScriptBlock>
                            </TableColumnItem>
                        </TableColumnItems>
                    </TableRowEntry>
                </TableRowEntries>
            </TableControl>
        </View>
    </ViewDefinitions>
</Configuration>
```

```
$filePath = 'D:\my.format.ps1xml'
Update-FormatData -PrependPath $filePath
Get-ChildItem -Path $PSHOME -File
```

When the `Name` column contains a long file name, the console truncates the name and adds an ellipsis `…` to indicate that there are truncated characters. When this happens, the remaining characters on the line are shifted 3 spaces to the left:
image

Removing the references to $PSStyle in the .ps1xml format file gives the expected layout:
image

The shift effect is present for any value of $PSStyle.OutputRendering.

### Expected behavior

```console
Output text on lines with a truncation ellipsis should remain aligned with its column header.
```

### Actual behavior

```console
Output text on lines with a truncation ellipsis is shifted to the left.
```

### Error details

```console
n/a
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #16700

Fix formatting truncation to handle strings with VT sequences.
The main changes are in buffer cell length calculation, as well as adding `VtSubstring` implementations, which are used to get part of a string that may contain escape sequences.

With the changes in this PR, the formatting works fine with the demo scripts from https://github.com/PowerShell/PowerShell/issues/16700#issuecomment-1103474523 and https://github.com/PowerShell/PowerShell/issues/16700#issuecomment-1103486148:

```pwsh
function Get-DemoObjects {
    [PSCustomObject]@{PSTypeName = "User"; Name = "Bob Saggat"; Tenure = 2; Role = "Developer" }
    [PSCustomObject]@{PSTypeName = "User"; Name = "John Seymour"; Tenure = 6; Role = "Sw Engineer" }
    [PSCustomObject]@{PSTypeName = "User"; Name = "Billy Bob Thorton"; Tenure = 13; Role = "Senior DevOps Engineer" }
}

Get-DemoObjects |
    Format-Table @{Width = 10; Name = "Name"; E = { (@("`e[32m", "`e[34m", "`e[33m", "`e[31m", "`e[33m", "`e[34m", "`e[32m")[[array]::BinarySearch(@(3, 5, 8), $_.Tenure)]) + $_.Name + "`e[39m"}},
                 @{Width = 15; Name = "Role";  E = { $_.Role }}, 
                 @{Width = 3; Name = "YIR";  E = { $_.Tenure }}
```

image

```pwsh
Get-DemoObjects |
    Format-Table @{Width = 10; Name = "Name"; E = { (@("`e[32m", "`e[34m", "`e[33m", "`e[31m", "`e[33m", "`e[34m", "`e[32m")[[array]::BinarySearch(@(3, 5, 8), $_.Tenure)]) + $_.Name + "`e[39m"}},
                 @{Width = 15; Name = "Role";  E = {
                                -join $(switch -regex ($_.Role){
                                        "Senior" { "`e[42m" }
                                        "Engineer" { "`e[1;33m" }
                                    }) + $_.Role  + "`e[0m"}}, 
                 @{Width = 3; Name = "YIR";  E = { $_.Tenure }}
```
image

```pwsh
$PSStyle.OutputRendering = "Ansi"
(Get-DemoObjects) + (Get-DemoObjects) + 
(Get-DemoObjects) + (Get-DemoObjects) + 
(Get-DemoObjects) + (Get-DemoObjects) | 
    Format-Wide @{E = { (@("`e[32m", "`e[34m", "`e[33m", "`e[31m", "`e[33m", "`e[34m", "`e[32m")[[array]::BinarySearch(@(3, 5, 8), $_.Tenure)]) + $_.Name + "`e[39m"}} -co 2 | Out-String -Width 47
```
image

```pwsh
Get-DemoObjects | Format-Table @{Width = 10; Name = "Name"; E = { "`e[33m" + $_.Name } }, 
                               @{Width = 15; Name = "Role"; E = { $_.Role }},
                               @{Width = 3;  Name = "YIR";  E = { $_.Tenure }}

Get-DemoObjects | Format-Table @{Width = 10; Name = "Name"; E = { "`e[1;33m" + $_.Name } }, 
                               @{Width = 15; Name = "Role"; E = { $_.Role }},
                               @{Width = 3;  Name = "YIR";  E = { $_.Tenure }}
```
image

Using the repro provided in https://github.com/PowerShell/PowerShell/issues/16700#issue-1093826191, now the formatting truncation and alignment work as expected:

image

`Out-String` works as well:

image

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

File: src/System.Management.Automation/FormatAndOutput/out-console/ConsoleLineOutput.cs [hunk 1]
```diff
@@ -163,6 +87,11 @@ internal sealed class ConsoleLineOutput : LineOutput
         internal static readonly PSTraceSource tracer = PSTraceSource.GetTracer("ConsoleLineOutput", "ConsoleLineOutput");
         #endregion tracer
 
+        /// <summary>
+        /// The default buffer cell calculation already works for the PowerShell console host and Visual studio code host.
+        /// </summary>
+        private static readonly HashSet<string> s_psHost = new(StringComparer.Ordinal) { "ConsoleHost", "Visual Studio Code Host" };
```
Comment (daxian-dbw) [inline src/System.Management.Automation/FormatAndOutput/out-console/ConsoleLineOutput.cs:93]: @SeeminglyScience Now that the default buffer cell calculation takes into account escape sequences and CJK characters, I think we can make `ConsoleHost` and VSCode host to use the default `DisplayCells` instead of calling into the host specific `LengthInBufferCells` method. Let me know if you have any concerns.

**Review by PaulHigin — APPROVED** [review]
LGTM

File: src/System.Management.Automation/FormatAndOutput/out-console/ConsoleLineOutput.cs (hunk 1 above)
Comment (SeeminglyScience) [reply src/System.Management.Automation/FormatAndOutput/out-console/ConsoleLineOutput.cs:93]: > @SeeminglyScience Now that the default buffer cell calculation takes into account escape sequences and CJK characters, I think we can make `ConsoleHost` and VSCode host to use the default `DisplayCells` instead of calling into the host specific `LengthInBufferCells` method. Let me know if you have any concerns.

I agree! VSCode just redirects to `ConsoleHost*`'s implementation so shouldn't need any changes there.

Also does this mean that piping to line output writers that aren't host aware should work now too? 😮 (e.g. `Out-String` and `less.exe` would calculate the wrong value width because they never call `LengthInBufferCells`)

**Review by SeeminglyScience — APPROVED** [review]
Very clever fix, well done! LGTM ❤️
