### PR TITLE
Fix constructing PSModulePath if a sub-path has trailing separator

### LINKED ISSUE #13025: Concatenated PSModulePath values for PS7 module paths
I'm seeing an oddity on one desktop whereby the two module paths for PS7 are concatenated rather than split by a comma and this results in modules not being loaded.

## Steps to reproduce

```
[Environment]::GetEnvironmentVariable("PSModulePath", "Process") -split ';' | sort
```

## Expected behavior

```
C:\Program Files\PowerShell\Modules\
c:\program files\powershell\7\Modules
```

## Actual behavior

```
C:\Program Files\PowerShell\Modules\c:\program files\powershell\7\Modules
```
or in full:
```
C:\Users\Robin\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules\c:\program files\powershell\7\Modules;;C:\Program Files\WindowsPowerShell\Modules\;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;
```
- note the double ;;

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ÔÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

When constructing PSModulePath, the code checks if one of user path, shared path, or $PSHome path is already part of PSModulePath.  The code that does the check trims whitespace and trailing path separator.  So if one of those paths match, but actually has whitespace or trailing separator, then the index doesn't take that into account and subsequent paths are inserted in the wrong location creating an invalid path.

The fix is if one of those paths are found, then find the next index of the path separator and insert at that index.  If there is no path separator after that index, then it just gets appended to the end.

Spent too much time trying to add a test.  The repro requires changing the system environment variable for PSModulePath and a new process to be started so that it's not inherited from an existing PowerShell process.  Validated manually.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/13025

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by rjmholt** [comment]
@SteveL-MSFT are you planning on re-adding a new test?

File: src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs [hunk 1]
```diff
@@ -1211,9 +1211,21 @@ public static string GetModulePath(string currentProcessModulePath, string hklmM
                 // sharedModulePath
                 // systemModulePath
                 currentProcessModulePath = AddToPath(currentProcessModulePath, personalModulePathToUse, 0);
-                int insertIndex = PathContainsSubstring(currentProcessModulePath, personalModulePathToUse) + personalModulePathToUse.Length + 1;
+                int insertIndex = currentProcessModulePath.IndexOf(Path.PathSeparator, PathContainsSubstring(currentProcessModulePath, personalModulePathToUse));
```
Comment (rjmholt) [inline src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs:1214]: Does the issue also occur when the alternate path separator is used? By this I include `\` on Unix, even though that isn't `Path.AlternatePathSeparator` there

Comment (vexx32) [reply src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs:1214]: @rjmholt I think you're thinking of `AlternateDirectorySeparatorChar`; I don't think there is an `AlternatePathSeparator` (`:` on Unix, `;` on Windows). As long as we're targeting the path separator itself, we should be OK here 🙂

Comment (rjmholt) [reply src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs:1214]: Oh, yep, got those confused. Read the "sub-path trailing separator" as "trailing directory separator" rather than "trailing path separator"

Comment (vexx32) [reply src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs:1214]: Every. Single. Time. 

I _wish_ they'd rename them, I don't know a single person who _hasn't_ confused them at least a dozen times. 😂

**Comment by SteveL-MSFT** [comment]
I might have to use a test hook to be able to add a test, need to think more about this.

**Comment by iSazonov** [comment]
I suggest add xUnit test. It is more fast and simple.

**Review by iSazonov — APPROVED** [review]
Downloaded artifact works well.

File: test/powershell/engine/Module/ModulePath.Tests.ps1 [hunk 2]
```diff
@@ -187,4 +187,11 @@ Describe "SxS Module Path Basic Tests" -tags "CI" {
             Remove-Item -Path $userConfigPath -Force
         }
     }
+
+    It 'User PSModulePath has trailing separator' -Skip:(!$IsWindows) {
```
Comment (rjmholt) [inline test/powershell/engine/Module/ModulePath.Tests.ps1:191]: What's the reason this only works on Windows?

Comment (iSazonov) [reply test/powershell/engine/Module/ModulePath.Tests.ps1:191]: Only Windows has pre-defined `PSModulePath`.

Comment (rjmholt) [reply test/powershell/engine/Module/ModulePath.Tests.ps1:191]: There are scenarios where it's pre-defined on *nix:

- Nested PowerShell process
- Environment variable set before startup

Comment (iSazonov) [reply test/powershell/engine/Module/ModulePath.Tests.ps1:191]: I mean the test :-)

Comment (rjmholt) [reply test/powershell/engine/Module/ModulePath.Tests.ps1:191]: Those both seem like scenarios we could test without too much trouble. Certainly (2) is just a case of setting the variable before the invocation and unsetting it afterward

Comment (SteveL-MSFT) [reply test/powershell/engine/Module/ModulePath.Tests.ps1:191]: The real world scenario where this happens is only if the env var in the registry has a trailing slash.  In other cases, I couldn't get the problem to repro which is why I had a hard time adding a test case that failed without the fix.  This test emulates that behavior by adding the slash to the user path and removing the shared path so that it gets inserted.

Comment (SteveL-MSFT) [reply test/powershell/engine/Module/ModulePath.Tests.ps1]: I think I can update the test to be cross platform

**Review by rjmholt — APPROVED** [review]

**Comment by rjmholt** [comment]
I'm hoping @daxian-dbw will also have a chance to review this this week

**Comment by rjmholt** [comment]
@PoshChan please remind me in 10 days

**Comment by rjmholt** [comment]
@daxian-dbw please take a moment to review this if you have time

File: src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs (hunk 1 above)
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs:1214]: The logic looks still pretty fragile. For example:
1. When `personalModulePathToUse` contains multiple paths separated by `;`, `AddToPath(currentProcessModulePath, personalModulePathToUse, 0)` basically will reverse the order of paths in `personalModulePathToUse` when inserting at index 0. Then when the code flow reaches here, `PathContainsSubstring(currentProcessModulePath, personalModulePathToUse)` will return -1 because the path order was reversed in `AddToPath`;

1. When `personalModulePathToUse` contains `;;` in it, then `PathContainsSubstring(currentProcessModulePath, personalModulePathToUse)` is likely to return -1.

In those 2 cases (maybe more), this will fail with `ArgumentOutOfRangeException`.

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs:1214]: How about updating `AddToPath`, to make it return the next index to insert the next module path?

Comment (SteveL-MSFT) [reply src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs:1214]: `personalModulePathToUse` is a single path so it can't contain `;;` in it nor be multiple paths unless someone deliberately put that into `powershell.config.json`

**Comment by TravisEz13** [comment]
@SteveL-MSFT If this is still needed, can you resolve the conflicts
