### PR TITLE
Fix empty file when redirecting both stdout and stderr

### LINKED ISSUE #20747: 7.4.0 Redirecting stdout and stderr to Two Separate Files Leaves Empty Files
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When I redirect the output and error streams of a native command to two separate files (when I know the command writes to the error stream), both files are created but they are both empty. The error file should contain content. If I redirect only the error stream, the file will contain the correct content.

Here I'm using `dotnet` as an example but the same thing happens with other commands. If you run `dotnet garbage` it will write to the error stream.

```
dotnet >x.txt 2>y.txt garbage
```

### Expected behavior

```console
PS> dotnet >x.txt 2>y.txt garbage
                                                                                                              PS> Get-Content y.txt
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'garbage' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet-download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
```

### Actual behavior

```console
PS> dotnet >x.txt 2>y.txt garbage
                                                                                                                                                                                 PS> Get-Content y.txt
                                                                                                                                                                                 PS> dotnet 2>y.txt garbage
                                                                                                                                                                                 PS> Get-Content y.txt
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-garbage does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

### Error details

```console
N/A
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

image

image

### PR DESCRIPTION
**Pull request by SeeminglyScience**
Fixes #20747

# PR Summary

Note I can't actually get `Start-PSPester` working locally for some reason, so I'll get to test failures if they come up.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

File: test/tools/TestExe/TestExe.cs [hunk 1]
```diff
@@ -36,6 +36,10 @@ private static int Main(string[] args)
                     case "-stderr":
                         Console.Error.WriteLine(args[1]);
                         break;
+                    case "-stderrandout":
+                        Console.WriteLine(args[1]);
+                        Console.Error.WriteLine(args[1]);
```
Comment (SteveL-MSFT) [inline test/tools/TestExe/TestExe.cs:41]: seems like it would be better if stderr had different output to stdout.  Maybe just reverse the text content for stderr?

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]

File: test/tools/TestExe/TestExe.cs (hunk 1 above)
Comment (SeeminglyScience) [reply test/tools/TestExe/TestExe.cs:41]: Makes sense! Added

**Review by SteveL-MSFT — APPROVED** [review]

File: src/System.Management.Automation/engine/NativeCommandProcessor.cs [hunk 2]
```diff
@@ -843,7 +846,7 @@ private ProcessOutputObject DequeueProcessOutput(bool blocking)
             }
             else
             {
-                if (_stdOutByteTransfer is not null)
+                if (_stdOutByteTransfer is not null && !_nativeProcess.StartInfo.RedirectStandardError)
```
[the remark this answers is not in the document]
Comment (daxian-dbw) [reply src/System.Management.Automation/engine/NativeCommandProcessor.cs:849]: For example:
```c#
private void ConsumeAvailableNativeProcessOutput(bool blocking)
{
    if (_isRunningInBackground)
    {
        return;
    }

    if (_nativeProcess.StartInfo.RedirectStandardOutput && _stdOutByteTransfer is not null)
    {
        if (blocking)
        {
            _stdOutByteTransfer.EOF.GetAwaiter().GetResult();
        }

        if (!_nativeProcess.StartInfo.RedirectStandardError)
        {
            return;
        }
    }

    if (_nativeProcess.StartInfo.RedirectStandardOutput || _nativeProcess.StartInfo.RedirectStandardError)
    {
        ProcessOutputObject record;
        while ((record = DequeueProcessOutput(blocking)) != null)
        {
            if (this.Command.Context.CurrentPipelineStopping)
            {
                this.StopProcessing();
                return;
            }

            ProcessOutputRecord(record);
        }
    }
}
```

[the remark this answers is not in the document]
Comment (SeeminglyScience) [reply src/System.Management.Automation/engine/NativeCommandProcessor.cs:849]: I think so! Good call let me try it

File: src/System.Management.Automation/engine/NativeCommandProcessor.cs [hunk 3]
```diff
@@ -861,19 +847,36 @@ private void ConsumeAvailableNativeProcessOutput(bool blocking)
         {
             if (!_isRunningInBackground)
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/NativeCommandProcessor.cs:848]:
```suggestion
            if (_isRunningInBackground)
```

**Review by daxian-dbw — CHANGES_REQUESTED** [review]

File: src/System.Management.Automation/engine/NativeCommandProcessor.cs (hunk 3 above)
Comment (SeeminglyScience) [reply src/System.Management.Automation/engine/NativeCommandProcessor.cs]: Good catch! ❤️

**Review by daxian-dbw — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
Before backporting to 7.4.x, we should wait on this to be included in a Preview release.
