### PR TITLE
Fix for files/folders not created when given path is drive root (#5228)

### LINKED ISSUE #5228: New-Item ignore's Path param if Name param is specified
Steps to reproduce
------------------

```powershell
Set-Location ~
New-Item -Path C:\ -Name Test -ItemType Directory -Verbose
```

Expected behavior
-----------------

```none
Test folder created in Root C:\
```

Actual behavior
---------------

```none
Folder created in current path
PS C:\Users\Aftab> New-Item -Path C:\ -Name Test -ItemType Directory -Verbose
VERBOSE: Performing the operation "Create Directory" on target "Destination: C:\Users\Aftab\Test".


    Directory: C:\Users\Aftab


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       25/10/2017     13:51                Test


PS C:\Users\Aftab> Get-Item C:\Test
Get-Item : Cannot find path 'C:\Test' because it does not exist.
At line:1 char:1
+ Get-Item C:\Test
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Test:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

PS C:\Users\Aftab> Get-Item ~\Test


    Directory: C:\Users\Aftab


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       25/10/2017     13:51                Test
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta.8
PSEdition                      Core
GitCommitId                    v6.0.0-beta.8
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by ghost**
## PR Summary

If the `Path` argument to `New-Item` is the root of a drive such as `C:\`, the LocationGlobber attempts to generate a drive root relative path from the path `C:`. `GetDriveRootRelativePathFromPSPath` determines that this is an absolute path, and strips the drive name and colon from the path; originally, this would result in `GenerateRelativePath` determining that the current working directory should be given as the relative path. Now, a check is made on whether stripping the drive name and colon results in an empty string; if it does, the root of the current PSDrive `context.Drive.Root` is returned as the relative path.

This fixes #5228.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [X] Issue filed - Issue link: https://github.com/PowerShell/PowerShell/issues/5228#
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by mcbobke** [comment]
@iSazonov new PR with branch workon5228.

**Comment by daxian-dbw** [comment]
@adityapatwardhan and @anmenaga, can you please review this PR?

File: src/System.Management.Automation/namespaces/LocationGlobber.cs [hunk 1]
```diff
@@ -2111,14 +2120,23 @@ internal bool IsShellVirtualDrive(string driveName, out SessionStateScope scope)
...
                 context.Drive = workingDriveForPath;
 
-                string relativePath =
-                    GenerateRelativePath(
-                        workingDriveForPath,
-                        path,
-                        escapeCurrentLocation,
-                        providerInstance,
-                        context);
+                string relativePath = "";
```
Comment (adityapatwardhan) [inline src/System.Management.Automation/namespaces/LocationGlobber.cs]: use `String.Empty`

File: src/System.Management.Automation/namespaces/LocationGlobber.cs [hunk 2]
```diff
@@ -2080,6 +2083,12 @@ internal bool IsShellVirtualDrive(string driveName, out SessionStateScope scope)
                         // this is the default behavior for all windows drives, and all non-filesystem
                         // drives on non-windows
                         path = path.Substring(driveName.Length + 1);
+
+                        if (path == "")
+                        {
+                            // path is to the root of a drive such as "C:\" or "C:"
```
Comment (adityapatwardhan) [inline src/System.Management.Automation/namespaces/LocationGlobber.cs]: The path has to be like `c:` for this to happen not "c:\". Please update comment.

**Review by adityapatwardhan — CHANGES_REQUESTED** [review]

**Comment by adityapatwardhan** [comment]
This change can affect a lot of scenarios, please add the `[Feature]` tag to the last commit so additional tests can be run. https://github.com/PowerShell/PowerShell/blob/6ef94c1dfe912ce18f93c05ce5362bbce2284291/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr

**Review by adityapatwardhan — APPROVED** [review]

File: test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1 [hunk 3]
```diff
@@ -117,6 +117,33 @@ Describe "New-Item" -Tags "CI" {
         $fileInfo.Target | Should -BeNullOrEmpty
         $fileInfo.LinkType | Should -BeExactly "HardLink"
     }
+
+    It "Should create a file at the root of the drive while the current working directory is not the root" {
```
Comment (daxian-dbw) [inline test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1]: The tests are wrong. They pass even without changes in this PR.

To repro this issue using "TestDrive:\", you need to first `Set-Location TestDrive:\`, and then run `New-Item` in the context of the `TestDrive:\`. You cannot just use regular filesystem drive path to repro this.

```
Executing script .\testPR6600.ps1

  Describing New-Item with links
    [+] Should create a file at the root of the drive while the current working directory is not the root 397ms
    [+] Should create a folder at the root of the drive while the current working directory is not the root 80ms
Tests completed in 477ms
Tests Passed: 2, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0
```

**Review by daxian-dbw — CHANGES_REQUESTED** [review]

File: test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1 (hunk 3 above)
Comment (daxian-dbw) [reply test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1]: Please use `[Feature]` when add commit to fix the feedback.

Comment (mcbobke) [reply test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1]: So should I avoid using $tmpDirectory altogether?

Comment (daxian-dbw) [reply test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1]: Yes, I believe that's how you can repro the issue with `TestDrive:\`. When using `$TestDirve`, you are actually using the real filesystem path, which is not a root path at all.
After you write new tests, please make sure that they fail as expected without your fix, but works with your fix.

Comment (mcbobke) [reply test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1]: Thank you, I'll be more explicit about `TestDrive:\` and will check with my new tests. I'll reply here when I confirm.

Comment (mcbobke) [reply test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1]:
```
Executing script .\test\powershell\Modules\Microsoft.PowerShell.Management\New-Item.Tests.ps1
    Describing New-Item
    [-] Should create a file at the root of the drive while the current working directory is not the root 107ms
      Expected path 'C:\Users\mbobke\AppData\Local\Temp\42bafa09-bdae-4f1d-a18f-33def150c3a3\testfile.txt' to exist, but it did not exist.
      127:             $FullyQualifiedFile | Should -Exist
      at <ScriptBlock>, C:\Users\mbobke\Documents\GitKraken\PowerShell\test\powershell\Modules\Microsoft.PowerShell.Management\New-Item.Tests.ps1: line 127

Confirm
The item at
C:\Users\mbobke\AppData\Local\Temp\42bafa09-bdae-4f1d-a18f-33def150c3a3\newDirectory has
children and the Recurse parameter was not specified. If you continue, all children will be
 removed with the item. Are you sure you want to continue?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): a
    [-] Should create a folder at the root of the drive while the current working directory is not the root 15.96s
      Expected path 'C:\Users\mbobke\AppData\Local\Temp\42bafa09-bdae-4f1d-a18f-33def150c3a3      ewDirectory2' to exist, but it did not exist.
      144:             $FullyQualifiedFolder2 | Should -Exist
      at <ScriptBlock>, C:\Users\mbobke\Documents\GitKraken\PowerShell\test\powershell\Modules\Microsoft.PowerShell.Management\New-Item.Tests.ps1: line 144
```
Confirmed that these tests fail without my changes implemented. Waiting for CI/CD to finish with the changes.

Comment (daxian-dbw) [reply test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1]: Thanks @mcbobke !
It would be easier to review if you push new commit instead of rebasing the existing one, so that we know where we were and only need to look at the new commits.

Also, please add the `[Feature]` tag to your commit message so that CI runs extra tests for the file system code change.

Comment (daxian-dbw) [reply test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1]: I will add the [Feature] tag for you.

Comment (mcbobke) [reply test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1]: Understood, I was under the impression that I should try and keep it to a single commit at all times, noted for the future. Sorry about the confusion about the tag, I thought it needed to be in the first line of the body. Thanks for the help!

**Review by daxian-dbw — APPROVED** [review]

**Comment by mcbobke** [comment]
Thank you all for the help and the merge!
