### PR TITLE
Restore the PowerShellStreamType enum with an ObsoleteAttribute

### LINKED ISSUE #11619: Public APIs missing in PowerShell 7.0.0-rc.2 since 6.2.3
I've run an analysis comparing public APIs available in PowerShell 6.2.3 vs 7.0.0-rc.2 and there are some public APIs that are missing.

While this is in many cases intentional, and likely to not be an issue, some may affect programs and tools trying to link against multiple versions of PowerShell (modules and some hosts). Trying to reference such an API would cause a sudden crash in one of these tools (the hard part being that the point at which the crash occurs may be hard to control).

I'm still refining the analysis, but here is a list of classes and members that have been removed:

## Types

- ~~`System.Management.Automation.PSJobProxy`~~ [Workflow]
- ~~`System.Management.Automation.PSChildJobProxy`~~ [Workflow]
- ~~`System.Management.Automation.JobDataAddedEventArgs`~~ [Workflow]
- `System.Management.Automation.PowerShellStreamType` (arguably workflow, but has generic name and namespace. Removed in https://github.com/PowerShell/PowerShell/pull/10083).
- ~~`System.Management.Automation.WorkflowInfo`~~ [Workflow]
- ~~`System.Management.Automation.Runspaces.PSSessionType` (arguably workflow, but possibly worth restoring with single value depending on how it's used)~~ Discussed with @daxian-dbw and @adityapatwardhan and decided that this is workflow-specific

## Fields

- ~~`System.Management.Automation.CommandTypes::Workflow`~~ [Workflow]
- ~~`System.Management.Automation.PSEngineEvent::WorkflowJobStartEvent`~~ [Workflow]
- ~~`System.Management.Automation.ModuleType::Workflow`~~ [Workflow]
- ~~`System.Management.Automation.Internal.DebuggerUtils::SetVariableFunction`~~ [Internal]
- ~~`System.Management.Automation.Internal.DebuggerUtils::RemoveVariableFunction`~~ [Internal]
- ~~`System.Management.Automation.Internal.DebuggerUtils::GetPSCallStackOverrideFunction`~~ [Internal]
- ~~`System.Management.Automation.Internal.PSMonitorRunspaceType::WorkflowInlineScript`~~ [Internal/Workflow]

## Methods and constructors (captures events and properties)

- ~~``Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache::ImportClasses(System.String,System.Tuple`2[System.String,System.Version],System.Collections.ObjectModel.Collection`1[System.Exception])``~~ [Internal]
- ~~``Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache::GetCachedClasses()``~~ [Internal]
- ~~``Microsoft.PowerShell.Commands.NewModuleManifestCommand::get_ClrVersion()``~~ **Fixed in https://github.com/PowerShell/PowerShell/pull/11623**
- ~~``Microsoft.PowerShell.Commands.NewModuleManifestCommand::set_ClrVersion(System.Version)``~~ **Fixed in https://github.com/PowerShell/PowerShell/pull/11623**
- ~~``Microsoft.PowerShell.Commands.RegisterPSSessionConfigurationCommand::get_SessionType()``~~ [Workflow]
- ~~``Microsoft.PowerShell.Commands.RegisterPSSessionConfigurationCommand::set_SessionType(System.Management.Automation.Runspaces.PSSessionType)``~~ [Workflow]
- ~~``Microsoft.PowerShell.Commands.InternalSymbolicLinkLinkCodeMethods::GetTarget(System.Management.Automation.PSObject)`` (arguably internal, but not internally namespaced. Return type changed in https://github.com/PowerShell/PowerShell/pull/8789)~~ Discussed with @daxian-dbw and @adityapatwardhan and decided that this is ok to remove
- ~~``System.Management.Automation.Debugger::SetBreakpoints(System.Collections.Generic.IEnumerable`1[System.Management.Automation.Breakpoint])``~~ **Fixed in https://github.com/PowerShell/PowerShell/pull/11622**
- ~~``System.Management.Automation.PowerShell::AsJobProxy()``~~ [Workflow]
- ~~``System.Management.Automation.ScriptBlock::set_IsFilter(System.Boolean)`` **Formerly threw InvalidOperationException. Should assess whether this is considered breaking. Changed in https://github.com/PowerShell/PowerShell/pull/9732**~~ Discussed with @daxian-dbw and @adityapatwardhan and decided that this is not a real breaking change
- ~~``System.Management.Automation.ScriptBlock::set_IsConfiguration(System.Boolean)`` **Formerly threw InvalidOperationException. Should assess whether this is considered breaking. Changed in https://github.com/PowerShell/PowerShell/pull/9732**~~ Discussed with @daxian-dbw and @adityapatwardhan and decided that this is not a real breaking change
- ~~``System.Management.Automation.PSModuleInfo::get_ExportedWorkflows()``~~ [Workflow]
- ~~``System.Management.Automation.Tracing.Tracer::EndpointRegistered(System.String,System.String,System.String)`` **Removed in https://github.com/PowerShell/PowerShell/pull/9618**~~ Discussed with @daxian-dbw, @adityapatwardhan and @JamesWTruher and decided that being a workflow-oriented, Windows-only API, this break is ok
- ~~``System.Management.Automation.Internal.DebuggerUtils::GetWorkflowDebuggerFunctions()``~~ [Internal/Workflow]

I'll continue this analysis to look into custom attributes

### PR DESCRIPTION
**Pull request by rjmholt**
# PR Summary

Fixes https://github.com/PowerShell/PowerShell/issues/11619.

## PR Context

Returns the `PowerShellStreamType` enum to code, since it was public, generically named and removed. Adds an `ObsoleteAttribute` to prevent new usage.

### CODE REVIEW

**Comment by rjmholt** [comment]
CodeFactor issues are due to reusing previous documentation comments

**Review by TravisEz13 — APPROVED** [review]

File: src/System.Management.Automation/engine/PowerShellStreamType.cs [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+    /// Enumeration of the possible PowerShell stream types.
+    /// This enumeration is obsolete.
+    /// </summary>
+    /// <remarks>
+    /// This enumeration is a public type formerly used in PowerShell Workflow,
+    /// but kept due to its generic name and public accessibility.
+    /// It is not used by any other PowerShell API, and is now obsolete
+    /// and should not be used if possible.
+    /// </remarks>
+    [Obsolete("Formerly used in PowerShell Workflow. Use an integer or System.Management.Automation.Language.RedirectionStream instead.")]
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/PowerShellStreamType.cs]: > Use an integer or System.Management.Automation.Language.RedirectionStream instead.

@TravisEz13 and I discussed on this message, and we think it's better to not give a workaround here given that those 2 enums have different members and values.

How about change the message to
```
This enum type was used only in PowerShell Workflow and is now obsolete
```
And make sure specify `true` for the `error` parameter.

**Review by daxian-dbw — CHANGES_REQUESTED** [review]
make sure specify `true` for the `error` parameter.

**Review by daxian-dbw — APPROVED** [review]

**Review by adityapatwardhan — APPROVED** [review]
