### PR TITLE
Fix help paging issues on macOS/Linux and with custom pager that takes arguments

### LINKED ISSUE #7175: Line wrapping in PS Core in-the-box help does not indent appropriately
Issue Details
-----------------
Long spans of help text that wrap lines do not honor indentation on subsequent lines.  This results in a less than pleasant reading experience. Here is what I'm seeing in 6.1 preview 3 on Windows:

image

Compare this to the nicer formatted 5.1 help:

image

There is also a typo in the 6.1 Get-ChildItem Description - it says `all child continers` and it should be `all child containers`.  Apparently that has been introduced by the rendered as the typo isn't in the source doc.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.3
PSEdition                      Core
GitCommitId                    v6.1.0-preview.3
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Moved from https://github.com/PowerShell/PowerShell-Docs/issues/2606 per request of @sdwheeler.

### LINKED ISSUE #8912: Passing parameters to $env:PAGER is broken in 6.2.0-preview.4
I have `$env:PAGER` set to `less "-PPowerShell help page line %lt (press h for help or q to quit)"` and on PS Core 6.1.0 on Windows 10 1809, PS Core uses less and gives me this nice footer during paging:

image

But in PS Core 6.2.0-preview.4 that same env var setting, causes `more.com` to be invoked. That is rather rude - ignoring my less preference.

# Steps to reproduce
Set the following env var value.
```powershell
$env:PAGER = 'less "-PPowerShell help page line %lt (press h for help or q to quit)"'
```

# Expected behavior
I get paging via less and with my desired footer.

# Actual behavior
more.com is invoked instead.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0-preview.4
PSEdition                      Core
GitCommitId                    6.2.0-preview.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by rkeithhill**
# PR Summary

Fix #7175 by using `Out-String -Stream -Width` before piping to an application.  This improves the help experience on macOS and Linux by ensuring lines of help text wrap properly for the given console width.

Fix #8912 by using the PS tokenizer to separate the pager command from arguments if both are specified in $env:PAGER.  Also ensures that there is no PowerShell interpretation of arguments to an application by using the stop parsing operator.

## PR Context

The current reading experience of all help topics on macOS and Linux is sub-par giving PowerShell Core a bit of a black eye on those platforms.  See #7175 for images of what this looks like.

Specify a custom pager with arguments works in v6.1 but is broken in v6.2.  This PR fixes this issue - #8912.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed:  #7175 #8912
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

File: src/System.Management.Automation/engine/InitialSessionState.cs [hunk 1]
```diff
@@ -4176,40 +4176,62 @@ .FORWARDHELPCATEGORY Cmdlet
...
+            if (Get-Command $env:PAGER -ErrorAction Ignore) {
+                # Entire PAGER value corresponds to a single command.
+                $pagerCommand = $env:PAGER
+            }
+            else {
+                # PAGER value is not a valid command, check if PAGER command and arguments have been specified.
+                # Tokenize the specified $env:PAGER value. Ignore tokenizing errors since any errors may be valid
+                # argument syntax for the paging utility.
+                $errs = $null
+                $tokens = [System.Management.Automation.PSParser]::Tokenize($env:PAGER, [ref]$errs)
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/InitialSessionState.cs]: I'd expect that Tokenizer is very fast and more fast than Get-Command. So we could always call it and then Get-Command. This simplify code.
We need look $errs and write useful message to user.
Also we could use try-catch for Get-Command and running the command to write more useful messages to user.

Comment (rkeithhill) [reply src/System.Management.Automation/engine/InitialSessionState.cs]: I'm not sure we should expose tokenizer errors.  We are only using the tokenizer when piping help output to applications.  The arguments passed to those applications could very well fail to tokenize by PowerShell.  For instance, say an app took an argument like `@{HEAD-1}`, perfectly valide for the app but gens a tokenizer error:
```
Missing '=' operator after key in hash literal.
```
For debugging, I propose we leave the __PSPAGER_ARGS env var so the user can inspect it to see exactly what we are passing for args to custom pager application.

File: src/System.Management.Automation/engine/InitialSessionState.cs [hunk 2]
```diff
@@ -4176,40 +4176,61 @@ .FORWARDHELPCATEGORY Cmdlet
...
     {
-        $customPagerCommand = """"
-        $customPagerCommandArgs = """"
-        $customPagerCommandLine = """"
-
-        if ($env:PAGER)
-        {
-            $customPagerCommandLine = $env:PAGER
+        # By default use more on Windows and less on Linux.
+        if ($IsWindows) {
```
Comment (RDIL) [inline src/System.Management.Automation/engine/InitialSessionState.cs]:
```suggestion
        if ($IsWindows)
        {
```

File: src/System.Management.Automation/engine/InitialSessionState.cs [hunk 3]
```diff
@@ -4176,40 +4176,61 @@ .FORWARDHELPCATEGORY Cmdlet
...
+            $pagerCommand = 'more.com'
+            $pagerArgs = $null
+        }
+        else {
```
Comment (RDIL) [inline src/System.Management.Automation/engine/InitialSessionState.cs]:
```suggestion
        else
        {
```

File: src/System.Management.Automation/engine/InitialSessionState.cs [hunk 4]
```diff
@@ -4176,40 +4176,61 @@ .FORWARDHELPCATEGORY Cmdlet
...
+            $pagerCommand = 'less'
+            $pagerArgs = '-Ps""Page %db?B of %D:.\. Press h for help or q to quit\.$""'
+        }
+
+        # Respect PAGER environment variable which allows user to specify a custom pager.
+        # Ignore a pure whitespace PAGER value as that would cause the tokenizer to return 0 tokens.
+        if (![string]::IsNullOrWhitespace($env:PAGER)) {
```
Comment (RDIL) [inline src/System.Management.Automation/engine/InitialSessionState.cs]:
```suggestion
        if (![string]::IsNullOrWhitespace($env:PAGER))
        {
```

File: src/System.Management.Automation/engine/InitialSessionState.cs [hunk 5]
```diff
@@ -4176,40 +4176,61 @@ .FORWARDHELPCATEGORY Cmdlet
...
+            if (Get-Command $env:PAGER -ErrorAction Ignore) {
```
Comment (RDIL) [inline src/System.Management.Automation/engine/InitialSessionState.cs]:
```suggestion
            if (Get-Command $env:PAGER -ErrorAction Ignore)
            {
```

File: src/System.Management.Automation/engine/InitialSessionState.cs [hunk 6]
```diff
@@ -4176,40 +4176,61 @@ .FORWARDHELPCATEGORY Cmdlet
...
+                # Entire PAGER value corresponds to a single command.
+                $pagerCommand = $env:PAGER
+                $pagerArgs = $null
+            }
+            else {
```
Comment (RDIL) [inline src/System.Management.Automation/engine/InitialSessionState.cs]:
```suggestion
            else
            {
```

File: src/System.Management.Automation/engine/InitialSessionState.cs [hunk 7]
```diff
@@ -4176,40 +4176,61 @@ .FORWARDHELPCATEGORY Cmdlet
...
+                # PAGER value is not a valid command, check if PAGER command and arguments have been specified.
+                # Tokenize the specified $env:PAGER value. Ignore tokenizing errors since any errors may be valid
+                # argument syntax for the paging utility.
+                $errs = $null
+                $tokens = [System.Management.Automation.PSParser]::Tokenize($env:PAGER, [ref]$errs)
+
+                $customPagerCommand = $tokens[0].Content
+                if (!(Get-Command $customPagerCommand -ErrorAction Ignore)) {
```
Comment (RDIL) [inline src/System.Management.Automation/engine/InitialSessionState.cs]:
```suggestion
                if (!(Get-Command $customPagerCommand -ErrorAction Ignore))
                {
```

File: src/System.Management.Automation/engine/InitialSessionState.cs [hunk 8]
```diff
@@ -4176,40 +4176,61 @@ .FORWARDHELPCATEGORY Cmdlet
...
+                    # Custom pager command is invalid, issue a warning.
+                    Write-Warning ""Ignoring invalid custom-paging utility command line specified in `$env:PAGER: $env:PAGER""
+                }
+                else {
```
Comment (RDIL) [inline src/System.Management.Automation/engine/InitialSessionState.cs]:
```suggestion
                else
                {
```

File: src/System.Management.Automation/engine/InitialSessionState.cs [hunk 9]
```diff
@@ -4176,40 +4176,61 @@ .FORWARDHELPCATEGORY Cmdlet
...
+                    $pagerCommand = $customPagerCommand
+                    $pagerArgs = if ($tokens.Count -gt 1) {$env:PAGER.Substring($tokens[1].Start)} else {$null}
+                }
+            }
+        }
 
-            # Split the command line into tokens, respecting quoting.
-            $customPagerCommand, $customPagerCommandArgs = & { Write-Output -- $customPagerCommandLine }
+        # If the pager is an application, format the output width before sending to the app.
+        if ((Get-Command $pagerCommand -ErrorAction Ignore).CommandType -eq 'Application') {
```
Comment (RDIL) [inline src/System.Management.Automation/engine/InitialSessionState.cs]:
```suggestion
        if ((Get-Command $pagerCommand -ErrorAction Ignore).CommandType -eq 'Application')
        {
```

File: src/System.Management.Automation/engine/InitialSessionState.cs [hunk 10]
```diff
@@ -4176,40 +4176,61 @@ .FORWARDHELPCATEGORY Cmdlet
...
+            $consoleWidth = [System.Math]::Max([System.Console]::WindowWidth, 20)
 
-            # See if the first token refers to a known command (executable),
-            # and if not, see if the command line as a whole is an executable path.
-            $cmds = Get-Command $customPagerCommand, $customPagerCommandLine -ErrorAction Ignore
-            if (-not $cmds) {
-                # Custom command is invalid; ignore it, but issue a warning.
-                Write-Warning ""Ignoring invalid custom-paging utility command line specified in `$env:PAGER: $customPagerCommandLine""
-                $customPagerCommand = $null # use default command
+            if ($pagerArgs) {
```
Comment (RDIL) [inline src/System.Management.Automation/engine/InitialSessionState.cs]:
```suggestion
            if ($pagerArgs)
            {
```

File: src/System.Management.Automation/engine/InitialSessionState.cs [hunk 11]
```diff
@@ -4176,40 +4176,61 @@ .FORWARDHELPCATEGORY Cmdlet
...
+                # Leave environment variable to help user debug arguments supplied in $env:PAGER.
+                $env:__PSPAGER_ARGS = $pagerArgs
+                $help | Out-String -Stream -Width ($consoleWidth - 1) | & $pagerCommand --% %__PSPAGER_ARGS%
             }
-            elseif ($cmds.Count -eq 1 -and $cmds[0].Source -eq $customPagerCommandLine) {
-                # The full command line is an unquoted path to an existing executable
-                # with embedded spaces.
-                $customPagerCommand = $customPagerCommandLine
-                $customPagerCommandArgs = $null
+            else {
```
Comment (RDIL) [inline src/System.Management.Automation/engine/InitialSessionState.cs]:
```suggestion
            else
            {
```

File: src/System.Management.Automation/engine/InitialSessionState.cs [hunk 12]
```diff
@@ -4176,40 +4176,61 @@ .FORWARDHELPCATEGORY Cmdlet
...
         }
-
-        # Respect PAGER, use more on Windows, and use less on Linux
-        if ($customPagerCommand) {
-            $help | & $customPagerCommand $customPagerCommandArgs
-        } elseif ($IsWindows) {
-            $help | more.com
-        } else {
-            $help | less -Ps""Page %db?B of %D:.\. Press h for help or q to quit\.$""
+        else {
```
Comment (RDIL) [inline src/System.Management.Automation/engine/InitialSessionState.cs]:
```suggestion
        else
        {
```

**Review by RDIL — CHANGES_REQUESTED** [review]
CSharp brace style issues

**Comment by vexx32** [comment]
@RDIL all of those are within a string which is actually PowerShell embedded into the C# code, so they should follow PowerShell style. :)

**Comment by RDIL** [comment]
why do i even try reviewing

**Comment by vexx32** [comment]
If for nothing else, because it'll help you pick all the nuances up that much faster! 🙂 

I had to triple check that, too, because something didn't look quite right, so don't feel bad. I stared at it for a good ten minutes before I realized what was going on. 😄

File: src/System.Management.Automation/engine/InitialSessionState.cs (hunk 2 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/InitialSessionState.cs]: @RDIL It is PowerShell code and we should use PowerShell formatting style.

Comment (RDIL) [reply src/System.Management.Automation/engine/InitialSessionState.cs]: I'm aware
https://github.com/PowerShell/PowerShell/pull/9033#issuecomment-469343958

**Review by adityapatwardhan — APPROVED** [review]

File: src/System.Management.Automation/engine/InitialSessionState.cs (hunk 1 above)
Comment (iSazonov) [reply src/System.Management.Automation/engine/InitialSessionState.cs]: > I'm not sure we should expose tokenizer errors.

No expose. I think we _could_ use this to create more useful message to user if it is possible.

**Comment by rkeithhill** [comment]
I suppose it is unlikely that this will make it in for the 6.2 release, eh?

**Comment by iSazonov** [comment]
Yes, GA-6.2 was already forked. In next milestone perhaps we'll convert the function to cmdlet.

**Comment by pougetat** [comment]
@rkeithhill Sorry about this one. I see your PR will fix the issue I introduced.

**Comment by rkeithhill** [comment]
This PR needs some more review and to be targeted for some milestone - 6.2.1 or 7.  I do not wish to see this closed as it addresses a real issue.

File: src/System.Management.Automation/engine/InitialSessionState.cs [hunk 13]
```diff
@@ -4176,40 +4176,61 @@ .FORWARDHELPCATEGORY Cmdlet
...
+                # PAGER value is not a valid command, check if PAGER command and arguments have been specified.
+                # Tokenize the specified $env:PAGER value. Ignore tokenizing errors since any errors may be valid
+                # argument syntax for the paging utility.
+                $errs = $null
+                $tokens = [System.Management.Automation.PSParser]::Tokenize($env:PAGER, [ref]$errs)
+
+                $customPagerCommand = $tokens[0].Content
+                if (!(Get-Command $customPagerCommand -ErrorAction Ignore)) {
+                    # Custom pager command is invalid, issue a warning.
+                    Write-Warning ""Ignoring invalid custom-paging utility command line specified in `$env:PAGER: $env:PAGER""
```
Comment (TravisEz13) [inline src/System.Management.Automation/engine/InitialSessionState.cs]: This is more that it was not found?  Can we update the message?

**Review by TravisEz13 — APPROVED** [review]
Only one minor issue.  Tell me if you want me to address it before I merge.

File: src/System.Management.Automation/engine/InitialSessionState.cs (hunk 13 above)
Comment (rkeithhill) [reply src/System.Management.Automation/engine/InitialSessionState.cs]: I can update the message. How about: ""Custom-paging utility command not found. Ignoring command specified in `$env:PAGER: $env:PAGER""

Comment (TravisEz13) [reply src/System.Management.Automation/engine/InitialSessionState.cs]: that looks better.

Comment (rkeithhill) [reply src/System.Management.Automation/engine/InitialSessionState.cs]: Done

**Review by TravisEz13 — APPROVED** [review]

**Comment by iSazonov** [comment]
@rkeithhill Thanks for fixing the paging issues.
