### PR TITLE
Treat -Target as literal in New-Item

### LINKED ISSUE #6232: Creating symbolic links or junctions with New-Item doesn't work if target contains '[' or ']'
Steps to reproduce
------------------

1. Type on an NTFS/ReFS file system:
```
New-Item -Path '[target]' -ItemType Directory
```
2. Try creating a junction (or symbolic link, substitute with 'SymbolicLink' in the -ItemType parameter)
```
New-Item -Path '[source]' -Value '[target]' -ItemType Junction
```

Expected behavior
-----------------
The junction should be created even if the target path contains square bracket characters

Actual behavior
---------------
 An error message is resulted:
```
new-item : Cannot find path '[target]' because it does not exist.
At line:1 char:1
+ New-Item -Path '[source]' -Value '[target]' -Itemtype Junction
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [New-Item], PSInvalidOperationException
+ FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.NewItem Command
```
Note: the command **can** be made to work with double escapes, but it seems hacky.
```
new-item -path '[source]' -value "```[target```]" -Itemtype Junction
```

Environment data
----------------

```
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### LINKED ISSUE #13136: New-Item: When creating symbolic links (symlinks) / reparse points, the -Target path should always be treated as a *literal* path
Note: 

* This is technically a breaking change, but one that to me falls into [Bucket 3: Unlikely Grey Area](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area).

* We've recently made an analogous change to `Invoke-WebRequest` / `Invoke-RestMethod`, which now sensibly interpret their `-OutFile` argument invariably as a _literal_ path - see #11701

  * Similar fixes are pending in other contexts: #4726, #9225, #4726.

## Summary of the new feature/enhancement

When you create a symlink or reparse point, you want to target a _specific, literal_ target path - you're not looking for this path to determined via _wildcard-pattern matching_, which, however, is what currently happens: a `-Target` (`-Value`) argument is (invariably) interpreted as a wildcard pattern. What makes the behavior even less useful is that the pattern must resolve to _exactly one_ path.

* Interpreting the `-Target` (`-Value`) argument as a wildcard expression means that meant-to-be-literal paths such as `[a].txt` would mistakenly target `a.txt`, if present, for instance.

* Also, as a potentially unwanted side effect, if the `-Target` (`-Value`) _is_ determined via wildcard resolution, a relative input path (pattern) is invariably resolved to a _full_ path.

**The sensible behavior is to _always_ treat the `-Target` (`-Value`) argument  as a _literal_ path** (and to preserve its relative-vs.-full path status, as specified).

---

Once the change is implemented, the following tests - which currently fail - should succeed:

```powershell
$null = New-Item 'file1', 'file[1]'

$targetRelative = 'file[1]'
$targetAbsolute = Join-Path $pwd.providerpath 'file[1]'

(New-Item -Type SymbolicLink fileL -Target $targetRelative).Target | Should -Be $targetRelative
(New-Item -Force -Type SymbolicLink fileL -Target $targetAbsolute).Target | Should -Be $targetAbsolute
```

The tests currently fail, because `file[1]` is interpreted as a wildcard pattern that happens to match `file1`.

### PR DESCRIPTION
**Pull request by GameMicrowave**
# PR Summary

Fix #6232
Fix #13136

Fix `New-Item` fails to create file links or creates links pointing to incorrect locations when the target path contains wildcard characters.

Make the `-Target` and `-Value` parameters of `New-Item` treat the path as a literal.

## PR Context

When using the `New-Item` command to create file links, if the target path contains wildcard characters, they are incorrectly interpreted. The following scenarios occur:

+ When creating a hard link, if the link path is an absolute path, the creation will always fail.
+ When creating a symbolic link:
  + If the wildcard characters in the link path are not escaped with a backtick, the creation will fail.
  + If the wildcard characters in the link path are escaped with a backtick, a link pointing to an incorrect path will be created.

+ When creating a Junction, the situation is similar to the above.

Example:

```powershell
New-Item lk21.txt -ItemType HardLink -Target 'D:\[test].txt'
# New-Item: Could not find item D:\[test].txt.

# The `Get-Item` command can correctly retrieve the file.
Get-Item -LP 'D:\[test].txt'
#    Directory: D:\
# Mode                 LastWriteTime         Length Name
# ----                 -------------         ------ ----
# -a---           2025/3/15    14:26              9 [test].txt
```

Now, the path is correctly parsed to create the link.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
  - [ ] None
  - **OR**
  - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
    - [ ] Experimental feature name(s): 
- **User-facing changes**
  - [x] Not Applicable
  - **OR**
  - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
  - [x] N/A or can only be tested interactively
  - **OR**
  - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
  - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
  - **OR**
  - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
    - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
      - [ ] Issue filed: 
    - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
      - [ ] Issue filed: 
    - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
      - [ ] Issue filed: 
    - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
      - [ ] Issue filed:

### CODE REVIEW

**Comment by GameMicrowave** [comment]
> 请阅读以下贡献者许可协议 （CLA）。如果您同意 CLA，请回复以下信息。
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > 选项：
> > 
> > * （默认 - 未指定公司）我对我的提交内容拥有唯一的知识产权，并且我不会在为我的雇主工作期间提交提交内容。
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * （当给出公司时）我在为我的雇主工作期间提交了提交内容（或者我的雇主根据合同或适用法律对我的提交内容拥有知识产权）。我已获得雇主的许可，可以代表我的雇主提交内容并签订本协议。通过在下面签名，定义的术语“您”包括我和我的雇主。
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> 贡献者许可协议

@microsoft-github-policy-service agree

**Comment by iSazonov** [comment]
@GameMicrowave There is #16306 which must be fixed first since it is public API.

File: src/System.Management.Automation/engine/regex.cs [hunk 1]
```diff
@@ -240,7 +240,7 @@ internal static string Escape(string pattern, char[] charsNotToEscape)
                 //
                 // if it is a wildcard char, escape it
                 //
-                if (IsWildcardChar(ch) && !charsNotToEscape.Contains(ch))
+                if ((IsWildcardChar(ch) || ch == '`') && !charsNotToEscape.Contains(ch))
```
Comment (ArmaanMcleod) [inline src/System.Management.Automation/engine/regex.cs:243]:
```suggestion
                if ((IsWildcardChar(ch) || ch == escapeChar) && !charsNotToEscape.Contains(ch))
```

Comment (ArmaanMcleod) [reply src/System.Management.Automation/engine/regex.cs:243]: @iSazonov I can't remember if this was the actual correct fix to the `Escape` method. We probably need to have a 2nd attempt at fixing public API for this in another PR.

Comment (iSazonov) [reply src/System.Management.Automation/engine/regex.cs:243]: Let's discuss in related issue.

**Comment by iSazonov** [comment]
@GameMicrowave Please resolve merge conflicts.

**Comment by GameMicrowave** [comment]
> @GameMicrowave Please resolve merge conflicts.

yes, i resolved it😊

**Comment by iSazonov** [comment]
@GameMicrowave I tried the build with examples from related issues and they don't work. Please add tests if you want to continue working on this issue.

**Comment by GameMicrowave** [comment]
> @GameMicrowave I tried the build with examples from related issues and they don't work. Please add tests if you want to continue working on this issue.

Alright, I've written a test script. In the process, I discovered another bug, which I've now fixed.

File: test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1 [hunk 2]
```diff
@@ -396,3 +396,34 @@ Describe "New-Item -Force should throw an error for invalid characters in direct
...
+    It "Should succeed in creating a file link." {
+        if (Test-Path -LiteralPath $testFolder) {
+            Remove-Item -LiteralPath $testFolder -Recurse -Force
+        }
+        New-Item $testFolder -Type Directory
+        Set-Content -PSPath $testFile -Value $info
+
+        New-Item $hardLink -Target ([WildcardPattern]::Escape((Get-Item -PSPath $testFile))) -Type HardLink    # create hardlink with absolute path
+        New-Item $symbolicLink -Target ([WildcardPattern]::Escape($testFile)) -Type SymbolicLink
+        New-Item $junction -Target ([WildcardPattern]::Escape((Get-Item -PSPath $testFolder))) -Type Junction
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1:422]: Please see PowerShell Committee conclusion in https://github.com/PowerShell/PowerShell/issues/6232#issuecomment-1864855190

Comment (GameMicrowave) [reply test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1]: OK, I make the `-Target` and `-Value` parameters of `New-Item` treat the path as a literal.

**Comment by GameMicrowave** [comment]
I don't know how to add a CI label to a PR. I tried to find a button, but I didn't find one

File: test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1 [hunk 3]
```diff
@@ -396,3 +396,42 @@ Describe "New-Item -Force should throw an error for invalid characters in direct
...
+    }
+    It "Should succeed in creating a junction on Windows." -Skip:(!$IsWindows) {
+        New-Item $junction -Target (Get-Item -PSPath .) -Type Junction
+        Get-Content -PSPath $fileInJunction | Should -Be $expectedFileContent
+        Remove-Item -PSPath $junction
+    }
+    
+	AfterAll {
+        Pop-Location
+        Pop-Location
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1:434]: I it is not reliable. I suggest to use full paths as in other tests.

File: test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1 [hunk 4]
```diff
@@ -396,3 +396,40 @@ Describe "New-Item -Force should throw an error for invalid characters in direct
...
+
+        $symbolicLink   = 'sym-lk.txt'
+        $hardLink       = 'hard-lk.txt'
+        $junction       = 'junc'
+        $fileInJunction = Join-Path $junction $testFile
+        
+        $expectedFileContent = 'succeed!'
+
+        New-Item "TestDrive:\$testFolder" -Type Directory
+        Push-Location -PSPath "TestDrive:\$testFolder"
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1:413]: Please don't use alias PSPath. We should explicitly use `Path` or `LiteralPath`.

**Comment by GameMicrowave** [comment]
@iSazonov All the tests have been passed. Do you think there's anything else that needs to be modified?

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 5]
```diff
@@ -2272,7 +2272,7 @@ protected override void NewItem(
                             if (!IsAbsolutePath(strTargetPath))
                             {
                                 // there is already a check before here so that strTargetPath should only resolve to 1 path
```
Comment (mklement0) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs:2274]: This comment can probably be removed.

**Comment by mklement0** [comment]
@iSazonov, other than that, it LGTM. Thanks your tackling this, @GameMicrowave.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 5 above)
Comment (GameMicrowave) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs]: OK

File: test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1 [hunk 6]
```diff
@@ -396,3 +396,40 @@ Describe "New-Item -Force should throw an error for invalid characters in direct
         { New-Item -Path $invalidPath -ItemType Directory -Force -ErrorAction Stop } | Should -Throw -ErrorId 'CreateDirectoryIOError,Microsoft.PowerShell.Commands.NewItemCommand'
     }
 }
+
+Describe "If the target path contains wildcard characters, the operation should succeed in creating a file link." -Tags @("CI", 'RequireAdminOnWindows') {
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1:400]: All file link tests are in FileSystem.Tests.ps1 line 555. Please move new tests to the file.

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 [hunk 7]
```diff
@@ -611,12 +611,12 @@ Describe "Hard link and symbolic link tests" -Tags "CI", "RequireAdminOnWindows"
         $realDir = Join-Path $TestPath "subdir"
         $realDir2 = Join-Path $TestPath "second-subdir"
         $nonDir = Join-Path $TestPath "not-a-dir"
-        $hardLinkToFile = Join-Path $TestPath "hard-to-file.txt"
-        $symLinkToFile = Join-Path $TestPath "sym-link-to-file.txt"
-        $symLinkToDir = Join-Path $TestPath "sym-link-to-dir"
-        $symLinkToNothing = Join-Path $TestPath "sym-link-to-nowhere"
-        $dirSymLinkToDir = Join-Path $TestPath "symd-link-to-dir"
-        $junctionToDir = Join-Path $TestPath "junction-to-dir"
+        $hardLinkToFile = Join-Path $TestPath "[hard-to-file].txt"
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1:614]: Since we haven't explicit tests please add new comment before the line that we intentionally use wildcard chars in follow names for testing.

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
@GameMicrowave Thanks for your contribution!
