### PR TITLE
Fixing JSON property accessor to attempt user settings directory creation on the first write operation

### LINKED ISSUE #2037: The  per-user configuration directory should not be created by JsonConfigFileAccessor until a write operation to user config file is requested
`JsonConfigFileAccessor` tries to create the per-user configuration directory at initialization, even if on configuration file is put there. And currently both read and write operations targeting the user scope settings will trigger the creation of the directory.

There is an edge case that we have to deal with -- what if somehow it fails to create the directory? The current implementation is to let the exception pop up, and reply on the caller to handle this situation. However, if the caller only issues a read request, it shouldn't matter that the configuration directory cannot be created, because that means no configuration file is there, so a default value should be returned for the setting, such as `null` for a string value.

IMHO, The per-user configuration directory should only be created when powershell has to -- only write requests to the user settings would trigger the creation of the directory.

### PR DESCRIPTION
**Pull request by mirichmo**
Fixes #2037 and #2205 
I addressed the issue by delaying user settings directory creation until a write operation takes place. At that point, the console should be up and running, so it is safe to let errors propagate for eventual display to the user. This should address all startup scenarios regardless of hosting technique.

I also wrote some new tests to validate basic file operations on the user settings PowerShellProperties.json file.

### CODE REVIEW

**Comment by mirichmo** [comment]
@daxian-dbw and @andschwa Please review

**Review by andyleejordan — APPROVED** [review]
Looks good to me, thanks!

**Review by lzybkr — COMMENTED** [review]
The filename PropertyAccessor.Tests.ps1 is too generic, I'd assume that tests something else.

File: src/System.Management.Automation/engine/PropertyAccessor.cs [hunk 1]
```diff
@@ -145,41 +145,24 @@ internal JsonConfigFileAccessor()
...
-                string tempAppDataConfigDir = Utils.GetUserConfigurationDirectory();
-                if (!Directory.Exists(tempAppDataConfigDir))
-                {
-                    Directory.CreateDirectory(tempAppDataConfigDir);
-                    // Only assign it if creation succeeds. It will throw if it fails.
-                    appDataConfigDirectory = tempAppDataConfigDir;
-                }
-                // Do not catch exceptions here. Let them flow up.
+                // Exceptions are not caught so that they will propagate to the host for display to the user.
+                Directory.CreateDirectory(appDataConfigDirectory);
```
Comment (lzybkr) [inline src/System.Management.Automation/engine/PropertyAccessor.cs]: There is a race condition here - another process could create the directory after the Exists test fails. You should probably catch the appropriate exception from CreateDirectory and ignore it if that happens.

**Review by lzybkr — CHANGES_REQUESTED** [review]

File: test/powershell/engine/PropertyAccessor.Tests.ps1 [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+# Functional tests to verify basic conditions for IO to the PowerShellProperties.json files
+# The properties files are supported on non-Windows OSes, but the tests are specific to 
+# Windows so that file IO can be verified using supported cmdlets.
+# 
+
+try {
+
+    #skip all tests on non-windows platform
+    $originalDefaultParameterValues = $PSDefaultParameterValues.Clone()
+    $IsNotSkipped = ($IsWindows -eq $true);
```
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: Maybe `$IsNotSkipped = $IsWindows`?
Or even better, why not just use `$IsWindows` without `$IsNotSkipped`? I don't feel this variable helps readability.

File: test/powershell/engine/PropertyAccessor.Tests.ps1 [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+    $PSDefaultParameterValues["it:skip"] = !$IsNotSkipped
+    $ShouldSkipTest = !$IsNotSkipped
```
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: `$shouldSkipTest` is not used in this test.

File: test/powershell/engine/PropertyAccessor.Tests.ps1 [hunk 4]
```diff
@@ -0,0 +1,96 @@
...
+
+    Describe "User-Specific PowerShellProperties.json Modifications" -Tags "CI" {
+
+        BeforeAll {
+            if ($IsNotSkipped) {
+                # Discover the user-specific PowerShellProperties.json file
+                $splitModulePath = $env:PSMODULEPATH -split ";"
+                $userModuleDir = $splitModulePath[0].TrimEnd("\")
+                $userSettingsDir = $userModuleDir -replace "\\Modules", ""
```
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: Assuming the first module path is the user module path is fragile. This may not work when a dev is running the test with a profile. I think it's safer to construct the path to the user property.json file. That should be easy given that the test only runs on win-platform.

File: src/System.Management.Automation/engine/PropertyAccessor.cs [hunk 5]
```diff
@@ -250,7 +233,8 @@ internal override void RemoveExecutionPolicy(PropertyScope scope, string shellId
             // Defaults to system wide.
             if (PropertyScope.CurrentUser == scope)
             {
-                scopeDirectory = GetCurrentUserConfigDirectory();
+                CreateUserConfigDirectory();
```
Comment (daxian-dbw) [inline src/System.Management.Automation/engine/PropertyAccessor.cs]: Minor question: is it really necessary to create the file when it's requested to remove a property? If the file doesn't exist, then no action needed, and the removal will be sure successful.

File: test/powershell/engine/PropertyAccessor.Tests.ps1 [hunk 6]
```diff
@@ -0,0 +1,96 @@
+#
+# Functional tests to verify basic conditions for IO to the PowerShellProperties.json files
+# The properties files are supported on non-Windows OSes, but the tests are specific to 
+# Windows so that file IO can be verified using supported cmdlets.
+# 
+
+try {
+
+    #skip all tests on non-windows platform
+    $originalDefaultParameterValues = $PSDefaultParameterValues.Clone()
```
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: >$originalDefaultParameterValues = $PSDefaultParameterValues.Clone()
$IsNotSkipped = ($IsWindows -eq $true);
$PSDefaultParameterValues["it:skip"] = !$IsNotSkipped
$ShouldSkipTest = !$IsNotSkipped

I think all these can be moved to `BeforeAll { }` and `$global:PSDefaultParameterValues = $originalDefaultParameterValues` can be moved to `AfterAll { }`.
Some examples:
PowerShell\test\powershell\Language\Scripting\I18n.Tests.ps1
PowerShell\test\powershell\Modules\Microsoft.PowerShell.Diagnostics\Get-WinEvent.Tests.ps1

File: test/powershell/engine/PropertyAccessor.Tests.ps1 [hunk 7]
```diff
@@ -0,0 +1,96 @@
...
+                    $backupPropertiesFile = Join-Path $userSettingsDir "ORIGINAL_PowerShellProperties.json"
+                    Copy-Item -Path $userPropertiesFile -Destination $backupPropertiesFile -Force -ErrorAction Continue
+                }
+                else {
+                    # create the directory and file if they do not already exist
+                    $null = New-Item -Type Directory  -Path $userSettingsDir -Force -ErrorAction SilentlyContinue
+                    Set-Content -Path $userPropertiesFile -Value '{"Microsoft.PowerShell:ExecutionPolicy":"RemoteSigned"}'
+                }
+
+                # Save original the Process ExecutionPolicy. The tests assume that it is Undefined
```
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: > original the
Should be **the original**

File: test/powershell/engine/PropertyAccessor.Tests.ps1 [hunk 8]
```diff
@@ -0,0 +1,96 @@
...
+
+        BeforeEach {
+            if ($IsNotSkipped) {
+                Set-Content -Path $userPropertiesFile -Value '{"Microsoft.PowerShell:ExecutionPolicy":"RemoteSigned"}'
+            }
+        }
+
+        AfterAll {
+            if ($IsNotSkipped) {
+                if ([string]::IsNullOrEmpty($backupPropertiesFile))
```
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: Use the powershell way to do it: `if (-not $backupPropertiesFile)`

File: test/powershell/engine/PropertyAccessor.Tests.ps1 [hunk 9]
```diff
@@ -0,0 +1,96 @@
...
+
+                # Save the file for restoration after the tests are complete
+                $backupPropertiesFile = ""
+                if (Test-Path $userPropertiesFile) {
+                    $backupPropertiesFile = Join-Path $userSettingsDir "ORIGINAL_PowerShellProperties.json"
+                    Copy-Item -Path $userPropertiesFile -Destination $backupPropertiesFile -Force -ErrorAction Continue
+                }
+                else {
+                    # create the directory and file if they do not already exist
+                    $null = New-Item -Type Directory  -Path $userSettingsDir -Force -ErrorAction SilentlyContinue
```
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: Do we want to create the directory `C:\Users\dongbow\Documents` when it already exists?
Probably it should be
``` powershell
elseif (-not (Test-Path $userSettingsDir))
{
    $null = New-Item -Type Directory -Path $userSettingsDir -Force -ErrorAction SilentlyContinue
}
```

File: test/powershell/engine/PropertyAccessor.Tests.ps1 [hunk 10]
```diff
@@ -0,0 +1,96 @@
...
+
+                # Restore the original Process ExecutionPolicy
+                Set-ExecutionPolicy -Scope Process -ExecutionPolicy $processExecutionPolicy
+            }
+        }
+
+        It "Verify Queries to Missing File Return Default Value" {
+            Remove-Item $userPropertiesFile -Force
+
+            Get-ExecutionPolicy -Scope CurrentUser | Should Be "Undefined"
```
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: Maybe add one more check to verify that read operation should not create the file.

File: test/powershell/engine/PropertyAccessor.Tests.ps1 [hunk 11]
```diff
@@ -0,0 +1,96 @@
...
+                # Save the file for restoration after the tests are complete
+                $backupPropertiesFile = ""
+                if (Test-Path $userPropertiesFile) {
+                    $backupPropertiesFile = Join-Path $userSettingsDir "ORIGINAL_PowerShellProperties.json"
+                    Copy-Item -Path $userPropertiesFile -Destination $backupPropertiesFile -Force -ErrorAction Continue
+                }
+                else {
+                    # create the directory and file if they do not already exist
+                    $null = New-Item -Type Directory  -Path $userSettingsDir -Force -ErrorAction SilentlyContinue
+                    Set-Content -Path $userPropertiesFile -Value '{"Microsoft.PowerShell:ExecutionPolicy":"RemoteSigned"}'
```
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: this line seems not needed given the same command will run in `BeforeEach { }`

**Review by daxian-dbw — CHANGES_REQUESTED** [review]

File: src/System.Management.Automation/engine/PropertyAccessor.cs (hunk 1 above)
Comment (mirichmo) [inline src/System.Management.Automation/engine/PropertyAccessor.cs]: CreateDirectory doesn't throw an exception if it already exists. It just returns the directory.
https://msdn.microsoft.com/en-us/library/54a0at6s(v=vs.110).aspx

Now the question becomes... is the check if it exists necessary? It feels like it is slightly faster to check first in scenarios where the directory already exists.

File: src/System.Management.Automation/engine/PropertyAccessor.cs (hunk 5 above)
Comment (mirichmo) [inline src/System.Management.Automation/engine/PropertyAccessor.cs]: Good point. I removed it

File: test/powershell/engine/PropertyAccessor.Tests.ps1 (hunk 3 above)
Comment (mirichmo) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: fixed

File: test/powershell/engine/PropertyAccessor.Tests.ps1 (hunk 8 above)
Comment (mirichmo) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: Fixed

File: src/System.Management.Automation/engine/PropertyAccessor.cs (hunk 1 above)
Comment (lzybkr) [inline src/System.Management.Automation/engine/PropertyAccessor.cs]: Indeed - CreateDirectory will check if the directory exists, so we can remove our redundant check.

File: test/powershell/engine/PropertyAccessor.Tests.ps1 (hunk 10 above)
Comment (mirichmo) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: Added

File: test/powershell/engine/PropertyAccessor.Tests.ps1 (hunk 4 above)
Comment (mirichmo) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: Fixed

File: test/powershell/engine/PropertyAccessor.Tests.ps1 (hunk 9 above)
Comment (mirichmo) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: Fixed

File: test/powershell/engine/PropertyAccessor.Tests.ps1 (hunk 6 above)
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: Thanks for the link the discussion. I think it depends on how many `Describe` sections you expect to be in a file. If there is just one `Describe`, then it's cleaner to have it in `BeforeAlll` and `AfterAll`. But I'm fine keep the try/finally as it's possible that we will add more `Describe` sections later.

File: test/powershell/engine/PropertyAccessor.Tests.ps1 (hunk 2 above)
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: #Closed

File: test/powershell/engine/PropertyAccessor.Tests.ps1 (hunk 3 above)
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: #Closed

File: test/powershell/engine/PropertyAccessor.Tests.ps1 (hunk 4 above)
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: #Closed

File: test/powershell/engine/PropertyAccessor.Tests.ps1 (hunk 9 above)
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: #Closed

File: test/powershell/engine/PropertyAccessor.Tests.ps1 (hunk 11 above)
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: #Closed

File: test/powershell/engine/PropertyAccessor.Tests.ps1 (hunk 7 above)
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: #Closed

File: test/powershell/engine/PropertyAccessor.Tests.ps1 (hunk 8 above)
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: #Closed

File: test/powershell/engine/PropertyAccessor.Tests.ps1 (hunk 10 above)
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: #Closed

File: test/powershell/engine/PropertyAccessor.Tests.ps1 [hunk 12]
```diff
@@ -0,0 +1,103 @@
...
+# 
+
+try {
+    # Skip these tests when run against "InBox" PowerShell
+    $IsInbox = $PSHOME.EndsWith('\WindowsPowerShell\v1.0', [System.StringComparison]::OrdinalIgnoreCase)
+    $productName = "PowerShell"
+
+    #skip all tests on non-windows platform
+    $originalDefaultParameterValues = $PSDefaultParameterValues.Clone()
+    $PSDefaultParameterValues["it:skip"] = (!$IsWindows -or $IsInbox)
```
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: Thanks for take Nano/IoT PS into account. Now it makes sense to have `$skipTest = !$IsWindows -or $IsInbox`, because the `if ($IsWindows)` below should actually be `if (!skipTest)`.

File: test/powershell/engine/PropertyAccessor.Tests.ps1 [hunk 13]
```diff
@@ -0,0 +1,103 @@
...
+
+    Describe "User-Specific PowerShellProperties.json Modifications" -Tags "CI" {
+
+        BeforeAll {
+            if ($IsWindows) {
```
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: It should be `if (!skipTest)`

File: test/powershell/engine/PropertyAccessor.Tests.ps1 [hunk 14]
```diff
@@ -0,0 +1,103 @@
...
+                }
+
+                # Save the original Process ExecutionPolicy. The tests assume that it is Undefined
+                $processExecutionPolicy = Get-ExecutionPolicy -Scope Process
+                Set-ExecutionPolicy -Scope Process -ExecutionPolicy Undefined
+            }
+        }
+
+        BeforeEach {
+            if ($IsWindows) {
```
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: It should be `if (!skipTest)`

File: test/powershell/engine/PropertyAccessor.Tests.ps1 [hunk 15]
```diff
@@ -0,0 +1,103 @@
...
+                Set-Content -Path $userPropertiesFile -Value '{"Microsoft.PowerShell:ExecutionPolicy":"RemoteSigned"}'
+            }
+        }
+
+        AfterAll {
+            if ($IsWindows) {
```
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: It should be `if (!skipTest)`

**Review by daxian-dbw — CHANGES_REQUESTED** [review]

File: test/powershell/engine/PropertyAccessor.Tests.ps1 (hunk 13 above)
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: #Closed

File: test/powershell/engine/PropertyAccessor.Tests.ps1 (hunk 14 above)
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: #Closed

File: test/powershell/engine/PropertyAccessor.Tests.ps1 (hunk 15 above)
Comment (daxian-dbw) [inline test/powershell/engine/PropertyAccessor.Tests.ps1]: #Closed

**Review by daxian-dbw — APPROVED** [review]
LGTM.

**Comment by daxian-dbw** [comment]
@lzybkr do you still have concerns on this PR? If not, I will merge it.
