### PR TITLE
Fix error message from new symbolic link missing target

### LINKED ISSUE #13073: Cryptic error message on new symbolic link missing value
## Steps to reproduce

```powershell
NI -TY S .
```

## Expected behavior

```none
Supply values for the following parameters:
Value:
```

## Actual behavior

```none
New-Item: .
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by yecril71pl**
# PR Summary

Fixes #13073 (well, at least descreases its morbidity).

## PR Context

When the target value was not given and `New-Item` throws an exception, use the custom message format intended to be used.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

File: src/System.Management.Automation/engine/SessionStateContainer.cs [hunk 1]
```diff
@@ -3500,14 +3500,14 @@ internal Collection<PSObject> NewItem(string[] paths, string name, string type,
                     {
                         if (content == null)
                         {
-                            throw PSTraceSource.NewArgumentNullException(SessionStateStrings.NewItemValueNotSpecified, path);
+                            throw PSTraceSource.NewArgumentNullException(nameof(content), SessionStateStrings.NewItemValueNotSpecified, path);
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/SessionStateContainer.cs:3503]: Please update the resource string. It is used only in the context so we can get better message like:
```
New-Item: Item '.' cannot be created because Target was not specified.
```

File: src/System.Management.Automation/engine/SessionStateContainer.cs [hunk 2]
```diff
@@ -3500,14 +3500,14 @@ internal Collection<PSObject> NewItem(string[] paths, string name, string type,
...
                         }
 
                         string targetPath = content.ToString();
 
                         if (string.IsNullOrEmpty(targetPath))
                         {
-                            throw PSTraceSource.NewArgumentNullException(SessionStateStrings.PathNotFound, targetPath);
+                            throw PSTraceSource.NewArgumentNullException(nameof(targetPath), SessionStateStrings.PathNotFound, targetPath);
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/SessionStateContainer.cs:3510]: I think it was and is not correct.
```suggestion
                            throw PSTraceSource.NewArgumentNullException(nameof(targetPath), SessionStateStrings.NewItemValueNotSpecified, path);
```

File: test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1 [hunk 3]
```diff
@@ -185,6 +185,11 @@ Describe "New-Item" -Tags "CI" {
             Pop-Location
         }
     }
+
+    It "Should display an error message when a symbolic link target is not specified" {
+        { New-Item -Name $testfile -Path $tmpDirectory -ItemType SymbolicLink } | Should -Throw -ErrorId 'ArgumentNull,Microsoft.PowerShell.Commands.NewItemCommand'
+        $ERROR | Select-Object -First 1 | Foreach-Object Exception | Foreach-Object Message | Should -Contain 'value'
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1:191]: Please remove this. We never check "Message" because of localization.
We could check `ParamName` instead.

Also we could add a test for second condition too (for `content.ToString()`)

File: src/System.Management.Automation/engine/SessionStateContainer.cs (hunk 2 above)
Comment (yecril71pl) [reply src/System.Management.Automation/engine/SessionStateContainer.cs:3510]: I think it is dead code.

Comment (iSazonov) [reply src/System.Management.Automation/engine/SessionStateContainer.cs:3510]: Really the New-Item parameter is `Value` and type of the parameter is `object`. So user can set an object here. I agree that it is an edge case but for consistency we should fix and test the code path. (You could thing about that the Value could get more complicated expression in future, maybe scriptblock?)

File: src/System.Management.Automation/engine/SessionStateContainer.cs [hunk 4]
```diff
@@ -3498,16 +3498,11 @@ internal Collection<PSObject> NewItem(string[] paths, string name, string type,
...
-                        if (content == null)
-                        {
-                            throw PSTraceSource.NewArgumentNullException(SessionStateStrings.NewItemValueNotSpecified, path);
-                        }
-
-                        string targetPath = content.ToString();
+                        string targetPath;
 
-                        if (string.IsNullOrEmpty(targetPath))
+                        if (content == null || string.IsNullOrEmpty(targetPath = content.ToString()))
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/SessionStateContainer.cs:3503]: Please use new operator:
```suggestion
                        if (content is null || string.IsNullOrEmpty(targetPath = content.ToString()))
```

File: test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1 [hunk 5]
```diff
@@ -185,6 +185,13 @@ Describe "New-Item" -Tags "CI" {
             Pop-Location
         }
     }
+
+    It "Should display an error message when a symbolic link target is not specified" {
+        { New-Item -Name:$testfile -Path:$tmpDirectory -ItemType:SymbolicLink } | Should -Throw -ErrorId 'ArgumentNull,Microsoft.PowerShell.Commands.NewItemCommand'
+        $Error | Select-Object -First:1 | Foreach-Object Exception | Foreach-Object ParamName | Should -Be 'content'
+        { New-Item -Name:$testfile -Path:$tmpDirectory -ItemType:SymbolicLink -Value:{} } | Should -Throw -ErrorId 'ArgumentNull,Microsoft.PowerShell.Commands.NewItemCommand'
+        $Error | Select-Object -First:1 | Foreach-Object Exception | Foreach-Object ParamName | Should -Be 'content'
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1:193]: Please follow common test style.
We can safely use `$Error[0]`.
We prefer to use `-BeExactly` for strings.
```suggestion
        { New-Item -Name $testfile -Path $tmpDirectory -ItemType SymbolicLink } | Should -Throw -ErrorId 'ArgumentNull,Microsoft.PowerShell.Commands.NewItemCommand'
        $Error[0].Exception.ParamName | Should -BeExactly 'Content'
        { New-Item -Name $testfile -Path $tmpDirectory -ItemType:SymbolicLink -Value {} } | Should -Throw -ErrorId 'ArgumentNull,Microsoft.PowerShell.Commands.NewItemCommand'
         $Error[0].Exception.ParamName | Should -BeExactly 'Content'
```

File: test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1 [hunk 6]
```diff
@@ -185,6 +185,13 @@ Describe "New-Item" -Tags "CI" {
             Pop-Location
         }
     }
+
+    It "Should display an error message when a symbolic link target is not specified" {
+        { New-Item -Name $testfile -Path $tmpDirectory -ItemType SymbolicLink } | Should -Throw -ErrorId 'ArgumentNull,Microsoft.PowerShell.Commands.NewItemCommand'
+        $Error[0].Exception.ParamName | Should -BeExactly 'Content'
+        { New-Item -Name $testfile -Path $tmpDirectory -ItemType:SymbolicLink -Value {} } | Should -Throw -ErrorId 'ArgumentNull,Microsoft.PowerShell.Commands.NewItemCommand'
+         $Error[0].Exception.ParamName | Should -BeExactly 'Content'
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1:193]:
```suggestion
        $Error[0].Exception.ParamName | Should -BeExactly 'content'
        { New-Item -Name $testfile -Path $tmpDirectory -ItemType:SymbolicLink -Value {} } | Should -Throw -ErrorId 'ArgumentNull,Microsoft.PowerShell.Commands.NewItemCommand'
         $Error[0].Exception.ParamName | Should -BeExactly 'content'
```

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
@yecril71pl Thanks for discovering and fixing the issue!

**Comment by yecril71pl** [comment]
> @yecril71pl Thanks for discovering and fixing the issue!

My pleasure.  I would like to note that:
1. I am still unhappy that `-TARGET` is not formally mandatory in this case.
2. I contend that `-PARAMETER:VALUE` is a better syntax in most cases because it is explicit and unambiguous.

**Comment by iSazonov** [comment]
> I am still unhappy that -TARGET is not formally mandatory in this case.

The cmdlet is provider based. I think it is impossible to make it mandatory for all scenarios. So the fix is good.

> I contend that -PARAMETER:VALUE is a better syntax in most cases because it is explicit and unambiguous

We follow common pattern for tests. It would be huge work to change a style for all tests.
