### PR TITLE
Fix ConvertTo-SecureString with key regression due to .NET breaking change

### LINKED ISSUE #16047: ConvertTo-SecureString truncates to multiples of 8 characters
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In 7.2.0-preview.9, `ConvertTo-SecureString` with either `-Key` or `-SecureKey` truncates the payload down to the nearest multiple of eight characters.  `ConvertFrom-SecureString` seems to be fine; SecureStrings created in 7.1.4 and imported to 7.2.0-preview.9 aren't truncated when converted to plaintext.

### Expected behavior

```console
PS> $Key = [Byte[]]::New(32)
>> '[8Chars][8Chars][Not8]' |
>> ConvertTo-SecureString -AsPlainText -Force |
>> ConvertFrom-SecureString -Key $Key |
>> ConvertTo-SecureString -Key $Key |
>> ConvertFrom-SecureString -AsPlainText
[8Chars][8Chars][Not8]

PS> $Key = [Byte[]]::New(32)
>> '🟥🟧🟨🟩🟦🟪' |
>> ConvertTo-SecureString -AsPlainText -Force |
>> ConvertFrom-SecureString -Key $Key |
>> ConvertTo-SecureString -Key $Key |
>> ConvertFrom-SecureString -AsPlainText
🟥🟧🟨🟩🟦🟪
```

### Actual behavior

```console
PS> $Key = [Byte[]]::New(32)
>> '[8Chars][8Chars][Not8]' |
>> ConvertTo-SecureString -AsPlainText -Force |
>> ConvertFrom-SecureString -Key $Key |
>> ConvertTo-SecureString -Key $Key |
>> ConvertFrom-SecureString -AsPlainText
[8Chars][8Chars]

PS> $Key = [Byte[]]::New(32)
>> '🟥🟧🟨🟩🟦🟪' |
>> ConvertTo-SecureString -AsPlainText -Force |
>> ConvertFrom-SecureString -Key $Key |
>> ConvertTo-SecureString -Key $Key |
>> ConvertFrom-SecureString -AsPlainText
🟥🟧🟨🟩
```

### Error details

_No response_

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.9
PSEdition                      Core
GitCommitId                    7.2.0-preview.9
OS                             Microsoft Windows 10.0.22449
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by PaulHigin**
# PR Summary

This PR fixes a regression in ConvertTo-SecureString found and reported by this [Issue](https://github.com/PowerShell/PowerShell/issues/16047).
Fix #16047.

## PR Context

This regression was caused by the change of behavior in the .NET CryptoStream.Read() method.  Previously, the Read method would synchronously read entire stream contents into the provided buffer, until the buffer was filled or the stream ended.  It was recently changed to read available data and return before the buffer is filled or the stream ended, breaking the existing code which would now read only partial stream contents.

Instead of performing multiple reads to ensure all stream content is obtained, this change uses an alternative common pattern to copy entire stream contents.  It also takes care to dispose all disposable objects and zero out clear-text buffers.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/security/SecureStringHelper.cs [hunk 1]
```diff
@@ -254,48 +252,46 @@ internal static EncryptionResult Encrypt(SecureString input, byte[] key, byte[]
...
-            if (iv == null)
-                iv = aes.IV;
-
-            encryptor = aes.CreateEncryptor(key, iv);
-            ms = new MemoryStream();
-
-            using (cs = new CryptoStream(ms, encryptor, CryptoStreamMode.Write))
+            using (Aes aes = Aes.Create())
             {
+                if (iv == null)
```
Comment (rjmholt) [inline src/System.Management.Automation/security/SecureStringHelper.cs:261]:
```suggestion
                if (iv is null)
```

File: src/System.Management.Automation/security/SecureStringHelper.cs [hunk 2]
```diff
@@ -254,48 +252,46 @@ internal static EncryptionResult Encrypt(SecureString input, byte[] key, byte[]
...
+                    iv = aes.IV;
+                }
+
                 //
                 // get clear text data from the input SecureString
                 //
                 byte[] data = GetData(input);
+                try
+                {
+                    using (var encryptor = aes.CreateEncryptor(key, iv))
```
Comment (rjmholt) [inline src/System.Management.Automation/security/SecureStringHelper.cs:272]:
```suggestion
                    using (ICryptoTransform encryptor = aes.CreateEncryptor(key, iv))
```

File: src/System.Management.Automation/security/SecureStringHelper.cs [hunk 3]
```diff
@@ -346,44 +340,33 @@ internal static SecureString Decrypt(string input, byte[] key, byte[] IV)
...
-                //
-                // decrypt the data
-                //
-                numBytesRead = cs.Read(tempDecryptedData, 0,
-                                       tempDecryptedData.Length);
-
-                decryptedData = new byte[numBytesRead];
-
-                for (int i = 0; i < numBytesRead; i++)
+                using (var decryptor = aes.CreateDecryptor(key, IV ?? aes.IV))
```
Comment (rjmholt) [inline src/System.Management.Automation/security/SecureStringHelper.cs:348]:
```suggestion
                using (ICryptoTransform decryptor = aes.CreateDecryptor(key, IV ?? aes.IV))
```

Comment (rjmholt) [reply src/System.Management.Automation/security/SecureStringHelper.cs:348]: We seem to use the `IV ?? aes.IV` pattern here and a separate assignment above. Might be worth changing the one above while we're improving the code?

**Review by rjmholt — APPROVED** [review]

File: src/System.Management.Automation/security/SecureStringHelper.cs (hunk 3 above)
Comment (PaulHigin) [reply src/System.Management.Automation/security/SecureStringHelper.cs]: The separate assignment above is needed because the initialization vector is also returned with the encrypted data.

**Comment by PaulHigin** [comment]
@rjmholt Thanks for the review!

File: src/System.Management.Automation/security/SecureStringHelper.cs [hunk 4]
```diff
@@ -227,14 +225,14 @@ internal static EncryptionResult Encrypt(SecureString input, SecureString key)
...
-            Array.Clear(keyBlob, 0, keyBlob.Length);
-
-            return output;
+            try
+            {
+                return Encrypt(input, keyBlob);
+            }
+            finally
+            {
+                Array.Clear(keyBlob, 0, keyBlob.Length);
```
Comment (iSazonov) [inline src/System.Management.Automation/security/SecureStringHelper.cs:234]:
```suggestion
                Array.Clear(keyBlob);
```

**Review by vexx32 — APPROVED** [review]

File: src/System.Management.Automation/security/SecureStringHelper.cs [hunk 5]
```diff
@@ -321,14 +315,14 @@ internal static SecureString Decrypt(string input, SecureString key, byte[] IV)
...
-            Array.Clear(keyBlob, 0, keyBlob.Length);
-
-            return output;
+            try
+            {
+                return Decrypt(input, keyBlob, IV);
+            }
+            finally
+            {
+                Array.Clear(keyBlob, 0, keyBlob.Length);
```
Comment (iSazonov) [inline src/System.Management.Automation/security/SecureStringHelper.cs:324]:
```suggestion
                Array.Clear(keyBlob);
```

File: src/System.Management.Automation/security/SecureStringHelper.cs [hunk 6]
```diff
@@ -254,48 +252,46 @@ internal static EncryptionResult Encrypt(SecureString input, byte[] key, byte[]
...
                 //
                 // get clear text data from the input SecureString
                 //
                 byte[] data = GetData(input);
+                try
+                {
+                    using (ICryptoTransform encryptor = aes.CreateEncryptor(key, iv))
+                    using (var sourceStream = new MemoryStream(data))
+                    using (var encryptedStream = new MemoryStream())
+                    {
```
Comment (iSazonov) [inline src/System.Management.Automation/security/SecureStringHelper.cs:275]: We could use new syntax and remove the nesting (here, above and below) since we reformat the code.

File: src/System.Management.Automation/security/SecureStringHelper.cs [hunk 7]
```diff
@@ -346,44 +340,33 @@ internal static SecureString Decrypt(string input, byte[] key, byte[] IV)
...
             //
-            Aes aes = Aes.Create();
-            encryptedData = ByteArrayFromString(input);
-
-            var decryptor = aes.CreateDecryptor(key, IV ?? aes.IV);
-
-            MemoryStream ms = new MemoryStream(encryptedData);
-
-            using (CryptoStream cs = new CryptoStream(ms, decryptor, CryptoStreamMode.Read))
+            using (var aes = Aes.Create())
```
Comment (iSazonov) [inline src/System.Management.Automation/security/SecureStringHelper.cs:346]: The same for nesting.

File: src/System.Management.Automation/security/SecureStringHelper.cs [hunk 8]
```diff
@@ -346,44 +340,33 @@ internal static SecureString Decrypt(string input, byte[] key, byte[] IV)
...
 
-                return s;
+                    byte[] decryptedData = targetStream.ToArray();
+                    try
+                    {
+                        return New(decryptedData);
+                    }
+                    finally
+                    {
+                        Array.Clear(decryptedData, 0, decryptedData.Length);
```
Comment (iSazonov) [inline src/System.Management.Automation/security/SecureStringHelper.cs:367]:
```suggestion
                        Array.Clear(decryptedData);
```

File: src/System.Management.Automation/security/SecureStringHelper.cs (hunk 6 above)
Comment (PaulHigin) [reply src/System.Management.Automation/security/SecureStringHelper.cs:275]: I don't feel this is necessary.

File: src/System.Management.Automation/security/SecureStringHelper.cs (hunk 7 above)
Comment (PaulHigin) [reply src/System.Management.Automation/security/SecureStringHelper.cs:346]: I don't feel this is necessary.

**Review by iSazonov — APPROVED** [review]
