### PR TITLE
Wait for SSH exit when closing remote connection

### LINKED ISSUE #13356: Defunct ssh processes and CPU load are kept after executing powershell through ssh on linux
## Steps to reproduce
Setup powershell ssh on linux system using the following guide: https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7

On the host machine (debian 10) execute the following command.

```
Invoke-Command -ScriptBlock {return "kaas";} -SSHTransport -HostName ps@localhost -KeyFilePath /home/ps/.ssh/id_rsa
```

## Expected behavior

No defunct processes from SSH on the machine executing PowerShell.

## Actual behavior

Each execution of the PowerShell script leaves a defunct ssh process. See example of 'ps aux' below. 

On the parent process there remains a CPU load which is unexpected for a server application. This becomes a major issue with a large amount defunct processes which seems to stack the CPU load on the parent process.

```
root@<machine>:/app# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   3880  1504 ?        Ss   09:34   0:00 /bin/bash /entrypoint.sh
root        21  0.1  1.1 3794740 70496 ?       Sl   09:34   0:02 dotnet <dll>
root        81  0.0  0.0   4012  3116 pts/0    Ss   09:35   0:00 bash
root       338  0.0  0.0   4012  3196 pts/1    Ss   09:39   0:00 bash
root      1201  0.0  0.4 2968504 27624 pts/0   Sl+  09:53   0:00 pwsh
root      1209  1.9  2.0 4157756 125756 pts/0  Sl+  09:53   0:04 dotnet /root/.dotnet/tools/.store/powershell/7.0.3/powershe
root      1240  0.0  0.0      0     0 pts/0    Z+   09:53   0:00 [ssh] <defunct>
root      1247  0.0  0.0      0     0 pts/0    Z+   09:53   0:00 [ssh] <defunct>
root      1253  0.0  0.0      0     0 pts/0    Z+   09:53   0:00 [ssh] <defunct>
root      1267  0.0  0.0      0     0 pts/0    Z+   09:53   0:00 [ssh] <defunct>
root      1274  0.0  0.0      0     0 pts/0    Z+   09:53   0:00 [ssh] <defunct>
root      1373  0.3  0.0      0     0 pts/0    Z+   09:57   0:00 [ssh] <defunct>
root      1377  0.0  0.0   7652  2684 pts/1    R+   09:57   0:00 ps aux 
```

## Environment data

Host machine:

```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Linux 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Target machine:

```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Linux 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

The configuration is that this is a Docker container (host) running a sidecar container (target).

The used image for the host is: 'mcr.microsoft.com/dotnet/core/aspnet:3.1'
The used image for the target is 'mcr.microsoft.com/powershell'

### PR DESCRIPTION
**Pull request by dinhngtu**
# PR Summary

Fixes #13356 by adding custom functions for killing and waiting for SSH processes. Requires PowerShell/PowerShell-Native#63.

## PR Context

On Unix, after a SSH session finishes, PowerShell uses System.Diagnostics.Process.Kill() to stop the process, but doesn't reap the process with waitpid(). This causes SSH to become a defunct (zombie) process.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

File: src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs [hunk 1]
```diff
@@ -2463,6 +2477,12 @@ private static unsafe void FreeArray(byte** arr, int length)
             int redirectStdin, int redirectStdout, int redirectStderr, int creationFlags,
             out int lpChildPid, out int stdinFd, out int stdoutFd, out int stderrFd);
 
+        [DllImport("libpsl-native", SetLastError = true)]
+        internal static extern bool KillProcess(int pid);
+
+        [DllImport("libpsl-native", SetLastError = true)]
+        internal static extern int WaitPid(int pid, bool nohang);
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs:2484]: Do we really need this in libpsl? Why not call from libc directly? Search by `DllImport("libc"` for examples.

Also we should add `[return: MarshalAs(UnmanagedType.Bool)]`.

Comment (dinhngtu) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs:2484]: Signals and other constants don't have a defined, standardized value, so I prefer to wrap it in libpsl and use the header constants there rather than coding it into S.M.A.

> Also we should add `[return: MarshalAs(UnmanagedType.Bool)]`.

Should I do the same for WaitPid as well?

Comment (iSazonov) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: I don't see we use these constants - I see only 2 parameters and return value.

Comment (dinhngtu) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: These are referenced in libpsl wrappers: PowerShell/PowerShell-Native#63

If you called directly into libc from S.M.A then you'd need to call `kill(pid, SIGKILL)` and `waitpid(pid, NULL, WNOHANG)`.

Comment (iSazonov) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: Aren't both POSIX?

Comment (dinhngtu) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: POSIX doesn't define the specific values of either constants (though SIGKILL should equal 9 most of the time).

Comment (iSazonov) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: Do they really different on supported platforms?

Comment (dinhngtu) [reply src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs]: I haven't looked into all platforms but following POSIX should be more portable than hardcoding the constants in S.M.A. While it might work with SIGKILL I doubt it'll be very reliable to hardcode WNOHANG. In addition, if we directly imported kill()/waitpid() in S.M.A it would then be possible to use them directly with nonportable constants, so I prefer to restrict the call interface in this fashion.

File: src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs [hunk 2]
```diff
@@ -2463,6 +2477,13 @@ private static unsafe void FreeArray(byte** arr, int length)
             int redirectStdin, int redirectStdout, int redirectStderr, int creationFlags,
             out int lpChildPid, out int stdinFd, out int stdoutFd, out int stderrFd);
 
+        [DllImport("libpsl-native", SetLastError = true)]
+        [return: MarshalAs(UnmanagedType.Bool)]
+        internal static extern bool KillProcess(int pid);
+
+        [DllImport("libpsl-native", SetLastError = true)]
+        internal static extern int WaitPid(int pid, bool nohang);
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs:2485]: No need to set SetLastError if we do not use it.

**Comment by adityapatwardhan** [comment]
@dinhngtu Just merged the PR in PowerShell Native.

File: src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs [hunk 3]
```diff
@@ -2265,6 +2270,15 @@ internal override BaseClientSessionTransportManager CreateClientSessionTransport
             return pid;
         }
 
+        private static void KillSSHProcessImpl(int pid)
+        {
+            // killing a zombie might or might not return ESRCH, so we ignore kill's return value
+            KillProcess(pid);
+            // block while waiting for process to die
+            // shouldn't take long after SIGKILL
+            WaitPid(pid, false);
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs:2279]:
```suggestion
            // killing a zombie might or might not return ESRCH, so we ignore kill's return value
            KillProcess(pid);

            // block while waiting for process to die
            // shouldn't take long after SIGKILL
            WaitPid(pid, false);
```

File: src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs [hunk 4]
```diff
@@ -2496,6 +2510,13 @@ private static unsafe void FreeArray(byte** arr, int length)
             int redirectStdin, int redirectStdout, int redirectStderr, int creationFlags,
             out int lpChildPid, out int stdinFd, out int stdoutFd, out int stderrFd);
 
+        [DllImport("libpsl-native")]
+        [return: MarshalAs(UnmanagedType.Bool)]
+        internal static extern bool KillProcess(int pid);
+
+        [DllImport("libpsl-native")]
+        internal static extern int WaitPid(int pid, bool nohang);
+
```
Comment (iSazonov) [inline src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs:2519]: I'd move this in https://github.com/PowerShell/PowerShell/blob/5abb90f21a12e1816312fb3b204835a2ad9d1065/src/System.Management.Automation/CoreCLR/CorePsPlatform.cs#L1043

**Comment by dinhngtu** [comment]
> @dinhngtu Just merged the PR in PowerShell Native.

Should I update something in powershell to use the new libpsl? I had to manually replace libpsl-native.so to test the new native library.

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
@dinhngtu It is still unpublished https://www.nuget.org/packages/Microsoft.PowerShell.Native/

**Comment by iSazonov** [comment]
@dinhngtu 7.2.0-preview.2 was published - please update the reference in csproj file.

**Comment by iSazonov** [comment]
@daxian-dbw @TravisEz13 Could you please clarify what is "1 workflow awaiting approval"? Is it CodeQL? Can I approve?

**Review by adityapatwardhan — APPROVED** [review]

**Comment by iSazonov** [comment]
@dinhngtu Thanks for your contribution!
