### PR TITLE
Handle exception if enumerating files fails when rebuilding path to have correct casing

### LINKED ISSUE #11013: AppX package installation locations cannot be targeted with Get-Item / Get-ChildItem
This is a regression from Windows PowerShell.

On Windows, AppX packages (for in-box applications such as Calculator) are installed in subfolders of hidden folder `$env:ProgramFiles\WindowsApps`

PowerShell Core cannot locate these folders, not even with `-Force` (which shouldn't be necessary, because it is only the parent folder that is hidden).

Curiously, you _can_ target _files inside_ those folders, though only by _literal_ name.

The problem may be related to permissions.

# Steps to reproduce

Run the following on Windows:

```powershell
$pkgDir = (Get-AppxPackage Microsoft.WindowsCalculator).InstallLocation

# OK, because a file *inside* the dir. is targeted by literal name.
{ Get-Item -EA Stop -Force $pkgDir\Calculator.exe } | Should -Not -Throw

# Targeting the dir. directly fails:
{ Get-Item -EA Stop -Force -LiteralPath $pkgDir } | Should -Not -Throw
{ Get-ChildItem -EA Stop -Force -LiteralPath $pkgDir } | Should -Not -Throw

# Using a wildcard produces no output.
# (This problem, unlike the others, also occurs in Windows PowerShell).
Get-ChildItem -Force -Path $pkgDir*  | Should -Not -BeNullOrEmpty
```

# Expected behavior

All tests should pass.

# Actual behavior

All tests but the first fail, because the directory itself cannot be targeted:

```none
"Cannot find path 'C:\Program Files\WindowsApps\Microsoft.WindowsCalculator_10.1908.0.0_x64__8wekyb3d8bbwe' because it does not exist."
```

The wildcard-based command produces no output.

# Environment data

```none
PowerShell Core 7.0.0-preview.5
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

In the code to reconstruct a path with correct casing, it has to go through each segment and use enumeration to get the correct case.  On some directories the user may not have permission to enumerate although they can still read a file/folder within that directory.  Fix is if there is an exception during enumeration, fail gracefully by just returning back the original path.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/11013

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 1]
```diff
@@ -161,14 +161,22 @@ private static string GetCorrectCasedPath(string path)
                     else
```
Comment (PoshChan) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: @SteveL-MSFT, your last commit had 1 failures in `PowerShell-CI-static-analysis`
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/cmdlet-example/command-line-simple-example.md.https://www.microsoft.com/net/core#linuxubuntu should work
```powershell
retry of URL failed with error: Response status code does not indicate success: 400 (Bad Request).
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 117
117:                                     throw "retry of URL failed with error: $($_.Exception.Message)"

```

**Comment by PoshChan** [comment]
@SteveL-MSFT, successfully started retry of `PowerShell-CI-static-analysis`

File: test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1 [hunk 2]
```diff
@@ -279,6 +279,23 @@ Describe "Basic FileSystem Provider Tests" -Tags "CI" {
...
+    Context "Appx path" {
+        BeforeAll {
+            $skipTest = $true
+            if ($IsWindows -and (Get-Command -Name Get-AppxPackage) -and (Get-AppxPackage Microsoft.WindowsCalculator)) {
+                $skipTest = $false
+            }
+        }
+
+        It "Can get an appx package item" -Skip:$skipTest {
+            $pkgDir = (Get-AppxPackage Microsoft.WindowsCalculator).InstallLocation
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1]: I haven't the package on my system.
```suggestion
            $pkgDir = (Get-AppxPackage)[0].InstallLocation
```

**Review by iSazonov — APPROVED** [review]

**Review by anmenaga — APPROVED** [review]
