### PR TITLE
Fix Parent property on processes with complex name

### LINKED ISSUE #12908: Process.Parent property is null on Linux if the process name contains a space
Discovered in #12894

https://github.com/PowerShell/PowerShell/blob/5ef69e88bc2a6e500349a8eec8d13bb27e143e3e/src/System.Management.Automation/CoreCLR/CorePsPlatform.cs#L972-L985
If a process name contains a space (like  `(ConsoleHost mai)` vs `(bash)`) the split returns additional extra element and we get wrong value with `parts[3]`.

The fix could be - search `)` to skip the process name.

`/proc/[pid]/stat` format for reference https://man7.org/linux/man-pages/man5/proc.5.html

## Steps to reproduce

```powershell
(Get-Process -Name 'process name').Parent
```

## Expected behavior

```none
# Returns parent process object
```

## Actual behavior

```none
# Returns null
```

## Environment data

```none
pwsh 7.1 Preview3
```

### LINKED ISSUE #17541: Parent Process Object is Missing
## Background 

I want to list the processes on my system. 

``` PowerShell
Get-Process 

 NPM(K)    PM(M)      WS(M)     CPU(s)      Id  SI ProcessName
 ------    -----      -----     ------      --  -- -----------
      0     0.00       3.75       0.00    1270 …69 (sd-pam)
      0     0.00       9.84       1.25     962 962 accounts-daemon
      0     0.00       0.00       0.00     117   0 acpi_thermal_pm
...

```

Further, I would like to sort the processes by parent. 

I'm on Linux. And I have a `Parent` property. I'm not sure if that is available on Windows. 

``` PowerShell
Get-Process | Select-Object @{name='Parent'; expr={$_.Parent.Id}}, Id, Name | Sort-Object Parent, Id

Parent     Id Name
------     -- ----
       105455 Web Content
1        2617 firefox
1      135731 code --no-sandbox --force-user-env --unity-launch --enable-crashpad
1284     1362 Thunar
1370   127909 thunderbird
1667     1688 pwsh
1688    11884 vim

```

## Issue

The issue I noticed was that some of the Parent Process IDs (PPID) were missing. 

Note there are no IDs in the Parent column below. 

``` PowerShell
Get-Process | Select-Object @{name='Parent'; expr={$_.Parent.Id}}, Id, Name | Sort-Object Parent, Id

Parent     Id Name
------     -- ----
            1 systemd
            2 kthreadd
          847 UVM global queue
          848 UVM deferred release queue
          849 UVM Tools Event Queue
...
       105455 Web Content
       105458 Web Content
...

```

It is not clear to me if there is a bug with PowerShell, a bug with .NET, or something I don't understand. 

The one-liner I'm issuing seems correct to me. 

But I'm not getting a Parent Process ID for worker processes, which is the output I expect. 

I don't think there is a permission issue because I am the only user. And the native task manager shows the correct parent and child relationships for processes. 

The affected processes are mostly Mozilla Firefox and Thunderbird workers. 

Screenshot_2022-06-19_15-52-37

## Environment 

``` text
$PSVersionTable | Format-Table -Wrap

Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Linux 5.18.5-1-MANJARO #1 SMP PREEMPT_DYNAMIC
                               Thu Jun 16 12:28:47 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

### PR DESCRIPTION
**Pull request by jborean93**
# PR Summary

Fix the `Parent` property to retrieve the parent process on Linux where
the process name has complex characters like a space or parenthesis.

## PR Context

Reads from `/proc/[pid]/status` rather than `/proc/[pid]/stat` on Linux to get the parent process id. The `status` file is nicer as each entry is on a newline and has a label making it easier to select the data required. This is an alternative approach to deal with process' with a space and parenthesis in the name avoiding the last index of logic or trying to correctly select the proper column in the `stat` file.

Fixes https://github.com/PowerShell/PowerShell/issues/12908
Fixes https://github.com/PowerShell/PowerShell/issues/17541

Alternative to https://github.com/PowerShell/PowerShell/pull/12925

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

File: src/System.Management.Automation/CoreCLR/CorePsPlatform.cs [hunk 1]
```diff
@@ -882,21 +883,37 @@ public static CommonStat GetStat(string path)
...
-                    if (parts.Length < 5)
+                    using FileStream fs = File.OpenRead(path);
+                    using StreamReader sr = new(fs);
+                    string line;
+                    while ((line = sr.ReadLine()) != null)
                     {
-                        return invalidPid;
+                        Match ppidMatch = Regex.Match(
+                            line,
+                            @"^PPid:\s+(\d+)$",
```
Comment (iSazonov) [inline src/System.Management.Automation/CoreCLR/CorePsPlatform.cs:906]: The proposal looks very expensive. I'd prefer #12925.

Comment (jborean93) [reply src/System.Management.Automation/CoreCLR/CorePsPlatform.cs:906]: Is the concern around the regex, the reading of multiple lines or something else? If it's the regex this could be changes to just doing `line.StartsWith("PPid: ")` and extract it from there but I thought regex gives some nicer validation.

My only concern about #12925 is if any extra entries are added to the `stat` file in the future that could mess with the `LastIndexOf(')')` check. I have no idea what the chances are of that happening but the file certainly has had additions in the past so I can't rule it out.

**Comment by daxian-dbw** [comment]
@JamesWTruher can you please review this PR?

File: src/System.Management.Automation/CoreCLR/CorePsPlatform.cs (hunk 1 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/CoreCLR/CorePsPlatform.cs:906]: @jborean93 is there any concern using `StartsWith()` and then splitting out the pid trimming the whitespace instead of a regex?

Comment (jborean93) [reply src/System.Management.Automation/CoreCLR/CorePsPlatform.cs:906]: The regex just ensure it's `PPid: digit` but considering this is probably mandated in the spec it's probably not something to be concerned about. I can change it to `StartsWith("PPid: ")` but didn't think regex would be that bad of a performance problem.

File: src/System.Management.Automation/CoreCLR/CorePsPlatform.cs [hunk 2]
```diff
@@ -882,21 +883,37 @@ public static CommonStat GetStat(string path)
...
+                var path = $"/proc/{pid}/status";
                 try
                 {
-                    var stat = System.IO.File.ReadAllText(path);
-                    var parts = stat.Split(' ', 5);
-                    if (parts.Length < 5)
+                    using FileStream fs = File.OpenRead(path);
+                    using StreamReader sr = new(fs);
+                    string line;
+                    while ((line = sr.ReadLine()) != null)
```
Comment (iSazonov) [inline src/System.Management.Automation/CoreCLR/CorePsPlatform.cs:902]: I suggest `File.ReadAllText()` and multiline Regex or IndexOf().

File: src/System.Management.Automation/CoreCLR/CorePsPlatform.cs (hunk 1 above)
Comment (daxian-dbw) [reply src/System.Management.Automation/CoreCLR/CorePsPlatform.cs:906]: @jborean93 Any chance to get the proposed changes done? Thanks!

Comment (jborean93) [reply src/System.Management.Automation/CoreCLR/CorePsPlatform.cs:906]: Sorry will get to this next week, just on holidays at the moment.

Comment (jborean93) [reply src/System.Management.Automation/CoreCLR/CorePsPlatform.cs]: Has been updated to use `StartsWith` instead as per the suggestion.

File: src/System.Management.Automation/CoreCLR/CorePsPlatform.cs (hunk 2 above)
Comment (jborean93) [reply src/System.Management.Automation/CoreCLR/CorePsPlatform.cs:900]: The benefit of `ReadLine()` here is that it streams the file rather than reads it all in memory. I've removed the regex stuff to just do `StartsWith()` as per the suggestion above.

**Comment by jborean93** [comment]
Looks like there might be a problem with using `testdrive:` in Pester. The permissions don't allow an unauthenticated users to set the executable bit breaking the tests for that scenario. Any suggestions on what to do there. I don't fully know how the tests are actually set up here.

File: src/System.Management.Automation/CoreCLR/CorePsPlatform.cs [hunk 3]
```diff
@@ -883,20 +883,40 @@ public static int GetProcFSParentPid(int pid)
...
                     {
-                        return invalidPid;
+                        if (!line.StartsWith("PPid:\t", StringComparison.OrdinalIgnoreCase))
+                        {
+                            continue;
+                        }
+
+                        string[] lineSplit = line.Split('\t', 2, StringSplitOptions.RemoveEmptyEntries);
+                        if (lineSplit.Length != 2)
```
Comment (iSazonov) [inline src/System.Management.Automation/CoreCLR/CorePsPlatform.cs:908]: Typo
```suggestion
                        string[] lineSplit = line.Split('\t', 3, StringSplitOptions.RemoveEmptyEntries);
                        if (lineSplit.Length != 3)
```

Comment (jborean93) [reply src/System.Management.Automation/CoreCLR/CorePsPlatform.cs]: Why did you change this, I only wanted a max of entries not 3 hence all the checks.

Comment (iSazonov) [reply src/System.Management.Automation/CoreCLR/CorePsPlatform.cs]: `a\tb\t\c` - if we need `b` we should split on 3.

Comment (jborean93) [reply src/System.Management.Automation/CoreCLR/CorePsPlatform.cs]: That’s not the case here, we only have the header and value. Please revert this commit.

File: src/System.Management.Automation/CoreCLR/CorePsPlatform.cs [hunk 4]
```diff
@@ -883,20 +883,40 @@ public static int GetProcFSParentPid(int pid)
...
+                    while ((line = sr.ReadLine()) != null)
                     {
-                        return invalidPid;
+                        if (!line.StartsWith("PPid:\t", StringComparison.OrdinalIgnoreCase))
+                        {
+                            continue;
+                        }
+
+                        string[] lineSplit = line.Split('\t', 3, StringSplitOptions.RemoveEmptyEntries);
+                        if (lineSplit.Length != 3)
```
Comment (iSazonov) [inline src/System.Management.Automation/CoreCLR/CorePsPlatform.cs:908]:
```suggestion
                        string[] lineSplit = line.Split('\t', 2, StringSplitOptions.RemoveEmptyEntries);
                        if (lineSplit.Length != 2)
```

File: src/System.Management.Automation/CoreCLR/CorePsPlatform.cs (hunk 3 above)
Comment (iSazonov) [reply src/System.Management.Automation/CoreCLR/CorePsPlatform.cs:908]: Ah, sorry, I forget it is another file.

**Comment by jborean93** [comment]
> Looks like there might be a problem with using testdrive: in Pester

Using `/tmp` as the path was enough to get it passing. Because it only runs on non-Windows that should be fine.

File: test/powershell/Modules/Microsoft.PowerShell.Management/Get-Process.Tests.ps1 [hunk 5]
```diff
@@ -138,5 +137,26 @@ Describe "Process Parent property" -Tags "CI" {
...
+        # Bug. See https://github.com/PowerShell/PowerShell/issues/12908
+        $commandName = 't ( e ( s ) t )'
+
+        $script = @'
+#!/bin/sh
+
+while true; do sleep 1; done
+'@
+
+        # Can't use testdrive: as unelevated user doesn't have perms in test in CI
```
Comment (iSazonov) [inline test/powershell/Modules/Microsoft.PowerShell.Management/Get-Process.Tests.ps1:151]: Please reword:
```suggestion
        # Can't use 'Testdrive:' as unelevated user doesn't have permissions to do 'chmod'.
```

I guess it is because .Net 7 RC1 has a breaking change in Directory.Create() where chmod mask was changed. If so, it might still break something in PowerShell or Pester.
/cc @nohwnd

**Review by iSazonov — APPROVED** [review]
LGTM in common.

If we don't want extra allocations, we could replace Split() by ReadonlySpan.TrimStart()

File: test/powershell/Modules/Microsoft.PowerShell.Management/Get-Process.Tests.ps1 (hunk 5 above)
Comment (jborean93) [reply test/powershell/Modules/Microsoft.PowerShell.Management/Get-Process.Tests.ps1:151]: I assumed this was just a byproduct of how PowerShell CI is set up. I've not looked into it but I believe the unelevated user may potentially be inheriting the same tmpdir as the elevated account and thus cannot set the execute bit on files in that dir. This is just a guess so your assumption could also be true.

**Review by daxian-dbw — APPROVED** [review]
LGTM. Thanks @jborean93!

**Comment by iSazonov** [comment]
@daxian-dbw Ready to merge?

**Comment by jborean93** [comment]
Thanks everyone for your reviews and suggestions.

**Comment by iSazonov** [comment]
@jborean93 Thanks for your contribution!
