### PR TITLE
Fix auto-downloading of files in OneDrive when doing `dir`

### LINKED ISSUE #7152: OneDrive "files on demand" (sparse files) being downloaded without contents being accessed.
Steps to reproduce
------------------
Change location to a folder synchronized with OneDrive where files or directories have not been accessed. This is represented in the UI by having a "cloud" icon in the "status" column in explorer. Run get-childitem for a listing of the contents. Any items that had a cloud icon in status now have a green check mark indicating that they have been downloaded. This can be verified in the OneDrive UI. 

Expected behavior
-----------------
Files are not downloaded until they are accessed.

Actual behavior
---------------
Files are downloaded without accessing contents. 

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

Related to the PR to [enable recursion into OneDrive](https://github.com/PowerShell/PowerShell/pull/9509) what's happening is that OneDrive online files are reparse points.  The current filesystemprovider automatically assumes a reparsepoint is a symlink so it opens the file trying to find the target of the symlink.  However, OneDrive online files are not symlinks so this causes the file to be downloaded so that it can be opened.  The fix is to use the same helper API in the other PR to check if it's a named surrogate and only then is it a symlink.  Otherwise, don't treat it as a symlink and don't try to retrieve the target.

Tested manually with my OneDrive folder.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/7152

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 3 failures in `PowerShell-CI-macos`
Test-Connection.Ping.Force IPv4 with implicit PingOptions
```powershell
Expected exactly $null, but got 10.79.10.99.
at <ScriptBlock>, /Users/vsts/agent/2.152.1/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1: line 91
91:             $result.Replies[0].Address              | Should -BeExactly $realAddress
```
Test-Connection.Ping.Force IPv4 with explicit PingOptions
```powershell
Expected exactly $null, but got 10.79.10.99.
at <ScriptBlock>, /Users/vsts/agent/2.152.1/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1: line 106
106:             $result1.Replies[0].Address              | Should -BeExactly $realAddress
```
Test-Connection.TraceRoute.TraceRoute works
```powershell
Expected exactly $null, but got 10.79.10.99.
at <ScriptBlock>, /Users/vsts/agent/2.152.1/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1: line 238
238:             $result.DestinationAddress | Should -BeExactly $realAddress
```

**Comment by SteveL-MSFT** [comment]
@PoshChan please retry macos,windows

**Comment by PoshChan** [comment]
@SteveL-MSFT, successfully started retry of `PowerShell-CI-macOS, PowerShell-CI-Windows`

**Comment by SteveL-MSFT** [comment]
Failing due to https://developercommunity.visualstudio.com/content/problem/607034/artifact-downloads-are-failing-201906.html

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs [hunk 1]
```diff
@@ -2001,7 +2001,8 @@ string ToModeString(FileSystemInfo fileSystemInfo)
         public static string NameString(PSObject instance)
         {
             return instance?.BaseObject is FileSystemInfo fileInfo
-                ? InternalSymbolicLinkLinkCodeMethods.IsReparsePoint(fileInfo)
+                ? (InternalSymbolicLinkLinkCodeMethods.IsReparsePoint(fileInfo) &&
+                    InternalSymbolicLinkLinkCodeMethods.IsNameSurrogateReparsePoint(fileInfo.FullName))
```
Comment (iSazonov) [inline src/System.Management.Automation/namespaces/FileSystemProvider.cs]: I see that we use `IsReparsePoint()` in 3 places and with the fix in 2 places we use `IsReparsePoint()` with `IsNameSurrogateReparsePoint()`. So question is should we do the same in 
`private static string Mode(PSObject instance, bool excludeHardLink)` too? If yes make sense join both the methods in one?

Comment (SteveL-MSFT) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs]: I saw that as well.  In the 3rd case, it's used to construct the `Mode` property.  I'm fine leaving that as-is so that an online file still shows up as `l` to indicate it is a link of some type.  Alternative would be to introduce a `o` to indicate online, but that may be confusing to users.

Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs]: My thoughts was that if user calls Mode property to display we will _download_ the file in the same way as with NameString().

Comment (sba923) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Of course, this is a matter of taste, but I tend to favor using "o" over "l" because "a link of some type" is also somewhat confusing--I prefer being able to easily tell an online file from a symlink.

**Comment by daxian-dbw** [comment]
Close and reopen the PR to force Windows CI build working properly.

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 1 above)
Comment (SteveL-MSFT) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs]: Let's have @PowerShell/powershell-committee discuss this

Comment (SteveL-MSFT) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs]: @PowerShell/powershell-committee reviewed this.  Currently, the length is in parenthesis already if the file is not downloaded locally so there doesn't seem to be a need to change the left column of mode introducing a new value.  Instead our recommendation is to continue to use `l` to show it is a link.

**Comment by SteveL-MSFT** [comment]
@iSazonov since @PowerShell/powershell-committee is ok with the change as it current exists regarding `mode`, if there are no code concerns, we should merge this

File: src/System.Management.Automation/namespaces/FileSystemProvider.cs (hunk 1 above)
Comment (iSazonov) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs]: @SteveL-MSFT Could you please address my comment about Mode property?

Comment (SteveL-MSFT) [reply src/System.Management.Automation/namespaces/FileSystemProvider.cs]: @iSazonov `Mode` is displayed by default and doesn't incur a download of the file.

**Review by iSazonov — APPROVED** [review]
