### PR TITLE
Test if a command is 'Out-Default' more thoroughly

### LINKED ISSUE #15651: Start-Transcript in Powershell .NET Interactive notebook hides future output
> NOTE: This issue is copied from https://github.com/dotnet/interactive/issues/1430

Once Start-Transcript appears on a PowerShell notebook, any attempt to output to the notebook fails.
See attached notebook for a repro.

As a user that has transcription enabled by default on every execution of PowerShell this is a pain point for making use of Jupyter Notebooks going forward.

Using a simple example PowerShell code block like this when I have transcription enabled on pwsh via regkey
```powershell 
$processes = Get-process | Select Name,ID -Last 10
$processes
```

Results in this 
image

when I then close vscode and re-open it with transcription disabled via reg key it then returns as expected
image

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #15651

PowerShell [automatically adds 'Out-Default -Transcript' to the end of pipeline](https://github.com/PowerShell/PowerShell/blob/1f2dc26ab45d07ac0cd90b6a76af946d088d5243/src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs#L325-L335) when it's transcribing and invoked via API. When [`-Transcript`](https://github.com/PowerShell/PowerShell/blob/1f2dc26ab45d07ac0cd90b6a76af946d088d5243/src/System.Management.Automation/FormatAndOutput/out-console/OutConsole.cs#L46-L53) is specified, objects passed through are transcribed but [are not passed ahead to the host](https://github.com/PowerShell/PowerShell/blob/1f2dc26ab45d07ac0cd90b6a76af946d088d5243/src/System.Management.Automation/FormatAndOutput/out-console/ConsoleLineOutput.cs#L337-L343).

The PowerShell sub-kernel actually already adds `Out-Default` to pass output to host, however, [we have to use `Out-Default2` as the name](https://github.com/dotnet/interactive/blob/09d6307ddaea52ea39c41abfa980fd3dce9a25d6/src/Microsoft.DotNet.Interactive.PowerShell/PowerShellKernel.cs#L63-L68) due to a limitation in the native command processor. Since we are using `Out-Default2`, PowerShell believes it doesn't have the `Out-Default` command at the end, and thus adds `Out-Default -Transcript` automatically, which prevents sending anything to the host and hence you don't see output from PowerShell sub-kernel when the transcription is turned on.

This needs to be fixed in the `InvokeHelper()` method, to not just check for the `Out-Default` name, but also check whether the `ImplementingType` is `typeof(OutDefaultCommand)`.

This PR also refactors the code a bit, to calculate `needToAddOutDefault` only if PowerShell is transcribing.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

**Review by PaulHigin — APPROVED** [review]
LGTM

**Review by iSazonov — APPROVED** [review]

File: src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs [hunk 1]
```diff
@@ -279,54 +276,53 @@ private void SetupInvokeThread(Thread invokeThread, bool changeName)
...
                             // Transcribe scripts, unless they are the pulse pipeline.
-                            this.Runspace.GetExecutionContext.EngineHostInterface.UI.TranscribeCommand(command.CommandText, null);
+                            Runspace.GetExecutionContext.EngineHostInterface.UI.TranscribeCommand(command.CommandText, invocation: null);
                         }
+                    }
+
+                    if (Runspace.GetExecutionContext.EngineHostInterface.UI.IsTranscribing)
+                    {
+                        bool needToAddOutDefault = true;
+                        Command lastCommand = Commands[Commands.Count - 1];
```
Comment (PaulHigin) [inline src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs:304]: Actually, thinking about this some more, this assumes that commands are piped together so that only the last one requires 'Out-Default' appended.  But what if the commands include statement separators?  It seems like 'Out-Default' would have to go at the end of those.

Please add a comment that illustrates when 'Out-Default -Transcribe' is needed.

**Review by PaulHigin — CHANGES_REQUESTED** [review]

File: src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs (hunk 1 above)
Comment (vexx32) [reply src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs:304]: I think if the commands include statement separators they'd be considered a completely distinct pipeline, wouldn't they?

Comment (daxian-dbw) [reply src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs:304]: Right, they would be considered distinct pipelines. Take `a | b; c` as an instance, initially there will be one pipeline processor (1) with one script block command `{ a | b; c }`, while executing that pipeline, another pipeline processor (2) is created with the commands `a` and `b`, after (2) finishes, another pipeline (3) is created for the command `c`.

Comment (PaulHigin) [reply src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs:304]: Ok, thanks.  Just wanted to check.

**Review by PaulHigin — APPROVED** [review]

**Comment by daxian-dbw** [comment]
BackPort-7.1.x-Consider context: this issue causes the PowerShell sub-kernel in .NET interactive to not work with `Start-Transcript`. Once the transcribing starts, a user of PowerShell notebook won't be able to see any output when running commands in the notebook.

**Comment by daxian-dbw** [comment]
@adityapatwardhan Can you please review and see if we can merge this one?

**Review by adityapatwardhan — APPROVED** [review]
